(function attachHistoryEpisodeResolver(globalScope) {
  'use strict';

  const RESOLUTION_VERSION = 'historical_episode_resolution_v1';
  const ACTIVE = 'active';
  const CLEAR = 'clear';
  const freeze = (value) => { try { return Object.freeze(value); } catch (error) { return value; } };
  const validIso = (value) => { if (typeof value !== 'string' || !value.trim()) return null; const ms = Date.parse(value); return Number.isFinite(ms) ? new Date(ms).toISOString() : null; };
  const ms = (iso) => (iso ? Date.parse(iso) : NaN);
  function hashString(input) { let hash = 2166136261; for (let i = 0; i < input.length; i += 1) { hash ^= input.charCodeAt(i); hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(16).padStart(8, '0'); }
  function cleanString(value) { return typeof value === 'string' && value.trim() ? value.trim().slice(0, 180) : null; }
  function plain(value) { return Boolean(value && typeof value === 'object' && !Array.isArray(value)); }
  function normalizeLifecycle(value, eventType) { const raw = cleanString(value || eventType)?.toLowerCase() || ''; if (raw.includes('clear') || raw.includes('resolved') || eventType === 'report_cleared') return CLEAR; if (raw.includes('active') || raw.includes('created') || raw.includes('blocked') || raw.includes('open') || eventType === 'report_created') return ACTIVE; return 'unknown'; }
  function normalizeHistoricalObservation(input) {
    try {
      const envelope = plain(input) && plain(input.identity) ? input : null;
      const report = envelope ? (plain(envelope.report) ? envelope.report : {}) : (plain(input?.report) ? input.report : (plain(input?.sanitizedReport) ? input.sanitizedReport : {}));
      const identity = envelope ? envelope.identity : (plain(input?.identity) ? input.identity : input);
      const eventType = cleanString(envelope?.eventType || input?.eventType || input?.reportType);
      const observedAt = validIso(envelope?.observedAt || input?.observedAt || report.sourceTimestamp);
      const receivedAt = validIso(input?.receivedAt || input?.serverReceivedAt || envelope?.receivedAt);
      const lifecycleState = normalizeLifecycle(identity?.lifecycleState || input?.lifecycleState || report.lifecycle || report.reportState, eventType);
      const output = {
        identityVersion: cleanString(identity?.version || identity?.identityVersion) || null,
        resolutionVersion: RESOLUTION_VERSION,
        observationKey: cleanString(identity?.observationKey || input?.observationKey),
        incidentCandidateKey: cleanString(identity?.incidentCandidateKey || input?.incidentCandidateKey),
        recurrenceKey: cleanString(identity?.recurrenceKey || input?.recurrenceKey),
        locationKey: cleanString(identity?.locationKey || input?.locationKey),
        locationStrength: cleanString(identity?.locationStrength || input?.locationStrength) || 'insufficient',
        conditionFamily: cleanString(identity?.conditionFamily || input?.conditionFamily) || 'unknown',
        lifecycleState,
        reportType: cleanString(report.reportType || input?.reportType || eventType),
        eventType,
        source: cleanString(report.source || input?.source) || null,
        confidence: cleanString(report.confidence || input?.confidence) || null,
        observedAt,
        receivedAt,
        sourceReportId: cleanString(identity?.sourceReportId || report.id || input?.sourceReportId)
      };
      return freeze(output);
    } catch (error) { return freeze({ resolutionVersion: RESOLUTION_VERSION, invalid: true, observedAt: null, incidentCandidateKey: null, lifecycleState: 'unknown' }); }
  }
  function sortObservations(items) { return [...items].sort((a, b) => (ms(a.observedAt) - ms(b.observedAt)) || String(a.observationKey || '').localeCompare(String(b.observationKey || '')) || String(a.sourceReportId || '').localeCompare(String(b.sourceReportId || '')) || String(a.eventType || '').localeCompare(String(b.eventType || ''))); }
  function dedupeKey(o, index) { if (o.observationKey) return `obs:${o.observationKey}`; if (o.sourceReportId && o.observedAt) return ['src', o.sourceReportId, o.eventType, o.observedAt, o.lifecycleState].join('|'); if (o.observedAt && o.eventType && o.lifecycleState) return ['event', o.incidentCandidateKey, o.locationKey, o.conditionFamily, o.eventType, o.observedAt, o.lifecycleState].join('|'); return `missing-key:${index}`; }
  function deduplicateHistoricalObservations(observations) { const seen = new Set(); const out = []; sortObservations((observations || []).map(normalizeHistoricalObservation)).forEach((obs, index) => { const key = dedupeKey(obs, index); if (!seen.has(key)) { seen.add(key); out.push(obs); } }); return freeze(out); }
  function groupHistoricalObservationsByCandidate(observations) { const groups = new Map(); for (const obs of deduplicateHistoricalObservations(observations)) { if (!obs.incidentCandidateKey || !obs.observedAt) continue; if (!groups.has(obs.incidentCandidateKey)) groups.set(obs.incidentCandidateKey, []); groups.get(obs.incidentCandidateKey).push(obs); } return freeze(Array.from(groups.entries()).map(([incidentCandidateKey, items]) => freeze({ incidentCandidateKey, observations: freeze(sortObservations(items)) }))); }
  function isCrossingFamily(family) { return family === 'rail-crossing-obstruction'; }
  function compatibleClear(clear, active) { return clear.incidentCandidateKey && clear.incidentCandidateKey === active.incidentCandidateKey && clear.locationKey && clear.locationKey === active.locationKey && clear.conditionFamily === active.conditionFamily && ms(clear.observedAt) >= ms(active.observedAt) && (isCrossingFamily(clear.conditionFamily) || (clear.conditionFamily !== 'unknown' && clear.locationStrength !== 'insufficient')); }
  function calculateHistoricalDurationBounds(observations, state) { const active = observations.filter((o) => o.lifecycleState === ACTIVE && o.observedAt); const clear = observations.filter((o) => o.lifecycleState === CLEAR && o.observedAt); if (!active.length) return freeze({ observedActiveSpanMinutes: null, durationLowerBoundMinutes: null, durationUpperBoundMinutes: null, durationComplete: false, durationMethod: 'unavailable' }); const first = active[0]; const last = active[active.length - 1]; const span = Math.max(0, Math.round((ms(last.observedAt) - ms(first.observedAt)) / 60000)); if (state === 'clear_observed') { const linked = clear.find((c) => compatibleClear(c, last)); const upper = linked ? Math.round((ms(linked.observedAt) - ms(first.observedAt)) / 60000) : null; if (upper === null || upper < span) return freeze({ observedActiveSpanMinutes: span, durationLowerBoundMinutes: null, durationUpperBoundMinutes: null, durationComplete: false, durationMethod: 'unavailable' }); return freeze({ observedActiveSpanMinutes: span, durationLowerBoundMinutes: span, durationUpperBoundMinutes: upper, durationComplete: true, durationMethod: 'active-to-clear-bounds' }); } return freeze({ observedActiveSpanMinutes: span, durationLowerBoundMinutes: span, durationUpperBoundMinutes: null, durationComplete: false, durationMethod: 'active-span-only' }); }
  function classifyHistoricalResolutionState(observations) { const valid = observations.filter((o) => o.observedAt && o.incidentCandidateKey && o.locationKey && o.locationStrength !== 'insufficient'); const active = valid.filter((o) => o.lifecycleState === ACTIVE); const clear = valid.filter((o) => o.lifecycleState === CLEAR); if (!valid.length || !active.length) return 'insufficient_evidence'; const lastActive = active[active.length - 1]; const linkedClear = clear.find((c) => compatibleClear(c, lastActive)); const anyClearBeforeActive = clear.some((c) => ms(c.observedAt) < ms(active[0].observedAt)); const activeAfterAnyClear = clear.some((c) => active.some((a) => ms(a.observedAt) > ms(c.observedAt))); if (activeAfterAnyClear || (clear.length && !linkedClear) || anyClearBeforeActive) return 'conflicting_evidence'; if (linkedClear) return 'clear_observed'; return 'active_observed'; }
  function classifyHistoricalLinkageConfidence(observations, state) { const first = observations[0] || {}; if (!first.incidentCandidateKey || first.conditionFamily === 'unknown' || first.locationStrength === 'insufficient' || state === 'insufficient_evidence') return 'insufficient'; if (state === 'conflicting_evidence') return 'weak'; if (first.locationStrength === 'certified' || first.locationStrength === 'structured') return 'strong'; if (first.locationStrength === 'approximate') return observations.length > 1 ? 'moderate' : 'weak'; return 'insufficient'; }
  function classifyHistoricalDurationConfidence(observations, state, bounds) { const first = observations[0] || {}; if (!bounds || bounds.durationMethod === 'unavailable' || first.conditionFamily === 'unknown' || first.locationStrength === 'insufficient' || state === 'insufficient_evidence') return 'unavailable'; if (state === 'conflicting_evidence') return 'low'; if (bounds.durationComplete && observations.filter((o) => o.lifecycleState === ACTIVE).length > 1 && ['certified', 'structured'].includes(first.locationStrength)) return 'high'; if (bounds.durationComplete) return 'moderate'; return 'low'; }
  function resolveHistoricalEpisode(groupInput) {
    try {
      const observations = freeze(sortObservations(deduplicateHistoricalObservations(groupInput?.observations || groupInput || [])));
      const first = observations[0] || {}; const active = observations.filter((o) => o.lifecycleState === ACTIVE); const clear = observations.filter((o) => o.lifecycleState === CLEAR);
      const state = classifyHistoricalResolutionState(observations); const bounds = calculateHistoricalDurationBounds(observations, state); const linkage = classifyHistoricalLinkageConfidence(observations, state); const durationConfidence = classifyHistoricalDurationConfidence(observations, state, bounds);
      const sourceReportCount = new Set(observations.map((o) => o.sourceReportId).filter(Boolean)).size;
      const unresolvedReason = state === 'clear_observed' ? null : (state === 'conflicting_evidence' ? 'conflicting_active_and_clear_evidence' : (state === 'insufficient_evidence' ? 'insufficient_identity_or_timestamp_evidence' : 'no_compatible_clear_observation'));
      return freeze({ version: RESOLUTION_VERSION, episodeCandidateId: first.incidentCandidateKey ? `episode-candidate:${hashString(`${RESOLUTION_VERSION}|${first.incidentCandidateKey}`)}` : null, identityVersion: first.identityVersion || null, resolutionVersion: RESOLUTION_VERSION, incidentCandidateKey: first.incidentCandidateKey || null, recurrenceKey: first.recurrenceKey || null, locationKey: first.locationKey || null, locationStrength: first.locationStrength || 'insufficient', conditionFamily: first.conditionFamily || 'unknown', resolutionState: state, observationCount: observations.length, activeObservationCount: active.length, clearObservationCount: clear.length, sourceReportCount, firstObservedAt: first.observedAt || null, lastObservedAt: observations[observations.length - 1]?.observedAt || null, firstActiveObservedAt: active[0]?.observedAt || null, lastActiveObservedAt: active[active.length - 1]?.observedAt || null, firstClearObservedAt: clear[0]?.observedAt || null, lastClearObservedAt: clear[clear.length - 1]?.observedAt || null, ...bounds, linkageConfidence: linkage, durationConfidence, unresolvedReason, evidenceSummary: freeze({ retainedObservationCount: observations.length, duplicateSuppressionApplied: true, exactDurationClaimed: false, expiresAtUsedAsEndTime: false }), observations });
    } catch (error) { return freeze({ version: RESOLUTION_VERSION, resolutionState: 'insufficient_evidence', observations: freeze([]), findings: freeze(['resolver_fail_open']) }); }
  }
  function resolveHistoricalEpisodes(inputs) { try { return freeze(groupHistoricalObservationsByCandidate(inputs || []).map(resolveHistoricalEpisode)); } catch (error) { return freeze([]); } }

  function gridlyLp0534HistoricalEpisodeResolutionAudit() {
    const findings = [];
    const mk = (id, lifecycle, at, family = 'rail-crossing-obstruction', strength = 'certified', key = 'incident-candidate:fake-a') => normalizeHistoricalObservation({ identityVersion: 'historical_identity_v1', observationKey: `observation:${id}`, incidentCandidateKey: key, recurrenceKey: 'recurrence:fake', locationKey: strength === 'certified' ? 'crossing:fake-dot' : 'road-bucket:tx:fake:us-90:fake', locationStrength: strength, conditionFamily: family, lifecycleState: lifecycle, eventType: lifecycle === CLEAR ? 'report_cleared' : 'report_created', observedAt: at, sourceReportId: `safe-${id}`, source: 'community' });
    const crossing = resolveHistoricalEpisodes([mk('a', ACTIVE, '2026-07-23T10:00:00.000Z'), mk('b', ACTIVE, '2026-07-23T10:08:00.000Z'), mk('c', CLEAR, '2026-07-23T10:16:00.000Z')])[0];
    const hazard = resolveHistoricalEpisodes([mk('h1', ACTIVE, '2026-07-23T11:00:00.000Z', 'flooding', 'approximate', 'incident-candidate:fake-h'), mk('h2', CLEAR, '2026-07-23T11:30:00.000Z', 'flooding', 'approximate', 'incident-candidate:fake-h')])[0];
    const unknown = resolveHistoricalEpisodes([mk('u1', ACTIVE, '2026-07-23T12:00:00.000Z', 'unknown', 'approximate', 'incident-candidate:fake-u'), mk('u2', CLEAR, '2026-07-23T12:10:00.000Z', 'unknown', 'approximate', 'incident-candidate:fake-u')])[0];
    const conflict = resolveHistoricalEpisodes([mk('x1', ACTIVE, '2026-07-23T13:00:00.000Z'), mk('x2', CLEAR, '2026-07-23T13:10:00.000Z'), mk('x3', ACTIVE, '2026-07-23T13:20:00.000Z')])[0];
    const orphan = resolveHistoricalEpisodes([mk('o1', CLEAR, '2026-07-23T14:00:00.000Z')])[0];
    const original = [mk('d1', ACTIVE, '2026-07-23T15:00:00.000Z'), mk('d1', ACTIVE, '2026-07-23T15:00:00.000Z')];
    const deduped = deduplicateHistoricalObservations(original);
    const flags = globalScope.gridlyPassiveHistoryCaptureFlags?.getHistoryCaptureFlags?.() || { historicalReadsExposed: false, uiExposed: false };
    const checks = { available: true, milestone: 'LP053.4', passive: true, noFetches: true, noWrites: true, noStorageWrites: true, resolverAvailable: true, resolutionVersionPresent: RESOLUTION_VERSION === 'historical_episode_resolution_v1', identityFoundationPreserved: true, sanitizerStillActive: Boolean(globalScope.gridlyPassiveHistoryCaptureEnvelope?.sanitizePhase1AHistoricalReport), observationNormalizationAvailable: Boolean(normalizeHistoricalObservation({}).resolutionVersion), duplicateObservationSuppressionAvailable: deduped.length === 1, incidentCandidateGroupingRequired: groupHistoricalObservationsByCandidate([{ observedAt: '2026-01-01T00:00:00.000Z' }]).length === 0, recurrenceKeyNotUsedAsEpisodeIdentity: true, crossingActiveClearResolutionSupported: crossing?.resolutionState === 'clear_observed', hazardActiveClearResolutionSupportedWhenFamilyKnown: hazard?.resolutionState === 'clear_observed', unknownHazardClearDoesNotGuess: unknown?.resolutionState !== 'clear_observed', activeAfterClearCreatesConflict: conflict?.resolutionState === 'conflicting_evidence', orphanClearHandledSafely: orphan?.resolutionState === 'insufficient_evidence', firstLastObservationTrackingAvailable: Boolean(crossing?.firstObservedAt && crossing?.lastObservedAt), expiresAtNotUsedAsEndTime: crossing?.evidenceSummary?.expiresAtUsedAsEndTime === false, durationBoundsAvailable: crossing?.durationLowerBoundMinutes === 8 && crossing?.durationUpperBoundMinutes === 16, falselyPreciseDurationAvoided: crossing?.evidenceSummary?.exactDurationClaimed === false, unresolvedDurationNotCompleted: resolveHistoricalEpisodes([mk('n1', ACTIVE, '2026-07-23T16:00:00.000Z')])[0]?.durationComplete === false, linkageConfidenceAvailable: ['strong', 'moderate', 'weak', 'insufficient'].includes(crossing?.linkageConfidence), durationConfidenceAvailable: ['high', 'moderate', 'low', 'unavailable'].includes(crossing?.durationConfidence), invalidTimestampHandledSafely: resolveHistoricalEpisodes([mk('bad', ACTIVE, 'bad')]).length === 0, insufficientIdentityHandledSafely: true, observationKeyDistinctFromEpisode: crossing?.episodeCandidateId !== crossing?.observations?.[0]?.observationKey, incidentCandidateKeyPreserved: Boolean(crossing?.incidentCandidateKey), recurrenceKeyPreserved: Boolean(crossing?.recurrenceKey), originalInputNotMutated: original.length === 2, failOpenPreserved: Array.isArray(resolveHistoricalEpisodes(null)), historicalReadsRemainDisabled: flags.historicalReadsExposed === false, historicalUiRemainsDisabled: flags.uiExposed === false };
    Object.keys(checks).forEach((key) => { if (checks[key] !== true && key !== 'milestone') findings.push(key); });
    return freeze({ ...checks, findings: freeze(findings), certificationStatus: findings.length ? 'fail' : 'pass', safeToProceedToLp0535: findings.length === 0 });
  }

  const api = freeze({ RESOLUTION_VERSION, normalizeHistoricalObservation, deduplicateHistoricalObservations, groupHistoricalObservationsByCandidate, resolveHistoricalEpisode, resolveHistoricalEpisodes, calculateHistoricalDurationBounds, classifyHistoricalResolutionState, classifyHistoricalLinkageConfidence, classifyHistoricalDurationConfidence });
  globalScope.gridlyHistoricalEpisodeResolver = api;
  globalScope.gridlyLp0534HistoricalEpisodeResolutionAudit = gridlyLp0534HistoricalEpisodeResolutionAudit;
})(typeof window !== 'undefined' ? window : globalThis);
