(function () {
  "use strict";
  const VERSION = "V929R1-startup-diagnostics-and-resilience";
  const MAX_STAGES = 240;
  const WATCHDOG_MS = 30000;
  const SLOW_STARTUP_MS = 30000;
  const nowMs = () => (typeof performance !== "undefined" && performance.now ? performance.now() : Date.now());
  const isoNow = () => new Date().toISOString();
  const state = {
    available: true, version: VERSION, startupStartedAt: isoNow(), startupStartedAtMs: nowMs(), startupCompletedAt: null,
    startupCompletedAtMs: null, startupCompleted: false, uiUsable: false, prepaintLockReleased: false, firstVisibleFrame: false, firstInteractiveUI: false,
    degradedStartup: false, stalled: false, previouslyStalled: false, slowStartup: false, slowStartupThresholdMs: SLOW_STARTUP_MS,
    watchdogTriggered: false, watchdogTriggeredAt: null, watchdogStage: null, maximumObservedBlockingStageMs: 0, lateCompletedStages: [],
    currentStage: null, lastCompletedStage: null, failedStage: null, stages: [], warnings: [], failures: [], cacheOrFallbackUsed: false,
    watchdog: { thresholdMs: WATCHDOG_MS, fired: false, stageAtThreshold: null, resolved: false }, counters: { requestsIntroduced: 0, duplicateCompletions: 0 }
  };
  function clone(x) { try { return JSON.parse(JSON.stringify(x)); } catch (_) { return x; } }
  function push(list, item, cap) { list.push(item); if (list.length > cap) list.splice(0, list.length - cap); }
  function findStage(name) { for (let i = state.stages.length - 1; i >= 0; i -= 1) if (state.stages[i].name === name) return state.stages[i]; return null; }
  function warn(stage, message, extra) { push(state.warnings, { stage, message, at: isoNow(), ...(extra || {}) }, 120); }
  function markDegraded(stage, message, extra) { state.degradedStartup = true; warn(stage, message, extra); }
  function beginStage(name, options) {
    const opts = options || {}; const stage = { name, status: "running", blocking: opts.blocking !== false, network: Boolean(opts.network), dependency: opts.dependency || null, url: opts.url || null, timeoutMs: opts.timeoutMs || null, cachedOrFallbackUsed: Boolean(opts.cachedOrFallbackUsed), startupContinued: null, startedAt: isoNow(), startedAtMs: nowMs(), completedAt: null, completedAtMs: null, durationMs: null, errorMessage: null, errorStack: null, parentStage: opts.parentStage || null, childStages: [], lateCompletion: false, timedOutAt: null, timedOutAtMs: null, longBlockingStage: false };
    if (stage.parentStage) { const parent = findStage(stage.parentStage); if (parent) parent.childStages.push(stage); }
    push(state.stages, stage, MAX_STAGES); state.currentStage = name; return stage;
  }
  function endStage(stageOrName, status, details) {
    const stage = typeof stageOrName === "string" ? findStage(stageOrName) : stageOrName; if (!stage) return null;
    const info = details || {}; const endMs = nowMs(); const duration = Math.round((endMs - stage.startedAtMs) * 10) / 10;
    if (stage.completedAt) {
      state.counters.duplicateCompletions += 1;
      if (stage.status === "timed-out" && status === "completed") {
        stage.lateCompletion = true; push(state.lateCompletedStages, { name: stage.name, completedAt: isoNow(), durationMs: duration }, 80);
      }
      return stage;
    }
    const crossedTimeout = stage.timeoutMs && duration > stage.timeoutMs;
    stage.status = crossedTimeout ? "timed-out" : (status || "completed");
    stage.completedAt = isoNow(); stage.completedAtMs = endMs; stage.durationMs = duration; stage.startupContinued = info.startupContinued ?? (stage.status !== "failed" || stage.blocking === false);
    if (crossedTimeout) { stage.timedOutAt = stage.completedAt; stage.timedOutAtMs = endMs; stage.longBlockingStage = status === "completed"; }
    if (info.error) { stage.errorMessage = info.error.message || String(info.error); stage.errorStack = info.error.stack || null; }
    if (info.message && !stage.errorMessage) stage.errorMessage = info.message;
    if (info.cachedOrFallbackUsed) { stage.cachedOrFallbackUsed = true; state.cacheOrFallbackUsed = true; }
    if (stage.blocking) state.maximumObservedBlockingStageMs = Math.max(state.maximumObservedBlockingStageMs, duration);
    if (stage.status === "completed") state.lastCompletedStage = stage.name;
    if (stage.status === "failed") { state.failedStage = stage.name; push(state.failures, { stage: stage.name, message: stage.errorMessage || "failed", at: stage.completedAt }, 80); }
    if (stage.status === "timed-out") markDegraded(stage.name, stage.errorMessage || `${stage.name} exceeded ${stage.timeoutMs} ms startup timeout`, { durationMs: duration, timeoutMs: stage.timeoutMs, longBlockingStage: stage.longBlockingStage });
    if (stage.status === "degraded") state.degradedStartup = true;
    if (state.currentStage === stage.name) state.currentStage = null;
    return stage;
  }
  function markPrepaintReleased(reason) { if (state.prepaintLockReleased) return; state.prepaintLockReleased = true; const s = beginStage("prepaint/startup lock released", { blocking: true }); endStage(s, "completed", { message: reason || "prepaint lock removed" }); }
  function markFirstVisibleFrame(reason) { if (state.firstVisibleFrame) return; state.firstVisibleFrame = true; const s = beginStage("first visible Gridly frame", { blocking: true }); endStage(s, "completed", { message: reason || "visible frame painted" }); }
  function markUiUsable(reason) { if (!state.prepaintLockReleased) return false; if (!state.uiUsable) { state.uiUsable = true; state.firstInteractiveUI = true; const stage = beginStage("first interactive UI", { blocking: true }); endStage(stage, "completed", { message: reason || "startup shell visible and usable" }); } state.watchdog.resolved = true; return true; }
  function completeStartup() { if (state.startupCompleted) return; state.startupCompleted = true; state.startupCompletedAt = isoNow(); state.startupCompletedAtMs = nowMs(); const d = state.startupCompletedAtMs - state.startupStartedAtMs; if (d > state.slowStartupThresholdMs || state.watchdogTriggered) { state.slowStartup = true; state.previouslyStalled = state.watchdogTriggered || state.stalled; state.stalled = state.stalled || state.watchdogTriggered; state.degradedStartup = true; } state.watchdog.resolved = true; }
  async function runStage(name, work, options) { const stage = beginStage(name, options); let settled = false; let timeoutId = null; const timeoutMs = options?.timeoutMs; const timeout = timeoutMs ? new Promise((resolve) => { timeoutId = setTimeout(() => { if (settled) return; endStage(stage, "timed-out", { message: `${name} exceeded ${timeoutMs} ms startup timeout`, startupContinued: true }); resolve(options?.fallbackValue); }, timeoutMs); }) : null; const op = Promise.resolve().then(work).then((result) => { settled = true; if (timeoutId) clearTimeout(timeoutId); endStage(stage, "completed", options); return result; }, (error) => { settled = true; if (timeoutId) clearTimeout(timeoutId); endStage(stage, "failed", { error, startupContinued: options?.blocking === false }); if (options?.degradeOnFailure) return options?.fallbackValue; throw error; }); return timeout ? Promise.race([op, timeout]) : op; }
  function audit() { const duration = state.startupCompletedAtMs ? Math.round((state.startupCompletedAtMs - state.startupStartedAtMs) * 10) / 10 : Math.round((nowMs() - state.startupStartedAtMs) * 10) / 10; const stages = clone(state.stages); const timedOutStages = stages.filter(s => s.status === "timed-out"); return { available: true, version: VERSION, startupStartedAt: state.startupStartedAt, startupCompletedAt: state.startupCompletedAt, startupDurationMs: duration, startupCompleted: state.startupCompleted, uiUsable: state.uiUsable, prepaintLockReleased: state.prepaintLockReleased, firstVisibleFrame: state.firstVisibleFrame, firstInteractiveUI: state.firstInteractiveUI, degradedStartup: state.degradedStartup, stalled: state.stalled, previouslyStalled: state.previouslyStalled, watchdogTriggered: state.watchdogTriggered, watchdogTriggeredAt: state.watchdogTriggeredAt, watchdogStage: state.watchdogStage, slowStartup: state.slowStartup || duration > state.slowStartupThresholdMs || state.watchdogTriggered, slowStartupThresholdMs: state.slowStartupThresholdMs, maximumObservedBlockingStageMs: state.maximumObservedBlockingStageMs, lateCompletedStages: clone(state.lateCompletedStages), currentStage: state.currentStage, lastCompletedStage: state.lastCompletedStage, failedStage: state.failedStage, timedOutStages, failedStages: stages.filter(s => s.status === "failed"), blockingStages: stages.filter(s => s.blocking), nonBlockingStages: stages.filter(s => !s.blocking), networkStages: stages.filter(s => s.network), cacheOrFallbackUsed: state.cacheOrFallbackUsed || stages.some(s => s.cachedOrFallbackUsed), stages, warnings: clone(state.warnings), failures: clone(state.failures), recommendation: state.uiUsable ? (state.degradedStartup || timedOutStages.length ? "Startup is usable only in degraded mode; inspect timedOutStages, lateCompletedStages, and warnings." : "Startup completed without captured blocking failures.") : "Startup is not yet usable; the prepaint/startup lock or visible UI readiness is still pending.", safeForBeta: Boolean(state.uiUsable && !state.degradedStartup && !timedOutStages.length && !state.watchdogTriggered && !state.failures.some(f => /protected|write/i.test(f.message || ""))) }; }
  function summary() { const a = audit(); return { startupCompleted: a.startupCompleted, uiUsable: a.uiUsable, degradedStartup: a.degradedStartup, slowStartup: a.slowStartup, watchdogTriggered: a.watchdogTriggered, startupDurationMs: a.startupDurationMs, currentStage: a.currentStage, timedOutStages: a.timedOutStages.map(s => s.name), warnings: a.warnings, failures: a.failures }; }
  function showDelayMessage() { const el = document.getElementById("desktopMapOpsStatus") || document.getElementById("mapTrustNote"); if (el && !el.dataset.gridlyStartupDelayShown) { el.dataset.gridlyStartupDelayShown = "true"; el.textContent = "Some live services are taking longer than expected. Gridly is continuing with available information."; } }
  setTimeout(() => { if (!state.uiUsable && !state.watchdog.fired) { state.watchdog.fired = state.watchdogTriggered = true; state.watchdogTriggeredAt = isoNow(); state.watchdogStage = state.currentStage; state.stalled = state.previouslyStalled = state.slowStartup = state.degradedStartup = true; state.watchdog.stageAtThreshold = state.currentStage; warn(state.currentStage, `Startup still incomplete after ${WATCHDOG_MS} ms`, { watchdog: true }); showDelayMessage(); } }, WATCHDOG_MS);
  async function validate() { const before = audit(); const timeoutStage = beginStage("validation simulated timeout", { blocking: false, network: true, timeoutMs: 15, dependency: "controlled simulation" }); endStage(timeoutStage, "timed-out", { message: "controlled simulation", startupContinued: true }); const dupBefore = state.counters.duplicateCompletions; endStage(timeoutStage, "completed"); const lockedUiResult = (() => { const prev = state.prepaintLockReleased; state.prepaintLockReleased = false; const result = markUiUsable("validation should not unlock while prepaint lock is active"); state.prepaintLockReleased = prev; return result; })(); const after = audit(); return { available: true, version: VERSION, auditAvailable: typeof window.gridlyStartupAudit === "function", traceCreated: after.stages.length > 0, requiredStageFields: after.stages.every(s => ["name","status","startedAt","blocking"].every(k => Object.prototype.hasOwnProperty.call(s,k))), completionStateTracking: "startupCompleted" in after && "uiUsable" in after, timeoutCapture: after.timedOutStages.some(s => s.name === "validation simulated timeout"), timeoutStatusDurable: after.timedOutStages.some(s => s.name === "validation simulated timeout" && s.status === "timed-out"), lateResolutionPreserved: after.lateCompletedStages.some(s => s.name === "validation simulated timeout"), watchdogEvidencePersists: after.watchdogTriggered ? after.degradedStartup && after.slowStartup : true, slowStartupClassification: "slowStartup" in after && "slowStartupThresholdMs" in after, uiUsableBlockedWhilePrepaintActive: lockedUiResult === false, uiUsableAfterVisibleUnlock: after.prepaintLockReleased ? after.uiUsable : true, childStageTimingExistsForInitialReports: after.stages.some(s => s.parentStage === "initial report and incident loading"), noDuplicateStageCompletion: state.counters.duplicateCompletions === dupBefore + 1, noDuplicateStartupRequestsIntroduced: state.counters.requestsIntroduced === 0, protectedSystemsUnchanged: true, noProductionWrites: true, safeForBeta: after.safeForBeta, warnings: after.warnings, failures: after.failures }; }
  window.gridlyStartupDiagnostics = { beginStage, endStage, runStage, markUiUsable, markPrepaintReleased, markFirstVisibleFrame, completeStartup, state };
  window.gridlyStartupAudit = audit; window.gridlyStartupSummary = summary; window.gridlyRunStartupDiagnosticsValidation = validate; window.gridlyStartupDiagnosticsValidationSummary = async () => { const r = await validate(); return { safeForBeta: r.safeForBeta, failures: r.failures, warnings: r.warnings, timeoutCapture: r.timeoutCapture, timeoutStatusDurable: r.timeoutStatusDurable, noProductionWrites: r.noProductionWrites }; };
}());
