(function initGridlyLp044DriveTexasCommunityAuthorityInventory(globalScope) {
  if (typeof require === "function" && !globalScope.gridlyQualifyDriveTexasGeometryAuthority) { try { globalScope.gridlyQualifyDriveTexasGeometryAuthority = require("./gridlyDriveTexasGeometryAuthority.js").qualify; } catch (_e) {} }
  "use strict";
  if (!globalScope || typeof globalScope !== "object") return;

  const MILESTONE = "LP044";
  const EARTH_RADIUS_MILES = 3958.7613;
  const ID_KEYS = Object.freeze(["eventId", "event_id", "sourceId", "providerSourceId", "globalId", "GLOBALID", "id", "incidentId"]);
  const NESTED_ID_OWNERS = Object.freeze(["raw", "rawRecord", "source", "sourceRecord", "sourceMetadata", "sourceTrace", "properties", "attributes", "providerRecord"]);

  function freeze(v) { return v && typeof v === "object" ? Object.freeze(v) : v; }
  function arr(v) { return Array.isArray(v) ? v : []; }
  function clone(v) { try { return JSON.parse(JSON.stringify(v)); } catch (_e) { return null; } }
  function txt(v) { return v == null ? "" : String(v).trim(); }
  function idText(v) { return txt(v).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
  function num(v) { const n = Number(v); return Number.isFinite(n) ? n : null; }
  function round(v, d = 3) { return Number.isFinite(v) ? Number(v.toFixed(d)) : null; }
  function inTexas(lat, lng) { return Number.isFinite(lat) && Number.isFinite(lng) && lat >= 25.5 && lat <= 36.6 && lng >= -106.7 && lng <= -93.2; }
  function pair(p) { if (!Array.isArray(p) || p.length < 2) return null; const a = num(p[0]), b = num(p[1]); if (!Number.isFinite(a) || !Number.isFinite(b)) return null; if (inTexas(b, a)) return [a, b]; if (inTexas(a, b)) return [b, a]; return null; }
  function stableHash(value) { const text = JSON.stringify(value); let h = 2166136261; for (let i = 0; i < text.length; i += 1) { h ^= text.charCodeAt(i); h = Math.imul(h, 16777619); } return (h >>> 0).toString(36); }
  function first(record, keys) { for (const k of keys) { const value = record && record[k]; if (txt(value)) return value; } return null; }
  function nestedFirst(record, keys) { for (const key of keys) { const direct = txt(record?.[key]); if (direct) return { value: direct, key, nested: false }; } for (const owner of NESTED_ID_OWNERS) { const node = record?.[owner]; if (!node || typeof node !== "object") continue; for (const key of keys) { const value = txt(node[key]); if (value) return { value, key: `${owner}.${key}`, nested: true }; } } return null; }
  function canonicalId(prefix, value) { const raw = txt(value); if (!raw) return null; if (/^(event|provider|fallback|unresolved):/i.test(raw)) return raw; return `${prefix}:${raw}`; }
  function canonicalIdentity(record, index) { const event = nestedFirst(record, ["eventId", "event_id"]); if (event) return { sourceId: canonicalId("event", event.value), sourceIdentityValue: event.value, sourceIdentityField: event.key, sourceIdentityMethod: event.nested ? "nested_event_id" : "event_id", missing: false }; const stable = nestedFirst(record, ID_KEYS.slice(2)); if (stable) return { sourceId: canonicalId("provider", stable.value), sourceIdentityValue: stable.value, sourceIdentityField: stable.key, sourceIdentityMethod: stable.nested ? "nested_stable_provider_source_id" : "stable_provider_source_id", missing: false }; const material = { category: record?.category, headline: record?.headline || record?.title, routeName: record?.routeName || record?.roadway, description: record?.description || record?.summary, startTime: record?.startTime || record?.beginDate, endTime: record?.endTime || record?.endDate, geometry: record?.sourceGeometry || record?.__geometry || record?.geometry || record?.roadwayGeometry || record?.routeGeometry, coordinates: record?.coordinates, latitude: record?.latitude, longitude: record?.longitude, index }; return { sourceId: `unresolved:${stableHash(material)}`, sourceIdentityValue: null, sourceIdentityField: null, sourceIdentityMethod: "deterministic_unresolved_source_identity", missing: true }; }
  function trustedGeometry(record) { const g = record?.sourceGeometry || record?.__geometry || record?.geometry || record?.roadwayGeometry || record?.routeGeometry; if (!g || typeof g !== "object") return null; if (g.type === "Point") { const p = pair(g.coordinates); return p ? { type: "Point", coordinates: p } : null; } if (g.type === "LineString") { const c = arr(g.coordinates).map(pair); return c.length >= 2 && c.every(Boolean) ? { type: "LineString", coordinates: c } : null; } if (g.type === "MultiLineString") { const lines = arr(g.coordinates).map((line) => arr(line).map(pair)); return lines.length && lines.every((line) => line.length >= 2 && line.every(Boolean)) ? { type: "MultiLineString", coordinates: lines } : null; } return null; }
  function coord(record) { const raw = record?.coordinates; let lat = num(record?.latitude ?? record?.lat ?? record?.y), lng = num(record?.longitude ?? record?.lng ?? record?.lon ?? record?.x); if (Array.isArray(raw)) { const p = pair(raw); if (p) { lat = p[1]; lng = p[0]; } } else if (raw && typeof raw === "object") { const a = num(raw.latitude ?? raw.lat ?? raw.y), b = num(raw.longitude ?? raw.lng ?? raw.lon ?? raw.x); if (inTexas(a, b)) { lat = a; lng = b; } else if (inTexas(b, a)) { lat = b; lng = a; } } return inTexas(lat, lng) ? { latitude: lat, longitude: lng } : null; }
  function points(g) { if (!g) return []; if (g.type === "Point") return [g.coordinates]; if (g.type === "LineString") return arr(g.coordinates); if (g.type === "MultiLineString") return arr(g.coordinates).flat(); return []; }
  function segments(g) { if (!g) return []; if (g.type === "Point") return []; if (g.type === "LineString") return arr(g.coordinates).slice(0, -1).map((p, i) => [p, g.coordinates[i + 1]]); if (g.type === "MultiLineString") return arr(g.coordinates).flatMap((line) => arr(line).slice(0, -1).map((p, i) => [p, line[i + 1]])); return []; }
  function bounds(g) { const ps = points(g); if (!ps.length) return null; return ps.reduce((b, p) => ({ minLongitude: Math.min(b.minLongitude, p[0]), maxLongitude: Math.max(b.maxLongitude, p[0]), minLatitude: Math.min(b.minLatitude, p[1]), maxLatitude: Math.max(b.maxLatitude, p[1]) }), { minLongitude: Infinity, maxLongitude: -Infinity, minLatitude: Infinity, maxLatitude: -Infinity }); }
  function hav(aLat, aLng, bLat, bLng) { const r = Math.PI / 180, dLat = (bLat - aLat) * r, dLng = (bLng - aLng) * r, s1 = Math.sin(dLat / 2), s2 = Math.sin(dLng / 2), a = s1 * s1 + Math.cos(aLat * r) * Math.cos(bLat * r) * s2 * s2; return 2 * EARTH_RADIUS_MILES * Math.atan2(Math.sqrt(a), Math.sqrt(Math.max(0, 1 - a))); }
  function pointSegMiles(lat, lng, a, b) { const latM = 69, lngM = Math.max(1, 69 * Math.cos(lat * Math.PI / 180)); const ax = (a[0] - lng) * lngM, ay = (a[1] - lat) * latM, bx = (b[0] - lng) * lngM, by = (b[1] - lat) * latM, dx = bx - ax, dy = by - ay, len = dx * dx + dy * dy, t = len > 0 ? Math.max(0, Math.min(1, (-(ax * dx + ay * dy)) / len)) : 0, x = ax + t * dx, y = ay + t * dy; return Math.sqrt(x * x + y * y); }
  function distGeomPoint(g, lat, lng) { if (!g) return Infinity; if (g.type === "Point") return hav(lat, lng, g.coordinates[1], g.coordinates[0]); let best = Infinity; segments(g).forEach((s) => { best = Math.min(best, pointSegMiles(lat, lng, s[0], s[1])); }); return best; }
  function normalizeCommunity(area, countyName) { const lat = num(area?.lat ?? area?.latitude ?? area?.center?.lat ?? area?.center?.latitude ?? area?.coordinates?.lat ?? area?.coordinates?.latitude); const lng = num(area?.lng ?? area?.lon ?? area?.longitude ?? area?.center?.lng ?? area?.center?.longitude ?? area?.coordinates?.lng ?? area?.coordinates?.longitude); const radiusMiles = num(area?.radiusMiles ?? area?.awarenessRadiusMiles ?? area?.radius); if (!area || area.countyWide || area.fallback || !Number.isFinite(lat) || !Number.isFinite(lng) || !Number.isFinite(radiusMiles)) return null; return { communityId: area.key || area.id || idText(area.label || area.storageValue), communityName: area.label || area.storageValue || area.value || area.key, countyId: area.countyId || null, countyName: countyName || area.countyName || null, latitude: lat, longitude: lng, radiusMiles }; }
  function communityList(input) { const direct = arr(input.communities).map((a) => normalizeCommunity(a)).filter(Boolean); if (direct.length) return direct.sort((a, b) => txt(a.countyId).localeCompare(txt(b.countyId)) || txt(a.communityName).localeCompare(txt(b.communityName))); const fromGroups = typeof globalScope.gridlyGetCountyGroupedAwarenessOptions === "function" ? arr(globalScope.gridlyGetCountyGroupedAwarenessOptions()).flatMap((group) => arr(group.communities).map((option) => { if (option?.countyWide || option?.fallback) return null; const resolved = typeof globalScope.resolveGridlyAwarenessArea === "function" ? globalScope.resolveGridlyAwarenessArea(option.value || option.label || option.key) : option; return normalizeCommunity(Object.assign({}, resolved || {}, option || {}, { countyId: (resolved || option || {}).countyId || group.countyId || group.countyValue }), group.countyLabel); })) : []; const defs = fromGroups.filter(Boolean); if (defs.length) return defs.sort((a, b) => txt(a.countyId).localeCompare(txt(b.countyId)) || txt(a.communityName).localeCompare(txt(b.communityName))); return arr(globalScope.GRIDLY_AWARENESS_AREA_DEFINITIONS).map((a) => normalizeCommunity(a, globalScope.GRIDLY_COUNTY_REGISTRY?.[a?.countyId]?.name)).filter(Boolean).sort((a, b) => txt(a.countyId).localeCompare(txt(b.countyId)) || txt(a.communityName).localeCompare(txt(b.communityName))); }
  function countyList(input) { if (Array.isArray(input.counties)) return input.counties.slice().sort((a, b) => txt(a.countyId).localeCompare(txt(b.countyId))); return Object.entries(globalScope.GRIDLY_COUNTY_REGISTRY || {}).map(([countyId, c]) => ({ countyId, countyName: c.name || countyId })).sort((a, b) => a.countyId.localeCompare(b.countyId)); }
  function sourceRecords(input) { if (Array.isArray(input.records)) return input.records; const c = globalScope.gridlyDriveTexasConnector, p = globalScope.gridlyDriveTexasProvider; return arr(c?.getAllNormalizedRecords?.()).length ? c.getAllNormalizedRecords() : arr(c?.getNormalizedRecords?.()).length ? c.getNormalizedRecords() : arr(p?.getNormalizedRecords?.()); }
  function production(input) { return input.productionSnapshot || (typeof globalScope.gridlyGetDriveTexasAuthoritySnapshot === "function" ? globalScope.gridlyGetDriveTexasAuthoritySnapshot(input) : null) || {}; }
  function classify(row) { if (row.duplicateSourceId) return "DUPLICATE_RECORD"; if (row.registryFailure) return "REGISTRY_UNAVAILABLE"; if (row.geographicStatus === "outside_gridly_coverage") return "OUTSIDE_GRIDLY_COVERAGE"; if (!row.geometryValid && row.geometryType !== "missing") return "INVALID_GEOMETRY_FALLBACK"; if (row.insideGridlyCoverage && !row.currentConsumerVisible) return "GEOGRAPHICALLY_RELEVANT_BUT_NOT_VISIBLE"; if (!row.insideGridlyCoverage && row.currentConsumerVisible) return "VISIBLE_WITHOUT_GEOGRAPHIC_AUTHORITY"; if (row.countyIdsIntersected.length && row.communityIntersectionCount === 0) return "COUNTY_MATCH_BUT_NO_COMMUNITY_INTERSECTION"; if (row.crossesMultipleCommunities && row.currentOwnershipMethod && !/multi|geometry/.test(row.currentOwnershipMethod)) return "MULTI_COMMUNITY_OWNERSHIP_COLLAPSED"; if (row.crossesMultipleCounties && row.currentOwnershipMethod && !/multi|geometry/.test(row.currentOwnershipMethod)) return "MULTI_COUNTY_OWNERSHIP_COLLAPSED"; return null; }


  function countRows(rows, predicate) { return rows.filter(predicate).length; }
  function summarizeCoverage(rows) { return { insideGridlyCoverage: countRows(rows, (r) => r.insideGridlyCoverage === true), outsideGridlyCoverage: countRows(rows, (r) => r.geographicStatus === "outside_gridly_coverage"), geographicallyUnresolved: countRows(rows, (r) => r.geographicStatus === "geographically_unresolved"), malformed: countRows(rows, (r) => r.geographicStatus === "malformed"), registryUnavailable: countRows(rows, (r) => r.geographicStatus === "registry_unavailable") }; }
  function summarizeDiscrepancies(rows) { return rows.reduce((m, r) => { if (r.discrepancyClassification) m[r.discrepancyClassification] = (m[r.discrepancyClassification] || 0) + 1; return m; }, {}); }
  function discrepancyProjection(row) { return { sourceId: row.sourceId, route: row.routeName, category: row.category, groundTruthCounties: row.countyNamesIntersected, groundTruthCommunities: row.communityNamesIntersected, currentOwnershipMethod: row.currentOwnershipMethod, currentEligibility: row.currentLp039Eligibility, currentRejectionReason: row.currentRejectionReason, classification: row.discrepancyClassification, firstProductionStageWhereCorrectGeographicRelationshipIsLost: row.firstProductionStageWhereLost }; }
  function summarizeCommunities(rows, comms, registryFailure) { return registryFailure ? [] : comms.map((cm) => { const hits = rows.filter((r) => r.communityIdsIntersected.includes(cm.communityId)); return { county: cm.countyName, community: cm.communityName, communityId: cm.communityId, intersectingDriveTexasRecordCount: hits.length, pointAuthorityRecordCount: countRows(hits, (r) => r.geometryType === "Point" || r.geographicResolutionMethod.includes("point")), lineStringAuthorityRecordCount: countRows(hits, (r) => r.geometryType === "LineString"), multiLineStringAuthorityRecordCount: countRows(hits, (r) => r.geometryType === "MultiLineString"), currentlyConsumerVisibleCount: countRows(hits, (r) => r.currentConsumerVisible === true), currentlyExcludedCount: countRows(hits, (r) => r.currentConsumerVisible !== true), categoriesRepresented: [...new Set(hits.map((r) => r.category).filter(Boolean))].sort(), routesRepresented: [...new Set(hits.map((r) => r.routeName).filter(Boolean))].sort(), sampleSourceIds: hits.slice(0, 10).map((r) => r.sourceId) }; }); }
  function summarizeCounties(rows, counties, comms, registryFailure) { const groupedCommunities = summarizeCommunities(rows, comms, registryFailure); return counties.map((cy) => { const hits = rows.filter((r) => r.countyIdsIntersected.includes(cy.countyId)); return { countyId: cy.countyId, countyName: cy.countyName, registryAvailable: !registryFailure, intersectingDriveTexasRecordCount: hits.length, recordsAssignedByGeometry: countRows(hits, (r) => r.geographicResolutionMethod === "trusted_complete_roadway_geometry"), recordsAssignedByPointFallback: countRows(hits, (r) => r.geographicResolutionMethod === "trusted_representative_point_fallback"), multiCountyRecordCount: countRows(hits, (r) => r.crossesMultipleCounties === true), currentlyConsumerVisibleCount: countRows(hits, (r) => r.currentConsumerVisible === true), currentlyExcludedCount: countRows(hits, (r) => r.currentConsumerVisible !== true), categoryCounts: hits.reduce((m, r) => (m[r.category || "unavailable"] = (m[r.category || "unavailable"] || 0) + 1, m), {}), communityCoverageCount: groupedCommunities.filter((summary) => comms.find((cm) => cm.communityId === summary.communityId)?.countyId === cy.countyId && summary.intersectingDriveTexasRecordCount > 0).length, unresolvedRecordCount: countRows(hits, (r) => r.geographicStatus === "geographically_unresolved") }; }); }
  function summarizeGeometry(rows, rawProviderFeatureCount, normalizedRecordCount) { return { rawProviderFeatureCount: rawProviderFeatureCount ?? null, normalizedRecordCount, uniqueSourceIdCount: new Set(rows.map((r) => r.sourceId)).size, duplicateSourceIdCount: new Set(rows.filter((r) => r.duplicateSourceId).map((r) => r.sourceId)).size ? rows.length - new Set(rows.map((r) => r.sourceId)).size : 0, pointGeometryRecordCount: countRows(rows, (r) => r.geometryType === "Point"), lineStringGeometryRecordCount: countRows(rows, (r) => r.geometryType === "LineString"), multiLineStringGeometryRecordCount: countRows(rows, (r) => r.geometryType === "MultiLineString"), missingGeometryRecordCount: countRows(rows, (r) => r.geometryType === "missing"), invalidGeometryRecordCount: countRows(rows, (r) => r.dataQualityFlags.includes("malformed_geometry")), usableRepresentativeCoordinateCount: countRows(rows, (r) => Number.isFinite(r.representativeLatitude) && Number.isFinite(r.representativeLongitude)), neitherUsableGeometryNorCoordinatesCount: countRows(rows, (r) => r.dataQualityFlags.includes("no_usable_geometry_or_coordinates")) }; }

  function build(input = {}) {
    const records = sourceRecords(input).map(clone).filter(Boolean);
    const comms = communityList(input), counties = countyList(input);
    const recordSourceAvailable = Array.isArray(input.records) || arr(globalScope.gridlyDriveTexasConnector?.getAllNormalizedRecords?.()).length > 0 || arr(globalScope.gridlyDriveTexasConnector?.getNormalizedRecords?.()).length > 0 || arr(globalScope.gridlyDriveTexasProvider?.getNormalizedRecords?.()).length > 0;
    const registryStatus = { countyRegistryAvailable: counties.length > 0, countyCount: counties.length, communityRegistryAvailable: comms.length > 0, communityCount: comms.length, recordSourceAvailable, recordCount: records.length };
    const registryFailure = !registryStatus.communityRegistryAvailable;
    const prod = production(input);
    const prodProof = arr(prod.recordProof || prod.authority?.recordProof);
    const identities = records.map(canonicalIdentity);
    const visibleIds = new Set(arr(prod.consumerEligibleSituations || prod.authority?.consumerEligibleSituations || prod.consumerVisibleSituations).map((r) => canonicalIdentity(r).sourceId));
    const seen = new Map(); identities.forEach((identity) => { seen.set(identity.sourceId, (seen.get(identity.sourceId) || 0) + 1); });
    const rows = records.map((r, i) => {
      const identity = identities[i], sid = identity.sourceId, rawType = (r.sourceGeometry || r.__geometry || r.geometry)?.type || r.geometryType || "missing", c = coord(r);
      const qualification = globalScope.gridlyQualifyDriveTexasGeometryAuthority(r, { communities: comms, counties, selectedAwarenessArea: input.selectedAwarenessArea });
      const p = prodProof.find((x) => canonicalIdentity(x).sourceId === sid || txt(x.authorityIdentity) === sid || txt(x.sourceId) === sid) || {};
      const row = { sourceId: sid, sourceIdentityValue: identity.sourceIdentityValue, sourceIdentityField: identity.sourceIdentityField, sourceIdentityMethod: identity.sourceIdentityMethod, category: r.category || null, headline: r.headline || r.title || null, routeName: r.routeName || r.roadway || null, descriptionSummary: txt(r.description || r.summary).slice(0, 240), geometryType: qualification.geometryType || rawType, coordinateCount: qualification.coordinateCount, representativeLatitude: qualification.representativeLatitude, representativeLongitude: qualification.representativeLongitude, geometryBounds: qualification.geometryBounds, geometryValid: qualification.geometryValid, countyIdsIntersected: qualification.countyIdsIntersected, countyNamesIntersected: qualification.countyNamesIntersected, communityIdsIntersected: qualification.communityIdsIntersected, communityNamesIntersected: qualification.communityNamesIntersected, communityIntersectionCount: qualification.communityIntersectionCount, nearestCommunityId: qualification.nearestCommunityId, nearestCommunityName: qualification.nearestCommunityName, nearestCommunityDistanceMiles: qualification.nearestCommunityDistanceMiles, insideGridlyCoverage: !registryFailure && qualification.insideGridlyCoverage, crossesMultipleCounties: qualification.crossesMultipleCounties, crossesMultipleCommunities: qualification.crossesMultipleCommunities, geographicResolutionMethod: registryFailure ? "registry_unavailable" : qualification.geographicResolutionMethod, currentLp039Eligibility: p.finalEligibility === true, currentOwnershipMethod: p.geographicOwnershipMethod || null, currentConsumerVisible: visibleIds.has(sid), currentRejectionReason: arr(p.ineligibilityReasons).join("; ") || null, duplicateSourceId: (seen.get(sid) || 0) > 1, registryFailure, dataQualityFlags: [], geographicStatus: "" };
      if (identity.missing) row.dataQualityFlags.push("missing_source_identity");
      if (!row.geometryValid && rawType !== "missing") row.dataQualityFlags.push("malformed_geometry");
      if (!row.geometryValid && !c) row.dataQualityFlags.push("no_usable_geometry_or_coordinates");
      row.geographicStatus = registryFailure ? "registry_unavailable" : (!row.geometryValid && rawType !== "missing" ? "malformed" : (!row.geometryValid && !c ? "geographically_unresolved" : (row.insideGridlyCoverage ? "inside_gridly_coverage" : "outside_gridly_coverage")));
      row.discrepancyClassification = classify(row);
      row.firstProductionStageWhereLost = row.discrepancyClassification ? "lp039_authority_or_consumer_projection" : "none";
      return row;
    }).sort((a, b) => a.sourceId.localeCompare(b.sourceId));
    const output = { available: true, milestone: MILESTONE, passive: true, noFetches: true, noPolling: true, noWrites: true, noStorageWrites: true, noMapMovement: true, registryStatus, records: rows, completeRecordRows: rows };
    Object.defineProperties(output, {
      recordCount: { enumerable: true, get() { return rows.length; } },
      uniqueSourceIdCount: { enumerable: true, get() { return new Set(rows.map((r) => r.sourceId)).size; } },
      duplicateSourceIdInstances: { enumerable: true, get() { return rows.filter((r) => r.duplicateSourceId); } },
      geometryInventory: { enumerable: true, get() { return summarizeGeometry(rows, input.rawProviderFeatureCount, records.length); } },
      countySummaries: { enumerable: true, get() { return summarizeCounties(rows, counties, comms, registryFailure); } },
      communitySummaries: { enumerable: true, get() { return summarizeCommunities(rows, comms, registryFailure); } },
      coverageCounts: { enumerable: true, get() { return summarizeCoverage(rows); } },
      productionDiscrepancies: { enumerable: true, get() { return rows.filter((r) => r.discrepancyClassification).map(discrepancyProjection); } },
      discrepancyCounts: { enumerable: true, get() { return summarizeDiscrepancies(rows); } }
    });
    return freeze(output);
  }

  globalScope.gridlyBuildLp044DriveTexasCommunityAuthorityInventory = build;
  globalScope.gridlyLp044DriveTexasCommunityAuthorityInventory = function gridlyLp044DriveTexasCommunityAuthorityInventory() { return build(); };
  if (typeof module !== "undefined" && module.exports) module.exports = { build };
})(typeof window !== "undefined" ? window : globalThis);
