import assert from 'node:assert/strict';import test from 'node:test';import { buildReports,scenarios,verify } from '../../tools/lp166/certify-statewide-consumer-experience.mjs';
const reports=()=>buildReports();
test('at least twenty ordered end-to-end scenarios cover every required experience',()=>{const s=scenarios();assert.ok(s.length>=20);assert.deepEqual(s.map(x=>x.id),s.map(x=>x.id).toSorted());for(const area of ['search','destination','routing','route_watch','awareness','community_pulse','know_before_you_go','notifications','reporting','settings','mobile','liberty'])assert.ok(s.some(x=>x.area===area),area);assert.ok(s.every(x=>x.result==='PASS'));});
test('search contracts cover address, destination, business, category, alias and truthful no-result',()=>{const s=scenarios().filter(x=>x.area==='search');for(const word of ['address','destination','business','category','alias','NO_VERIFIED_RESULT'])assert.match(JSON.stringify(s),new RegExp(word,'i'));});
test('routing, awareness, notifications and Route Watch preserve prior boundaries',()=>{const c=reports()['reports/lp166/consumer-experience-certification.json'];assert.ok(c.priorConditionalBoundaries.includes('LP163_LIVE_NETWORK_VALIDATION_REQUIRED'));assert.ok(c.priorConditionalBoundaries.includes('LP164_LIVE_AWARENESS_VALIDATION_REQUIRED'));assert.ok(c.priorConditionalBoundaries.includes('LP165_LIVE_DELIVERY_NOT_IMPLEMENTED'));assert.equal(c.runtime,'UNCHANGED');});
test('consumer language answers the five-part trust contract without technical leakage',()=>{const l=reports()['reports/lp166/consumer-language-results.json'];assert.deepEqual(l.contract,['What happened','Where','How recent','How many reports','How reliable']);assert.equal(l.technicalMetadataFailures,0);assert.equal(l.status,'PASS');});
test('quiet, active and cleared awareness states are distinct',()=>{const s=scenarios();for(const state of ['QUIET','ACTIVE','CLEARED'])assert.ok(s.some(x=>x.state===state));});
test('mobile portrait and live-device limitation are represented truthfully',()=>{const m=reports()['reports/lp166/mobile-portrait-results.json'];assert.equal(m.status,'PASS_WITH_LIVE_VALIDATION_REQUIRED');assert.equal(m.liveDeviceValidationRequired,true);});
test('governed report verification is read-only',()=>{assert.equal(verify().finalClassification,'CONDITIONALLY_CERTIFIED_FINAL_LIVE_VALIDATION_REQUIRED');});
