import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {join} from 'node:path';
const here=join(process.cwd(),'tools/responder/phase29');
const m=JSON.parse(readFileSync(join(here,'contract-version.json'),'utf8'));
if(createHash('sha256').update(readFileSync(join(here,m.artifact))).digest('hex')!==m.sha256)throw Error('Contract hash mismatch');
const t=JSON.parse(readFileSync(join(here,'taxonomy-v1.json'),'utf8'));
if(t.contractHash!==m.sha256)throw Error('Registry contract mismatch');
let s=readFileSync(join(here,'schema.local.sql'),'utf8');
s=s.replace('DEFAULT false CHECK(NOT publishing_enabled)','DEFAULT false');
s=s.replace(/CREATE FUNCTION dispatch_private.report_revision_guard\(\)[\s\S]*?END \$\$;/,'');
const start=s.indexOf(" IF p_command NOT IN('create_report'");
const end=s.indexOf(" IF p_command IN('create_report','revise_report') THEN",start);
const legacy=s.slice(start,end);
s=s.slice(0,start)+s.slice(end);
s=s.replace(' tok:=dispatch_private.token_for(org,actor);',legacy+' tok:=dispatch_private.token_for(org,actor);');
const q=v=>"'"+String(v).replaceAll("'","''")+"'";
const row=vs=>'('+vs.map(v=>typeof v==='boolean'?String(v):q(v)).join(',')+')';
const families=[...Object.keys(t.publicSubtypes),'INTERNAL','LEGACY'];
let seed=`INSERT INTO dispatch_private.report_contract_versions VALUES('PHASE29-v1',${q(m.sha256)},'PHASE29-INDEPENDENT-v1',now(),false);\nINSERT INTO dispatch_private.report_families VALUES ${families.map(v=>row([v])).join(',')};\n`;
const publicCodes=Object.values(t.publicSubtypes).flat();
const codes=[...publicCodes,...t.internalSubtypes,'LEGACY_UNCLASSIFIED'];
seed+='INSERT INTO dispatch_private.report_subtypes VALUES '+Object.entries(t.publicSubtypes).flatMap(([family,cs])=>cs.map(c=>row([c,family,true,t.hazardSubtypes.includes(c),t.version]))).concat(t.internalSubtypes.map(c=>row([c,'INTERNAL',false,false,t.version])),[row(['LEGACY_UNCLASSIFIED','LEGACY',false,false,t.version])]).join(',')+';\n';
const evidence=c=>c==='OFFICIAL_PUBLIC_NOTICE'?'N':c.startsWith('RAIL_')?'X':c.includes('UTILITY')||c.includes('INFRASTRUCTURE')||c==='DOWNED_POWER_LINE'?'U':t.internalSubtypes.includes(c)||c==='LEGACY_UNCLASSIFIED'?'INTERNAL':'R';
seed+='INSERT INTO dispatch_private.department_report_policies VALUES '+Object.keys(t.departmentPublic).flatMap(dep=>codes.map(c=>row([dep,c,t.departmentPublic[dep].includes(c)||t.departmentInternal[dep].includes(c),t.departmentPublic[dep].includes(c),evidence(c),t.version]))).join(',')+';\n';
seed+='INSERT INTO dispatch_private.capability_catalog(capability_key,subtype,legacy,high_risk_gate) VALUES '+publicCodes.map(c=>`(${q('awareness.report.'+c.toLowerCase()+'.publish')},${q(c)},false,false)`).concat(t.legacyCapabilities.map(c=>`(${q(c)},NULL,true,${c==='awareness.hazard.publish'||c==='awareness.road_closure.publish'})`)).join(',')+';\n';
seed+='INSERT INTO dispatch_private.capability_requirements VALUES '+publicCodes.flatMap(c=>[row([c,'awareness.report.'+c.toLowerCase()+'.publish','ALWAYS']),row([c,'awareness.hazard.publish','HAZARD']),row([c,'awareness.road_closure.publish','FULL_CLOSURE'])]).join(',')+';\n';
const tables=[...s.matchAll(/CREATE TABLE (dispatch_(?:private|audit|projection)\.\w+)/g)].map(x=>x[1]);
let security='GRANT dispatch_function_owner TO postgres;\n';
for(const table of tables)security+=`ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY; ALTER TABLE ${table} FORCE ROW LEVEL SECURITY; REVOKE ALL ON ${table} FROM PUBLIC,anon,authenticated,service_role;\n`;
const mutable=['report_details','road_impacts','capability_grant_constraints','content_quarantine','publication_reviews','sharing_agreements','shared_awareness_representations','report_public_projections'];
for(const table of tables) {
 const n=table.split('.')[1];
 const registry=['report_contract_versions','report_families','report_subtypes','department_report_policies','capability_catalog','capability_requirements','report_scope_segments'].includes(n);
 const acl=registry?'SELECT':n==='report_redaction_context'?'SELECT,INSERT,DELETE':mutable.includes(n)?'SELECT,INSERT,UPDATE':'SELECT,INSERT';
 security+=`GRANT ${acl} ON ${table} TO dispatch_function_owner;\n`;
}
const original=readFileSync(join(here,'../phase28/closure.sql'),'utf8').match(/CREATE OR REPLACE FUNCTION dispatch_private.reject_append_only\(\)[\s\S]*?END \$\$;/)[0];
const guarded=original.replace('SELECT user_id INTO subject',`IF TG_TABLE_NAME='record_revisions' AND TG_OP='UPDATE' AND EXISTS(SELECT 1 FROM dispatch_private.report_redaction_context c WHERE c.transaction_id=txid_current() AND c.record_id=(to_jsonb(OLD)->>'record_id')::uuid) AND (to_jsonb(NEW)-'snapshot')=(to_jsonb(OLD)-'snapshot') AND NEW.snapshot=jsonb_build_object('redacted',true,'record_id',(to_jsonb(OLD)->>'record_id')::uuid,'revision',(to_jsonb(OLD)->>'revision_number')::integer) THEN RETURN NEW; END IF;\n SELECT user_id INTO subject`);
security+=guarded+'\n';
for(const table of ['dispatch_private.road_impact_revisions','dispatch_private.content_screening_decisions','dispatch_audit.content_remediation_events'])security+=`CREATE TRIGGER phase29_append_only BEFORE UPDATE OR DELETE ON ${table} FOR EACH ROW EXECUTE FUNCTION dispatch_private.reject_append_only();\n`;
const functions=[...s.matchAll(/CREATE (?:OR REPLACE )?FUNCTION dispatch_private\.(\w+)\(([^)]*)\)/g)].map(x=>({name:x[1],args:x[2].split(',').filter(Boolean).map(p=>p.trim().split(/\s+/).slice(1).join(' ')).join(',')}));
security+='GRANT CREATE ON SCHEMA dispatch_private TO dispatch_function_owner;\n';
for(const f of functions)security+=`ALTER FUNCTION dispatch_private.${f.name}(${f.args}) OWNER TO dispatch_function_owner; REVOKE ALL ON FUNCTION dispatch_private.${f.name}(${f.args}) FROM PUBLIC,anon,authenticated,service_role;\n`;
security+='REVOKE CREATE ON SCHEMA dispatch_private FROM dispatch_function_owner;\nREVOKE EXECUTE ON FUNCTION dispatch_private.execute_command(text,jsonb) FROM authenticated;\nGRANT EXECUTE ON FUNCTION dispatch_private.report_execute(text,jsonb) TO authenticated;\n';
const commands=['create_report','revise_report','set_road_impact','approve_report_content','submit_report_publication','review_report_publication','publish_report','withdraw_report','quarantine_report','redact_report','grant_report_capability','renew_report_capability','create_sharing_agreement','approve_sharing_agreement','revoke_sharing_agreement','share_report','revoke_report_share'];
const oldCommands=[...readFileSync(join(here,'../phase28/command-contract.mjs'),'utf8').matchAll(/'([a-z]+_[a-z_]+)'/g)].map(x=>x[1]).filter(x=>!['expected_revision','source_revision'].includes(x));
for(const name of new Set([...commands,...oldCommands]))security+=`CREATE OR REPLACE FUNCTION dispatch_api.${name}(p_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY INVOKER SET search_path='' AS $fn$ SELECT dispatch_private.report_execute(${q(name)},p_payload) $fn$; REVOKE ALL ON FUNCTION dispatch_api.${name}(jsonb) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION dispatch_api.${name}(jsonb) TO authenticated;\n`;
security+=`CREATE POLICY report_public_read ON dispatch_projection.report_public_projections FOR SELECT TO anon,authenticated USING(dispatch_private.report_projection_eligible(id));
GRANT SELECT(id,organization_id,unit_id,subtype,title,summary,public_impacts,expires_at) ON dispatch_projection.report_public_projections TO anon,authenticated;
GRANT EXECUTE ON FUNCTION dispatch_private.report_projection_eligible(uuid) TO anon,authenticated;
CREATE VIEW dispatch_api.durable_public_reports WITH(security_invoker=true) AS SELECT id,organization_id,unit_id,subtype,title,summary,public_impacts,expires_at FROM dispatch_projection.report_public_projections;
GRANT SELECT ON dispatch_api.durable_public_reports TO anon,authenticated;
CREATE POLICY report_shared_read ON dispatch_private.shared_awareness_representations FOR SELECT TO authenticated USING(dispatch_private.report_shared_eligible(id));
GRANT SELECT(id,title,summary,valid_until) ON dispatch_private.shared_awareness_representations TO authenticated;
GRANT EXECUTE ON FUNCTION dispatch_private.report_shared_eligible(uuid) TO authenticated;
CREATE VIEW dispatch_api.durable_shared_awareness WITH(security_invoker=true) AS SELECT id,title,summary,valid_until FROM dispatch_private.shared_awareness_representations;
GRANT SELECT ON dispatch_api.durable_shared_awareness TO authenticated;
REVOKE dispatch_function_owner FROM postgres;
NOTIFY pgrst,'reload schema';
COMMIT;
`;
writeFileSync(join(here,'package.local.sql'),s+'\n'+seed+security);
writeFileSync(join(here,'object-inventory.json'),JSON.stringify({version:m.version,contractHash:m.sha256,tables,functions,commands,publicSubtypeCount:publicCodes.length,internalSubtypeCount:t.internalSubtypes.length,departmentPolicyRows:codes.length*4},null,2)+'\n');
console.log(JSON.stringify({tables:tables.length,commands:commands.length,departmentPolicies:codes.length*4}));
