-- DAYTON-REVIEW-01 additive authorization and exact candidate-state binding.
-- Actor tokens are opaque immutable lineage; no FK to the erasable identity mapping.
CREATE TABLE dispatch_private.reviewer_authorizations(
 id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,
 reviewer_token uuid NOT NULL,acting_unit_id uuid NOT NULL,target_unit_id uuid NOT NULL,
 subtype text NOT NULL REFERENCES dispatch_private.report_subtypes,risk_gates text[] NOT NULL DEFAULT '{}' CHECK(risk_gates<@ARRAY['awareness.hazard.publish','awareness.road_closure.publish']),
 scope_id uuid NOT NULL,scope_version integer NOT NULL,scope_source_version text NOT NULL,valid_from timestamptz NOT NULL DEFAULT now(),valid_until timestamptz NOT NULL,revoked_at timestamptz,
 authority_evidence text NOT NULL CHECK(length(authority_evidence) BETWEEN 1 AND 200),issued_by_token uuid NOT NULL,
 governance_approval_reference text CHECK(length(governance_approval_reference) BETWEEN 1 AND 200),policy_version text NOT NULL CHECK(policy_version='DAYTON-REVIEW-01-v1'),created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(valid_until>valid_from),CHECK(acting_unit_id=target_unit_id OR governance_approval_reference IS NOT NULL),
 FOREIGN KEY(organization_id,acting_unit_id) REFERENCES dispatch_private.organization_units(organization_id,id),
 FOREIGN KEY(organization_id,target_unit_id) REFERENCES dispatch_private.organization_units(organization_id,id),
 FOREIGN KEY(organization_id,scope_id) REFERENCES dispatch_private.operational_scopes(organization_id,id),
 FOREIGN KEY(scope_id,scope_version) REFERENCES dispatch_private.operational_scopes(id,version),UNIQUE(organization_id,id));
CREATE INDEX reviewer_authorizations_actor ON dispatch_private.reviewer_authorizations(organization_id,reviewer_token,target_unit_id);
ALTER TABLE dispatch_private.publication_reviews ADD COLUMN candidate_revision integer NOT NULL DEFAULT 1 CHECK(candidate_revision>0),
 ADD COLUMN reviewer_authorization_id uuid REFERENCES dispatch_private.reviewer_authorizations,
 ADD COLUMN acting_unit_id uuid REFERENCES dispatch_private.organization_units,
 ADD COLUMN reviewer_policy_version text NOT NULL DEFAULT 'DAYTON-REVIEW-01-v1' CHECK(reviewer_policy_version='DAYTON-REVIEW-01-v1');
CREATE TABLE dispatch_private.review_state_snapshots(review_id uuid PRIMARY KEY REFERENCES dispatch_private.publication_reviews,state_digest bytea NOT NULL CHECK(octet_length(state_digest)=32),impact_revisions jsonb NOT NULL CHECK(jsonb_typeof(impact_revisions)='array'),created_at timestamptz NOT NULL DEFAULT now());
CREATE FUNCTION dispatch_private.report_review_state(p_review uuid) RETURNS jsonb LANGUAGE sql STABLE SET search_path='' AS $$
 SELECT jsonb_build_object('candidate',to_jsonb(v)-ARRAY['state','reviewer_token','reviewed_at','reviewer_authorization_id','acting_unit_id'],
 'report',jsonb_build_object('id',r.id,'source_revision',r.current_revision,'status',r.status,'details_revision',d.revision,'detail_source_revision',d.source_revision,'subtype',d.subtype,'contract',d.contract_version,'contract_hash',cv.contract_hash,'policy',cv.policy_version,'scope',s.id,'scope_version',s.version,'scope_source_version',(SELECT source_version FROM dispatch_private.scope_governance WHERE scope_id=s.id),'unit_id',d.unit_id,'source_unit_id',r.owning_unit_id),
 'impacts',coalesce((SELECT jsonb_agg(to_jsonb(i) ORDER BY i.id) FROM dispatch_private.road_impacts i WHERE i.record_id=d.record_id),'[]'::jsonb),
 'linked',CASE WHEN d.linked_record_id IS NOT NULL THEN (SELECT jsonb_build_object('details',to_jsonb(ld),'source_revision',lr.current_revision,'status',lr.status,'impacts',coalesce((SELECT jsonb_agg(to_jsonb(i) ORDER BY i.id) FROM dispatch_private.road_impacts i WHERE i.record_id=ld.record_id),'[]'::jsonb)) FROM dispatch_private.report_details ld JOIN dispatch_private.operational_records lr ON lr.id=ld.record_id WHERE ld.record_id=d.linked_record_id) END)
 FROM dispatch_private.publication_reviews v JOIN dispatch_private.report_details d ON d.record_id=v.record_id JOIN dispatch_private.operational_records r ON r.id=d.record_id JOIN dispatch_private.report_contract_versions cv ON cv.version=d.contract_version JOIN dispatch_private.operational_scopes s ON s.id=r.operational_scope_id WHERE v.id=p_review $$;
CREATE FUNCTION dispatch_private.report_capture_review_state() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN
 INSERT INTO dispatch_private.review_state_snapshots(review_id,state_digest,impact_revisions) VALUES(NEW.id,extensions.digest(convert_to(dispatch_private.report_review_state(NEW.id)::text,'UTF8'),'sha256'),coalesce((SELECT jsonb_agg(jsonb_build_object('record_id',i.record_id,'impact_id',i.id,'revision',i.revision) ORDER BY i.record_id,i.id) FROM dispatch_private.road_impacts i WHERE i.record_id=NEW.record_id OR i.record_id=(SELECT linked_record_id FROM dispatch_private.report_details WHERE record_id=NEW.record_id)),'[]'::jsonb)); RETURN NEW; END $$;
CREATE TRIGGER report_capture_review_state AFTER INSERT ON dispatch_private.publication_reviews FOR EACH ROW EXECUTE FUNCTION dispatch_private.report_capture_review_state();
CREATE FUNCTION dispatch_private.report_review_state_valid(p_review uuid) RETURNS boolean LANGUAGE sql STABLE SET search_path='' AS $$
 SELECT coalesce((SELECT v.source_revision=r.current_revision AND v.details_revision=d.revision AND v.contract_version=d.contract_version AND v.policy_version=cv.policy_version AND v.reviewer_policy_version='DAYTON-REVIEW-01-v1' AND ss.state_digest=extensions.digest(convert_to(dispatch_private.report_review_state(v.id)::text,'UTF8'),'sha256') FROM dispatch_private.publication_reviews v JOIN dispatch_private.review_state_snapshots ss ON ss.review_id=v.id JOIN dispatch_private.report_details d ON d.record_id=v.record_id JOIN dispatch_private.operational_records r ON r.id=d.record_id JOIN dispatch_private.report_contract_versions cv ON cv.version=d.contract_version WHERE v.id=p_review),false) $$;
CREATE FUNCTION dispatch_private.report_reviewer_authorized(p_record uuid,p_authorization uuid,p_acting_unit uuid,p_token uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM dispatch_private.report_details d JOIN dispatch_private.operational_records r ON r.id=d.record_id JOIN dispatch_private.operational_scopes s ON s.id=r.operational_scope_id JOIN dispatch_private.reviewer_authorizations a ON a.id=p_authorization AND a.organization_id=d.organization_id JOIN dispatch_private.actor_tokens t ON t.token=a.reviewer_token AND t.organization_id=a.organization_id JOIN dispatch_private.profiles p ON p.user_id=t.user_id JOIN dispatch_private.organization_memberships m ON m.organization_id=a.organization_id AND m.user_id=t.user_id JOIN dispatch_private.role_permissions rp ON rp.role_key=m.role_template AND rp.permission_key='projection.review'
 WHERE d.record_id=p_record AND a.reviewer_token=p_token AND a.acting_unit_id=p_acting_unit AND a.target_unit_id=d.unit_id AND a.subtype=d.subtype AND a.scope_id=s.id AND a.scope_version=s.version AND s.status='ACTIVE' AND (s.valid_until IS NULL OR s.valid_until>now()) AND EXISTS(SELECT 1 FROM dispatch_private.scope_governance sg WHERE sg.scope_id=a.scope_id AND sg.organization_id=a.organization_id AND sg.source_version=a.scope_source_version AND sg.valid_until>now()) AND a.valid_from<=now() AND a.valid_until>now() AND a.revoked_at IS NULL AND a.policy_version='DAYTON-REVIEW-01-v1' AND p.status='ACTIVE' AND m.status='ACTIVE'
 AND NOT EXISTS(SELECT 1 FROM unnest(dispatch_private.report_required_keys(d.record_id)||coalesce(dispatch_private.report_required_keys(d.linked_record_id),ARRAY[]::text[])) k WHERE k IN('awareness.hazard.publish','awareness.road_closure.publish') AND NOT k=ANY(a.risk_gates))
 AND NOT EXISTS(SELECT 1 FROM unnest(ARRAY[a.acting_unit_id,a.target_unit_id]) target WHERE NOT EXISTS(SELECT 1 FROM dispatch_private.unit_memberships um JOIN dispatch_private.organization_units u ON u.id=um.unit_id WHERE um.unit_id=target AND um.organization_id=a.organization_id AND um.membership_id=m.id AND um.status='ACTIVE' AND u.status='ACTIVE' AND u.onboarding_state IN('PRIVATE_PILOT_READY','PUBLISHING_REVIEW_REQUIRED','PUBLISHING_ENABLED')))
 AND EXISTS(SELECT 1 FROM dispatch_private.unit_scope_grants us WHERE us.unit_id=a.target_unit_id AND us.organization_id=a.organization_id AND us.scope_id=a.scope_id)
 AND (a.acting_unit_id=a.target_unit_id OR a.governance_approval_reference IS NOT NULL)) $$;
CREATE FUNCTION dispatch_private.report_review_authorization_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN
 IF TG_OP='DELETE' OR OLD.revoked_at IS NOT NULL OR (to_jsonb(OLD)-'revoked_at')<>(to_jsonb(NEW)-'revoked_at') OR NEW.revoked_at IS NULL THEN RAISE EXCEPTION 'DAYTON_REVIEW_AUTHORIZATION_IMMUTABLE'; END IF; RETURN NEW; END $$;
CREATE TRIGGER report_review_authorization_guard BEFORE UPDATE OR DELETE ON dispatch_private.reviewer_authorizations FOR EACH ROW EXECUTE FUNCTION dispatch_private.report_review_authorization_guard();
