-- LOCAL DISPOSABLE ONLY. Not a production migration. OWNER APPROVED PHASE29-v1.
BEGIN;
GRANT dispatch_function_owner TO postgres;
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM gridly_rehearsal.environment WHERE marker='GRIDLY_PHASE26_LOCAL_SYNTHETIC' AND NOT production_access_authorized) THEN RAISE EXCEPTION 'PHASE29_REFUSED non-disposable environment'; END IF;
 IF EXISTS(SELECT 1 FROM dispatch_private.organizations) OR EXISTS(SELECT 1 FROM dispatch_audit.command_receipts) OR EXISTS(SELECT 1 FROM dispatch_projection.projection_candidates) THEN RAISE EXCEPTION 'PHASE29_REFUSED populated installation requires reviewed forward migration'; END IF;
END $$;
CREATE TABLE dispatch_private.report_contract_versions(version text PRIMARY KEY,contract_hash text NOT NULL CHECK(contract_hash ~ '^[a-f0-9]{64}$'),policy_version text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),publishing_enabled boolean NOT NULL DEFAULT false CHECK(NOT publishing_enabled));
CREATE TABLE dispatch_private.report_families(code text PRIMARY KEY);
CREATE TABLE dispatch_private.report_subtypes(code text PRIMARY KEY,family text NOT NULL REFERENCES dispatch_private.report_families,public_eligible boolean NOT NULL,hazard_required boolean NOT NULL DEFAULT false,contract_version text NOT NULL REFERENCES dispatch_private.report_contract_versions);
CREATE TABLE dispatch_private.department_report_policies(department text NOT NULL CHECK(department IN('POLICE','FIRE','EMS','PUBLIC_WORKS')),subtype text NOT NULL REFERENCES dispatch_private.report_subtypes,internal_allowed boolean NOT NULL DEFAULT false,public_allowed boolean NOT NULL DEFAULT false,evidence_class text NOT NULL CHECK(evidence_class IN('N','R','X','U','INTERNAL')),contract_version text NOT NULL REFERENCES dispatch_private.report_contract_versions,PRIMARY KEY(department,subtype),CHECK(NOT public_allowed OR internal_allowed));
CREATE TABLE dispatch_private.capability_catalog(capability_key text PRIMARY KEY,subtype text REFERENCES dispatch_private.report_subtypes,legacy boolean NOT NULL,high_risk_gate boolean NOT NULL DEFAULT false,CHECK(NOT legacy OR subtype IS NULL));
CREATE TABLE dispatch_private.capability_requirements(subtype text NOT NULL REFERENCES dispatch_private.report_subtypes,capability_key text NOT NULL REFERENCES dispatch_private.capability_catalog,requirement text NOT NULL CHECK(requirement IN('ALWAYS','HAZARD','FULL_CLOSURE')),PRIMARY KEY(subtype,capability_key));
ALTER TABLE dispatch_private.capability_grants DROP CONSTRAINT capability_grants_capability_key_check;
ALTER TABLE dispatch_private.capability_grants ADD CONSTRAINT capability_grants_catalog_fk FOREIGN KEY(capability_key) REFERENCES dispatch_private.capability_catalog DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE dispatch_private.capability_grant_constraints(grant_id uuid PRIMARY KEY,organization_id uuid NOT NULL,scope_id uuid NOT NULL,scope_version integer NOT NULL,subtype text NOT NULL REFERENCES dispatch_private.report_subtypes,closure_envelope text[] NOT NULL CHECK(cardinality(closure_envelope)>0 AND closure_envelope<@ARRAY['NONE','PARTIAL','FULL','UNKNOWN']),lane_envelope text[] NOT NULL CHECK(cardinality(lane_envelope)>0 AND lane_envelope<@ARRAY['NONE','ONE','MULTIPLE','ALL','UNKNOWN']),allowed_timing text[] NOT NULL CHECK(cardinality(allowed_timing)>0 AND allowed_timing<@ARRAY['PLANNED','UNPLANNED']),review_policy text NOT NULL CHECK(review_policy='PHASE29-INDEPENDENT-v1'),authority_evidence text NOT NULL CHECK(length(authority_evidence) BETWEEN 1 AND 200),evidence_class text NOT NULL CHECK(evidence_class IN('N','R','X','U')),renewal_revision integer NOT NULL DEFAULT 0,FOREIGN KEY(organization_id,grant_id) REFERENCES dispatch_private.capability_grants(organization_id,id),FOREIGN KEY(organization_id,scope_id) REFERENCES dispatch_private.operational_scopes(organization_id,id),FOREIGN KEY(scope_id,scope_version) REFERENCES dispatch_private.operational_scopes(id,version),UNIQUE(organization_id,grant_id));
CREATE TABLE dispatch_private.capability_grant_units(organization_id uuid NOT NULL,grant_id uuid NOT NULL,unit_id uuid NOT NULL,PRIMARY KEY(grant_id,unit_id),FOREIGN KEY(organization_id,grant_id) REFERENCES dispatch_private.capability_grant_constraints(organization_id,grant_id),FOREIGN KEY(organization_id,unit_id) REFERENCES dispatch_private.organization_units(organization_id,id));
CREATE TABLE dispatch_private.report_details(record_id uuid PRIMARY KEY,organization_id uuid NOT NULL,unit_id uuid NOT NULL,subtype text NOT NULL REFERENCES dispatch_private.report_subtypes,contract_version text NOT NULL REFERENCES dispatch_private.report_contract_versions,source_revision integer NOT NULL,revision integer NOT NULL DEFAULT 1,timing text NOT NULL CHECK(timing IN('PLANNED','UNPLANNED')),hazard_declared boolean NOT NULL DEFAULT false,screening_state text NOT NULL DEFAULT 'PENDING_REVIEW' CHECK(screening_state IN('PENDING_REVIEW','APPROVED','REJECTED_PROHIBITED_CONTENT','QUARANTINED','REDACTED')),author_token uuid NOT NULL,subject text CHECK(length(subject) BETWEEN 1 AND 160),body text CHECK(length(body) BETWEEN 1 AND 1000),notice_effective_at timestamptz,notice_expires_at timestamptz,linked_record_id uuid REFERENCES dispatch_private.operational_records,correction_of uuid REFERENCES dispatch_private.operational_records,withdrawn_at timestamptz,FOREIGN KEY(organization_id,record_id,source_revision) REFERENCES dispatch_audit.record_revisions(organization_id,record_id,revision_number),FOREIGN KEY(organization_id,unit_id) REFERENCES dispatch_private.organization_units(organization_id,id),CHECK(subtype<>'OFFICIAL_PUBLIC_NOTICE' OR (subject IS NOT NULL AND body IS NOT NULL AND notice_effective_at IS NOT NULL AND notice_expires_at>notice_effective_at)),UNIQUE(organization_id,record_id));
-- Governed geometry is explicit local evidence, never derived from client claims.
CREATE TABLE dispatch_private.report_scope_segments(id uuid PRIMARY KEY,organization_id uuid NOT NULL,scope_id uuid NOT NULL,scope_version integer NOT NULL,road_reference text NOT NULL,min_lat numeric NOT NULL,max_lat numeric NOT NULL,min_lon numeric NOT NULL,max_lon numeric NOT NULL,authority_evidence text NOT NULL,valid_until timestamptz NOT NULL,CHECK(min_lat>=-90 AND max_lat<=90 AND min_lat<=max_lat AND min_lon>=-180 AND max_lon<=180 AND min_lon<=max_lon),FOREIGN KEY(organization_id,scope_id) REFERENCES dispatch_private.operational_scopes(organization_id,id),FOREIGN KEY(scope_id,scope_version) REFERENCES dispatch_private.operational_scopes(id,version),UNIQUE(organization_id,id));
CREATE TABLE dispatch_private.road_impacts(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL,record_id uuid NOT NULL,revision integer NOT NULL DEFAULT 1,segment_id uuid,direction_affected text NOT NULL DEFAULT 'UNKNOWN' CHECK(direction_affected IN('NORTHBOUND','SOUTHBOUND','EASTBOUND','WESTBOUND','BOTH_DIRECTIONS','ALL_DIRECTIONS','NOT_APPLICABLE','UNKNOWN')),lane_extent text NOT NULL DEFAULT 'UNKNOWN' CHECK(lane_extent IN('NONE','ONE','MULTIPLE','ALL','UNKNOWN')),lanes_affected_count integer CHECK(lanes_affected_count>0),total_lanes_count integer CHECK(total_lanes_count>0),closure_extent text NOT NULL DEFAULT 'UNKNOWN' CHECK(closure_extent IN('NONE','PARTIAL','FULL','UNKNOWN')),traffic_operation text NOT NULL DEFAULT 'UNKNOWN' CHECK(traffic_operation IN('NORMAL','ALTERNATING','NARROWED','STOPPED','UNKNOWN')),public_passable text NOT NULL DEFAULT 'UNKNOWN' CHECK(public_passable IN('YES','NO','UNKNOWN')),emergency_vehicles_passable text NOT NULL DEFAULT 'UNKNOWN' CHECK(emergency_vehicles_passable IN('YES','NO','UNKNOWN')),start_lat numeric CHECK(start_lat BETWEEN -90 AND 90),start_lon numeric CHECK(start_lon BETWEEN -180 AND 180),end_lat numeric CHECK(end_lat BETWEEN -90 AND 90),end_lon numeric CHECK(end_lon BETWEEN -180 AND 180),duration_state text NOT NULL DEFAULT 'UNKNOWN' CHECK(duration_state IN('ESTIMATED','UNKNOWN')),estimated_end_at timestamptz,reason_subtype text NOT NULL REFERENCES dispatch_private.report_subtypes,last_confirmed_at timestamptz NOT NULL DEFAULT statement_timestamp(),timing text NOT NULL CHECK(timing IN('PLANNED','UNPLANNED')),scheduled_start_at timestamptz,effective_start_at timestamptz,impact_status text NOT NULL CHECK(impact_status IN('SCHEDULED','ACTIVE','CLEARED','EXPIRED','CANCELLED')),valid_until timestamptz NOT NULL,FOREIGN KEY(organization_id,record_id) REFERENCES dispatch_private.report_details(organization_id,record_id),FOREIGN KEY(organization_id,segment_id) REFERENCES dispatch_private.report_scope_segments(organization_id,id),CHECK(lanes_affected_count IS NULL OR total_lanes_count IS NULL OR lanes_affected_count<=total_lanes_count),CHECK(lane_extent<>'ONE' OR lanes_affected_count IS NULL OR lanes_affected_count=1),CHECK(lane_extent<>'MULTIPLE' OR lanes_affected_count IS NULL OR lanes_affected_count>=2),CHECK(lane_extent<>'ALL' OR lanes_affected_count IS NULL OR total_lanes_count IS NULL OR lanes_affected_count=total_lanes_count),CHECK(closure_extent<>'FULL' OR (lane_extent='ALL' AND traffic_operation='STOPPED' AND public_passable='NO')),CHECK(traffic_operation<>'ALTERNATING' OR closure_extent='PARTIAL'),CHECK(duration_state<>'ESTIMATED' OR estimated_end_at IS NOT NULL),CHECK(duration_state<>'UNKNOWN' OR estimated_end_at IS NULL),CHECK(timing<>'PLANNED' OR scheduled_start_at IS NOT NULL),CHECK((start_lat IS NULL)=(start_lon IS NULL) AND (end_lat IS NULL)=(end_lon IS NULL)),CHECK((start_lat IS NULL AND end_lat IS NULL) OR segment_id IS NOT NULL),UNIQUE(organization_id,id));
CREATE INDEX phase29_impacts_record ON dispatch_private.road_impacts(record_id);
CREATE TABLE dispatch_private.road_impact_revisions(impact_id uuid NOT NULL REFERENCES dispatch_private.road_impacts,revision integer NOT NULL,record_id uuid NOT NULL REFERENCES dispatch_private.report_details,source_revision integer NOT NULL,actor_token uuid NOT NULL,snapshot jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(impact_id,revision));
CREATE TABLE dispatch_private.content_screening_decisions(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,record_id uuid REFERENCES dispatch_private.report_details,source_revision integer,state text NOT NULL CHECK(state IN('PENDING_REVIEW','APPROVED','REJECTED_PROHIBITED_CONTENT','QUARANTINED','REDACTED')),rule_version text NOT NULL CHECK(rule_version='PHASE29-SCREEN-v1'),content_digest bytea NOT NULL CHECK(octet_length(content_digest)=32),actor_token uuid NOT NULL,independent_reviewer_token uuid,created_at timestamptz NOT NULL DEFAULT now(),CHECK(state<>'APPROVED' OR (independent_reviewer_token IS NOT NULL AND independent_reviewer_token<>actor_token)));
-- Quarantine deliberately retains only an opaque digest and stable incident identity.
-- No rejected plaintext is stored in ordinary records, quarantine, receipts or logs.
CREATE TABLE dispatch_private.content_quarantine(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,screening_decision_id uuid NOT NULL REFERENCES dispatch_private.content_screening_decisions,record_id uuid REFERENCES dispatch_private.report_details,state text NOT NULL CHECK(state IN('QUARANTINED','REDACTED')),created_at timestamptz NOT NULL DEFAULT now(),redacted_at timestamptz,policy_reference text);
CREATE TABLE dispatch_audit.content_remediation_events(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,quarantine_id uuid NOT NULL REFERENCES dispatch_private.content_quarantine,record_id uuid REFERENCES dispatch_private.report_details,actor_token uuid NOT NULL,policy_reference text NOT NULL CHECK(length(policy_reference) BETWEEN 1 AND 200),event_type text NOT NULL CHECK(event_type IN('QUARANTINED','REDACTED')),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE dispatch_private.publication_reviews(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL,record_id uuid NOT NULL,source_revision integer NOT NULL,details_revision integer NOT NULL,contract_version text NOT NULL REFERENCES dispatch_private.report_contract_versions,policy_version text NOT NULL CHECK(policy_version='PHASE29-INDEPENDENT-v1'),author_token uuid NOT NULL,reviewer_token uuid,state text NOT NULL DEFAULT 'PENDING_REVIEW' CHECK(state IN('PENDING_REVIEW','APPROVED','REJECTED','WITHDRAWN')),title text NOT NULL CHECK(length(title) BETWEEN 1 AND 160),summary text NOT NULL CHECK(length(summary) BETWEEN 1 AND 1000),grant_ids uuid[] NOT NULL CHECK(cardinality(grant_ids)>0),valid_until timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),reviewed_at timestamptz,FOREIGN KEY(organization_id,record_id,source_revision) REFERENCES dispatch_audit.record_revisions(organization_id,record_id,revision_number),CHECK(state<>'APPROVED' OR (reviewer_token IS NOT NULL AND reviewer_token<>author_token)),UNIQUE(organization_id,id));
CREATE TABLE dispatch_private.sharing_agreements(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),source_organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,recipient_organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,revision integer NOT NULL DEFAULT 1,scope_id uuid NOT NULL,scope_version integer NOT NULL,purpose text NOT NULL CHECK(length(purpose) BETWEEN 1 AND 200),allowed_subtypes text[] NOT NULL CHECK(cardinality(allowed_subtypes)>0),allowed_fields text[] NOT NULL CHECK(cardinality(allowed_fields)>0 AND allowed_fields<@ARRAY['title','summary','subtype','timing']),valid_from timestamptz NOT NULL DEFAULT now(),valid_until timestamptz NOT NULL,revoked_at timestamptz,onward_sharing boolean NOT NULL DEFAULT false CHECK(NOT onward_sharing),CHECK(source_organization_id<>recipient_organization_id),CHECK(valid_until>valid_from),FOREIGN KEY(source_organization_id,scope_id) REFERENCES dispatch_private.operational_scopes(organization_id,id),FOREIGN KEY(scope_id,scope_version) REFERENCES dispatch_private.operational_scopes(id,version));
CREATE TABLE dispatch_private.sharing_agreement_parties(agreement_id uuid NOT NULL REFERENCES dispatch_private.sharing_agreements,organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,agreement_revision integer NOT NULL,approver_membership_id uuid NOT NULL,approver_token uuid NOT NULL,approved_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(agreement_id,organization_id),FOREIGN KEY(organization_id,approver_membership_id) REFERENCES dispatch_private.organization_memberships(organization_id,id));
CREATE TABLE dispatch_private.sharing_agreement_units(agreement_id uuid NOT NULL REFERENCES dispatch_private.sharing_agreements,organization_id uuid NOT NULL,unit_id uuid NOT NULL,PRIMARY KEY(agreement_id,unit_id),FOREIGN KEY(organization_id,unit_id) REFERENCES dispatch_private.organization_units(organization_id,id));
CREATE TABLE dispatch_private.shared_awareness_representations(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL,record_id uuid NOT NULL,source_revision integer NOT NULL,details_revision integer NOT NULL,agreement_id uuid REFERENCES dispatch_private.sharing_agreements,revision integer NOT NULL DEFAULT 1,author_token uuid NOT NULL,reviewer_token uuid NOT NULL,title text NOT NULL CHECK(length(title) BETWEEN 1 AND 160),summary text NOT NULL CHECK(length(summary) BETWEEN 1 AND 500),valid_until timestamptz NOT NULL,revoked_at timestamptz,CHECK(author_token<>reviewer_token),FOREIGN KEY(organization_id,record_id,source_revision) REFERENCES dispatch_audit.record_revisions(organization_id,record_id,revision_number),UNIQUE(organization_id,id));
CREATE TABLE dispatch_private.shared_awareness_recipients(share_id uuid NOT NULL REFERENCES dispatch_private.shared_awareness_representations,organization_id uuid NOT NULL,unit_id uuid NOT NULL,PRIMARY KEY(share_id,unit_id),FOREIGN KEY(organization_id,unit_id) REFERENCES dispatch_private.organization_units(organization_id,id));
-- No new public API or public grants are installed before command certification.
-- The schema is intentionally inert until the reviewed command boundary is complete.
-- Seed/ACL/forced-RLS statements are generated from the hashed versioned registry.
-- Exact validators; no client-supplied identity, confirmation or geometry authority.
CREATE FUNCTION dispatch_private.report_department(p_unit uuid) RETURNS text LANGUAGE sql STABLE SET search_path='' AS $$ SELECT CASE unit_type WHEN 'LAW_ENFORCEMENT' THEN 'POLICE' ELSE unit_type::text END FROM dispatch_private.organization_units WHERE id=p_unit $$;
CREATE FUNCTION dispatch_private.report_keys(p jsonb,allowed text[]) RETURNS void LANGUAGE plpgsql IMMUTABLE SET search_path='' AS $$ BEGIN IF jsonb_typeof(p) IS DISTINCT FROM 'object' OR EXISTS(SELECT 1 FROM jsonb_object_keys(p) k WHERE NOT k=ANY(allowed)) THEN RAISE EXCEPTION 'PHASE29_UNEXPECTED_FIELDS'; END IF; END $$;
CREATE FUNCTION dispatch_private.report_screen(p jsonb) RETURNS boolean LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT p::text ~* '(patient|diagnos|treatment|medical.record|clinical|symptom|prescription|medical.history|patient.destination|victim|witness|suspect|juvenile|cjis|ncic|tcic|informant|investigat|tactical|body.camera|criminal.history|protected.identity|confidential|transport.destination)' $$;
CREATE FUNCTION dispatch_private.report_impact_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ DECLARE s dispatch_private.report_scope_segments%ROWTYPE; d dispatch_private.report_details%ROWTYPE; BEGIN
 IF TG_OP='UPDATE' AND (OLD.impact_status IN('CLEARED','EXPIRED','CANCELLED') OR (OLD.impact_status='SCHEDULED' AND NEW.impact_status NOT IN('SCHEDULED','ACTIVE','EXPIRED','CANCELLED')) OR (OLD.impact_status='ACTIVE' AND NEW.impact_status NOT IN('ACTIVE','CLEARED','EXPIRED','CANCELLED'))) THEN RAISE EXCEPTION 'PHASE29_IMPACT_LIFECYCLE'; END IF;
 SELECT * INTO d FROM dispatch_private.report_details WHERE record_id=NEW.record_id;
 IF NEW.last_confirmed_at>statement_timestamp() OR NEW.valid_until<=statement_timestamp() OR NEW.valid_until>statement_timestamp()+interval '1 day' OR NEW.reason_subtype IS DISTINCT FROM d.subtype OR NEW.timing IS DISTINCT FROM d.timing THEN RAISE EXCEPTION 'PHASE29_IMPACT_TIME_OR_CAUSE'; END IF;
 IF NEW.estimated_end_at IS NOT NULL AND NEW.estimated_end_at<=coalesce(NEW.effective_start_at,NEW.scheduled_start_at,statement_timestamp()) THEN RAISE EXCEPTION 'PHASE29_ESTIMATE'; END IF;
 IF NEW.impact_status='ACTIVE' AND (NEW.effective_start_at IS NULL OR NEW.effective_start_at>statement_timestamp()) THEN RAISE EXCEPTION 'PHASE29_ACTIVATION'; END IF;
 IF NEW.impact_status='SCHEDULED' AND (NEW.timing<>'PLANNED' OR NEW.scheduled_start_at IS NULL) THEN RAISE EXCEPTION 'PHASE29_SCHEDULE'; END IF;
 IF NEW.segment_id IS NOT NULL THEN
 SELECT * INTO s FROM dispatch_private.report_scope_segments WHERE id=NEW.segment_id AND organization_id=NEW.organization_id AND valid_until>statement_timestamp();
 IF NOT FOUND OR s.scope_id<>(SELECT operational_scope_id FROM dispatch_private.operational_records WHERE id=NEW.record_id) OR s.scope_version<>(SELECT version FROM dispatch_private.operational_scopes WHERE id=s.scope_id) OR (NEW.start_lat IS NOT NULL AND (NEW.start_lat NOT BETWEEN s.min_lat AND s.max_lat OR NEW.start_lon NOT BETWEEN s.min_lon AND s.max_lon)) OR (NEW.end_lat IS NOT NULL AND (NEW.end_lat NOT BETWEEN s.min_lat AND s.max_lat OR NEW.end_lon NOT BETWEEN s.min_lon AND s.max_lon)) THEN RAISE EXCEPTION 'PHASE29_GEOMETRY_SCOPE'; END IF;
 END IF; RETURN NEW;
END $$;
CREATE TRIGGER report_impact_guard BEFORE INSERT OR UPDATE ON dispatch_private.road_impacts FOR EACH ROW EXECUTE FUNCTION dispatch_private.report_impact_guard();
CREATE FUNCTION dispatch_private.report_required_keys(p_record uuid) RETURNS text[] LANGUAGE sql STABLE SET search_path='' AS $$
 SELECT ARRAY['awareness.report.'||lower(d.subtype)||'.publish']||CASE WHEN s.hazard_required OR d.hazard_declared OR EXISTS(SELECT 1 FROM dispatch_private.road_impacts i WHERE i.record_id=d.record_id AND i.reason_subtype IN(SELECT code FROM dispatch_private.report_subtypes WHERE hazard_required)) THEN ARRAY['awareness.hazard.publish'] ELSE ARRAY[]::text[] END||CASE WHEN EXISTS(SELECT 1 FROM dispatch_private.road_impacts i WHERE i.record_id=d.record_id AND i.closure_extent='FULL') THEN ARRAY['awareness.road_closure.publish'] ELSE ARRAY[]::text[] END FROM dispatch_private.report_details d JOIN dispatch_private.report_subtypes s ON s.code=d.subtype WHERE d.record_id=p_record $$;
CREATE FUNCTION dispatch_private.report_grants_valid(p_record uuid,p_grants uuid[]) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM dispatch_private.report_details d JOIN dispatch_private.operational_records r ON r.id=d.record_id JOIN dispatch_private.operational_scopes scope ON scope.id=r.operational_scope_id WHERE d.record_id=p_record AND NOT EXISTS(
 SELECT 1 FROM unnest(dispatch_private.report_required_keys(p_record)) required WHERE NOT EXISTS(
 SELECT 1 FROM dispatch_private.capability_grants g JOIN dispatch_private.capability_grant_constraints c ON c.grant_id=g.id JOIN dispatch_private.capability_grant_units u ON u.grant_id=g.id AND u.unit_id=d.unit_id
 WHERE g.id=ANY(p_grants) AND g.organization_id=d.organization_id AND g.capability_key=required AND g.status='ACTIVE' AND g.valid_from<=now() AND g.valid_until>now() AND g.valid_until<=g.valid_from+interval '90 days' AND g.operational_scope_id=scope.id AND g.operational_scope_version=scope.version AND c.organization_id=d.organization_id AND c.scope_id=scope.id AND c.scope_version=scope.version AND c.subtype=d.subtype AND d.timing=ANY(c.allowed_timing) AND NOT EXISTS(SELECT 1 FROM dispatch_private.road_impacts i WHERE i.record_id=d.record_id AND (NOT i.closure_extent=ANY(c.closure_envelope) OR NOT i.lane_extent=ANY(c.lane_envelope)))))) $$;
CREATE FUNCTION dispatch_private.report_review_prerequisites(p_review uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM dispatch_private.publication_reviews v JOIN dispatch_private.report_details d ON d.record_id=v.record_id JOIN dispatch_private.report_contract_versions cv ON cv.version=d.contract_version JOIN dispatch_private.report_subtypes st ON st.code=d.subtype JOIN dispatch_private.operational_records r ON r.id=d.record_id JOIN dispatch_private.organizations o ON o.id=d.organization_id JOIN dispatch_private.organization_units u ON u.id=d.unit_id JOIN dispatch_private.pilot_governance pg ON pg.organization_id=o.id JOIN dispatch_private.operational_scopes s ON s.id=r.operational_scope_id JOIN dispatch_private.scope_governance sg ON sg.scope_id=s.id AND sg.organization_id=o.id JOIN dispatch_private.department_report_policies dp ON dp.department=dispatch_private.report_department(d.unit_id) AND dp.subtype=d.subtype
 WHERE v.id=p_review AND v.state='APPROVED' AND v.valid_until>now() AND dispatch_private.report_review_state_valid(v.id) AND dispatch_private.report_reviewer_authorized(d.record_id,v.reviewer_authorization_id,v.acting_unit_id,v.reviewer_token) AND v.source_revision=r.current_revision AND v.details_revision=d.revision AND d.source_revision=r.current_revision AND d.withdrawn_at IS NULL AND d.screening_state='APPROVED' AND st.public_eligible AND dp.public_allowed AND cv.policy_version=v.policy_version AND o.status='ACTIVE' AND o.verification_level='VERIFIED_PUBLIC_ENTITY' AND u.status='ACTIVE' AND u.onboarding_state IN('PRIVATE_PILOT_READY','PUBLISHING_REVIEW_REQUIRED','PUBLISHING_ENABLED') AND pg.verification_expires_at>now() AND pg.attestation_expires_at>now() AND sg.valid_until>now() AND s.status='ACTIVE' AND (s.valid_until IS NULL OR s.valid_until>now()) AND r.status IN('OPEN','IN_PROGRESS','MONITORING') AND dispatch_private.report_grants_valid(r.id,v.grant_ids)
 AND EXISTS(SELECT 1 FROM dispatch_private.actor_tokens t JOIN dispatch_private.organization_memberships m ON m.organization_id=t.organization_id AND m.user_id=t.user_id JOIN dispatch_private.profiles p ON p.user_id=m.user_id JOIN dispatch_private.unit_memberships um ON um.membership_id=m.id AND um.unit_id=d.unit_id JOIN dispatch_private.role_permissions rp ON rp.role_key=m.role_template WHERE t.token=v.reviewer_token AND t.organization_id=d.organization_id AND m.status='ACTIVE' AND um.status='ACTIVE' AND p.status='ACTIVE' AND rp.permission_key='projection.review')
 AND EXISTS(SELECT 1 FROM dispatch_private.actor_tokens t JOIN dispatch_private.organization_memberships m ON m.organization_id=t.organization_id AND m.user_id=t.user_id JOIN dispatch_private.profiles ap ON ap.user_id=m.user_id JOIN dispatch_private.unit_memberships um ON um.membership_id=m.id AND um.unit_id=d.unit_id JOIN dispatch_private.role_permissions rp ON rp.role_key=m.role_template WHERE t.token=v.author_token AND t.organization_id=d.organization_id AND m.status='ACTIVE' AND um.status='ACTIVE' AND ap.status='ACTIVE' AND rp.permission_key='projection.submit')
 AND (d.subtype='OFFICIAL_PUBLIC_NOTICE' AND d.notice_effective_at<=now() AND d.notice_expires_at>now() OR EXISTS(SELECT 1 FROM dispatch_private.road_impacts i WHERE i.record_id=d.record_id))
 AND NOT EXISTS(SELECT 1 FROM dispatch_private.road_impacts i WHERE i.record_id=d.record_id AND (i.valid_until<=now() OR i.last_confirmed_at<now()-interval '15 minutes' OR i.impact_status NOT IN('ACTIVE','SCHEDULED') OR i.segment_id IS NULL OR NOT EXISTS(SELECT 1 FROM dispatch_private.report_scope_segments seg WHERE seg.id=i.segment_id AND seg.organization_id=d.organization_id AND seg.scope_id=s.id AND seg.scope_version=s.version AND seg.valid_until>now()) OR i.direction_affected='UNKNOWN' OR i.closure_extent='UNKNOWN' OR i.lane_extent='UNKNOWN' OR i.public_passable='UNKNOWN'))
 AND (d.subtype<>'OFFICIAL_PUBLIC_NOTICE' OR d.linked_record_id IS NULL OR EXISTS(SELECT 1 FROM dispatch_private.report_details ld WHERE ld.record_id=d.linked_record_id AND ld.organization_id=d.organization_id AND ld.unit_id=d.unit_id AND ld.screening_state='APPROVED' AND ld.withdrawn_at IS NULL AND ld.subtype<>'OFFICIAL_PUBLIC_NOTICE' AND ld.source_revision=(SELECT current_revision FROM dispatch_private.operational_records WHERE id=ld.record_id AND status IN('OPEN','IN_PROGRESS','MONITORING')) AND EXISTS(SELECT 1 FROM dispatch_private.road_impacts li WHERE li.record_id=ld.record_id) AND NOT EXISTS(SELECT 1 FROM dispatch_private.road_impacts li WHERE li.record_id=ld.record_id AND (li.valid_until<=now() OR li.last_confirmed_at<now()-interval '15 minutes' OR li.segment_id IS NULL OR li.direction_affected='UNKNOWN' OR li.closure_extent='UNKNOWN' OR li.lane_extent='UNKNOWN' OR li.public_passable='UNKNOWN')) AND dispatch_private.report_grants_valid(ld.record_id,v.grant_ids)))) $$;
CREATE FUNCTION dispatch_private.report_public_eligible(p_review uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM dispatch_private.publication_reviews v JOIN dispatch_private.report_details d ON d.record_id=v.record_id JOIN dispatch_private.report_contract_versions cv ON cv.version=d.contract_version JOIN dispatch_private.report_subtypes st ON st.code=d.subtype JOIN dispatch_private.operational_records r ON r.id=d.record_id JOIN dispatch_private.organizations o ON o.id=d.organization_id JOIN dispatch_private.organization_units u ON u.id=d.unit_id JOIN dispatch_private.pilot_governance pg ON pg.organization_id=o.id JOIN dispatch_private.operational_scopes s ON s.id=r.operational_scope_id JOIN dispatch_private.scope_governance sg ON sg.scope_id=s.id AND sg.organization_id=o.id JOIN dispatch_private.department_report_policies dp ON dp.department=dispatch_private.report_department(d.unit_id) AND dp.subtype=d.subtype
 WHERE v.id=p_review AND v.state='APPROVED' AND v.valid_until>now() AND dispatch_private.report_review_state_valid(v.id) AND dispatch_private.report_reviewer_authorized(d.record_id,v.reviewer_authorization_id,v.acting_unit_id,v.reviewer_token) AND v.source_revision=r.current_revision AND v.details_revision=d.revision AND d.source_revision=r.current_revision AND d.withdrawn_at IS NULL AND d.screening_state='APPROVED' AND st.public_eligible AND dp.public_allowed AND cv.publishing_enabled AND cv.policy_version=v.policy_version AND o.status='ACTIVE' AND o.verification_level='VERIFIED_PUBLIC_ENTITY' AND u.status='ACTIVE' AND u.onboarding_state='PUBLISHING_ENABLED' AND pg.publishing_enabled AND pg.verification_expires_at>now() AND pg.attestation_expires_at>now() AND sg.valid_until>now() AND s.status='ACTIVE' AND (s.valid_until IS NULL OR s.valid_until>now()) AND r.status IN('OPEN','IN_PROGRESS','MONITORING') AND dispatch_private.report_grants_valid(r.id,v.grant_ids)
 AND EXISTS(SELECT 1 FROM dispatch_private.actor_tokens t JOIN dispatch_private.organization_memberships m ON m.organization_id=t.organization_id AND m.user_id=t.user_id JOIN dispatch_private.profiles p ON p.user_id=m.user_id JOIN dispatch_private.unit_memberships um ON um.membership_id=m.id AND um.unit_id=d.unit_id JOIN dispatch_private.role_permissions rp ON rp.role_key=m.role_template WHERE t.token=v.reviewer_token AND t.organization_id=d.organization_id AND m.status='ACTIVE' AND um.status='ACTIVE' AND p.status='ACTIVE' AND rp.permission_key='projection.review')
 AND EXISTS(SELECT 1 FROM dispatch_private.actor_tokens t JOIN dispatch_private.organization_memberships m ON m.organization_id=t.organization_id AND m.user_id=t.user_id JOIN dispatch_private.profiles ap ON ap.user_id=m.user_id JOIN dispatch_private.unit_memberships um ON um.membership_id=m.id AND um.unit_id=d.unit_id JOIN dispatch_private.role_permissions rp ON rp.role_key=m.role_template WHERE t.token=v.author_token AND t.organization_id=d.organization_id AND m.status='ACTIVE' AND um.status='ACTIVE' AND ap.status='ACTIVE' AND rp.permission_key='projection.submit')
 AND (d.subtype='OFFICIAL_PUBLIC_NOTICE' AND d.notice_effective_at<=now() AND d.notice_expires_at>now() OR EXISTS(SELECT 1 FROM dispatch_private.road_impacts i WHERE i.record_id=d.record_id))
 AND NOT EXISTS(SELECT 1 FROM dispatch_private.road_impacts i WHERE i.record_id=d.record_id AND (i.valid_until<=now() OR i.last_confirmed_at<now()-interval '15 minutes' OR i.impact_status NOT IN('ACTIVE','SCHEDULED') OR i.segment_id IS NULL OR NOT EXISTS(SELECT 1 FROM dispatch_private.report_scope_segments seg WHERE seg.id=i.segment_id AND seg.organization_id=d.organization_id AND seg.scope_id=s.id AND seg.scope_version=s.version AND seg.valid_until>now()) OR i.direction_affected='UNKNOWN' OR i.closure_extent='UNKNOWN' OR i.lane_extent='UNKNOWN' OR i.public_passable='UNKNOWN'))
 AND (d.subtype<>'OFFICIAL_PUBLIC_NOTICE' OR d.linked_record_id IS NULL OR EXISTS(SELECT 1 FROM dispatch_private.report_details ld WHERE ld.record_id=d.linked_record_id AND ld.organization_id=d.organization_id AND ld.unit_id=d.unit_id AND ld.screening_state='APPROVED' AND ld.withdrawn_at IS NULL AND ld.subtype<>'OFFICIAL_PUBLIC_NOTICE' AND ld.source_revision=(SELECT current_revision FROM dispatch_private.operational_records WHERE id=ld.record_id AND status IN('OPEN','IN_PROGRESS','MONITORING')) AND EXISTS(SELECT 1 FROM dispatch_private.road_impacts li WHERE li.record_id=ld.record_id) AND NOT EXISTS(SELECT 1 FROM dispatch_private.road_impacts li WHERE li.record_id=ld.record_id AND (li.valid_until<=now() OR li.last_confirmed_at<now()-interval '15 minutes' OR li.segment_id IS NULL OR li.direction_affected='UNKNOWN' OR li.closure_extent='UNKNOWN' OR li.lane_extent='UNKNOWN' OR li.public_passable='UNKNOWN')) AND dispatch_private.report_grants_valid(ld.record_id,v.grant_ids)))) $$;
CREATE FUNCTION dispatch_private.report_shared_eligible(p_share uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$
 SELECT EXISTS(SELECT 1 FROM dispatch_private.shared_awareness_representations sh JOIN dispatch_private.report_details d ON d.record_id=sh.record_id JOIN dispatch_private.operational_records r ON r.id=d.record_id JOIN dispatch_private.operational_scopes s ON s.id=r.operational_scope_id JOIN dispatch_private.organization_units source_unit ON source_unit.id=d.unit_id
 WHERE sh.id=p_share AND sh.revoked_at IS NULL AND sh.valid_until>now() AND d.withdrawn_at IS NULL AND d.screening_state='APPROVED' AND sh.source_revision=r.current_revision AND sh.details_revision=d.revision AND source_unit.status='ACTIVE' AND s.status='ACTIVE' AND (s.valid_until IS NULL OR s.valid_until>now()) AND r.status NOT IN('CLOSED','CANCELLED')
 AND EXISTS(SELECT 1 FROM dispatch_private.shared_awareness_recipients x WHERE x.share_id=sh.id AND dispatch_private.unit_access(x.organization_id,x.unit_id,'internal.read') AND (x.organization_id=sh.organization_id AND sh.agreement_id IS NULL OR EXISTS(
 SELECT 1 FROM dispatch_private.sharing_agreements a JOIN dispatch_private.sharing_agreement_units au ON au.agreement_id=a.id AND au.unit_id=x.unit_id WHERE a.id=sh.agreement_id AND a.source_organization_id=sh.organization_id AND a.recipient_organization_id=x.organization_id AND a.revoked_at IS NULL AND a.valid_from<=now() AND a.valid_until>now() AND a.scope_id=s.id AND a.scope_version=s.version AND d.subtype=ANY(a.allowed_subtypes) AND a.allowed_fields@>ARRAY['title','summary'] AND (SELECT count(*) FROM dispatch_private.sharing_agreement_parties p JOIN dispatch_private.organization_memberships m ON m.id=p.approver_membership_id JOIN dispatch_private.profiles pr ON pr.user_id=m.user_id JOIN dispatch_private.organizations po ON po.id=m.organization_id WHERE p.agreement_id=a.id AND p.agreement_revision=a.revision AND m.status='ACTIVE' AND po.status='ACTIVE' AND pr.status='ACTIVE' AND m.role_template IN('OWNER','ORGANIZATION_ADMIN'))=2)))) $$;
-- Legacy records remain usable privately. Broad grants never qualify a new subtype.
CREATE OR REPLACE FUNCTION dispatch_private.pilot_candidate_eligible(p_record uuid,p_cap uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT false $$;
-- No legacy projection can silently become Phase 29 eligible.
CREATE TABLE dispatch_projection.report_public_projections(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),review_id uuid NOT NULL REFERENCES dispatch_private.publication_reviews,organization_id uuid NOT NULL,unit_id uuid NOT NULL,subtype text NOT NULL REFERENCES dispatch_private.report_subtypes,title text NOT NULL,summary text NOT NULL,public_impacts jsonb NOT NULL,expires_at timestamptz NOT NULL,withdrawn_at timestamptz,FOREIGN KEY(organization_id,unit_id) REFERENCES dispatch_private.organization_units(organization_id,id));
CREATE FUNCTION dispatch_private.report_projection_eligible(p_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT EXISTS(SELECT 1 FROM dispatch_projection.report_public_projections p WHERE p.id=p_id AND p.withdrawn_at IS NULL AND p.expires_at>now() AND dispatch_private.report_public_eligible(p.review_id)) $$;
CREATE FUNCTION dispatch_private.report_safe_impacts(p_record uuid) RETURNS jsonb LANGUAGE sql STABLE SET search_path='' AS $$ SELECT coalesce(jsonb_agg(jsonb_build_object('id',i.id,'direction_affected',i.direction_affected,'lane_extent',i.lane_extent,'lanes_affected_count',i.lanes_affected_count,'total_lanes_count',i.total_lanes_count,'closure_extent',i.closure_extent,'traffic_operation',i.traffic_operation,'public_passable',i.public_passable,'duration_state',i.duration_state,'estimated_end_at',i.estimated_end_at,'road_reference',(SELECT road_reference FROM dispatch_private.report_scope_segments WHERE id=i.segment_id),'start_point',CASE WHEN i.start_lat IS NOT NULL THEN jsonb_build_object('lat',i.start_lat,'lon',i.start_lon) END,'end_point',CASE WHEN i.end_lat IS NOT NULL THEN jsonb_build_object('lat',i.end_lat,'lon',i.end_lon) END,'timing',i.timing,'scheduled_start_at',i.scheduled_start_at,'effective_start_at',i.effective_start_at,'impact_status',i.impact_status,'valid_until',i.valid_until,'last_confirmed_at',i.last_confirmed_at) ORDER BY i.id),'[]'::jsonb) FROM dispatch_private.road_impacts i WHERE i.record_id=p_record $$;
CREATE TABLE dispatch_private.report_redaction_context(transaction_id bigint PRIMARY KEY,record_id uuid NOT NULL REFERENCES dispatch_private.operational_records,policy_reference text NOT NULL);
CREATE FUNCTION dispatch_private.report_revision_guard() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN
 IF TG_OP='UPDATE' AND EXISTS(SELECT 1 FROM dispatch_private.report_redaction_context c WHERE c.transaction_id=txid_current() AND c.record_id=OLD.record_id) AND (to_jsonb(NEW)-'snapshot')=(to_jsonb(OLD)-'snapshot') AND NEW.snapshot=jsonb_build_object('redacted',true,'record_id',OLD.record_id,'revision',OLD.revision_number) THEN RETURN NEW; END IF;
 RETURN dispatch_private.reject_append_only();
END $$;
-- Trigger functions cannot call another trigger function directly; preserve the frozen
-- guard by renaming its existing trigger and adding a constrained redaction trigger
-- only on the record-revision table in the generated package.
CREATE FUNCTION dispatch_private.report_execute(p_command text,p jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
#variable_conflict use_variable
<<report_command>>
DECLARE org uuid:=(p->>'organization_id')::uuid; actor uuid:=dispatch_private.current_actor_id(); k uuid:=(p->>'idempotency_key')::uuid; oid uuid:=(p->>'object_id')::uuid; rid uuid:=(p->>'record_id')::uuid; impact_revision integer; uid uuid:=(p->>'unit_id')::uuid; mid uuid; tok uuid; dept text; subtype text:=p->>'subtype'; r dispatch_private.operational_records%ROWTYPE; d dispatch_private.report_details%ROWTYPE; v dispatch_private.publication_reviews%ROWTYPE; a dispatch_private.sharing_agreements%ROWTYPE; h bytea:=dispatch_private.request_hash(p-'idempotency_key'); receipt dispatch_audit.command_receipts%ROWTYPE; result jsonb; source jsonb; flag boolean; expected integer:=(p->>'expected_revision')::integer; x jsonb; cap uuid; grants uuid[]; deadline timestamptz; qid uuid; sid uuid; recipients uuid[]; permission text; constraints dispatch_private.capability_grant_constraints%ROWTYPE;
BEGIN
 IF NOT dispatch_private.has_live_aal2() OR actor IS NULL OR org IS NULL OR k IS NULL THEN RAISE EXCEPTION 'PHASE29_FORBIDDEN'; END IF;
 IF p_command='invite_member' THEN RAISE EXCEPTION 'DAYTON_INVITE_SERVER_ISSUANCE_REQUIRED'; END IF;
 PERFORM pg_advisory_xact_lock(280028);
 PERFORM 1 FROM dispatch_private.organizations WHERE id=org AND status='ACTIVE' FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'PHASE29_ORGANIZATION'; END IF;
 tok:=dispatch_private.token_for(org,actor);
 permission:=CASE WHEN p_command IN('grant_report_capability','renew_report_capability','grant_review_authorization','revoke_review_authorization') THEN 'platform.capability.manage' WHEN p_command IN('approve_report_content','review_report_publication','quarantine_report','redact_report') THEN 'projection.review' WHEN p_command='publish_report' THEN 'projection.publish' WHEN p_command='submit_report_publication' THEN 'projection.submit' WHEN p_command IN('create_sharing_agreement','approve_sharing_agreement','revoke_sharing_agreement') THEN 'organization.manage' WHEN p_command IN('share_report','revoke_report_share') THEN 'internal.share' WHEN p_command='create_report' THEN 'operations.create' ELSE 'operations.update' END;
 IF permission LIKE 'platform.%' THEN IF NOT EXISTS(SELECT 1 FROM dispatch_private.platform_admin_grants WHERE user_id=actor AND permission_key=permission AND active) THEN RAISE EXCEPTION 'PHASE29_PLATFORM_PERMISSION'; END IF;
 ELSE mid:=dispatch_private.actor_membership(org,permission); IF mid IS NULL THEN RAISE EXCEPTION 'PHASE29_PERMISSION'; END IF; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(k::text,0));
 IF p_command='review_report_publication' AND NOT dispatch_private.report_review_attempt_eligible(oid,(p->>'reviewer_authorization_id')::uuid,(p->>'acting_unit_id')::uuid,tok) THEN RAISE EXCEPTION 'DAYTON_REVIEW_LIVE_ATTEMPT_DENIED'; END IF;
 SELECT * INTO receipt FROM dispatch_audit.command_receipts WHERE organization_id=org AND actor_user_id=actor AND command_name=p_command AND idempotency_key=k;
 IF FOUND THEN IF receipt.request_hash<>h THEN RAISE EXCEPTION 'PHASE29_REPLAY_MISMATCH'; END IF; RETURN receipt.result_payload||jsonb_build_object('replay',true); END IF;
 IF p_command NOT IN('grant_review_authorization','revoke_review_authorization','create_report','revise_report','set_road_impact','approve_report_content','submit_report_publication','review_report_publication','publish_report','withdraw_report','quarantine_report','redact_report','grant_report_capability','renew_report_capability','create_sharing_agreement','approve_sharing_agreement','revoke_sharing_agreement','share_report','revoke_report_share') THEN
 -- Legacy intake remains private/unclassified and may not import arbitrary content.
 IF p_command IN('create_operational_record','update_operational_record') THEN
  IF p ? 'private_payload' AND p->'private_payload'<>'{}'::jsonb THEN RAISE EXCEPTION 'PHASE29_LEGACY_INTAKE_REFUSED'; END IF;
  IF dispatch_private.report_screen(p) THEN RAISE EXCEPTION 'PHASE29_CONTENT_REFUSED'; END IF;
 END IF;
 IF p_command IN('create_internal_share','submit_projection_candidate') THEN
  rid:=(p->>'record_id')::uuid;
  IF EXISTS(SELECT 1 FROM dispatch_private.report_details WHERE record_id=rid) THEN RAISE EXCEPTION 'PHASE29_REVIEWED_REPORT_PATH_REQUIRED'; END IF;
  IF dispatch_private.report_screen(p) THEN RAISE EXCEPTION 'PHASE29_CONTENT_REFUSED'; END IF;
 END IF;
 IF p_command IN('update_operational_record','transition_operational_record','close_operational_record') AND EXISTS(SELECT 1 FROM dispatch_private.report_details WHERE record_id=oid) AND p_command='update_operational_record' THEN RAISE EXCEPTION 'PHASE29_REVISION_PATH_REQUIRED'; END IF;
 RETURN dispatch_private.execute_command(p_command,p);
 END IF;
 IF p_command IN('grant_review_authorization','revoke_review_authorization') THEN
 IF p_command='revoke_review_authorization' THEN
  PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','object_id']);
  UPDATE dispatch_private.reviewer_authorizations SET revoked_at=now() WHERE id=oid AND organization_id=org AND revoked_at IS NULL;
  IF NOT FOUND THEN RAISE EXCEPTION 'DAYTON_REVIEW_AUTHORIZATION_BOUNDARY'; END IF;
 ELSE
  PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','reviewer_membership_id','acting_unit_id','target_unit_id','subtype','risk_gates','scope_id','scope_version','valid_from','valid_until','authority_evidence','governance_approval_reference']);
  IF dispatch_private.report_screen(jsonb_build_object('evidence',p->>'authority_evidence','governance',p->>'governance_approval_reference')) THEN RAISE EXCEPTION 'DAYTON_REVIEW_AUTHORIZATION_EVIDENCE'; END IF;
  SELECT m.user_id INTO cap FROM dispatch_private.organization_memberships m JOIN dispatch_private.profiles pr ON pr.user_id=m.user_id JOIN dispatch_private.role_permissions rp ON rp.role_key=m.role_template AND rp.permission_key='projection.review' WHERE m.id=(p->>'reviewer_membership_id')::uuid AND m.organization_id=org AND m.status='ACTIVE' AND pr.status='ACTIVE';
  IF NOT FOUND OR NOT EXISTS(SELECT 1 FROM dispatch_private.report_subtypes st JOIN dispatch_private.department_report_policies dp ON dp.subtype=st.code AND dp.department=dispatch_private.report_department((p->>'target_unit_id')::uuid) WHERE st.code=subtype AND st.public_eligible AND dp.public_allowed) THEN RAISE EXCEPTION 'DAYTON_REVIEW_AUTHORIZATION_RECIPIENT'; END IF;
  IF NOT EXISTS(SELECT 1 FROM dispatch_private.operational_scopes sc JOIN dispatch_private.scope_governance sg ON sg.scope_id=sc.id AND sg.organization_id=sc.organization_id WHERE sc.id=(p->>'scope_id')::uuid AND sc.organization_id=org AND sc.version=(p->>'scope_version')::integer AND sc.status='ACTIVE' AND (sc.valid_until IS NULL OR sc.valid_until>now()) AND sg.valid_until>now()) THEN RAISE EXCEPTION 'DAYTON_REVIEW_AUTHORIZATION_SCOPE'; END IF;
  IF EXISTS(SELECT 1 FROM unnest(ARRAY[(p->>'acting_unit_id')::uuid,(p->>'target_unit_id')::uuid]) target WHERE NOT EXISTS(SELECT 1 FROM dispatch_private.unit_memberships um JOIN dispatch_private.organization_units u ON u.id=um.unit_id WHERE um.organization_id=org AND um.unit_id=target AND um.membership_id=(p->>'reviewer_membership_id')::uuid AND um.status='ACTIVE' AND u.status='ACTIVE')) THEN RAISE EXCEPTION 'DAYTON_REVIEW_AUTHORIZATION_UNITS'; END IF;
  deadline:=(p->>'valid_until')::timestamptz; IF deadline IS NULL OR deadline<=now() OR deadline>now()+interval '90 days' THEN RAISE EXCEPTION 'DAYTON_REVIEW_AUTHORIZATION_DURATION'; END IF;
  oid:=extensions.gen_random_uuid();
  INSERT INTO dispatch_private.reviewer_authorizations(id,organization_id,reviewer_token,acting_unit_id,target_unit_id,subtype,risk_gates,scope_id,scope_version,scope_source_version,valid_from,valid_until,authority_evidence,issued_by_token,governance_approval_reference,policy_version)
  VALUES(oid,org,dispatch_private.token_for(org,cap),(p->>'acting_unit_id')::uuid,(p->>'target_unit_id')::uuid,subtype,ARRAY(SELECT jsonb_array_elements_text(p->'risk_gates')),(p->>'scope_id')::uuid,(p->>'scope_version')::integer,(SELECT source_version FROM dispatch_private.scope_governance WHERE scope_id=(p->>'scope_id')::uuid),coalesce((p->>'valid_from')::timestamptz,now()),deadline,p->>'authority_evidence',tok,p->>'governance_approval_reference','DAYTON-REVIEW-01-v1');
 END IF;
 ELSIF p_command IN('create_report','revise_report') THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','object_id','unit_id','scope_id','subtype','timing','title','body','subject','notice_effective_at','notice_expires_at','linked_record_id','correction_of','hazard_declared','expected_revision','warning_acknowledged']);
 IF p->>'warning_acknowledged' IS DISTINCT FROM 'true' OR length(p->>'title') NOT BETWEEN 1 AND 160 OR length(coalesce(p->>'body',''))>1000 THEN RAISE EXCEPTION 'PHASE29_BOUNDED_INTAKE'; END IF;
 IF p_command='revise_report' THEN SELECT * INTO r FROM dispatch_private.operational_records WHERE id=oid AND organization_id=org FOR UPDATE; IF NOT FOUND OR NOT dispatch_private.record_access(oid,permission) OR r.current_revision IS DISTINCT FROM expected THEN RAISE EXCEPTION 'PHASE29_STALE_SOURCE'; END IF; uid:=r.owning_unit_id; END IF;
 dept:=dispatch_private.report_department(uid);
 IF uid IS NULL OR NOT dispatch_private.unit_access(org,uid,permission) OR NOT EXISTS(SELECT 1 FROM dispatch_private.department_report_policies WHERE department=dept AND department_report_policies.subtype=report_command.subtype AND internal_allowed) THEN RAISE EXCEPTION 'PHASE29_DEPARTMENT_DENIED'; END IF;
 flag:=dispatch_private.report_screen(jsonb_build_object('title',p->>'title','body',p->>'body','subject',p->>'subject'));
 IF flag THEN
 INSERT INTO dispatch_private.content_screening_decisions(organization_id,state,rule_version,content_digest,actor_token) VALUES(org,'QUARANTINED','PHASE29-SCREEN-v1',h,tok) RETURNING id INTO sid;
 INSERT INTO dispatch_private.content_quarantine(organization_id,screening_decision_id,state) VALUES(org,sid,'QUARANTINED') RETURNING id INTO oid;
 result:=jsonb_build_object('object_id',oid,'state','QUARANTINED','replay',false);
 ELSE
 IF p_command='create_report' THEN source:=dispatch_private.execute_command('create_operational_record',jsonb_build_object('organization_id',org,'idempotency_key',k,'unit_id',uid,'scope_id',p->>'scope_id','record_type',CASE WHEN subtype='OFFICIAL_PUBLIC_NOTICE' THEN 'OPERATIONAL_NOTICE' WHEN subtype='PLANNED_WORK' THEN 'PLANNED_WORK' WHEN subtype IN(SELECT code FROM dispatch_private.report_subtypes WHERE hazard_required) THEN 'HAZARD' ELSE 'CONDITION' END,'title',p->>'title','private_payload','{}'::jsonb,'data_attestation','OPERATIONAL_AWARENESS_ONLY','safety_class',CASE WHEN subtype='RESTRICTED_LAW_ENFORCEMENT_NOTE' THEN 'UNREVIEWED' ELSE 'GENERAL_AWARENESS' END)); oid:=(source->>'object_id')::uuid;
 ELSE PERFORM dispatch_private.execute_command('update_operational_record',jsonb_build_object('organization_id',org,'idempotency_key',k,'object_id',oid,'expected_revision',expected,'title',p->>'title','private_payload','{}'::jsonb,'data_attestation','OPERATIONAL_AWARENESS_ONLY')); END IF;
 SELECT * INTO r FROM dispatch_private.operational_records WHERE id=oid;
 IF p ? 'linked_record_id' AND NOT EXISTS(SELECT 1 FROM dispatch_private.operational_records lr JOIN dispatch_private.report_details ld ON ld.record_id=lr.id WHERE lr.id=(p->>'linked_record_id')::uuid AND lr.organization_id=org AND lr.owning_unit_id=uid AND lr.operational_scope_id=r.operational_scope_id AND ld.subtype<>'OFFICIAL_PUBLIC_NOTICE' AND dispatch_private.record_access(lr.id,'operations.read')) THEN RAISE EXCEPTION 'PHASE29_NOTICE_LINK'; END IF;
 IF subtype='OFFICIAL_PUBLIC_NOTICE' AND (coalesce((p->>'hazard_declared')::boolean,false) OR coalesce(p->>'body','')~*'(hazard|collision|crash|closure|closed|restriction|spill|high.water|power.line|smoke)') AND NOT p ? 'linked_record_id' THEN RAISE EXCEPTION 'PHASE29_NOTICE_STRUCTURED_LINK_REQUIRED'; END IF;
 IF subtype='OFFICIAL_PUBLIC_NOTICE' AND ((p->>'notice_expires_at')::timestamptz>now()+interval '1 day' OR (p->>'notice_expires_at')::timestamptz<=now()) THEN RAISE EXCEPTION 'PHASE29_NOTICE_EXPIRY'; END IF;
 INSERT INTO dispatch_private.report_details(record_id,organization_id,unit_id,subtype,contract_version,source_revision,timing,hazard_declared,author_token,subject,body,notice_effective_at,notice_expires_at,linked_record_id,correction_of)
 VALUES(oid,org,uid,subtype,'PHASE29-v1',r.current_revision,p->>'timing',coalesce((p->>'hazard_declared')::boolean,false),tok,p->>'subject',p->>'body',(p->>'notice_effective_at')::timestamptz,(p->>'notice_expires_at')::timestamptz,(p->>'linked_record_id')::uuid,(p->>'correction_of')::uuid)
 ON CONFLICT(record_id) DO UPDATE SET subtype=EXCLUDED.subtype,source_revision=EXCLUDED.source_revision,timing=EXCLUDED.timing,hazard_declared=EXCLUDED.hazard_declared,author_token=EXCLUDED.author_token,subject=EXCLUDED.subject,body=EXCLUDED.body,notice_effective_at=EXCLUDED.notice_effective_at,notice_expires_at=EXCLUDED.notice_expires_at,linked_record_id=EXCLUDED.linked_record_id,screening_state='PENDING_REVIEW',revision=dispatch_private.report_details.revision+1;
 IF p ? 'correction_of' THEN IF NOT dispatch_private.record_access((p->>'correction_of')::uuid,'operations.update') THEN RAISE EXCEPTION 'PHASE29_CORRECTION_SOURCE'; END IF; UPDATE dispatch_private.report_details SET withdrawn_at=now(),revision=revision+1 WHERE record_id=(p->>'correction_of')::uuid AND organization_id=org AND unit_id=uid; IF NOT FOUND THEN RAISE EXCEPTION 'PHASE29_CORRECTION_BOUNDARY'; END IF; END IF;
 INSERT INTO dispatch_private.content_screening_decisions(organization_id,record_id,source_revision,state,rule_version,content_digest,actor_token) VALUES(org,oid,r.current_revision,'PENDING_REVIEW','PHASE29-SCREEN-v1',h,tok);
 END IF;
 ELSIF p_command IN('grant_report_capability','renew_report_capability') THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','object_id','capability_key','subtype','scope_id','scope_version','unit_ids','closure_envelope','lane_envelope','allowed_timing','authority_evidence','evidence_class','valid_until','expected_revision']);
 IF p_command='renew_report_capability' THEN SELECT * INTO constraints FROM dispatch_private.capability_grant_constraints WHERE grant_id=oid AND organization_id=org FOR UPDATE; IF NOT FOUND OR expected IS DISTINCT FROM (SELECT revision FROM dispatch_private.capability_grants WHERE id=oid AND status='ACTIVE') THEN RAISE EXCEPTION 'PHASE29_STALE_GRANT'; END IF; PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','object_id','valid_until','expected_revision']);
 ELSE
 IF NOT EXISTS(SELECT 1 FROM dispatch_private.capability_catalog c WHERE c.capability_key=p->>'capability_key' AND (c.subtype=subtype OR c.high_risk_gate)) OR NOT EXISTS(SELECT 1 FROM dispatch_private.report_subtypes WHERE code=subtype AND public_eligible) THEN RAISE EXCEPTION 'PHASE29_EXACT_CAPABILITY'; END IF;
 IF NOT EXISTS(SELECT 1 FROM dispatch_private.operational_scopes s JOIN dispatch_private.scope_governance sg ON sg.scope_id=s.id WHERE s.id=(p->>'scope_id')::uuid AND s.organization_id=org AND s.version=(p->>'scope_version')::int AND s.status='ACTIVE' AND sg.valid_until>now()) THEN RAISE EXCEPTION 'PHASE29_GOVERNED_SCOPE'; END IF;
 oid:=extensions.gen_random_uuid();
 INSERT INTO dispatch_private.capability_grants(id,organization_id,capability_key,operational_scope_id,operational_scope_version,status,valid_until,granted_by_platform_actor,actor_token) VALUES(oid,org,p->>'capability_key',(p->>'scope_id')::uuid,(p->>'scope_version')::int,'ACTIVE',(p->>'valid_until')::timestamptz,actor,tok);
 INSERT INTO dispatch_private.capability_grant_constraints(grant_id,organization_id,scope_id,scope_version,subtype,closure_envelope,lane_envelope,allowed_timing,review_policy,authority_evidence,evidence_class) VALUES(oid,org,(p->>'scope_id')::uuid,(p->>'scope_version')::int,subtype,ARRAY(SELECT jsonb_array_elements_text(p->'closure_envelope')),ARRAY(SELECT jsonb_array_elements_text(p->'lane_envelope')),ARRAY(SELECT jsonb_array_elements_text(p->'allowed_timing')),'PHASE29-INDEPENDENT-v1',p->>'authority_evidence',p->>'evidence_class');
 IF jsonb_array_length(p->'unit_ids') NOT BETWEEN 1 AND 20 THEN RAISE EXCEPTION 'PHASE29_EXPLICIT_UNITS'; END IF;
 FOR x IN SELECT value FROM jsonb_array_elements(p->'unit_ids') LOOP uid:=(x#>>'{}')::uuid; IF NOT EXISTS(SELECT 1 FROM dispatch_private.organization_units u JOIN dispatch_private.department_report_policies dp ON dp.department=dispatch_private.report_department(u.id) AND dp.subtype=report_command.subtype WHERE u.id=uid AND u.organization_id=org AND u.status='ACTIVE' AND dp.public_allowed AND dp.evidence_class=p->>'evidence_class') THEN RAISE EXCEPTION 'PHASE29_GRANT_UNIT_DENIED'; END IF; INSERT INTO dispatch_private.capability_grant_units VALUES(org,oid,uid); END LOOP;
 END IF;
 deadline:=(p->>'valid_until')::timestamptz; IF deadline IS NULL OR deadline<=now() OR deadline>now()+interval '90 days' THEN RAISE EXCEPTION 'PHASE29_GRANT_DURATION'; END IF;
 IF p_command='renew_report_capability' THEN UPDATE dispatch_private.capability_grants SET valid_from=now(),valid_until=deadline,revision=revision+1 WHERE id=oid; UPDATE dispatch_private.capability_grant_constraints SET renewal_revision=renewal_revision+1 WHERE grant_id=oid; END IF;
 ELSIF p_command IN('create_sharing_agreement','approve_sharing_agreement','revoke_sharing_agreement') THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','object_id','recipient_organization_id','scope_id','scope_version','purpose','allowed_subtypes','allowed_fields','recipient_unit_ids','valid_until','expected_revision']);
 IF p_command='create_sharing_agreement' THEN
 oid:=extensions.gen_random_uuid(); INSERT INTO dispatch_private.sharing_agreements(id,source_organization_id,recipient_organization_id,scope_id,scope_version,purpose,allowed_subtypes,allowed_fields,valid_until) VALUES(oid,org,(p->>'recipient_organization_id')::uuid,(p->>'scope_id')::uuid,(p->>'scope_version')::int,p->>'purpose',ARRAY(SELECT jsonb_array_elements_text(p->'allowed_subtypes')),ARRAY(SELECT jsonb_array_elements_text(p->'allowed_fields')),(p->>'valid_until')::timestamptz);
 SELECT * INTO a FROM dispatch_private.sharing_agreements WHERE id=oid;
 IF a.valid_until>now()+interval '90 days' OR dispatch_private.report_screen(jsonb_build_object('purpose',a.purpose)) OR EXISTS(SELECT 1 FROM unnest(a.allowed_subtypes) c WHERE NOT EXISTS(SELECT 1 FROM dispatch_private.report_subtypes s WHERE s.code=c AND s.public_eligible)) OR NOT EXISTS(SELECT 1 FROM dispatch_private.operational_scopes WHERE id=a.scope_id AND status='ACTIVE' AND version=a.scope_version) THEN RAISE EXCEPTION 'PHASE29_AGREEMENT_POLICY'; END IF;
 IF jsonb_array_length(p->'recipient_unit_ids') NOT BETWEEN 1 AND 20 THEN RAISE EXCEPTION 'PHASE29_EXPLICIT_RECIPIENTS'; END IF;
 FOR x IN SELECT value FROM jsonb_array_elements(p->'recipient_unit_ids') LOOP uid:=(x#>>'{}')::uuid; IF NOT EXISTS(SELECT 1 FROM dispatch_private.organization_units WHERE id=uid AND organization_id=a.recipient_organization_id AND status='ACTIVE') THEN RAISE EXCEPTION 'PHASE29_AGREEMENT_RECIPIENT'; END IF; INSERT INTO dispatch_private.sharing_agreement_units VALUES(oid,a.recipient_organization_id,uid); END LOOP;
 ELSE PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','object_id','expected_revision']); SELECT * INTO a FROM dispatch_private.sharing_agreements WHERE id=oid AND org IN(source_organization_id,recipient_organization_id) FOR UPDATE;
 IF NOT FOUND OR a.revoked_at IS NOT NULL OR a.valid_until<=now() OR expected IS DISTINCT FROM a.revision THEN RAISE EXCEPTION 'PHASE29_STALE_AGREEMENT'; END IF;
 IF p_command='approve_sharing_agreement' THEN INSERT INTO dispatch_private.sharing_agreement_parties VALUES(oid,org,a.revision,mid,tok,now()); ELSE UPDATE dispatch_private.sharing_agreements SET revoked_at=now(),revision=revision+1 WHERE id=oid; END IF;
 END IF;
 ELSE
 IF p_command IN('review_report_publication','publish_report') THEN SELECT * INTO v FROM dispatch_private.publication_reviews WHERE id=oid AND organization_id=org FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'PHASE29_REVIEW_BOUNDARY'; END IF; rid:=v.record_id;
 ELSIF p_command='revoke_report_share' THEN SELECT record_id INTO rid FROM dispatch_private.shared_awareness_representations WHERE id=oid AND organization_id=org; END IF;
 SELECT * INTO d FROM dispatch_private.report_details WHERE record_id=coalesce(rid,oid) AND organization_id=org FOR UPDATE; IF NOT FOUND OR NOT dispatch_private.record_access(d.record_id,permission) THEN RAISE EXCEPTION 'PHASE29_SOURCE_BOUNDARY'; END IF; rid:=d.record_id;
 SELECT * INTO r FROM dispatch_private.operational_records WHERE id=rid;
 IF expected IS DISTINCT FROM d.revision OR d.source_revision<>r.current_revision THEN RAISE EXCEPTION 'PHASE29_STALE_REPORT'; END IF;
 IF p_command='set_road_impact' THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','record_id','object_id','expected_revision','impact_revision','impact']); x:=p->'impact';
 PERFORM dispatch_private.report_keys(x,ARRAY['segment_id','direction_affected','lane_extent','lanes_affected_count','total_lanes_count','closure_extent','traffic_operation','public_passable','emergency_vehicles_passable','start_lat','start_lon','end_lat','end_lon','duration_state','estimated_end_at','scheduled_start_at','impact_status','valid_until','passable_with_caution']);
 IF x->>'passable_with_caution'='true' AND (x->>'closure_extent' IS DISTINCT FROM 'PARTIAL' OR x->>'public_passable' IS DISTINCT FROM 'YES') THEN RAISE EXCEPTION 'PHASE29_CAUTION_RESTRICTION'; END IF;
 IF oid IS NOT NULL THEN SELECT revision INTO impact_revision FROM dispatch_private.road_impacts WHERE id=oid AND record_id=rid AND organization_id=org FOR UPDATE; IF NOT FOUND OR impact_revision IS DISTINCT FROM (p->>'impact_revision')::integer THEN RAISE EXCEPTION 'PHASE29_STALE_IMPACT'; END IF; ELSE oid:=extensions.gen_random_uuid(); END IF;
 INSERT INTO dispatch_private.road_impacts(id,organization_id,record_id,segment_id,direction_affected,lane_extent,lanes_affected_count,total_lanes_count,closure_extent,traffic_operation,public_passable,emergency_vehicles_passable,start_lat,start_lon,end_lat,end_lon,duration_state,estimated_end_at,reason_subtype,timing,scheduled_start_at,effective_start_at,impact_status,valid_until)
 VALUES(oid,org,rid,(x->>'segment_id')::uuid,coalesce(x->>'direction_affected','UNKNOWN'),coalesce(x->>'lane_extent','UNKNOWN'),(x->>'lanes_affected_count')::int,(x->>'total_lanes_count')::int,coalesce(x->>'closure_extent','UNKNOWN'),coalesce(x->>'traffic_operation','UNKNOWN'),coalesce(x->>'public_passable','UNKNOWN'),coalesce(x->>'emergency_vehicles_passable','UNKNOWN'),(x->>'start_lat')::numeric,(x->>'start_lon')::numeric,(x->>'end_lat')::numeric,(x->>'end_lon')::numeric,coalesce(x->>'duration_state','UNKNOWN'),(x->>'estimated_end_at')::timestamptz,d.subtype,d.timing,(x->>'scheduled_start_at')::timestamptz,CASE WHEN x->>'impact_status'='ACTIVE' THEN statement_timestamp() END,x->>'impact_status',(x->>'valid_until')::timestamptz) ON CONFLICT(id) DO UPDATE SET revision=dispatch_private.road_impacts.revision+1,segment_id=EXCLUDED.segment_id,direction_affected=EXCLUDED.direction_affected,lane_extent=EXCLUDED.lane_extent,lanes_affected_count=EXCLUDED.lanes_affected_count,total_lanes_count=EXCLUDED.total_lanes_count,closure_extent=EXCLUDED.closure_extent,traffic_operation=EXCLUDED.traffic_operation,public_passable=EXCLUDED.public_passable,emergency_vehicles_passable=EXCLUDED.emergency_vehicles_passable,start_lat=EXCLUDED.start_lat,start_lon=EXCLUDED.start_lon,end_lat=EXCLUDED.end_lat,end_lon=EXCLUDED.end_lon,duration_state=EXCLUDED.duration_state,estimated_end_at=EXCLUDED.estimated_end_at,reason_subtype=EXCLUDED.reason_subtype,last_confirmed_at=statement_timestamp(),timing=EXCLUDED.timing,scheduled_start_at=EXCLUDED.scheduled_start_at,effective_start_at=coalesce(dispatch_private.road_impacts.effective_start_at,EXCLUDED.effective_start_at),impact_status=EXCLUDED.impact_status,valid_until=EXCLUDED.valid_until;
 INSERT INTO dispatch_private.road_impact_revisions SELECT oid,i.revision,rid,d.source_revision,tok,to_jsonb(i),now() FROM dispatch_private.road_impacts i WHERE id=oid;
 UPDATE dispatch_private.report_details SET revision=revision+1,screening_state='PENDING_REVIEW' WHERE record_id=rid;
 ELSIF p_command='approve_report_content' THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','record_id','expected_revision']);
 IF d.author_token=tok OR d.screening_state<>'PENDING_REVIEW' OR dispatch_private.report_screen(jsonb_build_object('body',d.body,'subject',d.subject,'title',r.title)) THEN RAISE EXCEPTION 'PHASE29_CONTENT_APPROVAL_DENIED'; END IF;
 UPDATE dispatch_private.report_details SET screening_state='APPROVED' WHERE record_id=rid;
 INSERT INTO dispatch_private.content_screening_decisions(organization_id,record_id,source_revision,state,rule_version,content_digest,actor_token,independent_reviewer_token) VALUES(org,rid,d.source_revision,'APPROVED','PHASE29-SCREEN-v1',h,d.author_token,tok); oid:=rid;
 ELSIF p_command='submit_report_publication' THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','record_id','expected_revision','title','summary','grant_ids','valid_until']);
 IF d.screening_state<>'APPROVED' OR dispatch_private.report_screen(jsonb_build_object('title',p->>'title','summary',p->>'summary')) OR NOT EXISTS(SELECT 1 FROM dispatch_private.report_subtypes WHERE code=d.subtype AND public_eligible) THEN RAISE EXCEPTION 'PHASE29_PUBLIC_CONTENT'; END IF;
 grants:=ARRAY(SELECT value::uuid FROM jsonb_array_elements_text(p->'grant_ids')); IF NOT dispatch_private.report_grants_valid(rid,grants) OR (d.linked_record_id IS NOT NULL AND NOT dispatch_private.report_grants_valid(d.linked_record_id,grants)) THEN RAISE EXCEPTION 'PHASE29_CONJUNCTIVE_GATES'; END IF;
 deadline:=(p->>'valid_until')::timestamptz;
 IF deadline IS NULL OR deadline<=now() OR deadline>now()+interval '15 minutes' OR deadline>(SELECT min(valid_until) FROM dispatch_private.capability_grants WHERE id=ANY(grants)) OR deadline>(SELECT least(verification_expires_at,attestation_expires_at) FROM dispatch_private.pilot_governance WHERE organization_id=org) OR deadline>(SELECT valid_until FROM dispatch_private.scope_governance WHERE scope_id=r.operational_scope_id) OR deadline>coalesce((SELECT valid_until FROM dispatch_private.operational_scopes WHERE id=r.operational_scope_id),'infinity'::timestamptz) OR deadline>coalesce(d.notice_expires_at,'infinity'::timestamptz) OR EXISTS(SELECT 1 FROM dispatch_private.road_impacts WHERE record_id=rid AND deadline>least(valid_until,last_confirmed_at+interval '15 minutes')) THEN RAISE EXCEPTION 'PHASE29_PUBLIC_DEADLINE'; END IF;
 INSERT INTO dispatch_private.publication_reviews(organization_id,record_id,source_revision,details_revision,contract_version,policy_version,author_token,title,summary,grant_ids,valid_until) VALUES(org,rid,d.source_revision,d.revision,d.contract_version,'PHASE29-INDEPENDENT-v1',tok,p->>'title',p->>'summary',grants,deadline) RETURNING id INTO oid;
 ELSIF p_command='review_report_publication' THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','object_id','record_id','expected_revision','expected_candidate_revision','reviewer_authorization_id','acting_unit_id','decision']);
 IF (p->>'record_id')::uuid IS DISTINCT FROM v.record_id OR (p->>'expected_candidate_revision')::integer IS DISTINCT FROM v.candidate_revision OR NOT dispatch_private.report_review_state_valid(v.id) THEN RAISE EXCEPTION 'DAYTON_REVIEW_STALE_CANDIDATE'; END IF;
 IF NOT dispatch_private.report_reviewer_authorized(rid,(p->>'reviewer_authorization_id')::uuid,(p->>'acting_unit_id')::uuid,tok) THEN RAISE EXCEPTION 'DAYTON_REVIEW_AUTHORIZATION_DENIED'; END IF;
 IF v.state<>'PENDING_REVIEW' OR v.author_token=tok OR d.author_token=tok OR p->>'decision' NOT IN('APPROVED','REJECTED') THEN RAISE EXCEPTION 'PHASE29_INDEPENDENT_REVIEW'; END IF;
 UPDATE dispatch_private.publication_reviews SET state=p->>'decision',reviewer_token=tok,reviewer_authorization_id=(p->>'reviewer_authorization_id')::uuid,acting_unit_id=(p->>'acting_unit_id')::uuid,reviewed_at=now() WHERE id=oid;
 IF p->>'decision'='APPROVED' AND NOT dispatch_private.report_review_prerequisites(oid) THEN RAISE EXCEPTION 'DAYTON_REVIEW_LIVE_ELIGIBILITY_DENIED'; END IF;
 ELSIF p_command='publish_report' THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','object_id','expected_revision']);
 IF NOT dispatch_private.report_public_eligible(oid) THEN RAISE EXCEPTION 'PHASE29_PUBLICATION_DISABLED_OR_INELIGIBLE'; END IF;
 INSERT INTO dispatch_projection.report_public_projections(review_id,organization_id,unit_id,subtype,title,summary,public_impacts,expires_at) VALUES(oid,org,d.unit_id,d.subtype,v.title,v.summary,dispatch_private.report_safe_impacts(rid),v.valid_until) RETURNING id INTO oid;
 ELSIF p_command='withdraw_report' THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','record_id','expected_revision','reason_code']);
 IF p->>'reason_code' NOT IN('CORRECTION','EXPIRED','SAFETY','WITHDRAWN') THEN RAISE EXCEPTION 'PHASE29_REASON_CODE'; END IF;
 UPDATE dispatch_private.report_details SET withdrawn_at=now(),revision=revision+1 WHERE record_id=rid; oid:=rid;
 ELSIF p_command IN('quarantine_report','redact_report') THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','record_id','expected_revision','policy_reference']);
 IF length(p->>'policy_reference') NOT BETWEEN 1 AND 200 OR dispatch_private.report_screen(jsonb_build_object('policy',p->>'policy_reference')) THEN RAISE EXCEPTION 'PHASE29_POLICY_REFERENCE'; END IF;
 UPDATE dispatch_private.report_details SET screening_state='QUARANTINED',withdrawn_at=now(),revision=revision+1 WHERE record_id=rid;
 INSERT INTO dispatch_private.content_screening_decisions(organization_id,record_id,source_revision,state,rule_version,content_digest,actor_token) VALUES(org,rid,d.source_revision,'QUARANTINED','PHASE29-SCREEN-v1',h,tok) RETURNING id INTO sid;
 INSERT INTO dispatch_private.content_quarantine(organization_id,screening_decision_id,record_id,state,policy_reference) VALUES(org,sid,rid,'QUARANTINED',p->>'policy_reference') RETURNING id INTO qid;
 IF p_command='redact_report' THEN
 INSERT INTO dispatch_private.report_redaction_context VALUES(txid_current(),rid,p->>'policy_reference');
 UPDATE dispatch_audit.record_revisions SET snapshot=jsonb_build_object('redacted',true,'record_id',rid,'revision',revision_number) WHERE record_id=rid;
 UPDATE dispatch_private.operational_records SET title='[REDACTED]',private_payload='{}'::jsonb WHERE id=rid;
 UPDATE dispatch_private.report_details SET subject=CASE WHEN subject IS NOT NULL THEN '[REDACTED]' END,body=CASE WHEN body IS NOT NULL THEN '[REDACTED]' END,screening_state='REDACTED' WHERE record_id=rid;
 UPDATE dispatch_private.publication_reviews SET title='[REDACTED]',summary='[REDACTED]',state='WITHDRAWN' WHERE record_id=rid;
 UPDATE dispatch_projection.report_public_projections SET title='[REDACTED]',summary='[REDACTED]',withdrawn_at=now() WHERE review_id IN(SELECT id FROM dispatch_private.publication_reviews WHERE record_id=rid);
 UPDATE dispatch_private.shared_awareness_representations SET title='[REDACTED]',summary='[REDACTED]',revoked_at=now() WHERE record_id=rid;
 UPDATE dispatch_private.content_quarantine SET state='REDACTED',redacted_at=now() WHERE id=qid;
 DELETE FROM dispatch_private.report_redaction_context WHERE transaction_id=txid_current();
 END IF;
 INSERT INTO dispatch_audit.content_remediation_events(organization_id,quarantine_id,record_id,actor_token,policy_reference,event_type) VALUES(org,qid,rid,tok,p->>'policy_reference',CASE WHEN p_command='redact_report' THEN 'REDACTED' ELSE 'QUARANTINED' END); oid:=qid;
 ELSIF p_command='share_report' THEN
 PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','record_id','expected_revision','title','summary','agreement_id','recipient_unit_ids','valid_until','reviewer_token']);
 IF d.screening_state<>'APPROVED' OR NOT EXISTS(SELECT 1 FROM dispatch_private.report_subtypes WHERE code=d.subtype AND public_eligible) OR dispatch_private.report_screen(jsonb_build_object('title',p->>'title','summary',p->>'summary')) THEN RAISE EXCEPTION 'PHASE29_SHARE_CONTENT'; END IF;
 IF NOT EXISTS(SELECT 1 FROM dispatch_private.content_screening_decisions WHERE record_id=rid AND source_revision=d.source_revision AND state='APPROVED' AND independent_reviewer_token=(p->>'reviewer_token')::uuid AND independent_reviewer_token<>tok) THEN RAISE EXCEPTION 'PHASE29_SHARE_REVIEW'; END IF;
 deadline:=(p->>'valid_until')::timestamptz; IF deadline IS NULL OR deadline<=now() OR deadline>now()+interval '1 day' OR jsonb_array_length(p->'recipient_unit_ids') NOT BETWEEN 1 AND 20 THEN RAISE EXCEPTION 'PHASE29_SHARE_VALIDITY'; END IF;
 IF p ? 'agreement_id' THEN SELECT * INTO a FROM dispatch_private.sharing_agreements WHERE id=(p->>'agreement_id')::uuid AND source_organization_id=org AND revoked_at IS NULL AND valid_from<=now() AND valid_until>now() AND scope_id=r.operational_scope_id AND scope_version=(SELECT version FROM dispatch_private.operational_scopes WHERE id=r.operational_scope_id); IF NOT FOUND OR NOT d.subtype=ANY(a.allowed_subtypes) OR NOT a.allowed_fields@>ARRAY['title','summary'] OR (SELECT count(*) FROM dispatch_private.sharing_agreement_parties WHERE agreement_id=a.id AND agreement_revision=a.revision)<>2 OR deadline>a.valid_until THEN RAISE EXCEPTION 'PHASE29_BILATERAL_AGREEMENT'; END IF; END IF;
 oid:=extensions.gen_random_uuid();
 INSERT INTO dispatch_private.shared_awareness_representations(id,organization_id,record_id,source_revision,details_revision,agreement_id,author_token,reviewer_token,title,summary,valid_until) VALUES(oid,org,rid,d.source_revision,d.revision,(p->>'agreement_id')::uuid,tok,(p->>'reviewer_token')::uuid,p->>'title',p->>'summary',deadline);
 FOR x IN SELECT value FROM jsonb_array_elements(p->'recipient_unit_ids') LOOP uid:=(x#>>'{}')::uuid; SELECT organization_id INTO cap FROM dispatch_private.organization_units WHERE id=uid AND status='ACTIVE'; IF cap IS NULL OR (p ? 'agreement_id' AND (cap<>a.recipient_organization_id OR NOT EXISTS(SELECT 1 FROM dispatch_private.sharing_agreement_units WHERE agreement_id=a.id AND unit_id=uid))) OR (NOT p ? 'agreement_id' AND cap<>org) THEN RAISE EXCEPTION 'PHASE29_RECIPIENT_BOUNDARY'; END IF; INSERT INTO dispatch_private.shared_awareness_recipients VALUES(oid,cap,uid); END LOOP;
 ELSIF p_command='revoke_report_share' THEN PERFORM dispatch_private.report_keys(p,ARRAY['organization_id','idempotency_key','object_id','expected_revision']); UPDATE dispatch_private.shared_awareness_representations SET revoked_at=now(),revision=revision+1 WHERE id=oid AND organization_id=org;
 END IF;
 END IF;
 result:=coalesce(result,jsonb_build_object('object_id',oid,'replay',false));
 INSERT INTO dispatch_audit.command_receipts(organization_id,actor_user_id,session_id,command_name,idempotency_key,request_hash,result_payload,actor_token) VALUES(org,actor,dispatch_private.current_session_id(),p_command,k,h,result,tok);
 INSERT INTO dispatch_audit.command_versions(organization_id,command_name,object_id,expected_revision,revision,actor_token) VALUES(org,p_command,oid,expected,coalesce((SELECT revision FROM dispatch_private.report_details WHERE record_id=rid),1),tok);
 INSERT INTO dispatch_audit.pilot_events(organization_id,actor_token,command_name,target_id,revision,payload) VALUES(org,tok,p_command,oid,expected,jsonb_build_object('contract_version','PHASE29-v1','request_hash',encode(h,'hex'))||CASE WHEN p_command='review_report_publication' THEN (SELECT jsonb_build_object('author_token',pv.author_token,'reviewer_token',pv.reviewer_token,'decision',pv.state,'record_id',pv.record_id,'source_revision',pv.source_revision,'details_revision',pv.details_revision,'candidate_revision',pv.candidate_revision,'policy_version',pv.policy_version,'reviewer_policy_version',pv.reviewer_policy_version,'reviewer_authorization_id',pv.reviewer_authorization_id,'acting_unit_id',pv.acting_unit_id,'reviewed_at',pv.reviewed_at,'state_digest',(SELECT encode(state_digest,'hex') FROM dispatch_private.review_state_snapshots WHERE review_id=pv.id),'impact_revisions',(SELECT impact_revisions FROM dispatch_private.review_state_snapshots WHERE review_id=pv.id)) FROM dispatch_private.publication_reviews pv WHERE pv.id=oid) ELSE '{}'::jsonb END);
 RETURN result;
END $$;
