import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root=path.resolve(import.meta.dirname,'../..'), out=path.join(root,'reports/lp24111');
const read=f=>JSON.parse(fs.readFileSync(path.join(root,f),'utf8'));
const stable=x=>`${JSON.stringify(x,null,2)}\n`;
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex');
const release='2026-08-19.0', retrieved='2026-08-28';
const releaseUri=`s3://overturemaps-us-west-2/release/${release}/theme=places/type=place/*`;
const notExecuted='NOT_EXECUTED';

function artifacts(){
 const counties=read('data/lp104/texas-counties.json').counties;
 const place=read('data/generated/gridly-statewide-place-presentation-v1.json');
 const projection=read('data/generated/gridly-statewide-consumer-community-projection-v1.json');
 const cohort=read('reports/lp24110/statewide-poi-cohort.json');
 const map=read('tools/lp24111/category-map.json');
 const countyRows=counties.map(c=>({countyFips:c.fips,gridlyCountyId:c.countyId,countyName:c.countyName,assignmentAuthority:'CENSUS_COUNTY_GEOMETRY_SPATIAL_JOIN',rawPoiCount:null,normalizedCandidateCount:null,namedBusinessCount:null,categoryBearingCount:null,confidenceDistribution:null,addressCoverage:null,localityCoverage:null,brandCoverage:null,coverageFlag:'UNKNOWN_NOT_EXECUTED'}));
 const communityById=new Map(projection.communities.map(c=>[c.placeGeoid,c]));
 const anchors=Object.entries(place.places).map(([id,p])=>({communityId:id,communityName:communityById.get(id)?.displayName??null,presentationLatitude:p.lat,presentationLongitude:p.lon,radiusMiles:{5:null,10:null,25:null},coverageClass:'UNKNOWN_NOT_EXECUTED'}));
 const files={};
 files['overture-release.json']={schemaVersion:'gridly.lp24111.release.v1',releaseId:release,pinPolicy:'EXACT_RELEASE_ONLY',sourceUri:releaseUri,theme:'places',type:'place',retrievalDate:retrieved,sourceFormat:'GeoParquet',observedSchemaVersion:'UNKNOWN_PENDING_EXTRACTION',authorityState:'OWNER_TESTED_RELEASE; NETWORK_AUTHORITY_REVALIDATION_REQUIRED',retrieval:{duckdb:'1.5.5',powershellCommand:'powershell -File tools/lp24111/extract-texas.ps1'},licensingSources:['https://docs.overturemaps.org/attribution/','https://github.com/OvertureMaps/schema/blob/main/LICENSE']};
 files['schema-inventory.json']={schemaVersion:'gridly.lp24111.schema-inventory.v1',evidenceState:notExecuted,fields:[['id','REQUIRED_RUNTIME'],['names.primary','REQUIRED_RUNTIME'],['names.common/alternate','BUILD_ONLY'],['categories.primary','REQUIRED_RUNTIME'],['categories.alternate','BUILD_ONLY'],['addresses','USEFUL_RUNTIME'],['addresses.locality','USEFUL_RUNTIME'],['addresses.region','BUILD_ONLY'],['addresses.postcode','USEFUL_RUNTIME'],['geometry','REQUIRED_RUNTIME'],['bbox','NOT_REQUIRED'],['confidence','USEFUL_RUNTIME'],['brand','USEFUL_RUNTIME'],['websites','BUILD_ONLY'],['phones','BUILD_ONLY'],['operating_status','USEFUL_RUNTIME'],['sources','BUILD_ONLY']].map(([field,classification])=>({field,classification,observed:false}))};
 files['texas-extraction-summary.json']={schemaVersion:'gridly.lp24111.extraction.v1',executionState:notExecuted,reason:'No pinned-release extract is present in the repository; counts and sizes are not fabricated.',releaseId:release,sourceUri:releaseUri,geographicSelectionAuthority:'US Census TIGER/Line 2025 county geometries with STATEFP=48, dissolved; exact intersection, not address or rectangle',tool:'tools/lp24111/extract-texas.ps1',sql:'tools/lp24111/extract-texas.sql',rawTexasPoiCount:null,rawBytes:null,geoParquetBytes:null,durationSeconds:null,sourcePartitionsTouched:null,outputIgnored:true};
 files['county-coverage.json']={schemaVersion:'gridly.lp24111.county-coverage.v1',executionState:notExecuted,expectedCountyCount:254,accountedCountyCount:countyRows.length,rows:countyRows};
 files['community-coverage.json']={schemaVersion:'gridly.lp24111.community-coverage.v1',executionState:notExecuted,canonicalPlaceAuthority:'data/generated/gridly-statewide-place-presentation-v1.json',canonicalPlaceExpected:1859,canonicalPlaceAccounted:anchors.length,governedProjectionCommunityCount:projection.communities.length,radiiMiles:[5,10,25],thresholdPolicy:'PENDING_EMPIRICAL_DISTRIBUTION',classes:['NO_POI_COVERAGE','LOW_POI_COVERAGE','USEFUL_POI_COVERAGE','DENSE_POI_COVERAGE'],rows:anchors};
 files['category-coverage.json']={schemaVersion:'gridly.lp24111.category-coverage.v1',executionState:notExecuted,mappingSha256:sha('tools/lp24111/category-map.json'),mapping:map,results:Object.keys(map.categories).map(category=>({category,rawCount:null,normalizedCount:null,countiesRepresented:null}))};
 files['brand-coverage.json']={schemaVersion:'gridly.lp24111.brand-coverage.v1',executionState:notExecuted,brands:['Walmart','H-E-B','CVS','Walgreens','Starbucks',"McDonald's"].map(brand=>({brand,rawRecordCount:null,probableParentLocationCount:null,childPoiCount:null,duplicateClusters:null,countiesRepresented:null,geographicDistribution:null}))};
 files['duplicate-child-poi-analysis.json']={schemaVersion:'gridly.lp24111.conflation-audit.v1',executionState:notExecuted,classifications:['PARENT_POI','CHILD_POI','LIKELY_DUPLICATE','DISTINCT_POI','AMBIGUOUS'],signals:['stable ID/source relationship','normalized name','brand','address','coordinate proximity','phone','website','parent/child category','provenance','confidence'],rules:[{id:'walmart-child',parentPattern:'^walmart$',childPatterns:['pharmacy','bakery','vision center','photo center','auto care center','garden center'],action:'CLASSIFY_CHILD_ONLY_NO_PRODUCTION_DEDUPE'},{id:'coincident-identity',distanceMeters:25,requiresAny:['same normalized address','same phone','same website'],action:'LIKELY_DUPLICATE_REVIEW'}],counts:null};
 files['confidence-analysis.json']={schemaVersion:'gridly.lp24111.confidence.v1',executionState:notExecuted,candidateThresholds:[0.5,0.7,0.8,0.9],distributions:null,policy:'INSUFFICIENT_EVIDENCE_NO_THRESHOLD_RECOMMENDED'};
 files['address-locality-quality.json']={schemaVersion:'gridly.lp24111.address-quality.v1',executionState:notExecuted,metrics:{freeformAddress:null,locality:null,region:null,postcode:null},fallbackPolicy:'Use governed nearest community and spatially assigned county as context labels only; never fabricate a street address.'};
 files['normalized-schema-proposal.json']={schemaVersion:'gridly.lp24111.normalized-schema.v1',status:'PROPOSAL_NOT_RUNTIME',runtimeFields:{poiId:'string',name:'string',normalizedName:'string',brand:'string|null',primaryCategory:'string|null',gridlyCategories:'string[]',latitude:'number',longitude:'number',address:'string|null',locality:'string|null',postcode:'string|null',countyId:'string',confidence:'number|null',operatingStatus:'string|null',source:'OVERTURE'},buildOnlyFields:['alternateNames','alternateCategories','phones','websites','sourceRecords','conflationSignals','bbox'],zeroQueryCost:true};
 files['package-size-model.json']={schemaVersion:'gridly.lp24111.package-size.v1',executionState:notExecuted,measurements:{normalizedTexasBytes:null,gzipBytes:null,brotliBytes:null,averageCountyBytes:null,largestCountyBytes:null,ruralCountyBytes:null,metroCountyBytes:null,communityRadiusBytes:null},options:[{id:'A',design:'county JSON/JSONL',boundaryHandling:'county plus intersecting neighbor/radius manifest'},{id:'B',design:'compressed geographic shards'},{id:'C',design:'compact client index'},{id:'D',design:'Supabase governed index'},{id:'E',design:'hybrid static manifest plus bounded server search'}],provisionalRecommendation:'B: compressed spatial shards with small manifest and adjacent/radius shard expansion; certify only after measured extract',constraints:{cloudflareSingleAssetBytes:26214400,wholeTexasPhoneDownloadForbidden:true}};
 files['refresh-pipeline.json']={schemaVersion:'gridly.lp24111.refresh.v1',stages:['PIN','EXTRACT','NORMALIZE','CONFLATE','CATEGORY_MAP','SPATIAL_ASSIGN','PACKAGE','VERIFY','MANIFEST','DEPLOY'],cadence:'Evaluate each Overture release; promote only an explicitly pinned, verified release',changedRecordDetection:'stable place ID plus canonical normalized-record hash',invalidation:'rebuild changed spatial shards and dependency/neighbor manifests',manifest:'release, input hashes, tool hashes, row counts, shard hashes and sizes',rollback:'retain prior immutable manifest and shards',staleDetection:'alert when pinned release trails approved cadence; never silently follow latest'};
 files['attribution-licensing.json']={schemaVersion:'gridly.lp24111.licensing.v1',reviewState:'LEGAL_REVIEW_REQUIRED',authoritativeLinks:['https://docs.overturemaps.org/attribution/','https://docs.overturemaps.org/getting-data/'],claims:['Attribution and source-specific notices must be derived from the pinned extract source metadata.','Centralized About/Map attribution suitability is not certified.','Provenance must be retained build-side until counsel approves runtime notice design.'],legalGuarantee:false,networkVerificationState:'UNAVAILABLE_IN_BUILD_ENVIRONMENT'};
 files['osm-supplement-evaluation.json']={schemaVersion:'gridly.lp24111.osm-evaluation.v1',classification:'INSUFFICIENT_EVIDENCE',reason:'Neither executed Overture county/category results nor a matched Texas OSM increment audit exists.',odblReview:'LEGAL_REVIEW_REQUIRED',automaticCombination:false};
 files['lp24110-cohort-reconciliation.json']={schemaVersion:'gridly.lp24111.lp24110-reconciliation.v1',executionState:notExecuted,liveRuntimePassClaim:false,communities:cohort.communities.map(x=>({community:x.community,contextType:x.contextType,queries:x.queries,overtureCapability:'OWNER_OR_RAW_EVIDENCE_ONLY_OR_UNKNOWN',normalizedCapability:'NOT_EXECUTED'})),ownerObserved:[{area:'Dayton',evidence:['Walmart and child records','gas stations']},{area:'Dayton/Liberty',evidence:['hospital, emergency, urgent and other medical records']},{area:'Tarkington/rural',evidence:['H-E-B, Brookshire Brothers, Walmart, local markets, fuel and discount retail']},{area:'Pecos',evidence:['chain and local lodging']}],ownerEvidenceLabel:'OWNER_OBSERVED_NOT_INDEPENDENTLY_REPRODUCED'};
 files['certification.json']={schemaVersion:'gridly.lp24111.certification.v1',classifications:['OVERTURE_TEXAS_AUTHORITY_VIABLE_WITH_NORMALIZATION','MANUFACTURING_EXECUTION_REQUIRED','LEGAL_REVIEW_REQUIRED','OWNER_DECISION_REQUIRED'],basis:['Owner-observed POC supports promising raw category, brand, rural and lodging availability.','Statewide extract and measurements are not executed, so viability remains provisional.','Normalization and conflation are required before any runtime decision.'],productionPoiSearch:'NOT_LAUNCHED_NOT_CERTIFIED',zeroCostContract:'DESIGNED_NOT_RUNTIME_ACTIVATED'};
 files['exception-ledger.json']={schemaVersion:'gridly.lp24111.exceptions.v1',exceptions:[{id:'EXTRACT_NOT_EXECUTED',severity:'BLOCKER',affects:['county coverage','community coverage','categories','brands','duplicates','confidence','address quality','sizes']},{id:'RELEASE_AUTHORITY_REVALIDATION',severity:'BLOCKER',detail:'Owner-supplied future-dated release could not be independently reached from this environment.'},{id:'SCHEMA_NOT_OBSERVED',severity:'BLOCKER'},{id:'LICENSE_COUNSEL_REVIEW',severity:'BLOCKER'},{id:'OSM_INCREMENT_NOT_MEASURED',severity:'OPEN'}]};
 return files;
}

export function verify(){
 const a=artifacts();
 if(a['overture-release.json'].releaseId!==release || a['overture-release.json'].sourceUri.includes('latest')) throw Error('release is not pinned');
 if(a['county-coverage.json'].rows.length!==254 || new Set(a['county-coverage.json'].rows.map(x=>x.countyFips)).size!==254) throw Error('254-county accounting failed');
 if(a['community-coverage.json'].rows.length!==1859) throw Error('1,859 PLACE accounting failed');
 if(Object.keys(a['category-coverage.json'].mapping.categories).length!==10 || !a['category-coverage.json'].mapping.humanMedicalExclusions.includes('animal_hospital')) throw Error('category integrity failed');
 if(a['duplicate-child-poi-analysis.json'].rules.length<2) throw Error('conflation contract missing');
 if(!a['package-size-model.json'].constraints.wholeTexasPhoneDownloadForbidden) throw Error('bounded packaging missing');
 if(!a['attribution-licensing.json'].authoritativeLinks.length) throw Error('attribution missing');
 for(const f of ['js/app.js','js/lp24110-poi-search-certification.js']) if(a && !fs.existsSync(path.join(root,f))) throw Error(`runtime guard source absent ${f}`);
 return a;
}
const args=new Set(process.argv.slice(2)), a=verify();
if(args.has('--write')){fs.mkdirSync(out,{recursive:true}); for(const [f,v] of Object.entries(a)) fs.writeFileSync(path.join(out,f),stable(v)); console.log(`wrote ${Object.keys(a).length} LP241.11 artifacts`);}
else if(args.has('--verify')){for(const [f,v] of Object.entries(a)){const p=path.join(out,f); if(!fs.existsSync(p)||fs.readFileSync(p,'utf8')!==stable(v)) throw Error(`stale/missing ${f}`);} console.log(`verified ${Object.keys(a).length} LP241.11 artifacts`);}
else console.log('use --write or --verify');
