import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { buildReports, buildRouteRequest, validateDestination, validateRouteResponse, verify } from '../../tools/lp163/certify-statewide-destination-routing.mjs';

const reports=()=>buildReports();
test('selects a deterministic 16-county cohort with Liberty',()=>{const r=reports()['reports/lp163/representative-county-routing-results.json'];assert.equal(r.countyCount,16);assert.ok(r.counties.some(c=>c.countyFips==='48291'));assert.deepEqual(r.counties.map(c=>c.countyFips),r.counties.map(c=>c.countyFips).toSorted());assert.deepEqual(buildReports(),buildReports());});
test('preserves deterministic sampled identity and exact destination coordinates',()=>{const c=reports()['reports/lp163/destination-route-case-results.json'].cases;assert.equal(c.length,17);for(const x of c){assert.equal(x.destinationIdentifier,x.selectedResultIdentity);assert.deepEqual(x.selectedResultCoordinates,x.routeRequestDestinationCoordinates);assert.equal(x.coordinateEqualityResult,true);assert.equal(x.routeDestinationMarkerConsistency,true);assert.equal(x.certificationResult,'PASS');}});
test('constructs provider requests without centroid or midpoint fallback',()=>{const d={destinationId:'id',consumerDisplayName:'Place',latitude:30.1,longitude:-94.2};const r=buildRouteRequest({latitude:30,longitude:-94},d);assert.equal(r.ok,true);assert.deepEqual(r.destination,{latitude:30.1,longitude:-94.2});assert.equal('fallback' in r,false);});
test('invalid coordinates and missing identity fail honestly',()=>{assert.equal(validateDestination({destinationId:'x',consumerDisplayName:'x',latitude:91,longitude:0}).classification,'INVALID_DESTINATION');assert.equal(validateDestination({latitude:30,longitude:-94}).classification,'INVALID_DESTINATION');});
test('malformed and geometry-free provider responses never certify',()=>{for(const x of [{},{routes:[]},{routes:[{}]},{routes:[{geometry:{coordinates:[[1,2]]}}]}])assert.deepEqual(validateRouteResponse(x),{ok:false,classification:'INVALID_ROUTE_RESPONSE',geometryAvailable:false});});
test('valid recorded contract shape yields geometry, distance and travel time',()=>{const r=validateRouteResponse({routes:[{geometry:{coordinates:[[1,2],[3,4]]},distance:5,duration:6}]});assert.equal(r.ok,true);assert.equal(r.geometryAvailable,true);assert.equal(r.distanceAvailable,true);assert.equal(r.travelTimeAvailable,true);});
test('integration audits preview, intelligence, Route Watch, awareness and favorites',()=>{const r=reports()['reports/lp163/routing-integration-results.json'];assert.equal(r.status,'PASS');for(const k of ['networkRequired','exactRequestOrder','validatesGeometry','truthfulProviderFailure','routePreviewRequiresLayer','routeIntelligence','routeWatch','awareness','favorites'])assert.equal(r.audit[k],true,k);});
test('Liberty and unresolved address truth remain preserved',()=>{const l=reports()['reports/lp163/liberty-preservation-results.json'];assert.equal(l.status,'PASS');assert.equal(l.unresolvedAddress.classification,'NO_VERIFIED_RESULT');assert.equal(l.unresolvedAddress.interpolation,false);assert.equal(l.unresolvedAddress.nearbyNumberSubstitution,false);assert.equal(l.unresolvedAddress.inferredMatch,false);});
test('runtime, deployment, activation and manufacturing remain protected',()=>{const m=reports()['reports/lp163/statewide-destination-routing-certification.json'];assert.equal(m.performsManufacturingChange,false);assert.equal(m.performsRuntimeChange,false);assert.equal(m.performsDeploymentChange,false);assert.equal(m.performsActivationChange,false);assert.equal(m.protectedArtifactsModified,false);assert.equal(m.finalClassification,'CONDITIONALLY_CERTIFIED_LIVE_NETWORK_VALIDATION_REQUIRED');});
test('governed reports verify read-only and use canonical LF',()=>{const before=readFileSync('reports/lp163/lp163-summary.json');verify();assert.deepEqual(readFileSync('reports/lp163/lp163-summary.json'),before);for(const p of Object.keys(reports()))assert.equal(readFileSync(p).includes(13),false,p);});
