// Synthetic contract certification only. No geometry computation, authority,
// live sources, UI wiring or government identity certification is established.
import test from 'node:test';
import assert from 'node:assert/strict';
import {createCatalogue,resolveScope,createPerspective,selectPerspective,requestReframe,evaluateAwareness,PERSPECTIVES,STATES,REASONS,LIMITS} from '../dispatch/awareness-perspective.mjs';
const provenance={id:'fixture-geography',version:'snapshot-1',evidenceRef:'synthetic:reviewed-geography-1'};
const feed={id:'fixture-feed',version:'feed-1',evidenceRef:'synthetic:read-only-feed-1'};
const origin=()=>({version:'catalogue-1',sources:[{...provenance}],counties:[
 {fips:'48201',label:'Duplicate label',sourceId:provenance.id,sourceVersion:provenance.version,neighbors:['48157']},
 {fips:'48157',label:'Duplicate label',sourceId:provenance.id,sourceVersion:provenance.version,neighbors:['48201','48039']},
 {fips:'48039',label:'Third county',sourceId:provenance.id,sourceVersion:provenance.version,neighbors:['48157']}
],localities:[
 {canonicalId:'locality:fixture-alpha',label:'Same name',sourceId:provenance.id,sourceVersion:provenance.version,counties:['48201','48157']},
 {canonicalId:'locality:fixture-beta',label:'Same name',sourceId:provenance.id,sourceVersion:provenance.version,counties:['48039']}
],regions:[{canonicalId:'region:fixture-pair',label:'Configured region',sourceId:provenance.id,sourceVersion:provenance.version,counties:['48201','48157']}]});
const pins=()=>({version:'catalogue-1',sources:[{...provenance}]});
const catalog=()=>createCatalogue(origin(),pins());
const refs={LOCAL:'locality:fixture-alpha',COUNTY:'county:48201',REGIONAL:'region:fixture-pair'};
const ref=(kind='COUNTY',extra={})=>({perspective:kind,canonicalId:refs[kind],catalogueVersion:'catalogue-1',sourceVersion:'snapshot-1',...extra});
const area=(kind='COUNTY')=>resolveScope(catalog(),ref(kind));
const evidence=(s,reason='INSIDE_SELECTED_AREA',extra={})=>({reason,method:'GOVERNED_MEMBERSHIP',scopeIdentity:s.identity,reference:'synthetic:membership-evidence',...extra});
const record=(s,extra={})=>({sourceId:feed.id,sourceVersion:feed.version,nativeId:'record-1',revision:1,withdrawn:false,stale:false,catalogueVersion:s.catalogueVersion,countyFips:['48157','48201'],localityIds:['locality:fixture-alpha'],evidence:[evidence(s)],...extra});
const request=(s,extra={})=>({disclosure:{allowed:true,scopeIdentity:s.identity,sourceId:feed.id,decisionVersion:'decision-1'},source:{...feed},expectedSourceVersion:feed.version,health:'HEALTHY',coverage:'COMPLETE',nearbyMeters:1000,records:[record(s)],...extra});
const throws=f=>assert.throws(f,/AWARENESS_/);
function deeplyFrozen(value){if(value&&typeof value==='object'){assert.ok(Object.isFrozen(value));for(const x of Object.values(value))deeplyFrozen(x);}}

test('explicit perspective, coverage and relevance enums carry no role names',()=>{assert.deepEqual(PERSPECTIVES,['LOCAL','COUNTY','REGIONAL']);assert.equal(STATES.length,5);assert.equal(REASONS.length,4);deeplyFrozen(LIMITS);});
for(const kind of PERSPECTIVES)test(kind+' resolves canonical identity and exact source/catalogue versions',()=>{const s=area(kind);assert.equal(s.canonicalId,refs[kind]);assert.equal(s.source.version,'snapshot-1');assert.equal(s.catalogueVersion,'catalogue-1');assert.equal(s.certification.authority,'UNVERIFIED');deeplyFrozen(s);});
test('multi-county locality retains every sorted governed membership',()=>assert.deepEqual(area('LOCAL').countyFips,['48157','48201']));
test('regional memberships are explicitly configured; no implicit county expansion',()=>assert.deepEqual(area('REGIONAL').countyFips,['48157','48201']));
test('duplicate labels never collapse canonical localities or counties',()=>{const c=catalog();assert.equal(c.localities.length,2);assert.equal(c.counties.length,3);assert.notEqual(resolveScope(c,ref('LOCAL')).identity,resolveScope(c,ref('LOCAL',{canonicalId:'locality:fixture-beta'})).identity);});
test('renaming display labels does not change scope identity',()=>{const input=origin();input.counties[0].label='Renamed';assert.equal(resolveScope(createCatalogue(input,pins()),ref()).identity,area().identity);});
for(const change of [{canonicalId:'county:48999'},{canonicalId:'Duplicate label'},{canonicalId:''},{catalogueVersion:'old'},{sourceVersion:'old'},{perspective:'POLICE'},{canonicalId:'region:fixture-pair'}])test('unknown, ambiguous or stale scope rejects '+JSON.stringify(change),()=>throws(()=>resolveScope(catalog(),ref('COUNTY',change))));
test('changed catalogue source, evidence reference or snapshot cannot borrow old pins',()=>{for(const key of ['version','evidenceRef']){const v=origin();v.sources[0][key]='changed';throws(()=>createCatalogue(v,pins()));}const v=origin();v.version='catalogue-2';throws(()=>createCatalogue(v,pins()));});
test('stale entry source version rejects independently of registry version',()=>{const v=origin();v.localities[0].sourceVersion='old';throws(()=>createCatalogue(v,pins()));});
for(const code of ['4820','48000','00001','99999',48201])test('malformed FIPS rejected '+code,()=>{const v=origin();v.counties[0].fips=code;throws(()=>createCatalogue(v,pins()));});
test('empty, duplicate and unknown region memberships reject',()=>{for(const members of [[],['48201','48201'],['48999']]){const v=origin();v.regions[0].counties=members;throws(()=>createCatalogue(v,pins()));}});
test('ambiguous identity, source and membership duplicates reject',()=>{for(const change of [v=>v.sources.push({...v.sources[0]}),v=>v.counties.push({...v.counties[0]}),v=>v.localities.push({...v.localities[0]}),v=>v.localities[0].counties.push('48201')]){const v=origin();change(v);throws(()=>createCatalogue(v,pins()));}});
test('neighbor membership must be known, reciprocal and non-self',()=>{for(const members of [['48201'],['48999'],['48039']]){const v=origin();v.counties[0].neighbors=members;throws(()=>createCatalogue(v,pins()));}});
test('Home Area survives perspective switching without authorization or camera actions',()=>{const c=catalog(),home=resolveScope(c,ref('LOCAL')),county=resolveScope(c,ref()),region=resolveScope(c,ref('REGIONAL'));const a=createPerspective(home),b=selectPerspective(selectPerspective(a,county),region);assert.equal(b.homeArea,home);assert.equal(b.viewArea,region);assert.equal(b.cameraAction,'NONE');assert.equal(b.privilegeAction,'NONE');assert.deepEqual(Object.keys(b).sort(),['cameraAction','certification','homeArea','privilegeAction','viewArea']);deeplyFrozen(b);assert.equal(a.viewArea,home);});
test('camera reframing requires an explicit HOME or VIEW request',()=>{const s=createPerspective(area());throws(()=>requestReframe(s,'AUTO'));assert.equal(requestReframe(s,'HOME').action,'REFRAME_REQUEST');assert.equal(requestReframe(s,'VIEW').target,s.viewArea);assert.ok(!('camera' in requestReframe(s,'HOME')));});
test('a state cannot adopt a different catalogue even with matching display data',()=>{const s=createPerspective(area());throws(()=>selectPerspective(s,area('REGIONAL')));throws(()=>createPerspective(area('LOCAL'),area()));});
for(const kind of PERSPECTIVES)test(kind+' inside membership returns available identity-only information',()=>{const s=area(kind),r=evaluateAwareness(s,request(s));assert.equal(r.state,'AVAILABLE_INFORMATION');assert.equal(r.items.length,1);assert.equal(r.items[0].nativeId,'record-1');assert.equal(r.items[0].revision,1);assert.equal(r.safetyAssessment,'NOT_ESTABLISHED');deeplyFrozen(r);});
test('locality relevance cannot be inferred just from matching county membership',()=>{const s=area('LOCAL');const r=evaluateAwareness(s,request(s,{records:[record(s,{localityIds:[]})]}));assert.equal(r.state,'HEALTHY_NO_MATCHING_INCIDENTS');});
test('healthy complete zero results never certify safety',()=>{const s=area(),r=evaluateAwareness(s,request(s,{records:[]}));assert.equal(r.state,'HEALTHY_NO_MATCHING_INCIDENTS');assert.equal(r.certification.safety,'NOT_ESTABLISHED');});
for(const health of ['UNAVAILABLE','STALE'])test('source '+health+' is distinct from healthy zero and does not inspect records',()=>{const s=area(),input=request(s,{health,records:null});assert.equal(evaluateAwareness(s,input).state,'SOURCE_UNAVAILABLE_OR_STALE');});
for(const coverage of ['PARTIAL','UNAVAILABLE'])test('coverage '+coverage+' is distinct from quiet and does not inspect records',()=>{const s=area();assert.equal(evaluateAwareness(s,request(s,{coverage,records:null})).state,'GEOGRAPHIC_COVERAGE_UNAVAILABLE');});
test('permission denial does not read or disclose any protected source or record fields',()=>{const s=area();let reads=0;const input={disclosure:{allowed:false}};for(const key of ['records','source','health','coverage'])Object.defineProperty(input,key,{enumerable:true,get(){reads++;throw Error('protected');}});const r=evaluateAwareness(s,input);assert.equal(reads,0);assert.equal(r.state,'PERMISSION_DENIED');assert.deepEqual(r.items,[]);assert.deepEqual(r.history,[]);assert.ok(!('source' in r));assert.ok(!('count' in r));});
test('missing disclosure and forged scope decision fail closed before data inspection',()=>{const s=area();assert.equal(evaluateAwareness(s,{}).state,'PERMISSION_DENIED');const r=request(s);r.disclosure.scopeIdentity='forged';r.records=null;assert.equal(evaluateAwareness(s,r).state,'PERMISSION_DENIED');});
test('wrong disclosure source and unreviewed provider versions reject',()=>{const s=area();throws(()=>evaluateAwareness(s,request(s,{source:{...feed,id:'other'}})));throws(()=>evaluateAwareness(s,request(s,{expectedSourceVersion:'old'})));});
test('nearby county point evidence remains point evidence, never polygon crossing',()=>{const s=area(),near=evidence(s,'NEARBY',{method:'POINT_DISTANCE',distanceMeters:200});const r=record(s,{countyFips:['48157'],localityIds:[],evidence:[near]});const out=evaluateAwareness(s,request(s,{records:[r]}));assert.deepEqual(out.items[0].evidence.map(e=>e.reason),['NEARBY']);assert.equal(out.items[0].evidence[0].method,'POINT_DISTANCE');});
test('distance threshold and governed neighbor relationship both constrain nearby relevance',()=>{const s=area(),e=evidence(s,'NEARBY',{method:'POINT_DISTANCE',distanceMeters:200});for(const extra of [{countyFips:['48039']},{countyFips:['48157'],evidence:[{...e,distanceMeters:2000}]}]){const r=record(s,{countyFips:['48157'],localityIds:[],evidence:[e],...extra});assert.equal(evaluateAwareness(s,request(s,{records:[r]})).items.length,0);}});
test('a region includes every configured county plus separately evidenced adjacent relevance',()=>{const s=area('REGIONAL'),e=evidence(s,'NEARBY',{method:'POINT_DISTANCE',distanceMeters:500});const r=record(s,{countyFips:['48039'],localityIds:[],evidence:[e]});assert.equal(evaluateAwareness(s,request(s,{records:[r]})).items.length,1);});
test('cross-boundary relevance requires referenced polygon intersection and crossing evidence',()=>{const s=area(),e=evidence(s,'CROSSES_SELECTED_BOUNDARY',{method:'POLYGON_INTERSECTION',intersects:true,crossesBoundary:true});assert.equal(evaluateAwareness(s,request(s,{records:[record(s,{evidence:[e]})]})).items[0].evidence[0].reason,'CROSSES_SELECTED_BOUNDARY');throws(()=>evaluateAwareness(s,request(s,{records:[record(s,{evidence:[{...e,method:'POINT_DISTANCE',distanceMeters:100}]})]})));throws(()=>evaluateAwareness(s,request(s,{records:[record(s,{evidence:[{...e,crossesBoundary:false}]})]})));});
test('point proximity cannot establish a corridor impact; documentary evidence can',()=>{const s=area(),e=evidence(s,'AFFECTS_SELECTED_CORRIDOR',{method:'DOCUMENTED_CORRIDOR_IMPACT',corridorId:'corridor:fixture-1'});assert.equal(evaluateAwareness(s,request(s,{records:[record(s,{evidence:[e]})]})).items.length,1);throws(()=>evaluateAwareness(s,request(s,{records:[record(s,{evidence:[{...e,method:'POINT_DISTANCE',distanceMeters:50}]})]})));});
test('incomplete geographic evidence prevents a false quiet result',()=>{const s=area();assert.equal(evaluateAwareness(s,request(s,{records:[record(s,{evidence:[evidence(s,'INSIDE_SELECTED_AREA',{method:'INCOMPLETE'})]})]})).state,'GEOGRAPHIC_COVERAGE_UNAVAILABLE');assert.equal(evaluateAwareness(s,request(s,{records:[record(s,{countyFips:[],localityIds:[],evidence:[]})]})).state,'GEOGRAPHIC_COVERAGE_UNAVAILABLE');});
test('partial multi-county record membership rejects rather than collapsing the locality',()=>{const s=area();throws(()=>evaluateAwareness(s,request(s,{records:[record(s,{countyFips:['48201']})]})));});
for(const change of [{catalogueVersion:'old'},{sourceVersion:'old'},{countyFips:['48999']},{localityIds:['locality:unknown']},{revision:0},{withdrawn:'false'}])test('stale/malformed native record rejects '+JSON.stringify(change),()=>{const s=area();throws(()=>evaluateAwareness(s,request(s,{records:[record(s,change)]})));});
test('evidence bound to an old scope rejects',()=>{const s=area();throws(()=>evaluateAwareness(s,request(s,{records:[record(s,{evidence:[{...evidence(s),scopeIdentity:'old'}]})]})));});
test('withdrawal revision wins regardless of arrival order; no record duplication',()=>{const s=area(),old=record(s),withdrawn=record(s,{revision:2,withdrawn:true});for(const records of [[old,withdrawn,old],[withdrawn,old]]){const r=evaluateAwareness(s,request(s,{records}));assert.equal(r.state,'HEALTHY_NO_MATCHING_INCIDENTS');assert.equal(r.items.length,0);assert.deepEqual(r.history,[{sourceId:feed.id,sourceVersion:feed.version,nativeId:'record-1',revision:2,withdrawn:true,stale:false}]);}});
test('same-revision conflicting withdrawal is ambiguous and rejected',()=>{const s=area();throws(()=>evaluateAwareness(s,request(s,{records:[record(s),record(s,{withdrawn:true})]})));});
test('stale current records cannot be described as healthy quiet conditions',()=>{const s=area(),r=evaluateAwareness(s,request(s,{records:[record(s,{stale:true})]}));assert.equal(r.state,'SOURCE_UNAVAILABLE_OR_STALE');assert.equal(r.history[0].stale,true);});
test('a newer current revision supersedes older stale evidence',()=>{const s=area();const r=evaluateAwareness(s,request(s,{records:[record(s,{stale:true}),record(s,{revision:2})]}));assert.equal(r.items.length,1);assert.equal(r.items[0].revision,2);});
test('source namespaces remain separate and native IDs cannot be silently reassigned',()=>{const s=area();throws(()=>evaluateAwareness(s,request(s,{records:[record(s,{sourceId:'other-feed'})]})));const second={...feed,id:'fixture-feed-two'};const input=request(s,{source:second,records:[record(s,{sourceId:second.id})]});input.disclosure.sourceId=second.id;assert.equal(evaluateAwareness(s,input).items[0].sourceId,second.id);});
test('deterministic immutable outputs do not freeze or mutate caller-owned inputs',()=>{const s=area(),input=request(s,{records:[record(s,{nativeId:'z'}),record(s,{nativeId:'a'})]}),before=JSON.stringify(input);const first=evaluateAwareness(s,input);input.records.reverse();assert.deepEqual(first,evaluateAwareness(s,input));assert.deepEqual(first.items.map(r=>r.nativeId),['a','z']);assert.equal(Object.isFrozen(input.records),false);input.records[0].nativeId='changed';assert.equal(first.items[0].nativeId,'a');assert.equal(before.includes('"z"'),true);deeplyFrozen(first);});
test('source and canonical catalogue input ordering do not change resolved identity',()=>{const v=origin();v.counties.reverse();v.localities.reverse();v.regions[0].counties.reverse();assert.equal(resolveScope(createCatalogue(v,pins()),ref('REGIONAL')).identity,area('REGIONAL').identity);});
test('no authorization fields are accepted into scopes or incident records',()=>{const c=catalog();throws(()=>resolveScope(c,{...ref(),role:'OWNER'}));const s=area();throws(()=>evaluateAwareness(s,request(s,{records:[{...record(s),permissions:['publish']}]})));});
test('unknown keys, object getters and sparse/custom arrays reject without execution',()=>{const v=origin();v.authority='OWNER';throws(()=>createCatalogue(v,pins()));const getter=origin();Object.defineProperty(getter.counties[0],'label',{get(){throw Error('must not execute');},enumerable:true});throws(()=>createCatalogue(getter,pins()));const sparse=origin();sparse.localities=Array(1);throws(()=>createCatalogue(sparse,pins()));const custom=origin();custom.counties.map=()=>[];throws(()=>createCatalogue(custom,pins()));});
test('bounded record, catalogue, membership and evidence budgets fail closed',()=>{const s=area();throws(()=>evaluateAwareness(s,request(s,{records:Array.from({length:LIMITS.records+1},()=>record(s))})));const v=origin();v.counties=Array.from({length:LIMITS.counties+1},()=>v.counties[0]);throws(()=>createCatalogue(v,pins()));const e=origin();e.regions[0].counties=Array(LIMITS.memberships+1).fill('48201');throws(()=>createCatalogue(e,pins()));throws(()=>evaluateAwareness(s,request(s,{records:[record(s,{evidence:Array(LIMITS.evidence+1).fill(evidence(s))})]})));});
test('invalid health, coverage, nearby ranges and numeric revisions reject',()=>{const s=area();for(const change of [{health:'SAFE'},{coverage:'KNOWN'},{nearbyMeters:-1},{nearbyMeters:NaN},{nearbyMeters:LIMITS.nearbyMeters+1}])throws(()=>evaluateAwareness(s,request(s,change)));for(const revision of [NaN,Infinity,1.5,-1])throws(()=>evaluateAwareness(s,request(s,{records:[record(s,{revision})]})));});
test('incomplete neighboring context and prototype/cyclic inputs cannot become geography',()=>{const v=origin();v.counties[0].neighbors.push('48999');throws(()=>createCatalogue(v,pins()));throws(()=>createCatalogue(Object.create(origin()),pins()));const cyc=origin();cyc.localities[0].counties=[cyc];throws(()=>createCatalogue(cyc,pins()));});
test('known membership without relevance evidence is unknown coverage, never quiet',()=>{const s=area();assert.equal(evaluateAwareness(s,request(s,{records:[record(s,{evidence:[]})]})).state,'GEOGRAPHIC_COVERAGE_UNAVAILABLE');});
