import test from 'node:test';import assert from 'node:assert/strict';import {generateOccurrences,wallInstant,workStatus,changedDates,scheduleSummary} from '../dispatch/notice-schedule.mjs';
const project={start:'2026-10-09',end:'2026-10-15',timezone:'America/Chicago'},schedule={mode:'weekdays',weekdays:[1,2,3,4,5],startTime:'06:00',endTime:'16:00',exceptions:{}};
test('October 9–15 selected weekdays yield five exact Chicago occurrences',()=>{const o=generateOccurrences(project,schedule);assert.deepEqual(o.map(o=>o.date),['2026-10-09','2026-10-12','2026-10-13','2026-10-14','2026-10-15']);assert.equal(o[0].start,'2026-10-09T11:00:00.000Z');assert.equal(o[0].end,'2026-10-09T21:00:00.000Z');assert.match(scheduleSummary(project,schedule),/Monday.*Friday.*America\/Chicago/);});
for(let d=0;d<7;d++)test('weekday '+d+' maps Sunday through Saturday',()=>{const o=generateOccurrences({start:'2026-10-11',end:'2026-10-17',timezone:'UTC'},{...schedule,weekdays:[d]});assert.equal(o[0].date,'2026-10-'+String(11+d));});
test('work clock uses inclusive start and exclusive end; does not declare road status',()=>{const o=generateOccurrences(project,schedule);assert.equal(workStatus(o,Date.parse(o[0].start)-1),'Scheduled');assert.equal(workStatus(o,Date.parse(o[0].start)),'Within Scheduled Work Window');assert.equal(workStatus(o,Date.parse(o[0].end)-1),'Within Scheduled Work Window');assert.equal(workStatus(o,Date.parse(o[0].end)),'Outside Scheduled Work Hours');});
test('one-time stays under first date; continuous retains full day boundaries including weekends',()=>{assert.equal(generateOccurrences(project,{...schedule,mode:'once'}).length,1);const o=generateOccurrences(project,{...schedule,mode:'continuous'});assert.equal(o.length,7);assert.equal(o[6].end,'2026-10-16T05:00:00.000Z');});
test('spring and fall continuous days have exact 23/25 hour durations',()=>{for(const [date,hours]of [['2026-03-08',23],['2026-11-01',25]]){const [o]=generateOccurrences({start:date,end:date,timezone:'America/Chicago'},{...schedule,mode:'continuous'});assert.equal((Date.parse(o.end)-Date.parse(o.start))/3600000,hours);}});
test('DST ambiguous and nonexistent times refuse; other zones interpreted independently',()=>{assert.throws(()=>wallInstant('2026-03-08','02:30','America/Chicago'),/Nonexistent/);assert.throws(()=>wallInstant('2026-11-01','01:30','America/Chicago'),/Ambiguous/);assert.equal(wallInstant('2026-10-09','06:00','Asia/Kolkata'),'2026-10-09T00:30:00.000Z');});
test('skips and individual modified occurrences preserve date identity and affected-date review',()=>{const before=generateOccurrences(project,schedule),after=generateOccurrences(project,{...schedule,exceptions:{'2026-10-12':{kind:'skip'},'2026-10-13':{kind:'modify',startTime:'08:00',endTime:'12:00'}}});assert.equal(after.length,4);assert.equal(after.find(o=>o.date==='2026-10-13').start,'2026-10-13T13:00:00.000Z');assert.deepEqual(changedDates(before,after),['2026-10-12','2026-10-13']);});
for(const [label,p,s]of [['reversed dates',{...project,end:'2026-10-08'},schedule],['invalid calendar',{...project,start:'2026-02-30'},schedule],['range limit',{...project,end:'2028-10-09'},schedule],['invalid timezone',{...project,timezone:'Fake/Zone'},schedule],['no weekdays',project,{...schedule,weekdays:[]}],['duplicate weekday',project,{...schedule,weekdays:[1,1]}],['bad weekday',project,{...schedule,weekdays:[7]}],['overnight',project,{...schedule,startTime:'20:00',endTime:'06:00'}],['equal times',project,{...schedule,endTime:'06:00'}],['excluded exception',project,{...schedule,exceptions:{'2026-10-10':{kind:'skip'}}}],['empty recurrence',{...project,start:'2026-10-10',end:'2026-10-11'},schedule],['all skipped',project,{...schedule,mode:'once',exceptions:{'2026-10-09':{kind:'skip'}}}]])test('rejects '+label,()=>assert.throws(()=>generateOccurrences(p,s)));

test('timezone abbreviations are blocked to avoid ambiguous interpretation',()=>assert.throws(()=>wallInstant('2026-10-09','06:00','CST'),/IANA/));
