import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {chromium} from '@playwright/test';
import {previewServer} from '../tools/dispatch-ui/serve.mjs';
import {approvedBoardServer,sameMapPixels} from '../tools/dispatch-ui/approved-board.mjs';
import {markerCategories,opticalFit} from '../dispatch/marker-language.mjs';
let browser,server,baseline,base,approved;
const evidence=new URL('../reports/responder/dispatch-marker-normalization/',import.meta.url);
const listen=s=>new Promise(r=>s.listen(0,'127.0.0.1',()=>r(`http://127.0.0.1:${s.address().port}`)));
before(async()=>{server=previewServer({demo:true});baseline=approvedBoardServer('6bdccd803e9a30d294db7a3bbc015e86ce485210');base=await listen(server);approved=await listen(baseline);browser=await chromium.launch({headless:true,channel:process.env.DISPATCH_BROWSER_CHANNEL||'msedge'});await mkdir(evidence,{recursive:true});});
after(async()=>{await browser?.close();server?.close();baseline?.close();});
const path=n=>new URL(n+'.png',evidence).pathname.replace(/^\/([A-Z]:)/,'$1');
const view=p=>p.getByRole('combobox',{name:'View',exact:true});
const ready=p=>p.locator('[data-marker]').first().waitFor();
async function visit(fn,{theme='dark',width=1440,height=900}={}){const c=await browser.newContext({viewport:{width,height}});await c.addInitScript(t=>localStorage.setItem('gridlyDispatchTheme',t),theme);const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{await fn(p);assert.deepEqual(errors,[]);}finally{await c.close();}}
async function stable(p,options={}){let old=await protectedShot(p,options);for(let i=0;i<5;i++){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const now=await protectedShot(p,options);if(old.equals(now))return now;old=now;}throw new Error('Unsettled screenshot');}
const geometry=p=>p.locator('.geo-layout,.geo-list-panel,.geo-list-row,#dispatch-map,.map-caption,.map-credit,.geo-filters,.topbar,.sidebar,.shell-footer').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return [r.x,r.y,r.width,r.height];}));
test('each unchanged PNG fits the same optical target with uniform scale and fixed anchors',async()=>{for(const c of Object.values(markerCategories)){assert.ok((await readFile(new URL('../dispatch/assets/markers/'+c.asset,import.meta.url))).equals(await readFile(new URL('../assets/markers/png/'+c.asset,import.meta.url))));const f=opticalFit(c),ratio=f.scale*80/256;assert.ok(Math.abs(c.optical.diameter*ratio-35)<1e-9);assert.ok(Math.abs(f.x+c.optical.cx*ratio-40)<1e-9);assert.ok(Math.abs(f.y+c.optical.cy*ratio-30)<1e-9);assert.ok(c.tip>.7&&c.tip<.9);}});
for(const theme of ['dark','light'])test(`${theme}: four-category side-by-side and real map certification`,()=>visit(async p=>{
  const requests=[];p.on('request',r=>requests.push([r.url(),r.method()]));await p.goto(base+'/?demo=1&view=split');await ready(p);
  for(const unit of ['police','works'])for(const mode of ['split','map']){await p.getByLabel('ACTING UNIT').selectOption(unit);await view(p).selectOption(mode);await ready(p);const ids=unit==='police'?['DEMO-001','DEMO-002']:['DEMO-003','DEMO-004'];await p.screenshot({path:path(`${theme}-${unit}-${mode}-unselected`)});
    for(const id of ids){const marker=p.locator(`[data-marker="${id}"]`);const transformed=await marker.locator('img').evaluate(e=>getComputedStyle(e).transform);assert.notEqual(transformed,'none');const expected=opticalFit(Object.values(markerCategories)[Number(id.slice(-1))-1]);const rendered=await marker.locator('img').evaluate(e=>e.getBoundingClientRect().width);assert.ok(Math.abs(rendered-80*expected.scale)<.01);const shell=await marker.evaluate(e=>{const s=getComputedStyle(e,'::before');return [e.offsetWidth,e.offsetHeight,s.width,s.height,s.borderWidth];});assert.deepEqual(shell,[80,80,'48px','48px','2px']);if(id==='DEMO-004')assert.equal(await marker.evaluate(e=>getComputedStyle(e).opacity),'0.7');await p.locator(`[data-select="${id}"]`).click();assert.equal(await marker.getAttribute('aria-pressed'),'true');assert.equal(await marker.evaluate(e=>getComputedStyle(e,'::before').outlineWidth),'3px');assert.equal(await marker.evaluate(e=>getComputedStyle(e,'::before').outlineOffset),'2px');assert.match(await p.locator(`[data-geo-row="${id}"]`).getAttribute('class'),/is-selected/);if(id==='DEMO-004'){assert.equal(await marker.evaluate(e=>getComputedStyle(e).opacity),'1');assert.equal(await marker.locator('.marker-state').innerText(),'✓');}await p.screenshot({path:path(`${theme}-${unit}-${mode}-${id}`)});await p.locator('.leaflet-popup-close-button').click();if(mode==='map')await marker.screenshot({path:path(`${theme}-${id}-close`)});
    }
  }
  // Test-created gallery only; no route, production UI, or server allowlist addition.
  await p.evaluate(async()=>{const {incidentIcon,markerCategories}=await import('./marker-language.mjs');const host=document.createElement('section');host.id='optical-certification';host.className='geo-map-panel';host.style.cssText='position:fixed;inset:20px auto auto 20px;z-index:99999;width:720px;padding:24px;background:var(--map-land);color:var(--text-primary);display:grid;grid-template-columns:repeat(4,1fr);gap:16px;font:14px Arial';for(const [category,title]of [['flooding','Flooding'],['rail_blockage_delay','Rail blockage'],['signal_outage','Signal outage'],['debris','Debris']]){const cell=document.createElement('div');cell.style.textAlign='center';const label=document.createElement('p');label.textContent=title;const spec=incidentIcon({divIcon:o=>o},{mapCategory:category,severity:'Moderate',status:'Active'}),marker=document.createElement('div');marker.className=spec.className;marker.style.cssText='position:relative;width:80px;height:80px;margin:auto';marker.append(spec.html);cell.append(label,marker);host.append(cell);}document.body.append(host);await Promise.all([...host.querySelectorAll('img')].map(i=>i.decode()));});
  for(const selected of [false,true]){await p.locator('#optical-certification .dispatch-marker').evaluateAll((es,v)=>es.forEach(e=>e.classList.toggle('is-selected',v)),selected);await p.locator('#optical-certification').screenshot({path:path(`${theme}-four-categories-${selected?'selected':'unselected'}`)});}
  assert.ok(requests.every(([u,m])=>u.startsWith(base+'/')&&m==='GET'));
},{theme}));
for(const theme of ['dark','light'])for(const [width,height]of [[1440,900],[1920,1080],[1280,720],[1024,768]])test(`${theme} ${width}: exact approved Board, all non-icon pixels and geometry preserved`,()=>visit(async p=>{
  const snapshots={};for(const origin of [approved,base]){await p.goto(origin+'/?demo=1&view=board');await p.locator('tbody tr').first().waitFor();await p.mouse.move(0,0);const board=await stable(p);if(origin===approved)snapshots.board=board;else assert.ok(board.equals(snapshots.board));
    for(const unit of ['police','works'])for(const mode of ['split','map']){await p.getByLabel('ACTING UNIT').selectOption(unit);await view(p).selectOption(mode);await ready(p);await p.locator(`[data-select="${unit==='police'?'DEMO-001':'DEMO-004'}"]`).click();await p.mouse.move(0,0);const g=await geometry(p),png=await stable(p,{mask:[p.locator('[data-marker]')]});const key=unit+mode;if(origin===approved)snapshots[key]={g,png};else{assert.deepEqual(g,snapshots[key].g);if(!sameMapPixels(png,snapshots[key].png)){await writeFile(path('diff-before-'+theme+'-'+width+'-'+key),snapshots[key].png);await writeFile(path('diff-after-'+theme+'-'+width+'-'+key),png);}assert.ok(sameMapPixels(png,snapshots[key].png),'All pixels outside marker rectangles match, including selected row, popup and legend');}}
  }
},{theme,width,height}));

// Only the additive preview entry is hidden; all historical pixels remain checked.
async function protectedShot(page,options={}){const entry=page.locator('.notice-entry'),previous=await entry.evaluateAll(es=>es.map(e=>e.style.visibility));await entry.evaluateAll(es=>es.forEach(e=>e.style.visibility='hidden'));try{return await page.screenshot(options);}finally{await entry.evaluateAll((es,values)=>es.forEach((e,i)=>e.style.visibility=values[i]||''),previous);}}
