import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createRegistry,DATASET_HASH} from '../dispatch/road-selection.mjs';import {newNotice,loadWorkspace,saveNotice,preserveWorking,reviewChanges,overlapNotices,storageKey,validateNotice} from '../dispatch/notice-preview.mjs';
const registry=createRegistry(JSON.parse(readFileSync(new URL('../dispatch/demo/dayton-roads.geojson',import.meta.url))),DATASET_HASH),memory=()=>{const m=new Map();return {getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)};},draft=(unit='police',id='DEMO-NOTICE-test')=>({...newNotice(unit,id),restrictionChoice:'continuous',subject:'Synthetic road work',body:'Demonstration notice.',selected:[registry.features[0].id]});
test('save/reopen/refresh preserves one notice identity, seven restriction dates and five work dates',()=>{const s=memory(),n=draft();let saved=saveNotice(s,'police',registry,n,0).notice;assert.equal(saved.workOccurrences.length,5);assert.equal(saved.restrictionOccurrences.length,7);saved.work.exceptions['2026-10-12']={kind:'skip'};saved.work.exceptions['2026-10-13']={kind:'modify',startTime:'08:00',endTime:'12:00'};saved=saveNotice(s,'police',registry,saved,1).notice;const w=loadWorkspace(s,'police',registry);assert.equal(w.notices.length,1);assert.equal(w.notices[0].id,n.id);assert.equal(w.notices[0].revision,2);assert.equal(w.notices[0].history[0].snapshot.workOccurrences.length,5);assert.equal(w.notices[0].workOccurrences.length,4);assert.deepEqual(w.notices[0].history[1].changes.work,['2026-10-12','2026-10-13']);});
test('restriction remains scheduled beyond crew end independently',()=>{const s=memory(),n=saveNotice(s,'police',registry,draft(),0).notice;assert.ok(n.restrictionOccurrences[0].end>n.workOccurrences[0].end);assert.equal(n.restrictionOccurrences.length,7);});
test('working edits survive storage recovery, separately scoped by unit',()=>{const s=memory(),w=loadWorkspace(s,'police',registry),n=draft();n.subject='Unsaved edits';preserveWorking(s,w,n);assert.equal(loadWorkspace(s,'police',registry).working.subject,'Unsaved edits');assert.equal(loadWorkspace(s,'works',registry).working,null);assert.equal(loadWorkspace(s,'works',registry).notices.length,0);});
test('stale edits and closed revisions cannot overwrite; originals and unsaved inputs remain',()=>{const s=memory(),n=draft(),first=saveNotice(s,'police',registry,n,0).notice;const unsaved={...first,subject:'My unsaved edit'};saveNotice(s,'police',registry,first,1);assert.throws(()=>saveNotice(s,'police',registry,unsaved,1),/Stale/);assert.equal(unsaved.subject,'My unsaved edit');const current=loadWorkspace(s,'police',registry).notices[0];const closed=saveNotice(s,'police',registry,current,2,true).notice;assert.equal(closed.status,'CLOSED');assert.throws(()=>saveNotice(s,'police',registry,closed,3));assert.equal(loadWorkspace(s,'police',registry).notices.length,1);});
test('overlaps remain two distinct parent identities; date changes show affected dates',()=>{const s=memory(),a=saveNotice(s,'police',registry,draft(),0).notice,b=saveNotice(s,'police',registry,draft('police','DEMO-NOTICE-second'),0).notice;assert.deepEqual(overlapNotices(b,[a]),[a.id]);assert.equal(loadWorkspace(s,'police',registry).notices.length,2);assert.equal(reviewChanges(null,b).restriction.length,7);});
test('malformed storage, dataset change, cross-unit injection and occurrence/history tampering fail closed',()=>{for(const mutate of [w=>{w.version=0;},w=>{w.dataset='old';},w=>{w.notices[0].unit='works';},w=>{w.notices[0].workOccurrences[0].end='2099-01-01';},w=>{w.notices[0].history[0].snapshot.selected=['unknown'];}]){const s=memory();saveNotice(s,'police',registry,draft(),0);const w=JSON.parse(s.getItem(storageKey('police')));mutate(w);s.setItem(storageKey('police'),JSON.stringify(w));assert.throws(()=>loadWorkspace(s,'police',registry));}const s=memory();s.setItem(storageKey('police'),'{broken');assert.throws(()=>loadWorkspace(s,'police',registry));});
test('validity bounds, bounded text and real-unit IDs reject',()=>{const s=memory();assert.throws(()=>saveNotice(s,'police',registry,{...draft(),expiry:'2026-10-10T00:00'},0));assert.throws(()=>saveNotice(s,'police',registry,{...draft(),body:'x'.repeat(1001)},0));assert.throws(()=>loadWorkspace(s,'fire',registry));});

test('cross-unit save refuses before any storage write',()=>{const s=memory();assert.throws(()=>saveNotice(s,'police',registry,draft('works'),0),/out-of-scope/);assert.equal(s.getItem(storageKey('police')),null);assert.equal(s.getItem(storageKey('works')),null);});
test('malformed revision metadata and storage refusal cannot overwrite saved notices',()=>{const s=memory();saveNotice(s,'police',registry,draft(),0);const before=s.getItem(storageKey('police')),n=loadWorkspace(s,'police',registry).notices[0];assert.throws(()=>saveNotice({...s,setItem(){throw new Error('Storage unavailable');}},'police',registry,{...n,subject:'Unsaved'},1),/unavailable/);assert.equal(s.getItem(storageKey('police')),before);const w=JSON.parse(before);w.notices[0].history[0].changes=null;s.setItem(storageKey('police'),JSON.stringify(w));assert.throws(()=>loadWorkspace(s,'police',registry));});

test('new draft requires explicit restriction choice; no continuous default',()=>{const n={...draft(),restrictionChoice:''};assert.equal(newNotice('police').restrictionChoice,'');assert.notEqual(newNotice('police').restriction.mode,'continuous');assert.throws(()=>validateNotice(n,registry),/Choose when/);assert.throws(()=>validateNotice({...n,restrictionChoice:'invalid'},registry),/Malformed restriction/);});
test('matching work uses exact occurrences including skips and modifications; custom edits remain independent',()=>{const s=memory(),n=draft();n.restrictionChoice='work';n.work.exceptions={'2026-10-12':{kind:'skip'},'2026-10-13':{kind:'modify',startTime:'08:00',endTime:'12:00'}};n.restriction.exceptions={'2026-10-14':{kind:'skip'}};let saved=saveNotice(s,'police',registry,n,0).notice;assert.deepEqual(saved.restrictionOccurrences,saved.workOccurrences);assert.equal(saved.restriction.exceptions['2026-10-14'].kind,'skip');saved.restrictionChoice='custom';saved.restriction.startTime='17:00';saved.restriction.endTime='19:00';saved=saveNotice(s,'police',registry,saved,1).notice;assert.notDeepEqual(saved.restrictionOccurrences,saved.workOccurrences);assert.deepEqual(saved.history[0].snapshot.restrictionOccurrences,saved.history[0].snapshot.workOccurrences);assert.equal(loadWorkspace(s,'police',registry).notices.length,1);});
test('legacy v1 snapshots recover unchanged and can be revised with an explicit choice',()=>{const s=memory(),n=draft();delete n.restrictionChoice;n.restriction.mode='continuous';saveNotice(s,'police',registry,n,0);const before=s.getItem(storageKey('police')),old=loadWorkspace(s,'police',registry).notices[0];assert.equal(s.getItem(storageKey('police')),before);const snapshot=JSON.stringify(old.history[0].snapshot);old.restrictionChoice='work';saveNotice(s,'police',registry,old,1);const current=loadWorkspace(s,'police',registry).notices[0];assert.equal(JSON.stringify(current.history[0].snapshot),snapshot);assert.deepEqual(current.workOccurrences,current.restrictionOccurrences);});