import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {chromium,expect} from '@playwright/test';
import {ARCGIS_CONTRACTS as contracts,FUTURE_NETWORK_POLICY,liveProvider,tileContract,fixturePlan} from '../dispatch/arcgis-offline.mjs';
import {previewServer} from '../tools/dispatch-ui/serve.mjs';
const standard='arcgis-standard-fixture',satellite='arcgis-satellite-fixture';
test('documented immutable streets descriptor with independent static privilege',()=>{assert.ok(Object.isFrozen(contracts.standard));assert.equal(contracts.standard.privilege,'premium:user:staticbasemaptiles');assert.match(contracts.standard.url,/v1\/arcgis\/streets\/static\/tile\/\{z\}\/\{y\}\/\{x\}$/);assert.equal(contracts.standard.tileSize,512);assert.equal(contracts.standard.zoomOffset,-1);});
test('documented imagery discovery and map tile contract uses basemap privilege',()=>{assert.equal(contracts.imagery.privilege,'premium:user:basemaps');assert.equal(contracts.imagery.styleUrl,'https://basemapstyles-api.arcgis.com/arcgis/rest/services/styles/v2/webmaps/arcgis/imagery/standard');assert.match(contracts.imagery.url,/ibasemaps-api\.arcgis\.com.*World_Imagery.*\{z\}\/\{y\}\/\{x\}$/);assert.equal(contracts.imagery.tileSize,256);assert.equal(contracts.imagery.zoomOffset,0);});
test('labels are an independent transparent static overlay, never imagery',()=>{assert.match(contracts.labels.url,/imagery\/labels/);assert.notEqual(contracts.labels.privilege,contracts.imagery.privilege);assert.notEqual(contracts.labels.url,contracts.imagery.url);assert.equal(fixturePlan(standard).labels,'not-rendered');assert.equal(fixturePlan(satellite).labels,'available');});
for(const id of ['standard','imagery','labels'])test(id+' level row column and zoom offsets',()=>{for(const z of [5,9,14,18]){const d=tileContract(id,{z,x:1,y:2});assert.equal(d.level,z+contracts[id].zoomOffset);assert.ok(d.url.endsWith('/'+d.level+'/2/1'));assert.equal(new URL(d.url).search,'');assert.equal(d.row,2);assert.equal(d.column,1);}assert.throws(()=>tileContract(id,{z:4,x:0,y:0}));assert.throws(()=>tileContract(id,{z:19,x:0,y:0}));assert.throws(()=>tileContract(id,{z:5,x:2**(5+contracts[id].zoomOffset),y:0}));assert.throws(()=>tileContract(id,{z:5,x:-1,y:0}));});
for(const code of [401,403,404,498,499,503])test('fixture base HTTP '+code+' fails closed without standalone labels',()=>{const p=fixturePlan(satellite,{imagery:code});assert.equal(p.health,'unavailable');assert.equal(p.labels,'not-rendered');assert.equal(p.activation,false);assert.equal(p.operationalGeometry,false);assert.ok(!/token=|password/.test(JSON.stringify(p)));});
for(const code of [401,403,404,498,499,503])test('fixture labels HTTP '+code+' leaves truthful degraded imagery',()=>{const p=fixturePlan(satellite,{labels:code});assert.equal(p.health,'degraded');assert.notEqual(p.labels,'available');assert.equal(p.baseStatus,200);});
test('static denial cannot be mistaken for successful Standard',()=>assert.equal(fixturePlan(standard,{standard:403}).health,'unavailable'));
test('configuration accepts only synthetic status fixtures, no credential or activation fields',()=>{for(const c of [{token:null},{apiKey:null},{activation:true},{consumerConfig:null},{imagery:201},{imagery:'200'},null])assert.throws(()=>fixturePlan(satellite,c));assert.throws(()=>fixturePlan('remote'));assert.throws(()=>liveProvider());});
test('future explicit-host policy is frozen and inactive',()=>{assert.equal(FUTURE_NETWORK_POLICY.activation,false);assert.equal(FUTURE_NETWORK_POLICY.requiresSeparateApproval,true);assert.equal(FUTURE_NETWORK_POLICY.referrerPolicy,'strict-origin-when-cross-origin');for(const origin of [...FUTURE_NETWORK_POLICY.imageOrigins,...FUTURE_NETWORK_POLICY.metadataOrigins])assert.match(origin,/^https:\/\/[a-z-]+\.arcgis\.com$/);assert.ok(Object.isFrozen(FUTURE_NETWORK_POLICY.imageOrigins));});
test('offline implementation contains no network or credential-loading primitive',()=>{const s=readFileSync(new URL('../dispatch/arcgis-offline.mjs',import.meta.url),'utf8');assert.doesNotMatch(s,/\bfetch\s*\(|\bXMLHttpRequest\b|new Image\s*\(|localStorage|sessionStorage|process\.env|\.src\s*=/);assert.match(s,/LOCAL SYNTHETIC/);});
let server,browser,base;before(async()=>{server=previewServer({demo:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,channel:process.env.DISPATCH_BROWSER_CHANNEL||'msedge'});});after(async()=>{await browser?.close();await new Promise(r=>server.close(r));});
async function visit(fn,viewport={width:1440,height:900}){const context=await browser.newContext({viewport});await context.addInitScript(()=>{let value;window.__maps=[];Object.defineProperty(window,'L',{get:()=>value,set:L=>{value=L;const f=L.map;L.map=(...args)=>{const m=f(...args);window.__maps.push(m);return m;};}});});const p=await context.newPage(),errors=[],external=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(!r.url().startsWith(base+'/'))external.push('outside-loopback-origin');});await p.route('**/*',r=>r.request().url().startsWith(base+'/')?r.continue():r.abort());try{await p.goto(base+'/?demo=1&view=map');await p.locator('[data-marker]').first().waitFor();await fn(p);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);}finally{await context.close();}}
const camera=p=>p.evaluate(()=>{const m=window.__maps[0],c=m.getCenter();return [c.lat,c.lng,m.getZoom()];});
for(const viewport of [{width:1440,height:900},{width:390,height:844}])test('offline Standard/Satellite switching and fullscreen '+viewport.width,()=>visit(async p=>{await p.locator('[data-select="DEMO-001"]').click();await p.locator('.leaflet-popup-close-button').click();await p.getByRole('button',{name:'Expand Map',exact:true}).click();await p.getByRole('button',{name:'Filters',exact:true}).click();const markers=await p.locator('[data-marker]').count();const picker=p.getByRole('combobox',{name:'Basemap source'});for(const id of [standard,satellite,'local-mock','dayton',satellite]){const retained=await camera(p);await picker.selectOption(id);assert.deepEqual(await camera(p),retained);if(id.includes('arcgis')){await expect(p.locator('.map-source-status')).toContainText('LOCAL SYNTHETIC');await expect(p.locator('[data-arcgis-fixture]').first()).toBeVisible();assert.equal(await p.locator('[data-arcgis-fixture="labels"]').count()>0,id===satellite);}for(const z of [5,9,14,18]){await p.evaluate(z=>{window.__maps[0].setView([32.77,-96.8],z,{animate:false});},z);assert.equal((await camera(p))[2],z);}assert.equal(await p.locator('[data-marker]').count(),markers);assert.equal(await p.locator('[data-marker="DEMO-001"]').getAttribute('aria-pressed'),'true');assert.equal(await p.evaluate(()=>window.__maps.length),1);}await p.keyboard.press('Escape');await p.getByRole('button',{name:'Return to Map'}).click();await expect(p.getByRole('button',{name:'Expand Map',exact:true})).toBeFocused();},viewport));
test('independent missing-label fixture never masquerades as complete geography',()=>visit(async p=>{const result=await p.evaluate(async()=>{const {createArcgisFixtureBasemap}=await import('/arcgis-offline.mjs');let state;const adapter=createArcgisFixtureBasemap(window.L,window.__maps[0],{id:'arcgis-satellite-fixture',configuration:{labels:403},onState:s=>state=s});const labels=document.querySelectorAll('[data-arcgis-fixture="labels"]').length;adapter.destroy();return {state,labels};});assert.equal(result.state.health,'degraded');assert.equal(result.state.labels,'access-denied');assert.equal(result.labels,0);assert.match(result.state.coverage,/unverified/);}));
test('missing imagery refuses all fixture layers and preserves map camera',()=>visit(async p=>{const before=await camera(p);const result=await p.evaluate(async()=>{const {createArcgisFixtureBasemap}=await import('/arcgis-offline.mjs');let state;const adapter=createArcgisFixtureBasemap(window.L,window.__maps[0],{id:'arcgis-satellite-fixture',configuration:{imagery:401},onState:s=>state=s});adapter.destroy();return state;});assert.equal(result.health,'unavailable');assert.equal(await p.locator('[data-arcgis-fixture]').count(),0);assert.deepEqual(await camera(p),before);}));
test('current CSP and referrer remain self-only; live credentials never accepted',async()=>{const r=await fetch(base+'/arcgis-offline.mjs');assert.equal(r.status,200);assert.equal(r.headers.get('referrer-policy'),'no-referrer');assert.match(r.headers.get('content-security-policy'),/img-src 'self'; connect-src 'self'/);assert.doesNotMatch(r.headers.get('content-security-policy'),/arcgis|\*/);const plain=previewServer();await new Promise(r=>plain.listen(0,'127.0.0.1',r));try{assert.equal((await fetch('http://127.0.0.1:'+plain.address().port+'/arcgis-offline.mjs')).status,404);}finally{await new Promise(r=>plain.close(r));}});

test('local fixture render failure selects truthful Dayton fallback without camera loss',()=>visit(async p=>{await p.getByRole('button',{name:'Expand Map',exact:true}).click();await p.getByRole('button',{name:'Filters',exact:true}).click();const before=await camera(p);await p.evaluate(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(...args){return this.dataset.arcgisFixture?null:original.apply(this,args);};});await p.getByRole('combobox',{name:'Basemap source'}).selectOption(satellite);await expect(p.locator('.map-source-status')).toContainText('fallback');assert.deepEqual(await camera(p),before);assert.equal(await p.locator('[data-arcgis-fixture]').count(),0);}));
test('fixture geographic edge is unavailable and does not hide missing Dayton coverage',()=>visit(async p=>{await p.getByRole('button',{name:'Expand Map',exact:true}).click();await p.getByRole('button',{name:'Filters',exact:true}).click();await p.getByRole('combobox',{name:'Basemap source'}).selectOption(satellite);await p.evaluate(()=>{window.__maps[0].setView([30,210],7,{animate:false});});await expect(p.locator('.map-source-status')).toContainText('No local cartography coverage');await expect(p.locator('.map-source-status')).toContainText('fallback');assert.equal((await camera(p))[2],7);assert.equal(await p.locator('[data-arcgis-fixture]').count(),0);}));
test('offline fixture survives view teardown and recreation with camera and provider context',()=>visit(async p=>{await p.getByRole('button',{name:'Expand Map',exact:true}).click();await p.getByRole('button',{name:'Filters',exact:true}).click();await p.getByRole('combobox',{name:'Basemap source'}).selectOption(standard);await p.evaluate(()=>{window.__maps[0].setView([29.76,-95.37],9,{animate:false});});const before=await camera(p);await p.keyboard.press('Escape');await p.getByRole('button',{name:'Return to Map'}).click();await p.getByRole('combobox',{name:'View',exact:true}).selectOption('board');await p.getByRole('combobox',{name:'View',exact:true}).selectOption('map');await p.locator('[data-arcgis-fixture="standard"]').first().waitFor();const after=await p.evaluate(()=>{const m=window.__maps.at(-1),c=m.getCenter();return [c.lat,c.lng,m.getZoom()];});assert.deepEqual(after,before);await expect(p.locator('.map-source-status')).toContainText('LOCAL SYNTHETIC');}));
