import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {previewServer} from '../tools/dispatch-ui/serve.mjs';
let browser,server,base;const evidence=process.env.DISPATCH_WORKSPACE_EVIDENCE;
before(async()=>{server=previewServer({demo:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;browser=await chromium.launch({headless:true,channel:process.env.DISPATCH_BROWSER_CHANNEL||'msedge'});if(evidence)await mkdir(evidence,{recursive:true});});
after(async()=>{await browser?.close();await new Promise(r=>server.close(r));});
async function visit(fn,viewport={width:1440,height:900},theme='dark'){
 const context=await browser.newContext({viewport});await context.addInitScript(theme=>{localStorage.setItem('gridlyDispatchTheme',theme);let value;window.__maps=[];Object.defineProperty(window,'L',{configurable:true,get:()=>value,set:L=>{value=L;const factory=L.map;L.map=(...args)=>{const map=factory(...args);window.__maps.push(map);return map;};}});},theme);
 const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{await p.goto(base+'/?demo=1&view=map');await p.locator('[data-marker]').first().waitFor();await fn(p);assert.deepEqual(errors,[]);}finally{await context.close();}
}
const camera=p=>p.evaluate(()=>{const m=window.__maps.at(-1),c=m.getCenter();return [c.lat,c.lng,m.getZoom()];});
const readySize=p=>expect.poll(()=>p.evaluate(()=>{const m=window.__maps.at(-1),e=m.getContainer(),s=m.getSize();return [s.x,s.y,e.clientWidth,e.clientHeight];})).toMatchObject([expect.any(Number),expect.any(Number),expect.any(Number),expect.any(Number)]);
async function settled(p){await expect.poll(()=>p.evaluate(()=>{const m=window.__maps.at(-1),e=m.getContainer(),s=m.getSize();return s.x===e.clientWidth&&s.y===e.clientHeight;})).toBe(true);}
async function shot(p,name){if(evidence)await p.screenshot({path:evidence+'/'+name+'.png'});}
for(const theme of ['dark','light'])for(const [width,height] of [[1440,900],[1920,1080],[1024,768],[390,844],[844,390],[1280,600]])test(theme+' '+width+'x'+height+' expanded geometry, controls, camera and return',()=>visit(async p=>{
 const action=p.getByRole('button',{name:'Expand Map',exact:true});await expect(action).toBeVisible();assert.equal(await action.getAttribute('type'),'button');
 const rect=await action.boundingBox();assert.ok(rect.width>=50&&rect.height>=20);const others=await p.locator('#fit-incidents,.map-credit,[data-marker]').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};}));for(const r of others)assert.ok(rect.x+rect.width<=r.x||r.x+r.width<=rect.x||rect.y+rect.height<=r.y||r.y+r.height<=rect.y,'Expand control overlap');
 await action.scrollIntoViewIfNeeded();const control=await action.boundingBox();const normal=await p.locator('#dispatch-map').boundingBox();const before=await camera(p);if(theme==='dark'&&width===1440)await shot(p,'normal-map');
 await action.click();await settled(p);assert.deepEqual(await camera(p),before);assert.equal(await p.evaluate(()=>window.__maps.length),1);
 const expanded=await p.locator('#dispatch-map').boundingBox();assert.ok(expanded.width>=width-4);assert.ok(expanded.height>=height-2);assert.equal(expanded.x,0);assert.equal(expanded.y,0);assert.ok(expanded.height>normal.height||height<500);
 assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await expect(p.locator('.topbar')).not.toBeVisible();await expect(p.locator('.geo-map-panel > .panel-heading > div:first-child')).not.toBeVisible();await expect(p.locator('.map-credit')).toBeVisible();
 const controls=await p.locator('.expanded-map-actions .button,#fit-incidents,.leaflet-control-zoom,.map-credit').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom};}));for(const b of controls)assert.ok(b.x>=0&&b.y>=0&&b.right<=width&&b.bottom<=height,'clipped floating control');for(let i=0;i<controls.length;i++)for(let j=i+1;j<controls.length;j++){const a=controls[i],b=controls[j];assert.ok(a.right<=b.x||b.right<=a.x||a.bottom<=b.y||b.bottom<=a.y,'overlapping floating control');}
 if(evidence)await writeFile(evidence+'/'+theme+'-'+width+'x'+height+'-dimensions.json',JSON.stringify({viewport:{width,height},normal,expanded,expandControl:control}));await shot(p,theme+'-'+width+'x'+height+'-expanded');
 await p.getByRole('button',{name:'Incidents',exact:true}).click();await expect(p.locator('#map-incident-drawer')).toBeVisible();await shot(p,theme+'-'+width+'-drawer');await p.keyboard.press('Escape');await expect(p.getByRole('button',{name:'Incidents',exact:true})).toBeFocused();
 await p.getByRole('button',{name:'Return to Map'}).click();await settled(p);assert.deepEqual(await camera(p),before);await expect(action).toBeFocused();assert.deepEqual(await p.locator('#dispatch-map').boundingBox(),normal);assert.equal(await p.getByRole('combobox',{name:'View',exact:true}).inputValue(),'map');
},{width,height},theme));
test('selection, filters, detail dialog, layered Escape and repeated map reuse',()=>visit(async p=>{
 await p.locator('[data-select="DEMO-001"]').click();await p.locator('.leaflet-popup-close-button').click();const original=await camera(p);await p.getByRole('button',{name:'Expand Map'}).click();await settled(p);assert.deepEqual(await camera(p),original);assert.equal(await p.locator('[data-marker="DEMO-001"]').getAttribute('aria-pressed'),'true');
 await p.getByRole('button',{name:'Filters',exact:true}).click();await p.getByLabel('Search reports').fill('Street');await p.keyboard.press('Escape');await expect(p.getByRole('button',{name:'Filters',exact:true})).toBeFocused();assert.deepEqual(await camera(p),original);
 await p.getByRole('button',{name:'Incidents',exact:true}).click();await p.locator('[data-select="DEMO-001"]').click();await p.locator('.dispatch-popup').getByRole('button',{name:'View details'}).click();await p.keyboard.press('Escape');await expect(p.getByRole('dialog')).not.toBeVisible();assert.ok(await p.locator('.map-expanded').count());await p.keyboard.press('Escape');assert.equal(await p.locator('.leaflet-popup').count(),0);await p.keyboard.press('Escape');await expect(p.getByRole('button',{name:'Incidents',exact:true})).toBeFocused();await p.keyboard.press('Escape');await settled(p);await expect(p.getByRole('button',{name:'Expand Map'})).toBeFocused();assert.equal(await p.getByLabel('Search reports').inputValue(),'Street');
 for(let i=0;i<4;i++){await p.getByRole('button',{name:'Expand Map'}).click();await settled(p);await p.setViewportSize({width:1200+i*10,height:750+i*10});await settled(p);await p.getByRole('button',{name:'Return to Map'}).click();await settled(p);}assert.equal(await p.evaluate(()=>window.__maps.length),1);
 await p.getByRole('combobox',{name:'View',exact:true}).selectOption('board');assert.equal(await p.locator('#dispatch-map').count(),0);assert.equal(await p.evaluate(()=>document.body.classList.contains('dispatch-map-expanded')),false);await shot(p,'normal-board');
}));
test('expanded error and retry retain exit and list',()=>visit(async p=>{await p.route('**/dayton-context.geojson',r=>r.fulfill({status:503,body:''}));await p.reload();await p.getByText('Map unavailable',{exact:true}).waitFor();await p.getByRole('button',{name:'Expand Map'}).click();await p.getByRole('button',{name:'Incidents',exact:true}).click();assert.equal(await p.locator('[data-select]').count(),2);await p.keyboard.press('Escape');await p.unroute('**/dayton-context.geojson');await p.getByRole('button',{name:'Retry map',exact:true}).click();await p.locator('[data-marker]').first().waitFor();await settled(p);await p.getByRole('button',{name:'Return to Map'}).click();}));

test('expanded System theme updates without replacing the map or camera',()=>visit(async p=>{await p.getByRole('button',{name:'Expand Map'}).focus();await p.keyboard.press('Enter');await settled(p);const c=await camera(p);await p.emulateMedia({colorScheme:'light'});await expect(p.locator('html')).toHaveAttribute('data-theme','light');await p.emulateMedia({colorScheme:'dark'});await expect(p.locator('html')).toHaveAttribute('data-theme','dark');assert.deepEqual(await camera(p),c);assert.equal(await p.evaluate(()=>window.__maps.length),1);await p.keyboard.press('Escape');},{width:1440,height:900},'system'));
test('transparent Expand exclusion cannot conceal changes to the existing Fit control',()=>visit(async p=>{const {sameMapPixels}=await import('../tools/dispatch-ui/approved-board.mjs');await p.locator('#expand-map').evaluate(e=>e.style.visibility='hidden');const before=await p.screenshot();await p.locator('#fit-incidents').evaluate(e=>e.style.color='rgb(255,0,0)');const after=await p.screenshot();assert.equal(sameMapPixels(before,after),false);assert.equal(await p.locator('#fit-incidents').isVisible(),true);}));

test('expanded pan and zoom retain the same camera on return',()=>visit(async p=>{await p.getByRole('button',{name:'Expand Map'}).click();await settled(p);await p.evaluate(()=>{const m=window.__maps.at(-1);m.setZoom(16,{animate:false});m.panBy([20,10],{animate:false});});const c=await camera(p);await p.getByRole('button',{name:'Return to Map'}).click();await settled(p);assert.deepEqual(await camera(p),c);}));

test('floating panels never resize the map and attribution stays inside the viewport',()=>visit(async p=>{
 await p.getByRole('button',{name:'Expand Map'}).click();await settled(p);const r=await p.locator('#dispatch-map').boundingBox();
 for(const name of ['Incidents','Filters']){await p.getByRole('button',{name,exact:true}).click();assert.deepEqual(await p.locator('#dispatch-map').boundingBox(),r);await p.keyboard.press('Escape');}
 const boxes=await p.locator('.expanded-map-actions .button,#fit-incidents,.leaflet-control-zoom,.map-credit').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom};}));for(const b of boxes){assert.ok(b.x>=0&&b.y>=0&&b.right<=390&&b.bottom<=844);}
 for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert.ok(a.right<=b.x||b.right<=a.x||a.bottom<=b.y||b.bottom<=a.y,'floating controls overlap');}
},{width:390,height:844}));
test('unsupported browser fullscreen retains the complete viewport workspace',()=>visit(async p=>{
 await p.evaluate(()=>Object.defineProperty(document,'fullscreenEnabled',{configurable:true,value:false}));await p.getByRole('combobox',{name:'View',exact:true}).selectOption('board');await p.getByRole('combobox',{name:'View',exact:true}).selectOption('map');await p.locator('[data-marker]').first().waitFor();await p.getByRole('button',{name:'Expand Map'}).click();await settled(p);await expect(p.getByRole('button',{name:'Full screen',exact:true})).toBeDisabled();assert.equal((await p.locator('#dispatch-map').boundingBox()).height,900);await p.keyboard.press('Escape');await expect(p.getByRole('button',{name:'Expand Map'})).toBeFocused();
}));
test('fullscreen denial preserves map, camera and accessible fallback',()=>visit(async p=>{
 await p.getByRole('button',{name:'Expand Map'}).click();await settled(p);const c=await camera(p);await p.evaluate(()=>{document.querySelector('.shell').requestFullscreen=()=>Promise.reject(new DOMException('Denied','NotAllowedError'));});await p.getByRole('button',{name:'Full screen',exact:true}).click();await expect(p.locator('#map-fullscreen-status')).toContainText('Viewport map remains available');assert.deepEqual(await camera(p),c);assert.equal(await p.evaluate(()=>window.__maps.length),1);await p.keyboard.press('Escape');await expect(p.getByRole('button',{name:'Expand Map'})).toBeFocused();
}));
test('actual browser fullscreen and native exit synchronize return and focus',()=>visit(async p=>{
 await p.getByRole('button',{name:'Expand Map'}).click();await settled(p);const c=await camera(p);await p.getByRole('button',{name:'Full screen',exact:true}).click();await expect.poll(()=>p.evaluate(()=>document.fullscreenElement?.classList.contains('shell')||false)).toBe(true);await settled(p);assert.equal(await p.evaluate(()=>window.__maps.length),1);await shot(p,'native-fullscreen');await p.getByRole('button',{name:'Incidents',exact:true}).click();await p.evaluate(()=>document.exitFullscreen());await expect(p.locator('.map-expanded')).toHaveCount(0);await settled(p);await expect(p.getByRole('button',{name:'Expand Map'})).toBeFocused();assert.deepEqual(await camera(p),c);await p.getByRole('button',{name:'Expand Map'}).click();await p.getByRole('button',{name:'Full screen',exact:true}).click();await expect.poll(()=>p.evaluate(()=>!!document.fullscreenElement)).toBe(true);await p.getByRole('button',{name:'Return to Map'}).click();await expect.poll(()=>p.evaluate(()=>!!document.fullscreenElement)).toBe(false);await settled(p);await expect(p.getByRole('button',{name:'Expand Map'})).toBeFocused();assert.equal(await p.evaluate(()=>window.__maps.length),1);
}));

test('actual native fullscreen Escape returns without a stuck panel',()=>visit(async p=>{
 await p.getByRole('button',{name:'Expand Map'}).click();await settled(p);const c=await camera(p);await p.getByRole('button',{name:'Full screen',exact:true}).click();await expect.poll(()=>p.evaluate(()=>!!document.fullscreenElement)).toBe(true);await p.getByRole('button',{name:'Filters',exact:true}).click();await p.keyboard.press('Escape');await expect.poll(()=>p.evaluate(()=>!!document.fullscreenElement)).toBe(false);await expect(p.locator('.map-expanded')).toHaveCount(0);await settled(p);await expect(p.getByRole('button',{name:'Expand Map'})).toBeFocused();assert.deepEqual(await camera(p),c);assert.equal(await p.evaluate(()=>window.__maps.length),1);
}));
