import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {CONTRACT,LIMITS,digest,loadRegistry} from '../dispatch/roadway-registry.mjs';
import {INPUTS,validateLocal} from '../tools/dispatch-roadway-local/validate-registry.mjs';
const bytes=x=>new TextEncoder().encode(JSON.stringify(x));
const line=(id='way/1',name='Main Street')=>({type:'Feature',properties:{osmId:id,...(name===null?{}:{name})},geometry:{type:'LineString',coordinates:[[-94.9,30.02],[-94.899123456789,30.03]]}});
async function fixture(features=[line()],change={}){
 const data={type:'FeatureCollection',features},provenance={source:'synthetic-test-only',sha256:'a'.repeat(64),sourceTimestamp:'2026-05-09T22:50:58Z',license:'synthetic-test',copyright:'Synthetic tests; no agency or roadway authority.'};
 const input=bytes(data),p=bytes(provenance);
 const manifest={contract:CONTRACT,namespace:'osm',dataset:'synthetic-test-input',sourceDataset:provenance.source,sourceHash:provenance.sha256,snapshot:provenance.sourceTimestamp,version:'test-v1',packageId:'test.liberty',featureIdKey:'osmId',inputFeatureCount:features.length,inputHash:await digest(input),provenanceHash:await digest(p),countyFips:['48291'],crs:'OGC:CRS84',license:provenance.license,attribution:provenance.copyright,sourceTransform:'Synthetic test; exact coordinates.',...change};
 return {data,input,p,manifest,load:(m=manifest,i=input,pb=p)=>loadRegistry(i,pb,m,['48291','48339'])};
}
async function rejectsFeature(feature,pattern){const f=await fixture([feature]);await assert.rejects(f.load(),pattern);}
test('source, version, geometry and future operational identity remain separate',async()=>{const f=await fixture(),r=await f.load(),a=r.features[0];assert.equal(a.identity.sourceFeatureId,'way/1');assert.equal(a.version.sourceHash,'a'.repeat(64));assert.notEqual(a.version.inputHash,a.version.geometryHash);assert.equal(a.operationalSegmentId,null);assert.equal(a.selection.contract,CONTRACT);});
test('duplicate names and route references remain aliases',async()=>{const a=line(),b=line('way/2');a.properties.ref=b.properties.ref='US 90';const f=await fixture([a,b]),r=await f.load();assert.equal(r.search('Main Street').length,2);assert.equal(r.search('US 90').length,2);assert.notEqual(r.features[0].identityKey,r.features[1].identityKey);});
test('unnamed roads retain source identity and searchable ID',async()=>{const f=await fixture([line('way/1',null)]),r=await f.load();assert.equal(r.features[0].label,'Unnamed source road');assert.equal(r.search('way/1').length,1);});
for(const id of ['','way/no',' way/1'])test('reject missing/malformed ID '+String(id),()=>rejectsFeature(line(id===undefined?'way/1':id),/identity/).then(()=>{}));
// Explicit absent-property vector.
test('reject absent source property',async()=>{const x=line();delete x.properties.osmId;await rejectsFeature(x,/identity/);});
test('reject duplicate source identities',async()=>{const f=await fixture([line(),line()]);await assert.rejects(f.load(),/Duplicate source/);});
for(const p of [[181,30],[-94,91],[-94],[-94,30,5],['-94',30],[null,30]])test('reject invalid coordinate '+JSON.stringify(p),async()=>{const a=line();a.geometry.coordinates[1]=p;await rejectsFeature(a,/coordinate/);});
test('reject nonfinite coordinates',async()=>{const f=await fixture();f.data.features[0].geometry.coordinates[1][0]=Infinity;const input=bytes(f.data);await assert.rejects(f.load({...f.manifest,inputHash:await digest(input)},input),/coordinate/);});
test('LineString coordinates are exactly preserved and immutable',async()=>{const f=await fixture(),r=await f.load();assert.deepEqual(r.features[0].geometry,f.data.features[0].geometry);assert.throws(()=>{r.features[0].geometry.coordinates[0][0]=0;},TypeError);f.data.features[0].geometry.coordinates[0][0]=0;assert.equal(r.features[0].geometry.coordinates[0][0],-94.9);});
test('MultiLineString preserves separate components without connectors',async()=>{const a=line();a.geometry={type:'MultiLineString',coordinates:[a.geometry.coordinates,[[-95,31],[-95.01,31.01]]]};const f=await fixture([a]),r=await f.load();assert.deepEqual(r.features[0].geometry,a.geometry);assert.equal(r.features[0].geometry.coordinates.length,2);});
for(const g of [{type:'Point',coordinates:[-94,30]},{type:'LineString',coordinates:[]},{type:'MultiLineString',coordinates:[]},{type:'LineString',coordinates:[[-94,30],[-94,30]]},{type:'GeometryCollection',geometries:[]}])test('reject unsupported/empty/degenerate '+g.type+JSON.stringify(g.coordinates),async()=>{const a=line();a.geometry=g;await rejectsFeature(a,/geometry|line/);});
test('reject foreign geometry structures',async()=>{const a=line();a.geometry.crs='EPSG:3857';await rejectsFeature(a,/geometry/);});
test('reject unexpected CRS declaration',async()=>{const f=await fixture();await assert.rejects(f.load({...f.manifest,crs:'EPSG:3857'}),/reference system/);f.data.crs={type:'name',properties:{name:'EPSG:4326'}};const b=bytes(f.data);await assert.rejects(f.load({...f.manifest,inputHash:await digest(b)},b),/CRS/);});
test('digest binds geometry representation',async()=>{const f=await fixture(),r=await f.load();assert.equal(r.features[0].version.geometryHash,await digest(bytes(f.data.features[0].geometry)));});
test('input byte changes fail the pin',async()=>{const f=await fixture(),b=new Uint8Array([...f.input,32]);await assert.rejects(f.load(f.manifest,b),/hash mismatch/);});
test('changed geometry under a new reviewed pin invalidates old selection',async()=>{const f=await fixture(),r=await f.load();f.data.features[0].geometry.coordinates[1][0]-=.01;const b=bytes(f.data),next=await f.load({...f.manifest,inputHash:await digest(b)},b);assert.throws(()=>next.selected([r.features[0].selection]),/stale/);});
test('source version changes invalidate selection',async()=>{const f=await fixture(),r=await f.load(),next=await f.load({...f.manifest,version:'test-v2'});assert.throws(()=>next.selected([r.features[0].selection]),/stale/);});
test('selection refuses forged digest, unknown identity, extra fields and duplicates',async()=>{const f=await fixture(),r=await f.load(),s=r.features[0].selection;for(const v of [[{...s,geometryHash:'b'.repeat(64)}],[{...s,identity:'unknown'}],[{...s,role:'ADMIN'}],[s,s],[null]])assert.throws(()=>r.selected(v),/stale|Malformed/);assert.deepEqual(r.selected([s]),[r.features[0]]);assert.deepEqual(r.selected([]),[]);});
test('package isolation even for identical source geometry',async()=>{const f=await fixture(),r=await f.load(),other=await f.load({...f.manifest,packageId:'test.other'});assert.throws(()=>other.selected([r.features[0].selection]),/stale/);});
test('county isolation and unknown county rejection',async()=>{const f=await fixture(),r=await f.load(),other=await f.load({...f.manifest,countyFips:['48339']});assert.throws(()=>other.selected([r.features[0].selection]),/stale/);for(const c of [['99999'],['48291','48291'],[]])await assert.rejects(f.load({...f.manifest,countyFips:c}),/county/);});
test('multi-county identity preserves all memberships with no primary county',async()=>{const f=await fixture(undefined,{countyFips:['48339','48291']}),r=await f.load();assert.deepEqual(r.countyFips,['48291','48339']);assert.deepEqual(r.features[0].countyFips,r.countyFips);assert.equal(r.features[0].primaryCounty,undefined);assert.equal(r.features[0].certification.boundaryRelationship,'UNVERIFIED');});
test('missing and modified provenance fail closed',async()=>{const f=await fixture();await assert.rejects(f.load(f.manifest,f.input,null),/input/);await assert.rejects(f.load(f.manifest,f.input,bytes({})),/hash mismatch/);const p=bytes({...JSON.parse(new TextDecoder().decode(f.p)),license:'unknown'});await assert.rejects(f.load({...f.manifest,provenanceHash:await digest(p)},f.input,p),/provenance/);});
test('no topology, boundary or authority promotion',async()=>{const f=await fixture(),r=await f.load();assert.deepEqual(r.features[0].certification,{sourceGeometry:'VALID',sourceIdentity:'GOVERNED_LOCAL',topology:'UNVERIFIED',boundaryRelationship:'UNVERIFIED',roadwayAuthority:'UNVERIFIED',publication:'DISABLED'});});
test('bounded bytes, feature declaration, selection and search limits',async()=>{const f=await fixture();await assert.rejects(f.load(f.manifest,new Uint8Array(LIMITS.bytes+1)),/oversized/);await assert.rejects(f.load({...f.manifest,inputFeatureCount:45001}),/count/);const r=await f.load();assert.throws(()=>r.selected(Array(51).fill(r.features[0].selection)),/50/);assert.throws(()=>r.search('x'.repeat(241)),/search/);});
test('search result ceiling preserves existing preview semantics',async()=>{const f=await fixture(Array.from({length:41},(_,i)=>line('way/'+(i+1)))),r=await f.load();assert.equal(r.search('Main Street').length,40);});
test('polygon exclusion must be explicitly reviewed',async()=>{const a=line();a.geometry={type:'Polygon',coordinates:[]};const f=await fixture([line('way/2'),a]);await assert.rejects(f.load(),/geometry/);const r=await f.load({...f.manifest,excludedGeometryTypes:['Polygon']});assert.equal(r.statistics.excludedFeatures,1);assert.equal(r.features.length,1);});
test('approved actual sources validate without coordinate changes',async()=>{for(const m of INPUTS){const root=new URL('../',import.meta.url),b=await readFile(new URL(m.dataset,root)),p=await readFile(new URL('dispatch/demo/dayton-roads-provenance.json',root)),r=await loadRegistry(b,p,m,['48291']);const original=JSON.parse(b).features.filter(f=>f.geometry.type==='LineString');assert.deepEqual(r.features.map(f=>f.geometry),original.map(f=>f.geometry));assert.equal(r.features.length,m.inputFeatureCount-(m.excludedGeometryTypes?2:0));}});
test('read-only local validator uses bounded packages and reports actual timing',async()=>{const results=await validateLocal();assert.equal(results.length,2);assert.deepEqual(results.map(r=>r.roadFeatures),[331,8405]);for(const r of results){assert.ok(r.inputBytes<=LIMITS.bytes);assert.ok(r.elapsedMs>=0);assert.equal(r.publication,'DISABLED');}});
test('caller mutation cannot change async input or approved metadata',async()=>{const f=await fixture(),pending=f.load();f.input.fill(0);f.p.fill(0);f.manifest.packageId='forged';const r=await pending;assert.equal(r.packageId,'test.liberty');assert.equal(r.features[0].geometry.coordinates[0][0],-94.9);});
test('approved local descriptors cannot be mutated',()=>{assert.throws(()=>{INPUTS[0].countyFips[0]='48339';},TypeError);assert.throws(()=>{INPUTS[1].excludedGeometryTypes.push('LineString');},TypeError);});