import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {chromium} from '@playwright/test';
import {previewServer} from '../tools/dispatch-ui/serve.mjs';
import {approvedBoardServer} from '../tools/dispatch-ui/approved-board.mjs';
import {roadLabelPolicy} from '../dispatch/map-label-policy.mjs';
let browser,server,baseline,plain,base,approved,login;
const evidence=new URL('../reports/responder/dispatch-map-polish/',import.meta.url);
const listen=s=>new Promise(r=>s.listen(0,'127.0.0.1',()=>r(`http://127.0.0.1:${s.address().port}`)));
before(async()=>{server=previewServer({demo:true});baseline=approvedBoardServer('86633d7e0e76d2775d4e1567da19fa18528198ce');plain=previewServer();base=await listen(server);approved=await listen(baseline);login=await listen(plain);browser=await chromium.launch({headless:true,...(process.env.DISPATCH_BROWSER_CHANNEL?{channel:process.env.DISPATCH_BROWSER_CHANNEL}:{})});await mkdir(evidence,{recursive:true});});
after(async()=>{await browser?.close();server?.close();baseline?.close();plain?.close();});
async function visit(fn,{width=1440,height=900,theme='dark'}={}){const c=await browser.newContext({viewport:{width,height}});await c.addInitScript(t=>localStorage.setItem('gridlyDispatchTheme',t),theme);const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push({url:p.url(),message:e.message,stack:e.stack}));try{await fn(p);assert.deepEqual(errors,[]);}finally{await c.close();}}
const view=p=>p.getByRole('combobox',{name:'View',exact:true});
const ready=p=>p.locator('[data-marker]').first().waitFor();
const shot=(p,name)=>p.screenshot({path:new URL(name+'.png',evidence).pathname.replace(/^\/([A-Z]:)/,'$1')});
async function pan(p,key,count){await p.locator('#dispatch-map').focus();for(let i=0;i<count;i++){await p.keyboard.press(key);await p.locator('.leaflet-pan-anim').waitFor({state:'detached'});} /* Leaflet keyboard pan completion. */}
const geometry=p=>p.locator('.geo-layout,.geo-list-panel,.geo-list-row,#dispatch-map,.geo-filters,.topbar,.sidebar,.shell-footer').evaluateAll(nodes=>nodes.map(e=>{const r=e.getBoundingClientRect();return [r.x,r.y,r.width,r.height];}));
async function collisions(p){return p.evaluate(()=>{const boxes=selector=>[...document.querySelectorAll(selector)].map(e=>{const r=e.getBoundingClientRect();return {l:r.left,r:r.right,t:r.top,b:r.bottom,name:e.textContent};});const labels=boxes('[data-context-label] span'),icons=boxes('[data-marker]');const overlap=(a,b)=>a.l<b.r&&a.r>b.l&&a.t<b.b&&a.b>b.t;return {icons:labels.filter(a=>icons.some(b=>overlap(a,b))).map(a=>a.name),labels:labels.filter((a,i)=>labels.slice(i+1).some(b=>overlap(a,b))).map(a=>a.name)};});}
test('route hierarchy and progressive county policy',()=>{const refs=['I 10','US 90;TX 146','SH 146','TX 321','FM 1960','RM 1'];assert.deepEqual(refs.map(ref=>roadLabelPolicy({ref}).rank),[1,1,2,2,3,3]);assert.equal(roadLabelPolicy({name:'North Main Street',highway:'tertiary'}).group,'city');assert.equal(roadLabelPolicy({name:'County Road 6610'}).minZoom,16);assert.equal(roadLabelPolicy({ref:'CR 605'}).rank,6);assert.equal(roadLabelPolicy({name:'Quiet Street',highway:'residential'}).minZoom,15);});
test('landmark extraction includes only sourced named civic classes and documents omissions',async()=>{const d=JSON.parse(await readFile(new URL('../dispatch/demo/dayton-landmarks.geojson',import.meta.url))),m=JSON.parse(await readFile(new URL('../dispatch/demo/dayton-landmarks-provenance.json',import.meta.url)));assert.equal(d.features.length,9);assert.deepEqual([...new Set(d.features.map(f=>f.properties.category))].sort(),['fire','park','police','school']);assert.ok(d.features.every(f=>f.properties.osmId&&f.properties.sourceModified&&f.properties.authority.includes('not independently verified')));assert.doesNotMatch(JSON.stringify(d),/restaurant|retail|fuel|shop|phone|housenumber|"uid"/i);assert.deepEqual(m.omittedDuplicateNames,['Colbert Elementary School']);assert.match(m.rawSha256,/^[a-f0-9]{64}$/);});
test('marker art grows modestly with backing, selected ring, supplemental severity and subdued resolved state',()=>visit(async p=>{await p.goto(base+'/?demo=1&view=map&unit=works');await ready(p);assert.equal(await p.getByLabel('ACTING UNIT').inputValue(),'works');const active=p.locator('[data-marker="DEMO-003"]'),resolved=p.locator('[data-marker="DEMO-004"]');assert.equal(await active.locator('img').evaluate(e=>e.getBoundingClientRect().width),80);const backing=await active.evaluate(e=>{const c=getComputedStyle(e,'::before');return [c.width,c.height,c.backgroundColor,c.borderWidth];});assert.equal(backing[0],'48px');assert.equal(backing[1],'48px');assert.notEqual(backing[2],'rgba(0, 0, 0, 0)');assert.equal(backing[3],'2px');assert.equal(await resolved.evaluate(e=>getComputedStyle(e).opacity),'0.7');assert.equal(await resolved.locator('.marker-state').innerText(),'✓');await active.focus();await p.keyboard.press('Enter');assert.equal(await active.getAttribute('aria-pressed'),'true');assert.equal(await active.evaluate(e=>getComputedStyle(e,'::before').outlineWidth),'3px');assert.match(await active.getAttribute('aria-label'),/Signal Outage.*SH 146/);assert.match(await active.locator('img').getAttribute('src'),/traffic-signal-issue/);assert.doesNotMatch(await active.innerText(),/^[HML]$/);await p.locator('.dispatch-popup').getByRole('button',{name:'View details'}).click();await p.getByRole('dialog').waitFor();await p.keyboard.press('Escape');assert.equal(await active.getAttribute('aria-pressed'),'true');}));
test('county roads stay quiet at wide zoom and return at close zoom; landmarks are selective',()=>visit(async p=>{await p.goto(base+'/?demo=1&view=map');await ready(p);for(let i=0;i<2;i++)await p.getByRole('button',{name:'Zoom out',exact:true}).click();await p.locator('#dispatch-map[data-map-zoom="13"]').waitFor();assert.equal(await p.locator('[data-label-group=county]').count(),0);assert.equal(await p.locator('[data-landmark-category=school]').count(),0);assert.ok(await p.locator('[data-label-group=major]').count()>0);await shot(p,'dark-wide-hierarchy');for(let i=0;i<3;i++)await p.getByRole('button',{name:'Zoom in',exact:true}).click();await p.locator('#dispatch-map[data-map-zoom="16"]').waitFor();await pan(p,'ArrowLeft',8);assert.ok(await p.locator('[data-label-group=county]').count()>0);assert.ok(await p.locator('[data-label-group=county]').count()<=3);await shot(p,'dark-close-county');assert.deepEqual(await collisions(p),{icons:[],labels:[]});}));
for(const theme of ['dark','light'])test(`${theme}: landmark orientation and incident/label collision precedence`,()=>visit(async p=>{await p.goto(base+'/?demo=1&view=map');await ready(p);assert.deepEqual(await collisions(p),{icons:[],labels:[]});await p.locator('[data-select="DEMO-001"]').click();assert.deepEqual(await collisions(p),{icons:[],labels:[]});await p.locator('.leaflet-popup-close-button').click();await p.getByRole('button',{name:'Fit incidents'}).click();await pan(p,'ArrowUp',3);await pan(p,'ArrowLeft',3);assert.ok(await p.locator('[data-landmark-category]').count()>0);assert.ok(await p.locator('[data-landmark-category]').count()<=4);assert.match(await p.locator('[data-landmark-category]').first().getAttribute('aria-label'),/OpenStreetMap.*not independently verified/);assert.deepEqual(await collisions(p),{icons:[],labels:[]});await shot(p,theme+'-landmark-context');await p.getByRole('button',{name:'Zoom in',exact:true}).click();await shot(p,theme+'-landmark-close');},{theme}));
test('unit URLs are validated local demo options; landmark data is gated and failure recovers',()=>visit(async p=>{await p.goto(base+'/?demo=1&unit=invalid');assert.equal(await p.getByLabel('ACTING UNIT').inputValue(),'police');await p.goto(login+'/?demo=1&view=map&unit=works');await p.getByRole('heading',{name:'Welcome to Dispatch'}).waitFor();for(const path of ['demo/dayton-landmarks.geojson','demo/dayton-landmarks-provenance.json','map-label-policy.mjs'])assert.equal((await fetch(login+'/'+path)).status,404);await p.route('**/dayton-landmarks.geojson',r=>r.fulfill({status:503,body:''}));await p.goto(base+'/?demo=1&view=map');await p.getByText('Map unavailable',{exact:true}).waitFor();assert.equal(await p.locator('[data-select]').count(),2);await view(p).selectOption('board');assert.equal(await p.locator('tbody tr').count(),2);await p.unroute('**/dayton-landmarks.geojson');await view(p).selectOption('map');await ready(p);}));
for(const theme of ['dark','light'])for(const [width,height]of [[1440,900],[1920,1080],[1280,720],[1024,768]])test(`${theme} ${width}x${height}: exact approved Board, unchanged structure and marker certification`,()=>visit(async p=>{
  await p.goto(approved+'/?demo=1');await p.locator('tbody tr').first().waitFor();const board=await p.screenshot(),bounds={};
  for(const mode of ['split','map']){await view(p).selectOption(mode);await ready(p);bounds[mode]=await geometry(p);await shot(p,`${theme}-${width}x${height}-${mode}-before`);}
  await p.goto(base+'/?demo=1');await p.locator('tbody tr').first().waitFor();await p.mouse.move(0,0);assert.equal(board.equals(await p.screenshot()),true);await shot(p,`${theme}-${width}x${height}-board`);
  for(const unit of ['police','works']){await p.getByLabel('ACTING UNIT').selectOption(unit);for(const mode of ['split','map']){await view(p).selectOption(mode);await ready(p);await p.evaluate(()=>scrollTo(0,0));if(unit==='police')assert.deepEqual(await geometry(p),bounds[mode]);assert.deepEqual(await collisions(p),{icons:[],labels:[]});await shot(p,`${theme}-${width}x${height}-${unit}-${mode}`);await p.locator(`[data-select="${unit==='works'?'DEMO-003':mode==='split'?'DEMO-001':'DEMO-002'}"]`).click();await shot(p,`${theme}-${width}x${height}-${unit}-${mode}-selected`);}}
  await p.locator('.leaflet-popup-close-button').click();await shot(p,`${theme}-${width}x${height}-resolved-debris`);
},{theme,width,height}));
