import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import {MOCK_PROVIDER,validateProvider,validTile,renderMockTile} from '../dispatch/basemap-provider.mjs';
import {withinDaytonDisplay} from '../dispatch/basemap.mjs';
import {previewServer} from '../tools/dispatch-ui/serve.mjs';
let server,plain,browser,base,login;
const listen=s=>new Promise(r=>s.listen(0,'127.0.0.1',()=>r('http://127.0.0.1:'+s.address().port)));
before(async()=>{server=previewServer({demo:true});plain=previewServer();base=await listen(server);login=await listen(plain);browser=await chromium.launch({headless:true,channel:process.env.DISPATCH_BROWSER_CHANNEL||'msedge'});});
after(async()=>{await browser?.close();await Promise.all([server,plain].map(s=>new Promise(r=>s.close(r))));});
test('immutable synthetic provider never claims real roadway coverage',()=>{assert.equal(validateProvider(MOCK_PROVIDER),MOCK_PROVIDER);assert.ok(Object.isFrozen(MOCK_PROVIDER));assert.match(MOCK_PROVIDER.attribution,/mock.*Synthetic/i);assert.match(MOCK_PROVIDER.coverage,/no real/i);});
for(const change of [{kind:'licensed'},{id:'other'},{url:'https://tiles.invalid'},{token:'unapproved'},{maxZoom:30},{renderTile:()=>{}},{attribution:'Certified statewide road map'},{coverage:'Actual complete roadway coverage'}])test('unsupported descriptor fails closed '+Object.keys(change)[0],()=>assert.throws(()=>validateProvider({...MOCK_PROVIDER,...change})));
for(const c of [{z:4,x:0,y:0},{z:19,x:0,y:0},{z:5,x:-1,y:0},{z:5,x:32,y:0},{z:5,x:0,y:32},{z:5,x:0.5,y:0}])test('invalid tile rejected '+JSON.stringify(c),()=>assert.equal(validTile(c),false));
test('local county and regional tile coordinates are supported',()=>{for(const z of [5,9,14,18])assert.equal(validTile({z,x:0,y:2**z-1}),true);});
test('canvas rendering is deterministic and labels absence of road data',()=>{const draw=()=>{const calls=[],ctx=new Proxy({},{get:(_,k)=>(...a)=>calls.push([k,...a]),set:(_,k,v)=>{calls.push([k,v]);return true;}}),canvas={getContext:()=>ctx};renderMockTile(canvas,{z:9,x:111,y:202});return calls;};assert.deepEqual(draw(),draw());assert.ok(draw().some(c=>c.includes('SYNTHETIC · NO ROAD DATA')));assert.throws(()=>renderMockTile({getContext:()=>null},{z:9,x:0,y:0}),/unavailable/);});
test('Dayton extract coverage is display-only and bounded',()=>{assert.equal(withinDaytonDisplay({lat:30.047,lng:-94.891}),true);assert.equal(withinDaytonDisplay({lat:32.77,lng:-96.8}),false);});
test('module is demo gated; unknown routes and mutations remain refused',async()=>{assert.equal((await fetch(base+'/basemap-provider.mjs')).status,200);assert.equal((await fetch(base+'/basemap-provider.mjs',{method:'HEAD'})).status,200);assert.equal((await fetch(login+'/basemap-provider.mjs')).status,404);assert.equal((await fetch(base+'/unapproved-provider.mjs')).status,404);assert.equal((await fetch(base+'/basemap-provider.mjs',{method:'POST'})).status,405);assert.equal((await fetch(base+'/basemap-provider.mjs')).headers.get('content-security-policy').includes("connect-src 'self'"),true);});
async function visit(fn,{fail=false}={}){const context=await browser.newContext();await context.addInitScript(fail=>{let value;window.__maps=[];Object.defineProperty(window,'L',{get:()=>value,set:L=>{value=L;const f=L.map;L.map=(...a)=>{const m=f(...a);window.__maps.push(m);return m;};}});if(fail){const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(...a){if(this.dataset.mockTile)return null;return original.apply(this,a);};}},fail);const page=await context.newPage(),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>{if(!route.request().url().startsWith(base+'/')){external.push('external request');return route.abort();}return route.continue();});try{await page.goto(base+'/?demo=1&view=map&basemap=mock');await page.locator('[data-marker]').first().waitFor();await fn(page);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);}finally{await context.close();}}
test('free Texas panning and regional county local zoom; tile pruning and zero external requests',()=>visit(async p=>{await expect(p.locator('.map-source-status')).toContainText('healthy');for(const [lat,lng,z]of [[32.77,-96.8,5],[29.76,-95.37,9],[31.76,-106.49,14],[35.22,-101.83,18]]){await p.evaluate(([lat,lng,z])=>{window.__maps[0].setView([lat,lng],z,{animate:false});},[lat,lng,z]);await expect.poll(()=>p.evaluate(()=>window.__maps[0].getZoom())).toBe(z);const center=await p.evaluate(()=>{const m=window.__maps[0];return [m.getCenter().lat,m.getCenter().lng,!!m.options.maxBounds];});assert.ok(Math.abs(center[0]-lat)<0.01&&Math.abs(center[1]-lng)<0.01);assert.equal(center[2],false);await expect(p.locator('.map-source-status')).toContainText('healthy');assert.ok(await p.locator('[data-mock-tile]').count()<150);}await expect(p.locator('.map-source-status')).toContainText('no real geographic data');}));
test('tile failure produces truthful limited fallback without exception or camera relocation',()=>visit(async p=>{await expect(p.locator('.map-source-status')).toContainText('fallback');assert.equal(await p.locator('[data-mock-tile]').count(),0);await p.evaluate(()=>{window.__maps[0].setView([32.77,-96.8],7,{animate:false});});await expect(p.locator('.map-source-status')).toContainText('No local cartography coverage');assert.equal(await p.evaluate(()=>window.__maps[0].getZoom()),7);},{fail:true}));
test('provider switch preserves camera and markers; missing extract coverage remains explicit',()=>visit(async p=>{await p.getByRole('button',{name:'Expand Map',exact:true}).click();await p.evaluate(()=>{window.__maps[0].setView([32.77,-96.8],7,{animate:false});});const before=await p.evaluate(()=>{const m=window.__maps[0],c=m.getCenter();return [c.lat,c.lng,m.getZoom()];});const markers=await p.locator('[data-marker]').count();await p.getByRole('button',{name:'Filters',exact:true}).click();await p.getByRole('combobox',{name:'Basemap source'}).selectOption('dayton');await expect(p.locator('.map-source-status')).toContainText('No local cartography coverage');assert.deepEqual(await p.evaluate(()=>{const m=window.__maps[0],c=m.getCenter();return [c.lat,c.lng,m.getZoom()];}),before);assert.equal(await p.locator('[data-marker]').count(),markers);await p.getByRole('combobox',{name:'Basemap source'}).selectOption('local-mock');await expect(p.locator('.map-source-status')).toContainText('healthy');assert.equal(await p.evaluate(()=>window.__maps.length),1);}));

test('camera outside Web Mercator tile extent is reported unavailable, never healthy blank coverage',()=>visit(async p=>{await expect(p.locator('.map-source-status')).toContainText('healthy');await p.evaluate(()=>{window.__maps[0].setView([30,210],7,{animate:false});});await expect(p.locator('.map-source-status')).toContainText('fallback');await expect(p.locator('.map-source-status')).toContainText('No local cartography coverage');}));
