const assert = require('assert');
const fs = require('fs');

const app = fs.readFileSync('js/app.js', 'utf8');
const manifestText = fs.readFileSync('data/roadway-runtime-manifest.json', 'utf8');
const manifest = JSON.parse(manifestText);
const harris = manifest.counties['harris-tx'];
const originalExternalCounties = ['chambers-tx', 'jefferson-tx', 'hardin-tx', 'polk-tx', 'walker-tx', 'orange-tx', 'jasper-tx', 'newton-tx', 'tyler-tx', 'galveston-tx', 'brazoria-tx', 'fort-bend-tx', 'waller-tx', 'austin-tx', 'washington-tx', 'brazos-tx', 'grimes-tx', 'wharton-tx', 'colorado-tx', 'fayette-tx', 'lavaca-tx', 'jackson-tx', 'matagorda-tx', 'calhoun-tx'];

assert.strictEqual(harris.status, 'partition_runtime_integrated', 'Harris uses partition runtime integration state');
assert.strictEqual(harris.url, null, 'Harris does not use a single county package URL');
assert.strictEqual(harris.integrationGateEnabled, true, 'Harris integration gate remains enabled');
assert.strictEqual(harris.packageVersion, 'lp032.2', 'Harris package version is LP032.2');
assert.ok(harris.manifestUrl.endsWith('/roadways/harris-tx/lp032.2/manifest.json'), 'Harris uses a partition manifest URL');
assert.ok(app.includes('GRIDLY_HARRIS_PARTITION_RUNTIME_COUNTY_ID = "harris-tx"'), 'runtime is explicitly Harris-only');
assert.ok(app.includes('GRIDLY_HARRIS_PARTITION_RUNTIME_CONCURRENCY_LIMIT = 2'), 'bounded queue concurrency remains unchanged');
assert.ok(app.includes('GRIDLY_HARRIS_PARTITION_RUNTIME_PREFETCH_LIMIT = 2'), 'neighbor prefetch remains explicitly bounded');
assert.ok(app.includes('GRIDLY_HARRIS_PARTITION_RUNTIME_CACHE_LIMIT = 5'), 'Harris package cache is explicitly bounded to four visible packages plus one transition package');
assert.ok(app.includes('state.packageCache.size <= GRIDLY_HARRIS_PARTITION_RUNTIME_CACHE_LIMIT'), 'bounded-cache audit still enforces the configured cache limit');
assert.ok(app.includes('!protectedIds.has(entry.packageId)') && app.includes('Number(a.lastUsed || 0) - Number(b.lastUsed || 0)'), 'inactive LRU eviction remains present while protected packages are retained');
assert.ok(app.includes('state.queue.sort((a, b) => a.priority - b.priority)'), 'request queue prioritizes visible packages');
assert.ok(app.includes('state.activeGeneration') && app.includes('staleRequestSuppressions'), 'stale-request protection exists');
assert.ok(app.includes('function gridlyCompleteHarrisPackageRequest(request, text, features)'), 'successful package completion is centralized for authoritative cache updates');
assert.ok(app.includes('status: "loaded", features, featureCount: features.length, byteLength: text.length'), 'successful fetch stores parsed features, featureCount, and byteLength on the authoritative cache entry');
assert.ok(app.includes('gridlyCompleteHarrisPackageRequest(request, text, features); }).catch'), 'queued to loading to loaded transition is wired from the package fetch worker');
assert.ok(app.includes('function gridlyFailHarrisPackageRequest(request, error)'), 'failed package completion is centralized for authoritative cache updates');
assert.ok(app.includes('status: "failed", featureCount: 0, features: []'), 'failed fetch transitions authoritative cache entry to failed and clears parsed features');
assert.ok(app.includes('state.inFlight.delete(request.packageId); state.requestHistory.push({ ...request, completedAt'), 'in-flight cleanup and completion recording occur after both success and failure paths');
assert.ok(app.includes('gridlyEvictHarrisPackageCache(); gridlyAssembleHarrisActiveGeometry(); gridlyPumpHarrisPackageQueue();'), 'active geometry assembly is invoked after package completion before queue pumping continues');
assert.ok(app.includes('gridlyGetActiveCountyId() !== GRIDLY_HARRIS_PARTITION_RUNTIME_COUNTY_ID || request.generation !== state.activeGeneration'), 'stale completion cannot activate Harris geometry after county switch generation changes');
assert.ok(app.includes('state.packageCache.delete(request.packageId); return false;'), 'stale completions do not leave completed requests permanently loading');
assert.ok(app.includes('packageCompletionStatePass'), 'audit exposes the package completion state contract');
assert.ok(app.includes('entry.status === "loading" && completedRequestPackageIds.has(entry.packageId)'), 'package completion contract rejects completed requests that remain loading');
assert.ok(app.includes('gridlyGetHarrisSegmentId') && app.includes('stableSegmentId'), 'stable segment-ID deduplication exists');
assert.ok(app.includes('gridlyHarrisPackageOwnsSegment') && app.includes('canonicalOwnerPackageId'), 'canonical ownership is respected');
assert.ok(app.includes('gridlyScheduleHarrisPartitionVisibleBoundsLoad'), 'visible-bounds loader is installed');
assert.ok(app.includes('prefetchReasonByPackage') && app.includes('neighbors'), 'edge-neighbor prefetch is audited from manifest neighbors');
assert.ok(!/manifest\.packages\.forEach\(\s*\(?packageId|manifest\.packages\.forEach\(\s*\(?pkg[\s\S]{0,160}gridlyQueueHarrisPackage/.test(app), 'no all-package preload behavior is introduced');
assert.ok(app.includes('gridlyLp032HarrisPartitionRuntimeAudit'), 'audit helper is exposed');
assert.ok(app.includes('window.gridlyLp032HarrisPartitionRuntimeAudit = gridlyLp032HarrisPartitionRuntimeAudit'), 'browser audit helper is attached');
assert.ok(app.includes('function gridlyDeactivateHarrisPartitionRuntimeState'), 'county-switch deactivation helper is implemented');
assert.ok(app.includes('entry.activeGeometryState = "inactive"'), 'county-switch deactivation marks cached Harris geometry inactive without deleting loaded cache entries');
assert.ok(app.includes('state.activePackageIds = []'), 'county-switch deactivation clears active Harris package IDs');
assert.ok(app.includes('state.activeFeatureCount = 0'), 'county-switch deactivation clears active Harris feature count');
assert.ok(app.includes('state.lastAssemblySignature = ""'), 'county-switch deactivation resets assembly signature');
assert.ok(app.includes('state.loadStatus = "partition_runtime_inactive"'), 'county-switch deactivation transitions Harris load status inactive');
assert.ok(app.includes('function gridlyGetHarrisPartitionInactiveStatePass'), 'inactive state audit boolean is implemented');
assert.ok(app.includes('activeGeometryEntries.length === 0') && app.includes('state.activePackageIds.length === 0'), 'cleanup pass rejects active Harris package geometry after leaving Harris');
assert.ok(app.includes('activeGeometryState = activePackageIds.has(packageId) ? "visible" : "inactive"'), 'returning to Harris reactivates selected cached packages while leaving unneeded cache inactive');
assert.ok(app.includes('cached?.status === "loaded"') && app.includes('state.duplicateRequestSuppressions += 1'), 'valid cached Harris packages are reused without weakening duplicate/stale request protection');
assert.ok(app.includes('activeAssemblyState'), 'debug helper exposes current authoritative active assembly state');
assert.ok(!/harris-tx[\s\S]{0,220}data\/liberty-county-road-segments\.geojson/.test(app), 'no Liberty fallback is introduced for Harris');
assert.ok(!/service_role|service-role|SUPABASE_SERVICE_ROLE|sb_secret|supabase[^\n]{0,120}Authorization\s*:/i.test(app + manifestText), 'no Supabase credentials or authorization secret are embedded');
assert.ok(!/storage\/v1\/object\/(?:upload|sign|move|copy)|createSignedUrl|upload\(/i.test(app), 'no Supabase upload code is added to browser runtime');
originalExternalCounties.forEach((countyId) => {
  assert.strictEqual(manifest.counties[countyId].status, 'external_runtime', `${countyId} remains external runtime`);
  assert.ok(manifest.counties[countyId].url.includes(`/roadways/${countyId}/lp030-v1/`), `${countyId} external URL remains unchanged`);
});

console.log('LP032.4 Harris partition runtime static guardrail tests passed');
