const fs = require('fs');
const vm = require('vm');
const source = fs.readFileSync('js/app.js', 'utf8');
const start = source.indexOf('function gridlyLp0546NormalizeAreaKey');
const end = source.indexOf('window.gridlyLp0544ContextAwareHistoricalIntelligenceAudit', start);
if (start < 0 || end < 0) throw new Error('LP054.6D block not found');
const sandbox = { window: {}, exposeGridlyAuditHelper(name, fn) { sandbox.window[name] = fn; }, Object, Array, Set, Boolean, Number, String, RegExp };
vm.createContext(sandbox);
vm.runInContext(source.slice(start, end), sandbox);
const audit = sandbox.window.gridlyLp0546dCommunityScopePrecedenceAudit();
function assert(condition, message) { if (!condition) throw new Error(message); }
const byName = Object.fromEntries(audit.cases.map((c) => [c.caseName, c]));
assert(audit.browserCertificationStatus === 'PASS', 'aggregate audit should PASS');
assert(audit.safeToMergeLp0546d === true, 'LP054.6D should be safe to merge');
assert(byName.incompatible_dayton_vs_liberty.communityScopeEvaluationApplied === true, 'community scope evaluated first');
assert(byName.incompatible_dayton_vs_liberty.communityMismatchDetected === true, 'community mismatch detected');
assert(byName.incompatible_dayton_vs_liberty.countyScopeEvaluationApplied === false, 'county scope must not override community mismatch');
assert(byName.incompatible_dayton_vs_liberty.awarenessAreaCompatibilityPass === false, 'Dayton vs Liberty must be incompatible');
assert(byName.incompatible_dayton_vs_liberty.awarenessAreaCompatibilityReason === 'incompatible_community', 'Dayton vs Liberty reason');
assert(byName.incompatible_dayton_vs_cleveland.awarenessAreaCompatibilityReason === 'incompatible_community', 'Dayton vs Cleveland reason');
assert(byName.same_community_dayton.awarenessAreaCompatibilityPass === true, 'same Dayton should pass');
assert(byName.missing_crossing_community_in_dayton_scope.awarenessAreaCompatibilityReason === 'missing_crossing_community', 'missing crossing community conservative reason');
assert(byName.liberty_countywide_alias.awarenessAreaCompatibilityPass === true, 'countywide Liberty alias remains compatible');
assert(byName.different_county.awarenessAreaCompatibilityReason === 'incompatible_county', 'different county rejection');
assert(byName.existing_waco_marker_in_dayton.resolvedContextSubject === 'Waco Street crossing at US 90', 'Waco subject preserved in Dayton');
assert(byName.dayton_to_liberty_community_change.staleSpecificSubjectDetected === false, 'stale Waco subject removed');
assert(byName.dayton_to_liberty_community_change.staleSpecificPatternDetected === false, 'stale Waco pattern removed');
const mismatchAudit = sandbox.window.gridlyLp0546dCommunityScopePrecedenceAudit({ forceExpectationMismatch: true });
assert(mismatchAudit.browserCertificationStatus === 'REVIEW', 'expectation mismatch must REVIEW');
console.log(JSON.stringify({ status: audit.browserCertificationStatus, cases: audit.cases.length, failedCases: audit.failedCases }));
