const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const crypto = require('crypto');

const app = fs.readFileSync('js/app.js', 'utf8');
const ps = fs.readFileSync('scripts/build-gridly-zip-source.ps1', 'utf8');
const tool = fs.readFileSync('tools/build-gridly-zip-source.js', 'utf8');
const doc = fs.readFileSync('docs/LP051-4-OWNER-SIDE-ZIP-SOURCE-ACQUISITION-AND-IMPORT.md', 'utf8');
const runtime = JSON.parse(fs.readFileSync('data/gridly-zip-awareness-index-v2.json', 'utf8'));
const normalized = JSON.parse(fs.readFileSync('data/generated/gridly-zip-county-source-v1.json', 'utf8'));
const candidates = JSON.parse(fs.readFileSync('data/generated/gridly-zip-awareness-candidates-v1.json', 'utf8'));

assert(fs.existsSync('scripts/build-gridly-zip-source.ps1'), 'PowerShell acquisition helper exists');
assert(!ps.includes('&&'), 'PowerShell helper avoids PowerShell 7-only && syntax');
assert(ps.includes('GRIDLY_HUD_TOKEN'), 'HUD token is read from environment/local owner input');
assert(!/Bearer\s+[A-Za-z0-9._-]{12,}/.test(ps + tool + doc), 'no embedded credential values are committed');
assert(tool.includes('sourceType=\'hud_zip_county\'') || tool.includes("hud_zip_county"), 'source detector recognizes HUD ZIP-county source');
assert(tool.includes('census_zcta_gazetteer'), 'source detector recognizes Census ZCTA supporting source');
assert(tool.includes('schemaStatus'), 'source schema status is reported');
assert(tool.includes('sha256'), 'SHA-256 metadata is generated');
assert(doc.includes('ZIP/ZCTA equality is never sufficient'), 'ZIP-versus-ZCTA distinction is documented');
assert(doc.includes('Manual HUD download') || doc.includes('manually download'), 'manual HUD download fallback is documented');
assert.strictEqual(runtime.records.length, 36, 'LP051.3 governed runtime foundation is preserved');
assert.strictEqual(runtime.sourceImportCertificationStatus, 'blocked', 'source import does not claim complete without source');
assert.strictEqual(runtime.mergeReadyForUiIntegration, false, 'UI integration is not forced ready');
assert.strictEqual(normalized.records.length, 0, 'no normalized source rows are fabricated without source');
assert.strictEqual(candidates.records.length, 0, 'no source-backed candidates are fabricated without source');
assert.strictEqual(runtime.records.find((r) => r.zip === '77084').status, 'ambiguous', '77084 remains ambiguous');
assert.strictEqual(runtime.records.find((r) => r.zip === '77201').status, 'po_box_not_supported', 'PO Box-only behavior remains governed');
assert.strictEqual(runtime.records.find((r) => r.zip === '77210').status, 'unique_zip_not_supported', 'unique ZIP behavior remains governed');
assert(tool.includes('source_county_candidate_only'), 'county-only evidence is candidate-only, not automatic community resolution');
assert(tool.includes('split_supported_and_unsupported'), 'supported/unsupported overlap classification is represented');
assert(tool.includes('dominant_county_candidate'), 'dominant county policy is explicit');

const second = crypto.createHash('sha256').update(fs.readFileSync('data/gridly-zip-awareness-index-v2.json')).digest('hex');
require('child_process').execFileSync(process.execPath, ['tools/build-gridly-zip-source.js'], { stdio: 'ignore' });
const third = crypto.createHash('sha256').update(fs.readFileSync('data/gridly-zip-awareness-index-v2.json')).digest('hex');
assert.strictEqual(second, third, 'runtime generation is deterministic');

const noop = () => {};
const node = { style: {}, dataset: {}, hidden: true, classList: { add: noop, remove: noop, toggle: noop, contains: () => false }, appendChild: noop, setAttribute: noop, removeAttribute: noop, getAttribute: () => null, querySelector: () => null, querySelectorAll: () => [], addEventListener: noop, removeEventListener: noop, contains: () => false, getClientRects: () => [] };
const document = { addEventListener: noop, removeEventListener: noop, querySelector: () => null, querySelectorAll: () => [], getElementById: () => node, createElement: () => ({ ...node }), head: { appendChild: noop }, documentElement: { scrollWidth: 390, clientWidth: 390, classList: { add: noop, remove: noop, toggle: noop, contains: () => false } }, body: { ...node, classList: { add: noop, remove: noop, toggle: noop, contains: () => false } }, activeElement: null };
const sandbox = { window: { addEventListener: noop, removeEventListener: noop, location: { search: '' } }, document, localStorage: { data: {}, getItem(k) { return this.data[k] || null; }, setItem(k, v) { this.data[k] = String(v); }, removeItem(k) { delete this.data[k]; } }, sessionStorage: { getItem: () => null, setItem: noop, removeItem: noop }, navigator: { serviceWorker: null, userAgent: 'node' }, innerWidth: 390, innerHeight: 844, location: { search: '' }, console, setTimeout, clearTimeout, requestAnimationFrame: (fn) => fn(), crypto: { randomUUID: () => 'test-uuid' }, URLSearchParams, getComputedStyle: () => ({ display: 'block', visibility: 'visible' }), ResizeObserver: class { observe() {} disconnect() {} }, MutationObserver: class { observe() {} disconnect() {} }, fetch: async () => ({ ok: false, json: async () => ({}) }) };
sandbox.window = Object.assign(sandbox.window, sandbox);
vm.runInNewContext(app, sandbox, { timeout: 5000 });
const audit = sandbox.window.gridlyLp0514OwnerZipSourceAcquisitionAudit();
assert.strictEqual(audit.milestone, 'LP051.4');
assert.strictEqual(audit.ownerSideWorkflow, true);
assert.strictEqual(audit.passiveOnly, true);
assert.strictEqual(audit.sourceImportCertificationStatus, 'blocked');
assert.strictEqual(audit.coverageCertificationStatus, 'blocked');
assert.strictEqual(audit.supportedCountyCount, 28);
assert.strictEqual(audit.coveredCountyCount, 28);
assert.strictEqual(audit.unknownCountyIdCount, 0);
assert.strictEqual(audit.unknownCommunityCount, 0);
assert.strictEqual(audit.unknownAwarenessAreaCount, 0);
assert.strictEqual(audit.candidateIdentityErrorCount, 0);
assert.strictEqual(audit.manualSetupPreserved, true);
assert.strictEqual(audit.routeIntelligenceIndependent, true);
assert.strictEqual(audit.protectedSystemsUntouched, true);
assert.strictEqual(audit.mergeReadyForUiIntegration, false);
assert(audit.missingSourceRequirements.length > 0, 'blocked audit includes missing source requirements');
assert.strictEqual(sandbox.window.gridlyResolveHomeZipAwareness('77084').status, 'ambiguous');
assert.strictEqual(sandbox.window.gridlyResolveHomeZipAwareness('77201').status, 'po_box_not_supported');
assert.strictEqual(sandbox.window.gridlyResolveHomeZipAwareness('77210').status, 'unique_zip_not_supported');
assert.strictEqual(sandbox.window.gridlyResolveHomeZipAwareness('abc').status, 'invalid');
assert.strictEqual(sandbox.window.gridlyResolveHomeZipAwareness('99999').status, 'unsupported');
const beforeStorage = JSON.stringify(sandbox.localStorage.data);
sandbox.window.gridlyResolveHomeZipAwareness('77535');
assert.strictEqual(JSON.stringify(sandbox.localStorage.data), beforeStorage, 'resolver performs no storage writes');
