const assert = require('assert');
const fs = require('fs');

const app = fs.readFileSync('js/app.js', 'utf8');

assert.match(app, /version: "LP061"/, 'Travel Brief model is advanced to LP061');
assert.match(app, /driverDecisionPattern: true/, 'Travel Brief model declares Driver Decision Pattern ownership');
assert.match(app, /key: "driver-decision"/, 'Driver Decision section is present');
assert.match(app, /pattern: "LP061 Driver Decision Pattern"/, 'Driver Decision section identifies LP061 pattern');
assert.match(app, /lines: Object\.freeze\(\[interpretation, reason, confidence, freshness\]\)/, 'Travel Brief orders interpretation, reason, confidence, freshness');
assert.match(app, /gridlyDecisionRole/, 'Driver Decision DOM preserves logical field roles');
assert.match(app, /sourceLine: ""/, 'Driver Decision suppresses technical source label in consumer presentation');
assert.match(app, /gridlyBuildTravelBriefDecisionSection\(\{ story, records, driveTexasRecords \}\),\n\s+Object\.freeze\(\{ key: "community"/, 'Driver Decision section renders before existing source sections');
assert.match(app, /gridlyStoryActiveRecords\(\)/, 'Travel Brief preserves active community source');
assert.match(app, /gridlyStoryTransportationConnectorRecords\(\)/, 'Travel Brief preserves official roadway source');
assert.match(app, /gridlyBriefInteractionWeatherModel\(\)/, 'Travel Brief preserves weather source');
assert.match(app, /window\.gridlyLp061DriverDecisionPatternAudit = gridlyLp061DriverDecisionPatternAudit/, 'LP061 browser audit is exposed');
assert.match(app, /existingActionsPreserved: preservedActionValues\.every\(Boolean\)/, 'LP061 audit checks contextual action preservation');
assert.match(app, /confirm: Object\.freeze\(\{ applicable: contextualIncidentActionsApplicable, preserved: confirmPathPreserved/, 'Confirm action is contextually optional while preserving capability');
assert.match(app, /markCleared: Object\.freeze\(\{ applicable: contextualIncidentActionsApplicable, preserved: clearPathPreserved/, 'Mark Cleared action is contextually optional while preserving capability');
assert.match(app, /visibleWhenApplicable: !contextualIncidentActionsApplicable \|\| \/confirm\|still there\/i\.test\(actionText\)/, 'Applicable active-state confirm visibility remains protected');
assert.match(app, /visibleWhenApplicable: !contextualIncidentActionsApplicable \|\| \/mark cleared\|cleared\/i\.test\(actionText\)/, 'Applicable active-state clear visibility remains protected');
assert.match(app, /consumerPresentationLabelsSuppressed/, 'LP061 audit rejects exposed structural labels');
assert.match(app, /routeWatchLogic: "unchanged"/, 'LP061 audit protects Route Watch logic');
assert.match(app, /communityPulseLogic: "unchanged"/, 'LP061 audit protects Community Pulse logic');
assert.match(app, /officialRoadwayProcessing: "unchanged"/, 'LP061 audit protects official roadway processing');
assert.match(app, /weatherProcessing: "unchanged"/, 'LP061 audit protects weather processing');
assert.match(app, /hazardLifecycle: "unchanged"/, 'LP061 audit protects hazard lifecycle');
assert.match(app, /crossingLifecycle: "unchanged"/, 'LP061 audit protects crossing lifecycle');
assert.match(app, /reporting: "unchanged"/, 'LP061 audit protects reporting');
assert.match(app, /supabase: "unchanged"/, 'LP061 audit protects Supabase');
assert.match(app, /alertGeneration: "unchanged"/, 'LP061 audit protects alert generation');
const lp061Block = app.slice(app.indexOf('function gridlyTravelBriefFreshnessLine'), app.indexOf('function gridlyRenderTravelBrief'));
const renderBlock = app.slice(app.indexOf('function gridlyRenderTravelBrief'), app.indexOf('window.gridlyBuildTravelBriefModel'));
const css = fs.readFileSync('css/styles.css', 'utf8');
assert.doesNotMatch(lp061Block, /safe to proceed|guaranteed safety|guaranteed safe|all clear/i, 'Quiet-state language avoids safety guarantees');
assert.doesNotMatch(renderBlock, /Gridly interpretation/, 'Rendered consumer presentation does not expose Gridly interpretation');
assert.match(css, /gridly-travel-brief-item\[data-gridly-travel-brief-section=\"driver-decision\"\] \{[\s\S]*grid-template-columns: minmax\(0, 1fr\)/, 'Driver Decision is not constrained to narrow two-column layout');
assert.match(css, /data-gridly-decision-role=\"confidence\"[\s\S]*data-gridly-decision-role=\"freshness\"/, 'Confidence and freshness share compact metadata styling');

console.log('LP061 Driver Decision Pattern regression passed');
