const assert=require("node:assert/strict"),fs=require("node:fs");
const kb=require("../js/historical-knowledge-base.js"),retrieval=require("../js/historical-knowledge-retrieval.js"),sessions=require("../js/historical-retrieval-session.js"),assembly=require("../js/historical-narrative-input-assembly.js"),governance=require("../js/historical-narrative-invocation-governance.js");
const base=kb.createKnowledgeBase([{patternId:"p:1",revision:1,lineageId:"l:1",archiveId:"a:1",crossingIdentity:"x:1",roadwayIdentity:"road:1",awarenessArea:"area:1",community:"community:1",county:"county:1",category:"rail-delay",lifecycleStatus:"active",qualityStatus:"stable",evidenceStrength:4,activeRevision:true,lineageValid:true}]);
const request={contractVersion:retrieval.VERSIONS.requestContract,policyVersions:retrieval.VERSIONS,requestIdentity:"request:1",retrievalMode:"crossing-context",canonicalTimestamp:"2026-07-27T08:00:00Z",localTimestamp:"2026-07-27T08:00:00Z",canonicalTimezone:"UTC",countyIdentity:"county:1",communityIdentity:"community:1",awarenessAreaIdentity:"area:1",roadwayIdentity:"road:1",crossingIdentity:"x:1",patternCategory:"rail-delay"};
function inputFor(req=request){const result=retrieval.retrieve(base,req),context={canonicalTimestamp:req.canonicalTimestamp,localTimestamp:req.localTimestamp,canonicalTimezone:"UTC",countyIdentity:req.countyIdentity,communityIdentity:req.communityIdentity,awarenessAreaIdentity:req.awarenessAreaIdentity,roadwayIdentity:req.roadwayIdentity,crossingIdentity:req.crossingIdentity,knowledgeBaseFingerprint:base.fingerprints.knowledge,retrievalPolicyVersions:retrieval.VERSIONS};let session=sessions.createSession({contractVersion:sessions.VERSIONS.sessionContract,sessionPolicyVersions:sessions.VERSIONS,sessionMode:req.retrievalMode==="quiet-state-evaluation"?"quiet-state-investigation":"single-subject",creationContext:context});session=sessions.registerRequest(session,req,result);return assembly.assemble({contractVersion:assembly.VERSIONS.narrativeInputContract,policyVersions:assembly.VERSIONS,retrievalResult:result,session});}
const narrativeInput=inputFor(),options={contractVersion:governance.VERSIONS.invocationContract,invocationPolicyVersions:governance.VERSIONS,invocationMode:"generation",authorizationState:"generation authorized",narrativeInput};
assert.equal(governance.planInvocation({...options,contractVersion:"bad"}).failureCodes[0],governance.FAILURE_CODES.UNSUPPORTED_VERSION);
assert.equal(governance.planInvocation({...options,invocationPolicyVersions:{...governance.VERSIONS,quietPolicy:"bad"}}).failureCodes[0],governance.FAILURE_CODES.UNSUPPORTED_VERSION);
assert.equal(governance.planInvocation({...options,authorizationState:"unauthorized"}).failureCodes[0],governance.FAILURE_CODES.UNAUTHORIZED);
assert.equal(governance.planInvocation({...options,authorizationState:"dry-run authorized"}).failureCodes[0],governance.FAILURE_CODES.MODE_MISMATCH);
const a=governance.planInvocation(options),b=governance.planInvocation(Object.fromEntries(Object.entries(options).reverse()));assert.equal(a.accepted,true);assert.equal(a.invoked,false);assert.equal(a.invocationIdentity,b.invocationIdentity);assert.deepEqual(a,b);assert.equal(a.contract.invocationState,"generation-ready");assert.ok(Object.isFrozen(a)&&Object.isFrozen(a.plan)&&Object.isFrozen(a.diagnostics.fingerprints));assert.throws(()=>{"use strict";a.plan.invocationMode="bad"},TypeError);
assert.equal(a.duplicatePrevented,true);assert.equal(a.idempotent,true);assert.equal(a.explainability.validationStages.length,9);assert.equal(a.compatibility.compatible,true);assert.notEqual(governance.fingerprint(a.plan),governance.fingerprint({...a.plan,invocationMode:"dry-run"}));
let contract={invocationState:"created",lifecycleEvidence:[]};for(const state of ["validated","authorized","generation-ready","invoked","completed"]){contract=governance.transition(contract,state);assert.equal(contract.invocationState,state);}assert.equal(governance.transition(contract,"created").failureCode,governance.FAILURE_CODES.INVALID_TRANSITION);
assert.equal(governance.planInvocation({...options,narrativeInput:{...narrativeInput,narrativeInputIdentity:"mutated"}}).failureCodes[0],governance.FAILURE_CODES.INVALID_INPUT);
const quietRequest={...request,requestIdentity:"request:quiet",retrievalMode:"quiet-state-evaluation",crossingIdentity:null,roadwayIdentity:null,awarenessAreaIdentity:null,communityIdentity:null};const quietInput=inputFor(quietRequest);const quiet=governance.planInvocation({...options,invocationMode:"dry-run",authorizationState:"dry-run authorized",narrativeInput:quietInput});assert.equal(quiet.accepted,true);assert.equal(quiet.plan.quietStatePath,true);assert.equal(quiet.plan.expectedNarrativeType,"quiet-state");assert.equal(quiet.quietPackage.quietReason,"quiet_state_evaluation_requested");assert.equal(Object.prototype.hasOwnProperty.call(quiet.quietPackage,"wording"),false);
assert.equal(governance.ACTIVATION.generationPerformed,false);assert.doesNotThrow(()=>require("../js/historical-narrative-generator.js"));assert.doesNotThrow(()=>require("../js/historical-narrative-ranking.js"));assert.doesNotThrow(()=>require("../js/historical-intelligence-activation-boundary.js"));assert.doesNotThrow(()=>require("../js/historical-narrative-input-assembly.js"));for(const file of ["index.html","js/app.js"])assert.doesNotMatch(fs.readFileSync(file,"utf8"),/LP085|historical-narrative-invocation-governance/i);assert.equal(governance.certificationAudit().safeToMerge,true);console.log("LP085 Historical Narrative Invocation Governance passed");
