const assert=require("node:assert/strict"),fs=require("node:fs"),v=require("../js/historical-narrative-output-validation.js");
const input={narrativeInputIdentity:"input:1",retrievalIdentity:"retrieval:1",sessionIdentity:"session:1",requestIdentity:"request:1",knowledgeBaseFingerprint:"kb:1",selectedSubjectIdentity:"crossing:main",selectedSubjectType:"crossing",candidateIdentities:["crossing:main"],contextSummary:{normalizedHistoricalContext:"weekday mornings"},durationEvidence:[{identity:"crossing:main",eligible:true}],quietState:{quiet:false},fingerprints:{narrativeInput:"input-fp"}};
const invocation={invocationIdentity:"invocation:1",plan:{expectedNarrativeType:"crossing_delay",invocationFingerprint:"invocation-fp"}};
function base(extra={}){return {invocationIdentity:"invocation:1",narrativeInputIdentity:"input:1",retrievalIdentity:"retrieval:1",sessionIdentity:"session:1",requestIdentity:"request:1",knowledgeBaseFingerprint:"kb:1",narrativeInputFingerprint:"input-fp",invocationFingerprint:"invocation-fp",narrativeType:"crossing_delay",subjectIdentity:"crossing:main",subjectType:"crossing",historicalStatement:"Historically, crossing:main has often been reported blocked during weekday mornings.",durationStatement:"Delays have typically lasted about 15 minutes.",contextStatement:"weekday mornings",quietOutput:null,provenanceSummary:{invocationIdentity:"invocation:1",narrativeInputIdentity:"input:1",candidateIdentities:["crossing:main"],supportedStatements:["Historically, crossing:main has often been reported blocked during weekday mornings."]},compatibilityMetadata:{lp068:true,lp069:true,lp070:true,lp084:true,lp085:true,productionIsolation:true},contractVersion:v.VERSIONS.outputContract,policyVersions:v.VERSIONS,...extra};}
const contract=base(),normalized=v.normalizeOutput(contract).normalized,valid=v.validateOutput(normalized,invocation,input);assert.equal(valid.accepted,true);assert.equal(valid.downstreamEligibility,"ranking-eligible");assert.ok(Object.isFrozen(valid)&&Object.isFrozen(valid.normalizedOutput)&&Object.isFrozen(valid.diagnostics.fingerprints));
assert.deepEqual(v.normalizeOutput(base()),v.normalizeOutput(Object.fromEntries(Object.entries(base()).reverse())));assert.equal(v.validateOutput(normalized,invocation,input).fingerprints.finalValidationResult,valid.fingerprints.finalValidationResult);
const reject=(extra,code,inp=input,inv=invocation)=>assert.ok(v.validateOutput(v.normalizeOutput(base(extra)).normalized,inv,inp).failureCodes.includes(code),code);
reject({contractVersion:"bad"},v.FAILURE_CODES.UNSUPPORTED_VERSION);reject({subjectIdentity:null},v.FAILURE_CODES.SUBJECT_MISSING);reject({subjectIdentity:"road:other"},v.FAILURE_CODES.SUBJECT_MISMATCH);reject({narrativeType:"unknown"},v.FAILURE_CODES.TYPE_INVALID);reject({historicalStatement:null},v.FAILURE_CODES.STATEMENT_MISSING);reject({historicalStatement:"The selected area has often been blocked.",provenanceSummary:{invocationIdentity:"invocation:1",narrativeInputIdentity:"input:1",candidateIdentities:["crossing:main"],supportedStatements:["The selected area has often been blocked."]}},v.FAILURE_CODES.GENERIC_SUBJECT);
reject({durationStatement:"It has typically lasted one minute."},v.FAILURE_CODES.DURATION_ARTIFACT);reject({},v.FAILURE_CODES.DURATION_INELIGIBLE,{...input,durationEvidence:[{identity:"crossing:main",eligible:false}]});reject({historicalStatement:"The crossing is blocked currently.",provenanceSummary:{invocationIdentity:"invocation:1",narrativeInputIdentity:"input:1",candidateIdentities:["crossing:main"],supportedStatements:["The crossing is blocked currently."]}},v.FAILURE_CODES.PREDICTIVE_CURRENT);reject({historicalStatement:"The crossing will be blocked."},v.FAILURE_CODES.PREDICTIVE_FUTURE);reject({historicalStatement:"Drivers should avoid this route."},v.FAILURE_CODES.ROUTE_DIRECTIVE);reject({historicalStatement:"A current alert exists."},v.FAILURE_CODES.CURRENT_ALERT_CLAIM);reject({provenanceSummary:{invocationIdentity:"wrong",narrativeInputIdentity:"input:1",candidateIdentities:["crossing:main"],supportedStatements:[contract.historicalStatement]}},v.FAILURE_CODES.PROVENANCE_MISMATCH);reject({narrativeInputFingerprint:"wrong"},v.FAILURE_CODES.FINGERPRINT_MISMATCH);reject({invocationFingerprint:"wrong"},v.FAILURE_CODES.FINGERPRINT_MISMATCH);reject({provenanceSummary:{invocationIdentity:"invocation:1",narrativeInputIdentity:"input:1",candidateIdentities:["candidate:bad"],supportedStatements:[contract.historicalStatement]}},v.FAILURE_CODES.CANDIDATE_UNSUPPORTED);
const quietInput={...input,selectedSubjectIdentity:null,selectedSubjectType:null,candidateIdentities:[],durationEvidence:[],quietState:{quiet:true}},quietInvocation={...invocation,plan:{expectedNarrativeType:"quiet-state",invocationFingerprint:"invocation-fp"},quietPackage:{quietIdentity:"quiet:1",quietReason:"no evidence"}},quietRaw=base({narrativeType:"quiet-state",subjectIdentity:null,subjectType:null,historicalStatement:null,durationStatement:null,quietOutput:{quietIdentity:"quiet:1",quietReason:"no evidence"},provenanceSummary:{invocationIdentity:"invocation:1",narrativeInputIdentity:"input:1",candidateIdentities:[],supportedStatements:[]}}),quiet=v.validateOutput(v.normalizeOutput(quietRaw).normalized,quietInvocation,quietInput);assert.equal(quiet.downstreamEligibility,"quiet-eligible");reject({quietOutput:{quietIdentity:"quiet:1",quietReason:"no evidence"}},v.FAILURE_CODES.QUIET_MISMATCH);
assert.notEqual(valid.fingerprints.normalizedOutput,v.validateOutput(v.normalizeOutput(base({contextStatement:null})).normalized,invocation,input).fingerprints.normalizedOutput);assert.equal(v.validateOutput(base({extra:"bad"}),invocation,input).downstreamEligibility,"rejected");
for(const f of ["historical-narrative-generator.js","historical-narrative-ranking.js","historical-intelligence-activation-boundary.js","historical-narrative-input-assembly.js","historical-narrative-invocation-governance.js"])assert.doesNotThrow(()=>require(`../js/${f}`));for(const f of ["index.html","js/app.js"])assert.doesNotMatch(fs.readFileSync(f,"utf8"),/LP086|historical-narrative-output-validation/i);assert.equal(v.ACTIVATION.productionIntegration,false);assert.equal(v.certificationAudit().safeToMerge,true);console.log("LP086 Historical Narrative Output Validation passed");
