const assert = require("node:assert/strict");
const fs = require("node:fs"); const path = require("node:path"); const vm = require("node:vm");
const policy = require("../js/historical-operational-rollout-plan.js");
const input = policy.createOperationalInput(); const first = policy.assessOperationalRollout(input); const replay = policy.assessOperationalRollout(policy.createOperationalInput()); const r = first.report;
assert.equal(first.accepted, true); assert.deepEqual(first, replay); assert.deepEqual(r.rolloutStages.map(x => x.name), policy.STAGE_NAMES); assert.ok(r.rolloutStages.every(x => /explicit|none/.test(x.progression))); assert.equal(r.initialLearningScope.classification, "recommended-not-approved-not-implemented"); assert.deepEqual(r.initialLearningScope.approved, []); assert.deepEqual(r.initialLearningScope.implemented, []);
assert.match(r.proposedThresholds.classification, /proposed.*owner-approval/); assert.equal(r.proposedThresholds.provenRequirements, false); assert.deepEqual(r.evidencePlan.metrics.map(x => x.metric), policy.EVIDENCE_METRICS); assert.deepEqual(r.productValidationEvidence.concerns.map(x => x.concern), policy.PRODUCT_CONCERNS);
assert.equal(r.ownershipMatrix.length, 9); assert.ok(r.ownershipMatrix.every(x => x.owner)); assert.equal(r.incidentModel.length, 10); assert.ok(r.incidentModel.every(x => x.immediateAction && x.rollbackRequirement && x.reviewRequirement && x.restartCriteria)); assert.ok(r.rollbackPlan.every(x => !x.deletesEvidence && /archived observations/.test(x.evidencePreserved))); assert.equal(r.betaPlan.activationPerformed, false); assert.equal(r.activationDecisionFramework.ownerApprovalRequired, true); assert.equal(r.activationDecisionFramework.automaticDecision, false);
assert.deepEqual(r.launchChecklist.map(x => x.category), policy.CHECKLIST_CATEGORIES); assert.ok(r.decisionRegister.pendingOwnerApproval && r.decisionRegister.operationalAssumptions && r.decisionRegister.explicitNonDecisions); assert.ok(Object.isFrozen(first) && Object.isFrozen(r) && Object.isFrozen(r.rolloutStages) && Object.isFrozen(r.rolloutStages[0])); assert.ok(Object.values(r.sectionFingerprints).every(x => x.startsWith("lp093-fnv1a32:"))); assert.ok(r.reportFingerprint.startsWith("lp093-fnv1a32:"));
function reject(change, code) { const candidate = JSON.parse(JSON.stringify(input)); change(candidate); const result = policy.assessOperationalRollout(candidate); assert.equal(result.failClosed, true); assert.ok(result.failureCodes.includes(code)); }
reject(x => { x.reportVersion = "LP093.operational-rollout-report.v0"; }, policy.FAILURE_CODES.UNSUPPORTED_VERSION); reject(x => { x.policyVersions.betaPolicy = "LP093.beta-policy.v0"; }, policy.FAILURE_CODES.UNSUPPORTED_VERSION); reject(x => { x.requestedStage = 1; }, policy.FAILURE_CODES.INVALID_POLICY); reject(x => { x.automaticProgression = true; }, policy.FAILURE_CODES.INVALID_POLICY);
const audit = policy.operationalRolloutAudit(); assert.equal(audit.safeToMerge, true); assert.ok(Object.values(audit).every(Boolean));
const fixture = fs.readFileSync("tests/lp093-browser-certification.html", "utf8"); const scripts = [...fixture.matchAll(/<script src="([^"]+)"><\/script>/g)].map(x => x[1]); const window = { console: { table(){}, log(){}, error(){} } }; window.window=window; window.globalThis=window; const context=vm.createContext(window); scripts.forEach(relative => vm.runInContext(fs.readFileSync(path.resolve("tests", relative), "utf8"), context)); assert.equal(window.gridlyLp093HistoricalOperationalRolloutAudit().safeToMerge, true);
for (const file of ["index.html", "js/app.js"]) assert.doesNotMatch(fs.readFileSync(file, "utf8"), /LP093|historical-operational-rollout-plan/i);
assert.ok(r.productionIsolation.protectedSystems.every(x => x.unchanged)); assert.equal(r.productionIsolation.learningActive, false); assert.equal(r.productionIsolation.productionDataConnected, false);
console.log("LP093 Historical Intelligence Operational Rollout & Evidence Plan passed");
