const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const app = fs.readFileSync('js/app.js', 'utf8');
const client = fs.readFileSync('js/gridly-geocoding-client.js', 'utf8');
const edge = fs.readFileSync('supabase/functions/gridly-geocode/index.ts', 'utf8');
const migration = fs.readFileSync('supabase/migrations/202607280100_lp100_geocoding_governance.sql', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');
assert.doesNotMatch(app, /fetch\(`https:\/\/nominatim\.openstreetmap\.org\/search/);
assert.match(app, /gridlyGeocodingClient\.search/);
assert.match(app, /remote_search_explicit_action/);
assert.match(app, /while typing remains local-only/);
assert.match(app, /event\.key !== "Enter"/);
assert.ok(html.indexOf('gridly-geocoding-client.js') < html.indexOf('js/app.js'));
assert.match(html, /gridlyRemoteSearchBtn/);
assert.match(edge, /request\.method !== "POST"/);
assert.match(edge, /Content-Length/);
assert.match(edge, /unknown_field/);
assert.match(edge, /body\.query\.trim\(\)\.length < 3/);
assert.match(edge, /body\.limit > 15/);
assert.match(edge, /body\.context\?\.viewbox/);
assert.match(edge, /params\.set\("q", body\.query\)/);
assert.match(edge, /body\.structuredAddress\[field\]/);
assert.doesNotMatch(edge, /params\.set\("q"[^}]+structuredAddress/s);
assert.match(edge, /upstream\.status === 429/);
assert.match(edge, /Retry-After/);
assert.match(edge, /controller\.abort/);
assert.match(edge, /inflight\.has\(key\)/);
assert.match(edge, /gridly_reserve_geocode_provider_slot/);
assert.match(migration, /cache_key text primary key check \(cache_key ~ '\^\[a-f0-9\]\{64\}\$'\)/);
assert.match(migration, /greatest\(next_allowed_at, cooldown_until, clock_timestamp\(\)\)/);
assert.doesNotMatch(client, /localStorage|sessionStorage|console\./i);
assert.match(app, /safeToMerge: false, safeForPublicLaunch: false/);
const sandbox = { window: { crypto: { randomUUID: () => 'id' } }, fetch: async () => ({ json: async () => ({ ok: true, status: 'success', providerBoundary: 'gridly', cached: false, requestId: 'id', results: [] }) }) };
vm.runInNewContext(client, sandbox);
assert.equal(sandbox.window.gridlyGeocodingClient.endpoint.includes('gridly-geocode'), true);
assert.equal(sandbox.window.gridlyGeocodingClient.failureMessages.provider_timeout, 'Search is taking longer than expected. Please try again.');
console.log('LP100 geocoding boundary contracts passed.');
