import test from 'node:test'; import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises'; import { join } from 'node:path'; import { tmpdir } from 'node:os';
import { selectGovernedCounties } from '../tools/lp107/generate-runtime-certificates.mjs'; import { atomicJson, objectPaths, readiness, redact } from '../tools/lp108/lp108-core.mjs'; import { parseArguments, run as storageRun } from '../tools/lp108/sync-certified-address-storage.mjs';
import { CERTIFIED_COUNTIES } from '../supabase/functions/_shared/certified-address-identities.mjs'; import { libertyRequest } from '../supabase/functions/_shared/liberty-certified-address.mjs';
const manifest=JSON.parse(await readFile(new URL('../data/lp104/texas-counties.json',import.meta.url),'utf8'));const counties=selectGovernedCounties(manifest);const paths=counties.flatMap(c=>Object.values(objectPaths(c)));
const request=(county,extra={})=>({intent:'address',query:'100 Main Street',structuredAddress:{street:'100 Main Street',county:`${county.name} County`,state:'TX'},context:{countyId:`${county.slug}-tx`,countyFips:county.fips},...extra});
test('exact governed cohort has 28 identities',()=>assert.equal(counties.length,28));
test('governed cohort names and FIPS equal runtime identities',()=>assert.deepEqual(CERTIFIED_COUNTIES.map(x=>`${x.slug}-${x.fips}`),counties.map(x=>`${x.slug}-${x.fips}`)));
test('Storage contract has 56 unique private object paths',()=>{assert.equal(paths.length,56);assert.equal(new Set(paths).size,56);assert.ok(paths.every(x=>x.startsWith('lp104/txgio-addresses/')))});
test('missing local package fails closed',async()=>{const d=await mkdtemp(join(tmpdir(),'lp108-'));try{await assert.rejects(storageRun({plan:true,countyFips:'48015',packageDirectory:d}),/package missing/)}finally{await rm(d,{recursive:true,force:true})}});
test('missing local certificate fails closed',async()=>{const d=await mkdtemp(join(tmpdir(),'lp108-'));try{await writeFile(join(d,'austin-48015.addresses.jsonl.gz'),'fixture');await assert.rejects(storageRun({plan:true,countyFips:'48015',packageDirectory:d}),/certificate missing/)}finally{await rm(d,{recursive:true,force:true})}});
test('local mutation detector is part of the digest contract',async()=>assert.match(await readFile(new URL('../tools/lp108/lp108-core.mjs',import.meta.url),'utf8'),/changed during processing/));
test('certificate mismatch is validated before remote access',async()=>assert.match(await readFile(new URL('../tools/lp108/sync-certified-address-storage.mjs',import.meta.url),'utf8'),/validateRuntimeCertificate/));
test('Storage target ambiguity fails closed',async()=>assert.match(await readFile(new URL('../tools/lp108/sync-certified-address-storage.mjs',import.meta.url),'utf8'),/target ambiguous or inaccessible/));
test('missing credentials have truthful blocked language',async()=>assert.match(await readFile(new URL('../tools/lp108/sync-certified-address-storage.mjs',import.meta.url),'utf8'),/REMOTE EXECUTION NOT COMPLETED/));
test('plan mode excludes remote modes',()=>assert.throws(()=>parseArguments(['--plan','--upload']),/cannot perform remote/));
test('upload defaults to no replacement',()=>assert.equal(parseArguments(['--upload']).replaceMismatched,undefined));
test('replacement requires an explicit upload guard',()=>assert.throws(()=>parseArguments(['--replace-mismatched']),/requires --upload/));
test('private URL and credentials are redacted',()=>{assert.doesNotMatch(redact('authorization: eyJsecret /workspace/private/file'),/eyJsecret|workspace/)});
test('reports are atomic and leave no temporary file',async()=>{const d=await mkdtemp(join(tmpdir(),'lp108-'));try{await atomicJson(join(d,'r.json'),{ok:true});assert.deepEqual(await readdir(d),['r.json'])}finally{await rm(d,{recursive:true,force:true})}});
test('every governed request selects exactly its own county',()=>{for(const c of counties)assert.equal(libertyRequest(request(c)).identity.fips,c.fips)});
test('county and FIPS conflict fails closed',()=>assert.equal(libertyRequest(request(counties[0],{context:{countyId:'austin-tx',countyFips:'48291'}})),null));
test('unsupported county does not activate a package',()=>assert.equal(libertyRequest({intent:'address',query:'100 Main Street',structuredAddress:{street:'100 Main Street',county:'Travis County'},context:{countyFips:'48453',countyId:'travis-tx'}}),null));
test('exact house number is required',()=>assert.equal(libertyRequest({...request(counties[0]),structuredAddress:{county:'Austin County',street:'Main Street'}}),null));
test('acceptance certificates retain exact canonical rules',()=>assert.ok(CERTIFIED_COUNTIES.every(x=>x.artifact.endsWith('.addresses.jsonl.gz'))));
test('nearby substitution remains absent from runtime',async()=>assert.doesNotMatch(await readFile(new URL('../supabase/functions/_shared/liberty-certified-address.mjs',import.meta.url),'utf8'),/nearest(?:Match|Address)|nearby_house_substitution/));
test('road-only residential promotion remains absent',()=>assert.equal(libertyRequest({...request(counties[0]),structuredAddress:{county:'Austin County',street:'Main Street'}}),null));
test('business search remains outside certified provider',()=>assert.equal(libertyRequest({...request(counties[0]),intent:'business_place'}),null));
test('representative selection is defined by deterministic hashing',async()=>assert.match(await readFile(new URL('../tools/lp108/certify-remote-runtime.mjs',import.meta.url),'utf8'),/hash<selectedHash/));
test('tracked certification reports contain hashes rather than query text',async()=>assert.doesNotMatch(await readFile(new URL('../tools/lp108/certify-remote-runtime.mjs',import.meta.url),'utf8'),/counties:\s*\[["']/));
test('readiness cannot pass incomplete remote evidence',()=>assert.equal(readiness({localPackagesValid:28,localCertificatesValid:28,remoteObjectsMatching:55,edgeFunctionDeploymentRequired:true,edgeFunctionDeployed:false,countiesRuntimeCertified:28,exactCasesPassed:28,negativeControlsPassed:4,businessControlPassed:true}),false));
test('all 28 remote cases are represented by governed identities',()=>assert.equal(CERTIFIED_COUNTIES.length,28));
