import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,writeFile} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';import {gzipSync} from 'node:zlib';import {buildSidecar,digest,verifySidecar,exactKey,bucketForKey,eligible} from '../tools/lp108/harris-sidecar-core.mjs';
import {authenticationMode, boundedResponseText, syncItems, uploadFailureDetails} from '../tools/lp108/sync-harris-sidecar.mjs';
const rows=[{i:'first',h:'100',r:'COUNTY ROAD 7',a:'100 COUNTY ROAD 7',p:'HOUSTON',z:'77001',c:'Harris',f:'48201',x:-95.3,y:29.7},{i:'second',h:'100',r:'COUNTY ROAD 7',a:'100 COUNTY ROAD 7',p:'HOUSTON',z:'77001',c:'Harris',f:'48201',x:-95.31,y:29.71},{i:'wrong',h:'101',r:'ROAD',f:'48291',x:-94,y:30}];
async function fixture(){const d=await mkdtemp(join(tmpdir(),'lp10811-')),source=join(d,'source.gz');await writeFile(source,gzipSync(rows.map(x=>JSON.stringify(x)).join('\n')+'\n',{mtime:0}));const identity=await digest(source);return{d,source,sourceCertificate:identity,out:join(d,'sidecar.bin'),cert:join(d,'cert.json')}}
test('source size and sha mismatch fail closed',async()=>{const f=await fixture();await assert.rejects(buildSidecar({sourcePath:f.source,sourceCertificate:{...f.sourceCertificate,sizeBytes:1},outputPath:f.out,certificatePath:f.cert}),/size_mismatch/);await assert.rejects(buildSidecar({sourcePath:f.source,sourceCertificate:{...f.sourceCertificate,sha256:'0'.repeat(64)},outputPath:f.out,certificatePath:f.cert}),/sha256_mismatch/)});
test('output and certificate are deterministic and source-bound',async()=>{const a=await fixture();await buildSidecar({sourcePath:a.source,sourceCertificate:a.sourceCertificate,outputPath:a.out,certificatePath:a.cert});const bytes=await readFile(a.out),cert=await readFile(a.cert);const b=await fixture();await buildSidecar({sourcePath:b.source,sourceCertificate:b.sourceCertificate,outputPath:b.out,certificatePath:b.cert});assert.deepEqual(await readFile(b.out),bytes);assert.deepEqual(await readFile(b.cert),cert);const c=JSON.parse(cert);assert.equal(c.sourcePackageSha256,a.sourceCertificate.sha256);assert.equal(c.recordCount,2);await verifySidecar(a.out,c,a.sourceCertificate)});
test('eligibility, normalized exact key, bucket and package order evidence are governed',()=>{assert.equal(eligible(rows[0]),true);assert.equal(eligible(rows[2]),false);assert.equal(exactKey(rows[0]),'100|cr 7|houston|77001|48201');assert.ok(bucketForKey(exactKey(rows[0]))>=0)});

const failureDetails=(body,init={},extra={})=>uploadFailureDetails({response:new Response(body,{status:400,...init}),objectPath:'lp108/harris-48201.certified-lookup.bin',localByteSize:65091011,key:'sb_secret_fixture',uploadUrl:'https://project.supabase.co/storage/v1/object/certified-addresses/lp108/harris.bin?token=never-print',contentType:'application/octet-stream',remoteExists:false,replace:false,...extra});
test('JSON HTTP 400 exposes bounded safe Supabase fields',async()=>{const details=await failureDetails(JSON.stringify({code:'EntityTooLarge',message:'maximum file size exceeded',statusCode:'413'}),{statusText:'Bad Request',headers:{'content-type':'application/json; charset=utf-8'}});assert.equal(details.supabaseErrorCode,'EntityTooLarge');assert.equal(details.supabaseErrorMessage,'maximum file size exceeded');assert.equal(details.statusCode,'413');assert.equal(details.httpStatusText,'Bad Request');assert.equal(details.responseContentType,'application/json; charset=utf-8');assert.equal(details.localByteSize,65091011);assert.equal(details.uploadEndpointPath,'/storage/v1/object/certified-addresses/lp108/harris.bin');assert.doesNotMatch(JSON.stringify(details),/token=|never-print/)});
test('plain-text HTTP 400 response body is bounded',async()=>{const text=`failure ${'x'.repeat(5000)}`,bounded=await boundedResponseText(new Response(text,{status:400,headers:{'content-type':'text/plain'}}));assert.equal(bounded.length,2000);const details=await failureDetails(text,{headers:{'content-type':'text/plain'}});assert.equal(details.responseBody.length,2000);assert.equal(details.supabaseErrorMessage,null)});
test('service-role credentials are redacted from response details',async()=>{const modern='sb_secret_do-not-print',legacy='eyJhbGciOiJIUzI1NiJ9.payload.signature';for(const key of [modern,legacy]){const details=await failureDetails(JSON.stringify({code:'bad_key',message:`apikey: ${key} Authorization: Bearer ${legacy}`}),{headers:{'content-type':'application/json'}},{key});const output=JSON.stringify(details);assert.doesNotMatch(output,/do-not-print|eyJhbGci|Bearer/);assert.match(output,/apikey: \[REDACTED\]/)}});
test('modern and legacy authentication modes are labels without values',async()=>{assert.equal(authenticationMode('sb_secret_value'),'modern_sb_secret_apikey_only');assert.equal(authenticationMode('eyJlegacy.value'),'legacy_jwt_apikey_and_authorization');for(const key of ['sb_secret_value','eyJlegacy.value']){const output=JSON.stringify(await failureDetails('{}',{headers:{'content-type':'application/json'}},{key}));assert.match(output,new RegExp(authenticationMode(key)));assert.doesNotMatch(output,new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))}});
test('existing-object evidence and replacement mode are reported safely',async()=>{const details=await failureDetails('conflict',{headers:{'content-type':'text/plain'}},{remoteExists:true,replace:true,key:'eyJlegacy.secret'});assert.equal(details.objectAlreadyExistsRemotely,true);assert.equal(details.upsertReplaceMode,'replace (PUT, x-upsert=true)');assert.equal(details.authenticationMode,'legacy_jwt_apikey_and_authorization');assert.doesNotMatch(JSON.stringify(details),/eyJlegacy/)});
test('upload and remote verification behavior remains unchanged',async()=>{const d=await mkdtemp(join(tmpdir(),'lp10811-sync-')),file=join(d,'sidecar.bin'),bytes=Buffer.from('certified bytes');await writeFile(file,bytes);const item={path:'lp108/test.bin',file,type:'application/octet-stream'},calls=[];await syncItems({command:'upload',base:'https://project.supabase.co',key:'sb_secret_fixture',items:[item],fetchImpl:async(url,init={})=>{calls.push({url,method:init.method||'GET',headers:init.headers,body:init.body});return calls.length===1?new Response('missing',{status:404}):calls.length===2?new Response('',{status:200}):new Response(bytes)},log:()=>{}});assert.deepEqual(calls.map(x=>x.method),['GET','POST','GET']);assert.equal(calls[1].headers['x-upsert'],'false');assert.equal(calls[1].headers['content-type'],'application/octet-stream');assert.deepEqual(Buffer.from(calls[1].body),bytes)});
