import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test, { after } from 'node:test';
import { FAMILIES, P, buildArtifacts, json, verify, writeAll } from '../tools/lp1601-manufacture-overture-texas-destinations.mjs';
function fixture(){const dir=mkdtempSync(join(tmpdir(),'lp1601-')); const p=join(dir,'overture.json'); writeFileSync(p,json({sourceMetadata:{sourceName:'Overture Maps Places',sourceId:'overture-places',release:'2026-07-22.0',sourceFormat:'JSON',retrievalDate:'2026-08-05',license:'CDLA Permissive 2.0',attribution:'Overture Maps Foundation',geographicScope:'Owner supplied test extract'},records:[{id:'tx-1',name:'Liberty Grocery',latitude:30.05799,longitude:-94.79548,countyFips:'48291',categories:['grocery_store'],address:'100 Main St',community:'Liberty',postalCode:'77575',brand:'Local Grocer',confidence:.9},{id:'tx-1-dup',name:'Liberty Grocery',latitude:30.05799,longitude:-94.79548,countyFips:'48291',categories:['grocery_store'],address:'100 Main St',community:'Liberty',brand:'Local Grocer'},{id:'tx-2',name:'Houston Fuel',latitude:29.7604,longitude:-95.3698,countyFips:'48201',categories:['gas_station'],locality:'Houston',brand:'FuelCo'},{id:'tx-3',name:'Future Thing',latitude:30,longitude:-96,countyFips:'48015',categories:['future_category']},{id:'bad-1',name:'Oklahoma Store',latitude:35.4676,longitude:-97.5164,countyFips:'40109',categories:['restaurant']},{id:'bad-2',name:'Bad Coords',latitude:99,longitude:-95,countyFips:'48291',categories:['restaurant']},{id:'tx-4',name:'County Hospital',latitude:30.1,longitude:-94.8,countyFips:'48291',categories:['hospital']}]})); return p;}
function sha(s){return createHash('sha256').update(s).digest('hex')}
after(()=>{ writeAll({sourcePath:join(tmpdir(),'missing-overture-after.jsonl')}); });

test('LP160.1 returns SOURCE_UNAVAILABLE without using LP160 fixture or zero coverage claims',()=>{const a=buildArtifacts({sourcePath:join(tmpdir(),'missing-overture.jsonl')}); assert.equal(a[P.final].classification,'SOURCE_UNAVAILABLE'); assert.equal(a[P.summary].texasRecords,null); assert.equal(a[P.owner].powershell.build.includes('npm run build:lp1601'),true);});

test('LP160.1 records explicit Overture source identity and hashes',()=>{const a=buildArtifacts({sourcePath:fixture()}); assert.equal(a[P.manifest].sourceIdentity.sourceName,'Overture Maps Places'); assert.equal(a[P.manifest].sourceIdentity.release,'2026-07-22.0'); assert.equal(a[P.manifest].license,'CDLA Permissive 2.0'); assert.match(a[P.manifest].sha256,/^[0-9a-f]{64}$/); assert.ok(a[P.manifest].fileSizeBytes>0);});

test('LP160.1 extracts Texas, assigns counties, normalizes schema, and maps categories',()=>{const a=buildArtifacts({sourcePath:fixture()}); assert.equal(a[P.summary].sourceRecords,7); assert.equal(a[P.summary].texasRecords,5); assert.equal(a[P.summary].normalizedRecords,4); assert.equal(a[P.summary].duplicateRecords,1); assert.equal(a[P.summary].retainedDestinations,3); assert.equal(a[P.summary].excludedRecords,4); assert.deepEqual(a[P.mapping].requiredFamilies,FAMILIES); assert.equal(a[P.summary].categoryTotals.Retail,1); assert.equal(a[P.summary].categoryTotals.Fuel,1); assert.equal(a[P.summary].categoryTotals.Medical,1); for(const d of a[P.registry].destinations){assert.match(d.deterministicId,/^lp1601-txdest-[0-9a-f]{20}$/); assert.match(d.countyFips,/^48\d{3}$/); assert.equal(d.state,'TX'); assert.ok(Object.hasOwn(d,'displayName')); assert.ok(Object.hasOwn(d,'normalizedName')); assert.ok(Object.hasOwn(d,'sourceAttribution'));}});

test('LP160.1 integrates communities, reports unresolved, rejects every exclusion with reason',()=>{const a=buildArtifacts({sourcePath:fixture()}); assert.ok(a[P.community].relationships.some(r=>r.method==='SOURCE_PROVIDED')); assert.ok(a[P.community].relationships.some(r=>r.method==='GOVERNED_NEAREST_CONTEXT'||r.method==='UNRESOLVED')); assert.ok(a[P.exclusions].excludedRecords.every(e=>e.reasons.length>0)); assert.ok(a[P.rejected].rejectedRecords.some(r=>r.reasons.includes('Outside Texas')));});

test('LP160.1 handles duplicates deterministically and preserves Liberty candidate behavior',()=>{const a=buildArtifacts({sourcePath:fixture()}); assert.equal(a[P.duplicate].duplicateRecords,1); assert.ok(a[P.dupeRegister].decisions.some(d=>d.decision==='DUPLICATE')); assert.ok(a[P.registry].destinations.some(d=>d.countyFips==='48291'&&d.displayName==='Liberty Grocery'));});

test('LP160.1 output is stable and verification is read-only against generated artifacts',()=>{const src=fixture(); const a=buildArtifacts({sourcePath:src}); const b=buildArtifacts({sourcePath:src}); assert.equal(sha(json(a)),sha(json(b))); for(const [p,o] of Object.entries(a)){const full=p; const dir=full.split('/').slice(0,-1).join('/'); mkdirSync(dir,{recursive:true}); writeFileSync(full,json(o));} const before=Object.fromEntries(Object.values(P).map(p=>[p,sha(readFileSync(p))])); assert.equal(verify({sourcePath:src}).classification,'MANUFACTURING_COMPLETE'); const after=Object.fromEntries(Object.values(P).map(p=>[p,sha(readFileSync(p))])); assert.deepEqual(after,before);});
