import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { chmodSync, mkdtempSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import test from 'node:test';
import { P, P1601E, ADDRESS_ARRAY_FIELD_TYPE, OVERTURE_2026_07_22_SCHEMA_ADAPTER, SELECTED_ADDRESS_SQL_EXPRESSION, assertNoDirectAddressArrayAccess, buildArtifacts, buildOverture20260722ExtractionSql } from '../tools/lp1601-manufacture-overture-texas-destinations.mjs';

function controlledGeoParquet(){const dir=mkdtempSync(join(tmpdir(),'lp1601e-src-')); const p=join(dir,'CONTROLLED_TEST_FIXTURE.geoparquet'); writeFileSync(p,Buffer.from('PAR1CONTROLLED_TEST_FIXTURE_LP1601E')); return p;}
function fixtureSha(){return createHash('sha256').update(Buffer.from('PAR1CONTROLLED_TEST_FIXTURE_LP1601E')).digest('hex').toUpperCase();}
function fakeDuck(){const dir=mkdtempSync(join(tmpdir(),'lp1601e-duck-')); const p=join(dir,'duckdb'); writeFileSync(p,`#!/usr/bin/env node
const fs=require('fs'); const args=process.argv.slice(2);
if(args.includes('--version')){console.log('v1.5.5');process.exit(0)}
const sql=args[args.indexOf('-c')+1]||'';
if(/addresses\\.(freeform|locality|postcode|region|country)/.test(sql)){console.error('Cannot extract field freeform from expression "addresses" because it is not a struct, union, map, or json');process.exit(9)}
if(sql.includes('DESCRIBE')){console.log('addresses STRUCT(freeform VARCHAR, locality VARCHAR, postcode VARCHAR, region VARCHAR, country VARCHAR)[]');process.exit(0)}
const m=sql.match(/TO '([^']+)'/); if(m){fs.writeFileSync(m[1], [
 JSON.stringify({id:'one-us-tx',name:'One US TX',name_source:'PRIMARY',primary_name:'One US TX',common_name_en:null,common_names:{},primary_category:'supermarket',alternate_categories:[],brand_wikidata:null,brand_primary:null,brand_common_en:null,brand_name:null,brand_name_source:'UNRESOLVED',brand_common_names:null,formatted_address:'1 Main',locality:'Liberty',postcode:'77575',region:'TX',country:'US',address_quality:'FULL',source_address_count:1,selected_address_method:'FIRST_US_MEANINGFUL',selected_address_country:'US',selected_address_region:'TX',multiple_addresses_present:false,us_address_present:true,tx_address_present:true,confidence:.9,longitude:-94.79548,latitude:30.05799,geometry_valid:true,lifecycle_status:'UNKNOWN',countyFips:'48291'}),
 JSON.stringify({id:'us-and-mx',name:'US And MX',name_source:'PRIMARY',primary_name:'US And MX',common_name_en:null,common_names:{},primary_category:'restaurant',alternate_categories:[],brand_wikidata:null,brand_primary:null,brand_common_en:null,brand_name:null,brand_name_source:'UNRESOLVED',brand_common_names:null,formatted_address:'2 Main',locality:'Liberty',postcode:'77575',region:'TX',country:'US',address_quality:'FULL',source_address_count:2,selected_address_method:'FIRST_US_MEANINGFUL',selected_address_country:'US',selected_address_region:'TX',multiple_addresses_present:true,us_address_present:true,tx_address_present:true,confidence:.9,longitude:-94.79,latitude:30.05,geometry_valid:true,lifecycle_status:'UNKNOWN',countyFips:'48291'}),
 JSON.stringify({id:'conflicting-mx',name:'Conflicting MX',name_source:'PRIMARY',primary_name:'Conflicting MX',common_name_en:null,common_names:{},primary_category:'gas_station',alternate_categories:[],brand_wikidata:null,brand_primary:null,brand_common_en:null,brand_name:null,brand_name_source:'UNRESOLVED',brand_common_names:null,formatted_address:'Durango',locality:'Gomez',postcode:null,region:'DUR',country:'MX',address_quality:'FULL',source_address_count:1,selected_address_method:'FIRST_FREEFORM',selected_address_country:'MX',selected_address_region:'DUR',multiple_addresses_present:false,us_address_present:false,tx_address_present:false,confidence:.9,longitude:-94.8,latitude:30.06,geometry_valid:true,lifecycle_status:'UNKNOWN',countyFips:'48291'}),
 JSON.stringify({id:'outside-tx-text',name:'Outside Text TX',name_source:'PRIMARY',primary_name:'Outside Text TX',common_name_en:null,common_names:{},primary_category:'school',alternate_categories:[],brand_wikidata:null,brand_primary:null,brand_common_en:null,brand_name:null,brand_name_source:'UNRESOLVED',brand_common_names:null,formatted_address:'Austin TX',locality:'Austin',postcode:null,region:'TX',country:'US',address_quality:'LOCALITY_ONLY',source_address_count:1,selected_address_method:'FIRST_US_MEANINGFUL',selected_address_country:'US',selected_address_region:'TX',multiple_addresses_present:false,us_address_present:true,tx_address_present:true,confidence:.9,longitude:-90,latitude:40,geometry_valid:true,lifecycle_status:'UNKNOWN',countyFips:'48291'})
].join('\\n')+'\\n');}
process.exit(0);
`); chmodSync(p,0o755); return p;}
const opts={release:'2026-07-22.0',retrievalDate:'2026-08-05',license:'CDLA Permissive 2.0',attribution:'Overture Maps Foundation'};

test('LP160.1E SQL selects an address element before field access',()=>{const sql=buildOverture20260722ExtractionSql("'source.geoparquet'","'out.jsonl'"); assertNoDirectAddressArrayAccess(sql); assert.match(sql,/list_filter\(addresses/); assert.match(sql,/selected_address\.freeform/); assert.equal(OVERTURE_2026_07_22_SCHEMA_ADAPTER.verifiedSchema.addresses, ADDRESS_ARRAY_FIELD_TYPE); assert.match(SELECTED_ADDRESS_SQL_EXPRESSION,/UPPER\(NULLIF\(TRIM\(a\.country\)/); assert.throws(()=>assertNoDirectAddressArrayAccess('SELECT addresses.freeform FROM source'),/DIRECT_ADDRESS_ARRAY_ACCESS/);});

test('LP160.1E reports deterministic address quality and geometry authority',()=>{const src=controlledGeoParquet(); const a=buildArtifacts({...opts,sourcePath:src,expectedSha256:fixtureSha(),duckdbPath:fakeDuck(),stagingDirectory:mkdtempSync(join(tmpdir(),'lp1601e-stage-'))}); assert.equal(a[P1601E.final].finalClassification,'ADDRESS_SCHEMA_MAPPING_COMPLETE'); assert.equal(a[P1601E.compat].directAddressArrayAccessAbsent,true); assert.equal(a[P.summary].retainedDestinations,3); assert.equal(a[P1601E.quality].recordsWithMultipleAddresses,1); assert.equal(a[P1601E.conflict].records.find(r=>r.sourceRecordId==='conflicting-mx').status,'ADDRESS_COUNTRY_CONFLICT'); assert.ok(!a[P.registry].destinations.some(d=>d.sourceId==='outside-tx-text'), 'non-Texas geometry is excluded even with TX text'); assert.equal(a[P.registry].destinations.find(d=>d.sourceId==='one-us-tx').sourceLocality,'Liberty');});
