import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {buildEvidence,cohortIdentity,stage,verify} from '../tools/lp18811/provision-protected-environment.mjs';

const root=fs.realpathSync(new URL('../',import.meta.url));
const evidence=buildEvidence(root);
test('non-production wave, exact scope, real validator paths and closed authorities',()=>{assert.equal(evidence.environmentClassification,'OWNER_CONTROLLED_PROTECTED_NON_PRODUCTION');assert.equal(evidence.waveId,'LP18810-NP-001');assert.equal(evidence.targetCountyCount,215);for(const p of [evidence.validatorScript,evidence.executionAdapter])assert.ok(fs.existsSync(path.join(root,p)));assert.doesNotMatch(JSON.stringify(evidence),/fake validator|placeholder executable/i);assert.equal(evidence.productionDeploymentAuthorized,false);assert.equal(evidence.activationAuthorized,false);assert.equal(evidence.supabaseProductionMutationAvailable,false);});
test('HTTPS, identities, document and package byte contract are exact',()=>{assert.match(evidence.selectedEnvironment.rootUrl,/^https:\/\//);assert.equal(evidence.deploymentIdentityConfigured,false);assert.match(evidence.selectedEnvironment.buildIdentity,/^sha256:[a-f0-9]{64}$/);assert.equal(evidence.buildIdentityDocumentRequired,true);assert.equal(evidence.packageExposureContract.copyMode,'BYTE_FOR_BYTE_NO_TRANSFORMATION');assert.match(evidence.packageExposureContract.sha256Authority,/lp1885/);assert.equal(evidence.packageExposureContract.targetCount,215);});
test('access inputs and executor reference are required without portable secrets',()=>{for(const n of ['GRIDLY_VALIDATOR_ACCESS_CLIENT_ID','GRIDLY_VALIDATOR_ACCESS_CLIENT_SECRET','GRIDLY_EXECUTOR_IDENTITY_REFERENCE'])assert.ok(evidence.requiredEnvironmentVariables.includes(n));const text=JSON.stringify(evidence);assert.doesNotMatch(text,/CF-Access-Client-Secret|clientSecret|secretValue|cookie|bearer/i);assert.equal(evidence.serviceTokenRequired,true);assert.equal(evidence.executorIdentityReferenceRequired,true);});
test('baseline and fail-closed readiness remain unchanged',()=>{assert.equal(evidence.currentOperationalCount,28);assert.equal(evidence.restrictedCountyCount,11);assert.equal(evidence.newActivatedCount,0);assert.equal(evidence.runtimeOperationalCountChanged,false);assert.equal(evidence.restrictedCountyStateChanged,false);assert.equal(evidence.provisioningStatus,'PROTECTED_ENVIRONMENT_OWNER_PROVISIONING_ACTION_REQUIRED');assert.ok(evidence.blockingReasons.length);assert.equal(evidence.validatorExecuted,false);assert.equal(evidence.independentReviewStatus,'SEPARATE_PENDING');});
test('staging rejects missing owner bytes and ambiguous deployment identities',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'lp18811c-'));try{assert.throws(()=>stage({source:tmp,output:path.join(tmp,'out'),deploymentId:'latest',root}),/ambiguous/);assert.throws(()=>stage({source:tmp,output:path.join(tmp,'out'),deploymentId:'lp18811c-immutable-001',root}),/ENOENT/);}finally{fs.rmSync(tmp,{recursive:true,force:true});}});
test('portable evidence and cohort build identity are deterministic',()=>{const one=Buffer.from(JSON.stringify(buildEvidence(root))),two=Buffer.from(JSON.stringify(buildEvidence(root)));assert.deepEqual(one,two);assert.deepEqual(cohortIdentity(root),cohortIdentity(root));assert.doesNotThrow(()=>verify(root));assert.equal(crypto.createHash('sha256').update(one).digest('hex'),crypto.createHash('sha256').update(two).digest('hex'));});
