import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import test from 'node:test';
import { DIMENSION_CLASSIFICATION, ENVIRONMENT, governedInputs, parseArguments, validateScope, execute } from '../tools/lp18811/protected-validation-harness.mjs';
import { ingest } from '../tools/lp18811/ingest-validation-evidence.mjs';

const root=new URL('../',import.meta.url), repo=fs.realpathSync(root);
const governed=governedInputs(repo);
const output='evidence/lp18811/execution-results/lp18811b-test.local.json';
const base=['--wave','LP18810-NP-001','--county-fips',governed.fips.join(','),'--environment',ENVIRONMENT,'--repository-root',repo,'--evidence-output',output,'--protected-url','https://protected.invalid','--deployment-id','safe-deployment-id','--expected-build-identity','sha256:'+'a'.repeat(64),'--executor-identity-reference','evidence/executor/safe-reference.json','--no-production-deployment','--no-activation','--no-public-launch','--no-supabase-production-mutation','--no-restriction-clearing','--no-runtime-operational-membership-mutation'];
const env={GRIDLY_VALIDATOR_ACCESS_CLIENT_ID:'test-id',GRIDLY_VALIDATOR_ACCESS_CLIENT_SECRET:'test-secret'};
const fetchImpl=async url=>{const pathname=new URL(url).pathname;if(pathname==='/gridly-protected-build-identity.json')return Response.json({deploymentId:'safe-deployment-id',buildIdentity:'sha256:'+'a'.repeat(64),environmentClassification:ENVIRONMENT});return new Response(Buffer.from(pathname==='/'?'<html>protected</html>':'protected-package-bytes'),{status:200});};
const packageDigest=(_bytes,pkg)=>pkg.sha256;
const deps={fetchImpl,env,packageDigest};
const matrix=JSON.parse(fs.readFileSync(new URL('../reports/lp18810/county-membership-validation-matrix.json',import.meta.url)));
const identities=JSON.parse(fs.readFileSync(new URL('../reports/lp1885/community-package-identity-inventory.json',import.meta.url)));

test('semantic discovery finds candidates and documents why no reusable validator is duplicated',()=>{const doc=fs.readFileSync(new URL('../LP188.11B-PROTECTED-VALIDATION-HARNESS.md',import.meta.url),'utf8');for(const p of ['tools/Runtime/Invoke-GridlyRuntimeValidation.ps1','tools/Validation/Invoke-GridlySmokeTest.ps1','tools/lp1837/invoke-protected-preview.ps1','tools/lp151/validate-statewide-operations.mjs'])assert.match(doc,new RegExp(p.replaceAll('/','\\/')));assert.match(doc,/No existing executable performs/);assert.equal(fs.readdirSync(new URL('../tools/lp18811/',import.meta.url)).filter(x=>x.includes('protected-validation-harness')).length,1);});
test('wave, exact 215 scope, unknown FIPS, environment, and negative authorities fail closed',()=>{assert.equal(governed.fips.length,215);assert.equal(parseArguments(base).values.wave,'LP18810-NP-001');assert.throws(()=>validateScope(governed.fips.slice(0,-1).concat('48999').join(','),governed.fips),/exact 215/);assert.throws(()=>parseArguments(base.map(x=>x===ENVIRONMENT?'PRODUCTION':x)),/protected non-production/);for(const flag of ['--no-production-deployment','--no-activation','--no-supabase-production-mutation'])assert.throws(()=>parseArguments(base.filter(x=>x!==flag)),/missing --/);});
test('package SHA-256 is mandatory and package inputs are not rewritten',async()=>{assert.ok(governed.packages.every(x=>/^[a-f0-9]{64}$/.test(x.sha256)));const inventory=new URL('../reports/lp1885/community-package-identity-inventory.json',import.meta.url),before=crypto.createHash('sha256').update(fs.readFileSync(inventory)).digest('hex');try{await execute(base,deps);}finally{fs.rmSync(new URL(`../${output}`,import.meta.url),{force:true});}assert.equal(crypto.createHash('sha256').update(fs.readFileSync(inventory)).digest('hex'),before);});
test('credentials fail closed and secrets never enter portable LP188.11 evidence',async()=>{await assert.rejects(execute(base,{fetchImpl,packageDigest,env:{}}),/CLIENT_ID/);let made;try{made=await execute(base,deps);assert.doesNotMatch(JSON.stringify(made),/test-id|test-secret|protected\.invalid/);assert.equal(made.independentReview,undefined);assert.ok(made.results.every(x=>x.independentReview.status==='PENDING'));assert.doesNotThrow(()=>ingest({matrix,identities,evidenceDocuments:[made]}));}finally{fs.rmSync(new URL(`../${output}`,import.meta.url),{force:true});}});
test('automated/manual classifications are explicit and baselines cannot activate',async()=>{assert.deepEqual(DIMENSION_CLASSIFICATION,{deployment:'AUTOMATABLE',runtime:'AUTOMATABLE',regression:'EXTERNAL_ENVIRONMENT_REQUIRED',consumer:'OWNER_OBSERVATION_REQUIRED',boundary:'AUTOMATABLE',telemetry:'OWNER_OBSERVATION_REQUIRED',rollback:'OWNER_OBSERVATION_REQUIRED',operational:'OWNER_OBSERVATION_REQUIRED',executorEvidence:'OWNER_OBSERVATION_REQUIRED',independentReview:'INDEPENDENT_REVIEW_REQUIRED'});let evidence;try{evidence=await execute(base,deps);const made=ingest({matrix,identities,evidenceDocuments:[evidence]});assert.equal(made.summary.currentOperationalCount,28);assert.equal(made.summary.restrictedCountyCount,11);assert.equal(made.summary.newActivatedCount,0);assert.equal(made.summary.structurallyActivationEligibleCount,0);assert.ok(made.matrix.records.every(x=>x.activationStatus==='NOT_ACTIVATED'));}finally{fs.rmSync(new URL(`../${output}`,import.meta.url),{force:true});}});
test('two contract runs are byte-identical',async()=>{try{const a=await execute(base,deps), first=fs.readFileSync(new URL(`../${output}`,import.meta.url));const b=await execute(base,deps), second=fs.readFileSync(new URL(`../${output}`,import.meta.url));assert.deepEqual(a,b);assert.deepEqual(first,second);}finally{fs.rmSync(new URL(`../${output}`,import.meta.url),{force:true});}});
