import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { inspectArtifactResponse } from '../tools/lp18812/verify-certified-artifacts.mjs';
import { validateRemainingEvidence, ingestRemainingEvidence } from '../tools/lp18812/ingest-remaining-owner-evidence.mjs';
import { contract, migrateLegacyOwnerExecution, LEGACY_OWNER_EXECUTION_PROVENANCE } from '../tools/lp18812/statewide-validation-closure.mjs';

const source=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const fixtures=JSON.parse(source('reports/lp18812/wave0-remaining-fixture-contract.json'));
const artifactFixtures=fixtures.fixtures.filter(x=>x.assertionId==='CERTIFIED_ARTIFACT_STABILITY');
const response=(status=200,{redirected=false,type='application/json'}={})=>({status,redirected,headers:{get:()=>type}});
test('remaining harness fixture identities and exact scopes are governed',()=>{assert.deepEqual(fixtures.fixtureCountByAssertion,{CERTIFIED_ARTIFACT_STABILITY:28,COUNTY_BOUNDARY_ISOLATION:4,CONSUMER_RESULT_STABILITY:28,FALLBACK_BEHAVIOR_STABILITY:1,ROUTE_AWARENESS_STABILITY:1});assert.equal(new Set(fixtures.fixtures.map(x=>x.fixtureId)).size,62);const browser=source('tests/browser/lp18812-remaining-runtime.spec.mjs');assert.doesNotMatch(browser,/gridlyV858LocationInput|fill\(awarenessInput|OPERATIONAL_COUNTY_RESULT_STABILITY/);assert.match(browser,/families=\['COUNTY_BOUNDARY_ISOLATION','CONSUMER_RESULT_STABILITY','FALLBACK_BEHAVIOR_STABILITY','ROUTE_AWARENESS_STABILITY'\]/);});
test('artifact inspection rejects wrong status, bytes, hash, redirect, HTML, and empty bodies',()=>{const bytes=Buffer.from('governed');const fixture={...artifactFixtures[0],expectedResult:{...artifactFixtures[0].expectedResult,httpStatus:200,byteLength:bytes.length,sha256:`sha256:${crypto.createHash('sha256').update(bytes).digest('hex')}`}};assert.equal(inspectArtifactResponse(fixture,response(),bytes).passed,true);assert.equal(inspectArtifactResponse(fixture,response(401),bytes).passed,false);assert.equal(inspectArtifactResponse(fixture,response(),Buffer.from('wrong')).passed,false);assert.equal(inspectArtifactResponse({...fixture,expectedResult:{...fixture.expectedResult,sha256:'sha256:'+'0'.repeat(64)}},response(),bytes).passed,false);assert.equal(inspectArtifactResponse(fixture,response(200,{redirected:true}),bytes).passed,false);assert.equal(inspectArtifactResponse(fixture,response(200,{type:'text/html'}),Buffer.from('<html>Cloudflare Access</html>')).passed,false);assert.equal(inspectArtifactResponse(fixture,response(),Buffer.alloc(0)).passed,false);});
test('harnesses preserve Chromium, finite budgets, origin auth, and fail-closed mutation guard',()=>{const cfg=source('playwright.lp18812-remaining.config.mjs'),browser=source('tests/browser/lp18812-remaining-runtime.spec.mjs'),artifact=source('tools/lp18812/verify-certified-artifacts.mjs');assert.match(cfg,/workers:1,retries:0/);assert.match(cfg,/channel:'chromium'/);assert.match(cfg,/width:390,height:844/);assert.match(cfg,/timeout:300000/);assert.match(artifact,/OVERALL_BUDGET_MS=120000/);assert.match(browser,/url\.origin===protectedOrigin/);assert.match(browser,/classifyBlockedMutation/);assert.match(browser,/route\.abort\('blockedbyclient'\)/);});
test('portable harness and evidence surfaces contain no credentials, headers, or bodies',()=>{for(const file of ['tests/browser/lp18812-remaining-runtime.spec.mjs','tools/lp18812/verify-certified-artifacts.mjs']){const text=source(file);assert.doesNotMatch(text,/responseBody|bodyBase64|requestHeaders/);}const required=['fixtureId','assertionId','protectedPathname','status','observedByteLength','observedSha256','expectedByteLength','expectedSha256','passed'];for(const field of required)assert.match(source('tools/lp18812/verify-certified-artifacts.mjs'),new RegExp(field));});
function goodEvidence(){const contractDigest=`sha256:${crypto.createHash('sha256').update(source('reports/lp18812/wave0-remaining-fixture-contract.json')).digest('hex')}`;const rows=fixtures.fixtures.map(x=>({fixtureId:x.fixtureId,assertionId:x.assertionId,passed:true}));const outcome=id=>({assertionId:id,outcome:'PASS',executed:true,evidenceChecks:rows.filter(x=>x.assertionId===id).map(x=>({fixtureId:x.fixtureId,passed:true,evidenceReference:`observations#${x.fixtureId}`}))});return {artifact:{schemaVersion:'gridly.lp18812.certified-artifact-owner-execution.v1',fixtureContractDigest:contractDigest,failures:0,productionMutationObserved:false,activationObserved:false,observations:rows.filter(x=>x.assertionId==='CERTIFIED_ARTIFACT_STABILITY'),assertionOutcomes:[outcome('CERTIFIED_ARTIFACT_STABILITY')]},runtime:{schemaVersion:'gridly.lp18812.remaining-runtime-owner-execution.v1',fixtureContractDigest:contractDigest,failures:0,openS1:0,openS2:0,productionMutationObserved:false,activationObserved:false,observations:rows.filter(x=>x.assertionId!=='CERTIFIED_ARTIFACT_STABILITY'),assertionOutcomes:['COUNTY_BOUNDARY_ISOLATION','CONSUMER_RESULT_STABILITY','FALLBACK_BEHAVIOR_STABILITY','ROUTE_AWARENESS_STABILITY'].map(outcome)}};}
test('structured outcomes cannot pass with failed or missing checks',()=>{const {artifact,runtime}=goodEvidence();assert.equal(validateRemainingEvidence(artifact,runtime).length,5);const failed=structuredClone(runtime);failed.assertionOutcomes[0].evidenceChecks[0].passed=false;assert.throws(()=>validateRemainingEvidence(artifact,failed),/outcome_not_supported/);const missing=structuredClone(runtime);missing.observations.pop();assert.throws(()=>validateRemainingEvidence(artifact,missing),/fixture_scope_mismatch/);});
test('ingestion is idempotent, rejects altered evidence, preserves migrated operational outcome, and is required for final PASS',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'lp18812-remaining-')),{artifact,runtime}=goodEvidence(),a=path.join(temp,'a.json'),b=path.join(temp,'b.json'),receipt=path.join(temp,'receipt.json'),result=path.join(temp,'result.json'),partialPath=path.join(temp,'partial.json'),migrationPath=path.join(temp,'migration.json'),c=contract();const partial={results:c.exactWave0Fips.map(fips=>({fips,assertions:['CERTIFIED_ARTIFACT_STABILITY','OPERATIONAL_COUNTY_RESULT_STABILITY','CONSUMER_RESULT_STABILITY']})),failures:0,openS1:0,openS2:0,productionMutationObserved:false,blockedMutatingRequests:c.exactWave0Fips.map(()=>({method:'POST',origin:new URL(c.target.url).origin,pathname:'/cdn-cgi/rum',category:'CLOUDFLARE_MANAGED_RUM_TELEMETRY',blocked:true,productionMutationObserved:false})),activationObserved:false,schemaVersion:'gridly.lp18812.wave0-result.v1',contractDigest:LEGACY_OWNER_EXECUTION_PROVENANCE.legacyContractDigest,wave0Result:'FAIL'};fs.writeFileSync(partialPath,JSON.stringify(partial));fs.writeFileSync(migrationPath,JSON.stringify(migrateLegacyOwnerExecution(partial,c)));fs.writeFileSync(a,JSON.stringify(artifact));fs.writeFileSync(b,JSON.stringify(runtime));const args={artifactPath:a,runtimePath:b,receiptPath:receipt,resultPath:result,partialPath,migrationPath};assert.equal(ingestRemainingEvidence(args).wave0Result,'PASS');assert.equal(ingestRemainingEvidence(args).wave0Result,'PASS');const final=JSON.parse(fs.readFileSync(result));assert.deepEqual(final.completedWave0Assertions,['CERTIFIED_ARTIFACT_STABILITY','OPERATIONAL_COUNTY_RESULT_STABILITY','COUNTY_BOUNDARY_ISOLATION','CONSUMER_RESULT_STABILITY','FALLBACK_BEHAVIOR_STABILITY','ROUTE_AWARENESS_STABILITY']);runtime.executedAt='altered';fs.writeFileSync(b,JSON.stringify(runtime));assert.throws(()=>ingestRemainingEvidence(args),/different_remaining_owner_evidence/);fs.rmSync(temp,{recursive:true,force:true});});
