import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { contract, digest, governedTarget, reconcile, sanitize, validateEnvironment, APPROVED_ASSERTIONS, MUTATING_METHODS } from '../tools/lp18812/statewide-validation-closure.mjs';

const source=(p)=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const c=contract();
test('Playwright is exact dev-only and Chromium-only',()=>{const p=JSON.parse(source('package.json'));assert.equal(p.dependencies['@playwright/test'],undefined);assert.equal(p.devDependencies['@playwright/test'],'1.54.2');const cfg=source('playwright.lp18812.config.mjs');assert.match(cfg,/browserName: 'chromium'/);assert.doesNotMatch(source('index.html'),/playwright/i)});
test('only approved invisible hooks project governed runtime state',()=>{const app=source('js/app.js');assert.match(app,/data-gridly-active-county-fips/);assert.match(app,/data-gridly-package-identity/);assert.match(app,/gridlyGetActiveCountyId\(\)/);assert.match(app,/gridlyPackageRegistry\.getCommunityPackage/);assert.doesNotMatch(app,/CF-Access|Client-Secret/);assert.equal((app.match(/data-gridly-active-county-fips/g)||[]).length,2);assert.equal((app.match(/data-gridly-package-identity/g)||[]).length,2)});
test('hooks introduce no visible or activation behavior',()=>{const html=source('index.html');assert.doesNotMatch(html,/data-gridly-(active-county-fips|package-identity)/);const hook=source('js/app.js').match(/function gridlyPublishValidationIdentity\(\)[\s\S]*?\n}/)[0];assert.doesNotMatch(hook,/textContent|innerHTML|classList|activate|localStorage|fetch/)});
test('fixture identity, exact Wave 0 scope, defect binding and preserved dimensions',()=>{assert.equal(c.exactWave0Fips.length,28);assert.equal(new Set(c.exactWave0Fips).size,28);assert.deepEqual(c.assertions,APPROVED_ASSERTIONS);assert.equal(c.governedFixtures.length,56);assert.match(c.defectInventoryDigest,/^sha256:/);assert.deepEqual(c.completedDimensionsNotToRerun,['deployment','runtime','boundary']);assert.equal(c.state.currentOperationalCount,28);assert.equal(c.state.restrictedCountyCount,11);assert.equal(c.state.newActivatedCount,0)});
test('protected runner enforces read-only requests and credential secrecy',()=>{assert.deepEqual(MUTATING_METHODS,['POST','PUT','PATCH','DELETE']);const browser=source('tests/browser/lp18812-wave0.spec.mjs');assert.match(browser,/route\.abort\('blockedbyclient'\)/);assert.doesNotMatch(browser,/writeFileSync[\s\S]*GRIDLY_VALIDATOR_ACCESS_CLIENT_SECRET/);process.env.GRIDLY_VALIDATOR_ACCESS_CLIENT_SECRET='top-secret';assert.doesNotMatch(JSON.stringify(sanitize({x:'top-secret'})),/top-secret/)});
test('target identity comes from committed LP188.11 owner evidence, not historical infrastructure reuse evidence',()=>{const owner=JSON.parse(source('evidence/lp18811/execution-results/owner-result.json'));const provisioning=JSON.parse(source('reports/lp18811c/protected-environment-provisioning.json'));const target=governedTarget(owner,provisioning);assert.equal(target.deploymentId,owner.deploymentIdentity.deploymentId);assert.equal(target.deploymentId,'lp18811c-c5cc6370-412c-487e-b3d3-3ff8350b6f98');assert.notEqual(target.deploymentId,provisioning.infrastructureAudit.existingDeploymentId);assert.equal(c.target.deploymentId,target.deploymentId)});
test('governed build identity is reconciled and disagreement fails closed',()=>{const owner=JSON.parse(source('evidence/lp18811/execution-results/owner-result.json'));const provisioning=JSON.parse(source('reports/lp18811c/protected-environment-provisioning.json'));assert.equal(governedTarget(owner,provisioning).buildIdentity,owner.deploymentIdentity.expectedBuildIdentity);assert.equal(owner.deploymentIdentity.expectedBuildIdentity,provisioning.selectedEnvironment.buildIdentity);assert.throws(()=>governedTarget(owner,{...provisioning,selectedEnvironment:{...provisioning.selectedEnvironment,buildIdentity:'sha256:wrong'}}),/governed_build_identity_mismatch/)});
test('target accepts only the governed protected release, build, and non-production hostname',()=>{const good={GRIDLY_PROTECTED_URL:c.target.url,GRIDLY_PROTECTED_DEPLOYMENT_ID:'lp18811c-c5cc6370-412c-487e-b3d3-3ff8350b6f98',GRIDLY_PROTECTED_BUILD_IDENTITY:c.target.buildIdentity,GRIDLY_VALIDATOR_ACCESS_CLIENT_ID:'memory-only',GRIDLY_VALIDATOR_ACCESS_CLIENT_SECRET:'memory-only'};assert.equal(validateEnvironment(good,c),true);assert.throws(()=>validateEnvironment({...good,GRIDLY_PROTECTED_DEPLOYMENT_ID:'458fa7f4-ba68-44c7-82ea-c5e6475e456e'},c),/wrong_deployment/);assert.throws(()=>validateEnvironment({...good,GRIDLY_PROTECTED_DEPLOYMENT_ID:'arbitrary-wrong-id'},c),/wrong_deployment/);assert.throws(()=>validateEnvironment({...good,GRIDLY_PROTECTED_BUILD_IDENTITY:'wrong'},c),/wrong_build/);assert.throws(()=>validateEnvironment({...good,GRIDLY_PROTECTED_URL:'https://gridlygo.com'},c),/production_or_wrong_target/)});
test('Wave 0 reconciliation cannot weaken any pass gate',()=>{const base={results:c.exactWave0Fips.map(fips=>({fips,assertions:APPROVED_ASSERTIONS})),failures:0,openS1:0,openS2:0,productionMutationObserved:false,activationObserved:false};assert.equal(reconcile(base,c).wave0Result,'PASS');for(const change of [{failures:1},{openS1:1},{openS2:1},{productionMutationObserved:true},{activationObserved:true},{results:base.results.slice(1)}])assert.equal(reconcile({...base,...change},c).wave0Result,'FAIL')});
test('215 baseline is regression-only and deterministically bound',()=>{assert.equal(c.statewideFips.length,215);assert.equal(new Set(c.statewideFips).size,215);assert.equal(digest(c),digest(contract()));assert.equal(c.authorization.activation,false);assert.equal(c.authorization.mutation,false)});
test('closure governance preserves evidence ordering and reviewer separation',()=>{const doc=source('LP188.12-STATEWIDE-VALIDATION-CLOSURE.md');assert.match(doc,/consumer.*telemetry.*rollback.*operational/is);assert.match(doc,/executor cannot self-review/i);assert.match(doc,/STRUCTURALLY_ACTIVATION_ELIGIBLE/);assert.match(doc,/new activated: \*\*0\*\*/i)});
