import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {ROOT,canonical,digest,generate} from '../tools/lp18811/govern-wave0-journeys.mjs';
const read=p=>JSON.parse(fs.readFileSync(`${ROOT}/${p}`,'utf8'));
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(`${ROOT}/${p}`)).digest('hex');

test('the 56 prior fixtures and authority digests remain byte-for-byte governed',()=>{const f=generate();const c=f['wave0-fixture-authority.json'];const prior=read('reports/lp18811f3/wave0-fixture-contract.json');assert.deepEqual(c.priorFixtures,prior.fixtures);assert.equal(c.priorFixtureCount,56);assert.equal(c.priorFixtureContractDigest,'sha256:756cb4bbb819435506cd9aa5b52176616a8d0693bc8b642c8240971b74c38166');assert.equal(c.wave0ContractDigest,'sha256:a05d8fbb07bcdf1ee4b067d0aacbe6e690a8531f160396472f76757f3beeb257');assert.equal(c.severityTaxonomyDigest,'sha256:f920f96e8a6175f594368e400bef26717662aa4e316503acd4c867fc95654329')});
test('all assertions have explicit scope and exact fail-closed owner blockers',()=>{const c=generate()['wave0-fixture-authority.json'];assert.equal(Object.keys(c.scopeDecisions).length,6);assert.equal(c.ownerFixtureDecisionsRequired.length,6);assert.ok(c.ownerFixtureDecisionsRequired.every(x=>x.decisionRequired.length>80&&x.status==='OWNER_FIXTURE_DECISION_REQUIRED'));assert.equal(c.noInventedInputs,true);assert.equal(c.fixtureAuthorityComplete,false);for(const f of c.exactFipsScope)assert.match(f,/^48\d{3}$/)});
test('journeys bind authority, fixture digest, concrete expectations and prohibitions',()=>{const f=generate(),c=f['wave0-fixture-authority.json'],j=f['browser-journey-contract.json'];assert.equal(j.wave0ContractDigest,c.wave0ContractDigest);assert.equal(j.fixtureContractDigest,digest(c));assert.equal(j.journeys.length,6);for(const x of j.journeys){assert.ok(x.expectedResults.every(v=>v!== 'PASS'&&v.length>20));assert.ok(x.prohibitedResults.every(v=>v.length>20));assert.deepEqual(x.applicableFips,c.exactFipsScope);assert.equal(x.executionStatus,'NOT_EXECUTED_OWNER_FIXTURE_AUTHORITY_BLOCKED')}assert.match(canonical(j),/CF-Access-Client-Secret/);assert.doesNotMatch(canonical(j),/eyJ|clientSecret\s*:/i)});
test('browser decision, dependency boundary, and selector readiness are explicit',()=>{const f=generate(),d=f['browser-harness-decision.json'],a=f['selector-readiness-audit.json'],pkg=read('package.json');assert.equal(d.decisionStatus,'OWNER_DECISION_REQUIRED');assert.equal(d.newDependencyInstalled,false);assert.deepEqual(d.allowedValues,['OWNER_APPROVED_PLAYWRIGHT','OWNER_REJECTED_PLAYWRIGHT','OWNER_SUPPLIED_EQUIVALENT_HARNESS']);for(const n of ['playwright','@playwright/test'])assert.equal(pkg.dependencies?.[n],undefined);assert.equal(pkg.devDependencies?.['@playwright/test'],'1.54.2');assert.equal(a.journeys.length,6);assert.equal(a.missingHooks.length,2);assert.equal(a.uiModified,false)});
test('state, owner result, runtime dependencies, and deterministic output remain unchanged',()=>{const owner='evidence/lp18811/execution-results/owner-result.json',before=sha(owner),deps=canonical(read('package.json').dependencies),a=generate(),b=generate(),s=a['lp18811f4-summary.json'];assert.deepEqual(a,b);for(const[n,v]of Object.entries(a))assert.equal(fs.readFileSync(`${ROOT}/reports/lp18811f4/${n}`,'utf8'),canonical(v));assert.equal(sha(owner),before);assert.equal(canonical(read('package.json').dependencies),deps);assert.deepEqual(s.state,{currentOperationalCount:28,restrictedCountyCount:11,newActivatedCount:0,runtimeOperationalCountChanged:false,restrictedCountyStateChanged:false});for(const k of ['wave0Executed','regression215Executed','redeploymentOccurred','activationOccurred'])assert.equal(s[k],false);assert.equal(s.overallClassification,'WAVE0_JOURNEY_FIXTURE_OWNER_DECISION_REQUIRED')});
