import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {auditGovernedInputs,classifyAggregate,classifyPair,failClosedFarSouthwest,reconcileGovernance,PRECEDENCE} from '../tools/lp191/bexar-place-overlay.mjs';

test('real governed manifests reconcile 33 places and 30/29 atomic units',()=>{const a=reconcileGovernance();assert.equal(a.cohort.length,33);assert.equal(a.records.length,30);assert.equal(a.usable.length,29);assert.equal(a.pairEvaluationCount,957);assert.equal(a.precedence,PRECEDENCE)});
test('pair taxonomy distinguishes disjoint, touch, containment and partial overlap',()=>{assert.equal(classifyPair({intersectionArea:0}),'DISJOINT');assert.equal(classifyPair({intersectionArea:0,boundariesTouch:true}),'BOUNDARY_TOUCH_ONLY');assert.equal(classifyPair({intersectionArea:1,placeWithinAtomic:true}),'PLACE_CONTAINED_WITHIN_ATOMIC_UNIT');assert.equal(classifyPair({intersectionArea:1,atomicWithinPlace:true}),'ATOMIC_UNIT_CONTAINED_WITHIN_PLACE');assert.equal(classifyPair({intersectionArea:1}),'PARTIAL_AREA_OVERLAP')});
test('aggregate taxonomy distinguishes multiple units and the governance hold',()=>{assert.equal(classifyAggregate({positiveAreaCount:2,boundaryTouchCount:0}),'MULTI_ATOMIC_POSITIVE_AREA_OVERLAP');assert.equal(classifyAggregate({positiveAreaCount:0,boundaryTouchCount:1}),'BOUNDARY_TOUCH_ONLY');assert.equal(classifyAggregate({positiveAreaCount:2,boundaryTouchCount:0,farSouthwestPreventsCertification:true}),'INDETERMINATE_FAR_SOUTHWEST_GOVERNANCE_HOLD')});
test('Far Southwest remains fail closed',()=>{const x=failClosedFarSouthwest();assert.equal(x.preventsFullCertification,true);assert.equal(x.classification,'INDETERMINATE_FAR_SOUTHWEST_GOVERNANCE_HOLD')});
test('checked-in West Northwest byte drift fails before missing inputs can be manufactured',()=>{assert.throws(()=>auditGovernedInputs({ownerPlaceGeometry:'/missing/place.zip',ownerSaGeometry:'/missing/sa.geojson'}),/WEST_NORTHWEST_CERTIFIED_ARTIFACT_RECOVERY_OWNER_EXECUTION_REQUIRED/)});
test('protected runtime file is not an LP191 output',()=>{const source=fs.readFileSync(new URL('../tools/lp191/bexar-place-overlay.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/writeFileSync\([^)]*js\/app\.js/)});

test('recovery method is certified while owner replacement remains pending',()=>{const report=JSON.parse(fs.readFileSync(new URL('../reports/lp191/west-northwest-artifact-recovery.json',import.meta.url)));assert.equal(report.recoveryMethod,'RECOVERY_METHOD_CERTIFIED');assert.equal(report.artifactReplacement,'ARTIFACT_REPLACEMENT_OWNER_EXECUTION_PENDING');assert.equal(report.status,'CERTIFIED_ARTIFACT_RECOVERY_METHOD_READY_OWNER_EXECUTION_PENDING')});
