import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { build, outputs } from '../tools/lp199/build-statewide-place-presentation-camera-derivation.mjs';

const report=build();
test('inventory is complete, GEOID ordered, unique, and membership-preserving',()=>{assert.equal(report.inventory.length,1859);const ids=report.inventory.map(x=>x.placeGeoid);assert.deepEqual(ids,[...ids].sort());assert.equal(new Set(ids).size,1859);const projection=JSON.parse(fs.readFileSync('data/generated/gridly-statewide-consumer-community-projection-v1.json'));for(const row of projection.communities)assert.deepEqual(report.inventory.find(x=>x.placeGeoid===row.placeGeoid).countyMemberships,row.countyMemberships);assert.equal(report.inventory.reduce((n,x)=>n+x.countyMemberships.length,0),2058);});
test('four exact LP197 overrides are preserved and lookup is GEOID keyed',()=>{const approved=JSON.parse(fs.readFileSync('reports/lp197/governed-place-consumer-presentation-cameras.json')).cameras;assert.equal(approved.length,4);for(const a of approved){const x=report.inventory.find(r=>r.placeGeoid===a.placeGeoid);assert.deepEqual(x.selectedCamera,{lat:a.lat,lng:a.lng,zoom:13,method:'OWNER_APPROVED_OVERRIDE'});assert.equal(x.confidence,'OWNER_APPROVED_OVERRIDE');}assert.doesNotMatch(fs.readFileSync('tools/lp199/build-statewide-place-presentation-camera-derivation.mjs','utf8'),/byOverride\.get\([^)]*label/);});
test('candidate derivation, calibration, bad controls, and confidence vocabulary are deterministic',()=>{assert.deepEqual(outputs(),outputs());assert.deepEqual(report.calibration.map(x=>x.method),['existingCurrentPoint','geometryCentroid','pointOnSurface','boundingBoxCenter','hybridContainedCentroid']);assert.ok(report.calibration.every(x=>x.controls.length===4&&Number.isFinite(x.aggregate.meanErrorMeters)));assert.deepEqual(report.controlComparison.filter(x=>x.ownerClassification==='KNOWN_BAD_EXISTING_GENERIC').map(x=>x.label),['Corpus Christi','McAllen','Port Arthur','Tyler','Waco']);const allowed=new Set(['OWNER_APPROVED_OVERRIDE','DERIVED_HIGH_CONFIDENCE','DERIVED_REVIEW_RECOMMENDED','FALLBACK_EXISTING_CAMERA','UNRESOLVED']);assert.ok(report.inventory.every(x=>allowed.has(x.confidence)));});
test('no runtime activation, identity, ZIP, county, Houston, or San Antonio mutation is emitted',()=>{assert.equal(report.scope.runtimeActivation,false);assert.equal(report.scope.identityMutation,false);assert.equal(report.scope.zipMutation,false);assert.equal(report.scope.countyMembershipMutation,false);assert.equal(report.selection.genericDerivationCertified,false);assert.equal(report.inventory.find(x=>x.label==='Houston').selectedCamera.method,'EXISTING_CANONICAL_PLACE_CAMERA');assert.equal(report.inventory.find(x=>x.label==='San Antonio').selectedCamera.method,'EXISTING_CANONICAL_PLACE_CAMERA');assert.equal(report.corpusChristiSearchFinding.classification,'LP196_PARITY_DEFECT_REQUIRES_SEPARATE_RUNTIME_BROWSER_REPRODUCTION');});
test('reports use LF and a second generated build is byte-identical',()=>{for(const bytes of Object.values(outputs())){assert.equal(bytes.includes('\r'),false);assert.ok(bytes.endsWith('\n'));}assert.deepEqual(outputs(),outputs());});
