import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { FINAL11, run } from '../scripts/lp1904-final-statewide-runtime-activation-guarded.mjs';

const production=['js/app.js','assets/package-registry/runtime-package-registry.json','js/gridlyPackageRegistry.js','assets/location-resolution/gridly-authoritative-county-geometry-v1.json','assets/location-resolution/gridly-authoritative-county-geometry-v1.manifest.json'];
test('LP190.4 fixes the activation cohort and exposes all guarded modes',()=>{assert.deepEqual(FINAL11,['48061','48073','48113','48121','48135','48229','48329','48377','48401','48425','48441']);const source=fs.readFileSync('scripts/lp1904-final-statewide-runtime-activation-guarded.mjs','utf8');for(const flag of ['--whatif','--apply','--verify','--json'])assert.match(source,new RegExp(flag));assert.match(source,/countyRegistryRange/);assert.doesNotMatch(source,/gridlyResolveCountyIdForCoordinate\s*=/);});
test('missing owner-local governed payloads fail closed before WHATIF can write',()=>{const before=production.map(p=>fs.statSync(p).mtimeMs);assert.throws(()=>run('whatif'),/governed payload drift|ENOENT/);assert.deepEqual(production.map(p=>fs.statSync(p).mtimeMs),before);});
test('activation output contract requires every requested invariant',()=>{const source=fs.readFileSync('scripts/lp1904-final-statewide-runtime-activation-guarded.mjs','utf8');for(const key of ['operationalUniqueFips','allTexasCountiesOperational','final11Operational','original243Operational','runtimeRestrictedCountyCount','lp1903EligibilitySatisfied','communityMetadata','communityAvailability','countyIdentityFips','censusIdentityPlaceGeoid','productionGeometryCountyCount','productionManifestCountyCount','manifestPackageByteLength','manifestPackageSha256','manifestPackagePath','restrictedGeometryExcludedCount','resolverLogicUnchanged','boundsCandidatePrefilterOnly','polygonContainmentCertified','crossingPackagesUnchanged','protectedSystemsUnchanged'])assert.match(source,new RegExp(key));assert.match(source,/Object\.entries\(checks\)\.every/);});
test('blocked report is truthful and production/crossing scopes remain untouched',()=>{const report=JSON.parse(fs.readFileSync('reports/lp1904/final-statewide-runtime-activation.json'));assert.equal(report.activationPerformed,false);assert.deepEqual(report.productionSurfacesChanged,[]);assert.equal(report.postActivationOperationalCount,243);assert.equal(report.postActivationRestrictedCount,11);assert.equal(report.overallClassification,'OWNER_EXECUTION_REQUIRED_MISSING_GOVERNED_INPUTS_FAIL_CLOSED');});
