import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import vm from 'node:vm';
import {WRITE_ALLOWLIST} from '../tools/lp194/activate-san-antonio-runtime.mjs';
const source='evidence/lp193/san-antonio-consumer-region-design-geometry.geojson';
const runtime='data/runtime/san-antonio-consumer-regions.geojson';
const registry='data/runtime/san-antonio-consumer-regions.json';
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const expectedIds=['central-san-antonio','medical-region','airport-fort-sam','stone-oak-far-north','utsa-northwest','far-west-alamo-ranch','northeast-san-antonio','southside-brooks','southwest-port-san-antonio'];
const expectedLabels=['Central San Antonio','Medical Region','Airport / Fort Sam','Stone Oak / Far North','UTSA / Northwest','Far West / Alamo Ranch','Northeast San Antonio','Southside / Brooks','Southwest / Port San Antonio'];
const places=['Alamo Heights','Balcones Heights','Castle Hills','China Grove','Cibolo','Converse','Cross Mountain','Elmendorf','Fair Oaks Ranch','Grey Forest','Helotes','Hill Country Village','Hollywood Park','Kirby','Lackland AFB','Leon Valley','Live Oak','Lytle','Macdona','Olmos Park','Randolph AFB','Sandy Oaks','Scenic Oaks','Schertz','Selma','Shavano Park','Somerset','St. Hedwig','Terrell Hills','Timberwood Park','Universal City','Von Ormy','Windcrest'];
const data=()=>JSON.parse(fs.readFileSync(registry));
const functionBody=(source,name,next)=>{const start=source.indexOf(`function ${name}`);assert.notEqual(start,-1,`${name} exists`);const end=source.indexOf(`\n\n${next}`,start);return source.slice(start,end);};
function regionCameraHarness(){
 const source=fs.readFileSync('js/app.js','utf8');
 const regions=Object.fromEntries(data().regions.map(region=>[region.regionId,{id:region.regionId,countyId:region.countyId,lat:region.semanticCenter.latitude,lng:region.semanticCenter.longitude,startupZoom:region.startupZoom}]));
 const areas=Object.fromEntries(Object.values(regions).map(region=>[region.id,{key:region.id,awarenessRegionId:region.id,countyId:region.countyId,sanAntonioRegion:true,lat:region.lat,lng:region.lng,startupZoom:region.startupZoom}]));
 const calls={setView:[],county:0};
 const context={map:{},GRIDLY_LP194_SAN_ANTONIO_REGION_LOOKUP:regions,GRIDLY_AWARENESS_AREA_BY_KEY:areas,gridlySemanticCameraSequence:0,gridlyCommittedSemanticCamera:null,gridlyPlacePresentationTargets:{},GRIDLY_TOWN_STARTUP_ZOOM:13,GRIDLY_COUNTY_STARTUP_ZOOM:10,
  setGridlyAwarenessView(target,zoom,options){calls.setView.push({target,zoom,options});return true;},gridlyResolveCanonicalPlaceGeoid(){return null;},gridlyNormalizeCountyId(value){return value;},gridlyGetAuthoritativeCountyGeometryFocusBounds(){calls.county++;return null;},getGridlyAwarenessFitPadding(){return {};}};
 vm.runInNewContext(`${functionBody(source,'gridlyDispatchSemanticCamera','function gridlyFocusConfirmedHomeSelection')}\nthis.dispatch=gridlyDispatchSemanticCamera;`,context);
 return {context,calls,regions,areas};
}
test('exact certified geometry identity and nine valid features',()=>{assert.equal(fs.statSync(source).size,3577612);assert.equal(sha(source),'c8aa67df96e0ac21a9c339eb3eebf67d528522786ab662d8f330eb883dcedfae');assert.equal(sha(runtime),sha(source));const g=JSON.parse(fs.readFileSync(runtime));assert.deepEqual(g.features.map(f=>f.properties.regionId),expectedIds);assert.ok(g.features.every(f=>f.geometry?.coordinates?.length));});
test('exact identities, labels, LP193 centers, zooms, and memberships activate',()=>{const d=data(),l=JSON.parse(fs.readFileSync('reports/lp193/san-antonio-consumer-region-implementation-readiness.json'));assert.deepEqual(d.regions.map(r=>r.regionId),expectedIds);assert.deepEqual(d.regions.map(r=>r.consumerLabel),expectedLabels);for(const r of d.regions){const x=l.regions.find(v=>v.regionId===r.regionId);assert.deepEqual(r.semanticCenter,{latitude:x.semanticCenter.latitude,longitude:x.semanticCenter.longitude});assert.equal(r.startupZoom,x.startupZoom.proposedZoom);assert.deepEqual(r.atomicMembership,x.atomicMembership);}});
test('precedence preserves all 33 independent identities including selective holds',()=>{const d=data();assert.equal(d.precedence,'INDEPENDENT_GOVERNED_PLACE_WINS');assert.equal(d.independentPlaceCdpCount,places.length);assert.ok(places.includes('Somerset')&&places.includes('Von Ormy'));const overlay=JSON.parse(fs.readFileSync('reports/lp191/bexar-place-cdp-overlay.json'));for(const name of places)assert.ok(JSON.stringify(overlay).includes(name));});
test('Far Southwest is absent and southwest membership is selective',()=>{const d=data(),sw=d.regions.find(r=>r.regionId==='southwest-port-san-antonio');assert.equal(d.farSouthwestActivated,false);assert.deepEqual(sw.atomicMembership,['Port San Antonio','Southwest']);assert.equal(sw.limitation,'PARTIAL_CERTIFIED_REGION_PENDING_FAR_SOUTHWEST_CLARIFICATION');assert.ok(!d.regions.some(r=>r.atomicMembership.includes('Far Southwest')));});
test('awareness, search, ZIP and recenter contracts use existing machinery',()=>{const app=fs.readFileSync('js/app.js','utf8');for(const label of expectedLabels)assert.ok(app.includes(label));assert.match(app,/GRIDLY_AWARENESS_AREA_DEFINITIONS\.push\(gridlyLp194SanAntonioRegionAwarenessArea/);assert.match(app,/gridlyLp194FindSanAntonioRegion/);assert.match(app,/startupZoom: region\.startupZoom/);assert.ok(!app.includes('Far Southwest membership'));assert.ok(!JSON.stringify(data()).includes('zipMappings'));});
test('confirmed Central and Medical selections dispatch exact governed LP193 cameras',()=>{const {context,calls,areas}=regionCameraHarness();for(const id of ['central-san-antonio','medical-region'])assert.equal(context.dispatch(areas[id],'bexar-tx',{source:'confirmed_home'}),true);assert.deepEqual(JSON.parse(JSON.stringify(calls.setView)),[
 {target:{lat:29.43715940524094,lng:-98.52110359096712},zoom:11.16,options:{animate:false,compensateForChrome:false}},
 {target:{lat:29.495636300789577,lng:-98.51516602675414},zoom:11.36,options:{animate:false,compensateForChrome:false}}
]);});
test('all nine San Antonio regions use registry cameras and never county or parent-city fallback',()=>{const {context,calls,areas}=regionCameraHarness();for(const region of data().regions){const arbitraryPersisted={...areas[region.regionId],lat:1,lng:2,startupZoom:3};assert.equal(context.dispatch(arbitraryPersisted,'bexar-tx',{source:'confirmed_home'}),true);const issued=calls.setView.at(-1);assert.deepEqual(JSON.parse(JSON.stringify(issued.target)),{lat:region.semanticCenter.latitude,lng:region.semanticCenter.longitude},region.regionId);assert.equal(issued.zoom,region.startupZoom,region.regionId);}assert.equal(calls.setView.length,9);assert.equal(calls.county,0);assert.ok(calls.setView.every(call=>call.zoom!==9));});
test('confirmed home region path delegates to the shared semantic camera only',()=>{const app=fs.readFileSync('js/app.js','utf8');const focus=functionBody(app,'gridlyFocusConfirmedHomeSelection','function gridlyResolvePersistedSemanticContextForStartup');assert.match(focus,/gridlyDispatchSemanticCamera\(area, countyId, \{ source: "confirmed_home" \}\)/);assert.doesNotMatch(focus,/setView|flyTo|fitBounds/);});
test('Houston and statewide county runtime remain governed and unchanged in architecture',()=>{const app=fs.readFileSync('js/app.js','utf8');assert.match(app,/const GRIDLY_LP035_HOUSTON_REGION_MODEL/);assert.match(app,/GRIDLY_COUNTY_AWARENESS_BOUNDS_BY_ID/);assert.equal((app.match(/houston-downtown-midtown/g)||[]).length>0,true);});
test('whatif writes nothing, allowlist is exact, apply is idempotent, verify detects no drift',()=>{assert.deepEqual(WRITE_ALLOWLIST,[runtime,registry,'js/app.js']);const before=WRITE_ALLOWLIST.map(sha);let x=spawnSync(process.execPath,['tools/lp194/activate-san-antonio-runtime.mjs','--whatif'],{encoding:'utf8'});assert.equal(x.status,0,x.stderr);assert.deepEqual(WRITE_ALLOWLIST.map(sha),before);x=spawnSync(process.execPath,['tools/lp194/activate-san-antonio-runtime.mjs','--apply'],{encoding:'utf8'});assert.equal(x.status,0,x.stderr);assert.deepEqual(WRITE_ALLOWLIST.map(sha),before);x=spawnSync(process.execPath,['tools/lp194/activate-san-antonio-runtime.mjs','--verify'],{encoding:'utf8'});assert.equal(x.status,0,x.stderr);});
