import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { FINAL11, assertOperationalRegistryUnique, operationalRegistryAudit } from '../scripts/lp1904-final-statewide-runtime-activation-guarded.mjs';

const production=['js/app.js','assets/package-registry/runtime-package-registry.json','js/gridlyPackageRegistry.js','assets/location-resolution/gridly-authoritative-county-geometry-v1.json','assets/location-resolution/gridly-authoritative-county-geometry-v1.manifest.json'];
test('LP190.4 fixes the activation cohort and exposes all guarded modes',()=>{assert.deepEqual(FINAL11,['48061','48073','48113','48121','48135','48229','48329','48377','48401','48425','48441']);const source=fs.readFileSync('scripts/lp1904-final-statewide-runtime-activation-guarded.mjs','utf8');for(const flag of ['--whatif','--apply','--verify','--json'])assert.match(source,new RegExp(flag));assert.match(source,/countyRegistryRange/);assert.doesNotMatch(source,/gridlyResolveCountyIdForCoordinate\s*=/);});
const app=()=>fs.readFileSync('js/app.js','utf8');
const statewide=()=>JSON.parse(fs.readFileSync('assets/location-resolution/gridly-authoritative-texas-county-geometry-v1.json'));
test('current production registry is exactly 243 unique operational county identities',()=>{const audit=operationalRegistryAudit(app(),statewide().counties);assert.equal(audit.totalRecords,243);assert.equal(audit.extractedFipsCount,243);assert.equal(audit.uniqueFipsCount,243);assert.deepEqual(audit.duplicateFips,[]);assert.deepEqual(audit.duplicateRegistryKeys,[]);});
test('a duplicated operational county identity fails closed',()=>{const text=app().replace(/(  "anderson-tx": Object\.freeze\(\{[^\n]+\n)/, '$1  "anderson-alias-tx": Object.freeze({ id: "anderson-alias-tx", countyFips: "48001", operational: true }),\n');const audit=operationalRegistryAudit(text,statewide().counties);assert.deepEqual(audit.duplicateFips,[{fips:'48001',keys:['anderson-tx','anderson-alias-tx']}]);assert.throws(()=>assertOperationalRegistryUnique(audit),/operational FIPS must be unique: 48001/);});
test('a duplicated registry key fails before JavaScript evaluation can hide it',()=>{const text=app().replace(/(  "anderson-tx": Object\.freeze\(\{[^\n]+\n)/, '$1  "anderson-tx": Object.freeze({ id: "anderson-tx", countyFips: "48001", operational: true }),\n');assert.throws(()=>operationalRegistryAudit(text,statewide().counties),/runtime registry duplicate keys: anderson-tx/);});
test('FIPS references outside authoritative membership do not affect the audit',()=>{const text=`// countyFips: "48001", operational: true\n${app()}\n// countyFips: "48001", operational: true\n`;const audit=operationalRegistryAudit(text,statewide().counties);assert.equal(audit.uniqueFipsCount,243);assert.deepEqual(audit.duplicateFips,[]);});
test('guard preserves the exact cohort, 254 target, 243/11 runtime, and production bytes',()=>{const before=production.map(p=>fs.readFileSync(p));const audit=operationalRegistryAudit(app(),statewide().counties);assert.equal(audit.uniqueFipsCount,243);assert.equal(FINAL11.length,11);assert.equal(audit.uniqueFipsCount+FINAL11.length,254);assert.ok(FINAL11.every(fips=>!audit.operationalFips.has(fips)));const source=fs.readFileSync('scripts/lp1904-final-statewide-runtime-activation-guarded.mjs','utf8');assert.match(source,/currentRuntime:\{operational:243,restricted:11\}/);assert.match(source,/targetRuntime:\{operational:254,restricted:0\}/);assert.deepEqual(production.map(p=>fs.readFileSync(p)),before);});
test('activation output contract requires every requested invariant',()=>{const source=fs.readFileSync('scripts/lp1904-final-statewide-runtime-activation-guarded.mjs','utf8');for(const key of ['operationalUniqueFips','allTexasCountiesOperational','final11Operational','original243Operational','runtimeRestrictedCountyCount','lp1903EligibilitySatisfied','communityMetadata','communityAvailability','countyIdentityFips','censusIdentityPlaceGeoid','productionGeometryCountyCount','productionManifestCountyCount','manifestPackageByteLength','manifestPackageSha256','manifestPackagePath','restrictedGeometryExcludedCount','resolverLogicUnchanged','boundsCandidatePrefilterOnly','polygonContainmentCertified','crossingPackagesUnchanged','protectedSystemsUnchanged'])assert.match(source,new RegExp(key));assert.match(source,/Object\.entries\(checks\)\.every/);});
test('blocked report is truthful and production/crossing scopes remain untouched',()=>{const report=JSON.parse(fs.readFileSync('reports/lp1904/final-statewide-runtime-activation.json'));assert.equal(report.activationPerformed,false);assert.deepEqual(report.productionSurfacesChanged,[]);assert.equal(report.postActivationOperationalCount,243);assert.equal(report.postActivationRestrictedCount,11);assert.equal(report.overallClassification,'OWNER_EXECUTION_REQUIRED_MISSING_GOVERNED_INPUTS_FAIL_CLOSED');});
