import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { METHODS } from '../tools/lp200/derive-populated-cores.mjs';
import { FIRST_OWNER_IDENTITY, OWNER_ARTIFACT_ENV, ownerArtifactOutputs, preflightOwnerArtifact } from '../tools/lp200/verify-owner-artifact.mjs';

const projection=JSON.parse(fs.readFileSync('data/generated/gridly-statewide-consumer-community-projection-v1.json'));
const manifestBytes=fs.readFileSync('data/generated/lp104/txgio-addresses/manifest.json');
const manifest=JSON.parse(manifestBytes);
const placeSource={filename:'tl_2025_48_place.zip',bytes:9782040,sha256:'5a0c4d49641f69028ee9f5c343bf09936ec00a378e5e6393115b106bab935e13',vintage:2025};
const candidate=(method,lat,lng)=>({method,lat,lng,projectedX:1,projectedY:1,containment:'PASS',addressSupport:50,densityEvidence:{},containedAddressFallbackApplied:false});
function fixture(){const places={};for(const c of projection.communities){const candidates=Object.fromEntries(METHODS.map((m,i)=>[m,candidate(m,Number(c.intptlat||31)+i/10000,Number(c.intptlon||-97)+i/10000)]));places[c.placeGeoid]={placeGeoid:c.placeGeoid,label:c.displayName,countyMemberships:c.countyMemberships,addressPointsIntersectingPlace:50,uniqueAddressCount:50,addressDensityPerSquareKilometer:1,selectedDensityResolutionMeters:500,candidates,selectedMethod:METHODS.at(-1),classification:'POPULATED_CORE_CERTIFIED'};}return {schemaVersion:'gridly.lp200.statewide-place-populated-core-candidates.v1',certificationOnly:true,rowCount:1859,deduplicationRule:'fixture',inputBinding:{manifestSha256:crypto.createHash('sha256').update(manifestBytes).digest('hex'),acceptedAddressRecords:manifest.packages.reduce((n,p)=>n+p.acceptedRecords,0),packageCount:254,packageIdentities:manifest.packages.map(p=>({fips:p.fips,bytes:p.outputBytes,sha256:p.packageHash})),placeSource,canonicalPlaceCount:1859,membershipCount:2058},places};}
function withArtifact(value,fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp200-artifact-')),file=path.join(dir,'owner.json');try{fs.writeFileSync(file,typeof value==='string'?value:JSON.stringify(value));return fn(file);}finally{fs.rmSync(dir,{recursive:true,force:true});}}

test('explicit owner artifact contract verifies 1859 exact GEOIDs and 2058 memberships',()=>withArtifact(fixture(),file=>{const p=preflightOwnerArtifact(file);assert.equal(p.artifact.rowCount,1859);assert.equal(Object.values(p.artifact.places).reduce((n,r)=>n+r.countyMemberships.length,0),2058);assert.equal(p.binding.packageIdentities.length,254);assert.equal(p.binding.acceptedAddressRecords,12130953);}));
test('malformed, missing and duplicate-equivalent GEOID inventories fail closed',()=>{withArtifact('{',file=>assert.throws(()=>preflightOwnerArtifact(file),/INVALID_JSON/));const missing=fixture();delete missing.places[Object.keys(missing.places)[0]];withArtifact(missing,file=>assert.throws(()=>preflightOwnerArtifact(file),/GEOID_COUNT_OR_DUPLICATE/));const replaced=fixture(),keys=Object.keys(replaced.places);replaced.places[keys[0]]=structuredClone(replaced.places[keys[1]]);withArtifact(replaced,file=>assert.throws(()=>preflightOwnerArtifact(file),/PLACE_CONTRACT_MISMATCH/));});
test('input identity mismatch and volatile/runtime telemetry fail closed',()=>{const mismatch=fixture();mismatch.inputBinding.manifestSha256='0'.repeat(64);withArtifact(mismatch,file=>assert.throws(()=>preflightOwnerArtifact(file),/INPUT_IDENTITY_MISMATCH/));const volatile=fixture();volatile.processingDurationMilliseconds=4;withArtifact(volatile,file=>assert.throws(()=>preflightOwnerArtifact(file),/VOLATILE_FIELD/));});
test('artifact-only certification is deterministic, extracts controls, and preserves hash',()=>withArtifact(fixture(),file=>{const before=fs.readFileSync(file),a=ownerArtifactOutputs(file),b=ownerArtifactOutputs(file),after=fs.readFileSync(file);assert.deepEqual(a,b);assert.deepEqual(after,before);const report=JSON.parse(a['reports/lp200/statewide-governed-place-populated-core-signal-certification.json']);assert.equal(report.calibration.candidateMetrics.length,6);assert.equal(report.knownBadControls.length,5);assert.equal(report.smallPlaceControls.length,5);assert.equal(report.scope.addressPackagesOpened,false);assert.equal(report.scope.derivePopulatedCoresInvoked,false);assert.equal(report.scope.gdalSpatialExportInvoked,false);for(const bytes of Object.values(a))for(const word of ['processingDurationMilliseconds','generatedAt','startedAt','finishedAt','tempPath','pid'])assert.ok(!bytes.includes(`"${word}"`));}));
test('artifact-only implementation has an explicit path and no derivation/GDAL/address package calls',()=>{const source=fs.readFileSync('tools/lp200/verify-owner-artifact.mjs','utf8');assert.match(source,new RegExp(OWNER_ARTIFACT_ENV));assert.ok(!source.includes('derivePopulatedCores('));assert.ok(!source.includes('loadPlacePolygons('));assert.ok(!source.includes('spawnSync('));assert.ok(!source.includes('.addresses.jsonl.gz'));assert.equal(FIRST_OWNER_IDENTITY.sha256,'0c66bb25978f186bf37633dfb77e01bfbcb686b5309db0ec3055af5a2478e1fc');});
