const test=require('node:test'), assert=require('node:assert/strict'), fs=require('node:fs'), vm=require('node:vm'), cp=require('node:child_process');
const r=require('../js/gridlyMarkerRegistry.js'), n=require('../js/gridlyHazardNormalization.js');
const app=fs.readFileSync('js/app.js','utf8');
function fn(name){const a=app.indexOf('function '+name+'(');assert.ok(a>=0,name);return app.slice(a,app.indexOf('\nfunction ',a+1));}
const ctx={GridlyMarkerRegistry:r,GridlyHazardNormalization:n,GRIDLY_WINTER_MARKER_ASSETS:r.winterAssets,GRIDLY_PRODUCTION_MARKER_CATEGORY_ASSETS:r.assetMap,GRIDLY_PRODUCTION_MARKER_BASE_PATH:r.basePath,getHazardCategory:x=>x,resolveOtherHazardSubtypeFromRecord:x=>x.other_hazard_subtype||'',gridlyLp019SafeText:String};
vm.createContext(ctx);for(const name of ['getGridlyProductionMarkerCategory','getGridlyProductionMarkerAsset','gridlyLp019OfficialCategory','gridlyOfficialRoadwayPresentationCategory'])vm.runInContext(fn(name),ctx);
const category=x=>ctx.getGridlyProductionMarkerCategory(x);
test('every active canonical hazard and legacy category has explicit coverage',()=>{
 for(const condition of Object.keys(n.definitions))assert.ok(r.aliases[condition.toLowerCase()],condition);
 const inventory=JSON.parse(fs.readFileSync('reports/lp24447-marker-inventory.json'));for(const row of inventory.rows)assert.ok(r.aliases[row.category],row.category);
});
test('every intended distinct visual condition has its own asset',()=>assert.equal(new Set(Object.values(r.entries).map(x=>x.asset)).size,Object.keys(r.entries).length));
test('legacy aliases are deterministic and never accidentally fall through',()=>{for(const [alias,target]of Object.entries(r.aliases))assert.equal(r.resolve(alias).condition,target);for(const [alias,condition]of Object.entries(n.aliases)){assert.ok(r.aliases[alias],alias);if(condition!=='OTHER_ROAD_HAZARD')assert.notEqual(r.resolve(alias).condition,'other_hazard',alias);}});
test('seven winter assets remain separate from water, with improved slick/snow cues',()=>{assert.equal(new Set(Object.values(r.winterAssets)).size,7);for(const asset of Object.values(r.winterAssets))assert.notEqual(asset,r.resolve('flooding').asset);assert.match(r.resolve('black_ice').symbol,/slick.*glint/);assert.match(r.resolve('snow_on_road').symbol,/accumulated snow/);});
test('road states and vehicle/work distinctions are explicit',()=>{for(const set of [['road_blocked','road_impassable','road_closed'],['crash','disabled_vehicle'],['construction','traffic_backup'],['rail_issue','rail_blockage_delay','crossing_infrastructure'],['utility_work','downed_power_line']])assert.equal(new Set(set.map(x=>r.resolve(x).asset)).size,set.length);});
test('both report pickers and every other-hazard subtype have explicit mappings',()=>{const inv=JSON.parse(fs.readFileSync('reports/lp24447-marker-inventory.json'));for(const option of [...inv.picker.road,...inv.picker.other]){assert.ok(r.aliases[option.value],option.value);const record=option.value==='other'?{type:'other_hazard',other_hazard_subtype:'other'}:{report_type:option.value,normalizedEvent:n.community({type:option.value})};assert.equal(r.resolve(category(record)).asset,r.resolve(option.value).asset);}});
test('grouped legacy records retain original subtype over visual fallback',()=>{for(const type of ['black_ice','planned_work','fallen_tree','disabled_vehicle','road_impassable']){assert.equal(category({type:'debris',report_type:type}),r.resolve(type).condition);assert.equal(category({type:'debris',legacyReportType:type}),r.resolve(type).condition);}assert.equal(category({type:'other_hazard',other_hazard_subtype:'livestock_on_road'}),'livestock_on_road');});
test('community closure aliases cannot acquire the official closure symbol',()=>{for(const type of ['road_closed','road_closure','closure','txdot_closure','blocked_roadway']){assert.equal(category({report_type:type,normalizedEvent:n.community({type})}),'road_blocked');assert.equal(category({report_type:type}),'road_blocked');}assert.equal(ctx.gridlyOfficialRoadwayPresentationCategory({category:'Road Closure'}),'txdot_closure');});
test('DriveTexas keeps closure, work, crash, incident, damage, hazard and advisory meanings',()=>{for(const [label,want]of [['Road Closure','road_closed'],['Construction','construction'],['Crash','crash'],['Traffic incident','txdot_incident'],['Road damage','txdot_damage'],['Road hazard','other_hazard'],['Travel advisory','txdot_other'],['Disabled vehicle','disabled_vehicle'],['Bridge restriction','txdot_bridge_restriction'],['Heavy traffic delay','traffic_backup'],['High water','flooding'],['Possible black ice','black_ice_suspected']])assert.equal(r.resolve(ctx.gridlyOfficialRoadwayPresentationCategory({category:label})).condition,want,label);});
test('all static SVGs share viewbox, borders, dimensions, dependency-free vectors',()=>{for(const e of Object.values(r.entries)){assert.equal(e.size,64);assert.equal(e.tipRatio,244/256);const svg=fs.readFileSync(r.basePath+e.asset,'utf8');assert.match(svg,/viewBox="0 0 256 256"/);assert.match(svg,/stroke="#f0f9ff" stroke-width="4"/);assert.doesNotMatch(svg,/<image|<text|<script|<foreignObject|href=|url\(|font-/i);assert.ok(Buffer.byteLength(svg)<4000);}});
test('all legacy aliases remain available; unknown input alone uses fallback',()=>{assert.equal(r.resolve('unrecognized_future_type').condition,'other_hazard');assert.equal(r.resolve('standing water').condition,'flooding');assert.equal(r.resolve('road-work').condition,'construction');});
test('authority, geometry, providers and protocol modules remain byte-equivalent to starting commit',()=>{for(const file of ['js/gridlyHazardNormalization.js','js/gridlyDriveTexasProvider.js','js/gridlyWeatherProvider.js','js/gridly-report-protocol.js','js/gridly-ugc-compliance.js'])assert.equal(fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'),cp.execFileSync('git',['show','9c9e082d:'+file],{encoding:'utf8',maxBuffer:30e6}).replace(/\r\n/g,'\n'));});
test('lifecycle, filters, severity, popup labels and awareness context owners unchanged',()=>{const baseline=cp.execFileSync('git',['show','9c9e082d:js/app.js'],{encoding:'utf8',maxBuffer:30e6});for(const name of ['getGridlyIncidentSeverity','getGridlyIncidentVisualState','gridlyIncidentEligibleForMapMarker','getIncidentLifecycleState','gridlyTravelBriefCommunityCondition','buildReportHazardSurfaceHtml','buildGridlyHazardPopupConsumerModel','getHazardClusterKey','getUnifiedIncidentRenderKey']){let a=baseline.indexOf('function '+name+'(');assert.ok(a>=0,name);assert.ok(app.includes(baseline.slice(a,baseline.indexOf('\nfunction ',a+1))),name);}});
test('base artwork scaling has no condition-specific enlargement',()=>{const css=fs.readFileSync('css/styles.css','utf8');for(const match of (css+app).matchAll(/--gridly-production-marker-artwork-scale:\s*([\d.]+)/g))assert.equal(Number(match[1]),1);assert.match(css,/transform: scale\(1\.1\) !important/);});
