import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {artifacts,verify} from '../tools/lp24111/manufacture.mjs';
import {categoryFor,detectInputs,duplicateWinner,eligibilityFor,execute,expected,matchedColumns,measurementQueries,normalizationSql,normalizationStages,validateMatchedSchemas} from '../tools/lp24111/normalize.mjs';
const sql=()=>fs.readFileSync('tools/lp24111/extract-texas.sql','utf8');
const richCli=path.resolve('tools/lp24111/rich-manufacture.mjs');
const runRich=args=>spawnSync(process.execPath,[richCli,...args],{encoding:'utf8'});
const measuredEnvelope=reports=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp24111-envelope-')),file=path.join(dir,'normalized-measurements.json');fs.writeFileSync(file,JSON.stringify({schemaVersion:'gridly.lp24111.measured-normalization.v1',releaseId:'2026-08-19.0',reports}));return file;};

test('normalization report reasons follow execution state instead of surviving the measured merge',()=>{const unmeasured=artifacts({measurementsPath:'/definitely/absent/normalized-measurements.json'})['normalization-summary.json'];assert.equal(unmeasured.executionState,'NOT_EXECUTED');assert.match(unmeasured.reason,/absent from this checkout/);const measurementsPath=measuredEnvelope({'normalization-summary.json':{executionState:'OWNER_LOCAL_MEASURED',normalizedUniquePois:1462815,eligibleDestinations:364959,nonDestination:83992,excluded:12227,reviewRequired:1001637}}),measured=artifacts({measurementsPath})['normalization-summary.json'];assert.equal(measured.executionState,'OWNER_LOCAL_MEASURED');assert.equal(Object.hasOwn(measured,'reason'),false);assert.doesNotMatch(JSON.stringify(measured),/absent from this checkout|NOT_EXECUTED/);assert.deepEqual([measured.normalizedUniquePois,measured.eligibleDestinations,measured.nonDestination,measured.excluded,measured.reviewRequired],[1462815,364959,83992,12227,1001637]);});

test('measured envelope clears execution contradictions while preserving Phase D blockers and runtime boundary',()=>{const measurementsPath=measuredEnvelope({'normalization-summary.json':{executionState:'OWNER_LOCAL_MEASURED'},'execution-summary.json':{richFieldManufacturing:'OWNER_LOCAL_MEASURED',normalization:'OWNER_LOCAL_MEASURED'},'rich-field-extraction.json':{executionState:'OWNER_LOCAL_MEASURED',reason:'Owner-local authority-matched shards were normalized and measured without a remote refetch.'},'rich-authority-conservation.json':{executionState:'OWNER_LOCAL_MEASURED',duplicateContentConflicts:0,normalizationGate:'EXECUTED'},'exception-ledger.json':{exceptions:[{id:'REMAINING_PHASE_D_MEASUREMENTS_NOT_EXECUTED',severity:'BLOCKER'},{id:'LICENSE_COUNSEL_REVIEW',severity:'BLOCKER'}]},'certification.json':{productionPoiSearch:'NOT_LAUNCHED_NOT_CERTIFIED',zeroCostContract:'NON_RUNTIME'}}),a=artifacts({measurementsPath});assert.equal(a['execution-summary.json'].normalization,'OWNER_LOCAL_MEASURED');assert.equal(a['rich-field-extraction.json'].executionState,'OWNER_LOCAL_MEASURED');assert.doesNotMatch(a['rich-field-extraction.json'].reason,/not present|absent/);assert.equal(a['rich-authority-conservation.json'].duplicateContentConflicts,0);assert.ok(a['exception-ledger.json'].exceptions.some(x=>x.id==='REMAINING_PHASE_D_MEASUREMENTS_NOT_EXECUTED'&&x.severity==='BLOCKER'));assert.ok(a['exception-ledger.json'].exceptions.some(x=>x.id==='LICENSE_COUNSEL_REVIEW'&&x.severity==='BLOCKER'));assert.equal(a['certification.json'].productionPoiSearch,'NOT_LAUNCHED_NOT_CERTIFIED');assert.equal(a['certification.json'].zeroCostContract,'NON_RUNTIME');});

test('owner statewide evidence certifies exact per-ID conservation',()=>{const a=verify(),c=a['county-assignment-certification.json']; assert.equal(c.authorityIds,1462815); assert.equal(c.uniqueIds,1462815); assert.equal(c.uniqueCountyAssignments,1462815); assert.equal(c.totalCountyIntersections,1462815); assert.equal(c.unassigned,0); assert.equal(c.boundaryMulti,0); assert.equal(c.zeroCountLoss,true); assert.equal(c.exactUniqueIdConservation,'CERTIFIED');});
test('owner-certified rich shard conservation is recorded without inventing normalization',()=>{const a=verify(),r=a['rich-authority-conservation.json'],n=a['normalization-summary.json'];assert.deepEqual([r.inputShardRows,r.uniqueIds,r.crossShardDuplicateIds,r.extraDuplicateRows,r.maximumShardOccurrencesPerId,r.missingAuthorityIds,r.outsideAuthorityIds],[1462893,1462815,52,78,4,0,0]);assert.equal(r.conservationPassed,true);if(n.executionState==='OWNER_LOCAL_MEASURED'){assert.equal(r.executionState,'OWNER_LOCAL_MEASURED');assert.equal(r.normalizationGate,'EXECUTED');assert.equal(n.rawUniquePois,1462815);assert.equal(n.normalizedUniquePois,1462815);assert.ok(Number.isSafeInteger(n.eligibleDestinations));}else{assert.equal(n.executionState,'NOT_EXECUTED');assert.equal(n.normalizedUniquePois,null);assert.equal(n.eligibleDestinations,null);}assert.equal(a['certification.json'].productViability,'OVERTURE_TEXAS_POI_AUTHORITY_NOT_YET_PRODUCT_VIABLE');});
test('launcher and staged CRS authority are explicit',()=>{const ps=fs.readFileSync('tools/lp24111/extract-texas.ps1','utf8'); assert.match(ps,/Get-Content -Raw/); assert.match(ps,/\$program \| & \$DuckDb/); assert.doesNotMatch(ps,/\.read/); assert.match(sql(),/ST_Transform\(geom, 'EPSG:4269', 'OGC:CRS84', always_xy := true\)/); assert.match(sql(),/BOUNDARY_MULTI_INTERSECTION/);});
test('remote extraction is lightweight and literal-pruned',()=>{assert.match(sql(),/SELECT id, geometry, bbox/); assert.doesNotMatch(sql(),/SELECT p\.\*/i); assert.match(sql(),/bbox\.xmin <= -93\.5/); assert.match(sql(),/PERFORMANCE|literal/i);});
test('quality dimensions are independent',()=>{const a=verify(); assert.ok(a['category-coverage.json'].mapping.humanMedicalExclusions.includes('animal_hospital')); assert.ok(a['category-coverage.json'].mapping.nonDestinationExclusions.includes('structure_and_geography')); assert.equal(a['spatial-metadata-conflicts.json'].classification,'SPATIAL_METADATA_CONFLICT'); assert.match(a['confidence-analysis.json'].policy,/NO_CUTOFF/); assert.ok(a['duplicate-child-poi-analysis.json'].classifications.includes('CHILD_POI'));});
test('governed PLACE and non-PLACE coverage remain represented',()=>{const a=verify(); assert.equal(a['community-coverage.json'].canonicalPlaceAccounted,1859); assert.equal(a['governed-non-place-coverage.json'].governedInventory.total,29); assert.equal(a['lp24110-cohort-reconciliation.json'].communityCount,22);});
test('runtime and deployment remain untouched',()=>{const a=verify(); assert.equal(a['certification.json'].productionPoiSearch,'NOT_LAUNCHED_NOT_CERTIFIED'); assert.equal(a['refresh-pipeline.json'].deployIncluded,false); assert.doesNotMatch(fs.readFileSync('js/app.js','utf8'),/lp24111|overture-texas-places/i);});
test('rich shard plan is literal, bounded, projected, and locally authority-matched',async()=>{const a=verify(),m=a['rich-shard-manifest.json']; const {shardSql,validatePlan}=await import('../tools/lp24111/rich-manufacture.mjs'); assert.equal(m.shardCount,168); assert.equal(m.countyHardWalls,false); assert.equal(validatePlan(m),true); const query=shardSql(m.rows[0]); assert.match(query,/bbox\.xmin <= -106/); assert.match(query,/INNER JOIN read_parquet/); assert.doesNotMatch(query,/SELECT\s+\*/i); assert.doesNotMatch(query,/app\.js|deploy|supabase/i);});
test('Phase D measured and unmeasured result shapes remain explicit',()=>{
 const a=verify(),normalization=a['normalization-summary.json'],packages=a['package-size-model.json'],certification=a['certification.json'],ledger=a['taxonomy-resolution-ledger.json'],d2Reports=[a['review-taxonomy-census.json'],ledger,a['compact-package-measurements.json']],d2Measured=d2Reports.every(report=>report.executionState==='OWNER_LOCAL_MEASURED');
 if(normalization.executionState==='OWNER_LOCAL_MEASURED'){
  assert.equal(packages.executionState,'OWNER_LOCAL_MEASURED');
  assert.equal(certification.executiveResult,d2Measured?'PHASE_D3_IDENTITY_GOVERNANCE_READY_MEASUREMENT_PENDING':'PHASE_D_OWNER_LOCAL_NORMALIZATION_EXECUTED');
  assert.equal(normalization.normalizedUniquePois,1462815);
  if(d2Measured){
   assert.equal(ledger.before.normalizedUniquePois,1462815);
   const after=ledger.after;
   assert.deepEqual([after.GRIDLY_ELIGIBLE_DESTINATION,after.GRIDLY_NON_DESTINATION,after.GRIDLY_EXCLUDED,after.GRIDLY_REVIEW_REQUIRED],[393038,83992,12227,973558]);
   assert.equal(after.GRIDLY_ELIGIBLE_DESTINATION+after.GRIDLY_NON_DESTINATION+after.GRIDLY_EXCLUDED+after.GRIDLY_REVIEW_REQUIRED,ledger.before.normalizedUniquePois);
   assert.equal(Object.hasOwn(packages.measurements,'normalizedRows'),false);
   assert.equal(Object.hasOwn(packages.measurements,'compressedBytes'),true);
  }else{
   assert.equal(packages.measurements.normalizedRows,1462815);
   assert.ok(Number.isSafeInteger(packages.measurements.eligibleRows));
   assert.ok(Array.isArray(packages.measurements.rawRowsPerShard));
   assert.ok(packages.measurements.rawRowsPerShard.length<=168);
   assert.ok(packages.measurements.rawRowsPerShard.every(row=>typeof row.shardId==='string'&&Number.isSafeInteger(row.rawRows)));
   assert.equal(packages.measurements.rawRowsPerShard.reduce((sum,row)=>sum+row.rawRows,0),1462893);
   assert.equal(Object.hasOwn(packages.measurements,'compressedBytes'),false);
  }
 }else{
  assert.equal(d2Measured,false);
  assert.equal(normalization.executionState,'NOT_EXECUTED');
  assert.equal(normalization.normalizedUniquePois,null);
  assert.equal(normalization.eligibleDestinations,null);
  assert.equal(packages.executionState,'NOT_EXECUTED');
  assert.equal(packages.measurements.compressedBytes,null);
  assert.equal(certification.executiveResult,'PHASE_D_NOT_EXECUTED_INPUT_ARTIFACTS_UNAVAILABLE');
 }
 assert.equal(a['community-coverage.json'].executionState,'NOT_EXECUTED');
});

const fixture=async()=>{
 const m=await import('../tools/lp24111/rich-manufacture.mjs'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp24111-rich-')),authority=path.join(dir,'authority.parquet');fs.writeFileSync(authority,'authority');
 const shards=[{shardId:'tx-33-101',bounds:{xmin:-101,xmax:-100,ymin:33,ymax:34}},{shardId:'tx-33-100',bounds:{xmin:-100,xmax:-99,ymin:33,ymax:34}}];
 const query=sql=>sql.startsWith('DESCRIBE')?m.fields.map(column_name=>({column_name})):sql.includes('outsideCount')?[{rowCount:4,outsideCount:0}]:[{rowCount:2,duplicateCount:0,nonAuthorityCount:0}];
 const run=sql=>{const match=sql.match(/TO '([^']+)'/);if(match)fs.writeFileSync(match[1],'parquet');return [];};
 return {m,dir,authority,shards,query,run,progressPath:path.join(dir,'progress.json')};
};
test('rich CLI selects exactly one shard or an explicit ordered set and rejects unknown IDs',async()=>{const {m,shards}=await fixture();const manifest={rows:shards};assert.deepEqual(m.selectShards(manifest,m.parseCli(['--execute','--shard','tx-33-101']).ids).map(x=>x.shardId),['tx-33-101']);assert.deepEqual(m.selectShards(manifest,m.parseCli(['--execute','--shards','tx-33-100,tx-33-101']).ids).map(x=>x.shardId),['tx-33-100','tx-33-101']);assert.throws(()=>m.selectShards(manifest,['tx-0-0']),/Unknown shard ID/);});
test('rich ESM entrypoint invokes the CLI without activating execution on import',()=>{const plan=runRich(['--plan']);assert.equal(plan.status,0,plan.stderr);assert.match(plan.stdout,/validated 168 literal rich-field shards; selected 168 \(not executed\)/);const selected=runRich(['--plan','--shards','tx-33-101,tx-33-100']);assert.equal(selected.status,0,selected.stderr);assert.match(selected.stdout,/selected 2 \(not executed\)/);const invalid=runRich(['--execute','--shard','DOES-NOT-EXIST']);assert.notEqual(invalid.status,0);assert.match(invalid.stderr,/Unknown shard ID\(s\): DOES-NOT-EXIST/);const imported=spawnSync(process.execPath,['--input-type=module','--eval',`import ${JSON.stringify(new URL('../tools/lp24111/rich-manufacture.mjs',import.meta.url).href)}`],{encoding:'utf8'});assert.equal(imported.status,0,imported.stderr);assert.equal(imported.stdout,'');assert.equal(imported.stderr,'');const source=fs.readFileSync(richCli,'utf8');assert.match(source,/pathToFileURL\(process\.argv\[1\]\)\.href/);assert.doesNotMatch(source,/`file:\/\/\$\{process\.argv\[1\]\}`/);});
test('complete rich artifacts skip and remote-only artifacts resume matching',async()=>{const f=await fixture(),p1=f.m.artifactPaths(f.shards[0].shardId,f.dir),p2=f.m.artifactPaths(f.shards[1].shardId,f.dir);fs.writeFileSync(p1.remote,'x');fs.writeFileSync(p1.matched,'x');fs.writeFileSync(p2.remote,'x');const calls=[];const result=await f.m.executeShards(f.shards,{...f,outputDirectory:f.dir,run:sql=>{calls.push(sql);return f.run(sql);},now:()=> '2026-08-28T00:00:00.000Z',clock:(()=>{let n=0;return()=>++n;})()});assert.equal(result[f.shards[0].shardId].status,'COMPLETE_EXISTING');assert.equal(result[f.shards[1].shardId].status,'REMOTE_REUSED');assert.equal(calls.length,1);assert.match(calls[0],/INNER JOIN/);});
test('failure records measurements and preserves earlier shard success',async()=>{const f=await fixture();let calls=0;await assert.rejects(f.m.executeShards(f.shards,{...f,outputDirectory:f.dir,run:sql=>{if(++calls===3)throw Error('controlled failure');return f.run(sql);},now:()=> '2026-08-28T00:00:00.000Z',clock:(()=>{let n=100;return()=>n+=5;})()}),/tx-33-100/);const progress=JSON.parse(fs.readFileSync(f.progressPath));assert.equal(progress.shards['tx-33-101'].status,'MATCHED');assert.equal(progress.shards['tx-33-100'].status,'FAILED');assert.equal(progress.shards['tx-33-101'].remoteRowCount,4);assert.equal(progress.shards['tx-33-101'].authorityMatchedRowCount,2);assert.equal(progress.shards['tx-33-101'].releaseId,'2026-08-19.0');assert.equal(progress.shards['tx-33-101'].projectionFieldCount,f.m.fields.length);assert.ok(fs.existsSync(f.m.artifactPaths('tx-33-101',f.dir).matched));});
test('invalid rich artifact is classified without an implicit rebuild',async()=>{const f=await fixture(),p=f.m.artifactPaths(f.shards[0].shardId,f.dir);fs.writeFileSync(p.remote,'x');await assert.rejects(f.m.executeShards([f.shards[0]],{...f,outputDirectory:f.dir,query:sql=>sql.startsWith('DESCRIBE')?[]:f.query(sql)}),/missing field/);const progress=JSON.parse(fs.readFileSync(f.progressPath));assert.equal(progress.shards['tx-33-101'].status,'INVALID_EXISTING_ARTIFACT');});
test('dense candidate audit uses measured rows and deterministic ties only',async()=>{const {m}=await fixture();assert.deepEqual(m.denseCandidates({shards:{b:{shardId:'b',remoteRowCount:8},a:{shardId:'a',remoteRowCount:8},z:{shardId:'z',remoteRowCount:null}}}).map(x=>x.shardId),['a','b']);});
test('normalization executor fails closed and detects the complete owner-local contract',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp24111-normalize-'));assert.deepEqual(detectInputs(dir),{authority:false,assignment:false,shards:[],ready:false});for(const file of ['overture-texas-spatial-authority.geoparquet','county-assignment-certification.parquet'])fs.writeFileSync(path.join(dir,file),'x');for(let i=0;i<expected.shards;i++)fs.writeFileSync(path.join(dir,`tx-${String(25+Math.floor(i/14)).padStart(2,'0')}-${String(93+i%14).padStart(3,'0')}.authority-matched.parquet`),'x');const found=detectInputs(dir);assert.equal(found.ready,true);assert.equal(found.shards.length,168);});
test('category policy excludes natural features and animal medicine without confidence authority',()=>{assert.equal(categoryFor('hospital pharmacy'),'HOSPITAL');assert.equal(categoryFor('animal_hospital veterinarian'),null);assert.equal(eligibilityFor('mountain structure_and_geography'),'GRIDLY_EXCLUDED');assert.equal(eligibilityFor('confidence 0.01 grocery_store'),'GRIDLY_ELIGIBLE_DESTINATION');assert.equal(categoryFor('convenience_store'),'CONVENIENCE_STORE');});
test('dedup winner and materialization SQL are deterministic and conflict preserving',()=>{assert.equal(duplicateWinner([{id:'x',shard:'tx-b'},{id:'x',shard:'tx-a'}]).shard,'tx-a');const sqlText=normalizationSql('/tmp/lp24111');assert.match(sqlText,/ORDER BY filename/);assert.match(sqlText,/content_versions/);assert.match(sqlText,/PARTITION BY id/);assert.match(sqlText,/overture-texas-rich-authority-dedup\.parquet/);assert.match(sqlText,/overture-texas-normalized-poi\.parquet/);assert.match(sqlText,/overture-texas-eligible-poi\.parquet/);});
test('normalization preserves native CRS84 geometry and schema-safe multi-file reads',()=>{const sqlText=normalizationSql('/tmp/lp24111');assert.match(sqlText,/LOAD spatial/);assert.match(sqlText,/union_by_name=true/);assert.match(sqlText,/ST_X\(r\.geometry\) longitude/);assert.match(sqlText,/ST_Y\(r\.geometry\) latitude/);assert.doesNotMatch(sqlText,/ST_GeomFromWKB\(r\.geometry\)/);});
test('matched schema validation classifies native rows and only exact empty BLOB exceptions',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp24111-schema-'));for(let i=0;i<expected.shards;i++)fs.writeFileSync(path.join(dir,`tx-${String(25+Math.floor(i/14)).padStart(2,'0')}-${String(93+i%14).padStart(3,'0')}.authority-matched.parquet`),'existing owner artifact');const schema=type=>matchedColumns.map(column_name=>({column_name,column_type:column_name==='geometry'?type:'VARCHAR'}));let calls=0;const result=validateMatchedSchemas(dir,{query:sql=>{calls++;return sql.includes('count(*)')?[{row_count:1}]:schema("GEOMETRY('OGC:CRS84')");}});assert.equal(calls,336);assert.equal(result.populatedShardCount,168);assert.equal(result.emptyShardCount,0);assert.ok(result.classifications.every(x=>x.classification==='POPULATED_NATIVE_GEOMETRY'));
 let index=0;const mixed=validateMatchedSchemas(dir,{query:sql=>sql.includes('count(*)')?[{row_count:index++===0?0:1}]:schema(index===1?'BLOB':"GEOMETRY('OGC:CRS84')")});assert.equal(mixed.emptyShardCount,1);assert.equal(mixed.populatedShardCount,167);assert.equal(mixed.classifications[0].classification,'EMPTY_BLOB_SCHEMA_COMPATIBLE');assert.equal(mixed.populatedShards.includes(mixed.emptyShards[0]),false);
 assert.throws(()=>validateMatchedSchemas(dir,{query:sql=>sql.includes('count(*)')?[{row_count:1}]:schema('BLOB')}),/incompatible geometry logical type BLOB.*row_count=1/);
 assert.throws(()=>validateMatchedSchemas(dir,{query:sql=>sql.includes('count(*)')?[{row_count:0}]:schema('BLOB').filter(x=>x.column_name!=='sources')}),/missing columns: sources/);
 assert.throws(()=>validateMatchedSchemas(dir,{query:()=>{throw Error('unreadable')}}),/DuckDB: unreadable/);
});
test('populated-only union retains spatial loading and native geometry without rebuilding or fetching',()=>{const directory=path.resolve(os.tmpdir(),'lp24111'),stages=normalizationStages(directory,['tx-populated.authority-matched.parquet']),text=stages.map(x=>x.sql).join('\n'),portableText=text.replaceAll('\\','/'),portableExpected=path.join(directory,'tx-populated.authority-matched.parquet').replaceAll('\\','/');assert.match(text,/LOAD spatial/);assert.match(text,/union_by_name=true/);assert.ok(portableText.includes(`['${portableExpected}']`));assert.doesNotMatch(text,/tx-empty|ST_GeomFromWKB|http|TO\s+'[^']*authority-matched/);});
test('certified conservation constants remain unchanged',()=>{assert.deepEqual(expected,{shards:168,inputRows:1462893,uniqueIds:1462815,multiShardIds:52,extraRows:78,maxOccurrences:4});});
test('actual Phase D measurement SQL parses and returns its report contract in DuckDB',t=>{
 const executable=process.env.DUCKDB??'duckdb',version=spawnSync(executable,['--version'],{encoding:'utf8'});if(version.error?.code==='ENOENT')return t.skip('DuckDB CLI is not installed in this environment');assert.equal(version.status,0,version.stderr);
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp24111-measurements-')),normalized=path.join(dir,'overture-texas-normalized-poi.parquet'),rich=path.join(dir,'tx-30-100.authority-matched.parquet'),authority=path.join(dir,'authority.parquet'),quote=value=>`'${value.replaceAll("'","''")}'`;
 const setup=`COPY (SELECT * FROM (VALUES ('a','48001','GRIDLY_ELIGIBLE_DESTINATION','HOSPITAL',.91,'hospital'),('b','48003','GRIDLY_REVIEW_REQUIRED',NULL,.40,'veterinarian pharmacy')) t(id,county_fips,eligibility_class,gridly_category,confidence,searchable)) TO ${quote(normalized)} (FORMAT PARQUET); COPY (SELECT * FROM (VALUES ('a','n','c','b','a',.91,'open','s'),('b','n','c','b','a',.40,'open','s')) t(id,names,categories,brand,addresses,confidence,operating_status,sources)) TO ${quote(rich)} (FORMAT PARQUET); COPY (SELECT * FROM (VALUES ('a'),('b')) t(id)) TO ${quote(authority)} (FORMAT PARQUET);`;
 const prepared=spawnSync(executable,['-bail'],{input:setup,encoding:'utf8'});assert.equal(prepared.status,0,prepared.stderr);
 const q=value=>`'${value.replaceAll("'","''")}'`,queries=measurementQueries({glob:`[${q(rich)}]`,dedup:q(rich),normalized:q(normalized),authority:q(authority)}),expectedColumns={conservation:['input_rows','unique_ids','multi_ids','extra_rows','max_occurrences','content_conflicts','missing_authority','outside_authority'],eligibility:['eligibilityClass','count'],categories:['category','count','countiesRepresented'],confidence:['segment','n','ge_05','ge_07','ge_08','ge_09'],medical:['raw_candidates','veterinary_exclusions','hospital','emergency','urgent','pharmacy'],counties:['county_fips','rawUniqueRich','eligibleDestination','nonDestination','excluded','reviewRequired'],packages:['shardId','rawRows']};
 for(const [name,query] of Object.entries(queries)){const result=spawnSync(executable,['-bail','-json'],{input:query,encoding:'utf8'});assert.equal(result.status,0,`${name}: ${result.stderr}`);const rows=JSON.parse(result.stdout);assert.ok(rows.length,`${name} returned no rows`);assert.deepEqual(Object.keys(rows[0]),expectedColumns[name],`${name} report property contract`);}
 const eligibility=JSON.parse(spawnSync(executable,['-bail','-json'],{input:queries.eligibility,encoding:'utf8'}).stdout);assert.deepEqual(eligibility,[{eligibilityClass:'GRIDLY_ELIGIBLE_DESTINATION',count:1},{eligibilityClass:'GRIDLY_REVIEW_REQUIRED',count:1}]);
 const medical=JSON.parse(spawnSync(executable,['-bail','-json'],{input:queries.medical,encoding:'utf8'}).stdout)[0];assert.deepEqual(medical,{raw_candidates:2,veterinary_exclusions:1,hospital:1,emergency:0,urgent:0,pharmacy:0});
});
test('first rich read failure is reported and prevents every downstream stage',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp24111-fail-fast-'));for(const file of ['overture-texas-spatial-authority.geoparquet','county-assignment-certification.parquet'])fs.writeFileSync(path.join(dir,file),'owner artifact');for(let i=0;i<expected.shards;i++)fs.writeFileSync(path.join(dir,`tx-${String(25+Math.floor(i/14)).padStart(2,'0')}-${String(93+i%14).padStart(3,'0')}.authority-matched.parquet`),'owner artifact');const calls=[];const schema=matchedColumns.map(column_name=>({column_name,column_type:column_name==='geometry'?"GEOMETRY('OGC:CRS84')":'VARCHAR'}));assert.throws(()=>execute({directory:dir,query:sql=>{calls.push(sql);if(sql.includes('DESCRIBE SELECT'))return schema;if(sql.includes('count(*)')&&!sql.includes('filename=true'))return [{row_count:1}];throw Error('root geometry binder failure');}}),error=>{assert.match(error.message,/Stage RICH_INPUT_READ failed/);assert.match(error.message,/root geometry binder failure/);return true;});assert.equal(calls.length,337);assert.equal(calls.filter(sql=>sql.includes('COPY')).length,0);for(const stage of normalizationStages(dir).slice(1))assert.equal(fs.existsSync(stage.artifact),false);});
test('explicit normalization CLI does not treat absent isolated artifacts as measured',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp24111-cli-absent-')),started=Date.now(),run=spawnSync(process.execPath,['tools/lp24111/normalize.mjs','--execute','--directory',dir],{encoding:'utf8'}),elapsed=Date.now()-started;assert.notEqual(run.status,0);assert.match(run.stderr,/requires authority, county assignment, and exactly 168 matched shards; detected authority=false assignment=false shards=0/);assert.ok(elapsed<5000,`absent-input check exceeded its bounded 5 second contract: ${elapsed}ms`);assert.deepEqual(fs.readdirSync(dir),[]);});
