import assert from 'node:assert/strict';
import test from 'node:test';
import { EXPECTED, FailClosed, RuntimeV2Provider, candidateShardIds, execute, guard, validateRecord, validateRelease, validateRequest } from '../tools/lp24117/non-production-provider-rehearsal.mjs';

const config={environment:'NON_PRODUCTION',mode:'NON_PRODUCTION',providerGate:'OFF'};

test('certified runtime-v2 release verifies every real shard',()=>{const release=validateRelease();assert.equal(release.manifestSha256,EXPECTED.manifestSha256);assert.equal(release.records,391772);assert.equal(release.manifest.shards.length,86);});
test('production environment, wrong mode, and enabled gate fail closed',()=>{for(const bad of [{...config,environment:'PRODUCTION'},{...config,mode:'PRODUCTION'},{...config,providerGate:'ON'}])assert.throws(()=>guard(bad),FailClosed);});
test('v2 forbids POI identity and rejects ungoverned request identity',()=>{assert.throws(()=>validateRecord({id:'x',displayName:'x',gridlyCategory:'OTHER',latitude:1,longitude:1,countyContextId:'x-tx',communityIdentity:{}}),/communityIdentity/);assert.throws(()=>validateRequest({originType:'DIRECT_COORDINATE',communityIdentity:{stableGovernedIdentity:'x'}}),/REQUEST_IDENTITY/);assert.throws(()=>validateRequest({originType:'GOVERNED_NON_PLACE',communityIdentity:{placeGeoid:'fabricated'}}),/REQUEST_IDENTITY/);});
test('selector and provider use bounded v2 shards, cache reuse, and deterministic results',()=>{const release=validateRelease();const request={latitude:30.0466,longitude:-94.8852,radiusMiles:25,originType:'CANONICAL_PLACE',countyContextId:'liberty-tx',communityIdentity:{placeGeoid:'4819432'}};assert.ok(candidateShardIds(release.manifest,request).length<=4);const provider=new RuntimeV2Provider(release);const first=provider.search(request),loads=provider.loads,second=provider.search(request);assert.equal(provider.loads,loads);assert.deepEqual(first.results,second.results);assert.ok(first.results.every(x=>x.distanceMiles<=25&&!('communityIdentity'in x)));});
test('actual acceptance cohorts, zero-result, legal, attribution, cache and rollback certify',()=>{const reports=execute(config);const certification=reports['lp24117-certification.json'];assert.equal(certification.phaseState,'PHASE_LP24117_NON_PRODUCTION_POI_PROVIDER_REHEARSAL_CERTIFIED');assert.equal(certification.providerInitialized,true);assert.equal(certification.searchExecuted,true);assert.equal(certification.productionProviderEligible,false);assert.equal(reports['lp24117-cohort-results.json'].zeroResult.status,'ZERO_RESULT');assert.ok(reports['lp24117-radius-search-certification.json'].maxFanout<=4);assert.equal(reports['lp24117-rollback-result.json'].rollbackPassed,true);assert.equal(reports['lp24117-negative-case-results.json'].cases.length,22);});
