const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const n = require('../js/gridlyHazardNormalization.js');
const labels = require('../js/gridlyConditionDisplayLabel.js');
const app = fs.readFileSync('js/app.js','utf8');
const now = Date.parse('2026-09-21T12:00:00Z');
function fn(name) {const start=app.indexOf('function '+name+'(');assert.ok(start>=0,name);const end=app.indexOf('\nfunction ',start+1);return app.slice(start,end);}
function providers(){const ctx={console,GridlyHazardNormalization:n,GRIDLY_CONFIG:{}};ctx.window=ctx;ctx.globalThis=ctx;vm.createContext(ctx);for(const file of ['js/gridlyDriveTexasProvider.js','js/gridlyWeatherProvider.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx);return ctx;}
test('A: community blockage cannot become an official closure through metadata or confirmations',()=>{const e=n.community({report_type:'road_closed',source:'txdot',authorityClass:'OFFICIAL_PUBLIC',advisory:'ROAD_CLOSED',severity:'severe',confirmations:100});assert.equal(e.condition,'ROAD_BLOCKED');assert.equal(e.authorityClass,'COMMUNITY_OBSERVATION');assert.equal(e.severity,'SEVERE');assert.equal(e.advisory,'USE_CAUTION');assert.equal(n.label(e),'Road appears blocked');});
test('B: trusted closure remains distinct from physical blockage',()=>{const e=n.road({condition:'Road Closure'});assert.equal(e.condition,'UNKNOWN');assert.equal(e.advisory,'ROAD_CLOSED');assert.equal(n.label(e),'Road Closed');const b=n.road({condition:'Road Blocked'});assert.equal(b.condition,'ROAD_BLOCKED');assert.notEqual(b.advisory,'ROAD_CLOSED');});
test('C: impassable community wording is observational',()=>{assert.equal(n.label(n.community({type:'road_impassable',advisory:'IMPASSABLE'})),'Road appears impassable');assert.notEqual(n.community({type:'road_impassable',advisory:'IMPASSABLE'}).advisory,'IMPASSABLE');});
test('D: missing and unrecognized severities remain UNKNOWN',()=>{for(const severity of [undefined,null,'','critical','unrated'])assert.equal(n.community({severity}).severity,'UNKNOWN');for(const severity of ['low','moderate','high','severe'])assert.equal(n.community({severity}).severity,severity.toUpperCase());});
test('E: authority and severity are independent of confidence',()=>{for(const confirmations of [0,1,999]){const e=n.community({type:'ice',confirmations});assert.equal(e.severity,'UNKNOWN');assert.equal(e.authorityClass,'COMMUNITY_OBSERVATION');}assert.equal(n.derived({source:'official',advisory:'ROAD_CLOSED'}).authorityClass,'SYSTEM_DERIVED');});
test('F: all canonical conditions and aliases round trip without rail/road confusion',()=>{for(const [alias,condition]of Object.entries(n.aliases))assert.equal(n.community({type:alias}).condition,condition,alias);assert.equal(n.community({type:'blocked'}).condition,'RAIL_CROSSING_CONDITION');});
test('G: winter minimum uses one winter family and safe labels',()=>{assert.equal(n.winterOptions.length,7);for(const option of n.winterOptions){const e=n.community({type:option.type});assert.equal(e.markerFamily,'winter');assert.match(n.label(e),/reported/);}assert.equal(n.label(n.community({type:'black_ice'})),'Possible black ice reported');});
test('H: active, updated, resolved, expired and cancelled lifecycle',()=>{for(const state of ['active','updated','resolved','expired','cancelled']){const e=n.community({status:state},now);assert.equal(e.lifecycle,state.toUpperCase());assert.equal(n.isActive(e,now),['active','updated'].includes(state));}assert.equal(n.community({status:'unrecognized'},now).lifecycle,'UNKNOWN');assert.equal(n.community({expires_at:'2026-09-20T12:00:00Z'},now).lifecycle,'EXPIRED');assert.equal(n.community({type:'hazard_cleared'},now).lifecycle,'RESOLVED');});
test('I: stale updates cannot reopen terminal evidence',()=>{const old=n.community({id:'a',status:'resolved',updated_at:'2026-09-20T12:00:00Z'},now);assert.equal(n.materiallyReopened(old,n.community({id:'a',status:'active'},now)),false);assert.equal(n.materiallyReopened(old,n.community({id:'a',status:'active',updated_at:'2026-09-21T11:00:00Z'},now)),true);assert.equal(n.materiallyReopened(old,n.community({id:'b',status:'active',updated_at:'2026-09-21T11:00:00Z'},now)),false);});
test('J: full line/polygon geometry survives and detached copies do not mutate provider data',()=>{for(const type of ['LineString','Polygon','MultiLineString','MultiPolygon']){const ring=[[1,2],[3,4],[3,2],[1,2]];const geometry={type,coordinates:type==='LineString'?[[1,2],[3,4]]:type==='MultiPolygon'?[[ring]]:[ring]};const e=n.road({geometry});assert.deepEqual(e.sourceGeometry,geometry);assert.notEqual(e.sourceGeometry,geometry);assert.equal(e.geometryPrecision,type.includes('Line')?'LINE':'POLYGON');}assert.equal(n.community({lat:0,lng:0}).geometryPrecision,'POINT');assert.equal(n.community({lat:null,lng:null}).geometryPrecision,'UNKNOWN');assert.equal(n.community({countyId:'liberty'}).geometryPrecision,'COUNTY_ONLY');assert.equal(n.community({placeGeoid:'abc'}).geometryPrecision,'PLACE_ONLY');});
test('K: NWS winter warning never creates observed ice',()=>{const e=n.weather({event:'Winter Storm Warning',severity:'Severe',messageType:'Update',certainty:'Likely'});assert.equal(e.condition,'NOT_APPLICABLE');assert.equal(e.weatherPhenomenon,'Winter Storm Warning');assert.equal(e.authorityClass,'OFFICIAL_PUBLIC');assert.equal(e.lifecycle,'UPDATED');assert.equal(e.confidence.sourceValue,'Likely');assert.equal(n.label(e),'Winter Storm Warning');});
test('L: source providers attach normalized projections and retain legacy geometry and identity',()=>{const p=providers();const geometry={type:'LineString',coordinates:[[-95,30],[-94,31]]};const r=p.gridlyDriveTexasProvider.normalizeRecords({features:[{properties:{GLOBALID:'road-1',condition:'Road Closure',route_name:'US 90'},geometry}]})[0];assert.equal(r.normalizedEvent.advisory,'ROAD_CLOSED');assert.equal(r.id,'road-1');assert.equal(JSON.stringify(r.sourceGeometry.coordinates),JSON.stringify(geometry.coordinates));assert.equal(JSON.stringify(r.normalizedEvent.sourceGeometry.coordinates),JSON.stringify(geometry.coordinates));const w=p.gridlyWeatherProvider.normalizeRecords({features:[{id:'weather-1',properties:{event:'Winter Storm Warning',status:'Actual',messageType:'Cancel'},geometry:{type:'Polygon',coordinates:[[[-95,30],[-94,30],[-94,31],[-95,30]]]}}]})[0];assert.equal(w.normalizedEvent.lifecycle,'CANCELLED');assert.equal(w.normalizedEvent.geometryPrecision,'POLYGON');assert.equal(w.event,'Winter Storm Warning');});
test('M: existing formatter supplies safety labels without disturbing official weather',()=>{assert.equal(labels.gridlyConditionDisplayLabel({sourceFamily:'COMMUNITY_REPORTS',canonicalKey:'road_closed'}),'Road appears blocked');assert.equal(labels.gridlyConditionDisplayLabel({sourceFamily:'COMMUNITY_REPORTS',canonicalKey:'bridge_overpass_icing'}),'Bridge or overpass icing reported');assert.equal(labels.gridlyConditionDisplayLabel({sourceFamily:'WEATHER',providerEvent:'Ice Storm Warning'}),'Ice Storm Warning');});
test('N: terminal hazards cannot enter Active Issues and UPDATED remains active',()=>{const ctx={GridlyHazardNormalization:n,HAZARD_TYPES:{ice:{}},RECENTLY_CLEARED_WINDOW_MINUTES:30};vm.createContext(ctx);for(const name of ['isActiveReportType','isClearedReportType','isRecentlyCleared','getIncidentLifecycleState'])vm.runInContext(fn(name),ctx);for(const status of ['resolved','expired','cancelled'])assert.notEqual(ctx.getIncidentLifecycleState({type:'ice',status},now),'active');assert.equal(ctx.getIncidentLifecycleState({type:'ice',status:'updated'},now),'active');});
test('O: KBYG preserves each winter observation and obstruction distinction',()=>{const ctx={GridlyHazardNormalization:n,gridlyTravelBriefCleanLine:x=>String(x)};vm.createContext(ctx);for(const name of ['gridlyTravelBriefCommunityCondition','gridlyTravelBriefCommunityConditionCopy','gridlyTravelBriefCommunityConditionLine'])vm.runInContext(fn(name),ctx);for(const type of ['road_closed','road_impassable','high_water',...n.winterOptions.map(o=>o.type)]){const c=ctx.gridlyTravelBriefCommunityCondition({type});const copy=ctx.gridlyTravelBriefCommunityConditionCopy(c);const text=ctx.gridlyTravelBriefCommunityConditionLine(c,copy,'Crosby');assert.match(text,/Crosby/);assert.ok(text.startsWith(n.label(n.community({type}))),type);}});
test('P: new types retain existing protocol whitelist; no normalized fields enter submissions',()=>{const protocol=fs.readFileSync('js/gridly-report-protocol.js','utf8');assert.match(protocol,/PROTOCOL_VERSION = 2/);assert.doesNotMatch(protocol,/normalizedEvent|authorityClass|geometryPrecision/);assert.match(app,/GridlyHazardNormalization\.community\(row\)/);assert.match(app,/data-v2-winter-hazards/);assert.match(app,/ice: "winter-road.svg"/);});

test('Q: official detour and community directive attempts use different wording',()=>{for(const advisory of ['DETOUR_REQUIRED','AVOID_AREA','RESTRICTED_ACCESS','ROAD_CLOSED','TRAFFIC_CONTROL']){const official=n.road({type:'construction',advisory});assert.equal(n.label(official),n.advisoryLabels[advisory]);const community=n.community({type:'construction',advisory});assert.notEqual(community.advisory,advisory);assert.notEqual(n.label(community),n.advisoryLabels[advisory]);}});
test('R: winter plus observed impassability preserves both meanings without a directive',()=>{const event=n.community({type:'ice',impassableObserved:true,advisory:'IMPASSABLE'});assert.equal(event.condition,'ICE');assert.equal(event.accessObservation,'ROAD_IMPASSABLE');assert.equal(n.label(event),'Ice reported; road appears impassable');assert.equal(event.advisory,'USE_CAUTION');});
test('S: marker filters retain winter geography options and require delay semantics in Delays',()=>{const ctx={GridlyHazardNormalization:n,activeGeoFilter:'nearby'};vm.createContext(ctx);vm.runInContext(fn('gridlyIncidentEligibleForMapMarker'),ctx);for(const type of n.winterOptions.map(o=>o.type)){const row={type,normalizedEvent:n.community({type})};for(const filter of ['nearby','town','county','all']){ctx.activeGeoFilter=filter;assert.equal(ctx.gridlyIncidentEligibleForMapMarker(row),true,filter+type);}ctx.activeGeoFilter='active-delays';assert.equal(ctx.gridlyIncidentEligibleForMapMarker(row),false);assert.equal(ctx.gridlyIncidentEligibleForMapMarker({...row,normalizedEvent:n.community({type,advisory:'EXPECT_DELAYS'})}),true);}for(const status of ['resolved','expired','cancelled'])assert.equal(ctx.gridlyIncidentEligibleForMapMarker({type:'ice',status}),false);});
test('T: unknown severity and legacy subtype rendering survive the ingest adapter',()=>{assert.match(fn('normalizeReports'),/severity: row.severity \|\| "unknown"/);const ctx={GridlyHazardNormalization:n,resolveOtherHazardSubtypeFromRecord:r=>r.subtype,getOtherHazardSubtypeLabel:s=>s, getHazardCategory:x=>x,formatRoadHazardCategoryLabel:x=>x};vm.createContext(ctx);vm.runInContext(fn('getGridlyHazardConsumerTitle'),ctx);assert.equal(ctx.getGridlyHazardConsumerTitle({type:'other_hazard',subtype:'downed_power_line',normalizedEvent:n.community({type:'other_hazard'})}),'downed_power_line');});

test('U: malformed spatial and enum inputs do not invent precision or values',()=>{for(const type of ['__proto__','constructor','unrecognized']){const event=n.community({type,severity:type,geometry:{type,coordinates:[1,2]}});assert.equal(event.condition,'UNKNOWN');assert.equal(event.severity,'UNKNOWN');assert.equal(event.geometryPrecision,'UNKNOWN');}assert.equal(n.community({geometry:{type:'Polygon',coordinates:[[[1,2],[2,3]]]}}).geometryPrecision,'UNKNOWN');for(const status of ['needs_confirmation','confirmed','unconfirmed'])assert.equal(n.community({status}).lifecycle,'ACTIVE');});

test('V: ingestion recognizes legacy winter aliases without changing rail report classification',()=>{const HAZARD_TYPES=Object.fromEntries(['ice','black_ice_suspected','bridge_overpass_icing','road_blocked','road_impassable','crash'].map(k=>[k,{}]));const ctx={GridlyHazardNormalization:n,HAZARD_TYPES};vm.createContext(ctx);vm.runInContext(fn('gridlyNormalizeSharedRoadHazardType'),ctx);for(const [alias,type] of [['icy','ice'],['icy road','ice'],['black ice','black_ice_suspected'],['blocked roadway','road_blocked'],['wreck','crash'],['blocked','blocked']])assert.equal(ctx.gridlyNormalizeSharedRoadHazardType(alias),type);});
