import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {identity,references,reports,verify} from '../tools/lp24112c/final-counsel-handoff.mjs';
import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {extractFoursquareNotice,crossCheckOverture,ingest,FOURSQUARE_URL} from '../tools/lp24112c/ingest-authoritative-notice.mjs';
const r=reports();
test('exact sources and release identity are locked',()=>{const n=r['lp24112c-foursquare-notice-provenance.json'];assert.equal(n.sourceUrl,'https://opensource.foursquare.com/places-notice-txt/');assert.equal(n.sourceAuthority,'FOURSQUARE_OFFICIAL');assert.equal(n.overtureRecordedChangeDate,'2026-03-18');assert.equal(references.apache,'https://www.apache.org/licenses/LICENSE-2.0');assert.deepEqual(identity,{authorityReleaseId:'lp24111-d5-standalone-2026-08-28',runtimeSchemaVersion:'gridly.poi.runtime.v1',reviewedSourceInventoryHash:'a9d7a77b964af35fcb21ad3cd061ceb1e1a33ae4dc5091a25a119bada92cec13'});});
test('blocked acquisition never fabricates NOTICE provenance',()=>{const n=r['lp24112c-foursquare-notice-provenance.json'];assert.equal(fs.existsSync(new URL('../legal/third-party/foursquare/NOTICE.txt',import.meta.url)),false);assert.equal(n.noticeSha256,null);assert.equal(n.noticeBytes,null);assert.equal(n.provenanceStatus,'NOT_ACQUIRED');assert.equal(n.legalApprovalImplied,false);});
test('license exposure conserves runtime population',()=>{const e=r['lp24112c-final-license-evidence.json'];assert.deepEqual(e.combinations.map(x=>x.count),[355925,23248,12599]);assert.equal(e.combinations.reduce((n,x)=>n+x.count,0),391772);assert.equal(e.apacheCdlaPoiCount,23248);});
test('all counsel decisions and approvals remain unresolved',()=>{const m=r['lp24112c-approval-manifest-template.json'];assert.equal(r['lp24112c-counsel-decision-matrix.json'].decisions.length,16);assert.ok(r['lp24112c-counsel-decision-matrix.json'].decisions.every(x=>x.status==='COUNSEL_DECISION_REQUIRED'));assert.equal(m.approvedAt,null);assert.equal(m.approvedBy,null);assert.equal(m.legalClearanceStatus,'NOT_APPROVED');assert.equal(m.providerGateEligible,false);for(const k of ['resultsAttributionApproved','dataSourcesPageApproved','cdlaNoticeApproved','apacheNoticeApproved','foursquareNoticeApproved','cc0NoticeReviewed','censusAcknowledgementApproved'])assert.equal(m[k],false);});
test('absolute runtime boundary remains closed',()=>{const c=r['lp24112c-certification.json'];for(const k of ['runtimeActive','deployed','productionSupabaseMutation','overtureRefetch','osmMerged','upstreamDataRerun','normalization','shardRegeneration','phoneTesting'])assert.equal(c[k],false);assert.equal(c.productionPoiSearch,'NOT_LAUNCHED_NOT_CERTIFIED');assert.equal(c.targetAchieved,false);assert.doesNotThrow(verify);});
test('return template contains no fabricated identity',()=>{const t=fs.readFileSync(new URL('../LP241.12C-COUNSEL-DECISION-RETURN-TEMPLATE.md',import.meta.url),'utf8');assert.match(t,/Counsel name: \[COUNSEL TO COMPLETE\]/);assert.doesNotMatch(t,/Counsel name: [^\[]/);});

const noticeHtml='<!doctype html><html><body><header>SITE CHROME</header><article><h1>Foursquare OS Places NOTICE</h1><p>Copyright &amp; notice wording.</p><ul><li>Apache 2.0</li></ul></article><footer>FOOTER CHROME</footer></body></html>';
const overtureHtml=`<!doctype html><html><body><main><h1>Attribution</h1><p>Foursquare</p><p>Apache 2.0</p><p>Foursquare data transformed to Overture schema</p><p>Changed: 2026-03-18</p><a href="${FOURSQUARE_URL}">NOTICE</a></main></body></html>`;
test('snapshot ingestion fails closed for missing and malformed inputs',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp24112c-'));assert.throws(()=>ingest({foursquareHtml:path.join(dir,'missing'),overtureHtml:path.join(dir,'also-missing'),outputRoot:dir,write:false}),/FOURSQUARE_SNAPSHOT_MISSING/);fs.writeFileSync(path.join(dir,'f.html'),'bad');fs.writeFileSync(path.join(dir,'o.html'),overtureHtml);assert.throws(()=>ingest({foursquareHtml:path.join(dir,'f.html'),overtureHtml:path.join(dir,'o.html'),outputRoot:dir,write:false}),/FOURSQUARE_SNAPSHOT_MALFORMED/);});
test('ambiguous NOTICE extraction fails closed',()=>{assert.throws(()=>extractFoursquareNotice(`<html><body>${noticeHtml.match(/<article>[\s\S]*<\/article>/)[0]}${noticeHtml.match(/<article>[\s\S]*<\/article>/)[0]}</body></html>`),/FOURSQUARE_NOTICE_EXTRACTION_AMBIGUOUS/);});
test('NOTICE extraction is deterministic, nonempty, and excludes site chrome',()=>{const a=extractFoursquareNotice(noticeHtml),b=extractFoursquareNotice(noticeHtml);assert.equal(a,b);assert.ok(a.length>0);assert.match(a,/Copyright & notice wording/);assert.doesNotMatch(a,/SITE CHROME|FOOTER CHROME/);assert.equal(crypto.createHash('sha256').update(a).digest('hex'),crypto.createHash('sha256').update(b).digest('hex'));});
test('owner snapshot exact bytes and portable hashes are bound separately',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp24112c-')),f=path.join(dir,'f.html'),o=path.join(dir,'o.html');fs.writeFileSync(f,noticeHtml);fs.writeFileSync(o,overtureHtml);const p=ingest({foursquareHtml:f,overtureHtml:o,outputRoot:dir,write:true});assert.equal(p.sourceSnapshotBytes,Buffer.byteLength(noticeHtml));assert.equal(p.sourceSnapshotSha256,crypto.createHash('sha256').update(Buffer.from(noticeHtml)).digest('hex'));assert.notEqual(p.sourceSnapshotSha256,p.noticeSha256);assert.equal(p.sourceUrl,FOURSQUARE_URL);assert.equal(p.sourceAuthority,'FOURSQUARE_OFFICIAL');assert.equal(p.provenanceStatus,'ACQUIRED_FROM_AUTHORITATIVE_SOURCE');assert.equal(p.overtureAttribution.crossCheck.status,'VERIFIED_FROM_OWNER_AUTHORITATIVE_SNAPSHOT');assert.deepEqual(p.overtureAttribution.crossCheck.facts,{provider:'Foursquare',license:'Apache 2.0',transformation:'Foursquare data transformed to Overture schema',changed:'2026-03-18',noticeReference:FOURSQUARE_URL});});
test('Overture cross-check requires every snapshot fact',()=>{assert.doesNotThrow(()=>crossCheckOverture(overtureHtml));assert.throws(()=>crossCheckOverture(overtureHtml.replace('2026-03-18','2025-01-01')),/OVERTURE_ATTRIBUTION_CROSS_CHECK_FAILED/);});
test('ingestion implementation has no network or forbidden mutation path',()=>{const source=fs.readFileSync(new URL('../tools/lp24112c/ingest-authoritative-notice.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/\bfetch\s*\(|https?\.request|child_process|supabase|openstreetmap|phone/i);});
