const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),cp=require('node:child_process'),crypto=require('node:crypto');
const r=require('../js/gridlyMarkerRegistry.js'),n=require('../js/gridlyHazardNormalization.js'),manifest=require('../reports/lp24447-png-source-manifest.json'),app=fs.readFileSync('js/app.js','utf8');
function fn(name){const a=app.indexOf('function '+name+'(');assert.ok(a>=0,name);return app.slice(a,app.indexOf('\n}',a)+2);}
const ctx={GridlyMarkerRegistry:r,GridlyHazardNormalization:n,GRIDLY_WINTER_MARKER_ASSETS:r.winterAssets,GRIDLY_PRODUCTION_MARKER_CATEGORY_ASSETS:r.assetMap,GRIDLY_PRODUCTION_MARKER_BASE_PATH:r.basePath,getHazardCategory:x=>x,resolveOtherHazardSubtypeFromRecord:x=>x.subtype||'',gridlyLp019SafeText:String};vm.createContext(ctx);for(const name of ['getGridlyProductionMarkerCategory','getGridlyProductionMarkerAsset','gridlyLp019OfficialCategory','gridlyOfficialRoadwayPresentationCategory'])vm.runInContext(fn(name),ctx);
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
test('all 28 approved hazard files and 3 navigation files exist with exact ZIP bytes',()=>{const {unzipSync}=require('fflate'),archives=new Map();assert.equal(Object.keys(r.entries).length,28);assert.equal(Object.keys(r.navigation).length,3);for(const m of manifest){if(fs.existsSync(m.archive)){if(!archives.has(m.archive))archives.set(m.archive,unzipSync(fs.readFileSync(m.archive)));assert.equal(sha(fs.readFileSync(m.path)),sha(archives.get(m.archive)[m.entry]),m.file);}assert.equal(sha(fs.readFileSync(m.path)),m.sha256);}});
test('28 numbered filenames are completely represented without duplicate visual definitions',()=>{assert.equal(new Set(Object.values(r.entries).map(e=>e.asset)).size,28);for(let i=1;i<=28;i++)assert.ok(Object.values(r.entries).some(e=>e.asset.startsWith(String(i).padStart(2,'0')+'-')));});
for(const [input,file]of [['ice','01-icy-road.png'],['reduced_visibility','06-reduced-visibility.png'],['road_impassable','12-road-appears-blocked.png'],['fallen_tree','11-debris-in-road.png'],['crash','09-crash-wreck.png'],['road_closed','17-official-road-closed.png'],['road_blocked','12-road-appears-blocked.png'],['rail_blockage_delay','23-reported-crossing-delay.png'],['blocked_crossing','24-blocked-crossing.png'],['crossing_infrastructure','25-crossing-location.png'],['txdot_other','28-travel-advisory.png'],['unknown_value','16-other-hazard.png']])test(input+' resolves to '+file,()=>assert.equal(r.resolve(input).asset,file));
test('impassable has one blocked presentation while original condition survives',()=>{const e=n.community({type:'road_impassable'});assert.equal(e.condition,'ROAD_IMPASSABLE');assert.equal(e.provenance.rawType,'road_impassable');assert.equal(n.label(e),'Road Appears Blocked');assert.doesNotMatch(app,/data-hazard-type="road_impassable"|value: "road_impassable"|type: "road_impassable"/);});
test('roadway incident has no standalone asset and cannot swallow a known crash',()=>{assert.equal(r.entries.txdot_incident,undefined);assert.equal(r.resolve('txdot_incident').asset,'28-travel-advisory.png');assert.equal(r.resolve(ctx.gridlyOfficialRoadwayPresentationCategory({category:'Roadway Incident',type:'crash'})).asset,'09-crash-wreck.png');});
test('all navigation types resolve separately and unknown navigation fails closed',()=>{for(const [key,file]of [['current_location','current-location.png'],['trip_start','trip-start.png'],['trip_destination','trip-destination.png']])assert.equal(r.resolveNavigation(key).asset,file);assert.equal(r.resolveNavigation('unknown'),null);assert.ok(app.includes('getGridlyNavigationMarkerIcon("current_location")'));assert.ok(app.includes('getGridlyNavigationMarkerIcon("trip_destination")'));assert.ok(app.includes('isDestination ? "trip_destination" : "trip_start"'));});
test('community metadata cannot confer the official closure symbol',()=>{for(const type of ['road_closed','road_closure','closure','txdot_closure']){const record={report_type:type,source:'official',normalizedEvent:n.community({type,authorityClass:'OFFICIAL_PUBLIC'})};assert.equal(ctx.getGridlyProductionMarkerCategory(record),'road_blocked');assert.equal(record.normalizedEvent.authorityClass,'COMMUNITY_OBSERVATION');}assert.equal(ctx.gridlyOfficialRoadwayPresentationCategory({category:'Road Closure'}),'txdot_closure');});
test('all winter aliases and picker choices have explicit mappings',()=>{assert.equal(new Set(Object.values(r.winterAssets)).size,7);const old=require('../reports/lp24447-marker-inventory.json');for(const o of [...old.picker.road,...old.picker.other])assert.ok(r.aliases[o.value],o.value);for(const alias of Object.keys(n.aliases))assert.ok(r.aliases[alias],alias);});
test('normalization data/authority/lifecycle/geometry identical to starting implementation',()=>{const oldSource=cp.execFileSync('git',['show','f8c98922:js/gridlyHazardNormalization.js'],{encoding:'utf8'}),old={};vm.createContext(old);vm.runInContext(oldSource,old);for(const type of [...Object.keys(n.aliases),'unknown'])for(const boundary of ['community','road']){const row={type,advisory:'ROAD_CLOSED',source:'official',status:'active',lat:30,lng:-95,created_at:'2026-09-22T00:00:00Z'};assert.deepEqual(JSON.parse(JSON.stringify(n[boundary](row,1))),JSON.parse(JSON.stringify(old.GridlyHazardNormalization[boundary](row,1))));}});
test('provider/protocol sources are unchanged',()=>{for(const path of ['js/gridlyDriveTexasProvider.js','js/gridlyWeatherProvider.js','js/gridly-report-protocol.js','js/gridly-ugc-compliance.js'])assert.equal(fs.readFileSync(path,'utf8').replace(/\r\n/g,'\n'),cp.execFileSync('git',['show','f8c98922:'+path],{encoding:'utf8',maxBuffer:30e6}).replace(/\r\n/g,'\n'));});
test('rejected LP244.47 SVGs have no active source mapping and have been retired',()=>{assert.equal(fs.existsSync('assets/markers/unified') ? fs.readdirSync('assets/markers/unified').filter(f=>f.endsWith('.svg')).length : 0,0);assert.ok(!r.basePath.includes('unified'));for(const e of Object.values(r.entries)){assert.match(e.asset,/\.png$/);assert.equal(e.size,64);const bytes=fs.readFileSync(r.basePath+e.asset);assert.equal(bytes.readUInt32BE(16),e.width);assert.equal(bytes.readUInt32BE(20),e.height);}});

test('dimension audit handles unloaded PNGs with their individual source dimensions',()=>{const audit={GridlyMarkerRegistry:r,GRIDLY_PRODUCTION_MARKER_ASSETS:Object.values(r.entries).map(e=>e.asset),GRIDLY_PRODUCTION_MARKER_BASE_PATH:r.basePath,GRIDLY_PRODUCTION_MARKER_DIMENSION_STATE:new Map(),queueGridlyProductionMarkerDimensionProbe:()=>{},getGridlyProductionMarkerRenderedImageDimensions:()=>null};vm.createContext(audit);vm.runInContext(fn('buildGridlyProductionMarkerAssetDimensionAudit'),audit);const rows=audit.buildGridlyProductionMarkerAssetDimensionAudit(null);assert.equal(rows.length,28);assert.ok(rows.every(row=>row.expectedSizePass));});

test('generic community wrappers preserve a recognized crash visual',()=>{for(const type of ['other_hazard','roadway_incident','unknown'])assert.equal(ctx.getGridlyProductionMarkerCategory({report_type:type,normalizedEvent:n.community({type:'crash'})}),'crash');});
