import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {verify} from '../tools/lp24111/manufacture.mjs';
const sql=()=>fs.readFileSync('tools/lp24111/extract-texas.sql','utf8');
const richCli=path.resolve('tools/lp24111/rich-manufacture.mjs');
const runRich=args=>spawnSync(process.execPath,[richCli,...args],{encoding:'utf8'});

test('owner statewide evidence certifies exact per-ID conservation',()=>{const a=verify(),c=a['county-assignment-certification.json']; assert.equal(c.authorityIds,1462815); assert.equal(c.uniqueIds,1462815); assert.equal(c.uniqueCountyAssignments,1462815); assert.equal(c.totalCountyIntersections,1462815); assert.equal(c.unassigned,0); assert.equal(c.boundaryMulti,0); assert.equal(c.zeroCountLoss,true); assert.equal(c.exactUniqueIdConservation,'CERTIFIED');});
test('owner-certified rich shard conservation is recorded without inventing normalization',()=>{const a=verify(),r=a['rich-authority-conservation.json'],n=a['normalization-summary.json'];assert.deepEqual([r.inputShardRows,r.uniqueIds,r.crossShardDuplicateIds,r.extraDuplicateRows,r.maximumShardOccurrencesPerId,r.missingAuthorityIds,r.outsideAuthorityIds],[1462893,1462815,52,78,4,0,0]);assert.equal(r.conservationPassed,true);assert.equal(n.normalizedUniquePois,null);assert.equal(n.eligibleDestinations,null);assert.equal(a['certification.json'].productViability,'OVERTURE_TEXAS_POI_AUTHORITY_NOT_YET_PRODUCT_VIABLE');});
test('launcher and staged CRS authority are explicit',()=>{const ps=fs.readFileSync('tools/lp24111/extract-texas.ps1','utf8'); assert.match(ps,/Get-Content -Raw/); assert.match(ps,/\$program \| & \$DuckDb/); assert.doesNotMatch(ps,/\.read/); assert.match(sql(),/ST_Transform\(geom, 'EPSG:4269', 'OGC:CRS84', always_xy := true\)/); assert.match(sql(),/BOUNDARY_MULTI_INTERSECTION/);});
test('remote extraction is lightweight and literal-pruned',()=>{assert.match(sql(),/SELECT id, geometry, bbox/); assert.doesNotMatch(sql(),/SELECT p\.\*/i); assert.match(sql(),/bbox\.xmin <= -93\.5/); assert.match(sql(),/PERFORMANCE|literal/i);});
test('quality dimensions are independent',()=>{const a=verify(); assert.ok(a['category-coverage.json'].mapping.humanMedicalExclusions.includes('animal_hospital')); assert.ok(a['category-coverage.json'].mapping.nonDestinationExclusions.includes('structure_and_geography')); assert.equal(a['spatial-metadata-conflicts.json'].classification,'SPATIAL_METADATA_CONFLICT'); assert.match(a['confidence-analysis.json'].policy,/NO_CUTOFF/); assert.ok(a['duplicate-child-poi-analysis.json'].classifications.includes('CHILD_POI'));});
test('governed PLACE and non-PLACE coverage remain represented',()=>{const a=verify(); assert.equal(a['community-coverage.json'].canonicalPlaceAccounted,1859); assert.equal(a['governed-non-place-coverage.json'].governedInventory.total,29); assert.equal(a['lp24110-cohort-reconciliation.json'].communityCount,22);});
test('runtime and deployment remain untouched',()=>{const a=verify(); assert.equal(a['certification.json'].productionPoiSearch,'NOT_LAUNCHED_NOT_CERTIFIED'); assert.equal(a['refresh-pipeline.json'].deployIncluded,false); assert.doesNotMatch(fs.readFileSync('js/app.js','utf8'),/lp24111|overture-texas-places/i);});
test('rich shard plan is literal, bounded, projected, and locally authority-matched',async()=>{const a=verify(),m=a['rich-shard-manifest.json']; const {shardSql,validatePlan}=await import('../tools/lp24111/rich-manufacture.mjs'); assert.equal(m.shardCount,168); assert.equal(m.countyHardWalls,false); assert.equal(validatePlan(m),true); const query=shardSql(m.rows[0]); assert.match(query,/bbox\.xmin <= -106/); assert.match(query,/INNER JOIN read_parquet/); assert.doesNotMatch(query,/SELECT\s+\*/i); assert.doesNotMatch(query,/app\.js|deploy|supabase/i);});
test('Phase D unmeasured results remain explicit',()=>{const a=verify(); assert.equal(a['rich-field-extraction.json'].executionState,'NOT_EXECUTED'); assert.equal(a['package-size-model.json'].measurements.compressedBytes,null); assert.equal(a['community-coverage.json'].executionState,'NOT_EXECUTED'); assert.equal(a['certification.json'].executiveResult,'PHASE_D_NOT_EXECUTED_INPUT_ARTIFACTS_UNAVAILABLE');});

const fixture=async()=>{
 const m=await import('../tools/lp24111/rich-manufacture.mjs'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'lp24111-rich-')),authority=path.join(dir,'authority.parquet');fs.writeFileSync(authority,'authority');
 const shards=[{shardId:'tx-33-101',bounds:{xmin:-101,xmax:-100,ymin:33,ymax:34}},{shardId:'tx-33-100',bounds:{xmin:-100,xmax:-99,ymin:33,ymax:34}}];
 const query=sql=>sql.startsWith('DESCRIBE')?m.fields.map(column_name=>({column_name})):sql.includes('outsideCount')?[{rowCount:4,outsideCount:0}]:[{rowCount:2,duplicateCount:0,nonAuthorityCount:0}];
 const run=sql=>{const match=sql.match(/TO '([^']+)'/);if(match)fs.writeFileSync(match[1],'parquet');return [];};
 return {m,dir,authority,shards,query,run,progressPath:path.join(dir,'progress.json')};
};
test('rich CLI selects exactly one shard or an explicit ordered set and rejects unknown IDs',async()=>{const {m,shards}=await fixture();const manifest={rows:shards};assert.deepEqual(m.selectShards(manifest,m.parseCli(['--execute','--shard','tx-33-101']).ids).map(x=>x.shardId),['tx-33-101']);assert.deepEqual(m.selectShards(manifest,m.parseCli(['--execute','--shards','tx-33-100,tx-33-101']).ids).map(x=>x.shardId),['tx-33-100','tx-33-101']);assert.throws(()=>m.selectShards(manifest,['tx-0-0']),/Unknown shard ID/);});
test('rich ESM entrypoint invokes the CLI without activating execution on import',()=>{const plan=runRich(['--plan']);assert.equal(plan.status,0,plan.stderr);assert.match(plan.stdout,/validated 168 literal rich-field shards; selected 168 \(not executed\)/);const selected=runRich(['--plan','--shards','tx-33-101,tx-33-100']);assert.equal(selected.status,0,selected.stderr);assert.match(selected.stdout,/selected 2 \(not executed\)/);const invalid=runRich(['--execute','--shard','DOES-NOT-EXIST']);assert.notEqual(invalid.status,0);assert.match(invalid.stderr,/Unknown shard ID\(s\): DOES-NOT-EXIST/);const imported=spawnSync(process.execPath,['--input-type=module','--eval',`import ${JSON.stringify(new URL('../tools/lp24111/rich-manufacture.mjs',import.meta.url).href)}`],{encoding:'utf8'});assert.equal(imported.status,0,imported.stderr);assert.equal(imported.stdout,'');assert.equal(imported.stderr,'');const source=fs.readFileSync(richCli,'utf8');assert.match(source,/pathToFileURL\(process\.argv\[1\]\)\.href/);assert.doesNotMatch(source,/`file:\/\/\$\{process\.argv\[1\]\}`/);});
test('complete rich artifacts skip and remote-only artifacts resume matching',async()=>{const f=await fixture(),p1=f.m.artifactPaths(f.shards[0].shardId,f.dir),p2=f.m.artifactPaths(f.shards[1].shardId,f.dir);fs.writeFileSync(p1.remote,'x');fs.writeFileSync(p1.matched,'x');fs.writeFileSync(p2.remote,'x');const calls=[];const result=await f.m.executeShards(f.shards,{...f,outputDirectory:f.dir,run:sql=>{calls.push(sql);return f.run(sql);},now:()=> '2026-08-28T00:00:00.000Z',clock:(()=>{let n=0;return()=>++n;})()});assert.equal(result[f.shards[0].shardId].status,'COMPLETE_EXISTING');assert.equal(result[f.shards[1].shardId].status,'REMOTE_REUSED');assert.equal(calls.length,1);assert.match(calls[0],/INNER JOIN/);});
test('failure records measurements and preserves earlier shard success',async()=>{const f=await fixture();let calls=0;await assert.rejects(f.m.executeShards(f.shards,{...f,outputDirectory:f.dir,run:sql=>{if(++calls===3)throw Error('controlled failure');return f.run(sql);},now:()=> '2026-08-28T00:00:00.000Z',clock:(()=>{let n=100;return()=>n+=5;})()}),/tx-33-100/);const progress=JSON.parse(fs.readFileSync(f.progressPath));assert.equal(progress.shards['tx-33-101'].status,'MATCHED');assert.equal(progress.shards['tx-33-100'].status,'FAILED');assert.equal(progress.shards['tx-33-101'].remoteRowCount,4);assert.equal(progress.shards['tx-33-101'].authorityMatchedRowCount,2);assert.equal(progress.shards['tx-33-101'].releaseId,'2026-08-19.0');assert.equal(progress.shards['tx-33-101'].projectionFieldCount,f.m.fields.length);assert.ok(fs.existsSync(f.m.artifactPaths('tx-33-101',f.dir).matched));});
test('invalid rich artifact is classified without an implicit rebuild',async()=>{const f=await fixture(),p=f.m.artifactPaths(f.shards[0].shardId,f.dir);fs.writeFileSync(p.remote,'x');await assert.rejects(f.m.executeShards([f.shards[0]],{...f,outputDirectory:f.dir,query:sql=>sql.startsWith('DESCRIBE')?[]:f.query(sql)}),/missing field/);const progress=JSON.parse(fs.readFileSync(f.progressPath));assert.equal(progress.shards['tx-33-101'].status,'INVALID_EXISTING_ARTIFACT');});
test('dense candidate audit uses measured rows and deterministic ties only',async()=>{const {m}=await fixture();assert.deepEqual(m.denseCandidates({shards:{b:{shardId:'b',remoteRowCount:8},a:{shardId:'a',remoteRowCount:8},z:{shardId:'z',remoteRowCount:null}}}).map(x=>x.shardId),['a','b']);});
