import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildPlan, classifyProviderResult, verifyPlan} from '../tools/lp2416/statewide-address-certification.mjs';

const plan=buildPlan();
test('254 governed, unique, deterministic, privacy-safe county fixtures fail closed',()=>{assert.equal(verifyPlan(plan),true);assert.equal(new Set(plan.fixtures.map(x=>x.countyFips)).size,254);assert.ok(plan.fixtures.every(x=>x.countyName&&x.expectedCountyId&&x.queryStrategy==='GOVERNED_PUBLIC_COUNTY_COURTHOUSE'));assert.ok(plan.fixtures.every(x=>!/^\s*County Courthouse, Texas\s*$/i.test(x.privacySafeSeedQuery)));});
test('provider outcomes require valid coordinates and governed county identity',()=>{const row=plan.fixtures[0], base={providerBoundary:'gridly',ok:true,results:[{latitude:31.8,longitude:-95.5,address:{county:'Anderson County'}}]};assert.equal(classifyProviderResult(row,base),'PASS');assert.equal(classifyProviderResult(row,{...base,results:[{...base.results[0],address:{county:'Andrews County'}}]}),'WRONG_COUNTY');assert.equal(classifyProviderResult(row,{...base,results:[{...base.results[0],latitude:null}]}),'INVALID_COORDINATES');assert.equal(classifyProviderResult(row,{providerBoundary:'gridly',ok:false,status:'no_results',results:[]}),'NO_RESULT');assert.equal(classifyProviderResult(row,null),'PROVIDER_UNAVAILABLE');});
test('tracked artifacts agree, visual cohort is fixed, and every exception is surfaced',()=>{const tracked=JSON.parse(fs.readFileSync('LP241-STATEWIDE-ADDRESS-FIXTURE-PLAN.json'));assert.deepEqual(tracked,plan);const cohort=JSON.parse(fs.readFileSync('reports/lp2416/visual-cohort.json'));assert.equal(cohort.fixed,true);assert.equal(cohort.rows.length,12);assert.ok(cohort.rows.every(x=>x.riskClass));assert.deepEqual(cohort.rows.map(x=>x.countyFips),['48071','48073','48113','48141','48201','48229','48355','48375','48403','48439','48453','48465']);const ledger=JSON.parse(fs.readFileSync('reports/lp2416/exception-ledger.json'));assert.equal(ledger.count,254);assert.ok(ledger.exceptions.every(x=>x.classification==='NOT_EXECUTED'));});
