const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const cp=require('node:child_process');
const n=require('../js/gridlyHazardNormalization.js');
const app=fs.readFileSync('js/app.js','utf8');
function fn(name){const start=app.indexOf('function '+name+'(');assert.ok(start>=0,name);return app.slice(start,app.indexOf('\nfunction ',start+1));}
const registry=require('../js/gridlyMarkerRegistry.js');
const mapping=registry.winterAssets;
const ctx={GridlyMarkerRegistry:registry,GridlyHazardNormalization:n,GRIDLY_WINTER_MARKER_ASSETS:mapping,GRIDLY_PRODUCTION_MARKER_BASE_PATH:registry.basePath,GRIDLY_PRODUCTION_MARKER_CATEGORY_ASSETS:{other_hazard:'other-hazard.png',flooding:'water-over-road.png'},getHazardCategory:x=>x,resolveOtherHazardSubtypeFromRecord:()=>null};vm.createContext(ctx);vm.runInContext(fn('getGridlyProductionMarkerCategory'),ctx);vm.runInContext(fn('getGridlyProductionMarkerAsset'),ctx);
test('seven winter conditions resolve seven real, distinct approved PNG assets',()=>{assert.equal(Object.keys(mapping).length,7);assert.equal(new Set(Object.values(mapping)).size,7);for(const [condition,file]of Object.entries(mapping)){const asset=ctx.getGridlyProductionMarkerAsset(condition);assert.equal(asset.assetName,file);assert.ok(fs.existsSync(asset.assetPath));const png=fs.readFileSync(asset.assetPath);assert.equal(png.subarray(1,4).toString(),'PNG');assert.doesNotMatch(file,/water|flood|other-hazard/);}});
test('all picker choices preserve their normalized condition and map to distinct markers',()=>{for(const option of n.winterOptions){const event=n.community({type:option.type});assert.equal(event.markerFamily,'winter');const category=ctx.getGridlyProductionMarkerCategory({type:option.type,normalizedEvent:event});assert.equal(ctx.getGridlyProductionMarkerAsset(category).assetName,mapping[event.condition]);}});
test('legacy icy aliases and grouped render records keep the winter subtype',()=>{for(const alias of ['ice','icy','icy road','icy roads']){assert.equal(n.community({type:alias}).condition,'ICE');assert.equal(ctx.getGridlyProductionMarkerAsset(ctx.getGridlyProductionMarkerCategory({report_type:alias})).assetName,mapping.ICE);}for(const option of n.winterOptions){const category=ctx.getGridlyProductionMarkerCategory({type:'debris',report_type:option.type});assert.equal(ctx.getGridlyProductionMarkerAsset(category).assetName,mapping[n.community({type:option.type}).condition]);}});
test('popup wording retains observation/uncertainty; icon does not confer authority',()=>{const expected=['Ice reported','Possible black ice reported','Bridge or overpass icing reported','Snow-covered road reported','Sleet or freezing rain reported','Reduced visibility reported','Winter road hazard reported'];n.winterOptions.forEach((option,i)=>{const event=n.community({type:option.type,source:'official',confirmations:99});assert.equal(n.label(event),expected[i]);assert.equal(event.authorityClass,'COMMUNITY_OBSERVATION');});});
test('legacy ice/water artwork scaling alias is removed without changing severity code',()=>{const css=fs.readFileSync('css/styles.css','utf8');assert.doesNotMatch(css,/\[data-marker-category="standing_water"\], \[data-marker-category="ice"\]/);assert.match(css,/\[data-marker-category="standing_water"\]\)\s*\{\s*--gridly-production-marker-artwork-scale: 1/);const baseline=cp.execFileSync('git',['show','78241632:js/app.js'],{encoding:'utf8',maxBuffer:30e6});for(const name of ['getGridlyIncidentSeverity','getGridlyIncidentVisualState','getIncidentLifecycleState','gridlyTravelBriefCommunityCondition','buildReportHazardSurfaceHtml','getHazardClusterKey','getUnifiedIncidentRenderKey']){const start=baseline.indexOf('function '+name+'('),end=baseline.indexOf('\nfunction ',start+1);assert.equal(app.includes(baseline.slice(start,end)),true,name+' unchanged');}});
test('protected protocol/admission/retention sources remain unchanged; normalization contract covered in LP244.47',()=>{for(const file of ['js/gridly-report-protocol.js','js/gridly-ugc-compliance.js','js/gridlyWeatherProvider.js','js/gridlyDriveTexasProvider.js']){assert.equal(fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n'),cp.execFileSync('git',['show','78241632:'+file],{encoding:'utf8',maxBuffer:30e6}).replace(/\r\n/g,'\n'),file);}});

test('official roadway icon keeps source badge while resolving each winter asset',()=>{Object.assign(ctx,{GRIDLY_PRODUCTION_MARKER_DISPLAY_SIZE:64,gridlyOfficialRoadwayPresentationCategory:()=> 'txdot_flooding',getGridlyProductionMarkerAnchor:()=>[32,61],getGridlyProductionMarkerPopupAnchor:()=>[0,-55],getGridlyMarkerVisualConfig:()=>({className:'existing-official-style',priority:3}),getGridlyMarkerHierarchyConfig:()=>({emphasisLevel:'moderate',priorityRank:3,visualWeight:'standard'}),gridlyBuildVisualPriorityMetadata:()=>({attributes:'',className:'existing-source-style'}),sanitizeText:String,markGridlyProductionMarkerAssetLoad:()=>{},L:{divIcon:options=>options}});vm.runInContext(fn('gridlyBuildOfficialRoadwayProductionMarkerIcon'),ctx);for(const option of n.winterOptions){const icon=ctx.gridlyBuildOfficialRoadwayProductionMarkerIcon({category:option.type,normalizedEvent:n.road({type:option.type})});assert.ok(icon.html.includes(mapping[n.community({type:option.type}).condition]));assert.match(icon.html,/gridly-official-roadway-badge/);assert.match(icon.html,/>TX<\/span>/);assert.doesNotMatch(icon.html,/water-over-road/);}});
