import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {ARCHITECTURE,EVIDENCE_CLASSES,METROS,READINESS,buildAudit,classifyReadiness,deduplicateCandidates,serialize} from '../tools/audit-metro-child-area-evidence-governance.mjs';

const appPath=new URL('../js/app.js',import.meta.url);
const projectionPath=new URL('../data/generated/gridly-statewide-consumer-community-projection-v1.json',import.meta.url);
const appSource=fs.readFileSync(appPath,'utf8');
const projection=JSON.parse(fs.readFileSync(projectionPath,'utf8'));
const build=()=>buildAudit({appSource,projection,available:{priorJson:true,priorMd:true}});
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');

test('scope is exactly the five requested metros and includes Houston only as control',()=>{const r=build();assert.deepEqual(r.metros.map(x=>x.name),['San Antonio','Corpus Christi','Austin','Dallas','Fort Worth']);assert.equal(r.houstonReferenceControl.parentPlace.placeGeoid,'4835000');assert.equal(r.houstonReferenceControl.children.length,15);assert.ok(!r.metros.some(x=>x.name==='Houston'));});
test('evidence-strength vocabulary and provenance are preserved',()=>{const r=build();assert.deepEqual(Object.keys(r.evidenceClassificationPolicy),EVIDENCE_CLASSES);for(const m of r.metros)for(const c of m.independentlyGovernedCommunities){assert.equal(c.evidenceClassification,'GOVERNED_GENERATED');assert.equal(c.sourceFile,'data/generated/gridly-statewide-consumer-community-projection-v1.json');assert.match(c.sourcePath,/placeGeoid=/);}});
test('independently governed PLACE communities retain precedence',()=>{const r=build();for(const m of r.metros){assert.ok(m.independentlyGovernedCommunities.length>0);assert.ok(m.independentlyGovernedCommunities.every(x=>x.placeGeoid&&x.precedenceRequirement==='PRESERVE_INDEPENDENT_CANONICAL_IDENTITY'));assert.ok(!m.independentlyGovernedCommunities.some(x=>x.placeGeoid===m.geoid));}});
test('candidate deduplication is stable and deterministic',()=>{const rows=[{metroParent:'Dallas',candidateId:'x',candidateName:'X'},{metroParent:'Austin',candidateId:'a',candidateName:'A'},{metroParent:'Dallas',candidateId:'x',candidateName:'X'}];assert.deepEqual(deduplicateCandidates(rows),[rows[1],rows[0]]);const r=build();for(const m of r.metros){const names=m.independentlyGovernedCommunities.map(x=>x.name);assert.deepEqual(names,[...names].sort((a,b)=>a.localeCompare(b)));}assert.equal(serialize(r).json,serialize(build()).json);});
test('readiness boundaries are explicit',()=>{assert.deepEqual(READINESS,['READY_FROM_EXISTING_GOVERNED_EVIDENCE','PARTIALLY_READY_GOVERNED_GAPS_EXIST','GOVERNED_CHILD_DEFINITION_REQUIRED','INSUFFICIENT_EVIDENCE_FOR_REGIONALIZATION']);assert.equal(classifyReadiness({previous:'REVIEW',governedCandidateCount:1,materialGaps:false}),READINESS[0]);assert.equal(classifyReadiness({previous:'REVIEW',governedCandidateCount:1}),READINESS[1]);assert.equal(classifyReadiness({previous:'REGIONALIZE_LIKE_HOUSTON',governedCandidateCount:0}),READINESS[2]);assert.equal(classifyReadiness({previous:'REVIEW',governedCandidateCount:0}),READINESS[3]);const r=build();for(const m of r.metros)assert.equal(m.readiness,classifyReadiness({previous:m.previous,governedCandidateCount:0}));});
test('architecture compatibility serializes from the controlled vocabulary',()=>{const r=build();for(const m of r.metros)assert.ok(ARCHITECTURE.includes(m.architectureCompatibility));assert.match(serialize(r).markdown,/HOUSTON_ARCHITECTURE_REUSABLE_WITH_GENERALIZATION/);});
test('no invented child regions are emitted',()=>{const r=build();for(const m of r.metros){assert.equal(m.candidateChildAreas.length,0);assert.equal(m.namingAuthorityStatus,'CHILD_REGION_NAMES_REQUIRE_GOVERNED_SOURCE');}assert.equal(r.governance.childRegionCreationAuthorized,false);});
test('audit execution does not mutate app.js or runtime projection',async()=>{const before=[sha(appPath),sha(projectionPath)];const {run}=await import('../tools/audit-metro-child-area-evidence-governance.mjs');const tmp=await fs.promises.mkdtemp('/tmp/gridly-metro-audit-');run({app:new URL('../js/app.js',import.meta.url),projection:new URL('../data/generated/gridly-statewide-consumer-community-projection-v1.json',import.meta.url),priorJson:'/missing',priorMd:'/missing',geometryJson:'/missing',geometryMd:'/missing',json:`${tmp}/report.json`,markdown:`${tmp}/report.md`});assert.deepEqual([sha(appPath),sha(projectionPath)],before);});
test('source contains no production writes or runtime mutation contract',()=>{const source=fs.readFileSync(new URL('../tools/audit-metro-child-area-evidence-governance.mjs',import.meta.url),'utf8');assert.doesNotMatch(source,/writeFileSync\(opts\.app|writeFileSync\(opts\.projection|GRIDLY_AWARENESS_AREA_DEFINITIONS\.push|GRIDLY_LP035_HOUSTON_REGION_MODEL\s*=/);assert.deepEqual(METROS.map(x=>x.name),['San Antonio','Corpus Christi','Austin','Dallas','Fort Worth']);});
