import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import test from 'node:test';

const source = fs.readFileSync(new URL('../js/gridlyPoiBrowserProvider.js', import.meta.url), 'utf8');
function runtime(overrides = {}) { const context = { console, TextDecoder, Response, Blob, DecompressionStream, crypto: globalThis.crypto, fetch: async () => { throw new Error('network disabled'); }, ...overrides }; context.globalThis = context; vm.runInNewContext(source, context); return context; }
const manifest = JSON.parse(fs.readFileSync(new URL('../poi/lp24111-d5-standalone-2026-08-28/runtime-v2/manifest.json', import.meta.url)));

test('gate defaults OFF and does not fetch', async () => { let fetched = false; const ctx = runtime({ fetch: async () => { fetched = true; } }); assert.equal(ctx.gridlyPoiBrowserRehearsalAudit().gateEnabled, false); await assert.rejects(ctx.GridlyPoiBrowserProvider.initialize, /NON_PRODUCTION_GATE_OFF/); assert.equal(fetched, false); });
test('certified manifest and bounded candidate selection pass', () => { const api = runtime().GridlyPoiBrowserProvider; api._test.validateManifest(manifest); for (const radiusMiles of [5, 10, 25]) assert.ok(api._test.candidateShardIds(manifest, { latitude: 32.7767, longitude: -96.797, radiusMiles }).length <= 4); });
test('release, schema, attribution, and fanout mismatches fail closed', () => { const api = runtime().GridlyPoiBrowserProvider; for (const mutate of [m => m.authorityReleaseId = 'wrong', m => m.runtimeSchemaVersion = 'v1', m => m.legalBinding.target = 'missing', m => m.maxCandidateShards25Mi = 5]) { const copy = structuredClone(manifest); mutate(copy); assert.throws(() => api._test.validateManifest(copy)); } });
test('v2 validator rejects v1, community identity, unknown fields, and coordinates', () => { const validate = runtime().GridlyPoiBrowserProvider._test.validateRecord; const valid = { id: '1', displayName: 'Place', gridlyCategory: 'PHARMACY', latitude: 30, longitude: -95, countyContextId: 'liberty-tx' }; assert.equal(validate(valid), valid); for (const change of [r => delete r.countyContextId, r => r.communityIdentity = {}, r => r.legacyCategory = 'v1', r => r.latitude = 100]) { const row = { ...valid }; change(row); assert.throws(() => validate(row)); } });
test('request identity, radius, rollback, and no-fallback diagnostics are enforced', () => { const ctx = runtime({ __GRIDLY_POI_NON_PRODUCTION__: true }); const api = ctx.GridlyPoiBrowserProvider; assert.throws(() => api._test.validateRequest({ latitude: 30, longitude: -95, countyContextId: 'x', radiusMiles: 6 })); assert.throws(() => api._test.validateRequest({ latitude: 30, longitude: -95, countyContextId: 'x', radiusMiles: 5, originType: 'DIRECT_COORDINATE', communityIdentity: {} })); assert.throws(() => api._test.validateRequest({ latitude: 30, longitude: -95, countyContextId: 'x', radiusMiles: 5, originType: 'GOVERNED_NON_PLACE', communityIdentity: { placeGeoid: 'x' } })); api.rollback(); const audit = api.audit(); assert.equal(audit.providerInitialized, false); assert.equal(audit.fallbackAttempted, false); assert.equal(audit.productionProviderEligible, false); assert.equal(audit.productionGate, 'OFF'); });
