import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {supabaseInvitationAdapters,DISPATCH_AUTH_ORIGIN} from '../tools/responder/phase29/worker/supabase-adapters.mjs';
import {authenticatedInvitationService} from '../tools/responder/phase29/worker/authenticated-invitation-service.mjs';
import {InvitationDelivery,ResendAdapter,FROM,ORIGIN} from '../tools/responder/phase29/invitation-delivery.mjs';
import {resendTransport} from '../tools/responder/phase29/worker/resend-transport.mjs';
const operator=randomUUID(),recipient=randomUUID(),operatorJwt='synthetic.operator.signature',recipientJwt='synthetic.recipient.signature';
const env={GRIDLY_DISPATCH_ENVIRONMENT:'PRODUCTION',GRIDLY_DISPATCH_SENDING_ENABLED:'false',GRIDLY_DISPATCH_EMAIL_FROM:FROM,GRIDLY_DISPATCH_ORIGIN:ORIGIN,GRIDLY_DISPATCH_WEBHOOK_URL:ORIGIN+'/api/resend/webhook'};
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json'}});
function fixture(overrides={}){
 const calls=[];
 const fetchImpl=async(u,o)=>{calls.push({u,o});if(u.endsWith('/auth/v1/user'))return json({id:o.headers.Authorization.endsWith(operatorJwt)?operator:recipient,email:'verified@dispatch.invalid',email_confirmed_at:'2026-01-01T00:00:00Z',...overrides});return json({invitationId:randomUUID(),attemptId:randomUUID(),expiresAt:'2030-01-08T00:00:00Z',organization:'Synthetic municipality',unit:null})};
 const options={publishableKey:'sb_publishable_syntheticFixtureOnly',operatorAccessToken:operatorJwt,recipientSessions:new Map([[recipient,recipientJwt]]),fetchImpl};
 return {calls,options,ports:supabaseInvitationAdapters(options)};
}
test('operator validated live and RPC uses operator JWT and exact custom schema',async()=>{const f=fixture();await f.ports.authorizeOperator({},'ISSUE');const p={organization_id:randomUUID(),target_user_id:recipient};await f.ports.operatorRepository.issue(p);assert.equal(f.calls[0].u,DISPATCH_AUTH_ORIGIN+'/auth/v1/user');assert.equal(f.calls[1].u,DISPATCH_AUTH_ORIGIN+'/rest/v1/rpc/issue_dispatch_invitation');assert.equal(f.calls[1].o.headers['Content-Profile'],'dispatch_api');assert.equal(f.calls[1].o.headers.Authorization,'Bearer '+operatorJwt);assert.deepEqual(JSON.parse(f.calls[1].o.body),{p_payload:p});assert.equal(f.calls[1].o.redirect,'error')});
test('recipient identity and email derived from own verified Auth session',async()=>{const f=fixture();assert.deepEqual(await f.ports.resolveRecipient(recipient),{userId:recipient,email:'verified@dispatch.invalid',verified:true});assert.equal(f.calls[0].o.headers.Authorization,'Bearer '+recipientJwt)});
for(const [name,patch] of Object.entries({unconfirmed:{email_confirmed_at:null},wrongIdentity:{id:randomUUID()},anonymous:{is_anonymous:true},banned:{banned_until:'2099-01-01'},pendingEmailChange:{email_change:'unverified@dispatch.invalid'},futureConfirmation:{email_confirmed_at:'2099-01-01'}}))test('recipient refuses '+name,async()=>{await assert.rejects(()=>fixture(patch).ports.resolveRecipient(recipient))});
test('recipient injection and unregistered identity refused before fetch',async()=>{const f=fixture();for(const id of ['injected@example.com',randomUUID()])await assert.rejects(()=>f.ports.resolveRecipient(id));assert.equal(f.calls.length,0)});
test('recipient session map copied so callers cannot replace trusted mapping',async()=>{const f=fixture();f.options.recipientSessions.set(recipient,operatorJwt);assert.equal((await f.ports.resolveRecipient(recipient)).userId,recipient)});
test('consumer origin and non-publishable credentials refused',()=>{const f=fixture();for(const p of [{origin:'https://consumer.invalid'},{publishableKey:'sb_secret_forbidden'},{operatorAccessToken:''}])assert.throws(()=>supabaseInvitationAdapters({...f.options,...p}))});
for(const status of [401,403,500])test('Auth/RPC '+status+' sanitized',async()=>{const f=fixture();const a=supabaseInvitationAdapters({...f.options,fetchImpl:async()=>new Response('PRIVATE_TOKEN_CONTENT',{status})});await assert.rejects(()=>a.authorizeOperator({},'ISSUE'),e=>e.message==='IDENTITY_UNAVAILABLE')});
test('malformed oversized and network responses sanitized',async()=>{const f=fixture();for(const fetchImpl of [async()=>new Response('bad',{headers:{'Content-Type':'application/json'}}),async()=>new Response('x'.repeat(65537),{headers:{'Content-Type':'application/json'}}),async()=>{throw Error(operatorJwt)}])await assert.rejects(()=>supabaseInvitationAdapters({...f.options,fetchImpl}).authorizeOperator({},'ISSUE'),e=>!e.message.includes(operatorJwt))});
test('Auth timeout bounded and sanitized',async()=>{const f=fixture();await assert.rejects(()=>supabaseInvitationAdapters({...f.options,timeoutMs:10,fetchImpl:()=>new Promise(()=>{})}).authorizeOperator({},'ISSUE'),e=>e.message==='IDENTITY_UNAVAILABLE')});
test('disabled authenticated factory refuses before identity or DB calls',()=>{const s=authenticatedInvitationService(env);assert.throws(()=>s.sendInvitation({}),e=>e.message==='SENDING_DISABLED')});
test('HTML and plain text have recipient-specific wording and escaped link',async()=>{
 let wire;const records=[];const c={environment:'TEST',origin:ORIGIN,from:FROM,acceptPath:'/synthetic/accept',supportPath:'/synthetic/support',redirectPaths:['/synthetic/home']};
 const service=new InvitationDelivery({config:c,repository:{issue:async p=>{records.push(p);return {invitationId:randomUUID(),attemptId:randomUUID(),expiresAt:'2030-01-08T00:00:00Z',organization:'Synthetic & municipal',unit:'Police'}},claim:async()=>true,complete:async p=>records.push(p)},resolveRecipient:async id=>({userId:id,email:'synthetic@dispatch.invalid',verified:true}),authorizeOperator:async()=>{},provider:new ResendAdapter({environment:'TEST',transport:async p=>{wire=p;return {ok:true,id:'synthetic-message'}}})});
 await service.sendInvitation({organizationId:randomUUID(),targetUserId:recipient,requestId:randomUUID(),role:'OPERATOR',redirectPath:'/synthetic/home'});
 for(const word of ['specific to you','Do not forward','unexpected','authorization','seven 24-hour periods'])for(const format of ['text','html'])assert.ok(wire.body[format].includes(word));assert.ok(wire.body.html.includes('Synthetic &amp; municipal'));assert.ok(wire.body.html.includes('&amp;token='));assert.doesNotMatch(wire.body.html,/<img|<script|tracking/i);assert.ok(!JSON.stringify(records).includes('token='));
});
for(const status of [400,500])test('Resend '+status+' is bounded rejection',async()=>{const sendEnv={...env,GRIDLY_DISPATCH_SENDING_ENABLED:'true',GRIDLY_DISPATCH_RESEND_API_KEY:'re_syntheticFixtureOnly'};const id=randomUUID();const req={method:'POST',path:'/emails',credential:sendEnv.GRIDLY_DISPATCH_RESEND_API_KEY,idempotencyKey:id,body:{from:FROM,to:['synthetic@dispatch.invalid'],subject:'Gridly Dispatch invitation',text:'Synthetic',html:'<p>Synthetic</p>',tags:[{name:'invitation_id',value:randomUUID()},{name:'attempt_id',value:id}]}};assert.deepEqual(await resendTransport(sendEnv,{fetchImpl:async()=>new Response('DO_NOT_EXPOSE',{status})})(req),{ok:false,reason:'PROVIDER_REJECTED'})});
test('authenticated factory completes bounded claim send and result without token persistence',async()=>{
 const f=fixture();let providerCalls=0;const sql=[];
 const fetchImpl=async(u,o)=>{if(u==='https://api.resend.com/emails'){providerCalls++;const m=JSON.parse(o.body);assert.equal(m.from,FROM);assert.equal(m.to[0],'verified@dispatch.invalid');assert.ok(m.html.includes('specific to you'));return json({id:'synthetic-provider-message'})}return f.options.fetchImpl(u,o)};
 const createClient=()=>({connect:async()=>{},end:async()=>{},query:async(q,p)=>{sql.push([q,p]);return {rows:q.includes('invitation_claim_send')?[{allowed:true}]:[]}}});
 const sendEnv={...env,GRIDLY_DISPATCH_SENDING_ENABLED:'true',GRIDLY_DISPATCH_RESEND_API_KEY:'re_syntheticFixtureOnly',GRIDLY_DISPATCH_DB_CACHING_DISABLED:'true',GRIDLY_DISPATCH_DB_TLS_REQUIRED:'true',DISPATCH_DELIVERY_DB:{connectionString:'postgres://proxy:synthetic@localhost/postgres'}};
 const s=authenticatedInvitationService(sendEnv,{identity:f.options,paths:{acceptPath:'/synthetic/accept',supportPath:'/synthetic/support',redirectPaths:['/synthetic/home']},fetchImpl,createClient});
 const out=await s.sendInvitation({organizationId:randomUUID(),targetUserId:recipient,requestId:randomUUID(),role:'OPERATOR',redirectPath:'/synthetic/home'});
 assert.equal(out.status,'SENT');assert.equal(providerCalls,1);assert.ok(sql.some(([q])=>q.includes('invitation_claim_send')));assert.ok(sql.some(([q,p])=>q.includes('invitation_transport_result')&&p[0].includes('synthetic-provider-message')));assert.ok(!JSON.stringify(sql).includes('token='));assert.ok(!JSON.stringify(out).includes('token='));
});
test('public-style sender recipient HTML and origin inputs cannot reach issuance',async()=>{
 let writes=0;const core=new InvitationDelivery({config:{environment:'TEST',origin:ORIGIN,from:FROM,acceptPath:'/synthetic/accept',supportPath:'/synthetic/support',redirectPaths:['/synthetic/home']},repository:{issue:async()=>{writes++}},provider:new ResendAdapter({environment:'TEST',transport:async()=>{throw Error('not reached')}}),authorizeOperator:async()=>{},resolveRecipient:async id=>({userId:id,email:'synthetic@dispatch.invalid',verified:true})});
 const input={organizationId:randomUUID(),targetUserId:recipient,requestId:randomUUID(),role:'OPERATOR',redirectPath:'/synthetic/home'};
 for(const extra of [{to:'injected@example.com'},{from:FROM},{sender:FROM},{html:'<script>bad</script>'},{origin:ORIGIN}])await assert.rejects(()=>core.sendInvitation({...input,...extra}));assert.equal(writes,0);
});
