import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac,randomUUID} from 'node:crypto';
import {readFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(new URL('../tools/responder/phase29/worker/package.json',import.meta.url));
const {Miniflare}=require('miniflare');const {build}=require('esbuild');
import {settings,signingKey,databaseBinding} from '../tools/responder/phase29/worker/config.mjs';
import {resendTransport} from '../tools/responder/phase29/worker/resend-transport.mjs';
import {deliveryRepository} from '../tools/responder/phase29/worker/delivery-repository.mjs';
import {invitationService} from '../tools/responder/phase29/worker/invitation-service.mjs';
const secret=Buffer.from('local-only-synthetic-signing-key-32');
const bindings={GRIDLY_DISPATCH_EMAIL_FROM:'Gridly Dispatch <dispatch@gridlygo.com>',GRIDLY_DISPATCH_ORIGIN:'https://dispatch.gridlygo.com',GRIDLY_DISPATCH_WEBHOOK_URL:'https://dispatch.gridlygo.com/api/resend/webhook',GRIDLY_DISPATCH_ENVIRONMENT:'PRODUCTION',GRIDLY_DISPATCH_SENDING_ENABLED:'false',GRIDLY_DISPATCH_RESEND_WEBHOOK_SECRET:'whsec_'+secret.toString('base64')};
const dbEnv={...bindings,GRIDLY_DISPATCH_DB_CACHING_DISABLED:'true',GRIDLY_DISPATCH_DB_TLS_REQUIRED:'true',DISPATCH_DELIVERY_DB:{connectionString:'postgres://dispatch_delivery_connection:synthetic@dedicated.invalid/postgres?sslmode=verify-full'}};
const url=bindings.GRIDLY_DISPATCH_WEBHOOK_URL;let mf,missing,dir;
before(async()=>{dir=mkdtempSync(join(tmpdir(),'dispatch-worker-local-'));const r=await build({entryPoints:[new URL('../tools/responder/phase29/worker/runtime-fixture.mjs',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')],bundle:true,write:false,format:'esm',platform:'node',external:['node:*'],banner:{js:"import {createRequire as workerRequire} from 'node:module'; const require=workerRequire('/worker.mjs');"},logLevel:'silent'});const options={modules:true,script:r.outputFiles[0].text,compatibilityDate:'2026-07-30',compatibilityFlags:['nodejs_compat'],outboundService:()=>new Response(null,{status:503}),bindings};mf=new Miniflare(options);missing=new Miniflare({...options,bindings:{...bindings,GRIDLY_DISPATCH_RESEND_WEBHOOK_SECRET:''}})});
after(async()=>{await mf?.dispose();await missing?.dispose();rmSync(dir,{recursive:true,force:true})});
function signed(type='email.sent',{id=randomUUID(),stamp=String(Math.floor(Date.now()/1000)),message='synthetic-message',body}={}){body??=JSON.stringify({type,created_at:new Date().toISOString(),data:{email_id:message,text:'NEVER_LOG_TOKEN_BODY'}});return {body,headers:{'content-type':'application/json','svix-id':id,'svix-timestamp':stamp,'svix-signature':'v1,'+createHmac('sha256',secret).update(id+'.'+stamp+'.'+body).digest('base64')}}}
async function send(x=signed(),target=url,method='POST',runtime=mf){return runtime.dispatchFetch(target,{method,headers:x.headers,...(method==='GET'?{}:{body:x.body})})}
test('actual workerd accepts valid Svix signature and strips extra fields',async()=>{const r=await send();assert.equal(r.status,204);assert.equal(await r.text(),'');assert.equal(r.headers.get('cache-control'),'no-store')});
test('exact origin/path refuses alternate host, scheme, path and query',async()=>{for(const u of ['https://gridlygo.com/api/resend/webhook','http://dispatch.gridlygo.com/api/resend/webhook',url+'/other',url+'?token=private','https://dispatch.gridlygo.com/'])assert.equal((await send(signed(),u)).status,404)});
test('POST only and safe content type/encoding',async()=>{assert.equal((await send(signed(),url,'GET')).status,405);for(const h of [{'content-type':'text/plain'},{'content-encoding':'gzip'}]){const x=signed();Object.assign(x.headers,h);assert.equal((await send(x)).status,415)}});
test('raw body 65536 boundary and oversized chunked input',async()=>{const base=signed().body;const pad=base+' '.repeat(65536-Buffer.byteLength(base));assert.equal((await send(signed('email.sent',{body:pad}))).status,204);assert.equal((await send(signed('email.sent',{body:pad+' '}))).status,413)});
test('invalid missing stale future and tampered signatures never process',async()=>{for(const x of [signed('email.sent',{stamp:String(Math.floor(Date.now()/1000)-400)}),signed('email.sent',{stamp:String(Math.floor(Date.now()/1000)+400)}),(()=>{const x=signed();x.headers['svix-signature']='v1,invalid';return x})(),(()=>{const x=signed();delete x.headers['svix-id'];return x})(),(()=>{const x=signed();x.body+=' ';return x})()])assert.equal((await send(x)).status,401)});
test('signed malformed JSON and unknown event safely refused',async()=>{assert.equal((await send(signed('email.sent',{body:'not-json'}))).status,401);assert.equal((await send(signed('email.rejected'))).status,401)});
test('missing server signing secret refuses without payload disclosure',async()=>{const r=await send(signed(),url,'POST',missing);assert.equal(r.status,503);assert.equal(await r.text(),'')});
test('identical duplicate idempotent; changed duplicate conflict',async()=>{const x=signed();assert.equal((await send(x)).status,204);assert.equal((await send(x)).status,204);assert.equal((await send(signed('email.bounced',{id:x.headers['svix-id']}))).status,409)});
test('unknown correlation refuses; all seven events and adverse order supported',async()=>{assert.equal((await send(signed('email.sent',{message:'unknown'}))).status,503);for(const e of ['email.sent','email.delivery_delayed','email.delivered','email.failed','email.suppressed','email.bounced','email.complained','email.sent'])assert.equal((await send(signed(e))).status,204)});
test('raw Unicode bytes and BOM are not silently normalized',async()=>{const body=JSON.stringify({type:'email.sent',created_at:new Date().toISOString(),data:{email_id:'synthetic-message',ignored:'🚒'}});assert.equal((await send(signed('email.sent',{body}))).status,204);const x=signed();x.body='\ufeff'+x.body;assert.equal((await send(x)).status,401)});
test('configuration rejects caller origin and malformed bindings',()=>{for(const p of [{GRIDLY_DISPATCH_ORIGIN:'https://gridlygo.com'},{GRIDLY_DISPATCH_EMAIL_FROM:'other@gridlygo.com'},{GRIDLY_DISPATCH_ENVIRONMENT:'PREVIEW'},{GRIDLY_DISPATCH_SENDING_ENABLED:'yes'}])assert.throws(()=>settings({...bindings,...p}));assert.throws(()=>signingKey({...bindings,GRIDLY_DISPATCH_RESEND_WEBHOOK_SECRET:'raw-secret'}));assert.deepEqual(signingKey(bindings),secret)});
const key='re_SYNTHETIC_ONLY_NOT_REAL';const sendEnv={...bindings,GRIDLY_DISPATCH_SENDING_ENABLED:'true',GRIDLY_DISPATCH_RESEND_API_KEY:key};
function request(){const attempt=randomUUID();return {method:'POST',path:'/emails',credential:key,idempotencyKey:attempt,body:{from:bindings.GRIDLY_DISPATCH_EMAIL_FROM,to:['local@dispatch.invalid'],subject:'Gridly Dispatch invitation',text:'Synthetic token-bearing message; no network',tags:[{name:'invitation_id',value:randomUUID()},{name:'attempt_id',value:attempt}]}}}
test('disabled transport and facade refuse before fetch/operator writes',async()=>{let calls=0;const f=()=>{calls++;return new Response('{}')};await assert.rejects(()=>resendTransport({...sendEnv,GRIDLY_DISPATCH_SENDING_ENABLED:'false'},{fetchImpl:f})(request()));const s=invitationService(bindings);for(const n of ['sendInvitation','sendReissue','discloseFallback'])assert.throws(()=>s[n]({}));assert.equal(calls,0)});
test('missing API key and wrong sender refused before network',async()=>{let calls=0;const fetchImpl=()=>{calls++;return new Response('{}')};await assert.rejects(()=>resendTransport({...sendEnv,GRIDLY_DISPATCH_RESEND_API_KEY:''},{fetchImpl})(request()));const r=request();r.body.from='consumer@gridlygo.com';await assert.rejects(()=>resendTransport(sendEnv,{fetchImpl})(r));assert.equal(calls,0)});
test('mock fetch transport captures safe provider ID and bounded rejection',async()=>{let seen;const t=resendTransport(sendEnv,{fetchImpl:async(u,o)=>{seen={u,o};return new Response(JSON.stringify({id:'synthetic-provider-id',secret:'DO_NOT_RETURN'}))}});assert.deepEqual(await t(request()),{ok:true,id:'synthetic-provider-id'});assert.equal(seen.u,'https://api.resend.com/emails');assert.equal(seen.o.headers.Authorization,'Bearer '+key);assert.equal(seen.o.redirect,'error');assert.deepEqual(await resendTransport(sendEnv,{fetchImpl:async()=>new Response('NEVER_RETURN_TOKEN',{status:403})})(request()),{ok:false,reason:'PROVIDER_REJECTED'})});
test('transport timeout oversized and malicious response errors minimized',async()=>{for(const fetchImpl of [async()=>{throw Error(key)},async()=>new Response('x'.repeat(16385)),async()=>new Response('not-json')]){const out=await resendTransport(sendEnv,{fetchImpl})(request());assert.equal(out.ok,false);assert.ok(!JSON.stringify(out).includes(key))}const out=await resendTransport(sendEnv,{timeoutMs:10,fetchImpl:()=>new Promise(()=>{})})(request());assert.equal(out.reason,'PROVIDER_TIMEOUT')});
test('database binding rejects broad login insecure TLS and caching',()=>{for(const p of [{GRIDLY_DISPATCH_DB_CACHING_DISABLED:'false'},{GRIDLY_DISPATCH_DB_TLS_REQUIRED:'false'},{DISPATCH_DELIVERY_DB:{connectionString:'postgres://postgres:pw@host/db'}},{DISPATCH_DELIVERY_DB:{connectionString:'postgres://dispatch_delivery_connection:pw@host/db?sslmode=disable'}}])assert.throws(()=>databaseBinding({...dbEnv,...p}))});
function fakeClient(fail=false){const queries=[];return{queries,connect:async()=>{},end:async()=>queries.push('END'),query:async(sql,params)=>{queries.push([sql,params]);if(sql.startsWith('SELECT')&&fail)throw Object.assign(Error('sensitive provider body'),{code:'P0001'});return {rows:[{allowed:false}]}}}}
test('repository only parameterized bounded commands and transaction-local role',async()=>{const c=fakeClient();const r=deliveryRepository(dbEnv,{createClient:()=>c});assert.equal(await r.claim(randomUUID()),false);assert.equal(c.queries[1][0],'SET LOCAL ROLE dispatch_delivery_transport');assert.ok(c.queries.find(x=>Array.isArray(x)&&x[0].includes('$1::uuid')));assert.ok(c.queries.some(x=>Array.isArray(x)&&x[0]==='COMMIT'));assert.equal(c.queries.at(-1),'END');assert.equal(r.issue,undefined);assert.throws(()=>r.claim("x';DROP TABLE private;"));assert.throws(()=>r.event({eventId:'safe',messageId:'safe',status:'SENT',occurredAt:new Date().toISOString(),token:'NO'}))});
test('repository failures rollback close and minimize errors',async()=>{const c=fakeClient(true);await assert.rejects(()=>deliveryRepository(dbEnv,{createClient:()=>c}).claim(randomUUID()),e=>e.message==='DELIVERY_UNAVAILABLE');assert.ok(c.queries.some(x=>Array.isArray(x)&&x[0]==='ROLLBACK'));assert.equal(c.queries.at(-1),'END')});
test('source/config isolation: no browser build, no logging, exact route, no secret values',()=>{const config=JSON.parse(readFileSync(new URL('../tools/responder/phase29/worker/wrangler.jsonc',import.meta.url)));assert.deepEqual(config.routes,[{pattern:'dispatch.gridlygo.com/api/resend/webhook',zone_name:'gridlygo.com'}]);assert.equal(config.vars.GRIDLY_DISPATCH_SENDING_ENABLED,'false');assert.equal(config.workers_dev,false);for(const f of ['index.mjs','config.mjs','delivery-repository.mjs','resend-transport.mjs','invitation-service.mjs']){const s=readFileSync(new URL('../tools/responder/phase29/worker/'+f,import.meta.url),'utf8');assert.ok(!/console\.|NEXT_PUBLIC|service_role/.test(s));assert.ok(!s.includes(key))}assert.ok(!config.vars.GRIDLY_DISPATCH_RESEND_API_KEY);assert.ok(!config.vars.GRIDLY_DISPATCH_RESEND_WEBHOOK_SECRET)});

test('malformed base64 signature cannot gain validity through decoder tolerance',async()=>{const x=signed();x.headers['svix-signature']+='!';assert.equal((await send(x)).status,401)});
test('missing credential refuses operator service before writes; path overrides refused',()=>{let calls=0;const ports={operatorRepository:{issue:()=>{calls++}},authorizeOperator:async()=>{},resolveRecipient:async()=>{},paths:{acceptPath:'/synthetic/accept',supportPath:'/synthetic/support',redirectPaths:['/synthetic/home']}};assert.throws(()=>invitationService({...sendEnv,GRIDLY_DISPATCH_RESEND_API_KEY:''},ports));assert.throws(()=>invitationService(sendEnv,{...ports,paths:{...ports.paths,origin:'https://consumer.invalid'}}));assert.equal(calls,0)});

test('streamed chunks enforce raw-byte limit without Content-Length',async()=>{const x=signed();const chunks=[new Uint8Array(40000),new Uint8Array(30000)];const body=new ReadableStream({pull(c){const b=chunks.shift();b?c.enqueue(b):c.close()}});const r=await mf.dispatchFetch(url,{method:'POST',headers:x.headers,body,duplex:'half'});assert.equal(r.status,413)});
test('signed malformed UTF-8 refuses without replacement or persistence',async()=>{const stamp=String(Math.floor(Date.now()/1000)),id=randomUUID(),body=Buffer.from([0xc3,0x28]);const signature=createHmac('sha256',secret).update(Buffer.concat([Buffer.from(id+'.'+stamp+'.'),body])).digest('base64');const r=await mf.dispatchFetch(url,{method:'POST',body,headers:{'content-type':'application/json','svix-id':id,'svix-timestamp':stamp,'svix-signature':'v1,'+signature}});assert.equal(r.status,400);assert.equal(await r.text(),'')});