import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID,createHmac} from 'node:crypto';
import {configuration,InvitationDelivery,ResendAdapter,verifyWebhook,ORIGIN,FROM} from '../tools/responder/phase29/invitation-delivery.mjs';
const config={environment:'TEST',origin:ORIGIN,from:FROM,acceptPath:'/synthetic/accept',supportPath:'/synthetic/support',redirectPaths:['/synthetic/onboarding']};
const base=()=>({organizationId:randomUUID(),targetUserId:randomUUID(),requestId:randomUUID(),role:'OPERATOR',redirectPath:'/synthetic/onboarding'});
function fixture(transport=async()=>({ok:true,id:'mock-message'})){const stored=[],wire=[];const repo={claim:async()=>true,issue:async p=>{stored.push(p);return{invitationId:randomUUID(),attemptId:randomUUID(),expiresAt:'2030-01-08T00:00:00Z',organization:'Synthetic municipality',unit:'Synthetic Police'}},complete:async p=>stored.push(p),event:async p=>stored.push(p)};const provider=new ResendAdapter({environment:'TEST',transport:async p=>{wire.push(p);return transport(p)}});return{stored,wire,service:new InvitationDelivery({config,repository:repo,provider,resolveRecipient:async id=>({userId:id,email:'recipient@dispatch.invalid',verified:true}),authorizeOperator:async()=>{}})}}
test('exact sender/origin and explicit same-origin configuration',()=>{assert.equal(configuration(config).origin,ORIGIN);for(const c of [{from:'noreply@gridlygo.com'},{origin:'http://localhost'},{origin:'https://gridlygo.com'},{origin:'https://preview.invalid'},{redirectPaths:['https://third.invalid']},{redirectPaths:['//*']},{redirectPaths:['/a?return=https://evil.invalid']}])assert.throws(()=>configuration({...config,...c}));});
test('mock Resend success renders bounded content without token persistence',async()=>{const f=fixture();const result=await f.service.sendInvitation(base());assert.equal(result.status,'SENT');const message=f.wire[0];assert.equal(message.body.from,FROM);for(const v of ['Gridly Dispatch','Synthetic municipality','Synthetic Police','Purpose:','seven 24-hour periods','Do not forward','Support:'])assert.ok(message.body.text.includes(v));const token=new URL(message.body.text.match(/https:\/\/dispatch\.gridlygo\.com\/synthetic\/accept[^\n]+/)[0]).searchParams.get('token');assert.ok(token.length>=43);assert.ok(!JSON.stringify(f.stored).includes(token));assert.ok(!JSON.stringify(message.body.tags).includes(token));assert.ok(!JSON.stringify(result).includes(token));assert.match(f.stored[0].token_digest,/^[a-f0-9]{64}$/);});
test('caller origin/return and duration overrides refused',async()=>{for(const extra of [{origin:ORIGIN},{returnUrl:ORIGIN},{expiresAt:'2030-01-01'},{duration:6},{redirectPath:'/unapproved'}])await assert.rejects(()=>fixture().service.sendInvitation({...base(),...extra}));});
test('transport errors discard provider plaintext and fail delivery only',async()=>{const f=fixture(async p=>{throw new Error(p.body.text)});assert.equal((await f.service.sendInvitation(base())).status,'FAILED');assert.equal(f.stored.at(-1).reason,'TRANSPORT_FAILURE');assert.ok(!JSON.stringify(f.stored).includes('token='));});
test('manual fallback requires explicit authorization confirmation and reason',async()=>{const f=fixture();await assert.rejects(()=>f.service.discloseFallback({...base(),priorInvitationId:randomUUID(),expectedRevision:1}));const p={...base(),priorInvitationId:randomUUID(),expectedRevision:1,recipientConfirmed:true,fallbackReason:'DELIVERY_RECOVERY'};const out=await f.service.discloseFallback(p);assert.ok(out.link.includes('token='));assert.equal(f.wire.length,0);assert.ok(!JSON.stringify(f.stored).includes(new URL(out.link).searchParams.get('token')));f.service.authorize=async()=>{throw Error('forbidden')};await assert.rejects(()=>f.service.discloseFallback(p));});
test('verified webhook allowlist strips arbitrary token-bearing fields',()=>{const secret=Buffer.from('synthetic-test-webhook-key'),now=Date.now(),stamp=String(Math.floor(now/1000)),id='mock-event';const body=JSON.stringify({type:'email.delivered',created_at:new Date(now).toISOString(),data:{email_id:'mock-message',token:'DO_NOT_PERSIST',text:'SECRET_BODY'}});const headers={'svix-id':id,'svix-timestamp':stamp,'svix-signature':'v1,'+createHmac('sha256',secret).update(`${id}.${stamp}.${body}`).digest('base64')};const event=verifyWebhook({body,headers,secret,now});assert.equal(event.status,'DELIVERED');assert.ok(!JSON.stringify(event).includes('DO_NOT_PERSIST'));assert.ok(!JSON.stringify(event).includes('SECRET_BODY'));assert.throws(()=>verifyWebhook({body,headers:{...headers,'svix-signature':'v1,invalid'},secret,now}));assert.throws(()=>verifyWebhook({body,headers,secret,now:now+400000}));});
test('test recipient and credential isolation',async()=>{assert.throws(()=>new ResendAdapter({environment:'TEST',credential:'forbidden',transport:async()=>{}}));const f=fixture();f.service.resolveRecipient=async id=>({userId:id,email:'real@example.com',verified:true});await assert.rejects(()=>f.service.sendInvitation(base()));f.service.resolveRecipient=async()=>({userId:randomUUID(),email:'recipient@dispatch.invalid',verified:true});await assert.rejects(()=>f.service.sendInvitation(base()));});

test('webhook boundary uses only the server-held secret',async()=>{const f=fixture(),secret=Buffer.from('synthetic-server-held-signing-key');const service=new InvitationDelivery({config,repository:f.service.repo,provider:f.service.provider,resolveRecipient:f.service.resolveRecipient,authorizeOperator:f.service.authorize,webhookSecret:secret});const id='signed-event',stamp=String(Math.floor(Date.now()/1000)),body=JSON.stringify({type:'email.sent',created_at:new Date().toISOString(),data:{email_id:'mock-message',token:'NEVER_PERSIST'}});const headers={'svix-id':id,'svix-timestamp':stamp,'svix-signature':'v1,'+createHmac('sha256',secret).update(`${id}.${stamp}.${body}`).digest('base64')};await service.recordProviderEvent({body,headers});assert.equal(f.stored.at(-1).eventId,id);assert.ok(!JSON.stringify(f.stored).includes('NEVER_PERSIST'));await assert.rejects(()=>service.recordProviderEvent({body,headers,secret:Buffer.from('caller-key')}));await assert.rejects(()=>service.recordProviderEvent({body,headers:{...headers,'svix-signature':'v1,invalid'}}));});
test('send claim refusal prevents transport and exposes no link',async()=>{const f=fixture();f.service.repo.claim=async()=>false;const result=await f.service.sendInvitation(base());assert.equal(result.status,'REFUSED');assert.equal(f.wire.length,0);assert.ok(!JSON.stringify(result).includes('token='));});

test('reissue requires explicit prior identity and revision',async()=>{const f=fixture();await assert.rejects(()=>f.service.sendReissue(base()));await assert.rejects(()=>f.service.sendReissue({...base(),priorInvitationId:randomUUID(),expectedRevision:0}));await assert.rejects(()=>f.service.sendInvitation({...base(),priorInvitationId:randomUUID(),expectedRevision:1}));assert.equal(f.stored.length,0);});
