import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {validateTarget,PROJECT_REF} from '../tools/responder/phase29/installer/target.mjs';
const dir=new URL('../tools/responder/phase29/installer/',import.meta.url);const read=n=>readFileSync(new URL(n,dir),'utf8');const sql=read('install.sql'),manifest=JSON.parse(read('inventory.json'));
const packet={host:'db.'+PROJECT_REF+'.supabase.co',port:5432,database:'postgres',user:'postgres',projectRef:PROJECT_REF,settingsApproved:true,ssl:{rejectUnauthorized:true,ca:'TEST CA ONLY',servername:'db.'+PROJECT_REF+'.supabase.co',minVersion:'TLSv1.2'}};
test('exact dedicated target and TLS binding accepts approved shape',()=>assert.equal(validateTarget(packet).host,packet.host));
test('wrong project ref, consumer host, pooler and false approval refuse',()=>{for(const patch of [{projectRef:'wrong'},{host:'consumer.supabase.co'},{host:'pooler.supabase.com'},{settingsApproved:false},{port:6543},{user:'service_role'},{database:'other'}])assert.throws(()=>validateTarget({...packet,...patch}),/TARGET_REFUSED/)});
test('TLS bypass and mismatched certificate hostname refuse',()=>{for(const patch of [{rejectUnauthorized:false},{ca:''},{servername:'other'},{minVersion:'TLSv1'},{checkServerIdentity:()=>undefined}])assert.throws(()=>validateTarget({...packet,ssl:{...packet.ssl,...patch}}),/TARGET_REFUSED/)});
test('candidate hash matches exact generated SQL',()=>assert.equal(createHash('sha256').update(sql.replaceAll('\r\n','\n')).digest('hex'),manifest.installSha256));
test('single atomic transaction and no disposable artifacts',()=>{assert.equal((sql.match(/^BEGIN;/gm)||[]).length,1);assert.equal((sql.match(/^COMMIT;/gm)||[]).length,1);assert.doesNotMatch(sql,/gridly_consumer_sentinel|GRIDLY_PHASE26|gridly_rehearsal\.environment|CREATE SCHEMA report_retention/)});
test('precheck precedes every application object and grant hardening',()=>{assert.ok(sql.indexOf('DO $precheck$')<sql.indexOf('ALTER DEFAULT PRIVILEGES'));assert.ok(sql.indexOf('ALTER DEFAULT PRIVILEGES')<sql.indexOf('CREATE ROLE dispatch_function_owner'));assert.match(sql,/existing Dispatch namespace\/role/);assert.match(sql,/unknown default privilege baseline/)});
test('frozen input locks match canonical source contents',()=>{for(const [p,h] of Object.entries(manifest.sourceLocks)){const body=readFileSync(new URL('../'+p,import.meta.url),'utf8').replaceAll('\r\n','\n');assert.equal(createHash('sha256').update(body).digest('hex'),h,p)}});
test('retains frozen TOTP intervals and review rules',()=>{assert.match(sql,/10 minutes/);assert.match(sql,/5 minutes/);assert.match(sql,/report_review_attempt_eligible/);assert.match(sql,/PHASE29-INDEPENDENT-v1/)});
test('delivery login has no stored password and transport-only membership',()=>{assert.match(sql,/CREATE ROLE dispatch_delivery_connection LOGIN NOINHERIT NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE/);assert.match(sql,/WITH INHERIT FALSE, SET TRUE/);assert.doesNotMatch(sql,/PASSWORD\s+'/i)});
test('rollback scans every nonregistry table and leaves hardening',()=>{const r=read('rollback.sql');assert.match(r,/ROLLBACK_REFUSED evidence-bearing/);assert.match(r,/ROLLBACK_REFUSED external dependency/);assert.doesNotMatch(r,/ALTER DEFAULT PRIVILEGES.*GRANT/)});
test('creator ADMIN grants never authorize runtime SET or inheritance',()=>{assert.match(read('postflight.sql'),/\(set_option OR inherit_option\)/);assert.match(read('postflight.sql'),/NOT admin_option AND NOT inherit_option AND set_option/)});

test('installer SQL hashing survives CRLF checkout without changing text',()=>{const lf=sql.replaceAll('\r\n','\n'),crlf=lf.replaceAll('\n','\r\n');assert.equal(createHash('sha256').update(crlf.replaceAll('\r\n','\n')).digest('hex'),manifest.installSha256);assert.notEqual(createHash('sha256').update(lf+' ').digest('hex'),manifest.installSha256)});

test('failure probes preserve SQL dollar quotes and require actual injected exception',()=>{const source=read('runtime.test.mjs');assert.match(source,/replace\('COMMIT;',\(\)=>/);assert.match(source,/ERROR:/);const probe='COMMIT;'.replace('COMMIT;',()=> 'DO $$ BEGIN RAISE EXCEPTION \'INJECTED_FAILURE\'; END $$; COMMIT;');assert.match(probe,/DO \$\$/);assert.match(probe,/END \$\$/)});

test('both actual failure-probe source lines contain intact SQL delimiters',()=>{const lines=read('runtime.test.mjs').split('\n').filter(x=>x.startsWith("test('global browser defaults")||x.startsWith("test('failure after hardening"));assert.equal(lines.length,2);for(const line of lines){assert.match(line,/DO \$\$ BEGIN/);assert.match(line,/END \$\$;/)}});
