import test from 'node:test'; import assert from 'node:assert/strict';
import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..'),dir=path.join(root,'tools','responder','phase26'),ev=path.join(root,'reports','responder','phase26-evidence');
const files=['README.md','baseline.sql','preflight.sql','apply.sql','seed-static-contract.sql','compatibility.sql','postflight.sql','rollback.sql','failure-type-table.sql','failure-rls.sql','failure-command.sql','failure-grants.sql','catalog-snapshot.mjs','rehearsal-runtime.test.mjs','run-clone-rehearsal.ps1'];
test('package is isolated, warned, and contains no production endpoint or credential',()=>{for(const f of files){const p=path.join(dir,f);assert.ok(fs.existsSync(p),f);const t=fs.readFileSync(p,'utf8');assert.match(t,/LOCAL DISPOSABLE REHEARSAL ONLY/i,f);assert.match(t,/NOT AUTHORIZED FOR PRODUCTION EXECUTION/i,f);assert.doesNotMatch(t,/https:\/\/[a-z0-9]{15,}\.supabase\.co|sb_secret_|eyJ[A-Za-z0-9_-]{24,}\./i,f);assert.equal(p.includes(path.join('supabase','migrations')),false)} });
test('manufactured package freezes exact catalog and security inventory',()=>{const s=fs.readFileSync(path.join(dir,'apply.sql'),'utf8');assert.equal((s.match(/^CREATE TYPE /gm)||[]).length,23);assert.equal((s.match(/^CREATE TABLE dispatch_/gm)||[]).length,22);assert.equal((s.match(/^CREATE POLICY /gm)||[]).length,17);assert.match(s,/SECURITY DEFINER SET search_path=''/);assert.match(s,/REVOKE ALL ON ALL FUNCTIONS[\s\S]*FROM PUBLIC,anon,authenticated,service_role/);assert.match(s,/WITH\(security_invoker=true\)/);assert.doesNotMatch(s,/EXECUTE\s+p_(?:payload|command)/i);assert.match(s,/FOREACH n IN ARRAY names/)});
test('certified catalog, runtime vectors, rollback refusal, and teardown evidence pass',()=>{const c=JSON.parse(fs.readFileSync(path.join(ev,'post-catalog-certified.json'),'utf8')),r=JSON.parse(fs.readFileSync(path.join(ev,'runtime-vectors.json'),'utf8')),td=JSON.parse(fs.readFileSync(path.join(ev,'teardown.json'),'utf8'));const canonical=JSON.stringify(sort(c.catalog));assert.equal(crypto.createHash('sha256').update(canonical).digest('hex'),c.hash);assert.equal(c.catalog.tables.length,22);assert.equal(c.catalog.types.length,23);assert.equal(c.catalog.functions.length,64);assert.equal(c.catalog.policies.length,17);assert.equal(r.status,'PASS');assert.equal(r.commandNames.length,26);assert.equal(r.realLocalAuth,true);assert.equal(r.privateFieldLeak,false);assert.deepEqual(td.containers_remaining,[]);assert.deepEqual(td.networks_remaining,[]);assert.equal(td.remote_connections,0);assert.equal(td.production_credentials,0);assert.equal(td.runtime_directory_removed,true);assert.match(fs.readFileSync(path.join(dir,'rollback.sql'),'utf8'),/PHASE26_ROLLBACK_REFUSED evidence-bearing/)});
test('consumer/reporting sentinels and Data API boundary are explicit',()=>{const base=JSON.parse(fs.readFileSync(path.join(ev,'baseline-catalog.json'),'utf8')),cat=JSON.parse(fs.readFileSync(path.join(ev,'post-catalog-certified.json'),'utf8')).catalog,runner=fs.readFileSync(path.join(dir,'run-clone-rehearsal.ps1'),'utf8');assert.equal(base.consumer_rows,cat.consumer_rows);assert.equal(base.reporting_enabled,cat.reporting_enabled);assert.match(runner,/schemas = \["public", "graphql_public", "dispatch_api"\]/);assert.doesNotMatch(runner,/schemas = \[[^\]]*dispatch_private/)});
function sort(v){if(Array.isArray(v))return v.map(sort).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,sort(v[k])]));return v}
