import test from 'node:test';
import assert from 'node:assert/strict';
import {handle} from '../tools/responder/phase29/worker/index.mjs';
const env={DISPATCH_DELIVERY_DB:{connectionString:'postgresql://dispatch_delivery_connection:synthetic@localhost/postgres'},GRIDLY_DISPATCH_DB_CACHING_DISABLED:'true',GRIDLY_DISPATCH_DB_TLS_REQUIRED:'true'};
const req=(path='/health',method='GET')=>new Request('https://dispatch.gridlygo.com'+path,{method});
function client(failAt){let role='dispatch_delivery_connection',queries=[],ended=false;return {queries,get ended(){return ended},async connect(){if(failAt==='connect')throw Error('secret connection URI')},async query(sql){queries.push(sql);if(sql===failAt)throw Error('secret SQL password');if(sql.startsWith('BEGIN'))assert.equal(role,'dispatch_delivery_connection');if(sql.startsWith('SET LOCAL ROLE'))role='dispatch_delivery_transport';if(sql==='ROLLBACK')role='dispatch_delivery_connection';if(sql.startsWith('SELECT'))return {rows:[{database:'postgres',session_user:'dispatch_delivery_connection',current_user:role}]};return {rows:[]}},async end(){ended=true}}}
test('missing binding is sanitized 503 without Resend',async()=>{const r=await handle(req(),{});assert.equal(r.status,503);assert.equal((await r.json()).database.connected,false)});
test('governed transition rollback reset and logical pool reuse verified',async()=>{const c=client();const r=await handle(req(),env,{readinessOptions:{createClient:()=>c}});assert.equal(r.status,200);const b=await r.json();assert.equal(b.transportRole.verified,true);assert.equal(b.roleReset.verified,true);assert.equal(c.queries.filter(x=>x==='BEGIN READ ONLY').length,2);assert.equal(c.queries.filter(x=>x==='ROLLBACK').length,2);assert.ok(c.ended);assert.ok(c.queries.every(x=>/^(SELECT|BEGIN READ ONLY|SET LOCAL|ROLLBACK)/.test(x)));assert.doesNotMatch(JSON.stringify(b),/synthetic|postgresql|localhost|password|SELECT/)});
for(const fail of ['connect','SET LOCAL ROLE dispatch_delivery_transport',"SET LOCAL statement_timeout = '3000ms'"]){test('failure sanitized and cleanup '+fail,async()=>{const c=client(fail);const r=await handle(req(),env,{readinessOptions:{createClient:()=>c}});assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/secret|password|SQL|URI/);assert.ok(c.ended);if(fail!=='connect')assert.equal(c.queries.at(-1),'ROLLBACK')})}
test('wrong identity fails closed',async()=>{const c=client();c.query=async()=>({rows:[{database:'postgres',session_user:'postgres',current_user:'postgres'}]});assert.equal((await handle(req(),env,{readinessOptions:{createClient:()=>c}})).status,503)});
test('exact GET route only',async()=>{assert.equal((await handle(req('/health','POST'),{})).status,405);for(const path of ['/health?x=1','/health/','/api/health'])assert.equal((await handle(req(path),{})).status,404)});
test('webhook remains unavailable without secrets and is POST-only',async()=>{assert.equal((await handle(req('/api/resend/webhook'),{})).status,405);assert.equal((await handle(new Request('https://dispatch.gridlygo.com/api/resend/webhook',{method:'POST',headers:{'content-type':'application/json'},body:'{}'}),{})).status,503)});

test('cleanup failure sanitized',async()=>{const c=client();c.end=async()=>{throw Error('password URI')};const r=await handle(req(),env,{readinessOptions:{createClient:()=>c}});assert.equal(r.status,503);assert.doesNotMatch(await r.text(),/password|URI/)});
test('rollback failure closes logical client and refuses',async()=>{const c=client('ROLLBACK');const r=await handle(req(),env,{readinessOptions:{createClient:()=>c}});assert.equal(r.status,503);assert.ok(c.ended);assert.equal(c.queries.filter(x=>x==='ROLLBACK').length,2)});
test('health refuses alternate host and protocol',async()=>{for(const u of ['http://dispatch.gridlygo.com/health','https://gridlygo.com/health'])assert.equal((await handle(new Request(u),{})).status,404)});
