import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {FAR,MAX_REPAIR_AREA_DELTA_PERCENT,PATHS,WEST,governanceRecords,ownerPowerShell,validateManifest} from '../tools/certify-san-antonio-working-geometry-governance.mjs';

const read=p=>JSON.parse(fs.readFileSync(p));
test('the two exception identities and exact West Northwest defect are fixed inputs',()=>{assert.deepEqual(WEST,{name:'West Northwest',globalId:'4c5f3a02-22b0-4af8-8d74-b1bc35a8e03e',reason:'Ring Self-intersection[1627540.43352733 7270466.3643979]'});assert.equal(FAR.globalId,'0a54b85a-6d66-4887-8a12-19dff06070c8');assert.equal(MAX_REPAIR_AREA_DELTA_PERCENT,0.000001);});
test('checked-in reports preserve the certified geometry authority',()=>{const cert=read(PATHS.certJson),hold=read(PATHS.holdJson),manifest=read(PATHS.manifestJson);assert.equal(cert.status,'CERTIFIED');assert.equal(hold.status,'GEOMETRY_GOVERNANCE_HOLD_CITY_CLARIFICATION_REQUIRED');assert.equal(hold.repairedWorkingAuthorityGranted,false);assert.match(hold.evidenceConclusion,/insufficient City evidence/);assert.equal(manifest.records.length,30);assert.deepEqual(manifest.summary,{total:30,originalValid:28,derivedRepair:1,derivedRepairPending:0,hold:1,usableGovernedWorkingGeometry:29});assert.equal(manifest.consolidationPerformed,false);assert.equal(manifest.consumerRegionsCreated,false);assert.equal(manifest.consumerNamesCreated,false);assert.equal(manifest.runtimeMutationPerformed,false);});
test('manifest construction assigns no repaired authority to Far Southwest',()=>{const topology=read('reports/san-antonio-sa-tomorrow-topology-analysis.json');const pending=governanceRecords(topology,false),certified=governanceRecords(topology,true);assert.equal(validateManifest(pending,false),true);assert.equal(validateManifest(certified,true),true);const far=certified.find(x=>x.name===FAR.name),west=certified.find(x=>x.name===WEST.name);assert.equal(far.workingGeometryStatus,'GOVERNANCE_HOLD_NO_CERTIFIED_WORKING_GEOMETRY');assert.equal(far.workingGeometryAuthority,null);assert.equal(west.workingGeometryAuthority,'CERTIFIED_DERIVED_MAKEVALID');});
test('governed implementation uses only Node and GDAL MakeValid and protects prohibited scope',()=>{const source=fs.readFileSync('tools/certify-san-antonio-working-geometry-governance.mjs','utf8');assert.match(source,/ST_MakeValid/);assert.match(source,/ogr2ogr/);for(const forbidden of ['python','app.js','awarenessRadius','consumerRegionName','ST_Buffer','ST_Simplify','ST_Snap'])assert.equal(source.includes(forbidden),false,forbidden);assert.match(source,/consolidationPerformed:false/);assert.match(source,/consumerRegionsCreated:false/);});
test('pending reports are byte deterministic and owner workflow is closed-input PowerShell',()=>{for(const p of [PATHS.certJson,PATHS.holdJson,PATHS.manifestJson]){const bytes=fs.readFileSync(p);assert.ok(crypto.createHash('sha256').update(bytes).digest('hex'));assert.equal(bytes.at(-1),10);}const command=ownerPowerShell();assert.match(command,/GRIDLY_GDAL_BIN/);assert.match(command,/GRIDLY_SA_TOMORROW_GEOJSON/);assert.match(command,/certify:san-antonio-working-geometry-governance/);});
test('certification metadata remains present while artifact identity is independently gated',()=>{assert.equal(fs.existsSync(PATHS.artifact),true);assert.equal(fs.existsSync(PATHS.identity),true);assert.equal(read(PATHS.manifestJson).status,'ANALYSIS_READY_WITH_ONE_HELD_ATOMIC_UNIT');});
