import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {AUDIT_NAMES,EXPECTED_SOURCE,MATERIAL_PERCENT_THRESHOLD,assertExactScope,canonical,classify,extractInvalidityLocation,fingerprint,materialRepair,normalize,ownerPowerShell,parseArgs,percentDelta,serialize} from '../tools/audit-san-antonio-two-polygon-defects.mjs';

test('scope admits exactly the two independently named defects and no third polygon',()=>{assert.deepEqual(AUDIT_NAMES,['Far Southwest','West Northwest']);assert.equal(assertExactScope(AUDIT_NAMES),true);assert.throws(()=>assertExactScope([...AUDIT_NAMES,'Downtown']),/EXACT_TWO_POLYGON_SCOPE_REQUIRED/);assert.throws(()=>assertExactScope([...AUDIT_NAMES].reverse()),/EXACT_TWO_POLYGON_SCOPE_REQUIRED/);});
test('owner-certified source identity and working command are closed inputs',()=>{assert.deepEqual(EXPECTED_SOURCE,{bytes:1864489,sha256:'bf15d7d257d60970c894e590cacb996a15a8796d789e09335860fdb2a6a6e13d'});const args=parseArgs(['--source','owner.geojson','--current-url','https://current','--second-url','https://second']);assert.equal(args.source,'owner.geojson');assert.equal(args.secondUrl,'https://second');assert.throws(()=>parseArgs(['--discover-services']),/UNKNOWN_ARGUMENT/);});
test('ST_IsValidReason location is captured when exposed and null otherwise',()=>{assert.deepEqual(extractInvalidityLocation('Self-intersection[123.25 456.5]'),[123.25,456.5]);assert.deepEqual(extractInvalidityLocation('Ring Self-intersection[-98.1 29.4]'),[-98.1,29.4]);assert.equal(extractInvalidityLocation('Invalid Coordinate'),null);});
test('required SQL retains validity reasons but omits unavailable optional ring metrics',()=>{const source=fs.readFileSync('tools/audit-san-antonio-two-polygon-defects.mjs','utf8');assert.match(source,/ST_IsValidReason\(\$\{geom\}\) AS validityReason/);assert.equal(source.includes(['ST_Num','InteriorRings'].join('')),false);const evidence=normalize({valid:0,validityReason:'Self-intersection[1 2]',geometryType:'MULTIPOLYGON',componentCount:1,squareMiles:1,minX:0,minY:0,maxX:1,maxY:1,centroidX:.5,centroidY:.5,centroidContained:1,surfaceX:.5,surfaceY:.5});assert.equal(evidence.holeCount,null);assert.equal(evidence.ringCount,null);assert.equal(evidence.ringMetricsEvidence,'RING_METRICS_UNAVAILABLE_IN_GOVERNED_GDAL_BUILD');assert.equal(evidence.validityReason,'Self-intersection[1 2]');});
test('before/after area comparison and material repair threshold are deterministic',()=>{assert.equal(percentDelta(100,100.1),0.09999999999999432);assert.equal(percentDelta(0,1),null);assert.equal(MATERIAL_PERCENT_THRESHOLD,0.1);assert.equal(materialRepair(0.1),false);assert.equal(materialRepair(-0.10001),true);});
test('classifications remain independent and corrected second service wins explicitly',()=>{const small={squareMiles:39.4338,componentCount:1},repaired={squareMiles:39.43381,componentCount:1};assert.deepEqual(classify('West Northwest',small,repaired,{correctedGeometry:false},39.403),{classification:'SOURCE_GEOMETRY_INVALID_REPAIRABLE_DETERMINISTICALLY',governance:'CERTIFY_DETERMINISTIC_DERIVED_REPAIR'});assert.deepEqual(classify('Far Southwest',{squareMiles:28.432,componentCount:1},{squareMiles:28.432,componentCount:1},{correctedGeometry:false},23.127),{classification:'OWNER_REVIEW_REQUIRED',governance:'REQUIRE_CITY_SOURCE_CLARIFICATION'});assert.equal(classify('West Northwest',small,repaired,{correctedGeometry:true},39.403).classification,'SECOND_CITY_SERVICE_CONTAINS_CORRECTED_GEOMETRY');});
test('second-service fingerprints and report serialization are deterministic',()=>{assert.equal(fingerprint('00ab'),fingerprint('00AB'));assert.equal(serialize({z:1,a:{d:2,c:3}}),'{\n  "a": {\n    "c": 3,\n    "d": 2\n  },\n  "z": 1\n}\n');assert.deepEqual(Object.keys(canonical({z:1,a:2})),['a','z']);});
test('MakeValid is what-if only and tool has no governed/runtime/app mutation, Python, or consumer creation',()=>{const source=fs.readFileSync('tools/audit-san-antonio-two-polygon-defects.mjs','utf8');assert.match(source,/ST_MakeValid/);assert.match(source,/governedGeometryMutationPerformed:false/);assert.match(source,/consolidationPerformed:false/);assert.match(source,/consumerRegionsCreated:false/);assert.match(source,/consumerNamesCreated:false/);for(const forbidden of ['python','js/app.js','writeFileSync(source','childId','startupZoom','awarenessRadius'])assert.equal(source.toLowerCase().includes(forbidden.toLowerCase()),false,forbidden);assert.match(source,/ogr2ogr/);assert.match(source,/spawnSync/);});
test('owner fallback uses explicit URLs and the governed Windows GDAL/source paths',()=>{const command=ownerPowerShell();assert.match(command,/GRIDLY_GDAL_BIN/);assert.match(command,/QGIS 3\.44\.11/);assert.match(command,/SATomorrowSubAreaPlans-CoSAGIS-Opendata\.geojson/);assert.match(command,/--current-url/);assert.match(command,/--second-url/);});
test('checked-in pending reports remain deterministic and document every non-mutation guard',()=>{const report=JSON.parse(fs.readFileSync('reports/san-antonio-sa-tomorrow-two-polygon-defect-audit.json'));assert.equal(report.status,'OWNER_EXECUTION_REQUIRED');assert.deepEqual(report.scope,AUDIT_NAMES);assert.equal(report.governedGeometryMutationPerformed,false);assert.equal(report.consolidationPerformed,false);assert.equal(report.consumerRegionsCreated,false);assert.equal(report.consumerNamesCreated,false);assert.equal(report.records.length,2);assert.notEqual(report.records[0].defectClassification,report.records[1].defectClassification);});
