import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {REQUIRED_GEOIDS,constructSample,calculateUsableViewport,pointInside,classifyMeasurement,stableJson} from '../tools/audit-statewide-place-presentation-quality.mjs';
const bands=['under_1_square_mile','1_to_under_10_square_miles','10_to_under_100_square_miles','100_plus_square_miles'];
function fixture(){const ids=new Set(REQUIRED_GEOIDS);for(let i=0;i<170;i++)ids.add(`48${String(i+100).padStart(5,'0')}`);const places=[...ids].sort().map((geoid,i)=>({geoid,name:`Place ${i}`,governedType:i%2?'CDP':'INCORPORATED_PLACE',multiCounty:i%7===0,areaBand:bands[i%4],areaSquareMeters:i+1,componentCount:i%6===0?2+(i%5):1,multipart:i%6===0,bounds:{minLon:-100,minLat:30,maxLon:-99,maxLat:31},intpt:{lat:30.5,lon:-99.5},centroid:{lat:30.5,lon:-99.5,contained:i%5!==0},pointOnSurface:{lat:30.5,lon:-99.5},bboxMidpoint:{lat:30.5,lon:-99.5},distancesMeters:{intptToCentroid:i<120?50:1000+i},existingPresentationFocus:{point:{lat:30.5,lon:-99.5}}}));return {schemaVersion:'gridly.statewide-place-presentation-geometry-audit.v1',places,summary:{largestCandidateDisagreements:[...places].sort((a,b)=>b.distancesMeters.intptToCentroid-a.distancesMeters.intptToCentroid).slice(0,25).map(r=>({geoid:r.geoid}))}}}
test('sample is deterministic, deduplicated, governed, and includes mandatory cohorts',()=>{const g=fixture(),a=constructSample(g),b=constructSample(g);assert.deepEqual(a,b);assert.equal(new Set(a.geoids).size,a.count);assert.ok(a.count>=75&&a.count<=150);for(const id of REQUIRED_GEOIDS)assert.ok(a.geoids.includes(id));for(const r of g.summary.largestCandidateDisagreements)assert.ok(a.geoids.includes(r.geoid));for(const r of g.places.filter(x=>x.areaBand==='100_plus_square_miles'))assert.ok(a.geoids.includes(r.geoid));assert.ok(a.records.some(r=>r.sampleCohorts.includes('ordinaryControls')));assert.deepEqual(a.geoids,[...a.geoids].sort())});
test('usable viewport is the largest deterministic unoccluded rectangle',()=>{const r=calculateUsableViewport({left:0,top:0,right:100,bottom:100},[{left:0,top:0,right:100,bottom:20},{left:0,top:80,right:100,bottom:100}]);assert.deepEqual(r,{left:0,top:20,right:100,bottom:80,width:100,height:60,approximation:r.approximation});assert.equal(pointInside({x:50,y:50},r),true);assert.equal(pointInside({x:50,y:10},r),false)});
const base={usableViewport:{left:0,top:0,right:100,bottom:100},targetPixel:{x:50,y:50},geometryBoundsPixel:{},finalCenter:{},finalZoom:13,targetInsideUsableViewport:true,geometryIntersectsUsableViewport:true,geometryBoundsVisibleRatio:.8,normalizedTargetPosition:{x:.5,y:.5}};
test('classification boundaries are explicit and missing measurements fail closed',()=>{assert.equal(classifyMeasurement(base).classification,'PASS');assert.equal(classifyMeasurement({...base,geometryBoundsVisibleRatio:.499}).classification,'REVIEW');assert.equal(classifyMeasurement({...base,geometryBoundsVisibleRatio:.099}).classification,'FAIL');assert.equal(classifyMeasurement({...base,targetInsideUsableViewport:false}).classification,'FAIL');assert.equal(classifyMeasurement({...base,finalZoom:null}).classification,'UNAVAILABLE');assert.equal(classifyMeasurement({...base,geometryBoundsVisibleRatio:.5,normalizedTargetPosition:{x:.1,y:.5}}).classification,'PASS')});
test('stable serialization orders object keys',()=>assert.equal(stableJson({z:1,a:{y:2,x:3}}),'{\n  "a": {\n    "x": 3,\n    "y": 2\n  },\n  "z": 1\n}\n'));
test('audit implementation cannot mutate production runtime',()=>{const source=fs.readFileSync(new URL('../tools/audit-statewide-place-presentation-quality.mjs',import.meta.url),'utf8');const status=fs.readFileSync(new URL('../js/app.js',import.meta.url));assert.ok(status.length>0);assert.doesNotMatch(source,/writeFileSync\([^)]*app\.js|GRIDLY_PLACE_PRESENTATION_URL\s*=/);assert.match(source,/\['GET','HEAD','OPTIONS'\].*route\.continue\(\).*route\.abort\('blockedbyclient'\)/)});
