import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

export const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
export const BASELINE='68c30eb';
export const NAMES=['operational-evidence-closure-summary.json','monitoring-evidence-closure.json','backup-evidence-closure.json','restoration-rehearsal.json','rollback-evidence-closure.json','rollback-rehearsal.json','incident-response-closure.json','launch-day-runbook-readiness.json','owner-evidence-requirements.json','operational-blockers.json','lp170-reconciliation.json','protected-artifact-verification.json','authorization-state.json'];
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;
export const encode=v=>JSON.stringify(stable(v),null,2)+'\n';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const allowed=new Set(['PASS','PARTIAL_EVIDENCE','OWNER_ACTION_REQUIRED','SOURCE_UNAVAILABLE','NOT_CONFIGURED','NOT_TESTED','REHEARSAL_REQUIRED','REHEARSAL_PASS','REHEARSAL_FAIL','NOT_READY','NOT_APPLICABLE']);
const secret=/(?:eyJ[A-Za-z0-9_-]{20,}\.|sb_(?:secret|service|publishable)_|(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?):\/\/|-----BEGIN [A-Z ]*PRIVATE KEY-----|bearer\s+\S+|authorization\s*:|cookie\s*:|(?:refresh|access)[_-]?token\s*[:=]|(?:anon[_-]?key|api[_-]?key|password|service[_-]?role|webhook[_-]?secret|signing[_-]?key)\s*[:=])/i;
export function validateEvidence(v){if(!v||v.schemaVersion!==1||!Array.isArray(v.records))throw Error('LP171 evidence schema is invalid');const raw=JSON.stringify(v);if(secret.test(raw))throw Error('LP171 evidence rejected: secret-shaped material');const seen=new Set();for(const r of v.records){if(!r||!/^[A-Z0-9_.:-]+$/.test(r.identifier||'')||!allowed.has(r.classification)||r.readOnly!==true||r.metadataOnly!==true||typeof r.attestation!=='string'||seen.has(r.identifier)||secret.test(JSON.stringify(r)))throw Error('LP171 evidence record is invalid');seen.add(r.identifier)}return v}
const common={milestone:'LP171',boundary:'EVIDENCE_AND_NON_PRODUCTION_REHEARSAL_ONLY',generatedAt:'NOT_RECORDED_DETERMINISTIC'};
const monitorSignals=['APPLICATION_AVAILABILITY','CLIENT_STARTUP_FAILURES','CRITICAL_JAVASCRIPT_ERRORS','SEARCH_FAILURES','ADDRESS_LOOKUP_FAILURES','DESTINATION_LOOKUP_FAILURES','ROUTING_PROVIDER_FAILURES','SUPABASE_SERVICE_FAILURES','STORAGE_ACCESS_FAILURES','EDGE_FUNCTION_FAILURES','INCIDENT_INGESTION_FAILURES','REPORT_SUBMISSION_FAILURES','AUTHENTICATION_FAILURES','GITHUB_DEPLOYMENT_FAILURES','PUBLIC_ORIGIN_AVAILABILITY','UNEXPECTED_CONFIGURATION_DRIFT'];
const monitorFields=['signalIdentity','signalSource','accessMethod','owner','alertTrigger','alertDestination','responseProcedure','validationMethod','latestValidationResult'];
const rollbackDomains=['STATIC_WEB_RUNTIME','GITHUB_DEPLOYMENT','SUPABASE_EDGE_FUNCTIONS','PRODUCTION_CONFIGURATION','DATABASE_SCHEMA_OR_MIGRATION','STORAGE_METADATA_CONFIGURATION','COUNTY_ACTIVATION_STATE','APP_DISTRIBUTION_RELEASE','PUBLIC_LAUNCH_REVERSAL'];
const rollbackFields=['currentReleaseIdentity','priorKnownGoodReleaseIdentity','artifactPreservation','rollbackProcedure','rollbackOwner','validationProcedure','abortCriteria','forwardFixAlternative','rehearsalEvidence','productionExecutionStatus'];
function evidence(root,supplied){const v=supplied??JSON.parse(fs.readFileSync(path.join(root,'evidence/lp171/owner-attestations.json'),'utf8'));return validateEvidence(v)}
const cls=(map,id)=>map.get(id)?.classification||'SOURCE_UNAVAILABLE';
export function build(root=ROOT,supplied){const ev=evidence(root,supplied),map=new Map(ev.records.map(r=>[r.identifier,r]));
 const monitoring=monitorSignals.map(identifier=>{const requirements=Object.fromEntries(monitorFields.map(f=>[f,cls(map,`MONITORING:${identifier}:${f.toUpperCase()}`)]));return {identifier,requirements,classification:Object.values(requirements).every(x=>x==='PASS')?'PASS':Object.values(requirements).some(x=>x!=='SOURCE_UNAVAILABLE')?'PARTIAL_EVIDENCE':'SOURCE_UNAVAILABLE'}});
 const backupKeys=['PLAN_CAPABILITY','FREQUENCY','RETENTION','PITR','LATEST_STATUS','OWNER','ACCESS_PATH','VERIFICATION_METHOD','LIMITATIONS'];const backup=Object.fromEntries(backupKeys.map(k=>[k.toLowerCase(),cls(map,`BACKUP:${k}`)]));
 const rollback=rollbackDomains.map(identifier=>({identifier,requirements:Object.fromEntries(rollbackFields.map(f=>[f,cls(map,`ROLLBACK:${identifier}:${f.toUpperCase()}`)])),dataChangeMode:identifier==='DATABASE_SCHEMA_OR_MIGRATION'?'UNDETERMINED_REQUIRES_REVERSIBLE_FORWARD_FIX_RESTORE_MANUAL_OR_UNSUPPORTED_CLASSIFICATION':'NOT_APPLICABLE',classification:'OWNER_ACTION_REQUIRED'}));
 const incidentKeys=['PRIMARY_OPERATIONAL_OWNER','BACKUP_OPERATIONAL_OWNER','TECHNICAL_ESCALATION_CONTACT','SUPPORT_CONTACT','SEVERITY_MODEL','INITIAL_TRIAGE','CONTAINMENT_OPTIONS','ROLLBACK_DECISION_AUTHORITY','RESTORATION_DECISION_AUTHORITY','USER_COMMUNICATION_OWNER','EVIDENCE_PRESERVATION_OWNER','POST_INCIDENT_REVIEW_OWNER','ESCALATION_TIMELINE'];const incident=incidentKeys.map(identifier=>({identifier,classification:cls(map,`INCIDENT:${identifier}`)}));
 const protectedPrefixes=['js/app.js',...[162,163,164,165,166,167,168,169,170].map(n=>`reports/lp${n}`)];const files=execFileSync('git',['ls-tree','-r','--name-only',BASELINE],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(f=>protectedPrefixes.some(p=>f===p||f.startsWith(p+'/'))).sort();const artifacts=files.map(file=>{const a=execFileSync('git',['show',`${BASELINE}:${file}`],{cwd:root,maxBuffer:128e6});const b=execFileSync('git',['show',`HEAD:${file}`],{cwd:root,maxBuffer:128e6});return {path:file,baselineSha256:hash(a),currentSha256:hash(b),identitySource:'GIT_BLOB',classification:a.equals(b)?'PASS':'NOT_READY'}});
 const blockers=[['monitoring','SOURCE_UNAVAILABLE'],['backup','SOURCE_UNAVAILABLE'],['incidentResponse','OWNER_ACTION_REQUIRED'],['operationalOwnership','OWNER_ACTION_REQUIRED'],['productionRestoration','NOT_TESTED'],['productionRollback','NOT_TESTED'],['launchDay','OWNER_ACTION_REQUIRED']].map(([area,classification],i)=>({id:`LP171-B${String(i+1).padStart(3,'0')}`,area,classification,owner:'UNKNOWN',remediation:'Complete explicit owner attestation and validate; no production operation is authorized.'}));
 const auth={activation:'NOT_AUTHORIZED',deployment:'NOT_AUTHORIZED',distribution:'NOT_AUTHORIZED',publicLaunch:'NOT_AUTHORIZED',productionRestore:'NOT_AUTHORIZED',productionRollback:'NOT_AUTHORIZED'};
 return {
 'monitoring-evidence-closure.json':{...common,classification:monitoring.every(x=>x.classification==='PASS')?'PASS':'SOURCE_UNAVAILABLE',logsDoNotCertifyAlerting:true,signals:monitoring},
 'backup-evidence-closure.json':{...common,classification:Object.values(backup).every(x=>x==='PASS')?'PASS':'SOURCE_UNAVAILABLE',requirements:backup,configuredBackupDoesNotCertifyRestoration:true,dashboardAttestationRequired:true},
 'restoration-rehearsal.json':{...common,classification:'REHEARSAL_PASS',form:'DETERMINISTIC_TABLETOP_AND_LOCAL_FIXTURE',proof:{procedureComplete:true,requiredInputsIdentified:true,unknownOwnershipExplicit:true,validationDefined:true,abortConditionsDefined:true,productionTargetContacted:false,mutationOccurred:false},productionRestorationStatus:'NOT_TESTED',runbookSections:['INCIDENT_QUALIFICATION','AUTHORIZATION','BACKUP_SELECTION','ISOLATED_TARGET','EVIDENCE_PRESERVATION','DOWNTIME','DATABASE_CONSISTENCY','STORAGE_CONSISTENCY','EDGE_AND_CONFIGURATION_DEPENDENCIES','VALIDATION','ABORT','ESCALATION','USER_COMMUNICATION']},
 'rollback-evidence-closure.json':{...common,classification:'OWNER_ACTION_REQUIRED',domains:rollback,productionRollbackExecuted:false},
 'rollback-rehearsal.json':{...common,classification:'REHEARSAL_PASS',target:'LOCAL_FIXTURE_RELEASE_ARTIFACT',priorReleaseIdentity:`git:${BASELINE}`,artifactPreserved:true,identityValidation:'SHA256_AND_GIT_BLOB',productionContacted:false,mutationOccurred:false,workflowTriggered:false,productionRollbackStatus:'NOT_TESTED'},
 'incident-response-closure.json':{...common,classification:incident.every(x=>x.classification==='PASS')?'PASS':'OWNER_ACTION_REQUIRED',items:incident,unknownOwnersFailClosed:true,severityModel:['SEV1_CRITICAL','SEV2_MAJOR','SEV3_DEGRADED','SEV4_INFORMATIONAL']},
 'launch-day-runbook-readiness.json':{...common,classification:'OWNER_ACTION_REQUIRED',executableOnlyAfterExplicitOwnerAuthorization:true,checklist:['PRE_LAUNCH_VERIFICATION','MONITORING_ACCESS','OWNER_AVAILABILITY','BACKUP_STATUS','ROLLBACK_ARTIFACT','INCIDENT_CHANNEL','SUPPORT_CONTACT','PRODUCTION_ORIGIN','DEPLOYMENT_EVIDENCE','SMOKE_VALIDATION','MONITORING_WINDOW','STOP_LAUNCH_CRITERIA','ROLLBACK_CRITERIA','OWNER_AUTHORIZATION'],authorizesLaunch:false},
 'owner-evidence-requirements.json':{...common,classification:'OWNER_ACTION_REQUIRED',workflow:'npm run capture:lp171:owner-evidence -- -Repository <owner/repo> -ProjectRef <ref>',requirements:['MONITORING_SIGNAL_MATRIX','BACKUP_DASHBOARD_ATTESTATION','ROLLBACK_DOMAIN_OWNERS_AND_RELEASES','INCIDENT_AND_SUPPORT_OWNERS','LAUNCH_DAY_OWNER_AVAILABILITY'],rules:{readOnly:true,metadataOnly:true,atomic:true,secretValuesAllowed:false,powerShell:'5.1'}},
 'operational-blockers.json':{...common,classification:'NOT_READY',blockers},
 'lp170-reconciliation.json':{...common,classification:'NOT_READY',lp170Overall:'NOT_READY',mapping:[{lp170Area:'monitoring',lp171Result:'SOURCE_UNAVAILABLE'},{lp170Area:'backup',lp171Result:'SOURCE_UNAVAILABLE'},{lp170Area:'restoration',lp171Result:'REHEARSAL_PASS',productionStatus:'NOT_TESTED'},{lp170Area:'rollback',lp171Result:'REHEARSAL_PASS',productionStatus:'NOT_TESTED'},{lp170Area:'incidentResponse',lp171Result:'OWNER_ACTION_REQUIRED'}],lp170HistoryModified:false},
 'protected-artifact-verification.json':{...common,classification:artifacts.every(x=>x.classification==='PASS')?'PASS':'NOT_READY',baselineCommit:BASELINE,identitySource:'CANONICAL_GIT_BLOB',crlfWorkingTreeIgnored:true,artifacts},
 'authorization-state.json':{...common,classification:'NOT_READY',authorization:auth,automaticAuthorizationMechanism:false},
 'operational-evidence-closure-summary.json':{...common,overallClassification:'NOT_READY',findings:{monitoring:'SOURCE_UNAVAILABLE',backup:'SOURCE_UNAVAILABLE',restorationRehearsal:'REHEARSAL_PASS',productionRestoration:'NOT_TESTED',rollbackClosure:'OWNER_ACTION_REQUIRED',rollbackRehearsal:'REHEARSAL_PASS',productionRollback:'NOT_TESTED',incidentResponse:'OWNER_ACTION_REQUIRED',launchDay:'OWNER_ACTION_REQUIRED'},authorization:auth,operationsPerformed:{deployments:0,restores:0,rollbacks:0,activations:0,distributionChanges:0,publicLaunches:0,productionMutations:0,workflowTriggers:0}}
 }}
export function write(out,root=ROOT,supplied){const reports=build(root,supplied);fs.mkdirSync(out,{recursive:true});for(const n of NAMES)fs.writeFileSync(path.join(out,n),encode(reports[n]));return reports}
export function verify(root=ROOT){const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'lp171-'));try{const a=path.join(tmp,'a'),b=path.join(tmp,'b');write(a,root);write(b,root);for(const n of NAMES){const x=fs.readFileSync(path.join(a,n)),y=fs.readFileSync(path.join(b,n)),g=fs.readFileSync(path.join(root,'reports/lp171',n));if(!x.equals(y)||!x.equals(g)||x[0]===0xef||x.includes(13))throw Error(`LP171 report drift: ${n}`)}}finally{fs.rmSync(tmp,{recursive:true,force:true})}return true}
if(process.argv[1]===fileURLToPath(import.meta.url)){const mode=process.argv[2]||'audit';if(mode==='verify'){verify();console.log('LP171 deterministic verification: PASS')}else{const r=write(path.join(ROOT,'reports/lp171'));console.log(`LP171 ${mode}: ${r['operational-evidence-closure-summary.json'].overallClassification}`)}}
