DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN('dispatch_private','dispatch_audit','dispatch_projection') AND c.relkind='r' AND NOT(c.relrowsecurity AND c.relforcerowsecurity)) THEN RAISE EXCEPTION 'RLS drift'; END IF;
 IF EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname LIKE 'dispatch_%' AND p.prosecdef AND p.proconfig IS DISTINCT FROM ARRAY['search_path=""']) THEN RAISE EXCEPTION 'search_path drift'; END IF;
 IF (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_roles r ON r.oid=p.proowner WHERE n.nspname LIKE 'dispatch_%' AND p.prosecdef AND r.rolname='postgres')<>1 THEN RAISE EXCEPTION 'Auth bridge owner drift'; END IF;
 IF EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='dispatch_private' AND p.proname IN('current_actor_id','current_session_id') AND p.prosecdef) THEN RAISE EXCEPTION 'identity bridge drift'; END IF;
 IF has_table_privilege('authenticated','dispatch_private.operational_records','SELECT') OR has_column_privilege('authenticated','dispatch_private.operational_records','private_payload','SELECT') OR has_any_column_privilege('anon','dispatch_projection.projection_candidates','SELECT') OR has_any_column_privilege('authenticated','dispatch_projection.projection_candidates','SELECT') THEN RAISE EXCEPTION 'raw grant drift'; END IF;
 IF has_function_privilege('authenticated','dispatch_private.phase26_command(text,jsonb)','EXECUTE') THEN RAISE EXCEPTION 'legacy bypass'; END IF;
 IF has_function_privilege('authenticated','dispatch_private.phase28_partial_command(text,jsonb)','EXECUTE') OR has_function_privilege('authenticated','dispatch_private.pseudonymize_user(uuid)','EXECUTE') OR has_function_privilege('authenticated','dispatch_private.check_proof(uuid,uuid,text,jsonb,uuid)','EXECUTE') THEN RAISE EXCEPTION 'closure helper bypass'; END IF;
 IF has_any_column_privilege('authenticated','dispatch_private.auth_check_context','SELECT') OR has_table_privilege('authenticated','dispatch_private.auth_check_context','INSERT') OR has_table_privilege('authenticated','dispatch_private.erasure_context','INSERT') OR has_any_column_privilege('authenticated','dispatch_private.approval_proofs','SELECT') THEN RAISE EXCEPTION 'proof/context exposure'; END IF;
 IF EXISTS(SELECT 1 FROM dispatch_private.auth_check_context) OR EXISTS(SELECT 1 FROM dispatch_private.erasure_context) THEN RAISE EXCEPTION 'transaction context residue'; END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_proc WHERE oid='dispatch_private.has_live_aal2()'::regprocedure AND pronargs=0 AND prorettype='boolean'::regtype AND proowner=(SELECT oid FROM pg_roles WHERE rolname='postgres')) THEN RAISE EXCEPTION 'bounded bridge contract drift'; END IF;
 IF has_schema_privilege('dispatch_function_owner','dispatch_private','CREATE') THEN RAISE EXCEPTION 'DDL grant drift'; END IF;
 IF has_any_column_privilege('dispatch_function_owner','auth.users','SELECT') OR has_any_column_privilege('dispatch_function_owner','auth.sessions','SELECT') OR has_any_column_privilege('dispatch_function_owner','auth.mfa_factors','SELECT') THEN RAISE EXCEPTION 'Auth table grant drift'; END IF;
 IF to_regclass('dispatch_api.responder_public_projection') IS NOT NULL THEN RAISE EXCEPTION 'permanent compatibility forbidden'; END IF;
 IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='dispatch_function_owner' AND (rolcanlogin OR rolsuper OR rolcreatedb OR rolcreaterole OR rolinherit OR NOT rolbypassrls)) THEN RAISE EXCEPTION 'owner role drift'; END IF;
END $$;
SELECT 'PHASE28_POSTFLIGHT_PASS';
DO $post$ DECLARE r text; BEGIN
 IF (SELECT count(*) FROM pg_roles WHERE rolname LIKE 'dispatch\_%' ESCAPE '\')<>3 THEN RAISE EXCEPTION 'POSTFLIGHT roles'; END IF;
 FOREACH r IN ARRAY ARRAY['dispatch_delivery_connection','dispatch_delivery_transport'] LOOP
 IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r AND NOT rolinherit AND NOT rolbypassrls AND NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole AND NOT rolreplication AND rolcanlogin=(r='dispatch_delivery_connection')) THEN RAISE EXCEPTION 'POSTFLIGHT transport attributes'; END IF; END LOOP;
 IF (SELECT count(*) FROM pg_auth_members WHERE member=(SELECT oid FROM pg_roles WHERE rolname='dispatch_delivery_connection'))<>1 OR NOT EXISTS(SELECT 1 FROM pg_auth_members WHERE member=(SELECT oid FROM pg_roles WHERE rolname='dispatch_delivery_connection') AND roleid=(SELECT oid FROM pg_roles WHERE rolname='dispatch_delivery_transport') AND NOT admin_option AND NOT inherit_option AND set_option) THEN RAISE EXCEPTION 'POSTFLIGHT membership'; END IF;
 IF EXISTS(SELECT 1 FROM pg_auth_members WHERE member=(SELECT oid FROM pg_roles WHERE rolname='postgres') AND (set_option OR inherit_option) AND roleid IN(SELECT oid FROM pg_roles WHERE rolname LIKE 'dispatch\_%' ESCAPE '\')) THEN RAISE EXCEPTION 'POSTFLIGHT elevated installer membership'; END IF;
 IF has_schema_privilege('dispatch_delivery_connection','public','CREATE') OR has_database_privilege('dispatch_delivery_connection','postgres','CREATE') THEN RAISE EXCEPTION 'POSTFLIGHT connection DDL'; END IF;
 IF EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname LIKE 'dispatch\_%' ESCAPE '\' AND c.relkind IN('r','p') AND (has_any_column_privilege('dispatch_delivery_connection',c.oid,'SELECT') OR has_table_privilege('dispatch_delivery_transport',c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER'))) THEN RAISE EXCEPTION 'POSTFLIGHT transport table access'; END IF;
 IF EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname LIKE 'dispatch\_%' ESCAPE '\' AND has_function_privilege('dispatch_delivery_transport',p.oid,'EXECUTE') AND p.proname NOT IN('invitation_claim_send','invitation_transport_result')) THEN RAISE EXCEPTION 'POSTFLIGHT transport command access'; END IF;
 IF (SELECT count(*) FROM dispatch_private.report_subtypes WHERE public_eligible)<>18 OR (SELECT count(*) FROM dispatch_private.department_report_policies)<>104 OR (SELECT count(*) FROM dispatch_private.capability_catalog WHERE NOT legacy)<>18 THEN RAISE EXCEPTION 'POSTFLIGHT registry'; END IF;
 IF EXISTS(SELECT 1 FROM dispatch_private.report_contract_versions WHERE publishing_enabled) OR EXISTS(SELECT 1 FROM dispatch_private.organizations) OR EXISTS(SELECT 1 FROM dispatch_private.organization_units) OR EXISTS(SELECT 1 FROM dispatch_private.capability_grants) OR EXISTS(SELECT 1 FROM dispatch_private.organization_invitations) THEN RAISE EXCEPTION 'POSTFLIGHT activation forbidden'; END IF;
 IF to_regclass('dispatch_private.reviewer_authorizations') IS NULL OR to_regprocedure('dispatch_private.report_review_attempt_eligible(uuid,uuid,uuid,uuid)') IS NULL OR to_regclass('dispatch_private.invitation_delivery_suppressions') IS NULL THEN RAISE EXCEPTION 'POSTFLIGHT governance objects'; END IF;
 IF EXISTS(SELECT 1 FROM pg_default_acl d CROSS JOIN LATERAL aclexplode(d.defaclacl) a WHERE d.defaclrole=(SELECT oid FROM pg_roles WHERE rolname='postgres') AND d.defaclnamespace IN(0,(SELECT oid FROM pg_namespace WHERE nspname='public')) AND a.grantee IN(0,(SELECT oid FROM pg_roles WHERE rolname='anon'),(SELECT oid FROM pg_roles WHERE rolname='authenticated'),(SELECT oid FROM pg_roles WHERE rolname='service_role')) AND d.defaclobjtype IN('r','S')) THEN RAISE EXCEPTION 'POSTFLIGHT future table ACL'; END IF;
 IF to_regnamespace('gridly_rehearsal') IS NOT NULL OR to_regnamespace('report_retention') IS NOT NULL OR EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN('r','p','v','m')) THEN RAISE EXCEPTION 'POSTFLIGHT unexpected application namespace'; END IF;
END $post$;