-- Phase A: inside installer transaction; no mutation before this block.
DO $precheck$ DECLARE n text; r text;
BEGIN
 IF current_user<>'postgres' OR current_database()<>'postgres' THEN RAISE EXCEPTION 'INSTALL_REFUSED administrator/database'; END IF;
 IF current_setting('dispatch_install.bound_project_ref',true) IS DISTINCT FROM 'cmrrvwgkgjhmdugzhnrh' THEN RAISE EXCEPTION 'INSTALL_REFUSED project binding'; END IF;
 IF current_setting('server_version_num')::int/10000<>17 THEN RAISE EXCEPTION 'INSTALL_REFUSED PostgreSQL major'; END IF;
 IF current_setting('server_version_num')::int<170011 THEN RAISE EXCEPTION 'INSTALL_REFUSED PostgreSQL minimum 17.11'; END IF;
 IF EXISTS(SELECT 1 FROM pg_namespace WHERE nspname LIKE 'dispatch\_%' ESCAPE '\') OR EXISTS(SELECT 1 FROM pg_roles WHERE rolname LIKE 'dispatch\_%' ESCAPE '\') THEN RAISE EXCEPTION 'INSTALL_REFUSED existing Dispatch namespace/role'; END IF;
 IF EXISTS(SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN('r','p','v','m','S','f')) OR EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public') THEN RAISE EXCEPTION 'INSTALL_REFUSED nonempty public'; END IF;
 IF EXISTS(SELECT 1 FROM pg_namespace WHERE nspname NOT IN('public','auth','extensions','graphql','graphql_public','realtime','storage','vault','supabase_migrations','_supabase','_analytics','net','pgsodium','pgsodium_masks','_realtime','pgbouncer','supabase_functions') AND nspname NOT LIKE 'pg\_%' ESCAPE '\' AND nspname<>'information_schema') THEN RAISE EXCEPTION 'INSTALL_REFUSED unexpected application namespace %',(SELECT string_agg(nspname,',') FROM pg_namespace WHERE nspname NOT IN('public','auth','extensions','graphql','graphql_public','realtime','storage','vault','supabase_migrations','_supabase','_analytics','net','pgsodium','pgsodium_masks','_realtime','pgbouncer','supabase_functions') AND nspname NOT LIKE 'pg\_%' ESCAPE '\' AND nspname<>'information_schema'); END IF;
 FOREACH n IN ARRAY ARRAY['auth','extensions','storage','realtime'] LOOP IF to_regnamespace(n) IS NULL THEN RAISE EXCEPTION 'INSTALL_REFUSED platform schema %',n; END IF; END LOOP;
 FOREACH r IN ARRAY ARRAY['anon','authenticated','service_role','authenticator','supabase_auth_admin','supabase_admin'] LOOP IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r) THEN RAISE EXCEPTION 'INSTALL_REFUSED platform role %',r; END IF; END LOOP;
 IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='postgres' AND rolcreaterole AND rolcreatedb) OR EXISTS(SELECT 1 FROM pg_roles WHERE rolname IN('anon','authenticated','authenticator') AND (rolsuper OR rolbypassrls)) THEN RAISE EXCEPTION 'INSTALL_REFUSED platform attributes'; END IF;
 IF to_regclass('auth.users') IS NULL OR to_regclass('auth.sessions') IS NULL OR to_regclass('auth.mfa_factors') IS NULL THEN RAISE EXCEPTION 'INSTALL_REFUSED Auth dependencies'; END IF;
 IF EXISTS(SELECT 1 FROM auth.users) OR EXISTS(SELECT 1 FROM storage.objects) OR EXISTS(SELECT 1 FROM storage.buckets) THEN RAISE EXCEPTION 'INSTALL_REFUSED nonempty platform application data'; END IF;
 IF to_regprocedure('extensions.gen_random_uuid()') IS NULL OR to_regprocedure('extensions.digest(text,text)') IS NULL OR NOT EXISTS(SELECT 1 FROM pg_extension WHERE extname='pgcrypto') OR NOT EXISTS(SELECT 1 FROM pg_extension WHERE extname='pg_stat_statements') THEN RAISE EXCEPTION 'INSTALL_REFUSED extension/helper'; END IF;
 -- Refuse unreviewed grantors/grantees instead of silently erasing arbitrary ACLs.
 IF EXISTS(SELECT 1 FROM pg_default_acl d CROSS JOIN LATERAL aclexplode(d.defaclacl) a LEFT JOIN pg_namespace ns ON ns.oid=d.defaclnamespace WHERE (ns.nspname='public' OR (d.defaclnamespace=0 AND d.defaclrole=(SELECT oid FROM pg_roles WHERE rolname='postgres'))) AND (pg_get_userbyid(d.defaclrole) NOT IN('postgres','supabase_admin') OR a.grantee NOT IN(0,(SELECT oid FROM pg_roles WHERE rolname='postgres'),(SELECT oid FROM pg_roles WHERE rolname='supabase_admin'),(SELECT oid FROM pg_roles WHERE rolname='anon'),(SELECT oid FROM pg_roles WHERE rolname='authenticated'),(SELECT oid FROM pg_roles WHERE rolname='service_role')))) THEN RAISE EXCEPTION 'INSTALL_REFUSED unknown default privilege baseline'; END IF;
END $precheck$;
