import test from 'node:test';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {readFileSync,writeFileSync} from 'node:fs';
const docker=process.env.P29_DOCKER,project=process.env.P29_PROJECT_ID,evidence=process.env.P29_EVIDENCE_DIR;if(process.env.P29_API_URL!=='http://127.0.0.1:54321'||!/^gridly-dispatch-phase29-[a-f0-9]{12}$/.test(project??''))throw Error('LOCAL_ONLY');
const read=n=>readFileSync(new URL(n,import.meta.url),'utf8');const binding="SELECT set_config('dispatch_install.bound_project_ref','cmrrvwgkgjhmdugzhnrh',false);\n";
function sql(input,fail=false){const r=spawnSync(docker,['exec','-i','supabase_db_'+project,'psql','-X','-At','-v','ON_ERROR_STOP=1','-U','postgres','-d','postgres'],{input,encoding:'utf8',windowsHide:true,maxBuffer:20e6});if(!fail)assert.equal(r.status,0,r.stderr+'\n'+r.stdout);else assert.notEqual(r.status,0);return r;}
const checks=[];const install=read('install.sql'),rollback=read('rollback.sql');
const catalog="SELECT jsonb_build_object('tables',(SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl,'rls',c.relrowsecurity,'forced',c.relforcerowsecurity) ORDER BY n.nspname,c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN('auth','storage','realtime','vault')),'defaults',(SELECT jsonb_agg(jsonb_build_object('owner',pg_get_userbyid(d.defaclrole),'schema',n.nspname,'type',d.defaclobjtype,'acl',d.defaclacl) ORDER BY n.nspname,d.defaclrole,d.defaclobjtype) FROM pg_default_acl d JOIN pg_namespace n ON n.oid=d.defaclnamespace WHERE n.nspname IN('auth','storage','realtime','vault')));";
let platform;
test('clean standard Supabase baseline without fixtures',()=>{platform=sql(catalog).stdout.trim();assert.equal(sql("SELECT count(*) FROM pg_namespace WHERE nspname IN('gridly_rehearsal','report_retention','dispatch_private')").stdout.trim(),'0');checks.push('no disposable dependencies')});
for(const [name,setup,error] of [['wrong project',"SELECT set_config('dispatch_install.bound_project_ref','wrong',false);",'project binding'],['populated Dispatch',"CREATE SCHEMA dispatch_private; CREATE TABLE dispatch_private.existing(id int); INSERT INTO dispatch_private.existing VALUES(1);",'existing Dispatch'],['conflicting role','CREATE ROLE dispatch_delivery_connection NOLOGIN;','existing Dispatch'],['incompatible prior namespace','CREATE SCHEMA dispatch_audit;','existing Dispatch'],['unexpected public record','CREATE TABLE public.unexpected(id int); INSERT INTO public.unexpected VALUES(1);','nonempty public'],['unexpected owner defaults',"CREATE ROLE unexpected_grantee; ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT SELECT ON TABLES TO unexpected_grantee;",'unknown default']])test(name+' fails atomically',()=>{const r=sql(binding+'BEGIN;'+setup+install,true);assert.match(r.stderr,new RegExp(error));assert.equal(sql("SELECT count(*) FROM pg_namespace WHERE nspname LIKE 'dispatch\\_%' ESCAPE '\\'").stdout.trim(),'0');assert.equal(sql("SELECT count(*) FROM pg_roles WHERE rolname LIKE 'dispatch\\_%' ESCAPE '\\'").stdout.trim(),'0');checks.push(name+' atomic refusal')});
test('version condition is executed and rejects unsupported version',()=>{const pre=read('preflight.sql').replace("current_setting('server_version_num')::int/10000<>17","160011/10000<>17");assert.match(sql(binding+pre,true).stderr,/PostgreSQL major/);checks.push('unsupported version refusal')});
test('global browser defaults cannot leak into future private application tables',()=>{const probe=install.replace('COMMIT;',()=>"CREATE TABLE dispatch_private.future_global_probe(id int); DO $$ BEGIN IF has_table_privilege('anon','dispatch_private.future_global_probe','TRUNCATE,REFERENCES,TRIGGER,MAINTAIN') THEN RAISE EXCEPTION 'global default leaked'; END IF; END $$; ROLLBACK;");sql(binding+"BEGIN; ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT TRUNCATE,REFERENCES,TRIGGER,MAINTAIN ON TABLES TO anon;"+probe);assert.equal(sql("SELECT count(*) FROM pg_roles WHERE rolname LIKE 'dispatch%'").stdout.trim(),'0');checks.push('global defaults hardened and transaction rolled back')});
test('full clean install, inventories and frozen postflight pass',()=>{sql(binding+install);assert.equal(sql(catalog).stdout.trim(),platform);writeFileSync(evidence+'/platform-before-after.json',JSON.stringify({unchanged:true,catalog:JSON.parse(platform)},null,2));checks.push('clean install and platform catalog unchanged')});
test('future public table has no browser table privileges',()=>{sql("BEGIN; CREATE TABLE public.future_acl_probe(id int); DO $$ DECLARE r text; BEGIN FOREACH r IN ARRAY ARRAY['anon','authenticated','service_role'] LOOP IF has_table_privilege(r,'public.future_acl_probe','SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER,MAINTAIN') THEN RAISE EXCEPTION 'future privilege'; END IF; END LOOP; END $$; ROLLBACK;");checks.push('future object ACL denial')});
test('external view and evidence-bearing state refuse destructive rollback',()=>{const view=sql(binding+"BEGIN; CREATE VIEW public.external_reference AS SELECT record_id FROM dispatch_private.report_details;"+rollback,true);assert.match(view.stderr,/ROLLBACK_REFUSED external dependency/);const evidence=sql(binding+"BEGIN; INSERT INTO dispatch_private.organizations(display_name,legal_name,organization_type) VALUES('LOCAL REFUSAL','LOCAL REFUSAL','MUNICIPALITY');"+rollback,true);assert.match(evidence.stderr,/ROLLBACK_REFUSED evidence-bearing/);assert.equal(sql("SELECT count(*) FROM dispatch_private.organizations").stdout.trim(),'0');checks.push('external reference and evidence rollback refusal')});
test('failure after hardening rolls back roles objects and ACL mutations',()=>{sql(binding+rollback);const before=sql('SELECT coalesce(jsonb_agg(to_jsonb(d))::text,\'null\') FROM pg_default_acl d').stdout.trim();const broken=install.replace('COMMIT;',()=> 'DO $$ BEGIN RAISE EXCEPTION \'INJECTED_FAILURE\'; END $$; COMMIT;');assert.match(sql(binding+broken,true).stderr,/ERROR:\s+INJECTED_FAILURE/);assert.equal(sql("SELECT count(*) FROM pg_roles WHERE rolname LIKE 'dispatch\\_%' ESCAPE '\\'").stdout.trim(),'0');assert.equal(sql('SELECT coalesce(jsonb_agg(to_jsonb(d))::text,\'null\') FROM pg_default_acl d').stdout.trim(),before);checks.push('transactional failure rollback')});
test('empty rollback and reapply pass',()=>{sql(binding+install);sql(binding+rollback);sql(binding+install);checks.push('empty rollback reapply')});
test('exact inventory persisted for owner review',()=>{assert.equal(sql("SELECT count(*) FROM pg_roles WHERE rolname LIKE 'dispatch%'").stdout.trim(),'3');const c=sql("SELECT jsonb_build_object('memberships',(SELECT jsonb_agg(jsonb_build_object('role',pg_get_userbyid(roleid),'member',pg_get_userbyid(member),'grantor',pg_get_userbyid(grantor),'admin',admin_option,'inherit',inherit_option,'set',set_option) ORDER BY roleid,member,grantor) FROM pg_auth_members WHERE roleid IN(SELECT oid FROM pg_roles WHERE rolname LIKE 'dispatch%')),'roles',(SELECT jsonb_agg(jsonb_build_object('name',rolname,'login',rolcanlogin,'inherit',rolinherit,'bypass',rolbypassrls,'super',rolsuper,'createDb',rolcreatedb,'createRole',rolcreaterole) ORDER BY rolname) FROM pg_roles WHERE rolname LIKE 'dispatch%'),'tables',(SELECT jsonb_agg(jsonb_build_object('name',n.nspname||'.'||c.relname,'acl',c.relacl,'rls',c.relrowsecurity,'forced',c.relforcerowsecurity) ORDER BY n.nspname,c.relname) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname LIKE 'dispatch%' AND c.relkind='r'),'functions',(SELECT jsonb_agg(jsonb_build_object('signature',p.oid::regprocedure::text,'owner',pg_get_userbyid(p.proowner),'acl',p.proacl,'definer',p.prosecdef,'settings',p.proconfig) ORDER BY p.oid::regprocedure::text) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname LIKE 'dispatch%'));");writeFileSync(evidence+'/installed-inventory.json',c.stdout.trim()+'\n');checks.push('exact object role grant inventory');writeFileSync(evidence+'/installer-results.json',JSON.stringify({status:checks.length===15?'PASS':'FAIL',passed:checks.length,failed:15-checks.length,checks},null,2)+'\n')});