-- LOCAL DISPOSABLE PROTOTYPE ONLY
-- NOT A PRODUCTION MIGRATION

BEGIN;
DROP SCHEMA IF EXISTS dispatch_phase21_local CASCADE;
DROP ROLE IF EXISTS dispatch_phase21_public;
DROP ROLE IF EXISTS dispatch_phase21_app;
COMMIT;
