\set ON_ERROR_STOP on
-- LOCAL DISPOSABLE REHEARSAL ONLY - NOT AUTHORIZED FOR PRODUCTION EXECUTION
BEGIN;
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='dispatch_function_owner') THEN
 CREATE ROLE dispatch_function_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT BYPASSRLS;
END IF; END $$;
CREATE SCHEMA dispatch_private; CREATE SCHEMA dispatch_audit; CREATE SCHEMA dispatch_projection; CREATE SCHEMA dispatch_api;
REVOKE ALL ON SCHEMA dispatch_private,dispatch_audit,dispatch_projection,dispatch_api FROM PUBLIC;

CREATE TYPE dispatch_private.profile_status AS ENUM('ACTIVE','DISABLED');
CREATE TYPE dispatch_private.organization_status AS ENUM('PENDING','ACTIVE','SUSPENDED','CLOSED');
CREATE TYPE dispatch_private.organization_type AS ENUM('FIRE','EMS','LAW_ENFORCEMENT','EMERGENCY_MANAGEMENT','UTILITY','FLEET','TRUCKING','MUNICIPALITY','SCHOOL_DISTRICT','CONTRACTOR','PRIVATE_COMPANY','INDUSTRIAL_OPERATOR','TRANSPORTATION_OPERATOR','INFRASTRUCTURE_OPERATOR','OTHER');
CREATE TYPE dispatch_private.verification_level AS ENUM('UNVERIFIED','VERIFIED_ORGANIZATION','VERIFIED_PUBLIC_ENTITY');
CREATE TYPE dispatch_private.membership_status AS ENUM('INVITED','ACTIVE','SUSPENDED','REVOKED');
CREATE TYPE dispatch_private.role_template_key AS ENUM('OWNER','ORGANIZATION_ADMIN','SUPERVISOR','OPERATOR','VIEWER');
CREATE TYPE dispatch_private.invitation_status AS ENUM('PENDING','ACCEPTED','DECLINED','EXPIRED','REVOKED');
CREATE TYPE dispatch_private.permission_scope AS ENUM('ORGANIZATION','PLATFORM');
CREATE TYPE dispatch_private.scope_type AS ENUM('COUNTY','MULTI_COUNTY','STATEWIDE','SERVICE_TERRITORY','CORRIDOR','ROUTE','FACILITY','SITE','NON_GEOGRAPHIC');
CREATE TYPE dispatch_private.scope_status AS ENUM('ACTIVE','SUSPENDED','REVOKED');
CREATE TYPE dispatch_private.capability_status AS ENUM('PENDING','ACTIVE','SUSPENDED','REVOKED');
CREATE TYPE dispatch_private.record_type AS ENUM('CONDITION','HAZARD','PLANNED_WORK','OPERATIONAL_NOTICE');
CREATE TYPE dispatch_private.record_status AS ENUM('DRAFT','OPEN','IN_PROGRESS','MONITORING','CLOSED','CANCELLED');
CREATE TYPE dispatch_private.record_priority AS ENUM('LOW','NORMAL','HIGH','CRITICAL');
CREATE TYPE dispatch_private.assignment_status AS ENUM('ASSIGNED','CLEARED');
CREATE TYPE dispatch_private.source_class AS ENUM('COMMUNITY','OFFICIAL_PUBLIC','ORGANIZATION','PRIVATE_OPERATIONAL');
CREATE TYPE dispatch_private.visibility_class AS ENUM('PRIVATE','ORGANIZATION','PROJECTION_CANDIDATE','PUBLIC_PROJECTION');
CREATE TYPE dispatch_private.review_state AS ENUM('NOT_SUBMITTED','PENDING_REVIEW','APPROVED','REJECTED','WITHDRAWN');
CREATE TYPE dispatch_private.projection_status AS ENUM('SUBMITTED','APPROVED','REJECTED','WITHDRAWN');
CREATE TYPE dispatch_private.ownership_transfer_status AS ENUM('PENDING','ACCEPTED','CANCELLED');
CREATE TYPE dispatch_private.recovery_status AS ENUM('FIRST_APPROVED','RECOVERED','CANCELLED');
CREATE TYPE dispatch_audit.receipt_status AS ENUM('ACCEPTED');
CREATE TYPE dispatch_private.audit_event_type AS ENUM('ORGANIZATION_CREATED','ORGANIZATION_UPDATED','ORGANIZATION_ACTIVATED','ORGANIZATION_SUSPENDED','ORGANIZATION_REINSTATED','ORGANIZATION_CLOSED','MEMBER_INVITED','INVITATION_ACCEPTED','INVITATION_DECLINED','INVITATION_EXPIRED','MEMBER_SUSPENDED','MEMBER_REACTIVATED','MEMBER_REVOKED','MEMBERSHIP_LEFT','ROLE_CHANGED','OWNERSHIP_TRANSFER_INITIATED','OWNERSHIP_TRANSFER_CANCELLED','OWNERSHIP_TRANSFERRED','OWNERSHIP_RECOVERED','SCOPE_GRANTED','SCOPE_REVOKED','CAPABILITY_GRANTED','CAPABILITY_SUSPENDED','CAPABILITY_REVOKED','RECORD_CREATED','RECORD_UPDATED','RECORD_ASSIGNED','RECORD_CLOSED','RECORD_CANCELLED','PROJECTION_SUBMITTED','PROJECTION_APPROVED','PROJECTION_REJECTED','PROJECTION_PUBLISHED','PROJECTION_WITHDRAWN','SETTINGS_CHANGED');

CREATE TABLE dispatch_private.profiles(user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE RESTRICT,display_name text NOT NULL,status dispatch_private.profile_status NOT NULL DEFAULT 'ACTIVE',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE dispatch_private.organizations(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),display_name text NOT NULL,legal_name text NOT NULL,organization_type dispatch_private.organization_type NOT NULL,status dispatch_private.organization_status NOT NULL DEFAULT 'PENDING',verification_level dispatch_private.verification_level NOT NULL DEFAULT 'UNVERIFIED',governance_revision integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE dispatch_private.role_templates(role_key dispatch_private.role_template_key PRIMARY KEY,description text NOT NULL);
CREATE TABLE dispatch_private.permissions(permission_key text PRIMARY KEY,scope_class dispatch_private.permission_scope NOT NULL);
CREATE TABLE dispatch_private.role_permissions(role_key dispatch_private.role_template_key REFERENCES dispatch_private.role_templates,permission_key text REFERENCES dispatch_private.permissions,PRIMARY KEY(role_key,permission_key));
CREATE TABLE dispatch_private.organization_memberships(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,user_id uuid NOT NULL REFERENCES dispatch_private.profiles,status dispatch_private.membership_status NOT NULL,role_template dispatch_private.role_template_key NOT NULL,revision integer NOT NULL DEFAULT 0,activated_at timestamptz,UNIQUE(organization_id,id));
CREATE UNIQUE INDEX organization_memberships_live_pair ON dispatch_private.organization_memberships(organization_id,user_id) WHERE status IN('INVITED','ACTIVE','SUSPENDED');
CREATE UNIQUE INDEX organization_memberships_one_owner ON dispatch_private.organization_memberships(organization_id) WHERE status='ACTIVE' AND role_template='OWNER';
CREATE TABLE dispatch_private.organization_invitations(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,target_identity text NOT NULL,role_template dispatch_private.role_template_key NOT NULL,token_digest bytea NOT NULL UNIQUE CHECK(octet_length(token_digest)=32),status dispatch_private.invitation_status NOT NULL DEFAULT 'PENDING',expires_at timestamptz NOT NULL,created_by_membership_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),accepted_at timestamptz,revoked_at timestamptz,FOREIGN KEY(organization_id,created_by_membership_id) REFERENCES dispatch_private.organization_memberships(organization_id,id));
CREATE UNIQUE INDEX organization_invitations_pending ON dispatch_private.organization_invitations(organization_id,target_identity) WHERE status='PENDING';
CREATE TABLE dispatch_private.operational_scopes(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,scope_type dispatch_private.scope_type NOT NULL,status dispatch_private.scope_status NOT NULL DEFAULT 'ACTIVE',version integer NOT NULL DEFAULT 1,label text NOT NULL,source_reference text NOT NULL,valid_until timestamptz,UNIQUE(organization_id,id),UNIQUE(id,version));
CREATE TABLE dispatch_private.operational_scope_members(operational_scope_id uuid NOT NULL,scope_version integer NOT NULL,ordinal integer NOT NULL,member_kind text NOT NULL,member_identifier text NOT NULL,PRIMARY KEY(operational_scope_id,scope_version,member_kind,member_identifier),FOREIGN KEY(operational_scope_id,scope_version) REFERENCES dispatch_private.operational_scopes(id,version));
CREATE TABLE dispatch_private.platform_admin_grants(user_id uuid NOT NULL REFERENCES dispatch_private.profiles,permission_key text NOT NULL REFERENCES dispatch_private.permissions,active boolean NOT NULL DEFAULT true,granted_by_user_id uuid NOT NULL REFERENCES dispatch_private.profiles,PRIMARY KEY(user_id,permission_key));
CREATE TABLE dispatch_private.capability_grants(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,capability_key text NOT NULL CHECK(capability_key IN('awareness.condition.publish','awareness.hazard.publish','awareness.planned_work.publish','awareness.official_notice.publish','awareness.road_closure.publish')),operational_scope_id uuid NOT NULL,operational_scope_version integer NOT NULL,status dispatch_private.capability_status NOT NULL DEFAULT 'PENDING',valid_from timestamptz NOT NULL DEFAULT now(),valid_until timestamptz,revision integer NOT NULL DEFAULT 0,granted_by_platform_actor uuid NOT NULL REFERENCES dispatch_private.profiles,UNIQUE(organization_id,id),FOREIGN KEY(operational_scope_id,operational_scope_version) REFERENCES dispatch_private.operational_scopes(id,version));
CREATE TABLE dispatch_private.operational_records(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,operational_scope_id uuid NOT NULL,record_type dispatch_private.record_type NOT NULL,status dispatch_private.record_status NOT NULL DEFAULT 'DRAFT',priority dispatch_private.record_priority NOT NULL DEFAULT 'NORMAL',title text NOT NULL,private_payload jsonb NOT NULL DEFAULT '{}',current_revision integer NOT NULL DEFAULT 1,created_by_membership_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,id),FOREIGN KEY(organization_id,operational_scope_id) REFERENCES dispatch_private.operational_scopes(organization_id,id),FOREIGN KEY(organization_id,created_by_membership_id) REFERENCES dispatch_private.organization_memberships(organization_id,id));
CREATE TABLE dispatch_audit.record_revisions(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL,record_id uuid NOT NULL,revision_number integer NOT NULL,snapshot jsonb NOT NULL,actor_user_id uuid NOT NULL REFERENCES dispatch_private.profiles,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,record_id,revision_number),FOREIGN KEY(organization_id,record_id) REFERENCES dispatch_private.operational_records(organization_id,id));
CREATE TABLE dispatch_private.record_assignments(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL,record_id uuid NOT NULL,assigned_membership_id uuid NOT NULL,status dispatch_private.assignment_status NOT NULL DEFAULT 'ASSIGNED',created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(organization_id,record_id) REFERENCES dispatch_private.operational_records(organization_id,id),FOREIGN KEY(organization_id,assigned_membership_id) REFERENCES dispatch_private.organization_memberships(organization_id,id));
CREATE TABLE dispatch_private.record_provenance(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL,record_id uuid NOT NULL,revision_number integer NOT NULL,source_class dispatch_private.source_class NOT NULL,capability_grant_id uuid,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(organization_id,record_id,revision_number) REFERENCES dispatch_audit.record_revisions(organization_id,record_id,revision_number));
CREATE TABLE dispatch_private.ownership_transfers(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,from_membership_id uuid NOT NULL,to_membership_id uuid NOT NULL,status dispatch_private.ownership_transfer_status NOT NULL DEFAULT 'PENDING',expected_org_revision integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX ownership_transfers_one_pending ON dispatch_private.ownership_transfers(organization_id) WHERE status='PENDING';
CREATE TABLE dispatch_private.ownership_recovery_cases(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL REFERENCES dispatch_private.organizations,target_membership_id uuid NOT NULL,status dispatch_private.recovery_status NOT NULL DEFAULT 'FIRST_APPROVED',organization_revision integer NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE dispatch_private.recovery_approvals(case_id uuid NOT NULL REFERENCES dispatch_private.ownership_recovery_cases,user_id uuid NOT NULL REFERENCES dispatch_private.profiles,session_id uuid NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(case_id,user_id));
CREATE TABLE dispatch_audit.command_receipts(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid,actor_user_id uuid NOT NULL REFERENCES dispatch_private.profiles,session_id uuid NOT NULL,command_name text NOT NULL,idempotency_key uuid NOT NULL,request_hash bytea NOT NULL CHECK(octet_length(request_hash)=32),result_payload jsonb NOT NULL,status dispatch_audit.receipt_status NOT NULL DEFAULT 'ACCEPTED',created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX command_receipts_org_key ON dispatch_audit.command_receipts(organization_id,actor_user_id,command_name,idempotency_key) NULLS NOT DISTINCT;
CREATE TABLE dispatch_audit.audit_events(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid,actor_user_id uuid NOT NULL REFERENCES dispatch_private.profiles,event_type dispatch_private.audit_event_type NOT NULL,target_id uuid,event_payload jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE dispatch_projection.projection_candidates(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),organization_id uuid NOT NULL,source_record_id uuid NOT NULL,source_revision integer NOT NULL,capability_grant_id uuid NOT NULL,status dispatch_private.projection_status NOT NULL DEFAULT 'SUBMITTED',sanitized_payload jsonb NOT NULL,requested_by_user_id uuid NOT NULL REFERENCES dispatch_private.profiles,requested_at timestamptz NOT NULL DEFAULT now(),freshness_deadline timestamptz NOT NULL,UNIQUE(organization_id,id),FOREIGN KEY(organization_id,source_record_id,source_revision) REFERENCES dispatch_audit.record_revisions(organization_id,record_id,revision_number),FOREIGN KEY(organization_id,capability_grant_id) REFERENCES dispatch_private.capability_grants(organization_id,id));
CREATE TABLE dispatch_projection.public_safe_projections(id uuid PRIMARY KEY DEFAULT extensions.gen_random_uuid(),candidate_id uuid NOT NULL REFERENCES dispatch_projection.projection_candidates,projection_revision integer NOT NULL,organization_public_name text NOT NULL,source_class dispatch_private.source_class NOT NULL,source_label text NOT NULL,consumer_taxonomy text NOT NULL,title text NOT NULL,summary text NOT NULL,public_location jsonb,published_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,withdrawn_at timestamptz,invalidation_reason text,UNIQUE(candidate_id,projection_revision));

\ir seed-static-contract.sql

CREATE FUNCTION dispatch_private.request_hash(p jsonb) RETURNS bytea LANGUAGE sql IMMUTABLE SET search_path='' AS 'SELECT extensions.digest(pg_catalog.convert_to(p::text,''UTF8''),''sha256'')';
CREATE FUNCTION dispatch_private.current_session_id() RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT CASE WHEN coalesce(auth.jwt()->>'session_id','')~'^[0-9a-f-]{36}$' THEN (auth.jwt()->>'session_id')::uuid END $$;
CREATE FUNCTION dispatch_private.current_actor_id() RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT auth.uid() $$;
CREATE FUNCTION dispatch_private.has_live_aal2() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT coalesce((SELECT auth.uid()=u.id AND auth.jwt()->>'aal'='aal2' AND auth.jwt()->'amr' @> '[{"method":"totp"}]'::jsonb AND s.user_id=u.id AND s.aal='aal2' AND f.user_id=u.id AND f.status='verified' AND p.status='ACTIVE' FROM auth.users u JOIN auth.sessions s ON s.id=dispatch_private.current_session_id() JOIN auth.mfa_factors f ON f.id=s.factor_id JOIN dispatch_private.profiles p ON p.user_id=u.id WHERE u.id=auth.uid() AND u.deleted_at IS NULL),false) $$;
CREATE FUNCTION dispatch_private.actor_membership(p_org uuid,p_permission text) RETURNS uuid LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT m.id FROM dispatch_private.organization_memberships m JOIN dispatch_private.organizations o ON o.id=m.organization_id JOIN dispatch_private.role_permissions rp ON rp.role_key=m.role_template WHERE m.organization_id=p_org AND m.user_id=dispatch_private.current_actor_id() AND m.status='ACTIVE' AND o.status='ACTIVE' AND rp.permission_key=p_permission LIMIT 1 $$;
CREATE FUNCTION dispatch_private.command_permission(p_command text) RETURNS text LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT CASE WHEN p_command LIKE '%record%' THEN CASE WHEN p_command LIKE 'create%' THEN 'operations.create' WHEN p_command LIKE 'assign%' THEN 'operations.assign' WHEN p_command LIKE 'close%' THEN 'operations.close' ELSE 'operations.update' END WHEN p_command LIKE '%invitation%' OR p_command='invite_member' THEN 'members.invite' WHEN p_command LIKE '%member%' THEN 'members.manage' WHEN p_command LIKE '%ownership_transfer' THEN 'ownership.transfer' WHEN p_command LIKE '%projection%' THEN CASE WHEN p_command LIKE 'submit%' THEN 'projection.submit' WHEN p_command IN('approve_projection','reject_projection') THEN 'projection.review' ELSE 'projection.publish' END ELSE 'organization.manage' END $$;
CREATE FUNCTION dispatch_private.projection_eligible(p_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $$ SELECT coalesce((SELECT p.withdrawn_at IS NULL AND p.expires_at>now() AND c.status='APPROVED' AND o.status='ACTIVE' AND g.status='ACTIVE' AND (g.valid_until IS NULL OR g.valid_until>now()) AND s.status='ACTIVE' AND r.status NOT IN('CLOSED','CANCELLED') AND r.current_revision=c.source_revision FROM dispatch_projection.public_safe_projections p JOIN dispatch_projection.projection_candidates c ON c.id=p.candidate_id JOIN dispatch_private.organizations o ON o.id=c.organization_id JOIN dispatch_private.capability_grants g ON g.id=c.capability_grant_id JOIN dispatch_private.operational_scopes s ON s.id=g.operational_scope_id JOIN dispatch_private.operational_records r ON r.id=c.source_record_id WHERE p.id=p_id),false) $$;
CREATE FUNCTION dispatch_private.reject_append_only() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$ BEGIN RAISE EXCEPTION 'append-only'; END $$;
CREATE FUNCTION dispatch_private.safe_payload(p jsonb) RETURNS jsonb LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT p-'private_payload'-'internal_notes'-'assignment' $$;
CREATE FUNCTION dispatch_private.command_event(p text) RETURNS dispatch_private.audit_event_type LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT CASE WHEN p LIKE '%projection%' THEN 'SETTINGS_CHANGED'::dispatch_private.audit_event_type WHEN p LIKE '%member%' OR p LIKE '%invitation%' THEN 'SETTINGS_CHANGED'::dispatch_private.audit_event_type WHEN p LIKE '%capability%' THEN 'CAPABILITY_GRANTED'::dispatch_private.audit_event_type WHEN p LIKE '%record%' THEN 'RECORD_UPDATED'::dispatch_private.audit_event_type ELSE 'SETTINGS_CHANGED'::dispatch_private.audit_event_type END $$;
CREATE FUNCTION dispatch_private.is_platform_command(p text) RETURNS boolean LANGUAGE sql IMMUTABLE SET search_path='' AS $$ SELECT p IN('grant_capability','suspend_capability','revoke_capability','start_ownership_recovery','approve_ownership_recovery','set_organization_verification','set_organization_status') $$;
CREATE FUNCTION dispatch_private.execute_command(p_command text,p_payload jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $$
DECLARE a uuid:=dispatch_private.current_actor_id(); sid uuid:=dispatch_private.current_session_id(); org uuid:=(p_payload->>'organization_id')::uuid; key uuid:=(p_payload->>'idempotency_key')::uuid; h bytea:=dispatch_private.request_hash(p_payload-'idempotency_key'); old dispatch_audit.command_receipts%ROWTYPE; mid uuid; oid uuid:=coalesce((p_payload->>'object_id')::uuid,extensions.gen_random_uuid()); perm text;
BEGIN
 IF a IS NULL OR NOT dispatch_private.has_live_aal2() THEN RAISE EXCEPTION 'forbidden'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(key::text,0));
 SELECT * INTO old FROM dispatch_audit.command_receipts WHERE organization_id IS NOT DISTINCT FROM org AND actor_user_id=a AND command_name=p_command AND idempotency_key=key;
 IF FOUND THEN IF old.request_hash<>h THEN RAISE EXCEPTION 'idempotency payload mismatch'; END IF; RETURN old.result_payload||jsonb_build_object('replay',true); END IF;
 IF dispatch_private.is_platform_command(p_command) THEN
  IF NOT EXISTS(SELECT 1 FROM dispatch_private.platform_admin_grants g WHERE g.user_id=a AND g.active AND g.permission_key=CASE WHEN p_command LIKE '%capability%' THEN 'platform.capability.manage' WHEN p_command LIKE '%recovery%' THEN 'platform.ownership.recover' WHEN p_command='set_organization_status' THEN 'platform.organization.suspend' ELSE 'platform.organization.verify' END) THEN RAISE EXCEPTION 'forbidden'; END IF;
 ELSE
  IF p_command='accept_invitation' THEN mid:=NULL;
  ELSIF p_command='accept_ownership_transfer' THEN SELECT id INTO mid FROM dispatch_private.organization_memberships WHERE organization_id=org AND user_id=a AND status='ACTIVE'; IF mid IS NULL THEN RAISE EXCEPTION 'forbidden'; END IF;
  ELSE perm:=dispatch_private.command_permission(p_command); mid:=dispatch_private.actor_membership(org,perm); IF mid IS NULL THEN RAISE EXCEPTION 'forbidden'; END IF;
  END IF;
 END IF;
 IF p_command='create_operational_record' THEN INSERT INTO dispatch_private.operational_records(id,organization_id,operational_scope_id,record_type,status,title,private_payload,created_by_membership_id) VALUES(oid,org,(p_payload->>'scope_id')::uuid,(p_payload->>'record_type')::dispatch_private.record_type,'OPEN',p_payload->>'title',coalesce(p_payload->'private_payload','{}'),mid); INSERT INTO dispatch_audit.record_revisions(organization_id,record_id,revision_number,snapshot,actor_user_id) VALUES(org,oid,1,p_payload,a);
 ELSIF p_command='update_operational_record' THEN UPDATE dispatch_private.operational_records SET title=coalesce(p_payload->>'title',title),private_payload=coalesce(p_payload->'private_payload',private_payload),current_revision=current_revision+1 WHERE id=oid AND organization_id=org AND current_revision=(p_payload->>'expected_revision')::int; IF NOT FOUND THEN RAISE EXCEPTION 'stale revision'; END IF; INSERT INTO dispatch_audit.record_revisions(organization_id,record_id,revision_number,snapshot,actor_user_id) SELECT org,oid,current_revision,p_payload,a FROM dispatch_private.operational_records WHERE id=oid;
 ELSIF p_command='assign_operational_record' THEN INSERT INTO dispatch_private.record_assignments(organization_id,record_id,assigned_membership_id) VALUES(org,oid,(p_payload->>'membership_id')::uuid);
 ELSIF p_command='close_operational_record' THEN UPDATE dispatch_private.operational_records SET status='CLOSED',current_revision=current_revision+1 WHERE id=oid AND organization_id=org AND current_revision=(p_payload->>'expected_revision')::int; IF NOT FOUND THEN RAISE EXCEPTION 'stale revision'; END IF;
 ELSIF p_command='invite_member' THEN INSERT INTO dispatch_private.organization_invitations(id,organization_id,target_identity,role_template,token_digest,expires_at,created_by_membership_id) VALUES(oid,org,p_payload->>'target_identity',(p_payload->>'role')::dispatch_private.role_template_key,decode(p_payload->>'token_digest','hex'),(p_payload->>'expires_at')::timestamptz,mid);
 ELSIF p_command='revoke_invitation' THEN UPDATE dispatch_private.organization_invitations SET status='REVOKED',revoked_at=now() WHERE id=oid AND organization_id=org AND status='PENDING'; IF NOT FOUND THEN RAISE EXCEPTION 'invalid invitation'; END IF;
 ELSIF p_command='accept_invitation' THEN UPDATE dispatch_private.organization_invitations SET status='ACCEPTED',accepted_at=now() WHERE id=oid AND organization_id=org AND status='PENDING' AND expires_at>now() AND target_identity='user:'||a::text AND token_digest=extensions.digest(convert_to(p_payload->>'token','UTF8'),'sha256'); IF NOT FOUND THEN RAISE EXCEPTION 'invalid invitation'; END IF; INSERT INTO dispatch_private.organization_memberships(organization_id,user_id,status,role_template,activated_at) SELECT org,a,'ACTIVE',role_template,now() FROM dispatch_private.organization_invitations WHERE id=oid;
 ELSIF p_command='change_member_role' THEN UPDATE dispatch_private.organization_memberships SET role_template=(p_payload->>'role')::dispatch_private.role_template_key,revision=revision+1 WHERE id=oid AND organization_id=org;
 ELSIF p_command='suspend_member' THEN UPDATE dispatch_private.organization_memberships SET status='SUSPENDED',revision=revision+1 WHERE id=oid AND organization_id=org;
 ELSIF p_command='reactivate_member' THEN UPDATE dispatch_private.organization_memberships SET status='ACTIVE',revision=revision+1 WHERE id=oid AND organization_id=org;
 ELSIF p_command='revoke_member' THEN UPDATE dispatch_private.organization_memberships SET status='REVOKED',revision=revision+1 WHERE id=oid AND organization_id=org;
 ELSIF p_command='initiate_ownership_transfer' THEN INSERT INTO dispatch_private.ownership_transfers(id,organization_id,from_membership_id,to_membership_id,expected_org_revision) VALUES(oid,org,mid,(p_payload->>'to_membership_id')::uuid,(p_payload->>'expected_revision')::int);
 ELSIF p_command='accept_ownership_transfer' THEN
  UPDATE dispatch_private.ownership_transfers SET status='ACCEPTED' WHERE id=oid AND organization_id=org AND status='PENDING' AND to_membership_id=mid AND expected_org_revision=(SELECT governance_revision FROM dispatch_private.organizations WHERE id=org); IF NOT FOUND THEN RAISE EXCEPTION 'invalid transfer'; END IF;
  UPDATE dispatch_private.organization_memberships SET role_template='ORGANIZATION_ADMIN',revision=revision+1 WHERE organization_id=org AND role_template='OWNER' AND status='ACTIVE';
  UPDATE dispatch_private.organization_memberships SET role_template='OWNER',revision=revision+1 WHERE id=mid;
  UPDATE dispatch_private.organizations SET governance_revision=governance_revision+1 WHERE id=org;
 ELSIF p_command='cancel_ownership_transfer' THEN UPDATE dispatch_private.ownership_transfers SET status='CANCELLED' WHERE id=oid AND organization_id=org AND status='PENDING';
 ELSIF p_command='grant_capability' THEN INSERT INTO dispatch_private.capability_grants(id,organization_id,capability_key,operational_scope_id,operational_scope_version,status,valid_until,granted_by_platform_actor) VALUES(oid,org,p_payload->>'capability',(p_payload->>'scope_id')::uuid,1,'ACTIVE',(p_payload->>'valid_until')::timestamptz,a);
 ELSIF p_command IN('suspend_capability','revoke_capability') THEN UPDATE dispatch_private.capability_grants SET status=(CASE WHEN p_command='suspend_capability' THEN 'SUSPENDED' ELSE 'REVOKED' END)::dispatch_private.capability_status,revision=revision+1 WHERE id=oid AND organization_id=org AND status IN('ACTIVE','SUSPENDED'); IF NOT FOUND THEN RAISE EXCEPTION 'capability transition lost race'; END IF;
 ELSIF p_command='submit_projection_candidate' THEN INSERT INTO dispatch_projection.projection_candidates(id,organization_id,source_record_id,source_revision,capability_grant_id,sanitized_payload,requested_by_user_id,freshness_deadline) VALUES(oid,org,(p_payload->>'record_id')::uuid,(p_payload->>'source_revision')::int,(p_payload->>'capability_id')::uuid,dispatch_private.safe_payload(p_payload->'payload'),a,(p_payload->>'freshness_deadline')::timestamptz);
 ELSIF p_command='approve_projection' THEN UPDATE dispatch_projection.projection_candidates SET status='APPROVED' WHERE id=oid AND organization_id=org AND status='SUBMITTED'; IF NOT FOUND THEN RAISE EXCEPTION 'projection transition lost race'; END IF;
 ELSIF p_command='reject_projection' THEN UPDATE dispatch_projection.projection_candidates SET status='REJECTED' WHERE id=oid AND organization_id=org AND status='SUBMITTED'; IF NOT FOUND THEN RAISE EXCEPTION 'projection transition lost race'; END IF;
 ELSIF p_command='publish_projection' THEN INSERT INTO dispatch_projection.public_safe_projections(candidate_id,projection_revision,organization_public_name,source_class,source_label,consumer_taxonomy,title,summary,public_location,expires_at) SELECT id,1,p_payload->>'organization_public_name','ORGANIZATION',p_payload->>'source_label',p_payload->>'taxonomy',sanitized_payload->>'title',sanitized_payload->>'summary',sanitized_payload->'public_location',freshness_deadline FROM dispatch_projection.projection_candidates WHERE id=oid AND organization_id=org AND status='APPROVED' RETURNING id INTO oid;
 ELSIF p_command='withdraw_projection' THEN UPDATE dispatch_projection.public_safe_projections SET withdrawn_at=now(),invalidation_reason='withdrawn' WHERE id=oid;
 ELSIF p_command='set_organization_status' THEN UPDATE dispatch_private.organizations SET status=(p_payload->>'status')::dispatch_private.organization_status,governance_revision=governance_revision+1 WHERE id=org;
 ELSIF p_command='set_organization_verification' THEN UPDATE dispatch_private.organizations SET verification_level=(p_payload->>'verification_level')::dispatch_private.verification_level,governance_revision=governance_revision+1 WHERE id=org;
 ELSIF p_command='start_ownership_recovery' THEN INSERT INTO dispatch_private.ownership_recovery_cases(id,organization_id,target_membership_id,organization_revision) VALUES(oid,org,(p_payload->>'target_membership_id')::uuid,(p_payload->>'expected_revision')::int); INSERT INTO dispatch_private.recovery_approvals VALUES(oid,a,sid,now());
 ELSIF p_command='approve_ownership_recovery' THEN
  INSERT INTO dispatch_private.recovery_approvals VALUES(oid,a,sid,now());
  UPDATE dispatch_private.ownership_recovery_cases SET status='RECOVERED' WHERE id=oid AND organization_id=org AND status='FIRST_APPROVED' AND organization_revision=(SELECT governance_revision FROM dispatch_private.organizations WHERE id=org) AND (SELECT count(*) FROM dispatch_private.recovery_approvals WHERE case_id=oid)=2; IF NOT FOUND THEN RAISE EXCEPTION 'recovery requires distinct second approval and unchanged revision'; END IF;
  UPDATE dispatch_private.organization_memberships SET role_template='ORGANIZATION_ADMIN',revision=revision+1 WHERE organization_id=org AND role_template='OWNER' AND status='ACTIVE';
  UPDATE dispatch_private.organization_memberships SET role_template='OWNER',revision=revision+1 WHERE id=(SELECT target_membership_id FROM dispatch_private.ownership_recovery_cases WHERE id=oid);
  UPDATE dispatch_private.organizations SET governance_revision=governance_revision+1 WHERE id=org;
 END IF;
 INSERT INTO dispatch_audit.audit_events(organization_id,actor_user_id,event_type,target_id,event_payload) VALUES(org,a,dispatch_private.command_event(p_command),oid,jsonb_build_object('command',p_command));
 INSERT INTO dispatch_audit.command_receipts(organization_id,actor_user_id,session_id,command_name,idempotency_key,request_hash,result_payload) VALUES(org,a,sid,p_command,key,h,jsonb_build_object('command',p_command,'object_id',oid,'actor_id',a,'organization_id',org,'replay',false));
 RETURN jsonb_build_object('command',p_command,'object_id',oid,'actor_id',a,'organization_id',org,'replay',false);
END $$;

DO $factory$ DECLARE n text; names text[]:=ARRAY['create_operational_record','update_operational_record','assign_operational_record','close_operational_record','invite_member','revoke_invitation','accept_invitation','change_member_role','suspend_member','reactivate_member','revoke_member','initiate_ownership_transfer','accept_ownership_transfer','cancel_ownership_transfer','grant_capability','suspend_capability','revoke_capability','submit_projection_candidate','approve_projection','reject_projection','publish_projection','withdraw_projection','start_ownership_recovery','approve_ownership_recovery','set_organization_verification','set_organization_status']; BEGIN FOREACH n IN ARRAY names LOOP
 EXECUTE format('CREATE FUNCTION dispatch_private.%I_command(p_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path='''' AS $f$ SELECT dispatch_private.execute_command(%L,p_payload) $f$',n,n);
 EXECUTE format('CREATE FUNCTION dispatch_api.%I(p_payload jsonb) RETURNS jsonb LANGUAGE sql SECURITY INVOKER SET search_path='''' AS $f$ SELECT dispatch_private.%I_command(p_payload) $f$',n,n);
END LOOP; END $factory$;

CREATE TRIGGER revisions_append_only BEFORE UPDATE OR DELETE ON dispatch_audit.record_revisions FOR EACH ROW EXECUTE FUNCTION dispatch_private.reject_append_only();
CREATE TRIGGER audit_append_only BEFORE UPDATE OR DELETE ON dispatch_audit.audit_events FOR EACH ROW EXECUTE FUNCTION dispatch_private.reject_append_only();
CREATE TRIGGER receipts_append_only BEFORE UPDATE OR DELETE ON dispatch_audit.command_receipts FOR EACH ROW EXECUTE FUNCTION dispatch_private.reject_append_only();

DO $rls$ DECLARE r regclass; BEGIN FOR r IN SELECT format('%I.%I',n.nspname,c.relname)::regclass FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN('dispatch_private','dispatch_audit','dispatch_projection') AND c.relkind='r' LOOP EXECUTE format('ALTER TABLE %s ENABLE ROW LEVEL SECURITY',r); EXECUTE format('ALTER TABLE %s FORCE ROW LEVEL SECURITY',r); END LOOP; END $rls$;
CREATE POLICY profiles_self ON dispatch_private.profiles FOR SELECT TO authenticated USING(user_id=(SELECT auth.uid()) AND dispatch_private.has_live_aal2());
CREATE POLICY organizations_member ON dispatch_private.organizations FOR SELECT TO authenticated USING(dispatch_private.actor_membership(id,'organization.read') IS NOT NULL);
CREATE POLICY memberships_member ON dispatch_private.organization_memberships FOR SELECT TO authenticated USING(dispatch_private.actor_membership(organization_id,'members.read') IS NOT NULL);
CREATE POLICY invitations_member ON dispatch_private.organization_invitations FOR SELECT TO authenticated USING(dispatch_private.actor_membership(organization_id,'members.invite') IS NOT NULL);
CREATE POLICY scopes_member ON dispatch_private.operational_scopes FOR SELECT TO authenticated USING(dispatch_private.actor_membership(organization_id,'scope.read') IS NOT NULL);
CREATE POLICY records_member ON dispatch_private.operational_records FOR SELECT TO authenticated USING(dispatch_private.actor_membership(organization_id,'operations.read') IS NOT NULL);
CREATE POLICY assignments_member ON dispatch_private.record_assignments FOR SELECT TO authenticated USING(dispatch_private.actor_membership(organization_id,'operations.read') IS NOT NULL);
CREATE POLICY transfers_member ON dispatch_private.ownership_transfers FOR SELECT TO authenticated USING(dispatch_private.actor_membership(organization_id,'organization.read') IS NOT NULL);
CREATE POLICY revisions_member ON dispatch_audit.record_revisions FOR SELECT TO authenticated USING(dispatch_private.actor_membership(organization_id,'operations.read') IS NOT NULL);
CREATE POLICY candidates_member ON dispatch_projection.projection_candidates FOR SELECT TO authenticated USING(dispatch_private.actor_membership(organization_id,'projection.review') IS NOT NULL);
CREATE POLICY platform_self ON dispatch_private.platform_admin_grants FOR SELECT TO authenticated USING(user_id=(SELECT auth.uid()) AND dispatch_private.has_live_aal2());
CREATE POLICY capabilities_member ON dispatch_private.capability_grants FOR SELECT TO authenticated USING(dispatch_private.actor_membership(organization_id,'organization.read') IS NOT NULL);
CREATE POLICY recovery_platform ON dispatch_private.ownership_recovery_cases FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM dispatch_private.platform_admin_grants g WHERE g.user_id=(SELECT auth.uid()) AND g.permission_key='platform.ownership.recover' AND g.active));
CREATE POLICY public_projection_anon ON dispatch_projection.public_safe_projections FOR SELECT TO anon USING(dispatch_private.projection_eligible(id));
CREATE POLICY public_projection_auth ON dispatch_projection.public_safe_projections FOR SELECT TO authenticated USING(dispatch_private.projection_eligible(id));
CREATE POLICY organizations_platform ON dispatch_private.organizations FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM dispatch_private.platform_admin_grants g WHERE g.user_id=(SELECT auth.uid()) AND g.active));
CREATE POLICY audit_member ON dispatch_audit.audit_events FOR SELECT TO authenticated USING(dispatch_private.actor_membership(organization_id,'audit.read') IS NOT NULL OR EXISTS(SELECT 1 FROM dispatch_private.platform_admin_grants g WHERE g.user_id=(SELECT auth.uid()) AND g.permission_key='platform.audit.investigate' AND g.active));

CREATE VIEW dispatch_api.operational_records WITH(security_invoker=true) AS SELECT id,organization_id,operational_scope_id,record_type,status,priority,title,current_revision,created_at FROM dispatch_private.operational_records;
CREATE VIEW dispatch_api.public_safe_projections WITH(security_invoker=true) AS SELECT id,organization_public_name,source_class,source_label,consumer_taxonomy,title,summary,public_location,published_at,expires_at FROM dispatch_projection.public_safe_projections WHERE dispatch_private.projection_eligible(id);
\ir compatibility.sql

GRANT dispatch_function_owner TO postgres;
GRANT USAGE,CREATE ON SCHEMA dispatch_private TO dispatch_function_owner;
ALTER FUNCTION dispatch_private.execute_command(text,jsonb) OWNER TO dispatch_function_owner;
DO $owners$ DECLARE p regprocedure; BEGIN FOR p IN SELECT p.oid::regprocedure FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='dispatch_private' AND p.proname NOT IN('current_session_id','current_actor_id','has_live_aal2') LOOP EXECUTE format('ALTER FUNCTION %s OWNER TO dispatch_function_owner',p); END LOOP; END $owners$;
REVOKE CREATE ON SCHEMA dispatch_private FROM dispatch_function_owner;
GRANT USAGE ON SCHEMA extensions,dispatch_private,dispatch_audit,dispatch_projection TO dispatch_function_owner;
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA dispatch_private,dispatch_audit,dispatch_projection TO dispatch_function_owner;
REVOKE ALL ON ALL TABLES IN SCHEMA dispatch_private,dispatch_audit,dispatch_projection FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA dispatch_private,dispatch_audit,dispatch_projection,dispatch_api FROM PUBLIC,anon,authenticated,service_role;
GRANT EXECUTE ON FUNCTION dispatch_private.current_session_id(),dispatch_private.current_actor_id(),dispatch_private.has_live_aal2() TO dispatch_function_owner;
GRANT USAGE ON SCHEMA dispatch_api TO anon,authenticated; GRANT SELECT ON dispatch_api.public_safe_projections,dispatch_api.responder_public_projection TO anon,authenticated; GRANT SELECT ON dispatch_api.operational_records TO authenticated;
GRANT USAGE ON SCHEMA dispatch_private TO authenticated; GRANT EXECUTE ON FUNCTION dispatch_private.has_live_aal2(),dispatch_private.actor_membership(uuid,text),dispatch_private.projection_eligible(uuid) TO authenticated;
GRANT SELECT ON dispatch_private.operational_records TO authenticated;
GRANT USAGE ON SCHEMA dispatch_projection,dispatch_private TO anon,authenticated;
GRANT SELECT ON dispatch_projection.public_safe_projections,dispatch_projection.projection_candidates TO anon,authenticated;
GRANT EXECUTE ON FUNCTION dispatch_private.projection_eligible(uuid) TO anon;
DO $grants$ DECLARE p regprocedure; BEGIN FOR p IN SELECT p.oid::regprocedure FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='dispatch_api' AND p.prokind='f' LOOP EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO authenticated',p); END LOOP; END $grants$;
DO $private_grants$ DECLARE p regprocedure; BEGIN FOR p IN SELECT p.oid::regprocedure FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='dispatch_private' AND p.proname LIKE '%\_command' ESCAPE '\' LOOP EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO authenticated',p); END LOOP; END $private_grants$;
REVOKE dispatch_function_owner FROM postgres;
NOTIFY pgrst,'reload schema';
COMMIT;
