\set ON_ERROR_STOP on
-- LOCAL DISPOSABLE REHEARSAL ONLY - NOT AUTHORIZED FOR PRODUCTION EXECUTION
BEGIN; CREATE TABLE public.phase26_failure_rls(id integer); ALTER TABLE public.phase26_failure_rls ENABLE ROW LEVEL SECURITY; SELECT 1/0; COMMIT;
