\set ON_ERROR_STOP on
-- LOCAL DISPOSABLE REHEARSAL ONLY - NOT AUTHORIZED FOR PRODUCTION EXECUTION
BEGIN; CREATE FUNCTION public.phase26_failure_command() RETURNS void LANGUAGE sql AS 'SELECT'; SELECT 1/0; COMMIT;
