\set ON_ERROR_STOP on
-- LOCAL DISPOSABLE REHEARSAL ONLY - NOT AUTHORIZED FOR PRODUCTION EXECUTION
BEGIN; CREATE SCHEMA phase26_failure_type; CREATE TYPE phase26_failure_type.x AS ENUM('A'); SELECT 1/0; COMMIT;
