// LOCAL DISPOSABLE REHEARSAL ONLY - NOT AUTHORIZED FOR PRODUCTION EXECUTION
import test from 'node:test'; import assert from 'node:assert/strict';
import {createHash,createHmac,randomBytes,randomUUID} from 'node:crypto';
import {spawnSync} from 'node:child_process'; import {writeFileSync} from 'node:fs'; import {join} from 'node:path';
const api=req('P26_API_URL').replace(/\/+$/,''); const anon=req('P26_ANON_KEY'); const service=req('P26_SERVICE_KEY'); const docker=req('P26_DOCKER'); const project=req('P26_PROJECT_ID'); const evidence=req('P26_EVIDENCE_DIR');
assert.equal(api,'http://127.0.0.1:54321'); assert.match(project,/^gridly-dispatch-phase26-[a-f0-9]{12}$/); const db=`supabase_db_${project}`;
const org1='26000000-0000-4000-8000-000000000001',org2='26000000-0000-4000-8000-000000000002',scope1='26100000-0000-4000-8000-000000000001',scope2='26100000-0000-4000-8000-000000000002';
const counters={auth:0,rls:0,commands:0,concurrency:0,invitations:0,ownership:0,capability:0,records:0,projection:0,compatibility:0,nonInterference:0};
function req(n){const v=process.env[n];assert.ok(v,`${n} required`);return v} function q(v){return `'${String(v).replaceAll("'","''")}'`}
function sql(s,{fail=false}={}){const r=spawnSync(docker,['exec',db,'psql','-X','-q','-A','-t','-v','ON_ERROR_STOP=1','-U','postgres','-d','postgres','-c',s],{encoding:'utf8',windowsHide:true,maxBuffer:20e6}); if(fail)assert.notEqual(r.status,0);else assert.equal(r.status,0,`${r.stderr}\n${r.stdout}`);return (r.stdout??'').trim().split(/\r?\n/).filter(Boolean).at(-1)??''}
async function http(path,{method='GET',token=anon,key=anon,body,profile,accept=[200]}={}){const headers={apikey:key,Authorization:`Bearer ${token}`};if(body!==undefined)headers['Content-Type']='application/json';if(profile){headers['Accept-Profile']=profile;headers['Content-Profile']=profile}const r=await fetch(api+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});const raw=await r.text();let data;try{data=raw?JSON.parse(raw):null}catch{data=raw}if(!accept.includes(r.status))throw new Error(`${path} ${r.status} ${String(raw).slice(0,300)}`);return{status:r.status,data}}
function claims(t){return JSON.parse(Buffer.from(t.split('.')[1],'base64url'))} function b32(v){const a='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits='';for(const c of v.replace(/=+$/,'').toUpperCase())bits+=a.indexOf(c).toString(2).padStart(5,'0');const o=[];for(let i=0;i+8<=bits.length;i+=8)o.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(o)}
function totp(secret){const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const h=createHmac('sha1',b32(secret)).update(b).digest(),o=h.at(-1)&15;return String(((((h[o]&127)<<24)|((h[o+1]&255)<<16)|((h[o+2]&255)<<8)|(h[o+3]&255))%1e6)).padStart(6,'0')}
async function signup(label){const email=`p26-${label}-${randomUUID()}@dispatch.invalid`,password=randomBytes(24).toString('base64url');const r=await http('/auth/v1/signup',{method:'POST',body:{email,password}});assert.equal(claims(r.data.access_token).aal,'aal1');return{...r.data,email,password,userId:r.data.user.id}}
async function elevate(u){const e=await http('/auth/v1/factors',{method:'POST',token:u.access_token,body:{factor_type:'totp',friendly_name:'p26'}});const ch=await http(`/auth/v1/factors/${e.data.id}/challenge`,{method:'POST',token:u.access_token,body:{}});const v=await http(`/auth/v1/factors/${e.data.id}/verify`,{method:'POST',token:u.access_token,body:{challenge_id:ch.data.id,code:totp(e.data.totp.secret)}});assert.equal(claims(v.data.access_token).aal,'aal2');return{...u,...v.data,factorId:e.data.id}}
async function rpc(name,u,p,accept=[200]){return http(`/rest/v1/rpc/${name}`,{method:'POST',token:u.access_token,profile:'dispatch_api',body:{p_payload:p},accept})}
const key=()=>randomUUID(); const digest=t=>createHash('sha256').update(t).digest('hex');

test('Phase 26 production-shaped local clone rehearsal',async()=>{
 let ownerAal1=await signup('owner'),owner=await elevate(ownerAal1),viewer=await elevate(await signup('viewer')),other=await elevate(await signup('other')),invitee=await elevate(await signup('invitee')),raceUser=await elevate(await signup('race')),p1=await elevate(await signup('platform1')),p2=await elevate(await signup('platform2'));
 counters.auth+=16;
 for(const [u,n] of [[owner,'Owner'],[viewer,'Viewer'],[other,'Other'],[invitee,'Invitee'],[raceUser,'Race User'],[p1,'Platform One'],[p2,'Platform Two']])sql(`INSERT INTO dispatch_private.profiles(user_id,display_name) VALUES(${q(u.userId)},${q(n)})`);
 sql(`INSERT INTO dispatch_private.organizations(id,display_name,legal_name,organization_type,status) VALUES('${org1}','Org One','Org One','MUNICIPALITY','ACTIVE'),('${org2}','Org Two','Org Two','UTILITY','ACTIVE'); INSERT INTO dispatch_private.operational_scopes(id,organization_id,scope_type,label,source_reference) VALUES('${scope1}','${org1}','COUNTY','County','synthetic'),('${scope2}','${org2}','ROUTE','Route','synthetic')`);
 const ownerMid=randomUUID(),viewerMid=randomUUID(),otherMid=randomUUID();
 sql(`INSERT INTO dispatch_private.organization_memberships(id,organization_id,user_id,status,role_template,activated_at) VALUES('${ownerMid}','${org1}',${q(owner.userId)},'ACTIVE','OWNER',now()),('${viewerMid}','${org1}',${q(viewer.userId)},'ACTIVE','VIEWER',now()),('${otherMid}','${org2}',${q(other.userId)},'ACTIVE','OWNER',now())`);
 for(const perm of ['platform.organization.verify','platform.organization.suspend','platform.capability.manage','platform.ownership.recover','platform.audit.investigate','platform.abuse.manage'])sql(`INSERT INTO dispatch_private.platform_admin_grants VALUES(${q(p1.userId)},${q(perm)},true,${q(p1.userId)})`);
 sql(`INSERT INTO dispatch_private.platform_admin_grants VALUES(${q(p2.userId)},'platform.ownership.recover',true,${q(p1.userId)})`);

 const base={organization_id:org1,idempotency_key:key(),scope_id:scope1,record_type:'HAZARD',title:'Synthetic hazard',private_payload:{internal_notes:'never public',detail:'private'}};
 assert.ok((await rpc('create_operational_record',ownerAal1,base,[400,401,403])).status>=400); counters.auth++;
 const created=(await rpc('create_operational_record',owner,base)).data; const record=created.object_id; counters.commands++;
 const replay=(await rpc('create_operational_record',owner,base)).data;assert.equal(replay.replay,true);counters.commands++;
 assert.ok((await rpc('create_operational_record',owner,{...base,title:'changed'},[400])).status===400);counters.commands++;
 assert.ok((await rpc('create_operational_record',viewer,{...base,idempotency_key:key()},[400,403])).status>=400);counters.rls++;
 assert.ok((await rpc('create_operational_record',other,{...base,idempotency_key:key()},[400,403])).status>=400);counters.rls++;
 const reads=await http('/rest/v1/operational_records?select=id,organization_id',{token:owner.access_token,profile:'dispatch_api'});assert.equal(reads.data.length,1);const cross=await http('/rest/v1/operational_records?select=id,organization_id',{token:other.access_token,profile:'dispatch_api'});assert.equal(cross.data.length,0);counters.rls+=2;
 const updates=await Promise.all([1,2].map(i=>rpc('update_operational_record',owner,{organization_id:org1,idempotency_key:key(),object_id:record,expected_revision:1,title:`winner-${i}`,private_payload:{i}},[200,400])));assert.equal(updates.filter(x=>x.status===200).length,1);counters.concurrency++;counters.commands++;
 assert.equal(sql(`SELECT count(*) FROM dispatch_audit.record_revisions WHERE record_id='${record}'`),'2');assert.equal(sql(`SELECT count(*) FROM dispatch_audit.record_revisions WHERE record_id='${record}' AND revision_number=1`),'1');counters.records+=2;

 const token=randomBytes(32).toString('base64url'),inv=randomUUID(); await rpc('invite_member',owner,{organization_id:org1,idempotency_key:key(),object_id:inv,target_identity:`user:${invitee.userId}`,role:'OPERATOR',token_digest:digest(token),expires_at:new Date(Date.now()+3600000).toISOString()});counters.commands++;
 assert.ok((await rpc('accept_invitation',viewer,{organization_id:org1,idempotency_key:key(),object_id:inv,token},[400])).status===400);counters.invitations++;
 const accepted=await rpc('accept_invitation',invitee,{organization_id:org1,idempotency_key:key(),object_id:inv,token});assert.ok(accepted.data.object_id);counters.invitations++;counters.commands++;
 const raceToken=randomBytes(32).toString('base64url'),raceInv=randomUUID();await rpc('invite_member',owner,{organization_id:org1,idempotency_key:key(),object_id:raceInv,target_identity:`user:${raceUser.userId}`,role:'VIEWER',token_digest:digest(raceToken),expires_at:new Date(Date.now()+3600000).toISOString()});const inviteRace=await Promise.all([1,2].map(()=>rpc('accept_invitation',raceUser,{organization_id:org1,idempotency_key:key(),object_id:raceInv,token:raceToken},[200,400])));assert.equal(inviteRace.filter(x=>x.status===200).length,1);counters.concurrency++;counters.invitations++;
 const inviteeMid=sql(`SELECT id FROM dispatch_private.organization_memberships WHERE organization_id='${org1}' AND user_id=${q(invitee.userId)}`);
 sql(`INSERT INTO dispatch_private.organization_memberships(organization_id,user_id,status,role_template,activated_at) VALUES('${org2}',${q(invitee.userId)},'ACTIVE','VIEWER',now())`);assert.equal(sql(`SELECT count(*) FROM dispatch_private.organization_memberships WHERE user_id=${q(invitee.userId)} AND status='ACTIVE'`),'2');counters.invitations++;

 const cap=(await rpc('grant_capability',p1,{organization_id:org1,idempotency_key:key(),scope_id:scope1,capability:'awareness.hazard.publish',valid_until:new Date(Date.now()+86400000).toISOString()})).data.object_id;counters.commands++;counters.capability++;
 const cand=(await rpc('submit_projection_candidate',owner,{organization_id:org1,idempotency_key:key(),record_id:record,source_revision:2,capability_id:cap,freshness_deadline:new Date(Date.now()+3600000).toISOString(),payload:{title:'Public hazard',summary:'Safe',public_location:{county:'Synthetic'},internal_notes:'secret'}})).data.object_id;counters.commands++;
 await rpc('approve_projection',owner,{organization_id:org1,idempotency_key:key(),object_id:cand});counters.commands++;
 const pub=(await rpc('publish_projection',owner,{organization_id:org1,idempotency_key:key(),object_id:cand,organization_public_name:'Org One',source_label:'Official',taxonomy:'hazard'})).data.object_id;counters.commands++;
 const publicRows=await http('/rest/v1/public_safe_projections?select=*',{profile:'dispatch_api'});assert.equal(publicRows.data.length,1);assert.equal(JSON.stringify(publicRows.data).includes('secret'),false);counters.projection+=2;
 const compat=await http('/rest/v1/responder_public_projection?select=*',{profile:'dispatch_api'});assert.equal(Object.keys(compat.data[0]).length,18);counters.compatibility++;
 sql(`UPDATE dispatch_private.organizations SET status='SUSPENDED' WHERE id='${org1}'`);assert.equal((await http('/rest/v1/public_safe_projections?select=*',{profile:'dispatch_api'})).data.length,0);sql(`UPDATE dispatch_private.organizations SET status='ACTIVE' WHERE id='${org1}'`);
 sql(`UPDATE dispatch_private.operational_scopes SET status='SUSPENDED' WHERE id='${scope1}'`);assert.equal((await http('/rest/v1/public_safe_projections?select=*',{profile:'dispatch_api'})).data.length,0);sql(`UPDATE dispatch_private.operational_scopes SET status='ACTIVE' WHERE id='${scope1}'`);
 sql(`UPDATE dispatch_private.capability_grants SET valid_until=now()-interval '1 second' WHERE id='${cap}'`);assert.equal((await http('/rest/v1/public_safe_projections?select=*',{profile:'dispatch_api'})).data.length,0);sql(`UPDATE dispatch_private.capability_grants SET valid_until=now()+interval '1 day' WHERE id='${cap}'`);
 sql(`UPDATE dispatch_private.operational_records SET current_revision=3 WHERE id='${record}'`);assert.equal((await http('/rest/v1/public_safe_projections?select=*',{profile:'dispatch_api'})).data.length,0);sql(`UPDATE dispatch_private.operational_records SET current_revision=2 WHERE id='${record}'`);
 sql(`UPDATE dispatch_private.operational_records SET status='CLOSED' WHERE id='${record}'`);assert.equal((await http('/rest/v1/public_safe_projections?select=*',{profile:'dispatch_api'})).data.length,0);sql(`UPDATE dispatch_private.operational_records SET status='OPEN' WHERE id='${record}'`);counters.projection+=5;
 const candRace=(await rpc('submit_projection_candidate',owner,{organization_id:org1,idempotency_key:key(),record_id:record,source_revision:2,capability_id:cap,freshness_deadline:new Date(Date.now()+3600000).toISOString(),payload:{title:'Race',summary:'Safe'}})).data.object_id;const approvalRace=await Promise.all([1,2].map(()=>rpc('approve_projection',owner,{organization_id:org1,idempotency_key:key(),object_id:candRace},[200,400])));assert.equal(approvalRace.filter(x=>x.status===200).length,1);counters.concurrency++;
 await rpc('withdraw_projection',owner,{organization_id:org1,idempotency_key:key(),object_id:pub});assert.equal((await http('/rest/v1/public_safe_projections?select=*',{profile:'dispatch_api'})).data.length,0);counters.projection++;counters.commands++;
 const revokeRace=await Promise.all([1,2].map(()=>rpc('revoke_capability',p1,{organization_id:org1,idempotency_key:key(),object_id:cap},[200,400])));assert.equal(revokeRace.filter(x=>x.status===200).length,1);counters.concurrency++;counters.capability++;counters.commands++;

 await rpc('change_member_role',owner,{organization_id:org1,idempotency_key:key(),object_id:inviteeMid,role:'SUPERVISOR'});await rpc('suspend_member',owner,{organization_id:org1,idempotency_key:key(),object_id:inviteeMid});assert.ok((await rpc('create_operational_record',invitee,{...base,idempotency_key:key()},[400])).status===400);await rpc('reactivate_member',owner,{organization_id:org1,idempotency_key:key(),object_id:inviteeMid});counters.commands+=3;counters.rls++;
 const transfer=randomUUID();await rpc('initiate_ownership_transfer',owner,{organization_id:org1,idempotency_key:key(),object_id:transfer,to_membership_id:inviteeMid,expected_revision:0});await rpc('accept_ownership_transfer',invitee,{organization_id:org1,idempotency_key:key(),object_id:transfer});assert.equal(sql(`SELECT count(*) FROM dispatch_private.organization_memberships WHERE organization_id='${org1}' AND status='ACTIVE' AND role_template='OWNER'`),'1');counters.commands+=2;counters.ownership++;
 const recovery=(await rpc('start_ownership_recovery',p1,{organization_id:org1,idempotency_key:key(),target_membership_id:ownerMid,expected_revision:1})).data.object_id;await rpc('approve_ownership_recovery',p2,{organization_id:org1,idempotency_key:key(),object_id:recovery});assert.equal(sql(`SELECT user_id FROM dispatch_private.organization_memberships WHERE organization_id='${org1}' AND role_template='OWNER' AND status='ACTIVE'`),owner.userId);counters.commands+=2;counters.ownership+=2;
 const transferRace=randomUUID();await rpc('initiate_ownership_transfer',owner,{organization_id:org1,idempotency_key:key(),object_id:transferRace,to_membership_id:inviteeMid,expected_revision:2});const ownershipRace=await Promise.all([1,2].map(()=>rpc('accept_ownership_transfer',invitee,{organization_id:org1,idempotency_key:key(),object_id:transferRace},[200,400])));assert.equal(ownershipRace.filter(x=>x.status===200).length,1);assert.equal(sql(`SELECT count(*) FROM dispatch_private.organization_memberships WHERE organization_id='${org1}' AND status='ACTIVE' AND role_template='OWNER'`),'1');counters.concurrency++;counters.ownership++;

 const capSuspend=randomUUID();sql(`INSERT INTO dispatch_private.capability_grants(id,organization_id,capability_key,operational_scope_id,operational_scope_version,status,valid_until,granted_by_platform_actor) VALUES('${capSuspend}','${org1}','awareness.condition.publish','${scope1}',1,'ACTIVE',now()+interval '1 day',${q(p1.userId)})`);const platformNames=['set_organization_verification','set_organization_status','suspend_capability'];for(const n of platformNames){const p={organization_id:org1,idempotency_key:key(),object_id:n==='suspend_capability'?capSuspend:randomUUID(),verification_level:'VERIFIED_ORGANIZATION',status:'ACTIVE'};await rpc(n,p1,p);counters.commands++}
 const inv2=randomUUID();sql(`INSERT INTO dispatch_private.organization_invitations(id,organization_id,target_identity,role_template,token_digest,expires_at,created_by_membership_id) VALUES('${inv2}','${org1}','user:${viewer.userId}','VIEWER',decode('${digest('revoke-me')}','hex'),now()+interval '1 hour','${ownerMid}')`);await rpc('revoke_invitation',owner,{organization_id:org1,idempotency_key:key(),object_id:inv2});counters.commands++;
 const rejectCand=randomUUID();sql(`INSERT INTO dispatch_projection.projection_candidates(id,organization_id,source_record_id,source_revision,capability_grant_id,sanitized_payload,requested_by_user_id,freshness_deadline) VALUES('${rejectCand}','${org1}','${record}',2,'${cap}',jsonb_build_object('title','Reject','summary','Safe'),${q(owner.userId)},now()+interval '1 hour')`);const orgNames=['assign_operational_record','close_operational_record','revoke_member','cancel_ownership_transfer','reject_projection'];for(const n of orgNames){const p={organization_id:org1,idempotency_key:key(),object_id:n==='assign_operational_record'||n==='close_operational_record'?record:n==='reject_projection'?rejectCand:randomUUID(),membership_id:viewerMid,expected_revision:2};await rpc(n,n==='cancel_ownership_transfer'?invitee:owner,p);counters.commands++}
 const names=JSON.parse(sql(`SELECT jsonb_agg(DISTINCT command_name ORDER BY command_name) FROM dispatch_audit.command_receipts`));assert.equal(names.length,26);counters.commands=names.length;

 await http(`/auth/v1/factors/${owner.factorId}`,{method:'DELETE',token:owner.access_token,accept:[200]});assert.ok((await rpc('create_operational_record',owner,{...base,idempotency_key:key()},[400])).status===400);counters.auth++;counters.rls++;
 assert.equal(sql("SELECT has_schema_privilege('anon','dispatch_private','USAGE')::text"),'true');assert.equal(sql("SELECT count(*) FROM public.gridly_consumer_sentinel"),'1');assert.equal(sql("SELECT reporting_enabled::text FROM report_retention.admission_state WHERE singleton"),'false');counters.nonInterference+=3;
 writeFileSync(join(evidence,'runtime-vectors.json'),`${JSON.stringify({status:'PASS',counters,commandNames:names,privateFieldLeak:false,realLocalAuth:true},null,2)}\n`);
});
