import {createRequire} from 'node:module';import {root,out,write} from './inventory.mjs';
const require=createRequire(import.meta.url),session=await require('./session.cjs')(),records=[];
try{
 const {page:p,evidence}=await session.newPage();await p.addScriptTag({path:`${root}/tools/lp24449b1/runtime-probe.js`});
 await p.evaluate(async()=>{const g=getGridlyManualAwarenessAreaOptions().find(g=>g.countyId==='liberty-tx'),o=g.communities.find(o=>o.label==='Dayton');if(!gridlySaveCanonicalMultiCountyPlaceHome(o.canonicalResolution,'lp24449b1-lifecycle',g.countyId))throw Error('Home save failed');await lp24449b1.settle();});
 await p.evaluate(()=>{window.b1Clear={
  async settle(){await lp24449b1.settle();},
  async home(){if(gridlyGetCurrentAwarenessContext().type!=='HOME')document.getElementById('gridlyTemporaryContextReturnHome').click();await this.settle();},
  async search(name='Liberty'){const results=await gridlySearchAddress(`${name}, Liberty County, TX`);const selected=results.find(r=>r.placeGeoid);if(!selected)throw Error('Search missing');selectGridlySearchResult(selected);await this.settle();},
  async around(){gridlyActivateForegroundAwarenessContext({timestamp:Date.now(),coords:{latitude:30.04725,longitude:-94.88737,accuracy:10}});await this.settle();},
  async reset(){gridlyLocalTestReports.clear();await this.home();map.setView([30.04725,-94.88737],14,{animate:false});},
  async add(types){const anchor=getGridlyAwarenessAnchor(),rail=crossings.filter(c=>isGridlyPublicRoadwayCrossing(c)&&isGridlyReportableCrossing(c)).sort((a,b)=>getDistanceMiles(anchor.lat,anchor.lng,a.lat,a.lng)-getDistanceMiles(anchor.lat,anchor.lng,b.lat,b.lng));let ri=0;const fixtures=types.map((type,i)=>gridlyLocalTestReports.add(type,/crossing/.test(type)?{crossingId:rail[ri++].id}:{lat:anchor.lat+(i===1?.00325:i===2?-.00375:0),lng:anchor.lng+(i===1?-.0016:i===2?.0058:0),ageMinutes:i*5}));await this.settle();return fixtures;},
  async publish(){gridlyOfficialProviderConsumerRefresh({providerId:'drivetexas',reason:'interval_live_refresh'});await this.settle();},
  capture(label,expected){const published=gridlyCommunityPulseAuditState.activeAwareness?.activeAwarenessCount,projection=gridlyGetGovernedConsumerProjection(),fresh=buildGridlyCommunityPulseModel(),counts=Object.fromEntries(['locationContext','communityPulse','kbygCommunity','alerts'].map(k=>[k,projection.surfaces[k].length]));return {at:performance.now(),canonicalRevision:gridlyGetCanonicalActiveCommunityState().revision,publishedRevision:gridlyCommunityPulseAuditState.communityAwarenessSummary?.canonicalCommunityRevision,reportVersion:crossingRenderReportsVersion,countyGeneration:gridlyActiveCountyTransitionGeneration,label,expected,context:lp24449b1.identity(),published,fresh:fresh.activeAwareness.activeAwarenessCount,counts,location:document.getElementById('mobileAwarenessPanelIssues').innerText,pulseDOM:document.getElementById('gridlyCommunityPulseSubline').innerText,markers:unifiedIncidentLayer.getLayers().map(m=>m.options.incidentId),activeRailMarkers:[...crossingMarkers].filter(([,m])=>m.options.gridlyCommunityStatus==='active').map(([id])=>id),coverage:gridlyGetLocalSourceCoverage(),pass:published===expected&&fresh.activeAwareness.activeAwarenessCount===expected&&Object.values(counts).every(n=>n===expected)&&!document.body.innerText.includes('undefinedm')};}
 };});
 for(const order of ['provider-before-clear','provider-queued-at-clear','provider-after-clear']){const result=await p.evaluate(async order=>{await b1Clear.reset();const [fixture]=await b1Clear.add(['flooded-roadway']);if(order==='provider-before-clear')await b1Clear.publish();const ordering=[];const mark=label=>ordering.push(b1Clear.capture(label,NaN));const before=b1Clear.capture('active',1);mark('before-report-refresh');const pending=loadSharedReports('interval_live_refresh');mark('report-refresh-started');if(order==='provider-queued-at-clear')gridlyOfficialProviderConsumerRefresh({providerId:'drivetexas',reason:'interval_live_refresh'});mark('before-clear');gridlyLocalTestReports.clearOne(fixture.id);mark('after-clear');if(order==='provider-after-clear')gridlyOfficialProviderConsumerRefresh({providerId:'drivetexas',reason:'interval_live_refresh'});refreshGridlyCommunityPulseSharedModel({reason:'b1-concurrent-clear'});gridlyGetGovernedConsumerProjection();await Promise.resolve(pending);mark('report-refresh-resolved');await b1Clear.settle();const states=[before,b1Clear.capture('after-overlap',0)];await gridlyRunAlertsBackgroundRefreshAfterOpen('alerts_open_background_refresh');await b1Clear.settle();states.push(b1Clear.capture('after-alerts-refresh',0));return {name:order,ordering,states,pass:states.every(r=>r.pass)};},order);records.push(result);write(`${out}/generation-races.json`,{records,network:evidence});console.log(JSON.stringify({name:order,pass:result.pass}));}
 write(`${out}/generation-races.json`,{records,network:evidence,passed:records.every(r=>r.pass)});
}finally{await session.close();}
