import fs from 'node:fs';import {read,write,out} from './inventory.mjs';
const race=read('reports/lp24449b1/publication-race-before.json'),sequence=read('reports/lp24449b1/provenance-statewide.json');
const failure=sequence.records.find(row=>row.failed),id=failure.fixture.id;
write(`${out}/proven-root-cause.json`,{provenAt:new Date().toISOString(),productPatched:false,
 rootCause:'Same-area published community summaries are reusable without the existing canonical community revision. A DriveTexas consumer publication while a local report is active captures that normalized report in activeHazardsInArea. After clear removes the current authoritative rows, getGridlyAlertsSurfaceActiveCommunityReportRows falls back to the still-area-valid published summary; its original report object re-enters the lightweight Pulse model. Shared-model caching then republishes the wrong count.',
 exactCandidate:{id,county:failure.row.county_id,place:failure.row.place_geoid,object:failure.full.lightweight.selectedDetail.recordObject,source:'published summary activeHazardsInArea',firstRetainer:'gridlyGetPublishedAwarenessAlertRecordsForCurrentArea',downstream:['getGridlyAlertsSurfaceActiveCommunityReportRows','getGridlyUserFacingActiveRoadHazardIncidents','buildGridlyLightweightActiveAwareness','buildGridlyCommunityPulseModel','refreshGridlyCommunityPulseSharedModel']},
 evidence:{sequence:'provenance-statewide.json',pairedRace:'publication-race-before.json',pairedCases:race.records.map(row=>({county:row.row.county_id,place:row.row.place_geoid,publishBeforeClear:row.publish,immediate:row.proof.immediate.published.count,at2000:row.proof.samples.at(-1).state.published.count,afterRefreshes:row.proof.refreshes.map(r=>r.state.published.count)}))},
 visibleDifference:'Visible consumers read the governed projection, which is empty. The legacy active-awareness branch additionally trusts the old same-area publication.',
 sequenceSensitivity:'A provider/periodic publication must occur in the active interval. Five paired witnesses/controls clear without it and fail deterministically with it; county identity is not causal.',
 repairPlan:'Bind existing community-summary caches to gridlyGetCanonicalActiveCommunityState().revision at construction. Reject stale revisions at reuse/publication, rebuilding only a stale incoming summary when required. Preserve the existing official source envelope and retention contract; no timer, count override, fixture special case or blanket purge.',
 hypotheses:[
 [1,'RULED_OUT','raw activeHazards and normalized activeReports empty'],[2,'RULED_OUT','grouped current incident arrays empty'],[3,'RULED_OUT','marker layers/DOM empty after clear; retained object originates in publication'],[4,'RULED_IN','same-area cached summary retains obsolete community candidate'],[5,'RULED_OUT','new candidate collections inherit publication fallback; no persistent Set/Map removal failure'],[6,'RULED_OUT','same normalized object identity followed through fallback; raw removal succeeds'],[7,'PROVEN','published activeHazardsInArea retains original normalized report'],[8,'PROVEN','community clear revision missing from summary validity'],[9,'RULED_OUT','accepted context generation remains identical across clear; data revision changes'],[10,'PROVEN','provider publication before clear is causal; absence is paired passing control'],[11,'PROVEN','provider publication captures active model; later refreshes reuse old candidate'],[12,'RULED_OUT','fresh contexts in all three witnesses and two controls reproduce'],[13,'RULED_OUT','retained identity is exact flood fixture, not a crossing'],[14,'PROVEN','fixture/raw overlay removed; published normalized object remains'],[15,'PROVEN','cache keyed by area without canonical clear revision'],[16,'RULED_OUT','production provider consumer publication reproduces on fresh contexts with passive timed reads']
 ].map(([id,result,evidence])=>({id,result,evidence}))});
console.log(JSON.stringify({paired:race.records.length,forcedFailures:race.records.filter(r=>r.publish&&r.proof.immediate.published.count===1).length,controls:race.records.filter(r=>!r.publish&&r.proof.immediate.published.count===0).length,id}));
