import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const root=process.cwd(),artifacts=path.join(root,'.artifacts/lp24449b'),out=path.join(root,'reports/lp24449b');
const git=(...args)=>execFileSync('git',args,{encoding:'utf8'}).trim();
const branch=git('branch','--show-current'),head=git('rev-parse','HEAD');
if(branch!=='LP244.48-destination-quick-check-around-me'||head!=='5538432be3bfe12c6dc0d3f34dcc9fd97c6edc3c'||git('diff','HEAD','--name-only'))throw Error('Starting baseline mismatch');
if(fs.existsSync(path.join(artifacts,'baseline.json')))throw Error('Baseline already captured; never overwrite');
fs.mkdirSync(artifacts,{recursive:true});fs.mkdirSync(out,{recursive:true});
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(dir+'/'+e.name):[dir+'/'+e.name]);
const tracked=git('ls-files').split('\n');
const protectedPaths=[...new Set([...JSON.parse(fs.readFileSync('reports/lp24449a/starting-baseline.json')).protectedFiles.map(r=>r.file),...tracked.filter(f=>/^(android\/|ios\/|native\/|capacitor|package(?:-lock)?\.json)/.test(f))])].sort();
const evidencePaths=['reports/lp24449','tools/lp24449','.artifacts/lp24449','reports/lp24449a','tools/lp24449a','.artifacts/lp24449a'].flatMap(walk).concat(walk('docs/launch').filter(f=>/\/LP24449(?:A)?-/.test(f)));
const baseline={capturedAt:new Date().toISOString(),branch,head,status:git('status','--short'),log:git('log','--oneline','-20'),diffStat:git('diff','HEAD','--stat'),protectedFiles:protectedPaths.map(file=>({file,sha256:hash(file)})),priorEvidence:evidencePaths.map(file=>({file,sha256:hash(file)}))};
fs.writeFileSync(path.join(artifacts,'baseline.json'),JSON.stringify(baseline,null,2)+'\n');
fs.writeFileSync(path.join(out,'starting-baseline.json'),JSON.stringify(baseline,null,2)+'\n');
fs.copyFileSync('js/app.js',path.join(artifacts,'baseline-app.js'));
fs.copyFileSync('js/gridlyWeatherLiveConnector.js',path.join(artifacts,'baseline-weather.js'));
const codes=['PROVIDER_HEALTH_FALSE','CROSSING_ELIGIBLE_PACKAGE_MISSING','PULSE_PUBLISHED_COUNT_STALE_AFTER_CLEAR','FILTER_COUNTY_WRONG_SCOPE'];
const ledger=JSON.parse(fs.readFileSync('reports/lp24449/failure-ledger.json'));
const residuals=ledger.map((row,index)=>({originalFailureId:`LP24449-ledger-${String(index+1).padStart(5,'0')}`,originalLedgerIndex:index,...row})).filter(row=>codes.includes(row.code));
if(residuals.length!==2020)throw Error('Unexpected residual count');
fs.writeFileSync(path.join(out,'original-residual-failures.json'),JSON.stringify(residuals,null,2)+'\n');
console.log(JSON.stringify({branch,head,trackedClean:true,residuals:residuals.length,counts:Object.fromEntries(codes.map(code=>[code,residuals.filter(row=>row.code===code).length])),protectedFiles:protectedPaths.length,priorEvidence:evidencePaths.length}));
