import fs from 'node:fs';
import {execFileSync} from 'node:child_process';
const rows=JSON.parse(fs.readFileSync('reports/lp24449b/original-residual-failures.json'));
if(execFileSync('git',['diff','HEAD','--name-only'],{encoding:'utf8'}).trim())throw Error('Clustering must precede product edits');
const seams={
 PROVIDER_HEALTH_FALSE:{state:'ZERO_KNOWN_ISSUES_WITH_UNAVAILABLE_SOURCES',functions:['js/app.js:buildGridlyLocationContextMetricLines','js/app.js:gridlyTravelBriefConfidenceLine','js/app.js:gridlyGetAwarenessEvidenceCompleteness'],firstDivergence:'Zero active count becomes unqualified quiet copy without requiring complete source health.',rca:'shared consumer truthfulness gate; source-specific availability already exposed',confidence:'source-confirmed; controlled replay pending'},
 CROSSING_ELIGIBLE_PACKAGE_MISSING:{state:'STATIC_INVENTORY',functions:['tools/lp24449/pipeline.mjs','tools/wave3a1b/build-fra-county-authority.mjs','tools/wave3a2/build-crossing-package-manufacture.mjs'],firstDivergence:'Original certifier requires canonical membership source-FIPS identities in operational county package; existing package policy uses certified coordinate containment and preserves source FIPS separately.',rca:'likely shared certifier authority mismatch; each identity still requires verification',confidence:'architecture-confirmed; identity replay pending'},
 PULSE_PUBLISHED_COUNT_STALE_AFTER_CLEAR:{state:'ACTIVE_TO_CLEARED',functions:['js/app.js:publishGridlyCommunityPulseAuditState','tools/lp24449/runtime-probe.js:snapshot','tools/lp24449/convergence-recheck.mjs'],firstDivergence:'Original published activeAwareness count remains one while canonical rows and visible consumers clear; isolated replays converge.',rca:'unresolved: observe raw publication before calling model builders',confidence:'not yet deterministic; no product repair justified'},
 FILTER_COUNTY_WRONG_SCOPE:{state:'EXPLICIT_SEARCH_TO_COUNTY_FILTER',functions:['js/app.js:gridlyResolveCountyModeActiveContext','js/app.js:applyGeoFilterFromPill'],firstDivergence:'County filter resolves PLACE presentation coordinates before accepted operational county, potentially switching a multi-county place to its coordinate county.',rca:'shared coordinate-priority resolver; Aransas Pass original witness',confidence:'source-confirmed; current-baseline browser replay pending'}
};
const members=rows.map(r=>({originalFailureId:r.originalFailureId,code:r.code,county:r.county_id,community:r.community,place_geoid:r.place_geoid,operationalCounty:r.county_id,membership:`${r.place_geoid}/${r.county_id}`,consumer:r.consumer,...seams[r.code],sourceEvidence:r.detail.evidence||r.detail.comparisonEvidence||r.detail.screenshot||null}));
const groups=Object.entries(seams).map(([code,seam])=>({code,count:members.filter(r=>r.code===code).length,counties:[...new Set(members.filter(r=>r.code===code).map(r=>r.county))],...seam,originalFailureIds:members.filter(r=>r.code===code).map(r=>r.originalFailureId)}));
fs.writeFileSync('reports/lp24449b/residual-clustering.json',JSON.stringify({createdAt:new Date().toISOString(),phase:'PRE_PATCH_AUDIT',productUnchanged:true,total:members.length,groups,members},null,2)+'\n');
for(const file of ['inventory.mjs','session.cjs','runtime-probe.js'])fs.writeFileSync(`tools/lp24449b/${file}`,fs.readFileSync(`tools/lp24449a/${file}`,'utf8').replaceAll('lp24449a','lp24449b'));
fs.writeFileSync('tools/lp24449b/original-sequence-probe.js',fs.readFileSync('tools/lp24449/runtime-probe.js','utf8'));
console.log(JSON.stringify({total:members.length,groups:groups.map(g=>({code:g.code,count:g.count}))}));
