import fs from 'node:fs';import crypto from 'node:crypto';
import {read,write,out,artifacts,loadInventory} from './inventory.mjs';
import {summarizeAttempts} from './attempt-summary.mjs';
const inv=loadInventory(),required=name=>read(`reports/lp24449b/${name}.json`),key=r=>`${r.county_id}|${r.place_geoid}`;
const sourceHash=crypto.createHash('sha256').update(fs.readFileSync('js/app.js')).digest('hex');
const weatherHash=crypto.createHash('sha256').update(fs.readFileSync('js/gridlyWeatherLiveConnector.js')).digest('hex');
const original=required('original-residual-failures'),search=required('search-recertification'),matrix=required('provider-health-matrix'),crossings=required('crossing-statewide-recertification'),ownership=required('crossing-ownership-replay'),pulseBaseline=read('.artifacts/lp24449b/baseline-pulse.json'),pulseCurrent=read('.artifacts/lp24449b/current-pulse.json'),pulseStatewide=required('pulse-statewide'),filter=required('filter-lifecycle'),rail=required('rail-lifecycle'),ui=required('ui-messages'),integrity=required('integrity'),identity=required('identity-regression/decision'),identityBrowser=required('identity-regression/browser-summary'),targeted=required('targeted-tests');
const searches=new Map(search.records.map(r=>[key(r),r])),crossingRows=new Map(crossings.rows.map(r=>[key(r),r]));
const pulseBlocker=required('pulse-blocker-analysis');
const currentPulseFailures=new Map(pulseBlocker.currentFindings.map(row=>[key(row),row]));
rail.markerPolicyPassed=rail.states.every(s=>s.marker.connected&&s.marker.icon?.endsWith(s.kind==='blocked'?'24-blocked-crossing.png':s.kind==='delay'?'23-reported-crossing-delay.png':'25-crossing-location.png')&&s.marker.status===(s.count>0?'active':'inventory'));
rail.passed=rail.passed&&rail.markerPolicyPassed;write(`${out}/rail-lifecycle.json`,rail);
const csv=(name,headers,rows)=>fs.writeFileSync(`${out}/${name}.csv`,[headers,...rows].map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n')+'\n');
const replay=[];
const originalPulseCaptureConverged=r=>r?.originalCaptureReplay?.active.pulse.count===1&&r.originalCaptureReplay.cleared.pulse.count===0&&r.originalCaptureReplay.beforeOriginalSnapshot.publication?.activeAwareness?.activeAwarenessCount===0&&r.originalCaptureReplay.afterOriginalSnapshot.publication?.activeAwareness?.activeAwarenessCount===0;
for(const row of original){let pass=false,status='STILL_FAIL',reason='',proof=[];
 if(row.code==='PROVIDER_HEALTH_FALSE'){const s=searches.get(key(row));pass=s?.checks.sourceTruth===true&&matrix.passed;status=pass?'FIXED':'STILL_FAIL';reason='Current accepted membership uses the existing source authorities; unavailable plus zero is not presented as a complete quiet state.';proof=['search-recertification.json','provider-health-matrix.json'];}
 if(row.code==='CROSSING_ELIGIBLE_PACKAGE_MISSING'){const r=ownership.assertions.find(r=>r.originalFailureId===row.originalFailureId);pass=r?.classification==='RECLASSIFIED';for(const item of ownership.identities.filter(i=>i.originalFailureId===row.originalFailureId)){const owner=item.packages[0]?.county;const browser=search.records.find(s=>s.county_id===owner&&s.crossingProof.owner===owner&&s.crossingProof.inventoryIds.includes(item.runtimeId));item.runtimeOwnerBrowserProof=browser?{county:owner,place:browser.place_geoid,id:item.runtimeId,loaded:true}:null;pass&&=!!browser&&Object.values(item.checks).every(Boolean);}status=pass?'RECLASSIFIED':'STILL_FAIL';reason='FRA source-county lineage is not package ownership. Certified polygon containment, governed package, adapter ID, and current browser inventory agree.';proof=['crossing-ownership-replay.json','crossing-statewide-recertification.json','search-recertification.json'];}
 if(row.code==='PULSE_PUBLISHED_COUNT_STALE_AFTER_CLEAR'){const before=pulseBaseline.find(r=>r.originalFailureId===row.originalFailureId),after=pulseCurrent.find(r=>r.originalFailureId===row.originalFailureId);const zero=r=>r?.samples?.length===6&&r.samples.every(s=>s.raw.publication?.activeAwareness?.activeAwarenessCount===0)&&r.model?.pulse.count===0&&['locationContext','communityPulse','kbygCommunity','alerts'].every(k=>r.model.rows[k].length===0)&&r.refreshed?.publication?.activeAwareness?.activeAwarenessCount===0;
  pass=zero(before)&&zero(after)&&originalPulseCaptureConverged(before)&&originalPulseCaptureConverged(after)&&after.samples.every(s=>s.raw.groupedSnapshot?.active.length===0&&s.raw.hazardMarkers.length===0)&&after.originalContextReturn?.publication?.activeAwareness?.activeAwarenessCount===0&&after.originalCountyTransition?.searched.pulse.count===0&&after.originalCountyTransition?.returned.pulse.count===0&&pulseStatewide.passed;status=pass?'RECLASSIFIED':'STILL_FAIL';reason='Already converges on the starting HEAD and final source: immediate raw publication, 100/250/500/1000/2000 ms, normal refresh, original capture helper/order and original context transitions. Original historical stale audit snapshot is preserved; no deterministic current state-management defect was reproduced. Historical writer ordering is not recoverable from the old count-only capture.';proof=['.artifacts/lp24449b/baseline-pulse.json','.artifacts/lp24449b/current-pulse.json','pulse-statewide.json'];}
 if(row.code==='FILTER_COUNTY_WRONG_SCOPE'){const s=searches.get(key(row));pass=s?.checks.countyFilterOwner===true&&s.filterAfter.activeCounty==='aransas-tx'&&filter.passed;status=pass?'FIXED':'STILL_FAIL';reason='County view takes the accepted operational county before geographic centroid fallback. Search, Around Me, Return Home and Route Watch protection are checked separately.';proof=['search-recertification.json','filter-lifecycle.json','.artifacts/lp24449b/baseline-filter.json'];}
 if(row.code==='PULSE_PUBLISHED_COUNT_STALE_AFTER_CLEAR'&&!pass){reason='Original isolated baseline/current witnesses converge, but family closure remains blocked by independently reproduced stale publication counts in statewide sequences. See pulse-blocker-analysis.json; this is not certified as a timing artifact.';proof.push('pulse-blocker-analysis.json');}
 replay.push({originalFailureId:row.originalFailureId,code:row.code,county_id:row.county_id,place_geoid:row.place_geoid,community:row.community,consumer:row.consumer,status,reason,proof});
}
write(`${out}/crossing-ownership-replay.json`,ownership);
const providerReplay=replay.filter(r=>r.code==='PROVIDER_HEALTH_FALSE');write(`${out}/provider-health-replay.json`,{original:1997,records:providerReplay,matrix:'provider-health-matrix.json',passed:providerReplay.length===1997&&providerReplay.every(r=>r.status==='FIXED')});
csv('provider-health-replay',['original_failure_id','county','place_geoid','status'],providerReplay.map(r=>[r.originalFailureId,r.county_id,r.place_geoid,r.status]));
write(`${out}/pulse-replay.json`,{original:10,records:replay.filter(r=>r.code==='PULSE_PUBLISHED_COUNT_STALE_AFTER_CLEAR'),stateManagementRepair:false,presentationCopyRepair:true,classification:pulseBlocker.classification,originalTimedReplaysConverge:true,currentFindings:pulseBlocker.currentFindings,blockerEvidence:'pulse-blocker-analysis.json',timingTargetsMs:[0,100,250,500,1000,2000],baseline:pulseBaseline.map(r=>({id:r.originalFailureId,counts:r.samples.map(s=>s.raw.publication?.activeAwareness?.activeAwarenessCount)})),current:pulseCurrent.map(r=>({id:r.originalFailureId,counts:r.samples.map(s=>s.raw.publication?.activeAwareness?.activeAwarenessCount),returned:r.originalContextReturn?.publication?.activeAwareness?.activeAwarenessCount,transition:r.originalCountyTransition?.returned.pulse.count})),statewide:{count:pulseStatewide.records.length,passed:pulseStatewide.passed}});
const filterRows=search.records.filter(r=>r.is_multi_county).map(r=>({...r.filterAfter,county_id:r.county_id,place_geoid:r.place_geoid,pass:r.checks.countyFilterOwner}));
write(`${out}/filter-scope-replay.json`,{original:replay.filter(r=>r.code==='FILTER_COUNTY_WRONG_SCOPE'),multiCountyMemberships:filterRows.length,passed:filterRows.filter(r=>r.pass).length,rows:filterRows,lifecycle:'filter-lifecycle.json'});
const fixed=replay.filter(r=>r.status==='FIXED').length,reclassified=replay.filter(r=>r.status==='RECLASSIFIED').length,remaining=replay.filter(r=>r.status==='STILL_FAIL');
write(`${out}/replay-results.json`,{sourceHash,weatherHash,original:original.length,fixed,reclassified,remaining:remaining.length,records:replay});csv('replay-results',['original_failure_id','code','county','place_geoid','status','reason'],replay.map(r=>[r.originalFailureId,r.code,r.county_id,r.place_geoid,r.status,r.reason]));
const blockers=[],gate=(name,pass)=>{if(!pass)blockers.push(name);};
gate('Authorized branch and pre-commit HEAD',integrity.branch==='LP244.48-destination-quick-check-around-me'&&integrity.head==='5538432be3bfe12c6dc0d3f34dcc9fd97c6edc3c');
gate('All 2020 original residual closure assertions pass',replay.length===2020&&new Set(replay.map(r=>r.originalFailureId)).size===2020&&remaining.length===0);
gate('Provider ten-state matrix',matrix.passed&&matrix.states.length===10);
gate('All crossing memberships and packages',crossings.summary.passed===2058&&ownership.summary.geometryPassed===14&&crossings.packageAudit.packages.length===254&&crossings.packageAudit.packages.every(r=>r.pass));
gate('254 Pulse representative active/clear cases',pulseStatewide.passed&&pulseStatewide.records.length===254);
gate('362 actual County-filter interactions',filterRows.length===362&&filterRows.every(r=>r.pass)&&filter.passed);
gate('Protected LP244.49A identity gates',identity.decision==='APPROVE');
gate('Rail lifecycle',rail.passed);gate('Around Me messages, Route Details contrast, close controls',ui.passed);
gate('Focused regressions',targeted.passed&&targeted.weatherRegressionProven);gate('Integrity',integrity.protectedPass&&integrity.priorEvidencePass&&integrity.markerPass&&integrity.productSourceSha256===sourceHash);
gate('Final source statewide browser',search.sourceHash===sourceHash&&search.count===2058&&search.passed===2058);
gate('Final weather compatibility',required('final-weather-tests').exitCode===0&&required('final-weather-tests').weatherHash===weatherHash);
gate('Final weather source integrity',integrity.weatherSourceSha256===weatherHash);
const rows=inv.rows.map(r=>{const s=searches.get(key(r)),c=crossingRows.get(key(r));const checks={search:!!s?.pass,sourceTruth:!!s?.checks.sourceTruth,crossings:!!c?.pass&&s?.crossingProof.owner===r.county_id&&s?.crossingProof.allOwned,countyFilter:!r.is_multi_county||s?.checks.countyFilterOwner===true,weatherLocality:!!s?.checks.weatherPlace&&s?.checks.weatherCounty,pulseClear:!currentPulseFailures.has(key(r))};const localPass=Object.values(checks).every(Boolean);return {...r,checks,localPass,liveProviderStatus:'NEEDS_LIVE_PROVIDER_CONFIRMATION',certificationStatus:localPass?'CONDITIONAL':'FAIL',evidence:['search-recertification.json','crossing-statewide-recertification.json','identity-regression/decision.json']};});
gate('Exact statewide inclusion and local acceptance',rows.length===2058&&new Set(rows.map(r=>r.place_geoid)).size===1859&&new Set(rows.map(r=>r.county_id)).size===254&&rows.every(r=>r.localPass));
const decision=blockers.length?'HOLD':'CONDITIONAL';
write(`${out}/statewide-community-recertification.json`,{sourceHash,weatherHash,decision,count:rows.length,localPassed:rows.filter(r=>r.localPass).length,rows});csv('statewide-community-recertification',['county_id','place_geoid','community','local_pass','certification_status','live_provider_status'],rows.map(r=>[r.county_id,r.place_geoid,r.community_name,r.localPass,r.certificationStatus,r.liveProviderStatus]));
const summarize=(items,select,id)=>items.map(item=>{const selected=rows.filter(r=>select(r,item));return {[id]:item[id],memberships:selected.length,localPass:selected.every(r=>r.localPass),status:selected.every(r=>r.localPass)?'CONDITIONAL':'FAIL'};});
const counties=summarize(inv.counties,(r,c)=>r.county_id===c.countyId,'countyId'),communities=summarize(inv.communities,(r,c)=>r.place_geoid===c.placeGeoid,'placeGeoid');write(`${out}/county-summary.json`,{total:254,localPassed:counties.filter(r=>r.localPass).length,pass:0,conditional:counties.filter(r=>r.localPass).length,fail:counties.filter(r=>!r.localPass).length,rows:counties});write(`${out}/community-summary.json`,{total:1859,localPassed:communities.filter(r=>r.localPass).length,pass:0,conditional:communities.filter(r=>r.localPass).length,fail:communities.filter(r=>!r.localPass).length,rows:communities});
write(`${out}/provider-summary.json`,{sourceModel:'source-health-model.json',matrixPass:matrix.passed,originalReplays:providerReplay.length,liveProviderStatus:'NEEDS_LIVE_PROVIDER_CONFIRMATION',membershipCount:2058,countyCount:254,communityCount:1859,native:'NOT_DEVICE_TESTED',scope:'Only deterministic local responses and blocked/unavailable sources; no live provider certification is claimed.'});
write(`${out}/browser-summary.json`,{...identityBrowser,providerMatrix:{count:matrix.states.length,passed:matrix.passed},pulseOriginal:{count:10,passed:replay.filter(r=>r.code==='PULSE_PUBLISHED_COUNT_STALE_AFTER_CLEAR').every(r=>r.status!=='STILL_FAIL')},pulseStatewide:{count:pulseStatewide.records.length,passed:pulseStatewide.passed},filters:{multi:filterRows.length,passed:filterRows.filter(r=>r.pass).length,lifecycle:filter.passed},rail:rail.passed,uiMessages:ui.passed});
const homes=required('identity-regression/home-browser-results').records,baseline=required('starting-baseline');const timings=[...homes.map(r=>({...r,suite:'Home'})),...search.records.map(r=>({...r,suite:'Search'}))];
const slow=timings.slice().sort((a,b)=>b.runtimeMs-a.runtimeMs)[0],countyTimes=inv.counties.map(c=>({county:c.countyId,totalMs:timings.filter(r=>r.county_id===c.countyId).reduce((n,r)=>n+(r.runtimeMs||0),0)})).sort((a,b)=>b.totalMs-a.totalMs);
write(`${out}/performance.json`,{startedAt:baseline.capturedAt,generatedAt:new Date().toISOString(),elapsedWallMs:Date.now()-Date.parse(baseline.capturedAt),concurrencyLimit:2,completedBrowserScenarioCount:homes.length+search.records.length+254+19+67+17+10+10+pulseStatewide.records.length+filter.records.length+rail.states.length+ui.location.length+ui.routeDetails.length+ui.closeControls.length,scenarioDefinition:'Top-level suite records; Home save/reload/Return is one transaction, and embedded subchecks are not counted again.',assertionExecutions:read('.artifacts/lp24449b/static-certification.json').checks.length+homes.reduce((n,r)=>n+Object.keys(r.checks).length,0)+search.records.reduce((n,r)=>n+Object.keys(r.checks).length,0)+crossings.rows.reduce((n,r)=>n+Object.keys(r.checks).length,0)+pulseStatewide.records.reduce((n,r)=>n+Object.keys(r.checks||{}).length,0)+matrix.states.reduce((n,r)=>n+Object.keys(r.checks||{}).length,0),assertionDefinition:'Named static, Home, Search, crossing, Pulse and provider checks. Test-runner and visual subchecks are reported separately.',summedHomeAndSearchMs:timings.reduce((n,r)=>n+(r.runtimeMs||0),0),slowestMembership:slow?{suite:slow.suite,county:slow.county_id,place:slow.place_geoid,runtimeMs:slow.runtimeMs}:null,slowestCounty:countyTimes[0],timeouts:timings.filter(r=>/timeout/i.test(r.error||'')),retries:'JSONL checkpoints retain attempts; final report chooses the latest final-source membership record.'});
const attemptSummary=summarizeAttempts(artifacts,sourceHash);write(`${out}/attempt-summary.json`,attemptSummary);
const performance=required('performance');performance.attempts=attemptSummary;
performance.browserScenarioComponents={Home:homes.length,Search:search.records.length,crossCounty:identityBrowser.crossCounty.tested,startupProfiles:identityBrowser.profiles.tested,visibleSearch:identityBrowser.visibleSearch.tested,NuecesOriginalWitnesses:required('nueces-baseline-replay').count,providerMatrix:matrix.states.length,originalPulseBaseline:pulseBaseline.length,originalPulseCurrent:pulseCurrent.length,PulseCountyRepresentatives:pulseStatewide.records.length,filterLifecycle:filter.records.length,railStates:rail.states.length,AroundMeMessages:ui.location.length,routeDetailsThemes:ui.routeDetails.length,closeControls:ui.closeControls.length,threeHazardStates:required('freeze-three-hazards').states.length,SettingsChoicesAndReloads:read('.artifacts/lp24449b/freeze/settings.json').settings.length,SettingsViewports:read('.artifacts/lp24449b/freeze/settings.json').viewports.length,SettingsFreshDefault:1,geometryStates:read('.artifacts/lp24449b/freeze-geometry/browser.json').states.length,SavedPlacesViewports:required('freeze-saved-places').viewports.length,HomeReadComparisons:required('home-read-performance').length,textSizeComparisons:required('text-size-baseline').runs.length,historicalClearComparisons:required('freeze-clear-comparison').runs.length,AransasBaselineAndCurrent:2};
performance.completedBrowserScenarioCount=Object.values(performance.browserScenarioComponents).reduce((n,count)=>n+count,0);
performance.diagnosticBrowserScenarioCount=pulseBlocker.runs.slice(1).reduce((n,run)=>n+run.count,0)+pulseBlocker.isolated.completed;performance.totalBrowserScenarioCount=performance.completedBrowserScenarioCount+performance.diagnosticBrowserScenarioCount;performance.pulseDiagnosticRuns=pulseBlocker.runs;
performance.scenarioDefinition='Completed suite transactions or explicitly captured controlled states, itemized in browserScenarioComponents. A Home save/reload/Return transaction counts once. Exploratory provider pilots, retries and incidental subchecks are excluded; persisted attempts are separately reported. The two full Pulse diagnostics and five isolated traces are counted separately in diagnosticBrowserScenarioCount and included in totalBrowserScenarioCount.';
write(`${out}/performance.json`,performance);
write(`${out}/failure-ledger.json`,{decision,blockers,remainingOriginalFailures:remaining,statewideFailures:rows.filter(r=>!r.localPass),currentPulseFindings:pulseBlocker.currentFindings,preExistingTestFailures:identityBrowser.tests,liveProviderStatus:'NEEDS_LIVE_PROVIDER_CONFIRMATION'});
write(`${out}/decision.json`,{decision,sourceHash,weatherHash,blockers,original:2020,fixed,reclassified,remainingRealFail:rows.filter(r=>!r.localPass).length,remainingOriginalClosureAssertions:remaining.length,blockingGateCount:blockers.length,failureCountScope:'remainingRealFail counts unique currently failing memberships, including Pulse diagnostic witnesses. Ten original Pulse assertions remain unclosed (remainingOriginalClosureAssertions), not ten additional observed failures. Independent acceptance blockers also force HOLD.',generatedAt:new Date().toISOString(),liveProviderStatus:'NEEDS_LIVE_PROVIDER_CONFIRMATION'});
console.log(JSON.stringify({decision,blockers,fixed,reclassified,remaining:remaining.length}));
