import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {readFileSync,existsSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHmac,randomBytes,randomUUID} from 'node:crypto';
import {createServer} from 'node:net';
import {chromium,expect} from '@playwright/test';
const root=fileURLToPath(new URL('../../',import.meta.url)),here=fileURLToPath(new URL('./',import.meta.url));
const powershell=join(process.env.SystemRoot,'System32','WindowsPowerShell','v1.0','powershell.exe');
const powershellEnv={...process.env,PSModulePath:join(process.env.SystemRoot,'System32','WindowsPowerShell','v1.0','Modules')};
const docker='C:\\Users\\gulfi\\AppData\\Local\\Programs\\DockerDesktop\\resources\\bin\\docker.exe';
const supabase='C:\\Users\\gulfi\\AppData\\Local\\npm-cache\\_npx\\aa8e5c70f9d8d161\\node_modules\\@supabase\\cli-windows-x64\\bin\\supabase.exe';
const report=join(root,'reports','responder','dispatch-auth-owner','launcher-'+randomUUID());mkdirSync(report,{recursive:true});
const ps=(script,args=[],input)=>spawnSync(powershell,['-NoProfile','-NonInteractive','-File',join(here,script),...args],{input,encoding:'utf8',windowsHide:true,env:powershellEnv,maxBuffer:1e6});
const read=name=>readFileSync(join(here,name),'utf8');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const dock=args=>{const r=spawnSync(docker,['--host','npipe:////./pipe/dockerDesktopLinuxEngine',...args],{encoding:'utf8',windowsHide:true});assert.equal(r.status,0,'Docker assertion failed');return r.stdout.trim()};
function start(fault='None'){
 const child=spawn(powershell,['-NoProfile','-NonInteractive','-File',join(here,'owner.ps1'),'-Supabase',supabase,'-Docker',docker,'-Certification','-Fault',fault],{cwd:root,windowsHide:true,env:powershellEnv,stdio:['ignore','pipe','pipe']});let output='',errors='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>errors+=b);const done=new Promise(resolve=>child.once('close',code=>resolve(code)));return {child,done,logs:()=>output+errors,runtime:()=>output.match(/OWNER SESSION: ([^\r\n]+)/)?.[1]};
}
async function finished(run){let timeout;try{return await Promise.race([run.done,new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('Owner shutdown timeout')),240000);timeout.unref()})])}finally{clearTimeout(timeout)}}
async function ready(run){for(let i=0;i<1000;i++){const runtime=run.runtime();if(runtime&&existsSync(join(runtime,'ready.json')))return JSON.parse(readFileSync(join(runtime,'ready.json')));if(run.child.exitCode!==null)throw Error('Owner startup failed: '+run.logs());await delay(200)}throw Error('Owner startup timeout')}
function credential(runtime){const source="$s=ConvertTo-SecureString ([IO.File]::ReadAllText([Console]::In.ReadToEnd()));$p=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($s);try{[Console]::Out.Write([Runtime.InteropServices.Marshal]::PtrToStringBSTR($p))}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($p);$s.Dispose()}";const result=spawnSync(powershell,['-NoProfile','-NonInteractive','-Command',source],{input:join(runtime,'credentials.dpapi'),encoding:'utf8',windowsHide:true,env:powershellEnv});if(result.status!==0)throw Error('Private credential test failed');return JSON.parse(result.stdout)}
function totp(secret){let bits='';for(const c of secret.replace(/=+$/,'').toUpperCase())bits+='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(c).toString(2).padStart(5,'0');const key=[];for(let i=0;i+8<=bits.length;i+=8)key.push(parseInt(bits.slice(i,i+8),2));const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)));const hash=createHmac('sha1',Buffer.from(key)).update(counter).digest(),offset=hash.at(-1)&15;return String((hash.readUInt32BE(offset)&0x7fffffff)%1e6).padStart(6,'0')}
await test('existing guard and frontend files remain unchanged in launcher design',()=>{assert.ok(read('owner.ps1').includes("'context-docker-guard.cs'"));assert.ok(read('owner-runtime.mjs').includes("allowedUsers:[account.userId]"));assert.ok(!read('owner-runtime.mjs').includes('grant_type=password'));assert.ok(!read('owner-runtime.mjs').includes('/factors'));assert.ok(read('owner.ps1').includes('[Console]::TreatControlCAsInput=$true'));assert.ok(read('owner.ps1').includes('[int]$key.KeyChar -eq 3'));});
await test('occupied UI port refuses startup and preserves unrelated listener',async()=>{const server=createServer();await new Promise(resolve=>server.listen(4180,'127.0.0.1',resolve));try{const run=start();assert.notEqual(await finished(run),0);assert.match(run.logs(),/Expected port occupied: 4180/);assert.equal(run.runtime(),undefined);assert.ok(server.listening)}finally{server.closeAllConnections?.();await new Promise(resolve=>server.close(resolve))}});
await test('invalid stop path cannot affect any session',()=>{assert.notEqual(ps('owner-stop.ps1',['-SessionPath',root]).status,0)});
await test('credential storage is DPAPI, round trips privately and emits no password',()=>{
 const runtime=join(tmpdir(),'gridly-dispatch-auth-'+randomBytes(6).toString('hex'));mkdirSync(runtime);const path=join(runtime,'credentials.dpapi'),value={email:'local-owner-'+randomUUID()+'@dispatch.invalid',password:randomBytes(32).toString('base64url')};
 try{const input=JSON.stringify(value),sealed=ps('owner-credentials.ps1',['-Mode','Seal','-Path',path],input);if(sealed.status!==0)throw Error('DPAPI seal failed: '+sealed.stderr.replaceAll(value.password,'[private]').replaceAll(value.email,'[synthetic]'));if((sealed.stdout+sealed.stderr).includes(value.password)||readFileSync(path,'utf8').includes(value.password))throw Error('Credential leakage detected');assert.equal(ps('owner-credentials.ps1',['-Mode','Verify','-Path',path],input).status,0,'DPAPI verification failed')}finally{rmSync(runtime,{recursive:true,force:true})}
});
await test('startup failure after network creation cleans exact owned resources',async()=>{const run=start('AfterNetwork');assert.notEqual(await finished(run),0);const runtime=run.runtime();assert.ok(runtime);assert.ok(!existsSync(runtime));assert.match(run.logs(),/CLEANUP PASS/);assert.equal(dock(['network','ls','--filter','name='+runtime.split(/[\\/]/).at(-1),'-q']),'')});
await test('failure after synthetic provisioning removes database and encrypted credentials',async()=>{const run=start('AfterProvision');assert.notEqual(await finished(run),0);assert.ok(run.runtime());assert.ok(!existsSync(run.runtime()));assert.match(run.logs(),/startup refused at after-provision/);assert.match(run.logs(),/CLEANUP PASS/);writeFileSync(join(report,'failed-startup.json'),JSON.stringify({cleanup:true,secretRetained:false}))});
await test('retained owner UI: real sign-in, manual TOTP, authorized departments, logout and exact cleanup',{timeout:300000},async()=>{
 const control='gridly-owner-control-'+randomBytes(6).toString('hex');dock(['create','--name',control,'public.ecr.aws/supabase/mailpit:v1.31.3']);const run=start();let browser,context,account,secret,phase='startup';
 try{
  const state=await ready(run),runtime=run.runtime();account=credential(runtime);phase='runtime-proof';assert.equal(state.url,'http://127.0.0.1:4180/');assert.equal(state.units.length,2);assert.equal(state.catalogUnchanged,true);
  phase='private-ACL';const acl=spawnSync(powershell,['-NoProfile','-NonInteractive','-Command',"$a=Get-Acl -LiteralPath ([Console]::In.ReadToEnd());[Console]::Out.Write(($a.Access | ForEach-Object {$_.IdentityReference.Translate([Security.Principal.SecurityIdentifier]).Value}) -join ',')"],{input:runtime,encoding:'utf8',windowsHide:true,env:powershellEnv});assert.equal(acl.status,0);assert.ok(!/S-1-1-0|S-1-5-32-545|S-1-5-11/.test(acl.stdout));
  phase='browser-start';browser=await chromium.launch({channel:'msedge',headless:true});context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();await page.goto(state.url);await page.locator('#login').waitFor();await page.screenshot({path:join(report,'owner-login.png')});
  phase='anonymous-denial';const unauthenticated=await context.request.get(state.url+'api/context',{headers:{'X-Gridly-Dispatch':'local-auth'}});assert.equal(unauthenticated.status(),401);
  phase='sign-in-and-enrollment';await page.evaluate(({email,password})=>{document.querySelector('#email').value=email;document.querySelector('#password').value=password;document.querySelector('#login').requestSubmit()},account);await page.locator('#totp').waitFor();await page.locator('#enroll').click();await expect(page.locator('#enrollment-secret')).toContainText('setup key');secret=(await page.locator('#enrollment-secret').innerText()).split(': ').at(-1);
  phase='TOTP-and-context';await page.locator('#code').fill(totp(secret));await page.locator('#totp button').click();await page.locator('#authorized-unit').waitFor();assert.equal(await page.locator('#authorized-unit option').count(),2);const labels=await page.locator('#authorized-unit option').allTextContents();assert.ok(labels.every(v=>v.startsWith('Synthetic Acceptance Agency')));await page.locator('#authorized-unit').selectOption(state.units[1]);await expect(page.locator('#authorized-unit')).toHaveValue(state.units[1]);await page.screenshot({path:join(report,'owner-authorized.png')});
  phase='disabled-routes';assert.equal((await context.request.post(state.url+'api/notices',{headers:{Origin:state.url.slice(0,-1),'X-Gridly-Dispatch':'local-auth'},data:{}})).status(),404);assert.equal((await context.request.get(state.url+'demo/fixtures.mjs')).status(),404);
  phase='browser-secrecy';const body=await page.content();if(body.includes(account.password)||body.includes(secret)||/eyJ[a-zA-Z0-9_-]+\./.test(body))throw Error('Browser authority leakage');
  phase='logout';await page.locator('#logout').click();await page.locator('#login').waitFor();await expect(page.locator('#auth-message')).toHaveText('Signed out.');await page.reload();await page.locator('#login').waitFor();
  phase='log-secrecy';const logs=run.logs()+readFileSync(join(runtime,'worker.out'),'utf8')+readFileSync(join(runtime,'worker.err'),'utf8');if(logs.includes(account.password)||logs.includes(secret)||/eyJ[a-zA-Z0-9_-]+\./.test(logs))throw Error('Private material in launcher logs');
  for(const file of ['owner-login.png','owner-authorized.png']){const bytes=readFileSync(join(report,file));if(bytes.includes(Buffer.from(account.password))||bytes.includes(Buffer.from(secret)))throw Error('Screenshot leakage')}
  phase='normal-stop';const stop=ps('owner-stop.ps1',['-SessionPath',runtime]);assert.equal(stop.status,0);assert.equal(await finished(run),0);assert.ok(!existsSync(runtime));assert.match(run.logs(),/CLEANUP PASS/);assert.equal(dock(['inspect',control,'--format','{{.State.Running}}']),'false');
  const cleanup=JSON.parse(readFileSync(join(root,'reports','responder','dispatch-auth-owner',state.project,'cleanup.json'),'utf8').replace(/^\uFEFF/,''));assert.equal(cleanup.cleanupPassed,true);writeFileSync(join(report,'owner-gates.json'),JSON.stringify({result:'PASS',manualEnrollment:true,departments:2,plaintextOnDisk:false,secretLogs:false,normalStop:true,unrelatedResourcePreserved:true,url:state.url},null,2));
 }catch(error){if(account||secret){if(phase==='normal-stop')writeFileSync(join(report,'normal-stop-diagnostic.txt'),run.logs().replaceAll(account.password,'[private]').replaceAll(secret||'[none]','[private]').replace(/eyJ[a-zA-Z0-9_.-]+/g,'[private]'));throw Error('Owner acceptance integration failed at '+phase+'; sensitive details suppressed')};throw error}
 finally{if(run.runtime()&&existsSync(join(run.runtime(),'ready.json')))ps('owner-stop.ps1',['-SessionPath',run.runtime()]);await finished(run);if(context)await context.close();if(browser)await browser.close();dock(['rm',control])}
});
console.log('Owner evidence directory: '+report);
