// Fixture commits live only in UUID-owned TEMP clones. No source-history rewrites or production requests.
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync,rmSync,copyFileSync,lstatSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname,join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID,createHash} from 'node:crypto';
const root=fileURLToPath(new URL('../../',import.meta.url));
const temp=join(tmpdir(),'dispatch-portability-'+randomUUID()),copy=join(temp,'checkout');
const ps=join(process.env.SystemRoot,'System32','WindowsPowerShell','v1.0','powershell.exe');
const env={...process.env,PSModulePath:join(process.env.SystemRoot,'System32','WindowsPowerShell','v1.0','Modules')};
const manifestPath='tools/dispatch-auth-local/source-integrity.json';
const manifest=JSON.parse(readFileSync(join(root,manifestPath),'utf8'));
const snapshot=manifest.milestoneASnapshot,milestoneStart='a8d746d0a9f5215e4fabdf9ef544a4b9a79ba72e',milestoneSubject='Complete Dispatch fullscreen and regional awareness foundation';
const files=[...new Set([...Object.keys(manifest.sources),...Object.keys(snapshot?.files||{}),manifestPath])];
function git(repo,args){const r=spawnSync('git',['-c','safe.directory='+repo.replaceAll('\\','/'),'-C',repo,...args],{encoding:'utf8',windowsHide:true});assert.equal(r.status,0,'Disposable Git operation failed: '+r.stderr);return r.stdout.trim()}
// read-tree replaces the index without preserving sparse skip-worktree flags.
// Reapply the existing cone after every fixture transition; real edits inside
// the cone remain visible to the unchanged verifier. TEMP fixture only.
function restoreFixtureIndex(revision){git(copy,['read-tree',revision]);git(copy,['sparse-checkout','reapply']);}
function verify(repo=copy,review=false){return spawnSync(ps,['-NoProfile','-NonInteractive','-File',join(repo,'tools/dispatch-auth-local/verify-sources.ps1'),'-Repository',repo,...(review?['-MilestoneAReview']:[])],{encoding:'utf8',windowsHide:true,env})}
function edit(name,fn){const path=join(copy,name),original=readFileSync(path);try{fn(path,original)}finally{writeFileSync(path,original)}}
const repairBase='4e08dd26dc7aebcb57f7be85ab7972bf0cfe0b48';
const registryPaths=['dispatch/roadway-registry.mjs','tools/dispatch-roadway-local/validate-registry.mjs','tools/dispatch-roadway-local/README.md','tests/dispatch-roadway-registry.test.mjs'];
const approvalPaths=[...registryPaths,'tools/dispatch-auth-local/portability.test.mjs',manifestPath,'tools/dispatch-auth-local/verify-sources.ps1'];
function fixtureCommit(paths,message){git(copy,['add','--sparse','--',...paths]);if(git(copy,['rev-parse','HEAD'])===repairBase){const r=verify();assert.equal(r.status,0,r.stderr)}return git(copy,['-c','user.name=Local synthetic certification','-c','user.email=synthetic@dispatch.invalid','commit','-m',message]);}
function committedEdit(paths,operation){const before=git(copy,['rev-parse','HEAD']),originals=paths.map(p=>[p,existsSync(join(copy,p))?readFileSync(join(copy,p)):null]);try{operation();fixtureCommit(paths,'Synthetic adversarial fixture');assert.notEqual(verify().status,0);}finally{const current=git(copy,['rev-parse','HEAD']);git(copy,['update-ref','refs/heads/'+manifest.branch,before,current]);restoreFixtureIndex(before);for(const [p,b]of originals){if(b===null)rmSync(join(copy,p),{force:true});else writeFileSync(join(copy,p),b);}}}
const repairPaths=['tools/dispatch-auth-local/portability.test.mjs',manifestPath,'tools/dispatch-auth-local/verify-sources.ps1'];
const announcement='LOCAL DISPATCH URL: http://127.0.0.1:4180/';
function diagnostics(output,stage){
 const raw=output.match(/OWNER START\/SESSION REFUSED: ([^\r\n]+)/)?.[1];
 const known=/^(UI unreachable|UI isolation drift|Non-loopback UI reachable|Owner runtime startup timed out|Owner runtime startup refused(?: at [a-zA-Z-]+)?|Owner runtime ended unexpectedly|Guarded startup failed; private logs are not printed)$/;
 return {stage,refusal:raw?(known.test(raw)?raw:'startup refusal details withheld'):null,cleanupPass:output.includes('CLEANUP PASS:')};
}
async function waitLauncherReady({readOutput,workerReady,exited,now=Date.now,pause=ms=>new Promise(r=>setTimeout(r,ms)),timeoutMs=200000}){
 const start=now();let workerReadyMs=null;
 while(now()-start<timeoutMs){
  const output=readOutput(),ready=workerReady();if(ready&&workerReadyMs===null)workerReadyMs=now()-start;
  const stage=workerReadyMs===null?'waiting-worker':'waiting-launcher';
  if(output.includes('OWNER START/SESSION REFUSED:')||exited()){const error=Error('Owner launcher startup refused');error.diagnostic=diagnostics(output,stage);throw error}
  if(ready&&(output.includes(announcement+'\r\n')||output.includes(announcement+'\n')))return {stage:'launcher-ready',workerReadyMs,launcherReadyMs:now()-start};
  await pause(200);
 }
 const error=Error('Owner launcher readiness timeout');error.diagnostic=diagnostics(readOutput(),workerReadyMs===null?'waiting-worker':'waiting-launcher');throw error;
}
function requestOwnedStop(runtime,{ready,failed}){
 if(!runtime||!existsSync(runtime))return false;
 assert.equal(dirname(runtime),tmpdir(),'Owned runtime root required');assert.match(runtime.split(/[\\/]/).at(-1),/^gridly-dispatch-auth-[a-f0-9]{12}$/);assert.ok(!lstatSync(runtime).isSymbolicLink(),'Runtime reparse refused');
 assert.ok(ready||failed,'Normal stop withheld until launcher readiness');writeFileSync(join(runtime,'stop.request'),'');return true;
}
function awaitExit(done,timeoutMs=240000){let timer;return Promise.race([done,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Owner cleanup deadline exceeded')),timeoutMs);timer.unref()})]).finally(()=>clearTimeout(timer))}
if(manifest.basemapSnapshot){
 mkdirSync(temp);try{
  assert.equal(spawnSync('git',['-c','safe.directory='+root.replaceAll('\\','/'),'clone','--shared','--no-checkout','--branch',manifest.branch,root,copy],{encoding:'utf8'}).status,0);
  git(copy,['sparse-checkout','init','--cone']);git(copy,['sparse-checkout','set','dispatch','tools/dispatch-auth-local','tools/dispatch-ui','tools/responder/phase29/installer','tests']);git(copy,['checkout',manifest.branch]);
  const basemapStart='740a1a225ddeb18656a348d5878ff2c45693a775',basemapSubject='Establish continuous Dispatch basemap foundation',startingHead=git(copy,['rev-parse','HEAD']),paths=[...manifest.basemapSnapshot.inventory];
  const reviewed=(repo=copy)=>spawnSync(ps,['-NoProfile','-NonInteractive','-File',join(repo,'tools/dispatch-auth-local/verify-sources.ps1'),'-Repository',repo,'-BasemapReview'],{encoding:'utf8',windowsHide:true,env});
  if(startingHead===basemapStart){for(const name of paths){mkdirSync(dirname(join(copy,name)),{recursive:true});copyFileSync(join(root,name),join(copy,name));}const r=reviewed();assert.equal(r.status,0,r.stderr);assert.notEqual(verify().status,0);fixtureCommit(paths,basemapSubject);}
  const head=git(copy,['rev-parse','HEAD']);assert.equal(verify().status,0);
  function pendingReview(fn){const current=git(copy,['rev-parse','HEAD']);git(copy,['update-ref','refs/heads/'+manifest.branch,basemapStart,current]);restoreFixtureIndex(basemapStart);try{return fn();}finally{git(copy,['update-ref','refs/heads/'+manifest.branch,current,basemapStart]);restoreFixtureIndex(current);}}
  function pendingTest(name,fn){return test(name,()=>pendingReview(fn));}
  await pendingTest('exact eleven-file pending basemap review accepted',()=>{const r=reviewed();assert.equal(r.status,0,r.stderr)});
  await pendingTest('ordinary launcher refuses uncommitted basemap candidate',()=>assert.notEqual(verify().status,0));
  await pendingTest('old milestone flag cannot authorize new basemap candidate',()=>assert.notEqual(verify(copy,true).status,0));
  await pendingTest('every reviewed source mutation rejected',()=>{for(const name of paths.filter(p=>p!==manifestPath))edit(name,(p,b)=>{writeFileSync(p,Buffer.concat([b,Buffer.from('\n// unauthorized\n')]));assert.notEqual(reviewed().status,0,name);});});
  await pendingTest('every original security protection retained',()=>{for(const name of Object.keys(manifest.sources).filter(p=>!paths.includes(p)))edit(name,(p,b)=>{writeFileSync(p,Buffer.concat([b,Buffer.from('\n# unauthorized\n')]));assert.notEqual(reviewed().status,0,name);});});
  await pendingTest('missing and substituted manifests rejected',()=>edit(manifestPath,(p,b)=>{rmSync(p);assert.notEqual(reviewed().status,0);const m=structuredClone(manifest);m.basemapSnapshot.files['dispatch/basemap.mjs']='0'.repeat(64);writeFileSync(p,JSON.stringify(m));assert.notEqual(reviewed().status,0);}));
  await pendingTest('original manifest contracts cannot be changed',()=>edit(manifestPath,p=>{for(const change of [m=>m.sources['tools/dispatch-auth-local/session.mjs']='0'.repeat(64),m=>m.milestoneASnapshot.commitSubject='unauthorized']){const m=structuredClone(manifest);change(m);writeFileSync(p,JSON.stringify(m));assert.notEqual(reviewed().status,0);}}));
  await pendingTest('unapproved file addition and unrelated tracked changes rejected',()=>{const p=join(copy,'dispatch/extra.mjs');try{writeFileSync(p,'// unapproved');assert.notEqual(reviewed().status,0);}finally{rmSync(p);}edit('dispatch/components.mjs',(p,b)=>{writeFileSync(p,Buffer.concat([b,Buffer.from('\n// changed\n')]));assert.notEqual(reviewed().status,0);});});
  await pendingTest('staged index changes rejected and sparse restoration retained',()=>{try{git(copy,['add','--','dispatch/basemap.mjs']);assert.notEqual(reviewed().status,0);}finally{restoreFixtureIndex('HEAD');}assert.equal(reviewed().status,0);});
  await pendingTest('wrong branch rejected',()=>{git(copy,['checkout','-b','unreviewed-basemap']);try{assert.notEqual(reviewed().status,0);}finally{git(copy,['checkout',manifest.branch]);}});
  await pendingTest('unexpected starting revision rejected',()=>{const head=git(copy,['rev-parse','HEAD']),previous=git(copy,['rev-parse','HEAD^']);git(copy,['update-ref','refs/heads/'+manifest.branch,previous,head]);try{assert.notEqual(reviewed().status,0);}finally{git(copy,['update-ref','refs/heads/'+manifest.branch,head,previous]);}});
  await pendingTest('non-root and unrelated repository rejected',()=>{assert.notEqual(reviewed(join(copy,'dispatch')).status,0);const p=join(temp,'unrelated');mkdirSync(p);git(p,['init']);for(const name of [...new Set([...paths,...Object.keys(manifest.sources)])]){mkdirSync(dirname(join(p,name)),{recursive:true});copyFileSync(join(root,name),join(p,name));}assert.notEqual(reviewed(p).status,0);});
  await pendingTest('CRLF review conversion accepted without changed content',()=>edit('tools/dispatch-auth-local/verify-sources.ps1',(p,b)=>{writeFileSync(p,b.toString().replaceAll('\r\n','\n').replaceAll('\n','\r\n'));const r=reviewed();assert.equal(r.status,0,r.stderr)}));

  await test('exact reviewed direct-child basemap snapshot accepts ordinary startup',()=>{assert.equal(git(copy,['rev-parse','HEAD^']),basemapStart);assert.equal(git(copy,['show','-s','--format=%B']),basemapSubject);assert.deepEqual(git(copy,['diff-tree','--no-commit-id','--name-only','--no-renames','-r','HEAD']).split('\n').sort(),[...paths].sort());assert.equal(verify().status,0);});
  await test('committed basemap cannot use either review flag',()=>{assert.notEqual(reviewed().status,0);assert.notEqual(verify(copy,true).status,0);});
  function revisionCheck({parents=[basemapStart],subject=basemapSubject,tree=git(copy,['rev-parse','HEAD^{tree}'])}={}){const before=git(copy,['rev-parse','HEAD']),revision=git(copy,['-c','user.name=Local synthetic certification','-c','user.email=synthetic@dispatch.invalid','commit-tree',tree,...parents.flatMap(p=>['-p',p]),'-m',subject]);git(copy,['update-ref','refs/heads/'+manifest.branch,revision,before]);restoreFixtureIndex(revision);try{assert.notEqual(verify().status,0);}finally{git(copy,['update-ref','refs/heads/'+manifest.branch,before,revision]);restoreFixtureIndex(before);}}
  await test('wrong basemap commit subject rejected',()=>revisionCheck({subject:'Unauthorized basemap snapshot'}));
  await test('wrong basemap direct parent rejected',()=>revisionCheck({parents:[git(copy,['rev-parse',basemapStart+'^'])]}));
  await test('basemap merge and unrelated descendant rejected',()=>{revisionCheck({parents:[basemapStart,git(copy,['rev-parse',basemapStart+'^'])]});revisionCheck({parents:[git(copy,['rev-parse','HEAD'])]});});
  await test('committed basemap extra file inventory rejected',()=>{const p='dispatch/unapproved.mjs';try{writeFileSync(join(copy,p),'// unapproved');git(copy,['add','--',p]);revisionCheck({tree:git(copy,['write-tree'])});}finally{restoreFixtureIndex('HEAD');rmSync(join(copy,p),{force:true});}});
  await test('committed basemap missing addition rejected',()=>{try{git(copy,['rm','--cached','--','dispatch/basemap-provider.mjs']);revisionCheck({tree:git(copy,['write-tree'])});}finally{restoreFixtureIndex('HEAD');}});
  await test('committed basemap executable source mode rejected',()=>{try{git(copy,['update-index','--chmod=+x','--','dispatch/basemap.mjs']);revisionCheck({tree:git(copy,['write-tree'])});}finally{restoreFixtureIndex('HEAD');}});
  await test('committed basemap dirty index rejected',()=>edit('dispatch/basemap.mjs',(p,b)=>{try{writeFileSync(p,b.toString()+'\n// unreviewed\n');git(copy,['add','--',p]);assert.notEqual(verify().status,0);}finally{restoreFixtureIndex('HEAD');}}));
  await test('every committed basemap dirty reviewed source rejected',()=>{for(const name of paths)edit(name,(p,b)=>{writeFileSync(p,Buffer.concat([b,Buffer.from('\n// unauthorized\n')]));assert.notEqual(verify().status,0,name);});});
  await test('equivalent manifest substitution remains dirty and rejected',()=>edit(manifestPath,(p,b)=>{writeFileSync(p,b.toString()+'\n');assert.notEqual(verify().status,0);}));
  await test('committed untracked file and Auth addition rejected',()=>{for(const name of ['dispatch/unreviewed.mjs','tools/dispatch-auth-local/unreviewed.mjs']){const p=join(copy,name);try{writeFileSync(p,'// unreviewed');assert.notEqual(verify().status,0);}finally{rmSync(p);}}});
  await test('snapshot parent subject and inventory substitution rejected',()=>edit(manifestPath,p=>{for(const mutate of [m=>m.basemapSnapshot.startingHead='0'.repeat(40),m=>m.basemapSnapshot.commitSubject='unauthorized',m=>m.basemapSnapshot.inventory.pop()]){const m=structuredClone(manifest);mutate(m);writeFileSync(p,JSON.stringify(m));assert.notEqual(verify().status,0);}}));
  await test('committed CRLF verifier retains canonical content and clean Git interpretation',()=>edit('tools/dispatch-auth-local/verify-sources.ps1',(p,b)=>{writeFileSync(p,b.toString().replaceAll('\r\n','\n').replaceAll('\n','\r\n'));const r=verify();assert.equal(r.status,0,r.stderr);}));
  await test('worker listener readiness still does not permit premature shutdown',async()=>{let tick=0;const r=await waitLauncherReady({readOutput:()=>tick<2?'':announcement+'\n',workerReady:()=>true,exited:()=>false,now:()=>tick*200,pause:async()=>{tick++;}});assert.equal(r.launcherReadyMs,400);});
  await test('launcher readiness timeout and genuine failure remain bounded and sanitized',async()=>{let tick=0;await assert.rejects(waitLauncherReady({readOutput:()=>'',workerReady:()=>true,exited:()=>false,now:()=>tick,pause:async()=>{tick+=200},timeoutMs:600}),e=>e.diagnostic.stage==='waiting-launcher');await assert.rejects(waitLauncherReady({readOutput:()=>'OWNER START/SESSION REFUSED: UI unreachable\n',workerReady:()=>false,exited:()=>true}),e=>!!e.diagnostic);});
 if(process.env.DISPATCH_PORTABILITY_OWNER_SMOKE==='1')await test('committed evidence-free checkout starts genuine local login and cleans up',{timeout:600000},async()=>{
  assert.notEqual(head,manifest.baseRevision,'Postcommit verification required');
  const owner=join(copy,'tools/dispatch-auth-local/owner.ps1'),docker=process.env.DISPATCH_SMOKE_DOCKER,supabase=process.env.DISPATCH_SMOKE_SUPABASE;assert.ok(docker&&supabase);
  const child=spawn(ps,['-NoProfile','-NonInteractive','-File',owner,'-Supabase',supabase,'-Docker',docker,'-Certification'],{cwd:copy,env,windowsHide:true,stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);const done=new Promise(resolve=>child.once('close',resolve));let runtime,failure;
  const record={sourceRevision:head,sourceOverlay:false,precommitCandidate:startingHead===basemapStart,ready:false};
  try{
   record.readiness=await waitLauncherReady({readOutput:()=>output,workerReady:()=>{runtime=output.match(/OWNER SESSION: ([^\r\n]+)/)?.[1];return !!runtime&&existsSync(join(runtime,'ready.json'))},exited:()=>child.exitCode!==null});record.ready=true;
   const ready=JSON.parse(readFileSync(join(runtime,'ready.json')));assert.equal(ready.url,'http://127.0.0.1:4180/');assert.equal(ready.units.length,2);assert.equal(ready.catalogUnchanged,true);
   const response=await fetch(ready.url);record.loginHttpStatus=response.status;assert.equal(response.status,200);assert.match(await response.text(),/Gridly/i);const denied=await fetch(ready.url+'api/context',{headers:{'X-Gridly-Dispatch':'local-auth'}});record.anonymousContextStatus=denied.status;assert.equal(denied.status,401);
  }catch(error){failure=error;record.failure=error.diagnostic||diagnostics(output,record.ready?'http-checks':'waiting-readiness')}
  finally{
   try{record.stopRequested=requestOwnedStop(runtime,{ready:record.ready,failed:!!failure});record.stopAfterAnnouncement=output.includes(announcement+'\r\n')||output.includes(announcement+'\n');record.exitCode=await awaitExit(done);record.cleanup=diagnostics(output,'shutdown');record.runtimeRemoved=!runtime||!existsSync(runtime);if(record.exitCode!==0||!record.cleanup.cleanupPass||!record.runtimeRemoved){failure ||= Error('Owner shutdown verification failed')}}catch(error){failure ||= error;record.cleanupFailure={stage:'shutdown',category:'cleanup verification failed'}}
   const evidence=join(root,'reports/responder/dispatch-auth-owner');mkdirSync(evidence,{recursive:true});writeFileSync(join(evidence,'portability-smoke-'+randomUUID()+'.json'),JSON.stringify(record,null,2));
  }
  if(failure)throw Error('Owner smoke failed: '+JSON.stringify(record));
  assert.equal(record.stopAfterAnnouncement,true);assert.equal(record.exitCode,0);
 });
 }finally{assert.equal(dirname(temp),tmpdir());rmSync(temp,{recursive:true,force:true});}
}else{
mkdirSync(temp);
try{
 const cloned=spawnSync('git',['-c','safe.directory='+root.replaceAll('\\','/'),'clone','--shared','--no-checkout','--branch',manifest.branch,root,copy],{encoding:'utf8',windowsHide:true});assert.equal(cloned.status,0,'Local clone failed');
 git(copy,['sparse-checkout','init','--cone']);git(copy,['sparse-checkout','set','dispatch','tools/dispatch-auth-local','tools/dispatch-ui','tools/responder/phase29/installer','tests']);git(copy,['checkout',manifest.branch]);
 // Precommit: create a clean reviewed candidate only in the disposable clone.
 // Postcommit: use committed source alone, with no overlays.
 const startingHead=git(copy,['rev-parse','HEAD']);
 if(startingHead===repairBase){for(const name of approvalPaths){const target=join(copy,name);mkdirSync(dirname(target),{recursive:true});copyFileSync(join(root,name),target)}fixtureCommit(approvalPaths,'Synthetic reviewed seven-file candidate');}
 if(snapshot&&startingHead===milestoneStart){for(const name of snapshot.inventory){const target=join(copy,name);mkdirSync(dirname(target),{recursive:true});copyFileSync(join(root,name),target)}const pending=verify(copy,true);assert.equal(pending.status,0,pending.stderr);assert.notEqual(verify().status,0);fixtureCommit(snapshot.inventory,milestoneSubject);}
 const head=git(copy,['rev-parse','HEAD']);
 await test('certified development or closure checkout passes provenance and all source hashes',()=>{const r=verify(root,!!snapshot&&git(root,['rev-parse','HEAD'])===milestoneStart);assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/SOURCE INTEGRITY PASS/)});
 await test('fresh local source copy works without generated certification evidence',()=>{assert.ok(!existsSync(join(copy,'reports/responder/dispatch-auth-local')));assert.ok(!existsSync(join(copy,'reports/responder/dispatch-auth-owner')));const r=verify();assert.equal(r.status,0,r.stderr);assert.equal(git(copy,['status','--porcelain']), '')});
 await test('every security-critical source alteration fails closed',()=>{for(const name of Object.keys(manifest.sources))edit(name,(path,original)=>{writeFileSync(path,Buffer.concat([original,Buffer.from('\n# altered source\n')]));assert.notEqual(verify().status,0,'Altered source accepted: '+name)})});
 await test('missing reviewed manifest fails closed',()=>edit(manifestPath,path=>{rmSync(path);assert.notEqual(verify().status,0)}));
 await test('missing security-critical adapter fails closed',()=>edit('tools/dispatch-auth-local/session.mjs',path=>{rmSync(path);assert.notEqual(verify().status,0)}));
 await test('manifest cannot omit coverage, add traversal, or substitute base provenance',()=>{for(const change of [m=>delete m.sources['tools/dispatch-auth-local/session.mjs'],m=>m.sources['../escape']='0'.repeat(64),m=>m.baseRevision='0'.repeat(40)])edit(manifestPath,path=>{const m=structuredClone(manifest);change(m);writeFileSync(path,JSON.stringify(m));assert.notEqual(verify().status,0)})});
 await test('unrelated branch fails closed',()=>{git(copy,['checkout','-b','unrelated-portability-test']);try{assert.notEqual(verify().status,0)}finally{git(copy,['checkout',manifest.branch])}});
 await test('incompatible existing Git revision fails closed without creating a test commit',()=>{const previous=git(copy,['rev-parse',manifest.baseRevision+'^']);git(copy,['update-ref','refs/heads/'+manifest.branch,previous,head]);try{assert.notEqual(verify().status,0)}finally{git(copy,['update-ref','refs/heads/'+manifest.branch,head,previous])}});
 await test('unrelated repository cannot borrow the reviewed source set',()=>{const unrelated=join(temp,'unrelated');mkdirSync(unrelated);git(unrelated,['init']);for(const name of files){const target=join(unrelated,name);mkdirSync(dirname(target),{recursive:true});copyFileSync(join(root,name),target)}assert.notEqual(verify(unrelated).status,0)});
 await test('canonical text hashes support LF and Windows CRLF checkout conversion',()=>edit('tools/dispatch-auth-local/session.mjs',(path,original)=>{writeFileSync(path,original.toString().replaceAll('\r\n','\n').replaceAll('\n','\r\n'));const r=verify();assert.equal(r.status,0,r.stderr)}));
 await test('startup no longer depends on generated reports or a fixed current HEAD',()=>{const owner=readFileSync(join(copy,'tools/dispatch-auth-local/owner.ps1'),'utf8');assert.ok(owner.includes("'verify-sources.ps1'"));assert.ok(!owner.includes('certified-sources.json'));assert.ok(!owner.includes('4f685022e26a07297339750ae67219526384eef2'));assert.equal(manifest.format,'dispatch-local-auth-sha256-lf-v2')});
 await test('worker listener readiness does not complete launcher readiness',async()=>{let tick=0;const result=await waitLauncherReady({readOutput:()=>tick<2?'':announcement+'\n',workerReady:()=>true,exited:()=>false,now:()=>tick*200,pause:async()=>{tick++}});assert.equal(result.workerReadyMs,0);assert.equal(result.launcherReadyMs,400)});
 await test('normal stop is withheld until the complete readiness announcement',async()=>{let tick=0,completed=false;const result=await waitLauncherReady({readOutput:()=>tick===0?announcement:announcement+'\n',workerReady:()=>true,exited:()=>false,now:()=>tick*200,pause:async()=>{assert.equal(completed,false);tick++}});completed=result.stage==='launcher-ready';assert.equal(tick,1);assert.equal(completed,true)});
 await test('readiness timeout is bounded and retains only sanitized stage',async()=>{let tick=0;await assert.rejects(waitLauncherReady({readOutput:()=>'',workerReady:()=>true,exited:()=>false,now:()=>tick,pause:async()=>{tick+=200},timeoutMs:600}),error=>error.message==='Owner launcher readiness timeout'&&error.diagnostic.stage==='waiting-launcher');assert.equal(tick,600)});
 await test('genuine startup refusal preserves safe category without arbitrary details',async()=>{await assert.rejects(waitLauncherReady({readOutput:()=> 'OWNER START/SESSION REFUSED: UI unreachable\n',workerReady:()=>true,exited:()=>false}),error=>error.diagnostic.refusal==='UI unreachable');const safe=diagnostics('OWNER START/SESSION REFUSED: DO_NOT_RECORD_FAKE_VALUE\n','waiting-launcher');assert.ok(!JSON.stringify(safe).includes('DO_NOT_RECORD_FAKE_VALUE'));assert.equal(safe.refusal,'startup refusal details withheld')});
 await test('failed readiness permits exact owned cleanup but premature normal stop is refused',()=>{const runtime=join(tmpdir(),'gridly-dispatch-auth-'+randomUUID().replaceAll('-','').slice(0,12));mkdirSync(runtime);try{assert.throws(()=>requestOwnedStop(runtime,{ready:false,failed:false}),/withheld/);assert.ok(!existsSync(join(runtime,'stop.request')));assert.equal(requestOwnedStop(runtime,{ready:false,failed:true}),true)}finally{assert.equal(dirname(runtime),tmpdir());rmSync(runtime,{recursive:true,force:true})}});
 await test('unrelated roadway commit cannot borrow exact snapshot approval; legacy policy remains bounded',()=>{const name='dispatch/roadway-only-certification-fixture.mjs',before=git(copy,['rev-parse','HEAD']);try{writeFileSync(join(copy,name),'// Synthetic independent roadmap artifact; no imports or privileges.\n');fixtureCommit([name],'Synthetic independently certified roadway-only commit');const r=verify();if(snapshot)assert.notEqual(r.status,0);else assert.equal(r.status,0,r.stderr);}finally{const current=git(copy,['rev-parse','HEAD']);git(copy,['update-ref','refs/heads/'+manifest.branch,before,current]);restoreFixtureIndex(before);rmSync(join(copy,name),{force:true});}});
 await test('committed Auth alteration and forged manifest hash are refused',()=>committedEdit(['tools/dispatch-auth-local/session.mjs',manifestPath],()=>{const name='tools/dispatch-auth-local/session.mjs',body=readFileSync(join(copy,name),'utf8')+'\n// unreviewed\n';writeFileSync(join(copy,name),body);const m=JSON.parse(readFileSync(join(copy,manifestPath)));m.sources[name]=createHash('sha256').update(body.replaceAll('\r\n','\n')).digest('hex');writeFileSync(join(copy,manifestPath),JSON.stringify(m,null,2)+'\n');}));
 await test('committed guard changes are refused',()=>committedEdit(['tools/dispatch-auth-local/docker-guard.cs'],()=>{const p=join(copy,'tools/dispatch-auth-local/docker-guard.cs');writeFileSync(p,readFileSync(p,'utf8')+'\n// unreviewed\n');}));
 await test('verifier self-hash substitution cannot replace the reviewed Git manifest',()=>committedEdit(['tools/dispatch-auth-local/verify-sources.ps1',manifestPath],()=>{const name='tools/dispatch-auth-local/verify-sources.ps1',body=readFileSync(join(copy,name),'utf8')+'\n# unreviewed verifier\n';writeFileSync(join(copy,name),body);const m=JSON.parse(readFileSync(join(copy,manifestPath)));m.sources[name]=createHash('sha256').update(body.replaceAll('\r\n','\n')).digest('hex');writeFileSync(join(copy,manifestPath),JSON.stringify(m,null,2)+'\n');}));
 await test('new tracked or untracked Auth additions are never silently trusted',()=>{const name='tools/dispatch-auth-local/unreviewed-security-addon.mjs',p=join(copy,name);writeFileSync(p,'// synthetic unreviewed addition\n');try{assert.notEqual(verify().status,0);}finally{rmSync(p);}committedEdit([name],()=>writeFileSync(p,'// synthetic unreviewed addition\n'));});
 await test('untracked protected replacement is refused',()=>{const name='tools/dispatch-auth-local/session.mjs';git(copy,['rm','--cached','--',name]);try{assert.notEqual(verify().status,0);}finally{restoreFixtureIndex('HEAD');}});

 if(manifest.milestoneASnapshot){
  git(copy,['sparse-checkout','reapply']);assert.equal(git(copy,['status','--porcelain']), '', 'Committed fixture must be clean');
  const paths=[...manifest.milestoneASnapshot.inventory];
  function pendingReview(fn){const committed=git(copy,['rev-parse','HEAD']);git(copy,['update-ref','refs/heads/'+manifest.branch,milestoneStart,committed]);restoreFixtureIndex(milestoneStart);try{assert.equal(git(copy,['diff','--cached','--name-only','HEAD']),'');const changed=[...git(copy,['diff','--name-only','HEAD']).split('\n'),...git(copy,['ls-files','--others','--exclude-standard']).split('\n')].filter(Boolean).sort();assert.deepEqual(changed,[...paths].sort(),'Pending fixture must contain exactly the twelve reviewed changes');return fn()}finally{git(copy,['update-ref','refs/heads/'+manifest.branch,committed,milestoneStart]);restoreFixtureIndex(committed);}}
  function revisionCheck({parents=[milestoneStart],subject=milestoneSubject,tree=git(copy,['rev-parse','HEAD^{tree}'])}={}){const current=git(copy,['rev-parse','HEAD']);const revision=git(copy,['-c','user.name=Local synthetic certification','-c','user.email=synthetic@dispatch.invalid','commit-tree',tree,...parents.flatMap(p=>['-p',p]),'-m',subject]);try{git(copy,['update-ref','refs/heads/'+manifest.branch,revision,current]);restoreFixtureIndex(revision);assert.notEqual(verify().status,0,'Unreviewed fixture revision accepted');}finally{git(copy,['update-ref','refs/heads/'+manifest.branch,current,revision]);restoreFixtureIndex(current);}}
  await test('fixture index restoration preserves sparse flags and real dirty-source evidence',()=>{const revision=git(copy,['rev-parse','HEAD']),skipped=()=>git(copy,['ls-files','-t']).split('\n').filter(s=>s.startsWith('S '));const expected=skipped();assert.ok(expected.length>0);restoreFixtureIndex(revision);assert.deepEqual(skipped(),expected);assert.equal(git(copy,['status','--porcelain']),'');edit('dispatch/basemap.mjs',(p,b)=>{writeFileSync(p,b.toString()+'\n// intentional fixture edit\n');restoreFixtureIndex(revision);assert.ok(git(copy,['diff','--name-only']).split('\n').includes('dispatch/basemap.mjs'));assert.notEqual(verify().status,0);});restoreFixtureIndex(revision);const addition='dispatch/intentional-restoration-fixture.mjs';try{writeFileSync(join(copy,addition),'// intentional untracked fixture\n');restoreFixtureIndex(revision);assert.ok(git(copy,['ls-files','--others','--exclude-standard']).split('\n').includes(addition));assert.notEqual(verify().status,0);}finally{rmSync(join(copy,addition),{force:true});restoreFixtureIndex(revision);}assert.equal(git(copy,['status','--porcelain']),'');});
  await test('exact pending review passes while ordinary startup refuses the uncommitted candidate',()=>pendingReview(()=>{const r=verify(copy,true);assert.equal(r.status,0,r.stderr);assert.notEqual(verify().status,0);}));
  await test('every reviewed presentation and verifier mutation is rejected during review',()=>pendingReview(()=>{for(const name of paths.filter(p=>p!==manifestPath))edit(name,(p,b)=>{writeFileSync(p,Buffer.concat([b,Buffer.from('\n// changed\n')]));assert.notEqual(verify(copy,true).status,0,name);});}));
  await test('review cannot substitute approved hashes or original security hashes',()=>pendingReview(()=>{for(const change of [m=>m.milestoneASnapshot.files['dispatch/map.css']='0'.repeat(64),m=>m.sources['tools/dispatch-auth-local/session.mjs']='0'.repeat(64),m=>m.milestoneASnapshot.verifierCanonicalHash='0'.repeat(64)])edit(manifestPath,p=>{const m=structuredClone(manifest);change(m);writeFileSync(p,JSON.stringify(m));assert.notEqual(verify(copy,true).status,0);});}));
  await test('review rejects unexpected tracked and untracked source changes',()=>pendingReview(()=>{edit('dispatch/basemap.mjs',(p,b)=>{writeFileSync(p,Buffer.concat([b,Buffer.from('\n// changed\n')]));assert.notEqual(verify(copy,true).status,0);});const p=join(copy,'dispatch/unapproved.mjs');try{writeFileSync(p,'// unapproved');assert.notEqual(verify(copy,true).status,0);}finally{rmSync(p);}}));
  await test('review rejects changed Auth and Docker guard',()=>pendingReview(()=>{for(const name of ['tools/dispatch-auth-local/session.mjs','tools/dispatch-auth-local/docker-guard.cs'])edit(name,(p,b)=>{writeFileSync(p,Buffer.concat([b,Buffer.from('\n// changed\n')]));assert.notEqual(verify(copy,true).status,0);});}));
  await test('review rejects missing manifest and every milestone source',()=>pendingReview(()=>{for(const name of paths)edit(name,p=>{rmSync(p);assert.notEqual(verify(copy,true).status,0,name);});}));
  await test('review rejects a non-root repository argument',()=>pendingReview(()=>assert.notEqual(verify(join(copy,'dispatch'),true).status,0)));
  await test('review canonical verifier supports CRLF without accepting changed bytes',()=>pendingReview(()=>edit('tools/dispatch-auth-local/verify-sources.ps1',(p,b)=>{writeFileSync(p,b.toString().replaceAll('\r\n','\n').replaceAll('\n','\r\n'));const r=verify(copy,true);assert.equal(r.status,0,r.stderr);})));
  await test('review rejects wrong branch and exact starting revision',()=>pendingReview(()=>{git(copy,['checkout','-b','unapproved-review']);try{assert.notEqual(verify(copy,true).status,0);}finally{git(copy,['checkout',manifest.branch]);}const previous=git(copy,['rev-parse',milestoneStart+'^']);git(copy,['update-ref','refs/heads/'+manifest.branch,previous,milestoneStart]);try{assert.notEqual(verify(copy,true).status,0);}finally{git(copy,['update-ref','refs/heads/'+manifest.branch,milestoneStart,previous]);}}));
  await test('exact parent, subject, twelve-file inventory and committed bytes accept ordinary startup',()=>{assert.equal(git(copy,['rev-parse','HEAD^']),milestoneStart);assert.equal(git(copy,['log','-1','--format=%s']),milestoneSubject);assert.deepEqual(git(copy,['diff-tree','--no-commit-id','--name-only','--no-renames','-r',milestoneStart,'HEAD']).split('\n').sort(),paths.sort());const r=verify();assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/exact committed milestone snapshot/);});
  await test('committed snapshot cannot use the pending-review bypass',()=>assert.notEqual(verify(copy,true).status,0));
  await test('same candidate tree with wrong subject is rejected',()=>revisionCheck({subject:'Unapproved milestone subject'}));
  await test('same candidate tree with wrong direct parent is rejected',()=>revisionCheck({parents:[git(copy,['rev-parse',milestoneStart+'^'])]}));
  await test('merge-parent ambiguity is rejected',()=>revisionCheck({parents:[milestoneStart,git(copy,['rev-parse',milestoneStart+'^'])]}));
  await test('an empty unrelated descendant cannot borrow snapshot approval',()=>revisionCheck({parents:[git(copy,['rev-parse','HEAD'])]}));
  await test('correct parent and subject cannot add an unreviewed changed file',()=>{const p='dispatch/unapproved-inventory-fixture.mjs';try{writeFileSync(join(copy,p),'// isolated adversarial fixture\n');git(copy,['add','--sparse','--',p]);const tree=git(copy,['write-tree']);revisionCheck({tree});}finally{restoreFixtureIndex('HEAD');rmSync(join(copy,p),{force:true});}});
  await test('correct parent and subject cannot omit an approved addition',()=>{try{git(copy,['rm','--cached','--','dispatch/awareness-perspective.mjs']);const tree=git(copy,['write-tree']);revisionCheck({tree});}finally{restoreFixtureIndex('HEAD');}});
  await test('committed snapshot rejects every dirty reviewed source without reapproving hashes',()=>{for(const name of paths.filter(p=>p!==manifestPath))edit(name,(p,b)=>{writeFileSync(p,Buffer.concat([b,Buffer.from('\n// unreviewed\n')]));assert.notEqual(verify().status,0,name);});});
  await test('semantically unchanged manifest substitution is still dirty and rejected',()=>edit(manifestPath,(p,b)=>{writeFileSync(p,b.toString()+'\n');assert.notEqual(verify().status,0);}));
  await test('committed snapshot rejects untracked additions outside Auth',()=>{const p=join(copy,'dispatch/unapproved-presentation.mjs');try{writeFileSync(p,'// unreviewed');assert.notEqual(verify().status,0);}finally{rmSync(p);}});
  await test('reviewed source hashes cannot authorize executable file-mode changes',()=>{try{git(copy,['update-index','--chmod=+x','--','dispatch/app.mjs']);const tree=git(copy,['write-tree']);revisionCheck({tree});}finally{restoreFixtureIndex('HEAD');}});
  await test('committed snapshot rejects staged unreviewed content',()=>edit('dispatch/app.mjs',(p,b)=>{try{writeFileSync(p,b.toString()+'\n// unreviewed\n');git(copy,['add','--','dispatch/app.mjs']);assert.notEqual(verify().status,0);}finally{restoreFixtureIndex('HEAD');}}));
  await test('snapshot inventory, subject and parent fields cannot be substituted',()=>{for(const change of [m=>m.milestoneASnapshot.inventory.pop(),m=>m.milestoneASnapshot.commitSubject='Unapproved subject',m=>m.milestoneASnapshot.startingHead='0'.repeat(40)])edit(manifestPath,p=>{const m=structuredClone(manifest);change(m);writeFileSync(p,JSON.stringify(m));assert.notEqual(verify().status,0);});});
 }

 if(process.env.DISPATCH_PORTABILITY_OWNER_SMOKE==='1')await test('committed evidence-free checkout starts genuine local login and cleans up',{timeout:600000},async()=>{
  assert.notEqual(head,manifest.baseRevision,'Postcommit verification required');
  const owner=join(copy,'tools/dispatch-auth-local/owner.ps1'),docker=process.env.DISPATCH_SMOKE_DOCKER,supabase=process.env.DISPATCH_SMOKE_SUPABASE;assert.ok(docker&&supabase);
  const child=spawn(ps,['-NoProfile','-NonInteractive','-File',owner,'-Supabase',supabase,'-Docker',docker,'-Certification'],{cwd:copy,env,windowsHide:true,stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);const done=new Promise(resolve=>child.once('close',resolve));let runtime,failure;
  const record={sourceRevision:head,sourceOverlay:false,precommitCandidate:startingHead===repairBase||!!snapshot&&startingHead===milestoneStart,ready:false};
  try{
   record.readiness=await waitLauncherReady({readOutput:()=>output,workerReady:()=>{runtime=output.match(/OWNER SESSION: ([^\r\n]+)/)?.[1];return !!runtime&&existsSync(join(runtime,'ready.json'))},exited:()=>child.exitCode!==null});record.ready=true;
   const ready=JSON.parse(readFileSync(join(runtime,'ready.json')));assert.equal(ready.url,'http://127.0.0.1:4180/');assert.equal(ready.units.length,2);assert.equal(ready.catalogUnchanged,true);
   const response=await fetch(ready.url);record.loginHttpStatus=response.status;assert.equal(response.status,200);assert.match(await response.text(),/Gridly/i);const denied=await fetch(ready.url+'api/context',{headers:{'X-Gridly-Dispatch':'local-auth'}});record.anonymousContextStatus=denied.status;assert.equal(denied.status,401);
  }catch(error){failure=error;record.failure=error.diagnostic||diagnostics(output,record.ready?'http-checks':'waiting-readiness')}
  finally{
   try{record.stopRequested=requestOwnedStop(runtime,{ready:record.ready,failed:!!failure});record.stopAfterAnnouncement=output.includes(announcement+'\r\n')||output.includes(announcement+'\n');record.exitCode=await awaitExit(done);record.cleanup=diagnostics(output,'shutdown');record.runtimeRemoved=!runtime||!existsSync(runtime);if(record.exitCode!==0||!record.cleanup.cleanupPass||!record.runtimeRemoved){failure ||= Error('Owner shutdown verification failed')}}catch(error){failure ||= error;record.cleanupFailure={stage:'shutdown',category:'cleanup verification failed'}}
   const evidence=join(root,'reports/responder/dispatch-auth-owner');mkdirSync(evidence,{recursive:true});writeFileSync(join(evidence,'portability-smoke-'+randomUUID()+'.json'),JSON.stringify(record,null,2));
  }
  if(failure)throw Error('Owner smoke failed: '+JSON.stringify(record));
  assert.equal(record.stopAfterAnnouncement,true);assert.equal(record.exitCode,0);
 });
}finally{
 // Exact UUID-owned TEMP checkout only; never touch the source/protected worktrees.
 assert.equal(dirname(temp),tmpdir());assert.match(temp.split(/[\\/]/).at(-1),/^dispatch-portability-[a-f0-9-]{36}$/);rmSync(temp,{recursive:true,force:true});
}

}
