# Local integrity, not signed-code provenance or production authorization.
# Trust: approved policy digest + repository anchor + first reviewed Git manifest.
# Legacy policy permits non-security descendants; this milestone requires its exact direct-child snapshot.
# Legitimate clones share anchored Git history; remote identity, signatures and dependencies are not attested.
# The trusted verifier/approved Git history are part of the local TCB; replacing the executable can bypass local checks.
# Review manifests are updated manually during owner-approved certification, never regenerated by the launcher.
param([switch]$ArcgisOfflineReview,[switch]$BasemapReview,[switch]$MilestoneAReview,[string]$Repository=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..\..')).Path)
$ErrorActionPreference='Stop'
$repo=[IO.Path]::GetFullPath($Repository).TrimEnd('\','/');$safe=$repo.Replace('\','/')
$base='4f685022e26a07297339750ae67219526384eef2'
$anchor='4e08dd26dc7aebcb57f7be85ab7972bf0cfe0b48'
$branchName='codex/dispatch-visual-shell'
$policyDigest='e2da2515f0498a5a050a3dbeb33ddf7dcda8eb679508c1c378889f90ab7336e4'
$self='tools/dispatch-auth-local/verify-sources.ps1'
$manifestName='tools/dispatch-auth-local/source-integrity.json'
$repairPaths=@('tools/dispatch-auth-local/portability.test.mjs',$manifestName,$self)
function Git-Read([string[]]$Arguments){$result=@(& git --no-replace-objects -c ('safe.directory='+$safe) -C $repo @Arguments);if($LASTEXITCODE -ne 0){throw 'Source integrity Git check failed'};return $result}
function Text-Hash([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value.Replace("`r`n","`n"))))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
function Policy-Hash($m){
 $lines=@($m.format,$m.baseRevision,$m.repositoryAnchorRevision,$m.branch)
 [string[]]$policyNames=@($m.sources.PSObject.Properties.Name);[Array]::Sort($policyNames,[StringComparer]::Ordinal)
 foreach($name in $policyNames){if($name -ne $self){$lines+=($name+'='+$m.sources.$name)}}
 return Text-Hash (($lines -join "`n")+"`n")
}
$root=(Git-Read @('rev-parse','--show-toplevel')) -join ''
if([IO.Path]::GetFullPath($root) -ne $repo){throw 'Exact repository root required'}
if(((Git-Read @('branch','--show-current')) -join '') -ne $branchName){throw 'Certified Dispatch branch required'}
$head=(Git-Read @('rev-parse','HEAD')) -join ''
& git --no-replace-objects -c ('safe.directory='+$safe) -C $repo merge-base --is-ancestor $anchor $head
if($LASTEXITCODE -ne 0){throw 'Expected Dispatch repository anchor required'}
$required=@(
 'dispatch/app.mjs','dispatch/local-auth-view.mjs','dispatch/index.html','dispatch/styles.css','dispatch/map.css','dispatch/view-preference.mjs','dispatch/themes.css','dispatch/theme.js','dispatch/auth.mjs','dispatch/components.mjs','dispatch/assets/gridly-logo.png',
 'tools/dispatch-ui/serve.mjs','tools/responder/phase29/installer/install.sql',
 'tools/dispatch-auth-local/docker-guard.cs','tools/dispatch-auth-local/context-docker-guard.cs','tools/dispatch-auth-local/context.local.sql','tools/dispatch-auth-local/session.mjs','tools/dispatch-auth-local/server.mjs',
 'tools/dispatch-auth-local/owner.ps1','tools/dispatch-auth-local/owner-stop.ps1','tools/dispatch-auth-local/owner-credentials.ps1','tools/dispatch-auth-local/owner-fixture.mjs','tools/dispatch-auth-local/owner-runtime.mjs','tools/dispatch-auth-local/verify-sources.ps1',
 'tools/dispatch-auth-local/run.ps1','tools/dispatch-auth-local/certify.ps1','tools/dispatch-auth-local/run-regressions.ps1','tools/dispatch-auth-local/context.test.mjs','tools/dispatch-auth-local/browser.test-support.mjs','tools/dispatch-auth-local/owner.test.mjs','tools/dispatch-auth-local/owner-dialog.test.mjs','tools/dispatch-auth-local/owner-edge.test.mjs','tools/dispatch-auth-local/portability.test.mjs','tools/dispatch-auth-local/OWNER-ACCEPTANCE.md','tools/dispatch-auth-local/README.md'
)
$manifestPath=Join-Path $repo $manifestName
if(-not(Test-Path -LiteralPath $manifestPath -PathType Leaf)){throw 'Reviewed source manifest missing'}
$manifest=Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json

# Exact pending review or direct-child committed offline snapshot; no live ArcGIS activation.
$arcgisDigest='5b99941aaf3931af88bfe460fca4c8dde27457540abe109757a92f7a820563d7'
$arcgisHead='6317583b3e3e6166658b9355d3e582d7fe146165'
$arcgisSubject='Prepare Dispatch ArcGIS Standard and Satellite offline'
$arcgisPaths=@('dispatch/README.md','dispatch/arcgis-offline.mjs','dispatch/basemap.mjs','dispatch/map-view.mjs','tests/dispatch-arcgis-offline.test.mjs','tools/dispatch-ui/serve.mjs','tools/dispatch-auth-local/portability.test.mjs','tools/dispatch-auth-local/source-integrity.json','tools/dispatch-auth-local/verify-sources.ps1')
$arcgisAdditions=@('dispatch/arcgis-offline.mjs','tests/dispatch-arcgis-offline.test.mjs')
if($manifest.arcgisOfflineSnapshot){
 $pending=$head -eq $arcgisHead
 if($pending -and (-not $ArcgisOfflineReview -or $BasemapReview -or $MilestoneAReview)){throw 'Exact offline review required; ordinary startup refused'}
 if(-not $pending -and ($ArcgisOfflineReview -or $BasemapReview -or $MilestoneAReview)){throw 'Pending review cannot authorize committed offline snapshot'}
 $original=((Git-Read @('show',($arcgisHead+':'+$manifestName))) -join "`n")|ConvertFrom-Json
 [string[]]$originalKeys=@($original.PSObject.Properties.Name);[string[]]$actualKeys=@($manifest.PSObject.Properties.Name|Where-Object {$_ -ne 'arcgisOfflineSnapshot'});[Array]::Sort($originalKeys,[StringComparer]::Ordinal);[Array]::Sort($actualKeys,[StringComparer]::Ordinal)
 if(($originalKeys -join "`n") -cne ($actualKeys -join "`n")){throw 'Offline manifest substitution refused'}
 foreach($key in $originalKeys){if((Text-Hash ($manifest.$key|ConvertTo-Json -Compress -Depth 20)) -ne (Text-Hash ($original.$key|ConvertTo-Json -Compress -Depth 20))){throw 'Original snapshot or security policy changed'}}
 $review=$manifest.arcgisOfflineSnapshot
 if((($review.PSObject.Properties.Name|Sort-Object) -join ',') -ne 'commitSubject,files,inventory,startingHead,verifierCanonicalHash' -or $review.startingHead -ne $arcgisHead -or $review.commitSubject -cne $arcgisSubject){throw 'Invalid offline review shape'}
 [string[]]$paths=$arcgisPaths;[Array]::Sort($paths,[StringComparer]::Ordinal)
 if($review.inventory -isnot [Array] -or ($review.inventory -join "`n") -cne ($paths -join "`n")){throw 'Exact offline inventory required'}
 [string[]]$names=@($paths|Where-Object {$_ -ne $self -and $_ -ne $manifestName});[Array]::Sort($names,[StringComparer]::Ordinal)
 [string[]]$hashNames=@($review.files.PSObject.Properties.Name);[Array]::Sort($hashNames,[StringComparer]::Ordinal)
 if(($hashNames -join "`n") -cne ($names -join "`n")){throw 'Exact offline hash coverage required'}
 $lines=@($arcgisHead,$arcgisSubject,$review.verifierCanonicalHash)+@($paths|ForEach-Object {'inventory='+$_})+@($names|ForEach-Object {$_+'='+$review.files.$_})
 if((Text-Hash (($lines -join "`n")+"`n")) -ne $arcgisDigest){throw 'Unreviewed offline hashes'}
 $canonical=[regex]::Replace(([IO.File]::ReadAllText((Join-Path $repo $self))).Replace("`r`n","`n"),'(?m)^\$arcgisDigest=''[a-f0-9]{64}''$', '$arcgisDigest=''REVIEW_DIGEST''')
 if((Text-Hash $canonical) -ne $review.verifierCanonicalHash){throw 'Offline verifier tampered'}
 if($pending){
 if(@(Git-Read @('diff','--cached','--name-only')).Count){throw 'Offline review requires clean index'}
 [string[]]$changes=@(Git-Read @('diff','--name-only','HEAD'))+@(Git-Read @('ls-files','--others','--exclude-standard'));[Array]::Sort($changes,[StringComparer]::Ordinal)
 if(($changes -join "`n") -cne ($paths -join "`n")){throw 'Unexpected offline source inventory'}
 if(@(Git-Read @('diff','--name-only','--diff-filter=ADRTUXB','HEAD')).Count){throw 'Offline tracked source replacement refused'}
 }else{
  $parents=(((Git-Read @('rev-list','--parents','-n','1',$head)) -join '') -split ' ')
  if($parents.Count -ne 2 -or $parents[1] -ne $arcgisHead){throw 'Exact offline direct parent required'}
  if((((Git-Read @('show','-s','--format=%B',$head)) -join "`n").TrimEnd()) -cne $arcgisSubject){throw 'Exact offline commit subject required'}
  [string[]]$expectedChanges=@($paths|ForEach-Object {$(if($arcgisAdditions -contains $_){'A'}else{'M'})+"`t"+$_})
  [string[]]$actualChanges=@(Git-Read @('diff-tree','--no-commit-id','--name-status','--no-renames','-r',$arcgisHead,$head))
  [Array]::Sort($expectedChanges,[StringComparer]::Ordinal);[Array]::Sort($actualChanges,[StringComparer]::Ordinal)
  if(($actualChanges -join "`n") -cne ($expectedChanges -join "`n")){throw 'Exact offline committed inventory required'}
  & git --no-replace-objects -c ('safe.directory='+$safe) -C $repo diff --quiet HEAD --
  if($LASTEXITCODE -ne 0){throw 'Committed offline working tree or index dirty'}
  if(@(Git-Read @('ls-files','--others','--exclude-standard')).Count){throw 'Committed offline unreviewed source addition'}
 }
 $protected=@(@($required)+@($original.milestoneASnapshot.files.PSObject.Properties.Name)+@($original.basemapSnapshot.files.PSObject.Properties.Name)+@($paths)|Select-Object -Unique)
 $tracked=if($pending){@($protected|Where-Object {$arcgisAdditions -notcontains $_})}else{@($protected)}
 if(((@(Git-Read (@('ls-files','--')+@($tracked)))|Sort-Object) -join "`n") -cne (($tracked|Sort-Object) -join "`n")){throw 'Offline protected tracking changed'}
 foreach($name in $protected){
  $path=Join-Path $repo $name;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw 'Offline source missing'}
  $cursor=Get-Item -LiteralPath $path;while($cursor.FullName -ne $repo){if($cursor.Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'Offline reparse refused'};$cursor=Get-Item -LiteralPath ([IO.Path]::GetDirectoryName($cursor.FullName))}
  if($name -eq $self -or $name -eq $manifestName){continue}
  $expected=if($names -contains $name){$review.files.$name}elseif($original.basemapSnapshot.files.$name){$original.basemapSnapshot.files.$name}elseif($original.milestoneASnapshot.files.$name){$original.milestoneASnapshot.files.$name}else{$original.sources.$name}
  $actual=if($name -like '*.png'){(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}else{Text-Hash ([IO.File]::ReadAllText($path))}
  if($expected -notmatch '^[a-f0-9]{64}$' -or $actual -ne $expected){throw ('Offline/protected source mismatch: '+$name)}
 }
 foreach($entry in @(Git-Read (@('ls-files','--stage','--')+@($tracked)))){if($entry -notmatch '^100644 [a-f0-9]{40} 0\t'){throw 'Offline regular tracking required'}}
 $authRoot=Join-Path $repo 'tools/dispatch-auth-local'
 if(@(Get-ChildItem -LiteralPath $authRoot -Recurse -Force|Where-Object {$_.Attributes -band [IO.FileAttributes]::ReparsePoint}).Count){throw 'Offline Auth reparse refused'}
 $actualAuth=@(Get-ChildItem -LiteralPath $authRoot -File -Recurse -Force|ForEach-Object {$_.FullName.Substring($repo.Length+1).Replace('\','/')})
 $expectedAuth=@(Git-Read @('ls-tree','-r','--name-only',$arcgisHead,'--','tools/dispatch-auth-local'))
 if((($actualAuth|Sort-Object) -join "`n") -cne (($expectedAuth|Sort-Object) -join "`n")){throw 'Offline unapproved Auth addition'}
 $phase=if($pending){'pending review; ordinary startup closed'}else{'exact committed offline snapshot'}
 Write-Output ('SOURCE INTEGRITY PASS: nine-file offline; original protections retained; '+$phase)
 return
}
if($ArcgisOfflineReview){throw 'Reviewed offline manifest required'}

# Owner-approved two-state basemap contract: exact pending review or exact direct-child snapshot.
$basemapDigest='fb559c0ee5d9250bcda92ffc9e0962c10198f09571811e513fdd393f65cf575f'
$basemapHead='740a1a225ddeb18656a348d5878ff2c45693a775'
$basemapSubject='Establish continuous Dispatch basemap foundation'
$basemapAdditions=@('dispatch/basemap-provider.mjs','tests/dispatch-basemap-provider.test.mjs')
$basemapPaths=@('dispatch/README.md','dispatch/basemap-provider.mjs','dispatch/basemap.mjs','dispatch/map-view.mjs','dispatch/map.css','tests/dispatch-basemap-provider.test.mjs','tests/dispatch-map-workspace.test.mjs','tools/dispatch-ui/serve.mjs','tools/dispatch-auth-local/verify-sources.ps1','tools/dispatch-auth-local/source-integrity.json','tools/dispatch-auth-local/portability.test.mjs')
if($manifest.basemapSnapshot){
 $pending=$head -eq $basemapHead
 if($pending -and (-not $BasemapReview -or $MilestoneAReview)){throw 'Uncommitted basemap candidate; ordinary startup refused'}
 if(-not $pending -and ($BasemapReview -or $MilestoneAReview)){throw 'Pending review flag cannot authorize committed basemap'}
 $original=((Git-Read @('show',($basemapHead+':'+$manifestName))) -join "`n") | ConvertFrom-Json
 if((($manifest.PSObject.Properties.Name|Sort-Object) -join ',') -ne 'basemapSnapshot,baseRevision,branch,format,milestoneASnapshot,repositoryAnchorRevision,sources'){throw 'Invalid basemap manifest shape'}
 foreach($key in $original.PSObject.Properties.Name){if((Text-Hash ($manifest.$key|ConvertTo-Json -Compress -Depth 20)) -ne (Text-Hash ($original.$key|ConvertTo-Json -Compress -Depth 20))){throw 'Original integrity contract changed'}}
 $review=$manifest.basemapSnapshot
 if((($review.PSObject.Properties.Name|Sort-Object) -join ',') -ne 'commitSubject,files,inventory,startingHead,verifierCanonicalHash' -or $review.startingHead -ne $basemapHead -or $review.commitSubject -cne $basemapSubject){throw 'Invalid basemap review contract'}
 [string[]]$paths=$basemapPaths;[Array]::Sort($paths,[StringComparer]::Ordinal)
 if($review.inventory -isnot [Array] -or $review.inventory.Count -ne 11 -or ($review.inventory -join "`n") -cne ($paths -join "`n")){throw 'Exact eleven-file basemap inventory required'}
 [string[]]$names=@($paths|Where-Object {$_ -ne $self -and $_ -ne $manifestName});[Array]::Sort($names,[StringComparer]::Ordinal)
 [string[]]$fileNames=@($review.files.PSObject.Properties.Name);[Array]::Sort($fileNames,[StringComparer]::Ordinal)
 if(($fileNames -join "`n") -cne ($names -join "`n")){throw 'Exact basemap hash coverage required'}
 $lines=@($basemapHead,$basemapSubject,$review.verifierCanonicalHash)+@($paths|ForEach-Object {'inventory='+$_})+@($names|ForEach-Object {$_+'='+$review.files.$_})
 if((Text-Hash (($lines -join "`n")+"`n")) -ne $basemapDigest){throw 'Unreviewed basemap hashes'}
 $canonical=[regex]::Replace(([IO.File]::ReadAllText((Join-Path $repo $self))).Replace("`r`n","`n"),'(?m)^\$basemapDigest=''[a-f0-9]{64}''$', '$basemapDigest=''REVIEW_DIGEST''')
 if((Text-Hash $canonical) -ne $review.verifierCanonicalHash){throw 'Basemap verifier tampered'}
 if($pending){
 if(@(Git-Read @('diff','--cached','--name-only')).Count){throw 'Pending basemap review requires clean index'}
 [string[]]$changes=@(Git-Read @('diff','--name-only','HEAD'))+@(Git-Read @('ls-files','--others','--exclude-standard'));[Array]::Sort($changes,[StringComparer]::Ordinal)
 if(($changes -join "`n") -cne ($paths -join "`n") -or @(Git-Read @('diff','--name-only','--diff-filter=D','HEAD')).Count){throw 'Unexpected basemap source inventory'}
 }else{
  $parents=(((Git-Read @('rev-list','--parents','-n','1',$head)) -join '') -split ' ')
  if($parents.Count -ne 2 -or $parents[1] -ne $basemapHead){throw 'Exact basemap direct parent required'}
  if((((Git-Read @('show','-s','--format=%B',$head)) -join "`n").TrimEnd()) -cne $basemapSubject){throw 'Exact basemap commit subject required'}
  [string[]]$expectedChanges=@($paths|ForEach-Object {$(if($basemapAdditions -contains $_){'A'}else{'M'})+"`t"+$_})
  [string[]]$actualChanges=@(Git-Read @('diff-tree','--no-commit-id','--name-status','--no-renames','-r',$basemapHead,$head))
  [Array]::Sort($expectedChanges,[StringComparer]::Ordinal);[Array]::Sort($actualChanges,[StringComparer]::Ordinal)
  if(($actualChanges -join "`n") -cne ($expectedChanges -join "`n")){throw 'Exact basemap committed inventory required'}
  & git --no-replace-objects -c ('safe.directory='+$safe) -C $repo diff --quiet HEAD --
  if($LASTEXITCODE -ne 0){throw 'Committed basemap working tree or index dirty'}
  if(@(Git-Read @('ls-files','--others','--exclude-standard')).Count){throw 'Committed basemap unreviewed source addition'}
 }
 $expectedTracked=@(@($required)+@($original.milestoneASnapshot.files.PSObject.Properties.Name)+@($paths)|Select-Object -Unique)
 if($pending){$expectedTracked=@($expectedTracked|Where-Object {$basemapAdditions -notcontains $_})}
 $actualTracked=@(Git-Read (@('ls-files','--')+@($expectedTracked)))
 if((($actualTracked|Sort-Object) -join "`n") -cne (($expectedTracked|Sort-Object) -join "`n")){throw 'Basemap protected tracking changed'}

 foreach($name in @($required)+@($original.milestoneASnapshot.files.PSObject.Properties.Name)+@($paths)|Select-Object -Unique){
  $path=Join-Path $repo $name;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw 'Basemap/protected source missing'}
  $cursor=Get-Item -LiteralPath $path;while($cursor.FullName -ne $repo){if($cursor.Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'Basemap source reparse refused'};$cursor=Get-Item -LiteralPath ([IO.Path]::GetDirectoryName($cursor.FullName))}
  if($name -eq $manifestName -or $name -eq $self){continue}
  $expected=if($names -contains $name){$review.files.$name}elseif($original.milestoneASnapshot.files.$name){$original.milestoneASnapshot.files.$name}else{$original.sources.$name}
  $actual=if($name -like '*.png'){(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}else{Text-Hash ([IO.File]::ReadAllText($path))}
  if($expected -notmatch '^[a-f0-9]{64}$' -or $actual -ne $expected){throw ('Basemap/protected hash mismatch: '+$name)}
 }
 foreach($entry in @(Git-Read (@('ls-files','--stage','--')+@($required)+@($paths)))){if($entry -notmatch '^100644 [a-f0-9]{40} 0\t'){throw 'Basemap regular tracking required'}}
 $authRoot=Join-Path $repo 'tools/dispatch-auth-local'
 if(@(Get-ChildItem -LiteralPath $authRoot -Recurse -Force|Where-Object {$_.Attributes -band [IO.FileAttributes]::ReparsePoint}).Count){throw 'Basemap Auth reparse refused'}
 $actualAuth=@(Get-ChildItem -LiteralPath $authRoot -File -Recurse -Force|ForEach-Object {$_.FullName.Substring($repo.Length+1).Replace('\','/')})
 $expectedAuth=@(Git-Read @('ls-tree','-r','--name-only',$basemapHead,'--','tools/dispatch-auth-local'))
 if((($actualAuth|Sort-Object) -join "`n") -cne (($expectedAuth|Sort-Object) -join "`n")){throw 'Basemap unapproved Auth addition'}
 $phase=if($pending){'pending review; ordinary launcher closed'}else{'exact committed basemap snapshot'}
 Write-Output ('SOURCE INTEGRITY PASS: eleven-file basemap; original protections retained; '+$phase)
 return
}
if($BasemapReview){throw 'Reviewed basemap manifest required'}

# Owner-approved two-state contract. Pending review is never ordinary startup.
# Only the exact direct-child commit can promote these reviewed bytes; descendants
# need a separate owner-approved transition. No runtime manifest generation.
$milestoneDigest='842352313b77eeaef9dacb0f7a84924bdfa28b907be70e36f94eda2e16901aac'
$milestoneHead='a8d746d0a9f5215e4fabdf9ef544a4b9a79ba72e'
$milestoneSubject='Complete Dispatch fullscreen and regional awareness foundation'
$milestonePaths=@('dispatch/README.md','dispatch/app.mjs','dispatch/awareness-perspective.mjs','dispatch/map-view.mjs','dispatch/map.css','tests/dispatch-awareness-perspective.test.mjs','tests/dispatch-map-workspace.test.mjs','tests/dispatch-marker-normalization.test.mjs','tests/dispatch-selection.test.mjs','tools/dispatch-auth-local/portability.test.mjs',$manifestName,$self)
$milestoneAdditions=@('dispatch/awareness-perspective.mjs','tests/dispatch-awareness-perspective.test.mjs','tests/dispatch-map-workspace.test.mjs')
if($manifest.milestoneASnapshot){
 $pending=$head -eq $milestoneHead
 if($pending -and -not $MilestoneAReview){throw 'Uncommitted milestone candidate; ordinary startup refused'}
 if(-not $pending -and $MilestoneAReview){throw 'Explicit review requires exact milestone starting revision'}
 $original=((Git-Read @('show',($milestoneHead+':'+$manifestName))) -join "`n") | ConvertFrom-Json
 if((Policy-Hash $original) -ne $policyDigest){throw 'Original reviewed policy mismatch'}
 if((($manifest.PSObject.Properties.Name|Sort-Object) -join ',') -ne 'baseRevision,branch,format,milestoneASnapshot,repositoryAnchorRevision,sources'){throw 'Invalid milestone snapshot manifest'}
 foreach($key in 'format','baseRevision','repositoryAnchorRevision','branch'){if($manifest.$key -ne $original.$key){throw 'Original contract changed'}}
 if((Policy-Hash $manifest) -ne $policyDigest -or (Text-Hash ($manifest.sources|ConvertTo-Json -Compress)) -ne (Text-Hash ($original.sources|ConvertTo-Json -Compress))){throw 'Original protected hashes changed'}
 $review=$manifest.milestoneASnapshot
 if((($review.PSObject.Properties.Name|Sort-Object) -join ',') -ne 'commitSubject,files,inventory,startingHead,verifierCanonicalHash' -or $review.startingHead -ne $milestoneHead -or $review.commitSubject -cne $milestoneSubject){throw 'Invalid milestone snapshot contract'}
 [string[]]$orderedPaths=@($milestonePaths);[Array]::Sort($orderedPaths,[StringComparer]::Ordinal)
 if($review.inventory -isnot [Array] -or $review.inventory.Count -ne 12){throw 'Invalid snapshot inventory shape'}; if(($review.inventory -join "`n") -cne ($orderedPaths -join "`n")){throw 'Unexpected committed inventory contract'}
 $reviewNames=@($milestonePaths|Where-Object {$_ -ne $self -and $_ -ne $manifestName})
 if((($review.files.PSObject.Properties.Name|Sort-Object) -join "`n") -ne (($reviewNames|Sort-Object) -join "`n")){throw 'Unexpected review coverage'}
 [string[]]$ordered=$reviewNames;[Array]::Sort($ordered,[StringComparer]::Ordinal)
 $lines=@($milestoneHead,$milestoneSubject,$policyDigest,$review.verifierCanonicalHash)+@($orderedPaths|ForEach-Object {'inventory='+$_})
 foreach($name in $ordered){$lines+=($name+'='+$review.files.$name)}
 if((Text-Hash (($lines -join "`n")+"`n")) -ne $milestoneDigest){throw 'Unreviewed milestone snapshot hashes'}
 $canonical=[regex]::Replace(([IO.File]::ReadAllText((Join-Path $repo $self))).Replace("`r`n","`n"),'(?m)^\$milestoneDigest=''[a-f0-9]{64}''$', '$milestoneDigest=''REVIEW_DIGEST''')
 if((Text-Hash $canonical) -ne $review.verifierCanonicalHash){throw 'Review verifier tampered'}
 if($pending){
  $changes=@(Git-Read @('diff','--name-only','HEAD'))+@(Git-Read @('ls-files','--others','--exclude-standard'))
  if(@($changes|Where-Object {$milestonePaths -notcontains $_}).Count){throw 'Unexpected pending milestone source change'}
  if(@(Git-Read @('diff','--name-only','--diff-filter=D','HEAD')).Count){throw 'Review deletion refused'}
 }else{
  $parents=(((Git-Read @('rev-list','--parents','-n','1',$head)) -join '') -split ' ')
  if($parents.Count -ne 2 -or $parents[1] -ne $milestoneHead){throw 'Exact milestone direct parent required; unrelated revisions refused'}
  $subject=((Git-Read @('show','-s','--format=%B',$head)) -join "`n").TrimEnd()
  if($subject -cne $milestoneSubject){throw 'Exact milestone commit subject required'}
  [string[]]$expectedChanges=@($orderedPaths|ForEach-Object {$(if($milestoneAdditions -contains $_){'A'}else{'M'})+"`t"+$_})
  [string[]]$actualChanges=@(Git-Read @('diff-tree','--no-commit-id','--name-status','--no-renames','-r',$milestoneHead,$head))
  [Array]::Sort($expectedChanges,[StringComparer]::Ordinal);[Array]::Sort($actualChanges,[StringComparer]::Ordinal)
  if(($actualChanges -join "`n") -cne ($expectedChanges -join "`n")){throw 'Exact milestone changed-file inventory required'}
  & git --no-replace-objects -c ('safe.directory='+$safe) -C $repo diff --quiet HEAD --
  if($LASTEXITCODE -ne 0){throw 'Committed milestone has unreviewed working-tree or index changes'}
  if(@(Git-Read @('ls-files','--others','--exclude-standard')).Count){throw 'Unreviewed source addition to committed milestone'}
  foreach($entry in @(Git-Read (@('ls-tree',$head,'--')+@($required)+@($milestonePaths)))){if($entry -notmatch '^100644 blob [a-f0-9]{40}\t'){throw 'Regular tracked milestone source required'}}
 }
 foreach($name in @($required)+@($milestonePaths)|Select-Object -Unique){
  $path=Join-Path $repo $name;if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw ('Review source missing: '+$name)}
  $cursor=Get-Item -LiteralPath $path;while($cursor.FullName -ne $repo){if($cursor.Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'Review source reparse refused'};$cursor=Get-Item -LiteralPath ([IO.Path]::GetDirectoryName($cursor.FullName))}
  if($name -eq $manifestName -or $name -eq $self){continue}
  $expected=if($reviewNames -contains $name){$review.files.$name}else{$original.sources.$name}
  $actual=if($name -like '*.png'){(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}else{Text-Hash ([IO.File]::ReadAllText($path))}
  if($expected -notmatch '^[a-f0-9]{64}$' -or $actual -ne $expected){throw ('Review source mismatch: '+$name)}
 }
 $trackedRequired=if($pending){@($required)+@($manifestName)}else{@($required)+@($milestonePaths)|Select-Object -Unique}
 $tracked=@(Git-Read (@('ls-files','--')+@($trackedRequired)))
 if((($tracked|Sort-Object) -join "`n") -ne (($trackedRequired|Sort-Object) -join "`n")){throw 'Protected tracking changed'}
 $authRoot=Join-Path $repo 'tools/dispatch-auth-local'
 if(@(Get-ChildItem -LiteralPath $authRoot -Recurse -Force|Where-Object {$_.Attributes -band [IO.FileAttributes]::ReparsePoint}).Count){throw 'Review Auth reparse refused'}
 $actualAuth=@(Get-ChildItem -LiteralPath $authRoot -File -Recurse -Force|ForEach-Object {$_.FullName.Substring($repo.Length+1).Replace('\','/')})
 $expectedAuth=@(@($required)+@($manifestName)|Where-Object {$_ -like 'tools/dispatch-auth-local/*'})
 if(@(Compare-Object $actualAuth $expectedAuth).Count){throw 'Unreviewed Auth inventory'}
 $phase=if($pending){'exact pending milestone certification; ordinary launcher remains closed'}else{'exact committed milestone snapshot'}
 Write-Output ('SOURCE INTEGRITY PASS: 35 original policy hashes preserved; 12 reviewed milestone files; '+$phase)
 exit 0
}
if($manifest.milestoneAReview){throw 'Legacy pending review requires an approved snapshot transition'}


if((($manifest.PSObject.Properties.Name | Sort-Object) -join ',') -ne 'baseRevision,branch,format,repositoryAnchorRevision,sources' -or $manifest.format -ne 'dispatch-local-auth-sha256-lf-v2' -or $manifest.baseRevision -ne $base -or $manifest.repositoryAnchorRevision -ne $anchor -or $manifest.branch -ne $branchName){throw 'Invalid source manifest contract'}
if(((@($manifest.sources.PSObject.Properties.Name)|Sort-Object) -join "`n") -ne (($required|Sort-Object) -join "`n")){throw 'Incomplete source manifest coverage'}
if((Policy-Hash $manifest) -ne $policyDigest){throw 'Unreviewed manifest policy substitution'}
$protected=@($required)+@($manifestName)
$tracked=@(Git-Read (@('ls-files','--')+$protected))
if((($tracked|Sort-Object) -join "`n") -cne (($protected|Sort-Object) -join "`n")){throw 'Protected source replacement is not tracked'}
foreach($name in $protected){
 $path=Join-Path $repo $name
 if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw ('Required source missing: '+$name)}
 $cursor=Get-Item -LiteralPath $path
 while($cursor.FullName -ne $repo){if($cursor.Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'Source reparse refused'};$cursor=Get-Item -LiteralPath ([IO.Path]::GetDirectoryName($cursor.FullName));if(-not $cursor){throw 'Invalid source path'}}
 if($name -ne $manifestName){$expected=$manifest.sources.$name;if($expected -notmatch '^[a-f0-9]{64}$'){throw 'Invalid source digest'}
  if($name -like '*.png'){$actual=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}else{$actual=Text-Hash ([IO.File]::ReadAllText($path))}
  if($actual -ne $expected){throw ('Reviewed source mismatch: '+$name)}
 }
}
$authRoot=Join-Path $repo 'tools\dispatch-auth-local'
if(@(Get-ChildItem -LiteralPath $authRoot -Recurse -Force | Where-Object {$_.Attributes -band [IO.FileAttributes]::ReparsePoint}).Count){throw 'Auth inventory reparse refused'}
$actualInventory=@(Get-ChildItem -LiteralPath $authRoot -File -Recurse -Force | ForEach-Object {$_.FullName.Substring($repo.Length+1).Replace('\','/')})
$expectedInventory=@($protected | Where-Object {$_ -like 'tools/dispatch-auth-local/*'})
if(@(Compare-Object $actualInventory $expectedInventory).Count){throw 'Unreviewed security-relevant Auth addition or omission'}
if($head -eq $anchor){
 # Explicit pending owner review only. No HEAD exception authorizes runtime source changes.
 $changes=@(Git-Read @('diff','--name-only','HEAD'))
 if(@($changes|Where-Object {$protected -contains $_ -and $repairPaths -notcontains $_}).Count){throw 'Unreviewed pending source change'}
 & git --no-replace-objects -c ('safe.directory='+$safe) -C $repo diff --quiet HEAD -- @($protected | Where-Object {$repairPaths -notcontains $_})
 if($LASTEXITCODE -ne 0){throw 'Protected runtime changed during review'}
 $phase='pending-security-review'
}else{
 # Find the FIRST introduction of the approved policy, not the latest editable manifest.
 # A substituted self-hash or later manifest cannot replace that immutable review snapshot.
 $review=$null
 foreach($revision in @(Git-Read @('log','--first-parent','--reverse','--format=%H',($anchor+'..'+$head),'--',$manifestName))){
  try{$candidate=((Git-Read @('show',($revision+':'+$manifestName))) -join "`n") | ConvertFrom-Json;if((Policy-Hash $candidate) -eq $policyDigest){$review=$revision;break}}catch{continue}
 }
 if(-not $review){throw 'Reviewed security source snapshot absent'}
 & git --no-replace-objects -c ('safe.directory='+$safe) -C $repo diff --quiet $review -- @protected
 if($LASTEXITCODE -ne 0){throw 'Protected sources or manifest differ from reviewed Git snapshot'}
 $phase='reviewed-source-snapshot'
}
Write-Output ('SOURCE INTEGRITY PASS: '+$required.Count+' reviewed files; '+$phase+'; no generated evidence dependency')