# Local integrity, not signed-code provenance or production authorization.
# Trust: approved policy digest + repository anchor + first reviewed Git manifest.
# Later non-security commits may advance HEAD; protected content and Auth inventory may not.
# Legitimate clones share anchored Git history; remote identity, signatures and dependencies are not attested.
# The trusted verifier/approved Git history are part of the local TCB; replacing the executable can bypass local checks.
# Review manifests are updated manually during owner-approved certification, never regenerated by the launcher.
param([string]$Repository=(Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..\..')).Path)
$ErrorActionPreference='Stop'
$repo=[IO.Path]::GetFullPath($Repository).TrimEnd('\','/');$safe=$repo.Replace('\','/')
$base='4f685022e26a07297339750ae67219526384eef2'
$anchor='4e08dd26dc7aebcb57f7be85ab7972bf0cfe0b48'
$branchName='codex/dispatch-visual-shell'
$policyDigest='e2da2515f0498a5a050a3dbeb33ddf7dcda8eb679508c1c378889f90ab7336e4'
$self='tools/dispatch-auth-local/verify-sources.ps1'
$manifestName='tools/dispatch-auth-local/source-integrity.json'
$repairPaths=@('tools/dispatch-auth-local/portability.test.mjs',$manifestName,$self)
function Git-Read([string[]]$Arguments){$result=@(& git --no-replace-objects -c ('safe.directory='+$safe) -C $repo @Arguments);if($LASTEXITCODE -ne 0){throw 'Source integrity Git check failed'};return $result}
function Text-Hash([string]$Value){$sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Value.Replace("`r`n","`n"))))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}}
function Policy-Hash($m){
 $lines=@($m.format,$m.baseRevision,$m.repositoryAnchorRevision,$m.branch)
 [string[]]$policyNames=@($m.sources.PSObject.Properties.Name);[Array]::Sort($policyNames,[StringComparer]::Ordinal)
 foreach($name in $policyNames){if($name -ne $self){$lines+=($name+'='+$m.sources.$name)}}
 return Text-Hash (($lines -join "`n")+"`n")
}
$root=(Git-Read @('rev-parse','--show-toplevel')) -join ''
if([IO.Path]::GetFullPath($root) -ne $repo){throw 'Exact repository root required'}
if(((Git-Read @('branch','--show-current')) -join '') -ne $branchName){throw 'Certified Dispatch branch required'}
$head=(Git-Read @('rev-parse','HEAD')) -join ''
& git --no-replace-objects -c ('safe.directory='+$safe) -C $repo merge-base --is-ancestor $anchor $head
if($LASTEXITCODE -ne 0){throw 'Expected Dispatch repository anchor required'}
$required=@(
 'dispatch/app.mjs','dispatch/local-auth-view.mjs','dispatch/index.html','dispatch/styles.css','dispatch/map.css','dispatch/view-preference.mjs','dispatch/themes.css','dispatch/theme.js','dispatch/auth.mjs','dispatch/components.mjs','dispatch/assets/gridly-logo.png',
 'tools/dispatch-ui/serve.mjs','tools/responder/phase29/installer/install.sql',
 'tools/dispatch-auth-local/docker-guard.cs','tools/dispatch-auth-local/context-docker-guard.cs','tools/dispatch-auth-local/context.local.sql','tools/dispatch-auth-local/session.mjs','tools/dispatch-auth-local/server.mjs',
 'tools/dispatch-auth-local/owner.ps1','tools/dispatch-auth-local/owner-stop.ps1','tools/dispatch-auth-local/owner-credentials.ps1','tools/dispatch-auth-local/owner-fixture.mjs','tools/dispatch-auth-local/owner-runtime.mjs','tools/dispatch-auth-local/verify-sources.ps1',
 'tools/dispatch-auth-local/run.ps1','tools/dispatch-auth-local/certify.ps1','tools/dispatch-auth-local/run-regressions.ps1','tools/dispatch-auth-local/context.test.mjs','tools/dispatch-auth-local/browser.test-support.mjs','tools/dispatch-auth-local/owner.test.mjs','tools/dispatch-auth-local/owner-dialog.test.mjs','tools/dispatch-auth-local/owner-edge.test.mjs','tools/dispatch-auth-local/portability.test.mjs','tools/dispatch-auth-local/OWNER-ACCEPTANCE.md','tools/dispatch-auth-local/README.md'
)
$manifestPath=Join-Path $repo $manifestName
if(-not(Test-Path -LiteralPath $manifestPath -PathType Leaf)){throw 'Reviewed source manifest missing'}
$manifest=Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
if((($manifest.PSObject.Properties.Name | Sort-Object) -join ',') -ne 'baseRevision,branch,format,repositoryAnchorRevision,sources' -or $manifest.format -ne 'dispatch-local-auth-sha256-lf-v2' -or $manifest.baseRevision -ne $base -or $manifest.repositoryAnchorRevision -ne $anchor -or $manifest.branch -ne $branchName){throw 'Invalid source manifest contract'}
if(((@($manifest.sources.PSObject.Properties.Name)|Sort-Object) -join "`n") -ne (($required|Sort-Object) -join "`n")){throw 'Incomplete source manifest coverage'}
if((Policy-Hash $manifest) -ne $policyDigest){throw 'Unreviewed manifest policy substitution'}
$protected=@($required)+@($manifestName)
$tracked=@(Git-Read (@('ls-files','--')+$protected))
if((($tracked|Sort-Object) -join "`n") -cne (($protected|Sort-Object) -join "`n")){throw 'Protected source replacement is not tracked'}
foreach($name in $protected){
 $path=Join-Path $repo $name
 if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw ('Required source missing: '+$name)}
 $cursor=Get-Item -LiteralPath $path
 while($cursor.FullName -ne $repo){if($cursor.Attributes -band [IO.FileAttributes]::ReparsePoint){throw 'Source reparse refused'};$cursor=Get-Item -LiteralPath ([IO.Path]::GetDirectoryName($cursor.FullName));if(-not $cursor){throw 'Invalid source path'}}
 if($name -ne $manifestName){$expected=$manifest.sources.$name;if($expected -notmatch '^[a-f0-9]{64}$'){throw 'Invalid source digest'}
  if($name -like '*.png'){$actual=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}else{$actual=Text-Hash ([IO.File]::ReadAllText($path))}
  if($actual -ne $expected){throw ('Reviewed source mismatch: '+$name)}
 }
}
$authRoot=Join-Path $repo 'tools\dispatch-auth-local'
if(@(Get-ChildItem -LiteralPath $authRoot -Recurse -Force | Where-Object {$_.Attributes -band [IO.FileAttributes]::ReparsePoint}).Count){throw 'Auth inventory reparse refused'}
$actualInventory=@(Get-ChildItem -LiteralPath $authRoot -File -Recurse -Force | ForEach-Object {$_.FullName.Substring($repo.Length+1).Replace('\','/')})
$expectedInventory=@($protected | Where-Object {$_ -like 'tools/dispatch-auth-local/*'})
if(@(Compare-Object $actualInventory $expectedInventory).Count){throw 'Unreviewed security-relevant Auth addition or omission'}
if($head -eq $anchor){
 # Explicit pending owner review only. No HEAD exception authorizes runtime source changes.
 $changes=@(Git-Read @('diff','--name-only','HEAD'))
 if(@($changes|Where-Object {$protected -contains $_ -and $repairPaths -notcontains $_}).Count){throw 'Unreviewed pending source change'}
 & git --no-replace-objects -c ('safe.directory='+$safe) -C $repo diff --quiet HEAD -- @($protected | Where-Object {$repairPaths -notcontains $_})
 if($LASTEXITCODE -ne 0){throw 'Protected runtime changed during review'}
 $phase='pending-security-review'
}else{
 # Find the FIRST introduction of the approved policy, not the latest editable manifest.
 # A substituted self-hash or later manifest cannot replace that immutable review snapshot.
 $review=$null
 foreach($revision in @(Git-Read @('log','--first-parent','--reverse','--format=%H',($anchor+'..'+$head),'--',$manifestName))){
  try{$candidate=((Git-Read @('show',($revision+':'+$manifestName))) -join "`n") | ConvertFrom-Json;if((Policy-Hash $candidate) -eq $policyDigest){$review=$revision;break}}catch{continue}
 }
 if(-not $review){throw 'Reviewed security source snapshot absent'}
 & git --no-replace-objects -c ('safe.directory='+$safe) -C $repo diff --quiet $review -- @protected
 if($LASTEXITCODE -ne 0){throw 'Protected sources or manifest differ from reviewed Git snapshot'}
 $phase='reviewed-source-snapshot'
}
Write-Output ('SOURCE INTEGRITY PASS: '+$required.Count+' reviewed files; '+$phase+'; no generated evidence dependency')