const fs=require('node:fs');
const r=require('../../js/gridlyMarkerRegistry.js');
const out='.artifacts/lp24447-approved-png-review';fs.mkdirSync(out,{recursive:true});
function card(e,keys,base){return `<article><img src="../../${base}${e.asset}" alt="${e.label||e.key}"><h3>${e.label||e.key.replaceAll('_',' ')}</h3><code>${e.asset}</code><p>${keys}</p></article>`;}
const hazard=Object.values(r.entries).map(e=>card(e,Object.entries(r.aliases).filter(([,v])=>v===e.condition).map(([k])=>k).join(', '),r.basePath)).join('');
const nav=Object.values(r.navigation).map(e=>card(e,e.key,r.navigationBasePath)).join('');
const proof=[['fallen_tree','Legacy Fallen Tree → Debris in Road; raw data retained'],['road_impassable','Legacy Road Appears Impassable → Road Appears Blocked; raw data retained'],['roadway_incident','Generic Roadway Incident → Other Hazard (neutral fallback); no standalone marker. Known crash keeps Crash / Wreck.'],['travel_advisory','Explicit Travel Advisory → Travel Advisory; only established advisory input uses this marker.']].map(([key,text])=>card(r.resolve(key),text,r.basePath)).join('');
fs.writeFileSync(out+'/index.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Gridly approved marker review</title><style>body{margin:0;padding:24px;background:#edf3f8;color:#102b40;font:15px/1.5 system-ui}header{max-width:1000px}h1{line-height:1.2}section{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}article{background:white;border:1px solid #c9d9e4;border-radius:12px;padding:16px;overflow-wrap:anywhere}img{width:var(--size,64px);height:var(--size,64px);object-fit:contain}#navigation img{width:var(--size,48px);height:var(--size,48px)}code,p{font-size:12px}button{padding:10px;margin:4px;cursor:pointer}h3{margin:8px 0}footer{padding:24px 0}</style><header><p>GRIDLY · LOCAL OWNER REVIEW · LP244.47</p><h1>Exact approved PNG marker library</h1><p>Original PNG files displayed through CSS only. Runtime: hazards 64 × 64; navigation 48 × 48. Larger inspection changes display size only.</p><button onclick="document.body.style.removeProperty('--size')">Map size</button><button onclick="document.body.style.setProperty('--size','128px')">128 px inspection</button><button onclick="document.body.style.setProperty('--size','256px')">256 px inspection</button></header><h2>A — Hazard / reference library · 28 assets</h2><section>${hazard}</section><h2>B — Navigation · 3 assets</h2><section id="navigation">${nav}</section><h2>C — Consolidation proofs</h2><section>${proof}</section><footer>Crossing Location is a neutral reference. Navigation carries no incident or severity semantics. Local files only; no reporting, backend writes, or production changes.</footer></html>`);
console.log(out+'/index.html');
