import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import {execFileSync} from 'node:child_process';
import {ROOT,build} from '../../tools/lp1836/reassess-protected-preview-authorization.mjs';

test('candidate reconciles exact current governed artifact and Montgomery identities',()=>{const {candidate}=build();assert.equal(candidate.artifactIdentity,'sha256:c292ce65fd06f5f3265be988fa3fa8d152dbb0309aaf306e799646dd34b56a7f');assert.equal(candidate.fileCount,493);assert.equal(candidate.totalBytes,155746432);assert.equal(candidate.oversizedFileCount,0);assert.equal(candidate.montgomery.sha256,'2d7a52fdfbab8549a92b6724d557e9e26c4b089d523961d41b7ddc7b94c5e6b1');assert.ok(Object.values(candidate.exclusions).every(Boolean));});
test('real LP183.5 empty Direct Upload project state is explicit',()=>{const {pages}=build();assert.deepEqual(pages.project,{name:'gridly-preview',exists:true,model:'DIRECT_UPLOAD',directUpload:true,gitIntegration:false,productionBranch:'preview',deployments:0,customDomains:0,defaultHostname:'gridly-preview.pages.dev',automaticDeployment:false});assert.equal(pages.defaultHostnameApprovedForDistribution,false);assert.equal(pages.previewHostname.bound,false);});
test('Access evidence boundary and all live test statuses remain truthful',()=>{const {access}=build();assert.equal(access.evidenceStatus,'OWNER_VERIFIED_EXTERNAL_CONFIGURATION');assert.equal(access.apiVerified,false);for(const status of Object.values(access.liveTests))assert.equal(status,'NOT_RUN_LIVE_PREVIEW_DOES_NOT_EXIST');});
test('LP183.5A controls are incorporated without claiming rollback execution',()=>{const {rollback}=build();assert.equal(rollback.dnsRemoval.status,'PROVEN');assert.equal(rollback.pagesCustomDomainRemoval.status,'PROVEN_BY_AUTHORITATIVE_PLATFORM_DOCUMENTATION');assert.equal(rollback.projectDeletionFallback,'DOCUMENTED_LAST_RESORT_SEPARATELY_AUTHORIZED');assert.equal(rollback.firstDeployment.rollbackExecuted,false);assert.equal(rollback.firstDeployment.knownGoodRollback,'NOT_YET_AVAILABLE');});
test('future execution is bounded to one exact project and hostname with aborts',()=>{const {plan}=build();assert.equal(plan.targetProject,'gridly-preview');assert.equal(plan.targetHostname,'preview.gridlygo.com');assert.equal(plan.executionCount.directUploads,1);assert.ok(plan.abortConditions.length>=18);assert.equal(plan.futureOnly,true);});
test('scoped envelope cannot authorize launch, root replacement, or automation',()=>{const {authorization}=build();assert.equal(authorization.grantedNow,false);assert.equal(authorization.scope,'ONE_PROTECTED_PREVIEW_EXECUTION');for(const forbidden of ['public launch','root gridlygo.com replacement','automatic deployment'])assert.ok(authorization.explicitExclusions.includes(forbidden));for(const state of Object.values(authorization.globalAuthorizationState))assert.equal(state,'NOT_AUTHORIZED');});
test('reports perform no cloud execution and contain no secret-shaped material',()=>{const made=build();for(const report of Object.values(made))assert.equal(report.performsCloudExecution,false);const serialized=JSON.stringify(made);assert.doesNotMatch(serialized,/CLOUDFLARE_API_TOKEN|Bearer\s+[A-Za-z0-9._-]+|-----BEGIN .*PRIVATE KEY-----/);assert.equal(made.summary.secretSafety,'PASS_NO_SECRET_SHAPED_MATERIAL');});
test('protected runtime and native surfaces have no diff',()=>{const paths=['index.html','js/app.js','manifest.json','service-worker.js','android','ios'];const changed=execFileSync('git',['diff','--name-only','--',...paths],{cwd:ROOT,encoding:'utf8'}).trim();assert.equal(changed,'');});
test('generated Montgomery gzip is ignored and governed staging rejects arbitrary untracked input',()=>{const {candidate}=build();assert.equal(candidate.montgomery.repositoryState,'GENERATED_UNTRACKED_IGNORED');assert.equal(candidate.arbitraryUntrackedAdmission,'DENIED_BY_GOVERNED_MANIFEST');const ignored=execFileSync('git',['check-ignore',candidate.montgomery.path],{cwd:ROOT,encoding:'utf8'}).trim();assert.equal(ignored,candidate.montgomery.path);});
