// Documented contracts only. This module has no fetch, XHR, Image URL or credential loader.
const staticRoot='https://static-map-tiles-api.arcgis.com/arcgis/rest/services/static-basemap-tiles-service/v1';
const freeze=o=>Object.freeze(o);
export const ARCGIS_CONTRACTS=freeze({
 standard:freeze({id:'standard',service:'Static Basemap Tiles',privilege:'premium:user:staticbasemaptiles',url:staticRoot+'/arcgis/streets/static/tile/{z}/{y}/{x}',tileSize:512,zoomOffset:-1,attribution:'Powered by Esri · Esri, TomTom, Garmin, FAO, NOAA, USGS, OpenStreetMap contributors and the GIS User Community'}),
 imagery:freeze({id:'imagery',service:'Basemap Styles',privilege:'premium:user:basemaps',styleUrl:'https://basemapstyles-api.arcgis.com/arcgis/rest/services/styles/v2/webmaps/arcgis/imagery/standard',url:'https://ibasemaps-api.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',tileSize:256,zoomOffset:0,attribution:'Powered by Esri · Imagery source attribution must come from reviewed service metadata before live activation'}),
 labels:freeze({id:'labels',service:'Static Basemap Tiles',privilege:'premium:user:staticbasemaptiles',url:staticRoot+'/arcgis/imagery/labels/static/tile/{z}/{y}/{x}',tileSize:512,zoomOffset:-1,attribution:'Esri, TomTom, Garmin, FAO, NOAA, USGS, OpenStreetMap contributors and the GIS User Community'})
});
// A future policy proposal, never applied to server headers or used to connect.
export const FUTURE_NETWORK_POLICY=freeze({activation:false,referrerPolicy:'strict-origin-when-cross-origin',imageOrigins:freeze(['https://static-map-tiles-api.arcgis.com','https://ibasemaps-api.arcgis.com']),metadataOrigins:freeze(['https://static-map-tiles-api.arcgis.com','https://basemapstyles-api.arcgis.com','https://ibasemaps-api.arcgis.com']),requiresSeparateApproval:true});
export function liveProvider(){throw Error('Live ArcGIS activation disabled; credentials are not accepted');}
export function tileContract(id,c){const p=ARCGIS_CONTRACTS[id];if(!p||!c||Object.keys(c).sort().join(',')!=='x,y,z'||!Number.isInteger(c.z)||c.z<5||c.z>18||!Number.isInteger(c.x)||!Number.isInteger(c.y)||c.x<0||c.y<0||c.x>=2**(c.z+p.zoomOffset)||c.y>=2**(c.z+p.zoomOffset))throw Error('Invalid offline tile contract');return freeze({url:p.url.replace('{z}',String(c.z+p.zoomOffset)).replace('{y}',String(c.y)).replace('{x}',String(c.x)),level:c.z+p.zoomOffset,row:c.y,column:c.x,tileSize:p.tileSize,privilege:p.privilege});}
const statuses=freeze({200:'available',401:'missing-or-invalid-authorization',403:'access-denied',404:'missing-coverage',498:'expired-or-invalid-authorization',499:'missing-authorization',503:'service-unavailable'});
export function fixturePlan(id,configuration={}){
 if(!['arcgis-standard-fixture','arcgis-satellite-fixture'].includes(id)||!configuration||Object.getPrototypeOf(configuration)!==Object.prototype||Object.keys(configuration).some(k=>!['standard','imagery','labels'].includes(k)))throw Error('Only local synthetic fixture configuration accepted');
 for(const status of Object.values(configuration))if(typeof status!=='number'||!Object.hasOwn(statuses,status))throw Error('Invalid local fixture status');
 const base=id==='arcgis-standard-fixture'?'standard':'imagery',baseStatus=configuration[base]??200,labelStatus=configuration.labels??200,available=baseStatus===200;
 return freeze({id,base,baseStatus,labelStatus,health:available?(base==='imagery'&&labelStatus!==200?'degraded':'fixture-ready'):'unavailable',reason:statuses[baseStatus],labels:base==='imagery'&&available?(labelStatus===200?'available':statuses[labelStatus]):'not-rendered',activation:false,operationalGeometry:false,attribution:'LOCAL SYNTHETIC ARCGIS CONTRACT FIXTURE · Not real geography or satellite imagery · '+ARCGIS_CONTRACTS[base].attribution,coverage:'Synthetic fixture only; real geographic coverage is unverified'});
}
export function createArcgisFixtureBasemap(L,map,{id,configuration={},onState=()=>{}}){
 const plan=fixturePlan(id,configuration),layers=[];let disposed=false;const emit=state=>{if(!disposed)onState({...plan,...state});};emit(plan);
 if(plan.health==='unavailable')return {destroy(){disposed=true;},restyle(){},refresh(){}};
 function add(kind){const contract=ARCGIS_CONTRACTS[kind];const Tiles=L.GridLayer.extend({createTile(coords,done){const tile=document.createElement('canvas');tile.dataset.arcgisFixture=kind;tile.setAttribute('aria-hidden','true');tile.width=tile.height=contract.tileSize;queueMicrotask(()=>{if(disposed)return;const ctx=tile.getContext('2d');if(!ctx){emit({health:'unavailable',reason:'fixture-render-failed'});done(Error('Local fixture canvas unavailable'),tile);return;}if(kind!=='labels'){ctx.fillStyle=kind==='imagery'?'#496565':'#e8eeee';ctx.fillRect(0,0,tile.width,tile.height);}ctx.fillStyle=kind==='imagery'?'#ffffff':'#344b50';ctx.font='14px sans-serif';ctx.fillText(kind==='labels'?'SYNTHETIC LABELS OVERLAY':'SYNTHETIC '+kind.toUpperCase()+' FIXTURE',12,24);ctx.fillText('No real geographic data',12,44);done(null,tile);});return tile;}});const layer=new Tiles({tileSize:contract.tileSize,minZoom:5,maxZoom:18,noWrap:true,keepBuffer:1,updateWhenIdle:true,pane:'tilePane'});layers.push(layer);layer.addTo(map);}
 add(plan.base);if(plan.base==='imagery'&&plan.labels==='available')add('labels');
 const coverage=()=>{const b=map.getBounds();if(b.getWest()<-180||b.getEast()>180||b.getSouth()<-85.051129||b.getNorth()>85.051129)emit({health:'unavailable',reason:'missing-coverage'});};map.on('moveend',coverage);coverage();
 return {destroy(){if(disposed)return;disposed=true;map.off('moveend',coverage);for(const layer of layers)layer.remove();},restyle(){},refresh(){coverage();}};
}
