import {generateOccurrences,changedDates} from './notice-schedule.mjs';
import {DATASET_HASH} from './road-selection.mjs';
export const ORGANIZATION='DEMO-DAYTON',VERSION=1;
const fail=m=>{throw new Error(m);};
export const storageKey=unit=>'gridlyDispatchNoticePreview.v1.'+ORGANIZATION+'.'+unit;
export function emptyWorkspace(unit){if(!['police','works'].includes(unit))fail('No synthetic membership for this unit.');return {version:VERSION,dataset:DATASET_HASH,organization:ORGANIZATION,unit,notices:[],working:null};}
export function newNotice(unit,id='DEMO-NOTICE-'+crypto.randomUUID()){const schedule={mode:'weekdays',weekdays:[1,2,3,4,5],startTime:'06:00',endTime:'16:00',exceptions:{}};return {id,organization:ORGANIZATION,unit,dataset:DATASET_HASH,revision:0,status:'DRAFT',subject:'',body:'',reference:'',selected:[],effective:'2026-10-09T00:00',expiry:'2026-10-16T00:00',project:{start:'2026-10-09',end:'2026-10-15',timezone:'America/Chicago'},work:structuredClone(schedule),restrictionChoice:'',restriction:structuredClone(schedule),workOccurrences:[],restrictionOccurrences:[],history:[]};}
const bounded=(v,n)=>typeof v==='string'&&v.length<=n;
function shape(n,unit,registry){if(!n||n.organization!==ORGANIZATION||n.unit!==unit||n.dataset!==DATASET_HASH||!/^DEMO-NOTICE-[a-zA-Z0-9-]{1,80}$/.test(n.id)||!Number.isInteger(n.revision)||n.revision<0||!['DRAFT','CLOSED'].includes(n.status)||!bounded(n.subject,160)||!bounded(n.body,1000)||!bounded(n.reference,240)||!bounded(n.effective,16)||!bounded(n.expiry,16)||!n.project||!bounded(n.project.start,10)||!bounded(n.project.end,10)||!bounded(n.project.timezone,80)||!n.work||!n.restriction||!Array.isArray(n.history)||n.history.length>100)fail('Malformed or out-of-scope preview draft.');if(n.restrictionChoice!==undefined&&!['','work','continuous','custom'].includes(n.restrictionChoice))fail('Malformed restriction choice.');registry.selected(n.selected);for(const s of [n.work,n.restriction]){if(!['once','weekdays','continuous'].includes(s.mode)||!Array.isArray(s.weekdays)||s.weekdays.length>7||s.weekdays.some(d=>!Number.isInteger(d)||d<0||d>6)||!bounded(s.startTime,5)||!bounded(s.endTime,5)||!s.exceptions||typeof s.exceptions!=='object'||Array.isArray(s.exceptions)||Object.keys(s.exceptions).length>366)fail('Malformed draft schedule.');for(const [d,e]of Object.entries(s.exceptions)){if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||!e||!['skip','modify'].includes(e.kind)||(e.kind==='modify'&&(!bounded(e.startTime,5)||!bounded(e.endTime,5))))fail('Malformed draft exception.');}}}
export function validateNotice(n,registry){shape(n,n.unit,registry);if(!n.subject.trim()||!n.body.trim()||!n.selected.length)fail('Add at least one source line, a subject and notice text.');return buildNotice(n);}
import {wallInstant} from './notice-schedule.mjs';
// Optional choice keeps v1 snapshots readable without rewriting history.
// Custom hours survive toggling; matching uses actual work exceptions.
export function effectiveRestriction(n){if(n.restrictionChoice==='')fail('Choose when the roadway will be affected.');if(n.restrictionChoice==='work')return structuredClone(n.work);if(n.restrictionChoice==='continuous')return {...structuredClone(n.restriction),mode:'continuous'};return structuredClone(n.restriction);}
export function buildNotice(n){const workOccurrences=generateOccurrences(n.project,n.work),restrictionOccurrences=generateOccurrences(n.project,effectiveRestriction(n));if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(n.effective)||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(n.expiry))fail('Specify notice effective and expiry wall times.');const effectiveInstant=wallInstant(n.effective.slice(0,10),n.effective.slice(11),n.project.timezone),expiryInstant=wallInstant(n.expiry.slice(0,10),n.expiry.slice(11),n.project.timezone);if(expiryInstant<=effectiveInstant)fail('Notice expiry must be later than its effective time.');for(const o of [...workOccurrences,...restrictionOccurrences])if(o.start<effectiveInstant||o.end>expiryInstant)fail('Notice validity must contain every work and restriction occurrence.');return {...structuredClone(n),workOccurrences,restrictionOccurrences,effectiveInstant,expiryInstant};}
export function loadWorkspace(storage,unit,registry){const empty=emptyWorkspace(unit),raw=storage.getItem(storageKey(unit));if(raw===null)return empty;if(raw.length>2000000)fail('Preview storage exceeds its limit.');let w;try{w=JSON.parse(raw);}catch{fail('Preview storage is malformed. Reset explicitly to continue.');}if(w?.version!==VERSION||w.dataset!==DATASET_HASH||w.organization!==ORGANIZATION||w.unit!==unit||!Array.isArray(w.notices)||w.notices.length>30||new Set(w.notices.map(n=>n.id)).size!==w.notices.length)fail('Stale or malformed preview storage. Reset explicitly to continue.');for(const n of w.notices){shape(n,unit,registry);const rebuilt=validateNotice(n,registry);if(JSON.stringify(rebuilt.workOccurrences)!==JSON.stringify(n.workOccurrences)||JSON.stringify(rebuilt.restrictionOccurrences)!==JSON.stringify(n.restrictionOccurrences)||rebuilt.effectiveInstant!==n.effectiveInstant||rebuilt.expiryInstant!==n.expiryInstant||n.revision!==n.history.length)fail('Stored schedule or revision history is inconsistent.');for(let i=0;i<n.history.length;i++){const h=n.history[i];if(!h||typeof h.at!=='string'||!Number.isFinite(Date.parse(h.at))||!h.changes||!Array.isArray(h.changes.work)||!Array.isArray(h.changes.restriction)||JSON.stringify(h.changes)!==JSON.stringify(reviewChanges(i?n.history[i-1].snapshot:null,h.snapshot))||h.revision!==i+1||h.snapshot?.id!==n.id||h.snapshot?.unit!==unit||h.snapshot?.organization!==ORGANIZATION||h.snapshot?.dataset!==DATASET_HASH||h.snapshot?.revision!==i+1)fail('Malformed revision history.');const previous=validateNotice({...h.snapshot,history:[]},registry);if(JSON.stringify(previous.workOccurrences)!==JSON.stringify(h.snapshot.workOccurrences)||JSON.stringify(previous.restrictionOccurrences)!==JSON.stringify(h.snapshot.restrictionOccurrences))fail('Malformed historical occurrences.');}}for(const n of w.notices){const snapshot=structuredClone(n);delete snapshot.history;if(JSON.stringify(snapshot)!==JSON.stringify(n.history.at(-1)?.snapshot))fail('Latest revision does not match its saved snapshot.');}if(w.working)shape(w.working,unit,registry);return w;}
export function preserveWorking(storage,w,n){shape(n,w.unit,{selected:ids=>{if(!Array.isArray(ids)||ids.length>50)fail('Invalid working selection.');}});const currentRaw=storage.getItem(storageKey(w.unit));if(currentRaw){const current=JSON.parse(currentRaw);if(JSON.stringify(current.notices)!==JSON.stringify(w.notices))fail('Saved draft changed elsewhere. Unsaved edits remain in this editor; reopen the current revision before saving.');}const next={...w,working:structuredClone(n)};const bytes=JSON.stringify(next);if(bytes.length>2000000)fail('Preview storage limit reached; current saved drafts remain unchanged.');storage.setItem(storageKey(w.unit),bytes);return next;}
export function reviewChanges(previous,next){return {work:changedDates(previous?.workOccurrences,next.workOccurrences),restriction:changedDates(previous?.restrictionOccurrences,next.restrictionOccurrences)};}
export function saveNotice(storage,unit,registry,n,expectedRevision,close=false){const w=loadWorkspace(storage,unit,registry),old=w.notices.find(v=>v.id===n.id);if((old?.revision||0)!==expectedRevision||old?.status==='CLOSED')fail('Stale revision or closed draft. Unsaved edits retained; reopen the current revision.');if(w.notices.length>=30&&!old)fail('Limit of 30 synthetic notices reached.');if((old?.revision||0)>=100)fail('Revision limit reached.');shape(n,unit,registry);const next=validateNotice(n,registry);next.revision=expectedRevision+1;next.status=close?'CLOSED':'DRAFT';const snapshot=structuredClone(next);delete snapshot.history;next.history=[...(old?.history||[]),{revision:next.revision,at:new Date().toISOString(),changes:reviewChanges(old,next),snapshot}];w.notices=w.notices.filter(v=>v.id!==next.id).concat(next);w.working=null;const bytes=JSON.stringify(w);if(bytes.length>2000000)fail('Preview storage limit reached; current saved drafts remain unchanged.');storage.setItem(storageKey(unit),bytes);return {workspace:w,notice:next};}
export function overlapNotices(n,notices){return notices.filter(o=>o.id!==n.id&&o.status!=='CLOSED'&&o.selected.some(id=>n.selected.includes(id))&&o.effectiveInstant<n.expiryInstant&&n.effectiveInstant<o.expiryInstant).map(o=>o.id);}
