import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildReport, serializeReport, outputs, STATUSES} from '../../tools/lp185/build-post-preview-reconciliation.mjs';

const r=buildReport();
const byId=Object.fromEntries(r.launchGates.map(g=>[g.id,g]));
test('preserves LP183.7 preview while keeping every global authority closed',()=>{assert.equal(r.protectedPreviewStatus.status,'COMPLETE');assert.equal(r.protectedPreviewStatus.requiresRedeployment,false);assert.match(r.declaration,/DOES NOT AUTHORIZE PUBLIC LAUNCH/);assert.ok(Object.values(r.globalAuthorizationState).every(x=>x==='NOT_AUTHORIZED'));});
test('covers all 18 deterministically ordered reconciliation areas with governed statuses',()=>{assert.equal(r.launchGates.length,18);assert.deepEqual(r.launchGates.map(g=>g.id),Array.from({length:18},(_,i)=>`LP185-G${String(i+1).padStart(2,'0')}`));for(const g of r.launchGates){assert.ok(STATUSES.includes(g.status));for(const k of ['name','category','blockingStoreSubmission','blockingPublicLaunch','evidence','remainingActions','ownerDependency','platformDependency','legalDependency','physicalDeviceDependency','notes'])assert.ok(k in g);}});
test('external evidence remains fail closed and platforms are independent',()=>{assert.equal(r.storeSubmissionReadiness.Apple.status,'NOT_READY');assert.equal(r.storeSubmissionReadiness.Google.status,'NOT_READY');assert.notDeepEqual(r.storeSubmissionReadiness.Apple.blockingGateIds,r.storeSubmissionReadiness.Google.blockingGateIds);assert.equal(byId['LP185-G03'].status,'OWNER_ACTION_REQUIRED');assert.equal(byId['LP185-G02'].status,'ATTORNEY_OR_POLICY_REVIEW_REQUIRED');assert.equal(byId['LP185-G12'].status,'PLATFORM_ACTION_REQUIRED');});
test('browser validation and native source never become native release evidence',()=>{assert.equal(byId['LP185-G09'].status,'PHYSICAL_DEVICE_EVIDENCE_REQUIRED');assert.equal(byId['LP185-G10'].status,'PHYSICAL_DEVICE_EVIDENCE_REQUIRED');assert.match(byId['LP185-G07'].notes,/No release artifact/);assert.match(byId['LP185-G08'].notes,/No archive/);});
test('planned contacts, legal drafts and store assets are not upgraded',()=>{assert.match(byId['LP185-G03'].notes,/not operational evidence/);assert.match(byId['LP185-G02'].notes,/not attorney approval/);assert.match(byId['LP185-G11'].notes,/does not prove compliance/);});
test('statewide classification uses actual manufacturing and runtime counts',()=>{const text=byId['LP185-G15'].evidence.concat(byId['LP185-G15'].notes).join(' ');for(const fact of ['254','28','11','zero'])assert.match(text,new RegExp(fact,'i'));assert.equal(byId['LP185-G15'].status,'PARTIALLY_COMPLETE');});
test('audit performs no prohibited operation and sequence grants no authority',()=>{for(const k of ['performsRuntimeChange','performsDeploymentChange','performsActivationChange','performsDistributionChange','performsStoreSubmission','protectedArtifactsModified'])assert.equal(r[k],false);assert.ok(r.proposedLaunchSequence.every(x=>x.grantsAuthorization===false));});
test('final classification is derived from unresolved gates',()=>{assert.ok(r.launchGates.some(g=>g.status!=='COMPLETE'));assert.equal(r.finalClassification,'POST_PREVIEW_RECONCILIATION_COMPLETE_LAUNCH_REQUIREMENTS_REMAIN');assert.equal(r.publicLaunchReadiness.status,'NOT_READY');});
test('one owner checklist covers every dependency class without requesting secrets',()=>{assert.equal(r.ownerChecklist.length,10);for(const term of ['attorney','mailbox','Apple','Google','subscription','sign','physical','metadata','production','authorization'])assert.match(JSON.stringify(r.ownerChecklist),new RegExp(term,'i'));const forbidden=/(password\s*[:=]|otp\s*[:=]|api[_-]?key\s*[:=]|private[_-]?key\s*[:=]|recovery[_-]?code\s*[:=])/i;assert.doesNotMatch(serializeReport(r),forbidden);});
test('generated outputs are byte deterministic, canonical UTF-8 LF, and committed copies match',()=>{assert.equal(serializeReport(buildReport()),serializeReport(buildReport()));for(const [file,content] of Object.entries(outputs())){const expected=Buffer.from(content,'utf8'),actual=fs.readFileSync(file);assert.equal(expected.includes(13),false);assert.notDeepEqual([...expected.subarray(0,3)],[0xef,0xbb,0xbf]);assert.deepEqual(actual,expected);}});
