import test,{before,after} from 'node:test';import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';import {randomBytes,randomUUID} from 'node:crypto';import {createRequire} from 'node:module';import {readFileSync,writeFileSync} from 'node:fs';
import {deliveryRepository} from './delivery-repository.mjs';
const require=createRequire(new URL('./package.json',import.meta.url));const {Pool}=require('pg');
const project=process.env.P29_PROJECT_ID,docker=process.env.P29_DOCKER;
if(process.env.P29_API_URL!=='http://127.0.0.1:54321'||!/^gridly-dispatch-phase29-[a-f0-9]{12}$/.test(project??''))throw Error('LOCAL_DISPOSABLE_ONLY');
const admin=sql=>execFileSync(docker,['exec','-i','supabase_db_'+project,'psql','-X','-At','-v','ON_ERROR_STOP=1','-U','postgres','-d','postgres'],{input:sql,encoding:'utf8',stdio:['pipe','pipe','pipe']});
let pool;const password=randomBytes(32).toString('hex');const checks=[];
before(async()=>{admin(readFileSync(new URL('./database-principal.local.sql',import.meta.url),'utf8'));admin("ALTER ROLE dispatch_delivery_connection PASSWORD '"+password+"';");pool=new Pool({host:'127.0.0.1',port:54322,database:'postgres',user:'dispatch_delivery_connection',password,max:1,connectionTimeoutMillis:3000,query_timeout:5000});await pool.query('SELECT 1')});
after(async()=>{await pool?.end();writeFileSync(process.env.P29_EVIDENCE_DIR+'/worker-principal-results.json',JSON.stringify({status:checks.length===10?'PASS':'FAIL',passed:checks.length,failed:10-checks.length,checks},null,2))});
async function withClient(fn){const c=await pool.connect();try{return await fn(c)}finally{try{await c.query('ROLLBACK')}catch{}c.release()}}
test('narrow real login and role attributes',async()=>{const r=await pool.query("SELECT current_user,rolinherit,rolbypassrls,rolsuper,rolcreatedb,rolcreaterole,rolreplication FROM pg_roles WHERE rolname=current_user");assert.equal(r.rows[0].current_user,'dispatch_delivery_connection');for(const k of ['rolinherit','rolbypassrls','rolsuper','rolcreatedb','rolcreaterole','rolreplication'])assert.equal(r.rows[0][k],false);checks.push('login attributes')});
test('no direct private/Auth/audit/candidate table access',async()=>{for(const table of ['dispatch_private.invitation_delivery_attempts','dispatch_audit.invitation_delivery_events','auth.users','dispatch_private.publication_reviews'])await assert.rejects(()=>pool.query('SELECT * FROM '+table+' LIMIT 1'),e=>e.code==='42501');checks.push('private Auth audit candidate refusal')});
test('cannot assume unrelated command owner Auth or API roles',async()=>{for(const role of ['dispatch_function_owner','postgres','authenticated','service_role','supabase_auth_admin'])await withClient(async c=>{await c.query('BEGIN');await assert.rejects(()=>c.query('SET LOCAL ROLE '+role),e=>e.code==='42501')});checks.push('unrelated role refusal')});
test('no schema database role creation or object ownership',async()=>{for(const sql of ['CREATE SCHEMA worker_forbidden','CREATE DATABASE worker_forbidden','CREATE ROLE worker_forbidden','CREATE TABLE public.worker_forbidden(id int)'])await assert.rejects(()=>pool.query(sql),e=>e.code==='42501');const r=await pool.query("SELECT count(*)::int AS n FROM pg_class WHERE relowner=(SELECT oid FROM pg_roles WHERE rolname=current_user)");assert.equal(r.rows[0].n,0);checks.push('creation ownership refusal')});
test('allowed transport claim succeeds without table or issuance privilege',async()=>{await withClient(async c=>{await c.query('BEGIN');await c.query('SET LOCAL ROLE dispatch_delivery_transport');const r=await c.query('SELECT dispatch_private.invitation_claim_send($1::uuid) AS allowed',[randomUUID()]);assert.equal(r.rows[0].allowed,false);await assert.rejects(()=>c.query('SELECT * FROM dispatch_private.invitation_delivery_attempts'),e=>e.code==='42501')});await withClient(async c=>{await c.query('BEGIN');await c.query('SET LOCAL ROLE dispatch_delivery_transport');await assert.rejects(()=>c.query("SELECT dispatch_private.invitation_issue('{}'::jsonb)"),e=>e.code==='42501')});checks.push('bounded command only')});
test('transport result permitted but unknown correlation refuses safely',async()=>{await withClient(async c=>{await c.query('BEGIN');await c.query('SET LOCAL ROLE dispatch_delivery_transport');await assert.rejects(()=>c.query('SELECT dispatch_private.invitation_transport_result($1::jsonb)',[JSON.stringify({eventId:'synthetic-unknown',messageId:'unknown',status:'SENT',occurredAt:new Date().toISOString()})]),e=>e.code==='P0001'&&e.message==='DELIVERY_UNKNOWN')});checks.push('result permission and unknown refusal')});
test('transaction-local role resets after commit and pooled reuse',async()=>{let pid;await withClient(async c=>{pid=(await c.query('SELECT pg_backend_pid() AS pid')).rows[0].pid;await c.query('BEGIN');await c.query('SET LOCAL ROLE dispatch_delivery_transport');assert.equal((await c.query('SELECT current_user AS u')).rows[0].u,'dispatch_delivery_transport');await c.query('COMMIT');assert.equal((await c.query('SELECT current_user AS u')).rows[0].u,'dispatch_delivery_connection')});await withClient(async c=>{const r=(await c.query('SELECT current_user AS u,pg_backend_pid() AS pid')).rows[0];assert.equal(r.pid,pid);assert.equal(r.u,'dispatch_delivery_connection')});checks.push('commit pooled reset')});
test('rollback and timeout cannot leak assumed role',async()=>{await withClient(async c=>{await c.query('BEGIN');await c.query('SET LOCAL ROLE dispatch_delivery_transport');await c.query("SET LOCAL statement_timeout='30ms'");await assert.rejects(()=>c.query('SELECT pg_sleep(0.2)'),e=>e.code==='57014');await c.query('ROLLBACK');assert.equal((await c.query('SELECT current_user AS u')).rows[0].u,'dispatch_delivery_connection')});checks.push('timeout rollback reset')});

function actualRepository(){return deliveryRepository({GRIDLY_DISPATCH_DB_CACHING_DISABLED:'true',GRIDLY_DISPATCH_DB_TLS_REQUIRED:'true',DISPATCH_DELIVERY_DB:{connectionString:'postgres://dispatch_delivery_connection:synthetic@local.invalid/postgres?sslmode=verify-full'}},{createClient:()=>{let c;return{connect:async()=>{c=await pool.connect()},query:(...args)=>c.query(...args),end:async()=>c?.release()}}})}
test('actual repository uses login and resets pooled role after command refusal',async()=>{const r=actualRepository();assert.equal(await r.claim(randomUUID()),false);await assert.rejects(()=>r.event({eventId:'synthetic-repository-unknown',messageId:'unknown',status:'DELIVERED',occurredAt:new Date().toISOString()}),e=>e.message==='DELIVERY_UNAVAILABLE');assert.equal((await pool.query('SELECT current_user AS u')).rows[0].u,'dispatch_delivery_connection');checks.push('actual repository login reset')});
test('actual repository event succeeds deduplicates and leaves authorization unchanged',async()=>{const msg=admin("SELECT provider_message_id FROM dispatch_private.invitation_delivery_attempts WHERE provider_message_id IS NOT NULL LIMIT 1;").trim();assert.ok(msg);const before=admin('SELECT count(*) FROM dispatch_private.organization_memberships;');const e={eventId:'synthetic-repository-'+randomUUID(),messageId:msg,status:'SENT',occurredAt:new Date().toISOString()};const r=actualRepository();await r.event(e);await r.event(e);await assert.rejects(()=>r.event({...e,status:'BOUNCED'}),x=>x.code==='EVENT_CONFLICT');assert.equal(admin('SELECT count(*) FROM dispatch_private.organization_memberships;'),before);assert.equal((await pool.query('SELECT current_user AS u')).rows[0].u,'dispatch_delivery_connection');checks.push('actual repository persisted event dedup authorization separation')});