import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
const root=process.cwd(),out=path.join(root,'.artifacts/lp24449a');
const git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8'}).trim();
const branch=git('branch','--show-current'),head=git('rev-parse','HEAD');
if(branch!=='LP244.48-destination-quick-check-around-me'||head!=='02fe47fd1b76a4bd52d8f8487a96cdc8e5c804e8'||git('diff','HEAD','--name-only'))throw Error('Baseline mismatch or tracked changes');
fs.mkdirSync(out,{recursive:true});
if(fs.existsSync(path.join(out,'baseline.json')))throw Error('Baseline already captured; do not overwrite');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');
const files=[];const walk=p=>{for(const e of fs.readdirSync(path.join(root,p),{withFileTypes:true})){const f=p+'/'+e.name;if(e.isDirectory())walk(f);else files.push(f);}};
for(const p of ['tools/lp24449','reports/lp24449','.artifacts/lp24449'])walk(p);
for(const f of fs.readdirSync(path.join(root,'docs/launch')).filter(f=>f.startsWith('LP24449-')))files.push('docs/launch/'+f);
const protectedFiles=JSON.parse(fs.readFileSync(path.join(root,'.artifacts/lp24449/starting-integrity.json'),'utf8')).map(r=>({file:r.file,sha256:hash(r.file)}));
fs.writeFileSync(path.join(out,'baseline.json'),JSON.stringify({capturedAt:new Date().toISOString(),branch,head,status:git('status','--short'),protectedFiles,priorEvidence:files.map(file=>({file,sha256:hash(file)}))},null,2));
fs.copyFileSync(path.join(root,'js/app.js'),path.join(out,'baseline-app.js'));
const codes=['HOME_CHOICE_IDENTITY_BINDING_LOSS','HOME_MEMBERSHIP_WRONG_CONTEXT','HOME_BASELINE_WRONG_CONTEXT','MULTICOUNTY_WRONG_MEMBERSHIP','SEARCH_PUBLICATION_FAILED','SEARCH_NOT_FOUND','WEATHER_WRONG_LOCALITY'];
const ledger=JSON.parse(fs.readFileSync(path.join(root,'reports/lp24449/failure-ledger.json'),'utf8'));
const failures=ledger.filter(f=>codes.includes(f.code)).map((f,i)=>({originalFailureId:`LP24449-${String(i+1).padStart(4,'0')}`, ...f}));
fs.mkdirSync(path.join(root,'reports/lp24449a'),{recursive:true});
fs.writeFileSync(path.join(root,'reports/lp24449a/original-in-scope-failures.json'),JSON.stringify(failures,null,2));
console.log(JSON.stringify({branch,head,originalFailures:failures.length,counts:Object.fromEntries(codes.map(c=>[c,failures.filter(f=>f.code===c).length])),priorEvidenceFiles:files.length,protectedFiles:protectedFiles.length}));
