import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { execFileSync } from 'node:child_process';
import { ROOT, build } from '../../tools/lp1834/reassess-protected-preview.mjs';

test('current governed LP183.1 evidence supplies a Pages-compatible artifact identity',()=>{const made=build();const governed=JSON.parse(fs.readFileSync(`${ROOT}/reports/lp1831/deployable-artifact-manifest.json`));assert.equal(made.candidate.evidenceSource,'reports/lp1831/deployable-artifact-manifest.json');assert.equal(made.candidate.artifactIdentity,governed.artifactIdentity);assert.equal(made.candidate.oversizedFileCount,0);assert.equal(made.candidate.pagesCompatible,true);assert.ok(Object.values(made.candidate.exclusions).every(Boolean));});
test('generated Montgomery package is staged only through governance',()=>{const made=build();assert.equal(made.candidate.montgomery.presentInStagedArtifact,true);assert.equal(made.candidate.montgomery.repositoryState,'GENERATED_UNTRACKED_IGNORED');assert.equal(made.candidate.montgomery.arbitraryUntrackedAdmission,'DENIED_BY_GOVERNED_MANIFEST');assert.equal(made.candidate.binaryPullRequestBlocker,'NONE');});
test('Access facts retain their owner-provided external evidence boundary and tests remain pending',()=>{const {access}=build();assert.equal(access.evidenceBoundary,'OWNER_PROVIDED_MANUALLY_VERIFIED_NO_AUTHENTICATED_API_EVIDENCE');assert.equal(access.application.evidenceClass,'OWNER_VERIFIED_EXTERNAL_CONFIGURATION');assert.match(access.admissionTest.status,/NOT_RUN/);for(const denial of access.denialTests)assert.match(denial.status,/NOT_RUN/);});
test('absent Pages project and rollback limitations remain explicit',()=>{const made=build();assert.equal(made.pages.project.exists,false);assert.equal(made.pages.project.deployments,0);assert.match(made.rollback.firstDeployment.status,/NOT_EXECUTABLE/);assert.equal(made.rollback.knownGoodArtifactRollback.status,'NOT_YET_AVAILABLE');assert.equal(made.authorization.scopedExecutionAuthorization.granted,false);});
test('global authorizations remain closed and automatic deployment is forbidden',()=>{const made=build();for(const state of Object.values(made.authorization.globalAuthorizationState))assert.equal(state,'NOT_AUTHORIZED');assert.equal(made.pages.model,'DIRECT_UPLOAD');assert.equal(made.cloudExecution,undefined);for(const report of Object.values(made))assert.equal(report.performsCloudExecution,false);});
test('LP183.4 does not modify protected runtime or native surfaces',()=>{const protectedPaths=['index.html','js/app.js','manifest.json','service-worker.js','android','ios'];const changed=new Set(execFileSync('git',['diff','--name-only','--',...protectedPaths],{cwd:ROOT,encoding:'utf8'}).trim().split('\n').filter(Boolean));for(const item of protectedPaths)assert.ok(![...changed].some(file=>file===item||file.startsWith(`${item}/`)),item);});
