#!/usr/bin/env node
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repository = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const sources = Object.freeze({
  androidLegacyIcon: 'assets/icon-192.png',
  androidAdaptiveMark: 'assets/icons/incoming/gridly-icon-master-167.png',
  iosIcon: 'assets/store/icons/gridly-icon-master-1024.png',
  splash: 'assets/store/branding/Splash/gridly-splash-portrait.png'
});
export const outputs = Object.freeze({
  androidLegacyIcon: [
    'android/app/src/main/res/mipmap-anydpi/ic_launcher.png',
    'android/app/src/main/res/mipmap-anydpi/ic_launcher_round.png'
  ],
  androidAdaptiveMark: [
    'android/app/src/main/res/drawable-nodpi/ic_launcher_mark.png'
  ],
  iosIcon: [
    'ios/App/App/Assets.xcassets/AppIcon.appiconset/AppIcon-512@2x.png'
  ],
  splash: [
    'android/app/src/main/res/drawable/splash.png',
    'ios/App/App/Assets.xcassets/Splash.imageset/splash.png'
  ]
});

export const obsoleteOutputs = Object.freeze([
  'android/app/src/main/res/mipmap-anydpi/ic_launcher_foreground.png',
  'android/app/src/main/res/mipmap-anydpi/ic_launcher_mark.png',
  'android/app/src/main/res/mipmap-anydpi/ic_launcher_foreground.xml'
]);

async function writeTextIfChanged(destination, content) {
  const normalized = (value) => value.replace(/\r\n/g, '\n');
  try {
    if (normalized(await readFile(destination, 'utf8')) === normalized(content)) return false;
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  await writeFile(destination, content);
  return true;
}

export async function generateNativeAssets(outputRoot = repository) {
  // Converge checkouts generated by the former all-raster architecture with
  // clean checkouts. The adaptive foreground is now the XML derivative below.
  for (const path of obsoleteOutputs) {
    await rm(resolve(outputRoot, path), { force: true });
  }

  for (const [family, paths] of Object.entries(outputs)) {
    const source = resolve(repository, sources[family]);
    await readFile(source);
    for (const path of paths) {
      const destination = resolve(outputRoot, path);
      await mkdir(dirname(destination), { recursive: true });
      await copyFile(source, destination);
    }
  }
  // Adaptive launchers own the final mask. Keep the transparent, mark-only
  // authority distinct from the complete legacy tile and inset it into the
  // adaptive safe zone without rewriting its tracked binary bytes.
  const adaptiveForeground = resolve(outputRoot, 'android/app/src/main/res/drawable/ic_launcher_foreground.xml');
  await mkdir(dirname(adaptiveForeground), { recursive: true });
  await writeTextIfChanged(adaptiveForeground, `<?xml version="1.0" encoding="utf-8"?>\n<inset xmlns:android="http://schemas.android.com/apk/res/android" android:drawable="@drawable/ic_launcher_mark" android:inset="18%" />\n`);
}

const outputFlag = process.argv.indexOf('--output-root');
const outputRoot = outputFlag === -1 ? repository : resolve(process.argv[outputFlag + 1]);
await generateNativeAssets(outputRoot);
console.log(`Copied ${Object.values(outputs).flat().length} native raster assets and wrote one adaptive safe-zone XML resource from approved tracked Gridly artwork.`);
