<#
.SYNOPSIS
Creates the local-only Gridly DriveTexas API key configuration file.

.DESCRIPTION
Prompts privately for a DriveTexas API key, verifies js/gridly.local.js is ignored by Git,
and writes the safe local runtime configuration used by Gridly in the browser.
#>

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$localConfigRelativePath = "js/gridly.local.js"
$localConfigPath = Join-Path $repoRoot $localConfigRelativePath

function Invoke-Git {
  param(
    [Parameter(Mandatory = $true)]
    [string[]]$Arguments
  )

  $output = & git -C $repoRoot @Arguments 2>&1
  return [pscustomobject]@{
    ExitCode = $LASTEXITCODE
    Output = $output
  }
}

$ignoreCheck = Invoke-Git -Arguments @("check-ignore", "--quiet", $localConfigRelativePath)
if ($ignoreCheck.ExitCode -ne 0) {
  Write-Error "Refusing to continue: $localConfigRelativePath is not ignored by Git. Add it to .gitignore before storing a local DriveTexas key."
}

$trackedCheck = Invoke-Git -Arguments @("ls-files", "--error-unmatch", $localConfigRelativePath)
if ($trackedCheck.ExitCode -eq 0) {
  Write-Error "Refusing to continue: $localConfigRelativePath is tracked by Git. Remove it from tracking before storing a local DriveTexas key."
}

$secureKey = Read-Host -Prompt "Enter DriveTexas API key" -AsSecureString
if ($secureKey.Length -eq 0) {
  Write-Error "No DriveTexas API key was entered. No local config file was created."
}

$keyPointer = [IntPtr]::Zero
$plainKey = $null
try {
  $keyPointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureKey)
  $plainKey = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($keyPointer)

  if ([string]::IsNullOrWhiteSpace($plainKey)) {
    Write-Error "No DriveTexas API key was entered. No local config file was created."
  }

  $encodedKey = ConvertTo-Json -InputObject $plainKey -Compress
  $content = @"
// Local-only Gridly DriveTexas configuration.
// Generated by tools/Setup-GridlyLocalDriveTexas.ps1.
// This file is intentionally gitignored. Do not commit real API keys.
window.GRIDLY_TXDOT_API_KEY = $encodedKey;
window.GRIDLY_CONFIG = window.GRIDLY_CONFIG || {};
window.GRIDLY_CONFIG.txdot = window.GRIDLY_CONFIG.txdot || {};
window.GRIDLY_CONFIG.txdot.apiKey = window.GRIDLY_TXDOT_API_KEY || "";
"@

  New-Item -ItemType Directory -Path (Split-Path $localConfigPath -Parent) -Force | Out-Null
  Set-Content -Path $localConfigPath -Value $content -Encoding UTF8
}
finally {
  if ($keyPointer -ne [IntPtr]::Zero) {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($keyPointer)
  }
  $plainKey = $null
  $secureKey.Dispose()
}

$finalIgnoreCheck = Invoke-Git -Arguments @("check-ignore", "--quiet", $localConfigRelativePath)
if ($finalIgnoreCheck.ExitCode -ne 0) {
  Remove-Item -Path $localConfigPath -Force -ErrorAction SilentlyContinue
  Write-Error "Refusing to keep the local config: $localConfigRelativePath is not ignored by Git. The file was removed."
}

$finalTrackedCheck = Invoke-Git -Arguments @("ls-files", "--error-unmatch", $localConfigRelativePath)
if ($finalTrackedCheck.ExitCode -eq 0) {
  Remove-Item -Path $localConfigPath -Force -ErrorAction SilentlyContinue
  Write-Error "Refusing to keep the local config: $localConfigRelativePath is tracked by Git. The file was removed."
}

Write-Host "Created $localConfigRelativePath."
Write-Host "Confirmed $localConfigRelativePath is gitignored."
Write-Host "Confirmed $localConfigRelativePath is not tracked by Git."
Write-Host "Final instruction: refresh Gridly."
