plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gridlygo.gridly'
    compileSdk 36

    defaultConfig {
        applicationId 'com.gridlygo.gridly'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies {
    implementation project(':capacitor-android')
}
