import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {build,encode,validateEvidence,verify} from '../../tools/lp171/operational-closure.mjs';
const empty={schemaVersion:1,records:[]};
test('missing evidence fails closed while rehearsals remain distinct',()=>{const r=build(undefined,empty);assert.equal(r['operational-evidence-closure-summary.json'].overallClassification,'NOT_READY');assert.equal(r['monitoring-evidence-closure.json'].classification,'SOURCE_UNAVAILABLE');assert.equal(r['backup-evidence-closure.json'].configuredBackupDoesNotCertifyRestoration,true);assert.equal(r['restoration-rehearsal.json'].classification,'REHEARSAL_PASS');assert.equal(r['restoration-rehearsal.json'].productionRestorationStatus,'NOT_TESTED');assert.equal(r['rollback-rehearsal.json'].productionRollbackStatus,'NOT_TESTED')});
test('partial evidence and logs cannot certify monitoring alerting',()=>{const r=build(undefined,{schemaVersion:1,records:[{identifier:'MONITORING:APPLICATION_AVAILABILITY:SIGNALSOURCE',classification:'PARTIAL_EVIDENCE',sourceSystem:'OWNER',method:'ATTESTATION',readOnly:true,metadataOnly:true,attestation:'LOG_EXISTS'}]});assert.notEqual(r['monitoring-evidence-closure.json'].signals[0].classification,'PASS');assert.equal(r['monitoring-evidence-closure.json'].logsDoNotCertifyAlerting,true)});
test('unknown owners and launch checklist remain fail closed',()=>{const r=build(undefined,empty);assert.equal(r['incident-response-closure.json'].classification,'OWNER_ACTION_REQUIRED');assert.equal(r['launch-day-runbook-readiness.json'].authorizesLaunch,false);assert.ok(Object.values(r['authorization-state.json'].authorization).every(x=>x==='NOT_AUTHORIZED'))});
test('unsafe input is rejected without echo',()=>{const value='password'+'=do-not-echo';assert.throws(()=>validateEvidence({schemaVersion:1,records:[{identifier:'X',classification:'PASS',readOnly:true,metadataOnly:true,attestation:value}]}),e=>!e.message.includes('do-not-echo'))});
test('rehearsals contain no production operation',()=>{const r=build(undefined,empty),ops=r['operational-evidence-closure-summary.json'].operationsPerformed;assert.ok(Object.values(ops).every(x=>x===0));assert.equal(r['rollback-rehearsal.json'].workflowTriggered,false);assert.equal(r['restoration-rehearsal.json'].productionTargetContacted,undefined);assert.equal(r['restoration-rehearsal.json'].proof.productionTargetContacted,false)});
test('stable ordering, canonical encoding, and git blobs are deterministic',()=>{const a={schemaVersion:1,records:[]},b={records:[],schemaVersion:1};assert.equal(encode(a),encode(b));assert.ok(!encode(a).includes('\r'));assert.notEqual(encode(a).charCodeAt(0),0xfeff);assert.equal(build(undefined,empty)['protected-artifact-verification.json'].classification,'PASS');assert.equal(verify(),true)});
test('owner capture source contains only read-only CLI operations',()=>{const ps=fs.readFileSync(new URL('../../tools/lp171/capture-owner-evidence.ps1',import.meta.url),'utf8').toLowerCase();for(const forbidden of ['workflow run','functions deploy','db reset','db push','storage rm','git push'])assert.equal(ps.includes(forbidden),false)});
